### ISSUE TITLE
Make it easier to set the USER_CONFIG object

### ISSUE THREAD

**Issue by Ankcorn** [cube-js/cube.js#1001]
**Is your feature request related to a problem? Please describe.**
Setting it to the authInfo.u object was a little mystical until we found what to do in the docs

**Describe the solution you'd like**

A setUserContext function that is called after checkAuth. 

The 1st argument contains the return value of the checkAuth function

```javascript
CubejsServerCore.create({
  setUserContext: (authInfo) => ({ a: authInfo.a, b: authInfo.b })
});

```

**Comment by paveltiunov** [comment]
@Ankcorn Hey Thomas! Thanks for posting this!

**Comment by hassankhan** [comment]
Hi @Ankcorn :wave: 

Just wondering if this is still an issue for you? We've since overhauled the docs, including a new [Authentication section](https://cube.dev/docs/security). Would love to hear your feedback, if any 😀

**Comment by Ankcorn** [comment]
Nope! The new playground features totally take care of this in a better way than I came up with! :)

I am going to close this! 🥳 
Thanks, Hassan
