### ISSUE TITLE
pre-aggregations not supported by clickhouse

### ISSUE THREAD

**Issue by baldurgaldur** [cube-js/cube.js#1004]
**Describe the bug**
Unable to use pre-aggregations when using Clickhouse

**To Reproduce**
1. Run cubejs docker container on the same network as an container running ClickHouse server version 19.17.8 revision 54428.
2. Create a schema with preAggregation
3. Make a request that can be answered using the preAggregation.
4. Cubejs logs the following error:
`Error: Incorrect CREATE query: ENGINE required (version 19.17.8.54 (official build))
    at parseError (/usr/src/app/node_modules/@apla/clickhouse/src/parse-error.js:2:15)
    at errorHandler (/usr/src/app/node_modules/@apla/clickhouse/src/clickhouse.js:29:13)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/@apla/clickhouse/src/clickhouse.js:97:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Expected behavior**
A new table inserted into CH where the structure follows the defined preAggregation.

**Screenshots**

**Version:**
"@cubejs-backend/clickhouse-driver": "^0.15.0",
"@cubejs-backend/server": "^0.15.3"

**Comment by gudjonragnar** [comment]
Have you tried bumping the version of cube? I see that some improvements were made to the `ClickHouseQuery.js` recently regarding pre-aggregation:
```
preAggregationLoadSql(cube, preAggregation, tableName) {
    const sqlAndParams = this.preAggregationSql(cube, preAggregation);
    if (!preAggregation.indexes) {
      throw new UserError(`ClickHouse doesn't support pre-aggregations without indexes`);
    }
    const firstIndexName = Object.keys(preAggregation.indexes)[0];
    const indexColumns = this.evaluateIndexColumns(cube, preAggregation.indexes[firstIndexName]);
    return [`CREATE TABLE ${tableName} ENGINE = MergeTree() ORDER BY ${indexColumns.join(', ')} ${this.asSyntaxTable} ${sqlAndParams[0]}`, sqlAndParams[1]];
  }
```

**Comment by baldurgaldur** [comment]
Seems to work in v0.19.61
