### ISSUE TITLE
Pre-filter before joining cubes

### ISSUE THREAD

**Issue by gudjonragnar** [cube-js/cube.js#1010]
**Problem**

Is there a way for me to pre-filter the cube that I am joining (the right cube in the join)?

**Example Cube.js schema**
```javascript
cube(`CubeA`, {
  sql: `select * from tableA`,
  joins: {
    CubeB: {
      relationship: `hasMany`,
      sql: `${CubeA}.some_id = ${CubeB}.other_id`,
    },
  },

  dimensions: {
    some_id: {
      sql: `some_id`,
      type: `string`,
      primaryKey: true,
      shown: true,
    }, 
    property_A: {
      sql: `propertyA`,
      type: `string`  
    }
})
```

If I make a query that executes the join and have a dimension filter on `property_1` then the filtering will be done after the join. Something like:
```sql
SELECT * FROM
(
  select * from tableA
) LEFT JOIN (
  select * from tableB
) ON A.some_id = B.other_id
WHERE propertyB = 'asdf`
```

I would however like to get a generated sql that looks something like:
```sql
SELECT * FROM
(
  select * from tableA
) LEFT JOIN (
  select * from tableB
  WHERE propertyB = 'asdf`
) ON A.some_id = B.other_id
```

I am using ClickHouse, if that matters.

**Comment by vasilev-alex** [comment]
Hi @gudjonragnar!

You can add a `where` clause to the sql

```
sql: `select * from tableB where propertyB = 'asdf'`,
```

**Comment by gudjonragnar** [comment]
@vasilev-alex Thanks for the answer but I guess I was not clear enough in my example. The value of propertyB is variable (think datetime filtering), not a constant.

**Comment by paveltiunov** [comment]
@gudjonragnar It would be helpful if you provide names of business/domain specific entities. It's hard to guess what problem you're facing without this knowledge. Most probably solution lies in fact table modelling and not filtering as it usually turns out for analytics problems.

**Comment by gudjonragnar** [comment]
Alright, sorry about that. 
```javascript
cube(`Tickets`, {
  sql: `SELECT  entity_ref, 
      argMax(seat_location_section, snapshot_time) as section ,
      argMax(subtenant, snapshot_time) as subtenant 
        from entities prewhere archetype='Product' and archetype_variant ='Ticket'
      group by entity_ref`,

  joins: {
    Transactions: {
      relationship: `hasMany`,
      sql: `${Tickets}.entity_ref = ${Transactions}.ticket_ref`,
    },
  },
  dimensions: {...}
```
This Is the cube I am looking at. In it we are matching tickets to purchase transactions.
The transactions cube is 
```javascript
cube(`Transactions`, {
  sql: `SELECT * FROM transactions WHERE  product_archetype = 'Product' AND product_archetype_variant = 'Event'`,
  dimensions: {...},
```
Both of these tables are large on their own which is why it is beneficiary to apply dimension filters before the join takes place (pre-filtering). 
One of our queries is 
```javascript
{
  "dimensions":["Tickets.section"],
  "measures":["Transactions.customers","Transactions.itemCount","Transactions.revenue"],
  "timeDimensions":[{"dimension":"Transactions.occurredAt","dateRange":["2020-07-01T00:00:00.000Z","2020-07-31T23:59:59.999Z"]}],
  "filters":[{"operator":"in","dimension":"Transactions.type","values":["purchased","cancelled"]}]}
```
and the generated sql is something like this:
```sql
SELECT * FROM
(
  SELECT  entity_ref, 
      argMax(seat_location_section, snapshot_time) as section ,
      argMax(subtenant, snapshot_time) as subtenant 
        from entities prewhere archetype='Product' and archetype_variant ='Ticket'
      group by entity_ref
) AS tickets LEFT JOIN (
  select * from transactions where product_archetype = 'Product'
) AS transactions ON tickets.entity_ref = transactions.ticket_ref
WHERE occurred_at > 'some-date' AND occurred_at < 'other-date' AND transactions.type in ('purchased', 'cancelled')
```
This query takes too long to run because of the size of the data. By moving the last line (the where clause for the join) into the transaction selection so it becomes
```sql
select * from transactions
WHERE product_archetype = 'Product' AND occurred_at > 'some-date' AND occurred_at < 'other-date' AND transactions.type in ('purchased', 'cancelled')
```
the query execution time is reduced dramatically.
We are using the `Transactions` cube in other joins across our application and in those cases we have different filters. Because of that the `FILTER_PARAMS` solution would not work across the application, unless we create a set of essentially duplicate cubes each with their own `FILTER_PARAMS` filters. 
 
Hopefully this gives you some more insight into the issue. 

I would think that it would be beneficial overall to narrow down the sets of rows before the join is made instead of afterwards in almost all cases, and especially when the tables are big. I would also think that providing this dynamically in the query (with some restrictions) would be a strong feature to have.

**Comment by paveltiunov** [comment]
@gudjonragnar There's an experimental flag `rewriteQueries`. You can try to apply it so it can push your filters up to joins. It can be enabled using
```javascript
cube(`Tickets`, {
  rewriteQueries: true,
  // ...
```

**Comment by gudjonragnar** [comment]
Thanks @paveltiunov however, Clickhouse only supports join on clauses with equal sign, so that doesn't work for us since we cant filter on dates within a range that way.

**Comment by paveltiunov** [comment]
In this way, the only way I see is to put SQL for the join inside `cube.sql` param and materialize join as a whole.

**Comment by gudjonragnar** [comment]
Alright, thanks for the help. I will close the issue.
