### ISSUE TITLE
Suggest filter values in a dropdown

### ISSUE THREAD

**Issue by meymuthu** [cube-js/cube.js#1016]
**Problem**

How do I add a filter in cube.js from a field from database? I have a postgresql table with a field called products. Is there a way to show the values from this field in a drop down box in cube.js? Once user select the value then change the dashboard filter with the selected value?

**Comment by vasilev-alex** [comment]
Hey @meymuthu! Yes, you can do so but you'll need to code this behavior yourself as Cube.js doesn't provide the API for such cases at the moment.

It's up for you how you'll fetch the values from the DB but after you have it in the dropdown you can use https://cube.dev/docs/@cubejs-client-react#types-member-updater to set the filter.

**Comment by hassankhan** [comment]
Closing as answered by @vasilev-alex
