### ISSUE TITLE
i want to integrete cube.js dashboard app in my current projject and also wanted to use cube.js with highchart.also included widgets and draggable option

### ISSUE THREAD

**Issue by ashwiniIot** [cube-js/cube.js#1021]

**Comment by vasilev-alex** [comment]
hi @ashwiniIot!

Those widgets are a part of `react-antd-dynamic` template which you can find here https://github.com/cube-js/cubejs-playground-templates/tree/master/packages/react-antd-dynamic and as of now they’re not pluggable.

I’m not aware of your dashboard implementation details, but you probably should take a look at the other charts here https://github.com/cube-js/cubejs-playground-templates and create a `hightchart-charts` package or you can base your dashboard on the `react-antd-dynamic` template and tweak it.

**Comment by ashwiniIot** [comment]
Thank you for your response. I will check it out.




Thanks & Regards,
Ashwini Gawade
