### ISSUE TITLE
I have a question  I like to used the cube.js with my project where the widget is already there with its own data from local rest api i would like the add, remove and move widget functionality so i can add that.

### ISSUE THREAD

**Issue by navichawla92** [cube-js/cube.js#1023]
I have a question  I like to used the cube.js with my project where the widget is already there with its own data from local rest api i would like the add, remove and move widget functionality so i can add that.

**Comment by vasilev-alex** [comment]
hey @navichawla92, this may be helpful https://cube.dev/blog/react-query-builder-with-cubejs/

**Comment by navichawla92** [comment]
@vasilev-alex i think you misunderstood my question. I say the data is from other backend i dont want to used the cube.js backend. My data is already in the form of json etc so how i used that data to show in graph with other functionality.
Thanks
