### ISSUE TITLE
Support read-only mode for bigquery driver

### ISSUE THREAD

**Issue by Nathlmt** [cube-js/cube.js#1028]
**Is your feature request related to a problem? Please describe.**
I don't have create table permissions in my BigQuery dataset. So I can't build preAggregation schema.
Do you have any plan to develop this feature
Thank you.

**Comment by paveltiunov** [comment]
@Nathlmt Hey Nath! Should be already supported. Which version do you use?

**Comment by Nathlmt** [comment]
I use version 0.19.61. When I use
``` driverFactory: () => new BigqueryDriver({
    readOnly: true
  }),
``` 
I received error need create table permissions in BigQuery

**Comment by jcw-** [comment]
FYI, from a quick look at the code, I think only MSSqlDriver and PostgresDriver currently support that option (and MongoBIDriver is always read only).

**Comment by devtothemoon** [comment]
@paveltiunov Can you explain more ?

**Comment by paveltiunov** [comment]
Seems like param name conflict to me. As a workaround you can use something like:
```javascript
driverFactory: () => { 
  const driver = new BigqueryDriver();
  driver.readOnly = () => true;
  return driver;
},
```

**Comment by jcw-** [comment]
@paveltiunov each driver needs to implement it, as well as `downloadQueryResults`, see https://github.com/cube-js/cube.js/pull/395

**Comment by paveltiunov** [comment]
@jcw- Yeah. Right. However I added default implementation in `BaseDriver` for it.

**Comment by jcw-** [comment]
Oh you did! Nice. Just needs a base implementation for readOnly looks like, cool.
