### ISSUE TITLE
[cubejs-backend-server-core] How can I deploy Cubejs as an gRPC Application

### ISSUE THREAD

**Issue by koolamusic** [cube-js/cube.js#1035]
I read the deployment example https://cube.dev/docs/deployment#express
Seeing that the `server-core` allows you to deploy cubejs as part of an express application, I am wondering how one could wrap the cubejs service to use the gRPC communication pattern

**Comment by Levhav** [comment]
Hi, 
In cubejs not implemented gRPC interface.
You can use [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) for work with cubejs [REST API over gRPC ](https://grpc.io/blog/coreos/)
