### ISSUE TITLE
ElasticSearch can't find nodes option

### ISSUE THREAD

**Issue by iukea1** [cube-js/cube.js#1036]
**Problem**

Having an issue with having Cube.JS talking to my elasticsearch server that is running locally 
![image](https://user-images.githubusercontent.com/35882815/91618347-bbc29080-e94f-11ea-8dc4-44fffae3b620.png)

My .env looks like this
```
CUBEJS_DB_HOST=127.0.0.1:9200
CUBEJS_DB_NAME=test
CUBEJS_DB_USER=elastic
CUBEJS_DB_PASS=password
CUBEJS_WEB_SOCKETS=true
CUBEJS_DB_TYPE=elasticsearch
CUBEJS_API_SECRET=SECRET
```

is there something I am missing?

**Comment by Levhav** [comment]
Hi,
Could you provide more information about your system configuration?
What elasticsearch version do you use?
Thanks.

**Comment by Levhav** [comment]
Hi, @iukea1 
Did you solve your problem? If yes, could you please share your solution here?
Thanks.

**Comment by iukea1** [comment]
@Levhav I am using Elasticsearch 7.8.0

But I can change my Elasticsearch to any version if needed.

**Comment by iukea1** [comment]
I am still stuck on this :(

**Comment by Levhav** [comment]
Hi, @iukea1
I checked the ElasticSearch driver source code and found that you should use CUBEJS_DB_URL instead of CUBEJS_DB_HOST
in .env file.

```
CUBEJS_WEB_SOCKETS=true
CUBEJS_DB_TYPE=elasticsearch
CUBEJS_DB_URL=http://localhost:9200
CUBEJS_API_SECRET=SECRET
```
