### ISSUE TITLE
Error: TypeError: Cannot read property 'queryType' of undefined

### ISSUE THREAD

**Issue by dktjsp** [cube-js/cube.js#1043]
**Describe the bug**

When requesting the cube js server with the front-end library I get that error 

Error: TypeError: Cannot read property 'queryType' of undefined

But with an external tool (like postman) the error is not appearing 

**To Reproduce**

1. Use the following versions of cube js server

    "@cubejs-backend/postgres-driver": "^0.20.0",
    "@cubejs-backend/server": "^0.20.0",
    "@cubejs-backend/server-core": "^0.20.0",

2. Use the following versions of cube js front end lib

    "@cubejs-client/ngx": "^0.18.18"

3. Request using the front end client
4. Request using postman

**Expected behavior**

No error

**Version:**
0.20.0 -> backend
0.18.18 -> front

**Comment by vasilev-alex** [comment]
hey @dktjsp! Thanks for posting it here. 

Could you please check the latest `0.20.2` version? It should be fixed there.

**Comment by dktjsp** [comment]
Hello, thanks for your quick reply and the quick fix ! However I can not install it via npm , here is the output using the following versions : 

    "@cubejs-backend/server": "^0.20.2",
    "@cubejs-backend/server-core": "^0.20.2",
    "@cubejs-client/core": "^0.20.2",

`
npm install


npm ERR! code ETARGET
npm ERR! notarget No matching version found for @cubejs-backend/schema-compiler@^0.20.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@cubejs-backend/server-core'
npm ERR! notarget

`

**Comment by dktjsp** [comment]
It works ! Thank you for your quick intervention!
