### ISSUE TITLE
Which presto distribution is accepted?

### ISSUE THREAD

**Issue by marceloavf** [cube-js/cube.js#1056]
As we were trying to connect `prestosql` with cube.js, we have a lot of problems, so we tried to connect with `prestodb` and it works from the start.

But we saw that `prestosql` is more popular than `prestodb` and have been done for a much broader audience, does cube.js only connect with prestodb or it's compatible with prestosql too?

**Comment by paveltiunov** [comment]
Hey @marceloavf ! What problems do you have? Actually prestosql is a very recent hard fork of original prestodb https://github.com/prestodb/presto. We're open to support both of them however `prestosql` isn't on our roadmap yet. We're open for this contribution.

**Comment by anismiles** [comment]
Hey @marceloavf what issues are you facing? I am able to connect and work with `prestosql` just fine for almost everything except for pre-aggregations where `timestamp` columns are being created as `text`!

**Comment by paveltiunov** [comment]
@marceloavf Would love to hear your feedback here!

**Comment by marceloavf** [comment]
We'll be testing it again with newer versions, we were having problems to connect to it and I'll pay attention to pre-aggregations @anismiles.

Thank you.

**Comment by marceloavf** [comment]
We are having some errors while trying to connect receiving an error like this:

```
java.lang.IllegalArgumentException: Error: Multiple entries with same key:
```
