### ISSUE TITLE
How to split schema into multiple files for same cube

### ISSUE THREAD

**Issue by devopsprosiva** [cube-js/cube.js#1065]
**Problem**

Hi,

I've one schema with a lot of metric queries. Is there a way to split the schema into multiple files for the same cube?

Thanks,
Siva

**Comment by Levhav** [comment]
Hi,  
Did you see this [tutorial](https://cube.dev/docs/extending-cubes)?
If it not helpful for you, please let me know.
Thanks.

**Comment by devopsprosiva** [comment]
@Levhav Thanks. I'll take a look.

**Comment by devopsprosiva** [comment]
@Levhav The above example extends a new cube `ProductPurchases` using the `BaseEvents` cube. I'm not looking for that. What I need is to breakdown `BaseEvents` cube into multiple files. In my case, I only have one cube.

**Comment by Levhav** [comment]
You can use `require` and all other JavaScript functions in the cube configuration file.  

For example you can use somthing like this:
```js
const fs = require('fs');

let measures = JSON.parse(fs.readFileSync('./measures.json', 'utf-8', 'r+'));
let dimensions = JSON.parse(fs.readFileSync('./dimensions.json', 'utf-8', 'r+'));

cube(`MyCube`, {
  sql: `SELECT test as schem`,

  measures:measures,
  dimensions:dimensions, 
})
```

[More information here](https://cube.dev/docs/schema-execution-environment#require)

**Comment by Levhav** [comment]
Hi, @devopsprosiva  
Could you please elaborate on your use case?  Why your config so big? Do you use code generation for it, or maybe you have something other reasons?

**Comment by devopsprosiva** [comment]
Hi @Levhav,

Sorry for the delay in responding. Coming to my use case, I only have one view in the database. But I can write lot of queries based on different filters on the data. That's the reason why the schema file is getting big. Hope this helps in understanding better.

Thanks,
Siva
