### ISSUE TITLE
Athena Driver does not access views via the informationSchemaQuery

### ISSUE THREAD

**Issue by yatesdev** [cube-js/cube.js#1083]
**Describe the bug**
When attempting to use the dev server. The schema page fails to populate views as part of the tree.
This is due to Athena being weird about accessing views. You have to access them [specifically by view name](https://docs.aws.amazon.com/athena/latest/ug/querying-glue-catalog.html#querying-glue-catalog-listing-columns).
Querying information_schema.columns without the specific where clause will not return any view related columns.

**To Reproduce**
1. Create a table in athena.
2. Create a view in athena.
3. Load Cube.js dev playground connected to athena.
4. Go to schema tab.
5. Under 'Tables' tree view, see that only the table that was created is visible, not the view.

**Expected behavior**
To cube.js, an athena view should be treated just like a table and be visible within the playground's schema.
I can manually create a schema file and query the data as expected already.

**Version:**
0.19.61

**Additional context**
Current thought path on solution is to override the BaseDriver `tablesSchema` within AthenaDriver. 
It will require multiple round trips though.

Get full list of tables (this includes the views)
```
SELECT table_schema, table_name
FROM information_schema.tables
where tables.table_schema NOT IN ('information_schema', 'mysql', 'performance_schema', 'sys')
```

use `informationQuerySchema` from base to get normal tables/columns.

reduce the results... where table_schema and table_name do not exist in the `informationQuerySchema` call, make this query:
```
SELECT 
columns.column_name,
columns.table_name,
columns.table_schema,
columns.data_type
FROM information_schema.columns
WHERE columns.table_schema = `${table_schema}`
AND table_name = `${table_name}`
```
and merge with existing result set.

**Comment by RusovDmitriy** [comment]
Hey Mike! Thanks for posting this one. We'll fix this one shortly.
