### ISSUE TITLE
Sub query & performances (+ limit configuration)

### ISSUE THREAD

**Issue by dktjsp** [cube-js/cube.js#1106]
**Problem**

Hello, i'm looking at cube sql generated queries, and we may be able to get better performances if the query was simplified. And in our project we may also need to get rid of the limit in the query, but it's not configurable yet.

**Related Cube.js schema**
```javascript
cube(`realTime`, {
    sql: `SELECT * FROM rrl_event WHERE ${USER_CONTEXT.location.filter(locations => `location_id in (${locations.join(',')})`)}`
})
```

**Related Cube.js generated SQL**

```sql
SELECT "supplier".cl_technical_label "supplier__supplier_label",
       trim(box_code)                "real_time__box_code",
       "real_time".item_code         "real_time__item_code"
FROM (SELECT * FROM rrl_event WHERE 1 = 1) AS "real_time"
         LEFT JOIN embisphere.esr_customer_location AS "supplier" ON "supplier".cl_id = "real_time".location_id
WHERE ("real_time".event_date >= $1::timestamptz AND "real_time".event_date <= $2::timestamptz)
  AND ("real_time".event_type = 'BOXVLD')
GROUP BY 1, 2, 3
ORDER BY 1 ASC
LIMIT 10000
```

In this query we may expected a much simplier version, not including the sub query to gain performances, like this : 

```sql
SELECT "supplier".cl_technical_label "supplier__supplier_label",
       trim(box_code)                "real_time__box_code",
       item_code         "real_time__item_code"
FROM rrl_event 
         LEFT JOIN embisphere.esr_customer_location AS "supplier" ON "supplier".cl_id = "real_time".location_id
WHERE ("real_time".event_date >= $1::timestamptz AND "real_time".event_date <= $2::timestamptz)
  AND ("real_time".event_type = 'BOXVLD') AND  1 = 1
GROUP BY 1, 2, 3
ORDER BY 1 ASC
LIMIT 10000
```

The idea is to get rid of `SELECT * FROM rrl_event WHERE 1 = 1` and also to drop the limit.

Could we make this using cube js ? 

Thanks

**Comment by paveltiunov** [comment]
@dktjsp Hey Jules! There's an experimental flag for that: https://github.com/cube-js/cube.js/issues/1010#issuecomment-686783079.

**Comment by dktjsp** [comment]
Hey @paveltiunov , do you know if there is a way to remove the `::timestamptz` cast ? It's a big performance issue for us

**example** 

`"select max((\"real_time\".event_date::timestamptz AT TIME ZONE 'UTC')) from rrl_event AS \"real_time\""`

**Comment by paveltiunov** [comment]
@dktjsp Hey Jules! You can override SQL of `refreshKey` however you want: https://cube.dev/docs/pre-aggregations#refresh-key. Closing this issue as the original issue seems resolved.
