### ISSUE TITLE
CubejsServerCore Options Validation Breaks Serverless Deployments

### ISSUE THREAD

**Issue by sergio-dreamcode** [cube-js/cube.js#1110]
**Describe the bug**
We use CubeJS Serverless deployment and yesterday after upgrading to 0.20.8 we had some errors due to the new options validation that was added.

When Lambda function starts, this is the error that is logged:

```
{
    "errorType": "Error",
    "errorMessage": "Invalid cube-server-core options: child \"orchestratorOptions\" fails because [\"orchestratorOptions\" must be an object]",
    "stack": [
        "Error: Invalid cube-server-core options: child \"orchestratorOptions\" fails because [\"orchestratorOptions\" must be an object]",
        "    at module.exports (/var/task/node_modules/@cubejs-backend/server-core/core/optionsValidate.js:67:20)",
        "    at new CubejsServerCore (/var/task/node_modules/@cubejs-backend/server-core/core/index.js:155:5)",
        "    at new Handlers (/var/task/node_modules/@cubejs-backend/serverless/Handlers.js:77:23)",
        "    at new AWSHandlers (/var/task/node_modules/@cubejs-backend/serverless-aws/index.js:9:5)",
        "    at Object.<anonymous> (/var/task/src/cubeServer.js:51:18)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)"
    ]
}
```
Even if we set `orchestratorOptions` with default values or as in the example below where `orchestratorOptions` is not set the error still happens.

**To Reproduce**

Any basic Serverless setup with the correct CUBEJS_* environment variables set correctly.

```
const AWSHandlers = require("@cubejs-backend/serverless-aws");
const PostgresDriver = require('@cubejs-backend/postgres-driver');

module.exports = new AWSHandlers({
    logger: (msg, params) => {
        console.log(`${msg}: ${JSON.stringify(params)}`);
    },
    schemaPath: process.env.CUBEJS_SCHEMA_PATH,
    preAggregationsSchema: process.env.CUBEJS_PRE_AGGREGATIONS_SCHEMA,
    externalDbType: 'postgres',
    externalDriverFactory: () => new PostgresDriver({
        host: process.env.CUBEJS_EXT_DB_HOST,
        database: process.env.CUBEJS_EXT_DB_NAME,
        user: process.env.CUBEJS_EXT_DB_USER,
        password: process.env.CUBEJS_EXT_DB_PASS,
    }),
});
```

**Expected behavior**
The application should start as expected and set default values if `orchestratorOptions` is not set.

**Version:**
0.20.8

**Additional context**
We tried to reproduce locally with Express setup of CubeJS but it worked as expected so it only happens with Serverless. 

After checking source code seems that the issue is in the new validation added this week. The [optionsValidate.js](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-server-core/core/optionsValidate.js#L50) file in the core package expects `orchestratorOptions` to be an object, on the other hand the [Handlers.js](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-serverless/Handlers.js#L37) file in the serverless package sets the `orchestratorOptions` as a function and not as an object. That could explain why it fails even if `orchestratorOptions` property is not set.

**Comment by RusovDmitriy** [comment]
Hey Sergio! Thanks for posting this one. We'll fix this one shortly.
