### ISSUE TITLE
How to join measure from pre-aggregation table with measure from other cube to create calculated measure?

### ISSUE THREAD

**Issue by DharmitP** [cube-js/cube.js#1112]
**Problem**

I have a pre-aggregation table called `report` as defined below with a measure called `dollarValue`. I am using this pre-aggregation table to pull data and create reports (filtered based on `account`, `portfolioId`, and `country` as provided by the user). The user also needs to be able to convert the `dollarValue` (currently in USD) to any other currency. To do this, there is a cube called `ExchangeRate` as defined below. The `rateToUSD` is found by doing the follow filter:

```
  SELECT
      "exchange_rate".ratetousd "exchange_rate__rate_to_u_s_d"
    FROM
      reference.exchangerate AS "exchange_rate"
  WHERE ("exchange_rate".isocurrcd = 'CAD') 
      AND ("exchange_rate".startdt < '2017-10-12 16:49:10.000000'::timestamptz) 
      AND ("exchange_rate".enddt > '2017-10-12 16:49:10.000000'::timestamptz) 
  LIMIT 10000
```

The calculated measure is then `dollarValue` / `rateToUSD`. 

The problem is how to join the results from the pre-aggregation table and then apply the `rateToUSD` from the query above. I have done a join on the `Base` cube with the `ExchangeRate` cube but it generates the following SQL:

```
SELECT
  sum(
    (dollar_value) / "exchange_rate".ratetousd) "base__dollar_value"
FROM
  request.base_table AS "base"
  LEFT JOIN reference.exchangerate AS "exchange_rate" ON isoCurrCd = $ 1
WHERE
  (
    // filtering
  )
  AND ("exchange_rate".isocurrcd = $ 12)
  AND ("exchange_rate".startdt < $ 13 :: timestamptz)
  AND ("exchange_rate".enddt > $ 14 :: timestamptz)
GROUP BY
  1,
  2,
  3
ORDER BY
  4 DESC
LIMIT
  10000
```

Above, I am looking to replace "base" with "base_report" pre-aggregation table. Is this possible using Cube.js all within a single query?

**Related Cube.js schema**
```
cube(`Base`, {
 sql: `select * from base_table`,
 joins: {
   ExchangeRate: {
      relationship: `hasOne`,
      sql: `${FILTER_PARAMS.ExchangeRate.isoCurrCd.filter('isoCurrCd')}`
    }
 },
 preAggregations: {
   report: {
      type: `rollup`,
      measureReferences: [dollarValue],
      dimensionReferences: [
        account,
        portfolioId,
        country,
        state
      ],
      refreshKey: {
        every: `1 day`
      }
    }
  }
});
```
```
cube(`ExchangeRate`, {
  sql: `SELECT * FROM reference.exchangerate`,
  measures: {
    rateToUSD: {
      sql: `ratetousd`,
      type: `number`,
      format: `currency`
    }
  },
  dimensions: {
    isoCurrCd: {
      sql: `isocurrcd`,
      type: `string`
    },
    startDt: {
      sql: `startdt`,
      type: `time`
    },
    endDt: {
      sql: `enddt`,
      type: `time`
    }
  }
});

```

**Comment by Levhav** [comment]
Hi, @DharmitP 
I started checking your cube config. And it looks like uncompleted.
Could you please share full your schema files?
