### ISSUE TITLE
Cumulative Chart not showing up when using Redis cache 

### ISSUE THREAD

**Issue by jbstand** [cube-js/cube.js#1117]
Hi everyone,

first of all thanks for this amazing project, it's really useful.

I wanted to plot two charts :
- 1 BarChart displaying values per day
- 1 LineChart displaying the cumulative sum of those values per day

I've wrote the following schema : 
```
// @ts-nocheck
cube(`Redmine`, {
  sql: `SELECT * FROM redmine.view_changes_per_day`,

  joins: {
    
  },
  
  measures: {
    amount: {
      sql: `amount`,
      type: `sum`,
      description: `Changes Per Day`
    },

    cumsum: {
      sql: `amount`,
      type: `sum`,
      drillMembers: [status, tracker, project, type],
      rollingWindow: {
        trailing: `unbounded`,
      },
      description: `Cumulative Changes`
    }
  },
  
  dimensions: {
    status: {
      sql: `status`,
      type: `string`
    },
    
    tracker: {
      sql: `tracker`,
      type: `string`
    },
    
    project: {
      sql: `project`,
      type: `string`
    },
    
    type: {
      sql: `type`,
      type: `string`
    },
    
    date: {
      sql: `date`,
      type: `time`
    }
  },

  preAggregations: {
    projectAndDate: {
      type: `rollup`,
      measureReferences: [Redmine.amount],
      dimensionReferences: [project],
      timeDimensionReference: Date, // date or Date? Dimension is date
      granularity: `day`,
    }
  }
});
```

And I'm sending the following queries to the backend : 
```
{
   vizState:
     "{ \
     'query': \
     { \
       'measures': ['Redmine.cumsum'], \
       'timeDimensions': \
       [{ \
         'dimension': 'Redmine.date', \
         'granularity': 'day', \
         'dateRange': 'This year' \
       }], \
      'order': {}, \
       'dimensions': ['Redmine.status'], \
       'filters': \
       [{ \
         'dimension': 'Redmine.project', \
         'operator': 'contains', \
         'values': ['MH16'] \
       }] \
     }, \
     'chartType': 'line', \
     'orderMembers': \
     [{ \
       'id': 'Redmine.cumsum', \
       'title': 'Redmine CumSum', \
       'order': 'none' \
     }, \
     { \
       'id': 'Redmine.status', \
       'title': 'Redmine Status', \
       'order': 'none' \
     }, \
     { \
       'id': 'Redmine.date', \
       'title': 'Redmine Date', \
       'order': 'none' \
     }], \
     'pivotConfig': \
     { \
       'x': ['Redmine.date.day'], \
       'y': ['Redmine.status','measures'], \
       'fillMissingDates': true \
     }, \
     'shouldApplyHeuristicOrder': true \
     }",
   name: "Cummulative changes",
   id: "1",
   layout: "{ \
     'x': 0, \
     'y': 0, \
     'w': 7, \
     'h': 11 \
   }"
 },
 {
   vizState:
     "{ \
       'query': \
       { \
         'measures': ['Redmine.amount'], \
         'timeDimensions': \
         [{ \
           'dimension': 'Redmine.date', \
           'granularity': 'day' \
         }], \
         'order': {}, \
         'dimensions': ['Redmine.status'], \
         'filters': \
         [{ \
           'dimension': 'Redmine.project', \
           'operator': 'contains', \
           'values': ['Test'] \
         }] \
       }, \
       'chartType': 'bar', \
       'orderMembers': \
       [{ \
         'id': 'Redmine.amount', \
         'title': 'Redmine Amount', \
         'order': 'none' \
       }, \
       { \
         'id': 'Redmine.status', \
         'title': 'Redmine Status', \
         'order': 'none' \
       }, \
       { \
         'id': 'Redmine.date', \
         'title': 'Redmine Date', \
         'order': 'none' \
       }], \
       'pivotConfig': \
       { \
         'x': ['Redmine.date.day'], \
         'y': ['Redmine.status','measures'], \
         'fillMissingDates': true \
       }, \
       'shouldApplyHeuristicOrder': true \
     }",
  name: "Changes per day",
  id: "2",
   layout: "{ \
     'x': 0, \
     'y': 11, \
     'w': 7, \
     'h': 11 \
   }"
 }];
```

The Dashboard was showing up perfectly, Life was good!

I then configured Redis on my server to make it run with CubeJS, restarted my service and now the cumulative chart on my Dashboard is empty! The legend is good but there is no values displayed. (If I switch off Redis eveything comes back to normal).

So I've looked into my resultSet coming from the backend and compared the resultSet of the cumulative chart and the Barchart (which is still working). I discovered that the Time in the cumulative resultSet was set to DD-MM-YYYYT23.00.000 or DD-MM-YYYYT22.00.000 depending on winter/summer hour change. But the Time in the BarChart resultSet is always D-MM-YYYYT00.00.000 at midnight.

I tried to call resultSet.series() on both and the cumulative series only has "undefined" values but the BarChart series is correctly populated.

So I decided to run the generated SQL query manually on my DB and I've found that the working query for the BarChart had DATE_FORMAT(CONVERT_TZ(.....))) and the non working query for the cumulative chart had only CONVERT_TZ(.....).

The date column with the working query contains : 2020-05-26T00:00:00.000 a correct TimeStamp
The date column with the non working query contains :  2020-01-01 00:00:00.000000

I'm diving into the backend code to see what's going on but any help would be highly appreciated :)

Have an excellent day,
Jeremie Melly

**Comment by paveltiunov** [comment]
Hey @jbstand ! Could you please share what database do you use?

**Comment by jbstand** [comment]
I'm using mariaDB v10.3.22

**Comment by jbstand** [comment]
After a bit of digging I was able to display my chart by doing the following change : 

Initially :
https://github.com/cube-js/cube.js/blob/65ef327b82d4f932f760ae78396c1396ae047d1c/packages/cubejs-api-gateway/index.js#L105-L110

Changed that : 
`return (value instanceof Date ? moment(value) : moment.utc(value)).format(moment.HTML5_FMT.DATETIME_LOCAL_MS);`

To : 
`    return (value instanceof Date ? moment(value) : moment.utc(value)).format(moment.HTML5_FMT.DATETIME_LOCAL_MS + 'Z');`

What do you think of that change? I'm not sure that it'll not broke anything...

Cheers,
Jeremie

**Comment by jbstand** [comment]
Indeed, it broke the logic. The other charts are now empty.

**Comment by ovr** [comment]
Hello Jérémie,

Thank you for providing a lot of information and submitting an issue, I am planing to start investing issue tomorrow.

BTW:

Yes, the issue is inside `date` to `string` conversion, but this should be done inside driver (API gateway do own conversion, but it's not a good way, should be done in driver).

**Comment by jbstand** [comment]
Hey,

Thank you very much :) This is very appreciated.

In the meantime I'll try to spot the issue in the driver, see if I can gain some time :)

Cheers,
Jeremie

**Comment by ovr** [comment]
@jbstand I started to work on it, first:

> timeDimensionReference: Date, // date or Date? Dimension is date

Must be `date`, it's a field

**Comment by jbstand** [comment]
> 
> 
> @jbstand I started to work on it, first:
> 
> > timeDimensionReference: Date, // date or Date? Dimension is date
> 
> Must be `date`, it's a field

Thank you, I fixed it

**Comment by jbstand** [comment]
The fact that disabling Redis makes all the charts to render properly leads me to the conclusion that the issue is probably in query-orchestrator/orchestrator/

Do you know if, when using Redis, during the first query to populate the Redis cache, will the query data be stored first in Redis and reread from there to populate the chart or if it reads directly the data from the query to populate the chart and then cache them in Redis?

**Comment by ovr** [comment]
> Do you know if, when using Redis, during the first query to populate the Redis cache, will the query data be stored first in Redis and reread from there to populate the chart or if it reads directly the data from the query to populate the chart and then cache them in Redis?

It's complicated thing with a lot of cases... On timeout error it can skip reading and return from the cache for example, there are some options for waiting for renew to update cache and etc. etc. etc.

I am going to suggest enabling logging by `CUBEJS_LOG_LEVEL=trace`, you will see rows with

`Using cache for`
`Found cache entry`

Will be cool if you can share log, because I cannot reproduce it locally, but I am continue to trying to understand what is going wrong with reproducing.

Pretty funny question: Are you using the latest release?)

Thanks

**Comment by jbstand** [comment]
Hey,

Yes I updated to the latest release on the beginning of the week, reupdating now (just in case)!

Thank you for your help! I've joined the requested log file (which is big). I ran it after having flushed the Redis cache.

There is two charts, on with a basic query which works well and the faulty one (cumulative) with a massive query.

[log.log](https://github.com/cube-js/cube.js/files/5283450/log.log)

**Comment by ovr** [comment]
@jbstand Thanks for the log.

Good news: I can reproduce the bug, and I am working on the fix.

**Comment by jbstand** [comment]
Hey @ovr, that's great news! 

If you need it, do not hesitate to brief me and I will do my best to help you!

**Comment by jbstand** [comment]
OMG! Applying your fix made the magic happens!

All of my charts are now rendering perfectly even with Redis cache enabled.

Thank you so much for you time,
I owe you one !

Jeremie

**Comment by ovr** [comment]
Yeah, I prepared two different fixes, but I am waiting for review because it's probably not the best solution or has side effects.
