### ISSUE TITLE
SnowflakeDB Connection using Key-Pair authentication.

### ISSUE THREAD

**Issue by TheSPD** [cube-js/cube.js#1123]
**Problem**

Can we connect to snowflake db using Key Pair Authentication?
Something like this https://docs.snowflake.com/en/user-guide/kafka-connector-install.html#using-key-pair-authentication

I need this as we're using an SSO to login into snowflake and don't have "username/password".

**Comment by paveltiunov** [comment]
@TheSPD Hey Shreepad! This is something Snowflake Node.js driver is missing, unfortunately: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/62. Do you have the option of creating a service user?

**Comment by sam-som** [comment]
Hello 
Look like `key-auth` is just added to `https://github.com/snowflakedb/snowflake-connector-nodejs`
https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#using-key-pair-authentication-key-pair-rotation

Is there any update on the `cube.js` side? is `key-auth` now available for `snowflake`?
Thank you :)

**Comment by sam-som** [comment]
Hello :)
I have created a PR to add `key-pair` authentication to `SnowflakeDriver.js` here.
Please take a look 
https://github.com/cube-js/cube.js/pull/2724

**Comment by sam-som** [comment]
Hello 
Can i please get a CR on this PR? https://github.com/cube-js/cube.js/pull/2724
Thank you

**Comment by sam-som** [comment]
Merged and released in https://github.com/cube-js/cube.js/releases/tag/v0.27.16
https://www.npmjs.com/package/@cubejs-backend/snowflake-driver/v/0.27.16

**Comment by clayheaton** [comment]
@sam-som 
Hi, I wanted to try out Cube (self-hosted) and connect to Snowflake, authenticating with a key pair. I'm using an encrypted key and connect with it from various other applications and services without a problem. Cube is throwing this error:

```
Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag at Object.createPrivateKey (node:internal/crypto/keys:620:12) at loadPrivateKey (/cube/node_modules/snowflake-sdk/lib/authentication/auth_keypair.js:80:35) at auth_keypair.authenticate (/cube/node_modules/snowflake-sdk/lib/authentication/auth_keypair.js:169:20) at Connection.connect (/cube/node_modules/snowflake-sdk/lib/connection/connection.js:222:12) at password.password (/cube/node_modules/@cubejs-backend/snowflake-driver/src/SnowflakeDriver.ts:333:39) at new Promise (<anonymous>) at SnowflakeDriver.testConnection (/cube/node_modules/@cubejs-backend/snowflake-driver/src/SnowflakeDriver.ts:332:11) at CubejsServerCore.getDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:792:20) at processTicksAndRejections (node:internal/process/task_queues:96:5) at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:108:22 at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:78:9
```

This is in my `.env` file. Any idea?

```
CUBEJS_DB_TYPE=snowflake
CUBEJS_DB_SNOWFLAKE_ACCOUNT=myaccount.us-east-1
CUBEJS_DB_SNOWFLAKE_WAREHOUSE=MY_WAREHOUSE
CUBEJS_DB_NAME=MY_DB
CUBEJS_DB_USER=MY_SERVICE_ACCOUNT@MYCOMPANY.COM
CUBEJS_DB_SNOWFLAKE_AUTHENTICATOR=SNOWFLAKE_JWT
CUBEJS_DB_SNOWFLAKE_PRIVATE_KEY_PATH=my_key.p8
CUBEJS_DB_SNOWFLAKE_PRIVATE_KEY_PASS=my_key_pass
```
