### ISSUE TITLE
Server core options validation is missing server options (initApp and webSockets)

### ISSUE THREAD

**Issue by sajdre** [cube-js/cube.js#1124]
After server core options validation added (#1089) it's not possible to use options:
```
{
  webSockets?: boolean;
  initApp?(app: express.Application): void | Promise<void>;
}
```
that you can use according to https://cube.dev/docs/@cubejs-backend-server, you will get error "Invalid cube-server-core options: "initApp" is not allowed"

**Comment by RusovDmitriy** [comment]
Hey @sajdre! Already fixed this issue #1115, please wait for the next release.
