### ISSUE TITLE
Currency format it's not applied on measure

### ISSUE THREAD

**Issue by cesarochoa2006** [cube-js/cube.js#1157]
Hi. 

I have a schema that contains a simple aggregation column with currency format 

`...
measures: {
	...   
         util: {
                sql: `${CUBE
                    }."UTILITY"`,
                type: `sum`,
                format: `currency`
            },
...
}
...`

But when it comes to show the results, they aren't formatted at all, and just show plain numbers with no format. 
The db is Oracle and i'm using oracle driver succesfully except for this currency thing. 

At this point i don't know if i'm missing something or just the currency format don't work with Oracle queries.

**Comment by vasilev-alex** [comment]
Duplicate of #301
