### ISSUE TITLE
Support for Pagination in query format

### ISSUE THREAD

**Issue by avin3sh** [cube-js/cube.js#117]
Right now there is no standard way of paginating large number of results. There should either be support for `offset` or some other query `property` to achieve the same result.

**Comment by ifokeev** [comment]
+1, no way to offset the result

**Comment by paveltiunov** [comment]
@avin3sh Hey Avinesh! I think it makes to add such support. Could you please elaborate a little bit on your use case? Is it just a big table or a lot of chart data?

**Comment by avin3sh** [comment]
In our use case, we just have lots of rows to deal with and it would be better to have a neat way to specify offset in CubeJS query format so that we can effectively have pagination like effect.

**Comment by paveltiunov** [comment]
@avin3sh Makes sense. Could you please provide an example of such query?

**Comment by avin3sh** [comment]
@paveltiunov  So suppose in `COMMENTS` table we are storing `post_id`, `comment_id`, `comment_text`, `comment_time` - i.e. comments over each blog post with the timestamp, with many to one join to `POSTS` table. 

Now one of our dashboard elements require displaying blog post title along with total comments on the blog post, due to lack of equivalent `offset` support in CubeJs Query Format, we would have to get all the  `COUNT(comment_id)` measure, with `post_id` dimension, which will return all the blogposts in our DB along with total number of comments on each of the blog posts. That's could be potentially huge data to be sent in a single HTTP request if number of blog posts increase dramatically. But there is no other way around this since we do not have `offset` support in CubeJS Query Format.

**Comment by paveltiunov** [comment]
@avin3sh Do you mean displaying total comments count for specific blog post? If yes there's no need to for offset feature. The query in this case will be:
```
{
  measures: ['Comments.count'],
  filters: [{ dimension: 'Blog.postId', operator: 'equals', values: ['12345'] }]
}
```
This query will return always just one row.

**Comment by avin3sh** [comment]
@paveltiunov Apologies, I was not clear with my description.

I understand that I can always use filter to get comment count for a specific blog post, however the dashboard element displays the recent 100 blog posts and the admin has ability to keep hitting "next" button to get next 100 blog posts and so on until the end of all the blog posts. So in this case the equivalent native native SQL query would have `LIMIT 100` and `OFFSET 0` on the first page, and `LIMIT 200` and `OFFSET 100` on the second page and so on.

**Comment by paveltiunov** [comment]
Ok. Gotcha! Yeah. That makes sense.

**Comment by ifokeev** [comment]
up
without the offset framework is limiting a standard functionality

**Comment by ifokeev** [comment]
up

**Comment by paveltiunov** [comment]
@ifokeev Hey Ivan! Thanks for follow-up! Working on this one. 🙌

**Comment by yohayg** [comment]
Hi @paveltiunov, any progress on this one? Can you please point me to a start point where I can try to implement this by myself or assist in any other way?

Thanks,
Yohay

**Comment by paveltiunov** [comment]
@yohayg Hey Yohay! Thanks for asking! Just shipped.

**Comment by atulim** [comment]
How can we use Pagination @paveltiunov  in Cube.js?

**Comment by ifokeev** [comment]
@atulim you're able to use offset. See commit https://github.com/cube-js/cube.js/commit/7fb17150039fa1b2dad172fd4225103dc08032d5

**Comment by krystian50** [comment]
@paveltiunov I'm trying to use offset in my queries, but it seems like changing only offset, so for eg `{limit :10, offset: 0 }` => `{limit :10, offset: 10 }`, does not affect query. There's no difference. Changing to `{limit :20, offset: 10 }` only adds 10 extra items. Version 0.19.17 used with postgres. Does the offset work? It seems like being ignored. Is there a way to check the actual query?
