### ISSUE TITLE
unGrouped query returns only unique data

### ISSUE THREAD

**Issue by vignesh-123** [cube-js/cube.js#1173]
I am trying to get all the records after filtering from the database, but it is responding only with the unique set of values
```
{
"filters": [],
"limit": 100,
"dimensions": [
  "metrics.message_time",
  "metrics.user_id",
  "metrics.csv_name"
],
"ungrouped": true,
"renewQuery": true
}

```
This is the query that I use. The database contains more than 100 records, but I am receiving only 14 unique records 
Is there a way to get all the records even if they are duplicates

**Comment by RusovDmitriy** [comment]
Hey @vignesh-123! Could you please share your console logs? SQL query and other debug info

**Comment by keydunov** [comment]
HI @vignesh-123,

I'm going to close this one due to inactivity. Please feel free to reopen it with additional context as @RusovDmitriy requested.
