### ISSUE TITLE
Schema generation issue

### ISSUE THREAD

**Issue by rnavarych** [cube-js/cube.js#1176]
**bigquery issue**

I have issue with reading field from bigquery.

![Без названия](https://user-images.githubusercontent.com/5064975/95126542-5ab48680-075f-11eb-92e9-19ecfe4f617e.jpeg)

Cube.js generated this dimension but when I want to get this dimension from client side I had reading issue

participantSid: {
  sql: `${CUBE}.participant.isHost`,
  type: `string`,
  title: `Participant.sid`
},

Name participant not found inside call_events at [2:21]

**Comment by RusovDmitriy** [comment]
Hey @rnavarych! Could you please share console logs? (SQL query and other debug info)

**Comment by keydunov** [comment]
@rnavarych I'm going to close this one due to inactivity. Please feel free to submit your future questions to Stackoverflow with `cube.js` tag - https://stackoverflow.com/questions/tagged/cube.js
