### ISSUE TITLE
Duplicates names in ResultSet.seriesNames()

### ISSUE THREAD

**Issue by aviranmoz** [cube-js/cube.js#1186]
**Describe the bug**
Duplicates names when using ResultSet.seriesNames() with multiple queries.
I get back duplicate keys the first key repeat itself.

**To Reproduce**
1. Send multiple queries with useCubeQuery
2. Call resultSet.seriesNames() 
3. You will get the first key as number of queries you sent

**Expected behavior**
Get back the name of measure each query 

**Version:**
0.20.12

**Additional context**
cubejs-client-core package

**Comment by vasilev-alex** [comment]
Hey @aviranmoz! Could you please attach the queries you're sending as well as the `.seriesNames()` result?

**Comment by vasilev-alex** [comment]
Closed by #1187
