### ISSUE TITLE
How to use schema contexts

### ISSUE THREAD

**Issue by apuntovanini** [cube-js/cube.js#1188]
**Problem**

When we define contexts in the schema

```javascript
context(`Marketing`, {
  contextMembers: [Sessions, Events, Ads]
});
```

how can we use them in the front-end?

We have a query builder page that now shows all the measures from all the contexts. We'd like to limit measures, dimensions and time dimensions to the one belonging to a specific context, but can't understand how to do this.

**(by the way, there's a suggested place to store contexts?)**

**Comment by paveltiunov** [comment]
@apuntovanini Hey Andrea! Thanks for posting this! We're planning to add API to access those contexts. Let's use this issue to track the progress here.

**Comment by aditrades** [comment]
Waiting for this amazing feature as well.
We can participate in the development if some guidelines will be provided

**Comment by ankesh1998** [comment]
Hi @paveltiunov,
Any update on, How we can use the context members?

**Comment by paveltiunov** [comment]
Merging this one to #2145.
