### ISSUE TITLE
Issue with QueryBuilder render props

### ISSUE THREAD

**Issue by illusional** [cube-js/cube.js#1192]
**Describe the bug**

Hi, I'm using typescript + cubejs/react to render graphs in React. Through the docs, I see the [`QueryBuilder.render` function returns a `QueryBuilderRenderProps` type](https://github.com/cube-js/cube.js/blob/1c1152b06e2ddfe724ba0a332595d543b67d8c54/packages/cubejs-client-react/index.d.ts#L165).

In the [`QueryBuilder` examples on the web](https://cube.dev/docs/@cubejs-client-react#query-builder), you should be able to access the `resultSet, measures, availableMeasures, updateMeasures` properties on this render prop, however the `resultSet` is not declared on the [`QueryBuilderRenderProps` type](https://github.com/cube-js/cube.js/blob/1c1152b06e2ddfe724ba0a332595d543b67d8c54/packages/cubejs-client-react/index.d.ts#L181-L216). The use of `resultSet` is also used [just below the type declaration](https://github.com/cube-js/cube.js/blob/1c1152b06e2ddfe724ba0a332595d543b67d8c54/packages/cubejs-client-react/index.d.ts#L249).

It also seems

**To Reproduce**

```jsx
<QueryBuilder
    query={query} cubejsApi={cubejsApi}

    {/* The next line does not compile */}
    render={({resultSet, ...props}) => {
        return <p>Results here: {JSON.stringify(resultSet)}</p>         
    })
}) />
```

**Expected behavior**

This should compile, and `QueryBuilderRenderProps` type declaration should contain all possible types.

**Screenshots**

![image](https://user-images.githubusercontent.com/22381693/95732265-4d058080-0ccc-11eb-8a4e-95b45ea1e054.png)

**Version:**

```
"@cubejs-client/core": "0.20.10",
"@cubejs-client/react": "0.20.10",
```

**Additional context**

I believe this fix is to add these extra fields onto the type declaration, but just wanted to check before hand.

**Comment by RusovDmitriy** [comment]
Hey @illusional! Thanks for posting this one. We'll fix this one shortly.

**Comment by illusional** [comment]
Thanks @RusovDmitriy! Let me know if I can do anything to help :)

**Comment by RusovDmitriy** [comment]
@illusional  PR with the fix already merged. Please wait for the next release. Also, it may be worth paying attention to this comment https://github.com/cube-js/cube.js/pull/1193/files#r503231460
