### ISSUE TITLE
A schema builder API/library would standardise schema reuse across platforms 

### ISSUE THREAD

**Issue by chakravarthyvp** [cube-js/cube.js#1199]
**Is your feature request related to a problem? Please describe.**
I'm evaluating cube.js and felt that there is a need for a schema generation builder utility. This will enable multiple-stakeholders to use one common way to build and represent schema. For ex., our company has multiple products and therefore multiple metrics associated with them. Each product group need 1 way define what a metric schema would look like. This schema can be reused across different analytic systems. This is an example of an use case.

**Describe the solution you'd like**
The client library could be a javascript builder interface that the UI clients can programmatically build the schema.

**Describe alternatives you've considered**
The alternate right now is to hand-write the schema.

**Additional context**

**Comment by paveltiunov** [comment]
@chakravarthyvp Thanks for posting this! It's a big deal indeed. We provide these developer tools as a part of Cube Cloud.
