### ISSUE TITLE
Dynamically adding cubes from an external file in the schema location

### ISSUE THREAD

**Issue by manikasharma70** [cube-js/cube.js#1203]
How can I add a schema file in location "http://localhost:4000/#/schema" by dynamically creating cube data from an API end point.

![image](https://user-images.githubusercontent.com/18146464/96014713-4f9ade00-0e64-11eb-97fb-d912ef984f27.png)

**Comment by manikasharma70** [comment]
Please help

**Comment by vasilev-alex** [comment]
Hey @manikasharma70! 

If you go to the `Tables` tab and check the tables you want to generate schemas for, you'll see the `Plus` button to have that option.

P.S. if you update the Playground to the latest version, it'll be a bit more straightforward.

**Comment by manikasharma70** [comment]
@vasilev-alex  : The Tables will only have the tables of the database defined.
If we want to create dynamic Cubes with measures and dimensions and store it in schema folder, can we achieve that ?

**Comment by vasilev-alex** [comment]
We don't provide any API for that as of now. But there's a similar proposal which you can vote and follow https://github.com/cube-js/cube.js/issues/1199
