### ISSUE TITLE
Error: The server does not support SSL connections

### ISSUE THREAD

**Issue by horidon** [cube-js/cube.js#1212]
`Error: The server does not support SSL connections
    at QueryQueue.parseResult (/Users/mac/Desktop/flow_ai/analytics-cubejs/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:99:13)
    at QueryQueue.executeInQueue (/Users/mac/Desktop/flow_ai/analytics-cubejs/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:88:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/mac/Desktop/flow_ai/analytics-cubejs/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryCache.js:262:17`

The component that fails it
@cubejs-backend/postgres-driver - 0.21.1 (also found the same issue with 0.20.13)

Catching the error when just starting using the cubejs, it happened after updating the version of @cubejs-backend/postgres-driver. Stable version for me is 0.13.9

**CUBEJS_DB_SSL** is `false`

**Comment by ovr** [comment]
Hello @horidon,

1. Did you configure `PostgresDriver` by creating a new instance inside `js` file?

2. Did you set any env variable related SSL (because they can enable SSL for the connection)?

- `CUBEJS_DB_SSL_REJECT_UNAUTHORIZED`
- `CUBEJS_DB_SSL_CA`
- `CUBEJS_DB_SSL_CERT`
- `CUBEJS_DB_SSL_CIPHERS`
- `CUBEJS_DB_SSL_PASSPHRASE`

Thanks

**Comment by horidon** [comment]
Hi @ovr 
1. It's configured by cube js, from our side we provided CUBEJS_DB_TYPE: postgres
2. CUBEJS_DB_SSL: false; only it is set. I didn't set the any related variables to ssl

**Comment by ovr** [comment]
@horidon

I found an issue; We don't check that `CUBEJS_DB_SSL` is `true`. 
i.e We check that value is defined without taking a look at the value and comparing it with `true`. (I prepared a PR with a fix)

For now, I recommend you to drop the line with `CUBEJS_DB_SSL: false`.
Is it working for you?

Thanks

**Comment by sourav-jha** [comment]
Getting the same issue. I haven't added `CUBEJS_DB_SSL ` env.
cubejs version:0.26.99
