### ISSUE TITLE
Error when using boolean operators in filters

### ISSUE THREAD

**Issue by Manny91** [cube-js/cube.js#1242]
Hello I'm trying to use the new boolean operator and I'm having the following issue

**Describe the bug**
cubejs-client-core.js crashes when having a filter that uses the `and` and `or`  boolean operators
**To Reproduce**
Using <QueryBuilder> React Component and having a filter that uses the `or` and `and` operator an error happens and it crashes

**Expected behavior**
It should send the query object correctly

**Screenshots**
this is printing in console just the filters object
![image](https://user-images.githubusercontent.com/2591222/97012880-41258400-1540-11eb-9517-5c46d251839e.png)

Error message:
![image](https://user-images.githubusercontent.com/2591222/97012402-bba1d400-153f-11eb-846e-098fbf0d5347.png)

**Version:**
 "@cubejs-client/core": "0.22.1",
    "@cubejs-client/react": "0.22.1",

Am I building correctly the filters? Does anybody came across this issue?

Thanks

**Comment by vasilev-alex** [comment]
Hey, @Manny91! Can you please share the query you're trying to execute?

**Comment by Manny91** [comment]
Hey @vasilev-alex this is the json query Object I'm trying to send but the it crashes in cubejs-client-core side

```
{"measures":["publisher_cube.revenue","publisher_cube.impressions","publisher_cube.fillrate","publisher_cube.cpm"],"dimensions":[],"filters":[{"dimension":"DimPublisher.normalid","operator":"equals","values":["d88c7d36-032f-4194-ac97-e37e406d1ab9"]},{"or":[{"and":[{"member":"DimApp.normalid","operator":"equals","values":["fe9cdc5f-7794-40e1-ade3-fd967d07043f"]},{"member":"publisher_cube.appver","operator":"equals","values":["-1"]}]},{"and":[{"member":"DimApp.normalid","operator":"equals","values":["0f746a89-f776-403d-90e0-ef8e1d359373"]},{"member":"publisher_cube.appver","operator":"equals","values":["0"]}]}]}],"timeDimensions":[{"dimension":"DimDate.date","granularity":null}]}```

it is due the filter
```
{"or":[{"and":[{"member":"DimApp.normalid","operator":"equals","values":["fe9cdc5f-7794-40e1-ade3-fd967d07043f"]},{"member":"publisher_cube.appver","operator":"equals","values":["-1"]}]},{"and":[{"member":"DimApp.normalid","operator":"equals","values":["0f746a89-f776-403d-90e0-ef8e1d359373"]},{"member":"publisher_cube.appver","operator":"equals","values":["0"]}]}]}```

am I using the operators right?

Thanks

**Comment by vasilev-alex** [comment]
I've merged a fix that will prevent crashing the Playground, but the full boolean filters support is still in progress.

**Comment by Ksmike** [comment]
@vasilev-alex any follow up on when the boolean filter support will be in production?

**Comment by Manny91** [comment]
hey @vasilev-alex is there any plans for this boolean filter to be supported in production any time soon?

**Comment by vasilev-alex** [comment]
hey @Manny91! Are you talking about support in the Playground?

**Comment by Manny91** [comment]
if with Playground means frontend yes!

**Comment by Manny91** [comment]
Sorry @vasilev-alex, let me explain, my issue was when trying to use the filters in my react app it caused the error linked above, so I just wanted to double check if that will be supported any time soon

**Comment by vasilev-alex** [comment]
@Manny91 could you please post the query? I assume you're using the `useCubeQuery` hook?

**Comment by Manny91** [comment]
@vasilev-alex this was the query I was using where I found the error commented above
``` {"measures":["publisher_cube.revenue","publisher_cube.impressions","publisher_cube.fillrate","publisher_cube.cpm"],"dimensions":[],"filters":[{"dimension":"DimPublisher.normalid","operator":"equals","values":["d88c7d36-032f-4194-ac97-e37e406d1ab9"]},{"or":[{"and":[{"member":"DimApp.normalid","operator":"equals","values":["fe9cdc5f-7794-40e1-ade3-fd967d07043f"]},{"member":"publisher_cube.appver","operator":"equals","values":["-1"]}]},{"and":[{"member":"DimApp.normalid","operator":"equals","values":["0f746a89-f776-403d-90e0-ef8e1d359373"]},{"member":"publisher_cube.appver","operator":"equals","values":["0"]}]}]}],"timeDimensions":[{"dimension":"DimDate.date","granularity":null}]}```

this was causing cubejs-client-core.js  to crash when having a filter that uses the and and or boolean operators

**Comment by vasilev-alex** [comment]
@Manny91 that is a valid query. Which Cube.js version are you using?
