### ISSUE TITLE
Error: Dialect for 'undefined' is not found

### ISSUE THREAD

**Issue by alexeygolyshev** [cube-js/cube.js#1247]
**cube.js 0.22.2**

Even the test example doesn't work. Worked in 0.21.1. How to change the installable version during `cubejs create <project name> -d <database type>`?

![Untitled](https://user-images.githubusercontent.com/6998329/97183004-4e47aa80-17ae-11eb-8186-115a23d9319d.png)

**Comment by ovr** [comment]
Hello @alexeygolyshev,

Yes, I can approve. It's a bug in the latest version.

Please use `0.22.1` (without `^`) version for `@cubejs-backend/server`.

1. Change package.json
2. `rm -rf node_modules/ package.lock`
3. `npm install`

**Comment by ovr** [comment]
Fixed, released `v0.22.3` 🍰

**Comment by alexeygolyshev** [comment]
@ovr Thanks for the quick fix!

**Comment by ovr** [comment]
@alexeygolyshev You are welcome. Thank you for creating the issue.

Feel free to create issue(s) or post messages inside our Slack.
Link to join https://slack.cube.dev/.
