### ISSUE TITLE
Warning: Attribute filter.dimension is deprecated - appears at every query

### ISSUE THREAD

**Issue by sstefan97** [cube-js/cube.js#1268]
Hi! What do you think about turning this warning: 'Warning: Attribute filter.dimension is deprecated. Please use 'member' instead of 'dimension', into a console.info?. Since it appears on each request, even though in the query filter the new operator name 'member' is used, I consider it to be more of an informative message than a warning. It's helpful also for logging, where you want to filter out only warnings, and this message appears too much. Thanks!

**Comment by vasilev-alex** [comment]
Hey, @sstefan97! Thanks for posting it here.
