### ISSUE TITLE
Post processing results on server side

### ISSUE THREAD

**Issue by rawpixel-vincent** [cube-js/cube.js#1286]
**Is your feature request related to a problem? Please describe.**
Being able to optionally transform a set of results on the server side (after caching or before caching, to discuss).

**Describe the solution you'd like**
Given a specific cube.js server request, I should be able to hook into the set of results and transform it. 

**Describe alternatives you've considered**
- Making the request to other service(s) after getting the set of results from the cube.js server on the frontend
- Create a table to hold the data we need to render the set of results (so we could join the data on the schema/query side)

**Additional context**
In our use case, transforming the set of results directly within the cube.js server would be the more efficient way to do it.

**Comment by paveltiunov** [comment]
@rawpixel-vincent Hey Vincent! Thanks for posting this! Let's use this issue to collect use cases to address this issue in the best possible way. Would love to hear yours and other people use cases!

**Comment by rawpixel-vincent** [comment]
We use cube.js to render a bunch of table that shows a top hundreds entities for whatever metrics, so we'd like to call other services running on the same network server side to enrich those table (using the cube.js tasks)
But I think I found a way to do that and will post here once I tried

**Comment by paveltiunov** [comment]
@rawpixel-vincent That makes sense. Would love to hear about the approach you try! So is a challenge basically to run your service for records in Cube.js result set?

**Comment by rawpixel-vincent** [comment]
cool, I saw you are planning to migrate the express server integration to a micro service architecture. So what I suggest would not work.
Anyway, what I want to do would solve that issue, I want to call the cube.js service from another service on the same network. So is there a way to call the cube.js service from the server side, not using cube.js client api?

**Comment by rawpixel-vincent** [comment]
no problem.., I can use the cube.js client https://cube.dev/docs/@cubejs-client-core and implement what i want on my service..
