### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by philippefutureboy** [cube-js/cube.js#129]
**Is your feature request related to a problem? Please describe.**
I'm currently setting up a TDD flow for cubejs. I have two questions:

1. What would one test with regards to cubejs? So far on my side I think that testing the schemas for proper output seems to be a good rule of thumb.
2. Is there already a mechanism integrated to cubejs for testing?

**Describe the solution you'd like**
Cubejs provides an npm command that allows to run test against a mock database. Doesn't require extra setup bar installing dependencies (and potentially having docker/docker-compose) installed.

**Describe alternatives you've considered**
I've implemented a docker-compose setup with jest for integration testing (e2e). It runs cube in its own docker environment and uses jest to fill the database, issue queries using `@cubejs-frontend/core`, and test the result. Now I was wondering if there would be a way for such flow to be either done without a database, or done similarly, but without the need for extra setup like I did.

**Additional context**
If you are interested I can share my test setup repository :)

**Comment by philippefutureboy** [comment]
Heyo!! I've added my test setup repository!

https://github.com/arthurintelligence/cubejs-test

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! Thanks for sharing! 

That's really great question. So with schema compiler we use exactly same approach: integration tests which fill the database, run queries and test query results. Hard part here is you always need a database because cube.js schema most of times is DB specific. There was discussion about driver test suite while clickhouse implementation. I think it should be a separate package for testing cube.js which sets up environment like docker, loads the fixture to db and executes queries.

**Comment by philippefutureboy** [comment]
@paveltiunov Hey Pavel! Thanks for your answer :)

> Hard part here is you always need a database because cube.js schema most of times is DB specific. 

Agreed, but we can generate docker-compose configurations dynamically and then create the containers on the fly.

> There was discussion about driver test suite while clickhouse implementation. 

How would clickhouse help with SQL dialect specificity?

> I think it should be a separate package for testing cube.js which sets up environment like docker, loads the fixture to db and executes queries.

Agreed, I think that would be the optimal workflow. A package which reads your current configuration and can act as the test agent for your codebase. It would dynamically manage your docker environments based on a configuration file or by executing the `index.js` with mocked drivers to determine the configurations (I'd opt for a config file, easier to implement and maintain). 

Do you think my repo could be a good basis to start building that package? You most likely have something more thorough internally - would be great to see what you have in store

🚀

**Comment by paveltiunov** [comment]
@philippefutureboy I mean it was discussed here a little bit: https://github.com/statsbotco/cube.js/pull/98.

Yeah. We was thinking about it internally and here's the list of requirements for such test package we came up with:
1. Should be test framework agnostic.
2. Should provide simple API to init database, fill it with provided fixture, run query and then tear down it.
3. Ideally `server-core` shouldn't be involved here otherwise it complicates testing. Test package should use driver, `schema-compiler` and optionally `api-gateway` to create concurrency free testing environment.

**Comment by philippefutureboy** [comment]
1. How do you intend to make it test-framework agnostic?
2. By simple API to init db, you mean that each test suite would be able to create a db within the database instance?
3. How does server-core complicate things when involved?

**Comment by paveltiunov** [comment]
@philippefutureboy 
I was thinking about following interface:
```js
const cubejsTest = new CubejsTest({
  prepareFixture: (driver) => {}, // use driver to prepare fixture
  // various common params for CubejsServerCore goes here like driverFactory if required
  // based on a driver provided appropriate DB container should be started
});

describe('Visitors', function test() {
  this.timeout(20000);

  after(async () => {
    await cubejsTest.tearDown();
  });

  it('should calculate revenue', async () => {
    // here's the case with lazy init
    // on first runQuery call container should be started, filled with fixture and then query should be executed
    const result = await cubejsTest.runQuery({
      measures: [
        'visitors.visitor_revenue'
      ],
      dimensions: ['visitor_checkins.cardsCount'],
      timezone: 'America/Los_Angeles',
      order: [{
        id: 'visitor_checkins.cardsCount'
      }]
    });
      
    result.should.be.deepEqual([
      {
        "visitor_checkins.cards_count": "0",
        "visitors.visitor_revenue": "300"
      },
      {
        "visitor_checkins.cards_count": "1",
        "visitors.visitor_revenue": "100"
      },
      {
        "visitor_checkins.cards_count": null,
        "visitors.visitor_revenue": null
      }
    ]);
  });
});
```
So answering to your questions:
1. Please refer to example above. Even if we use test framework there's no actual depend from `CubejsTest` itself.
2. No as most of tests are read-only. For those ones which require pre-aggregations temp tables should be used behind the scenes.
3. `server-core` uses `query-orchestrator` which is caching, renewing data and maintains query execution queue. All of that can create various race conditions during the tests.

**Comment by philippefutureboy** [comment]
So if I understand properly, what you propose is to have a library CubejsTest that receives the same drivers and options as CubejsServerCore, but that is also responsible for spinning their own container for the database. 
While you say that most tests are read-only, there's still a need to setup the data in the tables. Different tests may require different datasets, and you wouldn't want two tests to collide. Plus what happens when you teardown in one test? Does it wait for the other tests to resolve before tearing down?

Hence I think that for every CubejsTest instance, a new container would be spun up.
However does that scale? If not, is there an optimization that can be done by creating only one container for each type of driver employed and then simply address different database names/documents?

**Comment by paveltiunov** [comment]
@philippefutureboy 
> So if I understand properly, what you propose is to have a library CubejsTest that receives the same drivers and options as CubejsServerCore, but that is also responsible for spinning their own container for the database.

Yep. Right.

> While you say that most tests are read-only, there's still a need to setup the data in the tables. Different tests may require different datasets, and you wouldn't want two tests to collide. Plus what happens when you teardown in one test? Does it wait for the other tests to resolve before tearing down?

That's a great question. I guess we need to manage containers inside `CubejsTest` instance and not statically. This way you can use different environments for different tests without collisions on one hand and re-use environment when we need to on other hand. Usually tests are run by all test frameworks consequently. If there's some sort of concurrency there it can be solved using teardown mutex or something like this.

>Hence I think that for every CubejsTest instance, a new container would be spun up.

Yes. Right.

> However does that scale? If not, is there an optimization that can be done by creating only one container for each type of driver employed and then simply address different database names/documents?

You can re-use single `CubejsTest` for all tests within a project or at least for a test suite. We have already tests that work with this level granularity and it seems to be working solution.

We would love if you can contribute such test package.

Thanks!

**Comment by philippefutureboy** [comment]
@paveltiunov I'd be happy to do so! How can I be of help?

Also, I attended a JS meetup Tuesday, and turns out the subject was about testing JS/React/GraphQL using Jest/Enzyme. Given the similarities between your @cubejs-client/react interface and the one provided by GraphQL, I think Cubejs React would benefit to emulate the GraphQL structure when it comes to testing => https://www.apollographql.com/docs/react/recipes/testing/#mockedprovider

What do you think?

Have a great day ✨

Phil

**Comment by paveltiunov** [comment]
@philippefutureboy I mean if you got the idea you can contribute such package to cube.js repository. We'll release it under `@cubejs-backend` then.

> Also, I attended a JS meetup Tuesday, and turns out the subject was about testing JS/React/GraphQL using Jest/Enzyme. Given the similarities between your @cubejs-client/react interface and the one provided by GraphQL, I think Cubejs React would benefit to emulate the GraphQL structure when it comes to testing.

I think it's neat idea. We're still figuring out what should be tested on frontend side as well so it worth considering.

Thanks!

**Comment by philippefutureboy** [comment]
Great! Will get started sometime next week :)

**Comment by philippefutureboy** [comment]
@paveltiunov I'm going through the cubejs-backend/* codebase right now, and I can't seem to find a test suite for the code. Do you have any tests & CI/CD pipeline?

**Comment by paveltiunov** [comment]
@philippefutureboy Most of tests are in `cubejs-schema-compiler` package. We don't have CI but we test before each release. Need to setup one for sure.

**Comment by philippefutureboy** [comment]
@paveltiunov I think that should be a major priority – your clients as well as those using cube.js as part of their project most likely use cube in production deployments. What happens if in a new patch there is a bug that is inserted? How do you know about regressions?

I'd volunteer to add a few tests here and there, but I don't know the internals of cube.js. If you are ready to provide me with BDD-style tests (`[given x,] should do y`) and descriptions of the expected behaviour, I can try my hand at helping you raise your test coverage during my spare time.
It would take priority over @cubejs-backend/server-test package however.

**Comment by paveltiunov** [comment]
@philippefutureboy That's really great point. The thing is cube.js right now has 2 components with decent amount of logic. These are schema-compiler and query-orchestrator. First one is heavily tested and at least 90% test covered. The second one is heavily tested in production environments and since it was open sourced there were no major changes to core components. There's 30-40% test coverage for query-orchestrator. And other backend components are merely wiring code.

We definitely need to increase code coverage. And I think we should start adding tests as new code changes come in or new regressions are spotted. Given current code base is tested by production deployments which manage over a dozen trillions of data points in total this lazy test adding approach seems something we can afford right now.

**Comment by philippefutureboy** [comment]
As for `@cubejs-backend/server-test`, here is my early assessment:

## Requirements

### Skeleton

* Support all of the normal properties of CubejsServer.create config
* Implement all of the normal CubejsServer API
* Implement a supplementary API for preparing fixtures & teardown
* Implement necessary API to run query.

### Muscles

* Support multitenancy

### Skin

* Efficiency in docker resource usage
* Optimization of test time

## Challenges

1. Implementing all of the features of CubejsServer as well as its API means that creating an external package will create a duplicate codebase and lead to issues and inconsistencies over time.
2. The driverFactory option introduces a great amount of complexity since we do not know until runtime which drivers will be used. 
3. Some users will be using parallel-running testing software, such as jest & AVA. This can lead to issues regarding spinning-up and tearing-down resources. 
  * in order to optimize resources, only one container per image should be spun up.
  * containers shouldn't be shut down during the execution of the test runs.
  * the process managing the container state shouldn't be delimited by any one of the test runs, and as such should be an independent process.
4. The tests should not interfere with each other. Some tests may require different datasets from each other, even on the same table.

## Early suggestions/solutions

1. @cubejs-backend/server-test should be a thin wrapper around @cubejs-backend/server-core or server, with most of the test harness functionalities are implemented as part of server-core and api-gateway, either as flag-enabled functionalities or as optional, low-level options passed to the constructor.
2. Options explored:
  * Dynamically parse the test files and all imports to determine the dependency tree and extract the cubejs modules loaded. See [dependency-tree](https://www.npmjs.com/package/dependency-tree). The issue with this solution is that it has to take in account the babel/webpack/typescript configs, thereby greatly increasing the complexity.
  * Create a js script like create-react-app around testing to setup the cubejs container manager. Advantages: can make spinning up a test-run independent process easier. Disadvantages: requires more setup from the user's perspective, and may interfere with their scripts.
  * Require the configuration of a `.cubejsrc` or `.cubejsrc.js` file which will provide the necessary configuration for the test harness to determine which containers to spin up. Obviously preferably this should be read before the test runs as a setup script, but we don't necessary always have that luxury.
3. Optimally if we had access to a setup script, the external process managing all the docker containers would spin-up all the containers from the .cubejsrc config before the tests are run. However I think it would be safer to assume that setup scripts will not necessarily be possible. As such the first CubejsTest instance should be tasks with starting the orchestrator process. Now this can result in a race condition, and I'm not too sure how to address that. Another option to consider is to add a pre/post test script that start and stops the container orchestrator service.
4. To avoid conflict between tests that do not need the same fixtures, I suggest to dynamically create new schemas within the database instance for each test. If we can get the name of the currently executing test we can use it to generate a hashed name for the schema/tables, and also dynamicallly transform the queries/cubes to reflect these new schema/table names.

## What does this mean implementation-wise?

* Create a new module specifically dedicated to the container orchestration service
* For each driver, or at least as part of `BaseDriver`, wrap the configuration into an object/type that will query the container orchestration service for the proper connection config and use these to override the user-passed config.
* The ApiGateway should be called with a mock of express, and the endpoint should be available by calling the `runQuery` method or equivalent.


## To take in account

* All of this would be greatly simplified if you opt for the create-react-app direction and just decide on which test framework is to be used (**cough** _jest_) and you build the best DX with your choices. You could leverage your cli much more that way. 
* These test functionalities should be provided as part of the boilerplate generated by the CLI.
 

So what do you think?

**Comment by paveltiunov** [comment]
@philippefutureboy First of all it's pretty decent research! Thanks for posting it. Overall the direction is correct.
Some thoughts and questions:
1. If we want to wrap `server-core` which is very interesting and promising idea we'd need to implement query-orchestrator for test purpose. As I mentioned earlier we need this to solve caching, concurrency and pre-aggregations issues in test environment.
2. What's the reason for "Dynamically parse the test files and all imports"?
3. For now we can provide scaffolding for some specific test framework. server-test itself won't have any dependencies on test frameworks.

**Comment by philippefutureboy** [comment]
@paveltiunov Thanks for your answers :)

> And other backend components are merely wiring code. [...] Given current code base is tested by production deployments which manage over a dozen trillions of data points in total this lazy test adding approach seems something we can afford right now.

This does not guarantee that the software is defect-free or that it will remain so. I understand however your position given time & money restrictions. My suggestion goes alongside yours: In order to ensure testing of new changes brought to the codebase, I'd suggest to add a git hook pre-commit that runs the test and ensures that the changed part has been covered.

> Some thoughts and questions:

1. **Caching:** Can we decouple caching from the query-orchestrator? I'd suggest in-memory caching like with [node-cache](https://www.npmjs.com/package/node-cache) or something similar that implements the interface you need. **Concurrency:** I'll need more details as to what are the responsibilities of the query-orchestrator in that regard before commenting on it. Could you also provide me with the lines in the codebase where this is taken care of? **Pre-aggregation:** Would this be an issue at all? I mean pre-aggregation can be performed directly on the database, right? Unless it is automatic and we need to delay it until the containers are ready, which shouldn't be too much of an issue.
2. To find which @cubejs-backend drivers where required by the currently executing scripts ahead of time, so that we can prepare the containers for that. For the reasons explained above, I'd opt for a `.cubejsrc` file instead.
3. Agreed. I don't think that server-test should have a dependency directly on a test framework either. I was simply pointing out that the inclusion of a setup file like jest's [setupFiles](https://jestjs.io/docs/en/configuration#setupfiles-array) configuration point is not necessarily something that is as easily implemented for other test frameworks, and as such may disadvantage those using other test frameworks. Given this, we can either go forward with that kind of setup and provide scaffolding for most of the popular test frameworks, provide scaffolding only for those that are easy to setup, or drop the idea of a setup file entirely and do the container orchestration from within the first call to CubejsTest.

Did I answer your questions? Is there anything you would like to address?

**Comment by paveltiunov** [comment]
@philippefutureboy 
1. We can bypass caching by providing implementation that doesn't cache. query-orchestrator much harder to bypass. In fact it's queue and fail over for query execution. Pre-aggregations have same semantics as cache. So you need a way to have pre-aggregations created each time they called instead of reused.
2. I think we can instantiate containers in lazy manner: when we know actual `dbType`.

Yeah. `learna` is cool.

**Comment by philippefutureboy** [comment]
@paveltiunov 

>  In fact it's queue and fail over for query execution. 

Can you elaborate?

> I think we can instantiate containers in lazy manner: when we know actual dbType.

If that's the route you wish to take we can do it that way. I felt like having a `.cubejsrc` was the most interesting option given that it can allow to specify all the containers to start at once, and then all tests can proceed.

I found a potential solution for the container orchestration service (COS) creation race condition: If the  COS binds a single port per test suite, then the resource can only belong to one instance of the COS, making the other ones crash and return an error to the main process.

**Comment by paveltiunov** [comment]
@philippefutureboy 
> Can you elaborate?
So it manages query execution queue. It also checks for timeouts, orphaned queries, prioritization, cancellation, etc. 

> If that's the route you wish to take we can do it that way. I felt like having a .cubejsrc was the most interesting option given that it can allow to specify all the containers to start at once, and then all tests can proceed.
I believe dbType can be extracted from .env for testing.

**Comment by philippefutureboy** [comment]
@paveltiunov Heyo! I just wanted to let you know that I haven't forgotten this issue, and I'll be contributing as soon as possible. Estimate +1-2 week before I start working on this (at a rate of 15 hours per week)

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! Sounds great! Thanks!

**Comment by philippefutureboy** [comment]
@paveltiunov Yay! I'm done working on the project I was working on, [savetube](https://github.com/philippefutureboy/savetube).

I'm now ready to tackle this task 🎉
