### ISSUE TITLE
Support "Authorization: Bearer xxx" token passing format in cubejs-api-gateway

### ISSUE THREAD

**Issue by joshk0** [cube-js/cube.js#1297]
**Is your feature request related to a problem? Please describe.**

It is idiomatic for JWTs to be accepted using a header format of `Authorization: Bearer <JWT>` (see [jwt.io introduction](https://jwt.io/introduction/).) In general, in history, the RFCs surrounding the authorization header have taken care to specify the mode of Authorization as the first part of the header value (e.g. Basic, Digest et al.) See [RFC 2617](https://tools.ietf.org/html/rfc2617) and [RFC 6750](https://tools.ietf.org/html/rfc6750).

However, according to Cube.js [docs](https://cube.dev/docs/rest-api), you in fact must pass the token as a bare string in the Authorization header. Since you do use JWTs idiomatically, people will naturally be drawn to specifying the Authorization header as a Bearer token.

**Describe the solution you'd like**
In cubejs-api-gateway, please support the use of the idiomatic `Authorization: Bearer xxx` method of passing JWTs into a webservice.

**Describe alternatives you've considered**
If you had a reason to want the key passed as a bare string, you could come up with an unofficial header key and value, such as X-Cubejs-JWT. Then there would be no expectations around what format that header would have and people would double check before using the API.

**Comment by hassankhan** [comment]
Interestingly, AWS Cognito does not use the `Authorization: Bearer <JWT>` format either.

**Comment by paveltiunov** [comment]
@joshk0 Hey Joshua! Thanks for posting it! It's really small change and we're looking for a volunteer to contribute this.
