### ISSUE TITLE
Import cubejs from '@cubejs-client/core'; error

### ISSUE THREAD

**Issue by dtslvr** [cube-js/cube.js#13]
Hi all,

I'm trying the VanillaJS Javascript integration (inside of an Angular component built with Angular CLI):

```
import cubejs from '@cubejs-client/core';
import Chart from 'chart.js';
import chartjsConfig from './toChartjsData';

@Component({
  selector: 'home',
  templateUrl: './home.html'
})
export class HomeComponent implements OnInit {

  public ngOnInit() {

    const cubejsApi = cubejs('dd44575826bc7113dbbbd06e7f490a5030f42c630da052913499956b6c20a993a9c72655f0c1d3921bad8b1047b411ed8f426d6342d526e082176aadc41a3e49');

    const resultSet = await cubejsApi.load({
       measures: ['Stories.count'],
       timeDimensions: [{
         dimension: 'Stories.time',
         dateRange: ['2015-01-01', '2015-12-31'],
         granularity: 'month'
       }]
    });

    const context = document.getElementById('myChart');
    new Chart(context, chartjsConfig(resultSet));
  }
}
```

But at `cubejs(...)` I get the following error: ```Uncaught Error: Uncaught (in promise): TypeError: core_2.default is not a function```

When I change the import to ```import * as cubejs from '@cubejs-client/core';``` it's fine.

**Comment by paveltiunov** [comment]
@dtslvr thanks for posting this! Seems like it's dependent on webpack settings. @keydunov I believe we've already seen this before somewhere?

**Comment by keydunov** [comment]
@paveltiunov Yes, I have seen it before with webpack `4.27.0`. Now, I'm running app with webpack `4.28.3` with no issue.
 
It could be related to https://github.com/webpack/webpack/issues/6584

@dtslvr What is your webpack version?

**Comment by dtslvr** [comment]
Hmm, I'm using it with [Angular CLI](https://cli.angular.io) and it does not seem to use Webpack anymore :thinking:

**Comment by vasilev-alex** [comment]
Apparently not relevant anymore as it works fine with the latest version. Closing the issue.
