### ISSUE TITLE
Mulitple PreAggregation tables are getting created for same query instead of updating the existing one.

### ISSUE THREAD

**Issue by manikasharma70** [cube-js/cube.js#1308]
Hi Team,
I am trying to create the pre-aggregation for a cube.

cube(`Application`, {
// sql:`SELECT idx,from_unixtime(servertime,'%y-%m-%dT%H:%i:%s') as 'servertime',customer,machine,username, text1->>'$.AverageQueueLength' AS 'AverageQueueLength', text1->>'$.InterruptRatePerSecond' AS 'InterruptRatePerSecond', text1->>'$.PercentUtilization' AS 'PercentUtilization', text3->>'$.ProcessImageName' AS 'ProcessImageName', text3->>'$.processmemusage_Kb' AS 'processmemusage_Kb', text3->>'$.processsize' AS 'processsize',text3->>'$.ProcessMemUsagePercent' AS 'ProcessMemUsagePercent'  from event.Events where scrip = 96 and customer = 'DEVTEST' and machine= 'QA-L2-WIN10' limit 10`,
sql:`SELECT idx,from_unixtime(servertime,'%y-%m-%dT%H:%i:%s') as 'servertime',customer,machine,username, text1->>'$.AverageQueueLength' AS 'AverageQueueLength', text1->>'$.InterruptRatePerSecond' AS 'InterruptRatePerSecond', text1->>'$.PercentUtilization' AS 'PercentUtilization', text3->>'$.ProcessImageName' AS 'ProcessImageName', text3->>'$.processmemusage_Kb' AS 'processmemusage_Kb', text3->>'$.processsize' AS 'processsize',text3->>'$.ProcessMemUsagePercent' AS 'ProcessMemUsagePercent'  from event.Events where scrip = 96 and customer = 'TJX_testing' limit 100`,
sqlAlias: `appDash`,
refreshKey: {
every: `60 second`
},
joins: {
     GroupsMachines:{
       relationship: 'hasMany',
       sql: `${GroupsMachines}.host = ${CUBE}.machine`
   }
  },
measures:{
InterruptRatePerSecond: {
type: `avg`,
sql: `InterruptRatePerSecond`,
title: `Interrupt Rate Per Second`
},
// drive: {
// type: `avg`,
// sql: `drive`,
// title: `Drive`
// },
PercentUtilization: {
type: `avg`,
sql: `PercentUtilization`,
title: `% Utilization - CPU`
},
processmemusage_Kb: {
type: `avg`,
sql: `processmemusage_Kb`,
title: `Memory usage in Kb`
},
// ProcessMemUsagePercent: {
// type: `avg`,
// sql: `ProcessMemUsagePercent`,
// title: `Memory Usage %`
// },
processsize: {
type: `avg`,
sql: `processsize`,
title: `Size`
},
AverageQueueLength: {
  type: `avg`,
  sql: `AverageQueueLength`,
  title: `Average Queue Length`
}
},
dimensions:{
  idx:{
    sql: `idx`,
    type: `number`,
    primaryKey: true
  },
ProcessImageName: {
    type: `string`,
    sql: `ProcessImageName`,
    title: `Process Name`
},
servertime: {
    sql: `servertime`,
    type: `time`,
    title: `Time`
},
site: {
    sql: `customer`,
    type: `string`,
    shown: true
  },

  machine: {
    sql: `machine`,
    type: `string`,
    shown: true
  },

  username: {
    sql: `username`,
    type: `string`
  },

  group: {
    sql: `${GroupsMachines}.name`,
    type: `string`
  }
},
segments:{
},
preAggregations:{
AllMonth: {
  type: `rollup`,
  measureReferences: [AverageQueueLength,InterruptRatePerSecond,PercentUtilization,processmemusage_Kb,processsize],
  dimensionReferences: [site,machine,username],
  timeDimensionReference: servertime,
  granularity: `month`,
  // partitionGranularity: `month`,
  scheduledRefresh: `true`,
  indexes: {
  main: {
  columns: [site,machine,username],
  }
  }
  }
}
});

The query used is :
query: {"measures":["Application.InterruptRatePerSecond","Application.PercentUtilization","Application.processmemusage_Kb","Application.processsize","Application.AverageQueueLength"],"timeDimensions":[{"dimension":"Application.servertime","granularity":"month","dateRange":"This year"}],"order":{"Application.InterruptRatePerSecond":"desc"},"dimensions":["Application.machine","Application.username","Application.site"],"filters":[],"renewQuery":true}

And if m using the same schema for the same duration , then instead of doing a select query in the already created table, it is creating new table on each query.

Tables_in_stb_pre_aggregations:
"app_dash__all_month_dvtpog2n_mcktltrd_1604475613183"
"app_dash__all_month_njn0psad_mcktltrd_1604475590130"
"app_dash__all_month_r3uoisir_mcktltrd_1604475699075"
"app_dash__all_month_ufzzplyi_mcktltrd_1604475811109"

Please help to resolve this issue.

**Comment by paveltiunov** [comment]
@manikasharma70 It's how pre-aggregations behave. Please see https://cube.dev/docs/pre-aggregations#pre-aggregations-garbage-collection
