### ISSUE TITLE
Creating pre aggregation table in mysql sometimes throw the following error

### ISSUE THREAD

**Issue by manikasharma70** [cube-js/cube.js#1310]
I have tried to create pre aggregations using the following cube:

cube(`Application`, {
// sql:`SELECT idx,from_unixtime(servertime,'%y-%m-%dT%H:%i:%s') as 'servertime',customer,machine,username, text1->>'$.AverageQueueLength' AS 'AverageQueueLength', text1->>'$.InterruptRatePerSecond' AS 'InterruptRatePerSecond', text1->>'$.PercentUtilization' AS 'PercentUtilization', text3->>'$.ProcessImageName' AS 'ProcessImageName', text3->>'$.processmemusage_Kb' AS 'processmemusage_Kb', text3->>'$.processsize' AS 'processsize',text3->>'$.ProcessMemUsagePercent' AS 'ProcessMemUsagePercent'  from event.Events where scrip = 96 and customer = 'DEVTEST' limit 100`,
sql:`SELECT idx,from_unixtime(servertime,'%y-%m-%dT%H:%i:%s') as 'servertime',customer,machine,username, text1->>'$.AverageQueueLength' AS 'AverageQueueLength', text1->>'$.InterruptRatePerSecond' AS 'InterruptRatePerSecond', text1->>'$.PercentUtilization' AS 'PercentUtilization', text3->>'$.ProcessImageName' AS 'ProcessImageName', text3->>'$.processmemusage_Kb' AS 'processmemusage_Kb', text3->>'$.processsize' AS 'processsize',text3->>'$.ProcessMemUsagePercent' AS 'ProcessMemUsagePercent'  from event.Events where scrip = 96
    and ${USER_CONTEXT.site.filter('customer')} and ${USER_CONTEXT.machine.filter('machine')} 
    and machine IN (select distinct(host) from core.Census where censusuniq IN (select censusuniq from core.MachineGroupMap 
    where mgroupuniq IN (select mgroupuniq from core.MachineGroups where ${USER_CONTEXT.group.filter('MachineGroups.name')})))`,
// sql: `SELECT idx,from_unixtime(servertime,'%y-%m-%dT%H:%i:%s') as "servertime",customer,machine,username, ${iter.selecttext} from event.Events where scrip = ${iter.scripno} and ${USER_CONTEXT.site.filter('customer')} and ${USER_CONTEXT.machine.filter('machine')} and machine IN (select distinct(host) from core.Census where censusuniq IN (select censusuniq from core.MachineGroupMap where mgroupuniq IN (select mgroupuniq from core.MachineGroups where ${USER_CONTEXT.group.filter('MachineGroups.name')})))`,
sqlAlias: `appDash`,
refreshKey: {
every: `60 second`
},
joins: {
     GroupsMachines:{
       relationship: 'hasMany',
       sql: `${GroupsMachines}.host = ${CUBE}.machine`
   }
  },
measures:{
InterruptRatePerSecond: {
type: `avg`,
sql: `InterruptRatePerSecond`,
title: `Interrupt Rate Per Second`
},
// drive: {
// type: `avg`,
// sql: `drive`,
// title: `Drive`
// },
PercentUtilization: {
type: `avg`,
sql: `PercentUtilization`,
title: `% Utilization - CPU`
},
processmemusage_Kb: {
type: `avg`,
sql: `processmemusage_Kb`,
title: `Memory usage in Kb`
},
// ProcessMemUsagePercent: {
// type: `avg`,
// sql: `ProcessMemUsagePercent`,
// title: `Memory Usage %`
// },
processsize: {
type: `avg`,
sql: `processsize`,
title: `Size`
},
AverageQueueLength: {
  type: `avg`,
  sql: `avgqu`,
  sql: `AverageQueueLength`,
  title: `Average Queue Length`
}
},
dimensions:{
  idx:{
    sql: `idx`,
    type: `number`,
    primaryKey: true
  },
ProcessImageName: {
    type: `string`,
    sql: `ProcessImageName`,
    title: `Process Name`
},
servertime: {
    sql: `servertime`,
    type: `time`,
    title: `Time`
},
site: {
    sql: `customer`,
    type: `string`,
    shown: true
  },

  machine: {
    sql: `machine`,
    type: `string`,
    shown: true
  },

  username: {
    sql: `username`,
    type: `string`
  },

  group: {
    sql: `${GroupsMachines}.name`,
    type: `string`
  }
},
segments:{
},
preAggregations:{
// AllHour: {
//   type: `rollup`,
//   measureReferences: [AverageQueueLength,InterruptRatePerSecond,PercentUtilization,processmemusage_Kb,processsize],
//   dimensionReferences: [site,machine,username],
//   timeDimensionReference: servertime,
//   granularity: `hour`,
//   scheduledRefresh: `true`,
//   indexes: {
//   main: {
//   columns: [site,machine,username],
//   }
//   }
// },
AllDay: {
  type: `rollup`,
  // measureReferences: [AverageQueueLength,InterruptRatePerSecond,PercentUtilization,processmemusage_Kb,processsize],
  measureReferences: [PercentUtilization],
  dimensionReferences: [site],
  timeDimensionReference: servertime,
  granularity: `day`,
  scheduledRefresh: `true`,
  indexes: {
  main: {
  columns: [site],
  }
  }
},
// AllWeek: {
//   type: `rollup`,
//   measureReferences: [AverageQueueLength,InterruptRatePerSecond,PercentUtilization,processmemusage_Kb,processsize],

//   dimensionReferences: [site,machine,username],
//   timeDimensionReference: servertime,
//   granularity: `week`,
//   scheduledRefresh: `true`,
//   indexes: {
//   main: {
//   columns: [site,machine,username],
//   }
//   }
// },
// AllMonth: {
//   type: `rollup`,
//   measureReferences: [AverageQueueLength,InterruptRatePerSecond,PercentUtilization,processmemusage_Kb,processsize],
//   dimensionReferences: [site,machine,username],
//   timeDimensionReference: servertime,
//   granularity: `month`,
//   scheduledRefresh: `true`,
//   indexes: {
//   main: {
//   columns: [site,machine,username],
//   }
//   }
//   }
}
});

But while running the schema and the table creation the following error is coming:

{"error":"Error: ER_TOO_BIG_FIELDLENGTH: Column length too big for column 'app_dash___percent_utilization' (max = 65535); use BLOB or TEXT instead"}

Can you help me in resolving this please.

**Comment by manikasharma70** [comment]
Please help

**Comment by paveltiunov** [comment]
@manikasharma70 I believe something went wrong with your schema definition and incorrect data has been selected for `app_dash___percent_utilization` column. Could you please try to run pre-aggregation SQL directly in the database and share results here?

**Comment by paveltiunov** [comment]
@manikasharma70 Did you have a chance to figure out what was the issue? Would love to hear what was the cause.
