### ISSUE TITLE
Using the sandbox to create a dashboard doesn't work

### ISSUE THREAD

**Issue by trotha01** [cube-js/cube.js#1318]
**Describe the bug**
When using the sandbox to create a chart, then adding it to the dashboard, causes the error `'query' is not defined`

**To Reproduce**
1. Follow the steps in https://cube.dev/docs/getting-started
2. `cubejs create react-dashboard -d postgres`
3. cd react-dashboard
4. update .env
```CUBEJS_DB_HOST=postgres
CUBEJS_DB_NAME=ecom
CUBEJS_DB_USER=test
CUBEJS_DB_PASS=test
CUBEJS_WEB_SOCKETS=true
CUBEJS_DB_TYPE=postgres
CUBEJS_API_SECRET=SECRET
```
5. uncomment postgres in docker-compose.yml
6. docker-compose up
7. Open localhost:4000
8. Go to "Dashboard App"
9. Select "Material UI D3 Dashboard - Create App"
10. Confirm Dashboard app starts up successfully
11. Go to "Build"
12. Create a chart
13. Select "+ Add to Dashboard"
14. Note the error `'query' is not defined`
15. This can be confirmed by going to the file `src/pages/DashboardPage.js` and noting that query is not defined.

**Expected behavior**
I expect that adding a chart to the dashboard does not cause errors.

**Screenshots**
<img width="892" alt="Screen Shot 2020-11-05 at 11 39 08 AM" src="https://user-images.githubusercontent.com/611431/98288378-c2373f00-1f74-11eb-9040-a759b8316de0.png">

<img width="892" alt="Screen Shot 2020-11-05 at 11 39 32 AM" src="https://user-images.githubusercontent.com/611431/98288375-c19ea880-1f74-11eb-9f33-01b8b43aa47a.png">

**Version:**
```bash
$ cubejs --version
0.23.7
```

**Additional context**

**Comment by vasilev-alex** [comment]
Fixed in `0.23.10`
