### ISSUE TITLE
Parameter sqlAlias doesn't work in subqueries

### ISSUE THREAD

**Issue by frfly** [cube-js/cube.js#1331]
**Describe the bug**
Query builder don't use sqlAlias for subquery aliases. As a result generated aliases are too long and DB truncates them.

**To Reproduce**
Construct cube with sqlAlias and subquery dimension.

**Expected behavior**
Query with shortened aliases for subquery

**Version:**
0.23.10

**Comment by paveltiunov** [comment]
@frfly Thanks for posting this! Currently, this issue is outside of our roadmap so please feel free to contribute it!

**Comment by paveltiunov** [comment]
Should be fixed in the latest release.
