### ISSUE TITLE
Cube-React: updateTimeDimensions accept dateRange or compareDateRange

### ISSUE THREAD

**Issue by BeAnMo** [cube-js/cube.js#1348]
Hi there,

**Is your feature request related to a problem? Please describe.**
I've been working with the react library (namely the "QueryBuilder" component) and have a scenario where I would like to use "compareDateRange" for certain queries. After glancing through the source code, I've found that only "dateRange" is accepted.

**Describe the solution you'd like**
The ability to pass either "dateRange" or "compareDateRange" to an updated object with "updateTimeDimensions".

Thanks for reading

**Comment by paveltiunov** [comment]
@BeAnMo Hey Ben! Thanks for posting this! It's currently out of scope for the current road map but we'd love to see this contribution as a pull request.

**Comment by BeAnMo** [comment]
@paveltiunov was there a test suite for the React client?
