### ISSUE TITLE
How to localize schema

### ISSUE THREAD

**Issue by apuntovanini** [cube-js/cube.js#1360]
**Problem**

How can I localize Cube.he schema? Can I use something like react-intl?

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `` //, ...
  dimensions: {
    name: {
      title: intl.formatMessage({ defaultMessage: "Title" })
    }
  }
})
```

**Comment by paveltiunov** [comment]
@apuntovanini Hey Andrea! Great question! Best practice is to use i18z libraries on the client side. You indeed can use `react-intl` when rendering your tables and charts.

**Comment by apuntovanini** [comment]
So you suggest to use (for instance) the key of the schema as message ID and localize on the front end right? It makes a lot of sense! Thanks!

**Comment by paveltiunov** [comment]
@apuntovanini Yep. Either member name or title.

**Comment by PieterVanZyl-Dev** [comment]
@paveltiunov 

I'm wondering how to localize the labels (translate them)

and I'm unsure how to approach this

I have a solution for handling localization for the titles but not for the labels

I'm doing this in Angular with i18n which compiles everything at compile time (not run time translations)
