### ISSUE TITLE
Websocket security

### ISSUE THREAD

**Issue by aminmc** [cube-js/cube.js#1362]
**Describe the bug**
We have a cubjejs backend configured with keycloak integration which looks like this:
```
    const jwt = require('express-jwt');
    const jwksRsa = require('jwks-rsa');

    cost checkJwt = jwt({
        secret: jwksRsa.expressJwtSecret({
            cache: false,
            rateLimit: true,
            jwksRequestsPerMinute: 5,
            jwksUri: `${config.get('auth.url')}/auth/realms/${config.get('auth.realm')}/protocol/openid-connect/certs`,
        }),
        audience: config.get('auth.audience'),
        issuer: `${config.get('auth.url')}/auth/realms/${config.get('auth.realm')}`,
        algorithms: ['RS256'],
    });

 const cubejsServer = new CubejsServer({
       webSockets: true,
        apiSecret: ' ',
        initApp: (app) => {
            app.use(checkJwt);
            app.use(require('cors')());
            app.use(bodyParser.json({ limit: '50mb' }));
        },
  });


```
At this point the API is secured and if i use a keycloak token then it works as expected.  I have to put apiSecret as the server doesn't start up. 

In the frontend i do the following:

```
 const [keycloak, initialized] = useKeycloak();

<CubeProvider
          cubejsApi={cubejs({
            transport: new WebSocketTransport({
              authorization: `${keycloak.token}`,
              apiUrl: config.get('cubejsApiUrl'),
            }),
          })}
        >
```

keycloak.token = JWT token from keycloak
cubejsApiUrl = ws://localhost:4001

What we're noticing is that if i put any random string in the authorization then the websocket connects successfully.  I would expect an unauthorized exception.

I've raised this issue as requested by @hassankhan.

**Comment by vasilev-alex** [comment]
Hey @aminmc! Are you running the server in production or development mode?

**Comment by aminmc** [comment]
Hey. I'm running in production mode.

**Comment by aminmc** [comment]
Hi @vasilev-alex please let me know if you need any more info or any more code that I can share. We're hoping to demo this stuff to our client sorry to pester.

**Comment by vasilev-alex** [comment]
@aminmc but do the actual `load` requests result in 403?

**Comment by aminmc** [comment]
so..if i do the following:
```
<CubeProvider
          cubejsApi={cubejs({
            transport: new WebSocketTransport({
              apiUrl: config.get('cubejsApiUrl'),
            }),
          })}
        >
```

I get an 401

If I do the following:

```
<CubeProvider
          cubejsApi={cubejs({
            transport: new WebSocketTransport({
              authorization: 'Some random string',
              apiUrl: config.get('cubejsApiUrl'),
            }),
          })}
        >
```

I get the successful websocket connection and data coming through. 

Apparently there is an option to configure something like socket.io but i'm not sure how to configure this.

**Comment by vasilev-alex** [comment]
ok, actually, all express middleware is ignored when used with WebSockets. I'd recommend you, for now, move the authorization logic to the `checkAuth` function https://cube.dev/docs/config#options-reference-check-auth

**Comment by aminmc** [comment]
@vasilev-alex Thanks. Changed it to use checkAuth and it seems to be working.

**Comment by mbkh68** [comment]
Having similar issue, but in my case, normal http request is validated with no issue, but websocket connections returns 
`{messageId: 1, message: {error: "Not authorized"}, status: 403}`

**Comment by mbkh68** [comment]
> all express middleware is ignored when used with WebSockets.
This not yet fixed?
