### ISSUE TITLE
Issue in loading schema with Node 14.15.0

### ISSUE THREAD

**Issue by praseetha-nair** [cube-js/cube.js#1372]
We are facing issues in loading schema files in cube server with Node version 14.15.0. The schema files and tables are not loading,  we are seeing the overlay. We are using pg version 12. Any idea what's the issue?

**Comment by priyasooraj** [comment]
Hi can we have an update on this issue please ?

**Comment by Karthika-08** [comment]
I am also facing the same issue. Is there any solution?

**Comment by ovr** [comment]
I still not able to reproduce this issue with Node.js `v14.15.1` and PostgreSQL `v12.4`.

@praseetha-nair @priyasooraj @Karthika-08 can you provide more details?

**Comment by praseetha-nair** [comment]
The issue was in our package.json file. Updated 

```
"@cubejs-backend/postgres-driver": "^0.23.11",
"@cubejs-backend/server": "^0.23.12"
```

Solved the issue.
