### ISSUE TITLE
Docker image size is increased a lot on v0.23.2

### ISSUE THREAD

**Issue by donge** [cube-js/cube.js#1391]
**Problem**

There is a huge size incremental on v0.23.2, is there a big dependency change?

![image](https://user-images.githubusercontent.com/1329129/99328640-79a64c80-28b7-11eb-861d-d9fe6454240c.png)

**Related Cube.js schema**
no

**Related Cube.js generated SQL**
no

**Comment by ovr** [comment]
Hello @donge,

We switched from Alpine to Debian as the base image.

```
docker run --rm --entrypoint=docker-entrypoint.sh -it cubejs/cube:v0.23.1 cat /etc/issue                                                                                                                                              
Welcome to Alpine Linux 3.11
Kernel \r on an \m (\l)
```

```
docker run --rm --entrypoint=docker-entrypoint.sh -it cubejs/cube:v0.23.2 cat /etc/issue                                                                                                                                                       
Debian GNU/Linux 9 \n \l
```

Could you please elaborate on your use case?

**Comment by hassankhan** [comment]
Hi @donge, you should be able to use the Alpine image available on Docker Hub. Thanks for posting the issue, marking as resolved.
