### ISSUE TITLE
Pivoting Control in Playground: Charting with more than one dimensions in Explore tab

### ISSUE THREAD

**Issue by bonchef** [cube-js/cube.js#140]
**Describe the bug**
Adding a second dimension does not render charts as a two-dimension chart (such as stacked bar chart) in some case and when it works it seems not intuitive.

**To Reproduce**

Sort of working scenario:
Go to Explore
Pick a Measure, time dimension is automatically added and with group by Day
Then pick a dimension - expect a two dimension chart at this point
But it automatically switched to table and cleared the group by Day
Forcing it back to charts would work.

Failing scenario:
Pick a measure
Remove the default time dimension
Add first dimension - chart rendered as expected
Add second dimension
Again it switches to table automatically but preserving the two dimensions in this case
Forcing it back to bar-chart and expect stacked bar chart - however, it flatten the first and second dimension in to a single concatenated string value - e.g. YearName and MonthName become "YearName, MonthName".

**Expected behavior**
Ideally should not switch to table view, and if it is a design intent, it should preserve the time and group by and render a pivot table instead of a table.

As for the failing case, expect a second dimension to be expressed as two-diemnsion bar chart.  For more than two dimensions, switching to pivot table automatically or limiting charts to max two dimensions seem reasonable.

**Screenshots**

**Version:**
0.9.32

**Additional context**

**Comment by paveltiunov** [comment]
@bonchef Thanks for posting this! There're some heuristics in place for `QueryBuilder` which works for some scenarios and doesn't for another. I think the first line solution is to add pivoting control in playground.

**Comment by paveltiunov** [comment]
Should be fixed in the latest version. Feel free to open a new issue if it still persists.
