### ISSUE TITLE
[Types] Missing types for orchestrator options

### ISSUE THREAD

**Issue by hagmic** [cube-js/cube.js#1421]
**Describe the bug**
The `orchestratorOptions` configuration field allows for configuration via a function, but the types do not reflect that.

**To Reproduce**
1. Configure the `orchestrationOptions` in a TypeScript project with a function.
2. See that there is a TypeScript error.

**Version:**
0.23.14

**Additional Context**
Functionality still works, we've just had to ignore the TypeScript error.

**Comment by ovr** [comment]
Merged, released in `v0.23.15`.

Thanks
