### ISSUE TITLE
Query Variables: perform a funnel query based on different events selected by the front end

### ISSUE THREAD

**Issue by 610278470** [cube-js/cube.js#144]
The funnel model on the back end is not fixed, so I can choose different events to filter on the front end. Now every filter query needs to write a cube (), every new funnel needs to update the server code, queries can only be based on fixed rules to query. I tried to write my own SQL statement to query, and found that funnel query SQL statement is too complex to maintain. Thank you！

**Comment by paveltiunov** [comment]
@610278470 Heya! It's a great question. So currently there's no simple way to pass steps of a funnel from frontend to backend in query. We're thinking about ability to pass arbitrary query variables and use them while SQL generation. 

The workaround is to save your funnel definition somewhere before actual visualization. Many analytics tools like Mixpanel or Amplitude go this way. It's also very handy to have this definition saved when it comes to performance optimizations.
