### ISSUE TITLE
Redis intermittent "too big inline request" during pre-aggregations routine

### ISSUE THREAD

**Issue by rawpixel-vincent** [cube-js/cube.js#1447]
**Describe the bug**
The cube.js server throw RedisClient "too big inline request" error during the pre-agregations.
I've sent the cube.js schema and full error trace to @paveltiunov on slack.
```
ReplyError: ERR Protocol error: too big inline request\n    at parseError (/var/www/service/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/var/www/service/node_modules/redis-parser/lib/parser.js:302:14)
```

**To Reproduce**
I suppose this happens with a large generated query we use rollup window, which create a sub query with each day.
Enable the refresh pre aggregation on that cube.

**Version:**
cubejs-backend/server-core 0.19.59
cubejs-backend/postgres-driver 0.19.56

**Additional context**
Using Redis 6.0.5 hosted on aws elasticache, we never encounter that error on the other applications using this server, we also use to send huge request in batch (million of keys) to that server without issues, although in our use case the key/values are quiet small.

**Comment by paveltiunov** [comment]
@rawpixel-vincent Hey Vincent! Thanks for posting this! Could you please provide your Cube.js trace logs and Redis `MONITOR` logs?

**Comment by rawpixel-vincent** [comment]
cube.js wasn't the culprit here, we simply used our server to his capacity, other of our services started to throw errors related to redis. So in our case we had to upgrade the memory of our instances.
