### ISSUE TITLE
Url mismatch in CubeJS docs

### ISSUE THREAD

**Issue by ronnjoe10** [cube-js/cube.js#1452]
Hi, 

React dashboard git repo link in Cube JS redirects to an error page. This is due to a spelling mistake in the github docs. 
Url provided in docs : https://github.com/cube-js/cube.js/tree/master/examples/react-dashboard
Actual github Url :  https://github.com/cube-js/cube.js/tree/master/examples/react-dashobard

Cheers,
Joe

**Comment by hassankhan** [comment]
Hi @ronnjoe10, thanks for bringing this to our attention 👍 The link should now be working
