### ISSUE TITLE
API for Data Loading in CubeJS Server

### ISSUE THREAD

**Issue by ajaytech** [cube-js/cube.js#1458]
How can I load data with API using CubeJS Backend?

So here we need to create the Custom Implementation or some options are present?

**Comment by ovr** [comment]
Hello @ajaytech,

> How can I load data with API using CubeJS Backend?

If you are asking about saving (inserting) data by Cube.js, it's not possible and probably will not be possible because Cube.js is an analytical API platform (something like an OLAP server).

You can do it inside your application.

Thanks

**Comment by ajaytech** [comment]
@ovr : Thanks for the reply.

For this express based API for data loading is better for some alternative approach are present which is better?

**Comment by ovr** [comment]
Historically, Cube.js has been being embedded in Express applications running on Node.js. We are moving to a microservice architecture, and we provide the official Docker image. Embedding is a deprecated way.

If we are speaking about event tracking, you can:

1. Write a microservice that provides an HTTP entry point and collects metrics inside the database.
2. Use a snowflake collector (https://web-analytics.cube.dev/data-collection-and-storage).
3. Anything else
