### ISSUE TITLE
using cube js with angular

### ISSUE THREAD

**Issue by vikas-29** [cube-js/cube.js#1472]
I am following below tutorial for using cube js with angular. I am using Angular 10
https://cube.dev/docs/@cubejs-client-ngx

I have installed @cubejs-client/core and @cubejs-client/ngx packages. When CubejsClient  is injected in the component's constructor below error is shown in browser's console tab
core.js:4197 ERROR Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:2284)
    at Module.ɵɵinject (core.js:2294)
    at Object.CubejsClient_Factory [as factory] (cubejs-client-ngx.js:94)
    at R3Injector.hydrate (core.js:11249)
    at R3Injector.get (core.js:11071)
    at NgModuleRef$1.get (core.js:24199)
    at Object.get (core.js:22102)
    at getOrCreateInjectable (core.js:3921)
    at Module.ɵɵdirectiveInject (core.js:13753)
    at NodeInjectorFactory.StockChartComponent_Factory [as factory] (stock-chart.component.ts:11)

any help will be appreciated 
thanks

**Comment by vasilev-alex** [comment]
Hi @vikas-29! Unfortunately, I wasn't able to reproduce the error. However, I found this thread where people have a similar problem https://github.com/angular/angular/issues/25813. Could you please check it out and see if that helps?

Also, could you please post your `tsconfig.json` file?

**Comment by vikas-29** [comment]
> Hi @vikas-29! Unfortunately, I wasn't able to reproduce the error. However, I found this thread where people have a similar problem [angular/angular#25813](https://github.com/angular/angular/issues/25813). Could you please check it out and see if that helps?
> 
> Also, could you please post your `tsconfig.json` file?

Hi @vasilev-alex thanks for your reply below is my tsconfig.json file
[tsconfig.txt](https://github.com/cube-js/cube.js/files/5615054/tsconfig.txt)

**Comment by vikas-29** [comment]
> Hi @vikas-29! Unfortunately, I wasn't able to reproduce the error. However, I found this thread where people have a similar problem [angular/angular#25813](https://github.com/angular/angular/issues/25813). Could you please check it out and see if that helps?
> 
> Also, could you please post your `tsconfig.json` file?

Hi @vasilev-alex I have followed the link you have provide and have found below line of code useful to resolve my issue

I put this path in the compilerOptions section of tsconfig.app.json of the angular application:
"paths": { "@angular/*": [ "../node_modules/@angular/*" ] }

thanks
