### ISSUE TITLE
Filter by empty / non-empty string

### ISSUE THREAD

**Issue by agavish** [cube-js/cube.js#1480]
**Is your feature request related to a problem? Please describe.**
I'm unable to filter dimensions by empty or non-empty strings - a very common scenario when handling massive data sets with sometimes empty strings.

**Describe the solution you'd like**
Add an "is Empty" and "is not Empty" operators to the list:
![Screen Shot 2020-11-30 at 3 42 19 PM](https://user-images.githubusercontent.com/3663224/100662303-b4ca6600-3322-11eb-8361-e0b580b3e199.png)

**Describe alternatives you've considered**
Tried using all of the following:

- equals ""
- equals " "
- is Set

**Comment by paveltiunov** [comment]
@agavish Hey Adam! Thanks for posting this one! It should work in API. Is this issue relates only to the playground filtering options?

**Comment by agavish** [comment]
Yes this is via Playground and local Cube.js deployment
