### ISSUE TITLE
Support multiple schemas for the same database.

### ISSUE THREAD

**Issue by MattGson** [cube-js/cube.js#1483]
**Is your feature request related to a problem? Please describe.**

We have fairly complicated authorisation rules and many different (customisable) ways of analysing the same data.
Because of this, we require many different cubes for the same database based on different users and use-cases (particularly join ordering). 
It becomes very hard to give appropriate names to the cubes and makes it difficult to understand the intent from the clients perspective.

**Describe the solution you'd like**
A possible solution would be to have cube namespaces/modules that allow cubes to arbitrarily divided based on use-cases/permissions etc. Cubes in each namespace would have unique names but cubes in separate namespaces could have the same name. 

Cubes need not be shared or joined across namespaces. Instead, the cube-server, would provide a parameter on each endpoint to specify which namespace to use.

i.e. 
- System admin namespace has a cube user which represents any user on the platform
- Usage analytics namespace has a cube user which represents users with particular properties and in a particular group which the client is authorised to view.

The two namespaces also define the joins differently based on how they want to query the data.

Example api:
```
/cubejs-api/v1/meta?namespace=usage_analytics
```

**Describe alternatives you've considered**
Prefixing each cube with a namespace name or trying to come up with descriptive names that incorporate the purpose of the cube.

**Comment by igorlukanin** [comment]
@MattGson Thanks for such a detailed explanation of your issue and a possible solution!

Did you have a chance to check if these existing features of Cube.js might apply to the issue: [Multitenancy](https://cube.dev/docs/multitenancy-setup) (i.e., `repositoryFactory` option), [Execution Environment](https://cube.dev/docs/schema-execution-environment), and maybe [Contexts](https://cube.dev/docs/context)?

Cc @hassankhan

**Comment by MattGson** [comment]
@igorlukanin I have gone through the docs on all of these. 

- Multi-tenancy does not apply as these namespaces exist within the same tenant (for every tenant). 
- Execution Environment may be useful for some deep customisation but doesn't make sense for the use case as far as I can tell
- Contexts looks like it might be heading in the right direction but right now the documentation is pretty much non-existent and it does not appear to solve the duplication/naming problem. In fact, it doesn't look like contexts do anything at all right now?

**Comment by igorlukanin** [comment]
@MattGson Sounds reasonable! What do you think of using `repositoryFactory` to dynamically switch between schemas based on `authInfo`? Hope you find [this example](https://cube.dev/docs/multitenancy-setup#multiple-schema-and-drivers) useful.

**Comment by MattGson** [comment]
@igorlukanin Thanks for the suggestion. I have set something up using `repositoryFactory` and a custom header to specify the schema (I would have used a query param but not sure how to make it work with the cube client). 

This is a reasonable solution as it allows multiple isolated schemas that the client can choose from. The only small limitation is that there is no easy way to find out what schemas are available.

**Comment by igorlukanin** [comment]
> The only small limitation is that there is no easy way to find out what schemas are available.

I would suggest that available schemas should be provided to the client app from a common configuration source.

However, If you want to get this information from Cube.js, I can suggest a **really dirty** hack. You can have a special "service schema", available when a special value is set in your auth header, and in that "service schema" you can have a cube which provides the list of other schemas, possibly with some meta information to filter upon. It's far from a perfect setup but it may allow to have a single point of configuration that exposes your other schemas to the client. The cube might look like this:

```js
cube('Schemas', {
  sql: `SELECT * FROM ('schema1', 'schema2', 'schema3') AS schemas (name)`,
  // ...
})
```

**Comment by MattGson** [comment]
@igorlukanin Thanks for the idea. I'm just going for the configuration option for now but I'll keep this in mind.

**Comment by paveltiunov** [comment]
This is something that should be solved by contexts. Let's put this conversation in this issue: #2145 .
