### ISSUE TITLE
Playground UI for schema generation

### ISSUE THREAD

**Issue by PVinay737** [cube-js/cube.js#150]
**Describe the bug**
In #149 the measure and dimension attributes are defined(count and id) . Is it feasible to generate a schema at will if a user wants to 

- choose from a set of measures,dimensions,formats..etc

**Comment by paveltiunov** [comment]
@PVinay737 I believe you refer to Playground UI here which can be used to select what exactly is generated based on tables schema.

**Comment by PVinay737** [comment]
Yeah

**Comment by hassankhan** [comment]
Closing as this feature landed some time ago 😅
