### ISSUE TITLE
Time series data not based on date/time

### ISSUE THREAD

**Issue by zacheg** [cube-js/cube.js#1503]
**Problem**

How can i handle time series data that does not have a date time field but instead has a field that starts at 0 and ticks up for each `group` in the data. Is this possible in Cube.JS? Ideally it would have very similar functionality to the existing time features. 

For example a group in the data set has 50K points. I would like to query the data to generate a plot of one of the variables. If my main integer field were of the date/time type I could simply use the granularity field in the query, but with this non-time time series data i do not see an obvious way to do this.

**Comment by paveltiunov** [comment]
Hey @zacheg! So do you store actual time intervals or something like a counter?

**Comment by zacheg** [comment]
Hi @paveltiunov! We store a counter that is milliseconds since the beginning of the recording with the table having multiple recordings in it with roughly one row each second.

**Comment by paveltiunov** [comment]
@zacheg You believe you can extrapolate time from your column in SQL. Which database do you use?
