### ISSUE TITLE
Runtime for Querying

### ISSUE THREAD

**Issue by PVinay737** [cube-js/cube.js#151]
What's the usual time complexity for querying given that the dimensions are too many (with/without pre-aggregations )  ?

**Comment by paveltiunov** [comment]
@PVinay737 Hey Vinay! It's really great question. Actually it depends a lot of on amount of data, dimension cardinalities, database engine, etc. Could you please provide some more information on that?

**Comment by PVinay737** [comment]
Just wanted to know how well cube.js workflow happens in different scenarios and maybe optimize it accordingly

**Comment by paveltiunov** [comment]
@PVinay737 I see. So as the rule of thumb no specific optimization is required until 10-100M of data points depending on time to insight requirements. From that point there're different scale strategies for cube.js which include caching configuration https://cube.dev/docs/caching, and pre-aggregations https://cube.dev/docs/pre-aggregations. In production cube.js is heavily battle tested on trillions data points sets and can provide subsecond response times in such setups with proper configuration.
