### ISSUE TITLE
Better UI instead of dropdown to display members in Playground

### ISSUE THREAD

**Issue by PVinay737** [cube-js/cube.js#152]
Something like auto complete looks good when there are large number of dimensions

![dropdown](https://user-images.githubusercontent.com/44138475/60586140-0c237a00-9daf-11e9-8d92-f1a4be3da897.png)

**Comment by paveltiunov** [comment]
@PVinay737 Yeah. Agree. Current dropdown is a little bit awkward if there're too many entries.

**Comment by hassankhan** [comment]
@paveltiunov Could use something like [this](https://codesandbox.io/s/o78u1) (found from [here](https://ant.design/components/select/))
