### ISSUE TITLE
Prevent React state updates on unmounted components

### ISSUE THREAD

**Issue by sfletche** [cube-js/cube.js#1522]
**Describe the bug**
useCubeQuery currently updates state after an async / await.
https://github.com/cube-js/cube.js/blob/4485fc8b577e5830adfd23aff397140c981d34f7/packages/cubejs-client-react/src/useCubeQuery.js#L66-L70
However, it's possible the component is no longer mounted when that async request completes.
This results in the following console warning
![image](https://user-images.githubusercontent.com/1268443/101223548-1cddbc80-3641-11eb-92d6-116e90fdb5f1.png)
about updating state on an unmounted component.

One solution to this would be to leverage the useIsMounted hook to block the setting of state when the component is no longer mounted.

**To Reproduce**
With the dev tools open to view console warnings
Navigate to a view containing a component that uses useCubeQuery 
Immediately navigate away from this ^ view (before the query has time to complete)
See Warning in console 

**Expected behavior**
No Warning in console (and no updating of state on unmounted components)

**Screenshots**

**Version:**
@cubejs-client/react v0.23.6

**Additional context**
Using a hook like
```
const useIsMounted = () => {
  const isMounted = useRef(false);

  useEffect(() => {
    isMounted.current = true;
    return () => { isMounted.current = false; };
  }, []);

  return isMounted.current;
};
```
We could get the lion's share of issues handled by changing the code here
https://github.com/cube-js/cube.js/blob/4485fc8b577e5830adfd23aff397140c981d34f7/packages/cubejs-client-react/src/useCubeQuery.js#L66-L72
to something like
```
const loadedResultSet = await cubejsApi.load(query, {
  mutexObj: mutexRef.current,
  mutexKey: 'query',
  progressCallback
});
if (isMounted) {
  setResultSet(loadedResultSet);
  setLoading(false);
  setProgress(null);
}
```

**Comment by hassankhan** [comment]
Hi @sfletche, thanks for posting this issue 👍 

The `isMounted()` hook looks good, we could probably use something like [`use-is-mounted-ref`](https://github.com/helderburato/use-is-mounted-ref) to cover the lion's share of issues as you mentioned. A more complete solution would also use cancellable promises, cancelling them on component unmount.
