### ISSUE TITLE
Empty results for BigQuery in Google Cloud serverless mode

### ISSUE THREAD

**Issue by landyrev** [cube-js/cube.js#153]
**Describe the bug**
BigQuery cubes return empty datasets while running in Google Cloud serverless mode

**To Reproduce**
1. Setup CobeJs in serverless mode ([for example](https://github.com/landyrev/test-cube))
2. Deploy it to Google Cloud
3. Try to query any BigQuery cube (for example `{"measures":["Orders.count"]}`)
4. Get empty result, without any errors

**Expected behavior**
Query result is not empty (as if you run it locally)

**Version:**
@cubejs-backend/bigquery-driver 0.10.11
@cubejs-backend/serverless 0.10.11
@cubejs-backend/serverless-google 0.10.11
@google-cloud/bigquery 2.1

**Comment by landyrev** [comment]
Thanks to [this thread](https://stackoverflow.com/questions/56334274/google-cloud-bigquery-query-api-returning-empty-promise-when-used-in-cloud-func) I found workaround: downgrading `@google-cloud/bigquery` to `1.3.x` and forking `@cubejs-backend/bigquery-driver` (because it’s in incompatible with older version) helped me to get results from bigquery cubes

**Comment by landyrev** [comment]
Updating `@google-cloud/bigquery` to `4.1.4` version (latest for now) solves problem too.

Maybe it's good idea to update bigquery client version in bigquery-driver package.json?

**Comment by paveltiunov** [comment]
@landyrev That's a great catch! Yeah. Definitely makes sense to upgrade version in driver. Would love if you provide PR for that.

**Comment by landyrev** [comment]
And here is related `@google-cloud/bigquery` issue: https://github.com/googleapis/nodejs-bigquery/issues/463
