### ISSUE TITLE
SQL Columns Names in Upper Case for Schema

### ISSUE THREAD

**Issue by ajaytech** [cube-js/cube.js#1541]
Hey all, Is it mandatory to have the Column name in the upper case if we want to use CubeJS?

When  Database Fields(Column names) is Upper Case CubeJS gives an error.

Specifically when queries that are generated containing a `count(distinct "NAME")` gets executed in DB.

For now, with double quotes in the schema for the upper case Column name, it works for basic queries.
like: 

  ```
  userId: {
      sql: `"NAME"`,
      type: `string`,
      shown: false,
    },
```

**Comment by hassankhan** [comment]
@ajaytech Thanks for creating the issue 😄 

This seems to be an issue with the Node Postgres driver: https://github.com/brianc/node-postgres/issues/195. Their recommended workaround is exactly as you mentioned, wrapping in double-quotes.
