### ISSUE TITLE
Support for other dimension types ?

### ISSUE THREAD

**Issue by PVinay737** [cube-js/cube.js#157]
Is it possible to use cube.js for querying other dimension types other than time, string,number, and geo or is it a `nested variation` of the above?

Examples 

```{ "_id" : { "$sid" : "x"},  id :10,"type":"tv","nat" : [ "P", "Q", "R" ] } , "X" : [ { "A" : "B" } ] }```

**Comment by paveltiunov** [comment]
Hey @PVinay737 ! Yep. Sure! Please refer to `dimensions` property of query https://cube.dev/docs/query-format#query-properties and schema https://cube.dev/docs/dimensions#top.
