### ISSUE TITLE
chartPivot() fails when data blending on the same measure 

### ISSUE THREAD

**Issue by MattGson** [cube-js/cube.js#1573]
**Describe the bug**

When doing cohort analysis, often we want to compare the same measure for multiple different groups.
The definitions of these groups can be complex (think audiences)

i.e. Compare:
-         average purchase price for users in group A who have made less than 10 purchases
-         average purchase price for users in group B who have made at least 10 purchases

As far as I can see, doing this with one query is difficult due to the way dimensions group the data. The resulting groups will be wrong because it will group by the actual value of Users.purchase_count, not the binary filters <10 or >=10. There is also no way to tell cube to combine the groupings correctly as far as I can tell?

A easy and obvious solution is to create one query for each cohort. This works well and is easy to construct (and probably more efficient to execute for a small number of cohorts).

The problem is that using `chartPivot()` on the client fails. Only one of the queries results end up in the data set. This is likely because `chartPivot()` just sets the key in the object based on the measure name (which is the same for both series) and ends up overwriting each query with the previous next one.

**Describe the solution you'd like**
A potential solution would be to give every query a name/title. This would be used to prefix the measures for the resulting series. 
i.e.
Query:
```
 { 
     name: `Group A < 10`
     measures: [...],
    ....
 }
```

ChartPivot
```
{ x: '2020-10-15T00:00:00', 'GroupA<10.Users.AveragePurchase': 6, ... }
```

**Describe alternatives you've considered**
Bypassing or extending the chartPivot functionality manually.

**Comment by vasilev-alex** [comment]
Hey @MattGson! Thanks for the detailed description. Yes, we need to fix it.
