### ISSUE TITLE
Error with Cube.js pre-aggregations in BigQuery

### ISSUE THREAD

**Issue by AdamWidi-BF** [cube-js/cube.js#158]
**Describe the bug**
Attempted to set up a pre-aggregation in a cube against BigQuery and received the following error: "Error: Error: this.bigquery.startQuery is not a function"

**To Reproduce**
1. Created a dataset in BigQuery named 'stb_pre_aggregations'
2. Granted the service account used for Cube-JS as BigQuery Admin
3.  Added the following pre aggregation in the cube definition. 
preAggregations: {
    main: {
      type: `originalSql`
    }
4. Ran "npm run dev" to launch CubeJS environment.
5. Opened Cube.js Playground
6. Added dimension to playground from cube with aggregations defined.
7. Saw "Error: Error: this.bigquery.startQuery is not a function"

**Expected behavior**
Expected to see new table created in stb_pre_aggregations dataset in BigQuery.

**Screenshots**
![image](https://user-images.githubusercontent.com/52676585/60837131-0fdb4600-a18d-11e9-8c13-08d08226f621.png)

**Version:**
  "dependencies": {
    "@cubejs-backend/bigquery-driver": "^0.10.0",
    "@cubejs-backend/server": "^0.10.6"
  }

**Additional context**

**Comment by paveltiunov** [comment]
@AdamWidi-BF Hey Adam! Thanks for posting this! Just fixed it. Could you please `npm update @cubejs-backend/bigquery-driver` and check?
