### ISSUE TITLE
Improve response from `/run-scheduled-refresh` REST API endpoint

### ISSUE THREAD

**Issue by magno32** [cube-js/cube.js#1585]
**Is your feature request related to a problem? Please describe.**
Not a problem... Its a feature.  Per my discussion with @hassankhan and in addition to #1584 

**Describe the solution you'd like**
When calling `run-scheduled-refresh` , the response should be more meaningful than `{"error", "Continue wait"}`  For a serverless deployment, it makes sense (to me) to at least report some info about the refresh queue so the caller will know when to stop calling it.

**Comment by magno32** [comment]
I just realized I had already opened #765,  but I still think the response could be improved.

**Comment by hassankhan** [comment]
Closing as answered by @paveltiunov [here](https://github.com/cube-js/cube.js/issues/765#issuecomment-652609609).
