### ISSUE TITLE
RefreshScheduler needlessly checks connection(?) to athena using SELECT 1 every 5 seconds

### ISSUE THREAD

**Issue by benswinburne** [cube-js/cube.js#1592]
**Describe the bug**
Every 5 seconds Cube.js runs `select 1` against Athena (presumably to check the connection?)

This doesn't cost anything as no data is scanned, but it uses up one of available concurrent queries on the account whilst making the query log completely unreadable because of pages and pages of `select 1`.

The RefreshScheduler has this code

```
      await orchestratorApi.executeQuery({
        ...sqlQuery,
        preAggregations: [],
        query: 'SELECT 1', // TODO get rid off it
        continueWait: true,
        renewQuery: true,
        requestId: context.requestId
      });
```

What would removing it entail exactly?

**To Reproduce**
```
cube(`Events`, {
  sql: `SELECT * FROM events.events`,

  refreshKey: {
    every: `1 hour`,
  },

  ...
}
```

**Expected behavior**
Not send `select 1` every 5 seconds for whataver

**Screenshots**
![image](https://user-images.githubusercontent.com/1208977/102025510-5aa0ba80-3d90-11eb-9a3b-f817f543ca46.png)

**Version:**
```
  "devDependencies": {
    "@cubejs-backend/athena-driver": "^0.24.5",
    "@cubejs-backend/postgres-driver": "^0.24.4",
    "@cubejs-backend/server": "^0.24.4"
  }
```

**Comment by hassankhan** [comment]
Hi @benswinburne :wave: this behaviour was changed in f69324c60ee4adfdfded67dddedab113fb5fdb95 and should be available in the next minor release.

**Comment by benswinburne** [comment]
Ah fantastic, thanks. 

Just noticed that I can set it to a number rather than true which allows me to configure the number of seconds.

What would be the downside of setting this to a much longer interval in my usecase? I.e. is it only checking connectivity? could i set it to say 24 hours and it not break anything or is it important that it is regularly doing it even in the case of say athena where it doesn't necessarily loose the connection so to speak?

**Comment by benswinburne** [comment]
@hassankhan I just had a play around with this.

Changing the value to a much higher number actually stops the scheduledRefresh happening (obviously now that i think about it).

That said the fix in https://github.com/cube-js/cube.js/commit/f69324c60ee4adfdfded67dddedab113fb5fdb95 simply changes the default from 5 seconds to 30. It doesn't address the fact that it is unnecessary to run a select 1 against the database.

Presumably this is only actually a requirement for databases which connect using a socket/hold a persistent connection or pool of connections and isn't necessary for Athena/bigquery/Aurora (if using http?)
