### ISSUE TITLE
`compareDateRange` needs to be added to the type definitions for 

### ISSUE THREAD

**Issue by cbroome** [cube-js/cube.js#1621]
**Describe the bug**

The article on https://cube.dev/blog/comparing-data-over-different-time-periods/ describes a new `compareDateRange` property available on TimeDimensions. Based on what I could see this is available in the repository however it doesn't look like the type definitions were added so it is unavailable for Typescript projects. 

**To Reproduce**
1. npm install the latest cubejs-core (0.24.8 as of this writing)
2. Include cubejs-core
3. Try to instantiate a query with a compareDateRange property in a Typescript file.

**Expected behavior**
Typescript projects can use the `compareDateRange` property

**Version:**
 * `@cubejs-client/core": "^0.24.8"`
 * ` @cubejs-client/react": "^0.24.8"`

**Comment by SoozaV** [comment]
This is not completed yet:

![image](https://github.com/cube-js/cube/assets/23610892/49eec11c-fe12-4a22-a3c3-42369b1217b4)

version 0.33.12
