### ISSUE TITLE
Support local function calls rather than sql queries for pre-aggregation checks

### ISSUE THREAD

**Issue by benswinburne** [cube-js/cube.js#1624]
**Is your feature request related to a problem? Please describe.**
I don't use any `min`/`max` queries with my refreshKeys because with athena it's slow and costly to do that so everything is done using dates and times but not against the data itself.

What ends up happening is for every pre aggregated table I get queries like

    SELECT CASE WHEN NOW() < from_iso8601_timestamp('2020-12-13T23:59:59Z') + interval '7' day THEN FLOOR((0 + 6300 + to_unixtime(NOW())) / 86400) END

Which just returns values such as the following

![image](https://user-images.githubusercontent.com/1208977/102413824-70f78200-3fed-11eb-9064-827d1e27e0e4.png)

What this means is i get endless pages upon pages of these queries in my athena query history and it makes it completely impossible to find any information of any real value (especially in the console where the paging is not controllable by the user and you can't skip to page 50 or whatever)

![image](https://user-images.githubusercontent.com/1208977/102346550-ef750500-3f96-11eb-8b30-495a319c5a6a.png)

**Describe the solution you'd like**

I assume that the `updateWindow` property of the refresh key is what determines the query which is generated. Without knowing how/why it's implemented by querying the database it's hard to suggest what might be a good option, but some sort of `useSqlToDetermineUpdateWindow: false` option or something might work?

**Comment by paveltiunov** [comment]
@benswinburne Hey Ben! Thanks for posting this one! This is indeed something we're considering however the reason it works this way is database is the only reliable source of time synchronization as of now. The moment we introduce separate clocks we'd need to figure out what will be the single source of truth for these clocks. Is it Cube.js instances, Redis?

I'll leave it open for discussion and to share use cases. It'll be pretty tricky to implement so it'd be great to collect some more info here.

**Comment by paveltiunov** [comment]
`refreshKey` `every` checks were moved to Cube Store for evaluation.
