### ISSUE TITLE
Get SQL Query with AWS API Gateway

### ISSUE THREAD

**Issue by joeyhub** [cube-js/cube.js#164]
![image](https://user-images.githubusercontent.com/1512978/61721323-3342eb00-ad60-11e9-9ed8-724b7b45a18f.png)

I'm immediately seeing things like this. To be just sending SQL over HTTP is a warning sign though haven't checked out what it's doing, I guess it's actually the JSON syntax rather than actual SQL which is a safe restricted subset that SQL is built from (I guess it returns that or something).

Instead have `request(path, params)` such as `request('/sql', {query: JSON.stringify(query)})`.

Then DRY and there are probably good libraries out there to convert an object to a query string with the right URL encoding on keys and values rather than DIY.

Even if this is a false positive, it's hard to establish quick if that's the case with the code written in the way it currently is.

**Comment by paveltiunov** [comment]
@joeyhub Hey Joey! Thanks for bringing this issue! Yeah. Actually this code should be reused. There's no SQL transferred as part of GET request though. It's JSON query https://cube.dev/docs/query-format#top. `encodeURIComponent` there to fix AWS API gateway compatibility as I remember. Need to fix this one.

**Comment by joeyhub** [comment]
I think actually encodeURIComponent needs to be there in all cases, just for the HTTP query string spec (probably URI/URL spec actually), which gets a bit repetitive hence just using a generic object to query string lib which would always encodeURIComponent. It's technically possible to have {"&otherparm=something":"&=??&+#mor strange things"} which will parse as multiple arguments.

If just instead passing the object, which only at the very moment it needs to be URLfied makes the code much more flexible and means generally you don't have to worry about the URL encoding, would just always get done at the last minute (point of exit / conversion to URL for HTTP lib) allowing objects to be passed around in the JS to build up a query object without getting stuck into transport concerns prematurely. Would make it a lot easier to replace with some other forms of transport.

**Comment by paveltiunov** [comment]
@joeyhub Yep. Agree. Would love to see such contribution!

**Comment by paveltiunov** [comment]
Fixed in v0.11.0.
