### ISSUE TITLE
Add queryType in API reference docs

### ISSUE THREAD

**Issue by pierre-b** [cube-js/cube.js#1648]
The new feature `compareDateRange` doesn't specify in the docs that a new parameter `queryType=multi` should be added to the query.

An update of the documentation would be great: https://cube.dev/docs/rest-api#api-reference-v-1-load

Thanks!

**Comment by hassankhan** [comment]
Thanks for reporting this, @pierre-b!

**Comment by pierre-b** [comment]
Thanks @hassankhan for taking care of the ticket. keep going :)
