### ISSUE TITLE
Google BigTable

### ISSUE THREAD

**Issue by gregorskii** [cube-js/cube.js#165]
Hello,

I am checking this out for a future project and was curious how adaptable this library is to no-sql databases like HBase / Google Big Table / Time series etc that don't conform to SQL queries.

How attached is the plugin system to sending SQL like queries as apposed to no-sql types?

Thinking about creating a plugin for my use case but I didn't want to spin my wheels if it was out of the realm of possibility.

Thanks

**Comment by paveltiunov** [comment]
@gregorskii Hey Gregory! It's a great question! So the SQL interface is requirement for Cube.js and everything under hood is built around SQL. In fact we do support Hive and Google BigQuery drivers which are complementary SQL solutions to HBase and Google Big Table. If you can share your use case we can guide you in the right direction on how to implement it using Cube.js. I mean what type of data you have, where is it stored and what type of analytics do you plan to build?

**Comment by gregorskii** [comment]
Hi @paveltiunov,

Thank you for the response. We are intending to use BigTable (sub 5 sec averages) for fast queries for a dashboard, and BigQuery for longer ETLs. Looking over this library it felt very inspired by GraphQL so my main question was whether the library had a resolver like methodology for pulling data.

Thanks!

**Comment by paveltiunov** [comment]
@gregorskii While it seems very similar to GraphQL at first sight underlying transport and how results are resolved very different. Actually Cube.js query doesn't resolve specific fields - it's an OLAP query which resolves to a result set. So there's no such resolvers concept in place.

**Comment by gregorskii** [comment]
@paveltiunov,

Thank you for clarifying that. This project looks great and I will keep an eye on it, it may not fit this particular use case but I may find one in the future.

Have a good one.
