### ISSUE TITLE
I am using cubejs backend for my project and i am trying to get the relation between tables in the front and i did not find away to get them

### ISSUE THREAD

**Issue by MahmoudTohamy** [cube-js/cube.js#1657]
**Problem**

A clear and concise description of what the problem is. Ex. How can I do X with Cube.js? [...]

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `` //, ...
})
```

**Related Cube.js generated SQL**

```sql
SELECT * FROM ...
```

**Comment by vasilev-alex** [comment]
Hi! Did you check out this page https://cube.dev/docs/joins?

**Comment by MahmoudTohamy** [comment]
yes i did but i did not find any clue about how to get the relation between tables (from the front end)

**Comment by vasilev-alex** [comment]
You have to specify relations manually in your schema files. There's no way to do it in the Playground as of now.

**Comment by MahmoudTohamy** [comment]
I have specified it but when i use the meta api it only get the tables and i can not indicate the relation between the tables
