### ISSUE TITLE
Website: black text on dark blue background 

### ISSUE THREAD

**Issue by crimson-med** [cube-js/cube.js#167]
**Describe the bug**

When viewing the website in firefox the code text example is unreadable

**To Reproduce**
1. Go on Firefox
2. Go on https://cube.dev/
3. Scroll down to `Built for developers`
4. See black text on dark blue blackground

**Expected behavior**

A readable white text as on Chrome

**Screenshots**

![dark text on dark background](https://image.noelshack.com/fichiers/2019/30/3/1563942208-screenshot-2019-07-24-at-12-18-29-pm.png)

**Comment by Priyanshu-Kapadia** [comment]
Update your Firefox to latest version

**Comment by crimson-med** [comment]
I am currently on firefox `68.0.1` which I believe is already the latest version

**Comment by paveltiunov** [comment]
Hey @Priyanshu-Kapadia ! Thanks for posting this one. I can confirm its reproduced in Mac Firefox for me.

**Comment by paveltiunov** [comment]
cc @keydunov

**Comment by Priyanshu-Kapadia** [comment]
Try chrome browser

**Comment by crimson-med** [comment]
@Priyanshu-Kapadia I have mentioned that Chrome works. The issue is simply cross-platform compatibility. I noticed this issue on firefox. And when I arrive it didn't make me want to read the code. It's not as compelling as white text that stands out. 

A website is the first impression people get of a product therefor it should be compatible to all browser not just work on one specific browser. I know how to solve this issue but I made the issue so you guys could improve the portability of your website.

**Comment by keydunov** [comment]
@crimson-med Thanks for bringing this up 👍  We definitely need to fix that.

**Comment by yakuzaaaa** [comment]
https://github.com/csstools/postcss-preset-env-www/issues/14

**Comment by im-Amitto** [comment]
@crimson-med can you please specify your firefox version as I am not able to reproduce it with mine

**Comment by crimson-med** [comment]
@im-Amitto `68.0.1`

**Comment by im-Amitto** [comment]
@crimson-med 
Sorry, but I am still not able to reproduce the bug.

**Screenshot**
![Screenshot from 2019-07-26 14-56-20](https://user-images.githubusercontent.com/29653282/61941724-abeeb500-afb5-11e9-9e40-60248450947b.png)

**Comment by geoffp** [comment]
@im-Amitto disbling the CSS that sets `Source Code Pro` gets us the right colors:
**Before**
<img width="608" alt="image" src="https://user-images.githubusercontent.com/76232/61997490-c8e3c080-b067-11e9-9574-4f0e9b077c5c.png">
**After**
<img width="631" alt="image" src="https://user-images.githubusercontent.com/76232/61997494-d8630980-b067-11e9-9fe3-b0adec37c3f6.png">

I wonder if it's a platform-specific font issue. It's possible that it renders fine in Ubuntu but not Mac OS. I see also that it's loading an `.otf` version of the `Source Code Pro` font. Is there a `.woff` version we could try to see if that helps?

**Comment by im-Amitto** [comment]
@geoffp well, give it a shot.
you can find source code pro @https://github.com/adobe-fonts/source-code-pro

**Comment by tenphi** [comment]
Thanks, everyone! We replaced the "Source Code Pro" font with "Jet Brains Mono" and it helped. The issue will be closed soon.
