### ISSUE TITLE
Can I connect to 2 databases at the same time and work with both of them at the same time 

### ISSUE THREAD

**Issue by MahmoudTohamy** [cube-js/cube.js#1673]
**Problem**

A clear and concise description of what the problem is. Ex. How can I do X with Cube.js? [...]

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `` //, ...
})
```

**Related Cube.js generated SQL**

```sql
SELECT * FROM ...
```

**Comment by vasilev-alex** [comment]
Hi! Yes, you can find more info here https://cube.dev/docs/multitenancy-setup

**Comment by MahmoudTohamy** [comment]
what i had understood from it that i can connect to more than onde database but it will only read from one database 
but what i need is to read from more than one database at the same time 
getting all tables and dimension from both databases and use them

**Comment by vasilev-alex** [comment]
It is possible using rollup joins and the Cube Store. More documentation on that is coming soon.
