### ISSUE TITLE
need Language support 

### ISSUE THREAD

**Issue by ChanJeff123** [cube-js/cube.js#1674]
when I change schema file  ,
I get a error 
Error: Error: Compile errors: 游戏 cube: child "name" fails because ["name" with value "游戏" fails to match the identifier pattern]

help someone can fix that,or i can join to help

**Comment by ovr** [comment]
Hello @ChanJeff123 ,

You can use `title` to set display name for cubes.

https://cube.dev/docs/cube#parameters-title

Thanks

**Comment by paveltiunov** [comment]
This is a duplicate of #1360
