### ISSUE TITLE
Question about your image on README.md

### ISSUE THREAD

**Issue by LoicPoullain** [cube-js/cube.js#168]
Hi cube.js,

I love your [graphic](https://camo.githubusercontent.com/5668adf597a95a4a63a4074ebd096c7daa8734b7/68747470733a2f2f692e696d6775722e636f6d2f466c754746716f2e706e67) on your README.md. Did you use a particular software to draw it?

Thanks!

**Comment by paveltiunov** [comment]
@LoicPoullain Hey Loïc! Great question! I believe it's Figma. cc @keydunov

**Comment by LoicPoullain** [comment]
Thank you!
