### ISSUE TITLE
can i specify the folder to generate the schema in it? 

### ISSUE THREAD

**Issue by MahmoudTohamy** [cube-js/cube.js#1686]
**Problem**

A clear and concise description of what the problem is. Ex. How can I do X with Cube.js? [...]

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `` //, ...
})
```

**Related Cube.js generated SQL**

```sql
SELECT * FROM ...
```

**Comment by vasilev-alex** [comment]
Hey @MahmoudTohamy! No, there's no such option at the moment.

**Comment by vasilev-alex** [comment]
@MahmoudTohamy, actually I was wrong. Here's what you're looking for https://cube.dev/docs/config#options-reference-schema-path

**Comment by MahmoudTohamy** [comment]
yes I have read it but this specifies the folder to read files from 
but what I need to specifies where the files generated for the first time I create a schema
