### ISSUE TITLE
queueOptions not applied with CubejsServerCore.create

### ISSUE THREAD

**Issue by dktjsp** [cube-js/cube.js#1688]
**Describe the bug**

Hello,

i'm facing an issue with CubejsServerCore.create() , I pass the following options for the cache & pre aggregations 

``` 
            orchestratorOptions: {
                queryCacheOptions: {
                    backgroundRenew: false,
                    queueOptions
                },
                preAggregationsOptions: {queueOptions}
            },
```

with queueOptions 

```
const queueOptions = {
    concurrency: 8,
    continueWaitTimeout: 5,
    executionTimeout: 1800,
    heartBeatInterval: 600,
    orphanedTimeout: 220
};
```

But it seems that my pre-aggregations queries are canceled if they are taking more than 10 minutes (600 seconds : the default value)

So I believe that the option is not applied because it does not come from my dbs (I've checked the timeouts, etc)

**To Reproduce**
1. Use server core with an existing express app
2. Apply my options
3. Check your pre aggregations queries timeout (with huge queries that takes more than 10 minutes)
4. The query gets canceled at 10 minutes

**Expected behavior**

It should respect my timeout

**Screenshots**

No screenshots

**Version:**

```
    "@cubejs-backend/postgres-driver": "^0.25.2",
    "@cubejs-backend/server": "^0.25.3",
    "@cubejs-backend/server-core": "^0.25.3",
    "@cubejs-client/core": "^0.25.0"
```

**Additional context**

No additional context

**Comment by dktjsp** [comment]
Hello, any updates on this ? :/ 

Thanks

**Comment by paveltiunov** [comment]
@dktjsp Hey Jules! Which DB do you use? Some of the databases have driver level timeout as well.

**Comment by dktjsp** [comment]
@paveltiunov I use postgres

**Comment by dktjsp** [comment]
Still not fixed :/

**Comment by paveltiunov** [comment]
@dktjsp Postgres driver has an `executionTimeout` option which is 10 minutes by default. It's database level and works through `set statement_timeout to`.

**Comment by dktjsp** [comment]
Alright thanks :)

**Comment by dktjsp** [comment]
Hello @paveltiunov , sorry to bother you again but I've set the statement_timeout  to 30 minutes (1 800 000) and still not working :/
