### ISSUE TITLE
"The Cube.js Way" Diagram in the README misspelled "Caching"

### ISSUE THREAD

**Issue by WesPainter** [cube-js/cube.js#170]
Right hand diagram misspelled caching as cashing.  Not trying to be pedantic, just thought I'd point it out!

https://raw.githubusercontent.com/statsbotco/cube.js/master/docs/old-was-vs-cubejs-way.png

**Comment by paveltiunov** [comment]
Hey @WesPainter ! Thanks for posting this! Yeah. We just spotted it yesterday.

**Comment by samtsai** [comment]
Nice, was just gonna post this.

**Comment by keydunov** [comment]
Thanks! Fixed.
