### ISSUE TITLE
Cube.js API client is not provided

### ISSUE THREAD

**Issue by MahmoudTohamy** [cube-js/cube.js#1716]
I am trying to use drill members in a graph and I am using
const Query = {
    measures: ["Addresses.count"],
    dimensions: ["Addresses.country"],
  };
  let { resultset } = useCubeQuery(Query);
and in the schema drillMembers: [id, country, city, companyid, createdat, updatedat]
and the resultset is null  and the error msg is Cube.js API client is not provided

**Comment by ovr** [comment]
Hello @MahmoudTohamy ,

Before using hooks, you should set the client by `CubeProvider`.

https://cube.dev/docs/@cubejs-client-react#cube-provider

Thanks

**Comment by paveltiunov** [comment]
@MahmoudTohamy Did you have a chance to resolve this issue?
