### ISSUE TITLE
React Dashboard doesn't work with Recharts

### ISSUE THREAD

**Issue by kmarenov** [cube-js/cube.js#1735]
I created a dashboard as described in the [react-dashboard.cube.dev](https://react-dashboard.cube.dev/) tutorial, but I got the error described here [https://github.com/recharts/recharts/issues/2360](https://github.com/recharts/recharts/issues/2360)

Replacing the recharts version in the dashboard app with "2.0.0-beta.8" (without ^) works for me.

**Comment by vasilev-alex** [comment]
Hi @kmarenov! Thanks for posting it here. You're right, this issue comes from `recharts`. We're going to hardcode the version to fix it.

**Comment by vasilev-alex** [comment]
Should be fixed now.
