### ISSUE TITLE
Support for ElasticSearch

### ISSUE THREAD

**Issue by AnandChowdhary** [cube-js/cube.js#174]
**Is your feature request related to a problem? Please describe.**
Thanks for already great support with multiple DBMSes! I'd love to get support for ElasticSearch since it's perfect for analytics-related data and aggregation.

**Describe the solution you'd like**
Support for ElasticSearch as a database

**Comment by paveltiunov** [comment]
@AnandChowdhary Hey Anand! Thanks for posting this! This driver actually was requested for 3 times already in https://slack.cube.dev. There's a good chance that someone is working on it already. Makes sense to double check that. 

Here's guide on how to implement driver: https://github.com/cube-js/cube.js/blob/master/CONTRIBUTING.md#implementing-driver

**Comment by chad-codeworkshop** [comment]
@AnandChowdhary did PR #551 solve your issue?

**Comment by AnandChowdhary** [comment]
Looks great, thanks!

**Comment by Dineshagrawal85** [comment]
Hi, elasticsearch support added cubejs?
