### ISSUE TITLE
Postgres: ERROR: type "string" does not exist

### ISSUE THREAD

**Issue by shietpas** [cube-js/cube.js#176]
**Describe the bug**
I have a pre-aggregate defined as an External Rollup, where Postgres is the database type for pre-aggregations.  When cube.js attempts to create the pre-aggregate table, it defines some fields as data type "String", which is not supported in Postgres.  Similar to following
CREATE TABLE stb_pre_aggregations.my_dimension_and_date_pavk001m_lhrjued2_1564600063903 ("myCol1" **STRING**, "myCol2" STRING, "myMeasure" FLOAT)"

Exception: textPayload:  "{"message":"Error querying db","query":"SELECT xxxx","params":["2019-01-01T00:00:00Z","2019-12-31T23:59:59Z"],"error":"Error: type \"string\" does not exist\n    at QueryQueue.parseResult (/srv/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:75:13)\n    at QueryQueue.executeInQueue (/srv/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:64:19)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"}"  
 timestamp:  "2019-07-31T19:08:12.527Z"  

**To Reproduce**
1. Define cube schema using Big Query as primary database type
2. Define pre-aggregate with "external: true" for External Rollup
3. Define external database type to be Postgres
4. Run query that would result in pre-aggregate creation

**Expected behavior**
Table should be created in Postgres under stb_pre_aggregations schema that reflects pre-aggregation table using valid Postgres data types.

**Screenshots**

**Version:**
0.10.16

**Additional context**
Using serverless-google-cloudfunctions

**Comment by paveltiunov** [comment]
@shietpas Thanks for posting this! 

Need to implement this one: https://github.com/cube-js/cube.js/blob/353ed631bd9c227f4d9d77df63b2ebf900a680ed/packages/cubejs-query-orchestrator/driver/BaseDriver.js#L157

**Comment by shietpas** [comment]
@paveltiunov I assume this means overriding the fromGenericType method in the PostgresDriver.js file.  Can I edit that in this GitHub project (fork/PR)?  I'm not familiar with how that ends up in npm under @cubejs-backend/postgres-driver package.

**Comment by paveltiunov** [comment]
@shietpas Yep. You can fork and then provide PR. We'll release it for npm then.
