### ISSUE TITLE
GraphQL query syntax for Cube.js 

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#1765]
**Is your feature request related to a problem? Please describe.**
Following a recent discussion in [Cube.js Slack](https://slack.cube.dev), I'd like to propose a new GraphQL query syntax for Cube.js as an alternative to the current JSON-based [Cube.js query format](https://cube.dev/docs/query-format). This new GraphQL query syntax might be more concise, expressive, and developer-friendly as GraphQL has already gained a lot of popularity.

**Describe the solution you'd like**
It would certainly be a massive effort including these steps:
— a documented GraphQL-based query syntax is added to Cube.js
— a GraphQL server is included into Cube.js and ran alongside the current REST API
— based on the data schema provided, GraphQL type definitions are generated automatically

However, as Cube.js query syntax supports numerous features, such as [Data Blending](https://cube.dev/docs/data-blending), is may be tricky to provide an alternative query syntax that covers all existing features and use cases.

**Describe alternatives you've considered**
Keeping the status quo.

**Additional context**
Here's a few example of what this new GraphQL query syntax might look like.

1a. A simple query using the current Cube.js query syntax:

```javascript
{
  measures: [ 'Repos.count' ],
  dimensions: [ 'Repos.language' ],
}
```

1b. A simple query using the proposed Cube.js GraphQL query syntax

```graphql
{
  Repos {
    count
    language
  }
}
```

2a. A complex query using the current Cube.js query syntax:

```javascript
const MostUsedKnownLanguage = {
  measures: [ 'Repos.count' ],
  dimensions: [ 'Repos.language' ],
  filters: [ {
    dimension: 'Repos.language',
    operator: 'notEquals',
    values: [ 'Unknown' ],
  } ],
  order: {
    'Repos.count': 'desc',
  },
  limit: 1,
}
```

2b. A complex query using the proposed Cube.js GraphQL query syntax

```graphql
query MostUsedKnownLanguage(limit: 1) {
  Repos {
    count(orderBy: DESC)
    language(filter: { operator: NOT_EQUALS, values: [ 'Unknown' ] })
  }
}
```

**Comment by MattGson** [comment]
I don't think the proposed syntax really makes sense.

This query:
```
{
  Repos {
    count
    language
  }
}
```
implies that the response json would be:
```
{
    "repos": {
        "count": {...}
        "language": {...}
    }
}
```
I assume this is not what is actually intended?

**Comment by igorlukanin** [comment]
@MattGson You're right, the constraint that GraphQL query shape matches the response shape is certainly violated here. Is it really an issue? I assume that one should work with Cube.js [ResultSet](https://cube.dev/docs/@cubejs-client-core#result-set) object and its methods anyway rather than use the response data directly.

**Comment by MattGson** [comment]
@igorlukanin I suppose this constraint is not really an issue? I feel like it might be difficult to benefit from GraphQL though? The main benefit I can see would be utilising the schema and existing tooling for this. Of particular benefit are things like type generation and auto-documentation which cannot be done easily with REST.  

If there is no query response schema, then what is the benefit? The query syntax seems like it would be an improvement in that it can be linted and auto-completed with existing tooling but not otherwise. I would say that using GraphQL syntax without describing a graph is not intuitive and probably a downgrade from the current query syntax, particularly for people who already use GraphQL regularly.

**Comment by rpaik** [comment]
Closing this issue and moving the conversation to the [Cube.js forum](https://forum.cube.dev/t/graphql-query-syntax-for-cube-js/53).

**Comment by tomsej** [comment]
Think Bitquery did something similar. They build GraphQL on top of their activecube and Clickhouse. So I think their syntax can be a good inspiration:

**Result**: https://graphql.bitquery.io/ide#
**Video**: https://www.youtube.com/watch?v=k4Ij0U4kw1U

So I do not really think it would be downgrade to the current query syntax.

**Comment by tomsej** [comment]
> I don't think the proposed syntax really makes sense.
> 
> This query:
> 
> ```
> {
>   Repos {
>     count
>     language
>   }
> }
> ```
> 
> implies that the response json would be:
> 
> ```
> {
>     "repos": {
>         "count": {...}
>         "language": {...}
>     }
> }
> ```
> 
> I assume this is not what is actually intended?

Actually this query:

```
{
  Repos {
    count
    language
  }
}
```
Implies something like this:

```
{
    "repos": {
        "count": 111
        "language": "en"
    }
}
```
