### ISSUE TITLE
Add support for redis sentinel

### ISSUE THREAD

**Issue by jrylander** [cube-js/cube.js#1769]
We are using Redis Sentinal at our company and therefore cube.js cannot use the Redis server(s)

I propose we use ioredis like described in https://github.com/cube-js/cube.js/issues/146#issuecomment-591085482 by @keeganmccallum

We use ioredis for other services at our company and it seems to work well

```
const Redis = require('ioredis');

module.exports = function createRedisClient(url) {
    // map exec responses to match node-redis: https://github.com/luin/ioredis/wiki/Migrating-from-node_redis
    Redis.Pipeline.prototype.execAsync = function () {
        return new Promise((resolve, reject) => {
            // rely on scope
            this.exec(function (err, res) {
                console.log(err, res)
                if (err) return reject(err);
                return resolve(res.map((nestArr) => nestArr[1]));
            })
        })
    };
    const [host, port] = url.replace('redis://', '').split(':');
    let options = {
        sentinels: [{ host, port }],
        name: "mymaster"
    };

    if (process.env.REDIS_TLS === 'true') {
        options.tls = {};
    }

    if (process.env.REDIS_PASSWORD) {
        options.password = process.env.REDIS_PASSWORD;
    }

    const client = new Redis(options);

    ['brpop', 'del', 'get', 'hget', 'rpop', 'set', 'zadd', 'zrange', 'zrangebyscore', 'keys'].forEach(
        k => {
            client[`${k}Async`] = client[k];
        }
    );

    return client;
};
```

**Comment by jrylander** [comment]
I do not have so much time but will try to build cube.js locally to test out solution(s)

**Comment by jrylander** [comment]
I have started looking into this feature now

**Comment by johanjvrens** [comment]
Any progress on this feature?

**Comment by jrylander** [comment]
I am working on https://github.com/cube-js/cube.js/pull/1815 and more specifically with ioredis not being stable when connections gets created and destroyed. I am makign progress (I think :) )

**Comment by jrylander** [comment]
Latest change (making the pool call disconnect instead of end seems to have made ioredis happy). I would be glad if more people could the this now.
