### ISSUE TITLE
Access USER_CONTEXT in asyncModule

### ISSUE THREAD

**Issue by gusthavosantana** [cube-js/cube.js#1794]
**I need to load the schemas dynamically based on the current tenant (this data is in the `req.authInfo` object)**

Ex: For a tenant 1 I need to load schemas A and B, for a tenant 2 I need to load schemas C and D.
Ideally, I could have access to `USER_CONTEXT` within the callback function of `asyncModule`.

Do you have any idea how this can be resolved?

The code below demonstrates the way I thought about implementing. This code does not work because I made the callback function of asyncModule receive context, which would be the request context. I also hid the generateSchema function.

```
const fetch = require('node-fetch');
const { BASE_URL } = require('../config/envVariables');

asyncModule(async (context) => {

  const currentApp = context.authInfo.appId;

  const response = await fetch(`${BASE_URL}/schemas`);
  const schemas = await response.json();
  const filteredSchemas = schemas.filter(currentSchema => currentSchema.appId === currentApp);

  filteredSchemas.forEach((schema) => {
       generateSchema(schema);
  });
  
  function generateSchema(schema) {
      ...
  }
});
```

**Comment by paveltiunov** [comment]
Hey @gusthavosantana ! You should use `COMPILE_CONTEXT` instead: https://cube.dev/docs/multitenancy-setup#user-context-vs-multitenant-compile-context.

**Comment by gusthavosantana** [comment]
It worked. Thanks @paveltiunov !
