### ISSUE TITLE
[question] How to obtain percentage of total?

### ISSUE THREAD

**Issue by philippefutureboy** [cube-js/cube.js#180]
Given the following table and data:

```sql
CREATE TABLE IF NOT EXISTS Orders (
  id INT,
  status VARCHAR(10) NOT NULL,
  amount INT NOT NULL
)
SELECT * FROM (
  SELECT 1 as id, 100 as amount, 'new' status
    UNION ALL
  SELECT 2 as id, 200 as amount, 'new' status
    UNION ALL
  SELECT 3 as id, 300 as amount, 'processed' status
    UNION ALL
  SELECT 4 as id, 500 as amount, 'processed' status
    UNION ALL
  SELECT 5 as id, 600 as amount, 'shipped' status
) AS t;
```

The following query allows to obtain the percentage that each entry represents with regard to the total:

```sql
SELECT
  status,
  SUM(amount) AS amount,
  SUM(amount) / totalAmount * 100.00 as percentage_amount
FROM Orders
CROSS JOIN (
  SELECT SUM(amount) AS totalAmount FROM Orders
  WHERE Orders.status IN ('new', 'processed')
) AS t
WHERE Orders.status IN ('new', 'processed')
GROUP BY Orders.status;
```

Which returns the following:

| status | amount | percentage_amount |
|-------|---------|---------------------|
| new | 300 | 27.272727 |
| processed | 800 | 72.727273 |

Is there a way to obtain the `percentage_amount` in Cube.js? I couldn't find a way to do this in the docs. More explicitly, I couldn't find a way to do the SUM across all of the values that can be found in the CROSS JOIN.

Thanks a lot!

Cheers,

Phil

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! Usually such type of calculations are done on client side if this for example is required to show pie chart percentages. In case you need to calculate it in SQL you can use window functions.

**Comment by philippefutureboy** [comment]
@paveltiunov Interesting. I would have expected these calculations to be carried out in the Cube instead. My philosophy is that all data processing post data-warehouse should be done within the database if possible, so as to centralize all the code that manipulates the data. Then any post-processing such as formatting and reorganizing the data can be done in a layer after the Cube.

By window functions, do you mean [`rollingWindow`](https://cube.dev/docs/measures#parameters-rolling-window)?

**Comment by paveltiunov** [comment]
@philippefutureboy Yep. Right. But this case is special because it's kind of non-invariant measure that depends on result set. 

By window functions I mean SQL window functions. For example in Postgres: https://www.postgresql.org/docs/9.1/tutorial-window.html

**Comment by paveltiunov** [comment]
Closing it as it seems answered.

**Comment by philippefutureboy** [comment]
Sorry! I totally didn't see the answer!

Before you close, can you give me an example of how that would translate in a schema?

**Comment by paveltiunov** [comment]
@philippefutureboy Do you mean on how to write such window function SQL?

**Comment by philippefutureboy** [comment]
There's definitely a little bit of that XD
But more importantly what I'd like to know where to put it in the schema. Do I declare it like a normal measure and just write the necessary sql in the `sql` prop?

And for info, the most used version of MySQL, 5.7 [doesn't have direct support for window functions](https://stackoverflow.com/questions/37538350/mysql-workaround-for-window-functions).

**Comment by paveltiunov** [comment]
@philippefutureboy Its usually declared in `sql` of a cube rather than a measure.

**Comment by philippefutureboy** [comment]
Ok! I'm not totally clear on the concept but I'll go check some examples online and see how it can apply to Cube.js :)

Thank you!

**Comment by paveltiunov** [comment]
You can also consider using data blending API: https://cube.dev/blog/introducing-data-blending-api/.

**Comment by Phil-Barber** [comment]
Another way to achieve this (if the breakdown is a known distinct set) is to use `filter` in a measure to define measures for: amountAsNew, amountAsProcessed, totalAmount and then use a calculated measure for percentageAmountAsNew:

https://cube.dev/docs/recipes/referencing-dynamic-measures

eg.
```
    amountAsNew: {
      sql: `amount`,
      type: "sum",
      filters: [
        {
          sql: "status = 'new'",
        },
      ],
    },
    totalAmount: {
      sql: `amount`,
      type: "sum",
    },
    percentageAmountNew: {
      sql: `${amountAsNew} / ${totalAmount} * 100`,
      type: "number",
      format: "percent",
    },
```
