### ISSUE TITLE
Unexpected string literal Bigquery

### ISSUE THREAD

**Issue by tonxxd** [cube-js/cube.js#182]
**Describe the bug**
Hello, I am using cubejs with BigQuery where I store analytics data. There are nested fields in the database. 
When using the cubejs server ui in the schema section to automatically generate the schema for my table I am not able to run queries against BigQuery since i get this error

Error: Syntax error: Unexpected string literal "parentField.childField" at [*:*] when querying.

The sql field generated in the schema is like
`${CUBE}."parentField.childField"`

It should be 
`${CUBE}.parentField.childField`

Editing the schema file removing " solve the issue

**Comment by paveltiunov** [comment]
@tonxxd Hey Enrico! Thanks for posting this! Yep. I think I understand what's going on.

**Comment by paveltiunov** [comment]
Need to support sql generation for nested fields by returning `nestedName` from `BigQueryDriver`: https://github.com/cube-js/cube.js/blob/10c635c7d60750ce792591ad1bb7908b442efcee/packages/cubejs-bigquery-driver/driver/BigQueryDriver.js#L94

**Comment by paveltiunov** [comment]
@tonxxd Hey Enrico! Just fixed. Could you please update version and check?

**Comment by tonxxd** [comment]
Hey! Thank you very much for the fast response. I updated the package, now some fields seam ok, others not. For example i have a repeated nested field that throws this error while querying 

<img width="618" alt="Schermata 2019-08-15 alle 18 00 36" src="https://user-images.githubusercontent.com/2827496/63108222-9fdb8f00-bf86-11e9-8c64-b8604965cb39.png">
<img width="1311" alt="Schermata 2019-08-15 alle 17 59 56" src="https://user-images.githubusercontent.com/2827496/63108224-a0742580-bf86-11e9-9c80-bf8221b49fc5.png">

Error: Error: Cannot access field items on a value with type ARRAY<STRUCT<items ARRAY<STRUCT<total FLOAT64, brandId STRING, quantity INT64, ...>>, shipping_address STRUCT<zip STRING, country STRING, street STRING, ...>, shipping_method STRING, ...>> at [2:28]

**Comment by sharno** [comment]
Is there a fix for the new error like 
```
Error: Error: Cannot access field balance on a value with type ARRAY<STRUCT<price FLOAT64, balance FLOAT64, currency_iso STRING, ...>> at [5:41]
```
 or should I open another bug for this?
