### ISSUE TITLE
Feature Request: Disable automatic fetching when using the dashboard

### ISSUE THREAD

**Issue by benswinburne** [cube-js/cube.js#1826]
Athena is my primary data store which is partitioned by date. As such queries without a date filter query my entire dataset of many gigs. Unfortunately when a developer loads up the dashboard to build reports etc, it automatically attempts to fetch everything as soon as the page loads. This incurs large, slow, costly queries which the developer has to remember to go into Athena and cancel (never happens).

**Describe the solution you'd like**
I'd like automatically run to be off by default.
A UI checkbox for run automatically for those who want to continue the behaviour.

**Describe alternatives you've considered**
- Turn on rollupOnlyMode on the server - not ideal when trying to build/plan rollups.
- Automatically add a date range filter to all queries in dev mode - not ideal for obvious reasons.

```
queryTransformer: (query) => {
  if (process.env.NODE_ENV !== 'production') {
    query.filters.push({
      member: 'Events.dt',
      operator: 'inDateRange',
      values: [nowMinusOneWeek(), now()],
    });
  }

  return query;
},
```

**Comment by keydunov** [comment]
HI @benswinburne,

**Comment by benswinburne** [comment]
@vasilev-alex great, thanks for your work on this! Much appreciated.

**Comment by manikasharma70** [comment]
@vasilev-alex How can we use the same enhancement in the UI in dashboard-app using the QueryBuilder component in React-dashboard
