### ISSUE TITLE
Is Athena required for serverless deployments?

### ISSUE THREAD

**Issue by dcworldwide** [cube-js/cube.js#184]
If I were to deploy cube.js using AWS serverless architecture, is athena required? 

The docs https://cube.dev/docs/deployment#serverless do not mention whether Athena is optional or required. But when reading it, I assume it is required because there are athena keys in the serverless.yml config. I'm evaluating the idea of using Postgres RDS as the sole datasource for cubejs.

**Comment by paveltiunov** [comment]
@dcworldwide Thanks for posting this one! It isn't required. We should adjust documentation and scaffolding to make it clear.

**Comment by dcworldwide** [comment]
Great thanks! That's a big help.

**Comment by platform-kit** [comment]
@paveltiunov, does this mean the serverless function created by `cubejs create cubejs-serverless -d athena -t serverless` could be deployed on Netlify (which deploys serverless Node functions to AWS Lambda)? If so, could you point out what kind of modifications might be needed?

**Comment by hassankhan** [comment]
Hi @platform-kit, we're not exactly sure what modifications would be needed if deploying through Netlify. From what I can tell, it supports functions but there are other aspects of Serverless deployment configuration (such as VPC setup) that don't seem to have a Netlify equivalent.
