### ISSUE TITLE
Pre-aggregation queries not compatible with MSSQL

### ISSUE THREAD

**Issue by antoniablair** [cube-js/cube.js#185]
**Describe the bug**
Trying to use the preAggregation features throws errors when using MSSQL. It is unable to create or write to `stb_pre_aggregations` due to some of the SQL syntax. 

Some examples are ~ `NOW(),` (in the refresh strategy), creating a table with `CREATE TABLE xyz AS SELECT`, and `trunc_data`. 

**To Reproduce**
1. While using MSSQL, declaring preAggregations and then hitting the Cube API with queries that would use them will show the error in logs / console. 

**Expected behavior**
When resolved, the preAggregations would be able to build as expected.

**Comment by paveltiunov** [comment]
@antoniablair Hey Antonia! Thanks for posting it! Should be fixed now.

**Comment by antoniablair** [comment]
@paveltiunov The pre-aggregation tables are building as expected (other than the separate segment issue I opened), thank you!

**Comment by paveltiunov** [comment]
Great to hear that!

**Comment by MuhammadMattiullah** [comment]
Hello @antoniablair can you please tell me how to allow write access to pre-aggregation in cube js ?
https://github.com/cube-js/cube.js/issues/233  
Updated Pre-aggregation Block in schema File:
preAggregations: {
EnergyWrtAssetId: {
type: rollup,
measureReferences: [SumOfEnergy],
dimensionReferences: [assetid],
timeDimensionReference: createdat,
granularity: day
}
}
I got the below error when i try to run the query:

Error: parse sql 'CREATE SCHEMA IF NOT EXISTS stb_pre_aggregations' error: unexpected SCHEMA at position 15 near schema

But when i removed the pre-aggregation from the schema file then its working fine and results are expected but after adding the pre-aggregation block to my schema file then i got the error provided above..
Kindly guide me how can i achieve the pre-aggregation
Your response would be highly appreciated!

**Comment by antoniablair** [comment]
@MuhammadMattiullah Are you using SQL Server or a different database? Which version of CubeJS are you using?

**Comment by MuhammadMattiullah** [comment]
@antoniablair Thanks for your response!
I am using mongodb and for it to connect with cube js i am using mongodb connecterBI i.e mongosqld for connection and queries.

**Comment by MuhammadMattiullah** [comment]
@antoniablair cubejs version 0.10.15
