### ISSUE TITLE
Preaggregations with segments cause error with MSSQL

### ISSUE THREAD

**Issue by antoniablair** [cube-js/cube.js#186]
**Describe the bug**
Using segments with pre-aggregations results in a query error with MSSQL: `Error: Incorrect syntax near the keyword 'AS'.`

Evaluations on a lookup do not return true or false in MSSQL so it likely needs special syntax.

**To Reproduce**
1. In dev mode, create a pre-aggregation that utilizes an existing segment, i.e. `      segmentReferences: [mySegment],`
2. Attempt to use a query that calls that pre-aggregation, and the error will show up in the console. 

**Expected behavior**
It should be able to build a pre-aggregation table or query an existing table if the pre-aggregation schema contains a segment. 

**Screenshots**

**Version:**
0.10.25

**Comment by paveltiunov** [comment]
@antoniablair Hey Antonia! Thanks for posting this! Should be fixed now. Could you please check?
