### ISSUE TITLE
Dynamic Schema

### ISSUE THREAD

**Issue by killix** [cube-js/cube.js#187]
**Is your feature request related to a problem? Please describe.**

I would like to how it's possible to generate dynamic schema?
I tried this code:

```javacript
const configurations = [
  {
    name: `Users`,
    content: {
      sql: `SELECT * FROM public.Users`,

      joins: {},

      measures: {
        count: {
          type: `count`,
          drillMembers: ['uuid', 'name', 'createdAt', 'updatedAt']
        }
      },

      dimensions: {
        uuid: {
          sql: `uuid`,
          type: `string`
        },

        name: {
          sql: `name`,
          type: `string`
        },

        createdAt: {
          sql: `created_at`,
          type: `time`
        },

        updatedAt: {
          sql: `updated_at`,
          type: `time`
        },

        startedAt: {
          sql: `started_at`,
          type: `time`
        }
      }
    }
  }
]

configurations.forEach((configuration) => {
  cube(configuration.name, configuration.content)
})
```

but i got lot of errors like : 
`cube: child "sql" fails because ["sql" is required]` or `child "dimensions" fails because [child "uuid" fails because [child "case" fails because ["case" is required], "sql" is not allowed, child "sql" fails because ["sql" must be a Function]]]`

**Comment by paveltiunov** [comment]
@killix Hey Issam! Thanks for posting this! Actually there's transpiler processing before JavaScript in schema files is executed. It replaces `sql` properties with appropriate functions. It works only inside `cube` definitions:
```
configurations.forEach(configuration => {
  cube(configuration.name, {
    name: `Users`,
    content: {
      sql: `SELECT * FROM public.${configuration.table}`,

      joins: {},

      measures: {
        count: {
          type: `count`,
          drillMembers: ['uuid', 'name', 'createdAt', 'updatedAt']
        }
      },

      dimensions: {
        uuid: {
          sql: `uuid`,
          type: `string`
        },

        name: {
          sql: `name`,
          type: `string`
        },

        createdAt: {
          sql: `created_at`,
          type: `time`
        },

        updatedAt: {
          sql: `updated_at`,
          type: `time`
        },

        startedAt: {
          sql: `started_at`,
          type: `time`
        }
      }
    }
  })
})
```
We should add this to the docs.

**Comment by killix** [comment]
thanks @paveltiunov for you help. Unfortunately, i tried your code and i got the same error.

**Comment by paveltiunov** [comment]
@killix Sorry. Just edited it. Copied together with `content` property. Could you please try again?

**Comment by killix** [comment]
it's work.Thanks!

**Comment by Rashiq796** [comment]
is there any way to solve converting into function issue?. my schema is returned from an api request. so it show the error "sql should be a function"
`const fetch = require('node-fetch');
const Funnels = require('Funnels');

asyncModule(async () => {
  const configuration = await (await fetch('http://localhost:4001/get-schema')).json();
  configuration.forEach(item=>{
    cube(item.name,{
      sql: `SELECT * FROM public."${item.table}"`,
      joins: {
        Locations:{
          relationship:`hasMany`,
          sql:`"${item.table}".locationid=${Locations}.locationid`
        }
      },
    
      measures: item.measures,  
      dimensions:item.dimensions,
    })
  })
})`

**Comment by paveltiunov** [comment]
Hey @Rashiq796 ! I believe you're looking for this: https://cube.dev/docs/schema-execution-environment#context-symbols-transpile

**Comment by Rashiq796** [comment]
@paveltiunov thank you for your help. the problem is API returns an json object so it cannot have functions in it. 
schema coming from api is always different.

**Comment by paveltiunov** [comment]
@Rashiq796 Here's how generate schema out of JSON: https://cube.dev/docs/schema-generation#top
