### ISSUE TITLE
VueJs Client, limit not working

### ISSUE THREAD

**Issue by AgussDiaz28** [cube-js/cube.js#188]
**Describe the bug**
When you try to perform a Limit on the query, que query builder, will not send the limit set to the backend. The vue client is not looking for that parameter to sent.

**Comment by paveltiunov** [comment]
@AgussDiaz28 Hey Agustin! Thanks for posting this! As I see there's TODO for it: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-vue/src/QueryBuilder.js#L150
