### ISSUE TITLE
Playground doesn't support time dimension filters

### ISSUE THREAD

**Issue by gane5h** [cube-js/cube.js#189]
**Describe the bug**
If you have a `time` dimension and you try to create a filter, the `operators` are not relevant to `time` dimensions. This is because the `operators` map in `@cubejs-client/core/src/Meta.js` is missing the `time` key (incomplete implementation.)

**To Reproduce**
1. Add a time dimension
2. Add filter for that dimension
3. Observe that the operators dropdown continue to show as if it were a `string` dimension.

**Expected behavior**
Expect operators relevant to date-time fields. Maybe internally consider it to be epoch number and use the operators from the `number` type, but then it'll have to convert it to the relevant `WHERE` clause based on the database.

**Version:**
master

**Additional context**
The playground UI will also need to support a `DateTimePicker`. My database is PostgreSQL.

**Comment by paveltiunov** [comment]
@gane5h Hey Ganesh! Yep. I can confirm that there's lack of this implementation.

**Comment by FanaHOVA** [comment]
Just ran into this myself, seems like a good thing to add. Time filtered queries are a base use case and this really help non-technical users interact with Cube.

@paveltiunov I started digging around the codebase to implement this, but can't decide which datepicker to implement (if any...). What's your take? On http://captable.645ventures.com/ I used [react-day-picker](https://github.com/gpbl/react-day-picker) and didn't have many issues.

**Comment by hburbano** [comment]
Working on a UI for a CubeJs integration just recently found this issue, including the operators as options on the client meta would be a great first step? a small PR adding the time operators to the meta so they are available through both client and QueryBuilder and therefore available for the client/user to implement, and then introduce a new PR with the implementation on the Playground for the different use cases which would definitely be more complex?

**Comment by hassankhan** [comment]
Closing this as the Playground now supports filtering based on time dimensions.
