### ISSUE TITLE
Drilldown UI hooks

### ISSUE THREAD

**Issue by gane5h** [cube-js/cube.js#190]
**Is your feature request related to a problem? Please describe.**
It'll be nice to add a feature to follow the `drillMember` in the playground.

**Describe the solution you'd like**
When I click on a measure column that has a `drillMember` definition, I should be able to unpack the rows that contribute to that metric. For example, 

|Province dimension|Count measure|
|---|---|
|BC|2|
|Alberta|6|

When I click on the "2", take me to the rows that contribute to BC's count. 

This can be implemented using a `WHERE` clause. Build a playground explore view with the dimensions from `drillMembers` and a `WHERE` clause on the drill path (in this case `WHERE province="BC"`

The same logic applies for `timeDimension` columns as well. The entire `date_trunc(...)` should be moved to the `WHERE` clause.

**Comment by paveltiunov** [comment]
@gane5h Hey Ganesh! Thanks for posting this! Already working on it.

**Comment by jdwilkin** [comment]
I am sorry if I missed this, but is there progress on this? thanks

**Comment by vasilev-alex** [comment]
Hi, @gane5h @jdwilkin!

I've updated the docs here https://cube.dev/docs/@cubejs-client-core#result-set-drill-down and created a simple example on codesandbox https://codesandbox.io/s/nostalgic-moore-wk3ev where you can get the idea on how to use the `drillDown` method.
