### ISSUE TITLE
  I'm struggling to see how I would represent the following type of postgres SQL query in a cube.js schema:

### ISSUE THREAD

**Issue by eugeneingram** [cube-js/cube.js#1910]
**Problem**

I'm struggling to see how I would represent the following type of Postgres SQL query in a Cube.js schema:

**Postgres SQL statement**
```
SELECT
    CASE
        WHEN COUNT(tpp.net_total_amount) > 0 THEN
            SUM(tpp.net_total_amount) / COUNT(tpp.net_total_amount)
        ELSE
            NULL
        END AS average_spend_per_customer
FROM
    (
        SELECT
            SUM(ts.total_amount) AS net_total_amount
        FROM
            postgres.transactions AS ts
        WHERE
            ts.transaction_date >= '2020-11-01' AND
            ts.transaction_date < '2020-12-01'
        GROUP BY
            ts.customer_id,
            ts.event_id
    ) AS tpp
;
````

I had the feeling that pre-aggregations might be what I'm after, but that doesn't seem to be the case after looking into them. I can get a list of total amount spent per customer per event with the following schema:

**Cube.js Schema**

```
cube(`TransactionTotalAmountByCustomerAndEvent`, {
  sql: `SELECT * FROM postgres.transactions`,
     
  joins: {
  
  },
      
  measures: {
   sum: {
      sql: `SUM(total_amount)`,
      type: `number`
    }
  },
      
  dimensions: {
    eventId: {
      sql: `event_id`,
      type: `string`
    },
        
    customerId: {
      sql: `customer_id`,
      type: `string`
    },
        
    transactionDate: {
      sql: `transaction_date`,
      type: `time`
    }
  },
      
  preAggregations: {
    customerAndEvent: {
      type: `rollup`,
      measureReferences: [sum],
      dimensionReferences: [customerId, eventId]
    }
  }
});
```

But that is really just giving me the output of the inner SELECT statement grouped by customer and event. How do I query the cube to get the average customer spend per event figure I'm after?

**Comment by igorlukanin** [comment]
Hey @eugeneingram 👋 Would you please have a look at the [calculated measures](https://cube.dev/docs/measures#calculated-measures) feature of Cube.js? I think it might help you to express what you currently have in your outer `SELECT` clause.

**Comment by paveltiunov** [comment]
@eugeneingram Did you have a chance to solve this issue?

**Comment by eugeneingram** [comment]
> Hey @eugeneingram wave Would you please have a look at the [calculated measures](https://cube.dev/docs/measures#calculated-measures) feature of Cube.js? I think it might help you to express what you currently have in your outer `SELECT` clause.

Thanks, but from looking at it, it doesn't do what I need.  I need an inner query to total the amount spent by customers per event.  I then need the outer query to get the average spend per customer.  I don't think calculated measures will help produce this nested query from what I can see and my experiments with it haven't given me what I need. I can get with an SQL query directly against the database the correct figures. A calculated measure will give me the average amount spent per transaction, not the average amount spent by a customer at an event (a customer may make multiple separate transactions at an event).
