### ISSUE TITLE
Weird debugging output of Cube.js CLI

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#1916]
**Describe the bug**
When I run Cube.js CLI, I get weird debugging messages. See `(node:6900) Warning: ...` below:

```
❯ npm run dev

> hello-world@0.0.1 dev
> ./node_modules/.bin/cubejs-server

🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000
🚀 Cube.js server (0.25.30) is listening on 4000
(node:6900) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6900) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
^CReceived SIGINT signal, shutting down in 30s

❯ node -v
v15.3.0

❯ cat package.json| grep @cubejs
    "@cubejs-backend/postgres-driver": "^0.25.30",
    "@cubejs-backend/server": "^0.25.30"
```

**To Reproduce**

Run `npm run dev` in a Cube.js project directory.

**Expected behavior**

No such messages should be shown.

**Screenshots**

<img width="752" alt="Screenshot 2021-01-27 at 14 43 04" src="https://user-images.githubusercontent.com/3852894/106064002-f91d7c80-60ad-11eb-8aa7-3c82f059df9f.png">

**Version:**
0.25.30

**Comment by ovr** [comment]
Hello @igorlukanin ,

We already have an issue for it https://github.com/cube-js/cube.js/issues/1798,
And PR https://github.com/cube-js/cube.js/pull/1817

Thanks
