### ISSUE TITLE
Subquery Issue

### ISSUE THREAD

**Issue by kartblanch** [cube-js/cube.js#192]
Hi, guys!
I have a problem in your example with part subquery [(https://cube.dev/docs/subquery)](url).
First, I created in my Postgresql DataBase two tables (sales_managers and deals) with necessary column. After that,  created Cube.js Schemas like in example. Finally, I'm running my request:
```
let properties = {
            measures: ["Deals.amount"],
        };
        let query = {
            query: JSON.stringify(propertiesObject)
        };

        request({url: cubeApiUrl, qs: query}, function (err, response, body) {
            if (err) {
                reject(err);
                return;
            }

            let res = JSON.parse(body);
            .......
        });
```

... and see a problem: 

> primary key for 'SalesManagers' is required when join is defined in order to make aggregates work properly

So...okey, I add to this tables PKs (id, sales_manager_id) but the problem is same. Has anyone seen and solved this problem?  Thanks for your attention.

**Comment by paveltiunov** [comment]
@kartblanch Hey Anton! Thanks for posting this! Could you please share your Cube.js schema files?

**Comment by kartblanch** [comment]
Hi, Pavel! Yes, of course.

```
cube(`SalesManagers`, {
    sql: `select * from sales_managers`,

    joins: {
        Deals: {
            relationship: `hasMany`,
            sql: `${SalesManagers}.id = ${Deals}.sales_manager_id`
        }
    },
    dimensions: {
        dealsAmount: {
            sql: `${Deals.amount}`,
            type: `number`,
            subQuery: true
        }
    },
    measures: {
        averageDealsAmount: {
            sql: `${dealsAmount}`,
            type: `avg`
        }
    }
});
```
As you can see, the Schema composed as in the example. Thank you in advance!

**Comment by paveltiunov** [comment]
@kartblanch Yep. I see. `primaryKey` is missing in `cube` definition. Here's info on how you can add it: https://cube.dev/docs/joins#setting-a-primary-key

**Comment by kartblanch** [comment]
@paveltiunov Thanks for your help! It's working. I think information about PK will be add in subquery chapter by author in the future. Good luck in further development!

**Comment by paveltiunov** [comment]
@kartblanch Great to hear that! Yeah. It probably makes sense to adjust doc a little. Would love to see such docs pull request!
