### ISSUE TITLE
Multiplication Measure or Dimension

### ISSUE THREAD

**Issue by botisma** [cube-js/cube.js#193]
I don't know if i need to put that as a bug or a feature request :/
But i got some difficulty to understand the difference between dimensions/measures and use multiplication in my use case.

My use case:

I have this `PRODUCTS` table

```
| id |  product_id | inStock | updated_at | created_at |
|----|:--------:|---------|------------|------------|
| 1  | product1 | 200     | ...        | ....       |
| 2  | product2 | 150     | ...        | ....       |
| 3  | prosuct3 | 50      | ...        | ....       |
```
and `PRODUCTS_PRICES` table

```
| id | product_id | country | price  | created_at |
|----|:----------:|---------|--------|------------|
| 1  | product1   | en      | 20.34  | ....       |
| 2  | product2   | en      | 123.45 | ....       |
| 3  | prosuct3   | en      | 56.78  | ....       |
```

And theses related cubes:

```javascript
cube(`ProductPrices`, {
  sql: `SELECT * FROM product_prices`,

  dimensions: {
    price: {
      sql: `price`,
      type: `number`
    },
    country: {
      sql: `country`,
      type: `string`
    },
    product_id: {
      sql: `product_id`,
      type: `number`
    },
    id: {
      sql: `id`,
      type: `string`,
      primaryKey: true,
      shown: true
    }
  }
})

cube(`Products`, {
  sql: `SELECT * FROM products`,
  joins: {
    ProductPrices: {
      relationship: `hasMany`,
      sql: `${ProductPrices}.product_id = ${Products}.product_id`
    }
  },

  dimensions: {
    inStock: {
      sql: `inStock`,
      type: `number`
    },
    value: {
      sql: `${Products}.inStock*${ProductPrices}.price`,
      type: `number`
    },
    product_id: {
      sql: `product_id`,
      type: `number`
    },
    id: {
      sql: `id`,
      type: `string`,
      primaryKey: true,
      shown: true
    }
  }
})

```

With this query:

```
{
  renewQuery: true,
  // measures: ['Products.amount'],
  dimensions: ['Products.amount'],
  timeDimensions: [
    {
      dimension: 'Products.created_at',
      dateRange: ['2019-01-01', '2019-07-28'],
      granularity: 'day'
    }
  ],
  filters: [
    {
      dimension: 'Products.shop_id',
      operator: 'equals',
      values: [987]
    }
  ],
  order: {
    'Products.date': 'asc'
  }
}
```

- It's sound weird to me to have `price`, `inStock`, `value` in the `dimensions` object instead to the `measures` object.
When i try to move this field in `measures`. I got an SQL error about the `groupBy`

- I am not able to add an `SUM` of the `amount`. If  i update the `Products` cube to include:

```javascript
  measures: {
    total: {
      sql: `${amount}`, // or `${Products}.inStock*${ProductPrices}.price`,
      type: `sum`
    }
  },
```

i got some error bout multiplication and subquery. How i can achieve that?

Thanks guys for your help.

**Comment by paveltiunov** [comment]
Hey @botisma ! 
> It's sound weird to me to have price, inStock, value in the dimensions object instead to the measures object.

Yeah. I believe `price`, `inStock` and `value` should be measures indeed.

> When i try to move this field in measures. I got an SQL error about the groupBy

I believe it's due to you use `number` type but referencing just a column. It should be `sum` type instead.

> I am not able to add an SUM of the amount. If i update the Products cube to include:

Should it be `value` instead of `amount`?

> i got some error bout multiplication and subquery. How i can achieve that?

It's because you defined join as `hasMany`. If there're many prices for the product in this table you should add additional condition on how to select only one in the join and change type to `belongsTo`. For example add `country` condition.

**Comment by botisma** [comment]
i tried to convert `inStock` and `value` to `measures` and update the type to 'sum'. It's work for `inStock` but about `value` i got `null` in all values. The weird think, it's when i run the query generated by cube i see the good result for `value`

> Should it be value instead of amount?
yes

**Comment by paveltiunov** [comment]
@botisma Do you mean when you run SQL you see right results and when you see it in Playground UI there're nulls?

**Comment by botisma** [comment]
when i run the SQL i see the result, and when i console log the result coming from the client i got null. I think it's something around the casting. It happened when i add a casting like `${Products}.inStock::FLOAT*${ProductPrices}.price::FLOAT`

Also i just figure out by debugging this issue. All sum value is converted as a string result which weird, no?

**Comment by botisma** [comment]
> Also i just figure out by debugging this issue. All sum values (inStock, value) is converted as a string result which weird, no?

it's look like this is coming from `pg` nvm

**Comment by paveltiunov** [comment]
@botisma Interesting. Could you please share resulting SQL from Playground? And could you please provide results you see when you run this SQL in DB directly and API Response from Cube.js?

**Comment by paveltiunov** [comment]
@botisma Did you have a chance to resolve it?

**Comment by nagin22** [comment]
jhb
