### ISSUE TITLE
Cubejs assumes server timezone and ignores the user's request

### ISSUE THREAD

**Issue by gane5h** [cube-js/cube.js#196]
**Describe the bug**
The API gateway assumes server time zone even though the user explicitly specifies a timezone. 

**To Reproduce**
Query a table with a `ts_column timestamp` column and try the following aggregate query:

```
select date_trunc('month', ts_column), count(*)
from transactions
group by 1
```
Returns data like the following:
![image](https://user-images.githubusercontent.com/182680/64070130-6efa8b80-cc0f-11e9-88b8-d79ed78cab9e.png)

Request
![image](https://user-images.githubusercontent.com/182680/64070159-f34d0e80-cc0f-11e9-8b12-0202dc2bcd41.png)

But the response from the cubejs/server – 

![image](https://user-images.githubusercontent.com/182680/64070141-b54fea80-cc0f-11e9-94ec-fc26f5b765a8.png)

The 17:00 is because the server is running in the Pacific timezone.

**Expected behavior**

**Additional context**

The bug is in 
`return moment(value).format(moment.HTML5_FMT.DATETIME_LOCAL_MS)`

where `moment()` uses localtime. It should be more explicit `moment.utc()` and then convert to the required timezone.

**Comment by paveltiunov** [comment]
@gane5h Hey Ganesh! Thanks for posting this! What DB do you use?

**Comment by gane5h** [comment]
@paveltiunov PostgreSQL

**Comment by paveltiunov** [comment]
@gane5h Makes sense. Could you please share your schema file?

**Comment by gane5h** [comment]
```
cube(`UserTransactions`, {
  sql: `
  WITH userwallets as (
    SELECT 
    substr(e.data , 13 ) AS "logged_proxy"
    FROM
    live.block_log_events e
  )
  SELECT
  to_timestamp(${CRYPTO_EPOCH} + (block_id >> 32))::timestamp at time zone 'UTC' AS block_signed_at,
  '0x' || encode("to", 'hex') AS to_address
FROM
  live.block_transactions t
  WHERE "to" in (
select logged_proxy from userwallets
  )
` ,

  measures: {
    count: {
      type: `count`,
      drillMembers: []
    },
  },

  dimensions: {
    blockSignedAt_date: {
      sql: `date_trunc('day', ${CUBE}.block_signed_at)`,
      type: `time`
    },
    blockSignedAt_week: {
      sql: `date_trunc('week', ${CUBE}.block_signed_at)`,
      type: `time`
    },
    blockSignedAt_month: {
      sql: `date_trunc('month', ${CUBE}.block_signed_at)`,
      type: `time`
    },
    blockSignedAt: {
      sql: `${CUBE}.block_signed_at`,
      type: `time`
    },
    toAddress: {
      sql: `to_address`,
      primaryKey: true,
      type: `string`
    }
  }
});

```

**Comment by gane5h** [comment]
@paveltiunov Also, no rush – I'm stepping away for the long weekend and will pick up on Tuesday. Thanks for all your help!

**Comment by paveltiunov** [comment]
@gane5h I see. Your definition lacks type conversion I believe.
You should request your dimension using
```
{
  measures: ['UserTransactions.count'],
  dimensions: ['UserTransactions.blockSignedAt.month']
}
```
Cube.js automatically does all timezone and granularity conversions. This one should work as expected.

`moment(value)` is used there because Postgres driver returns dates as javascript `Date` object. In case server is in some non-UTC time zone and you request local dates in Postgres query there will be conversion.

**Comment by gane5h** [comment]
Hey @paveltiunov – your suggestion works beautifully. Thanks.

I feel I'm missing something. When your dimension is `UserTransactions.blockSignedAt.month`, is that referring to `blockSignedAt_month` or `blockSignedAt` with `date_trunc` applied?

The use of ".' to specify the granularity – is this in the docs somewhere? I must have missed it.

**Comment by paveltiunov** [comment]
@gane5h Hey Ganesh! Yep. It's in the docs: https://cube.dev/docs/query-format. `UserTransactions.blockSignedAt.month` refers to `blockSignedAt` with `date_trunc` and time zone conversion functions applied. It's also equivalent to
```
{
  timeDimensions: [{
    dimension: 'UserTransactions.blockSignedAt',
    granularity: 'month'
  }]
}
```

**Comment by gane5h** [comment]
OK, this is brilliant! Thank you!

I can now delete all of the other custom dimensions I built.
