### ISSUE TITLE
issues with websocket on v0.26.2 

### ISSUE THREAD

**Issue by lielran** [cube-js/cube.js#1974]
after migration, it seems that the first call for cube is pass the auth and return the result (after successful handshake: true)
first query return data. 
and all the rest of the queries got to the server with empty `securityContext`

**Comment by ovr** [comment]
Hello @lielran, thank you for bug report.

Started to work on it, I will come back shortly with results of testing.

**Comment by lielran** [comment]
The missing `SecurityContext` is shown on `queryTransformer` function from the second message.

**Comment by ovr** [comment]
Released `v0.26.4`, will be published in ~10 minutes. Thanks
