### ISSUE TITLE
How can add meta into schema's dimension when I generating schema by generate-schema api?

### ISSUE THREAD

**Issue by radiorz** [cube-js/cube.js#1988]
**Problem**

How can add meta into schema's dimension when I generating schema by generate-schema api?

I want to add meta like this 
```
cube(`Cube`,{
  ···
  dimensions:{
    patient:{
        sql: `${CUBE}.\`bedClass\``,
        type: `string`,
        // here:
       meta:{
          ...
       }    
    }
  }

}）
```

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `` //, ...
})
```

**Comment by rongfengliang** [comment]
@radiorz  i think just generate one  <name>.js file  which contains meta info will work

**Comment by vasilev-alex** [comment]
hi @radiorz! There's no way other than manual editing at the moment. The docs https://cube.dev/docs/dimensions#parameters-meta
