### ISSUE TITLE
Angular: How to set token after user is logged into the app?

### ISSUE THREAD

**Issue by hobojoe** [cube-js/cube.js#1992]
**Problem**

A very common use case is to only request the CubeJS token once the user is authenticated to my app. Then I can provide a token initialize CubeJS.

The way it is on the docs (https://cube.dev/docs/@cubejs-client-ngx#api), you set the config on the app.module, hence, before the user has a chance to login to the app.

How would I set the token AFTER I know who the user is (after he has authenticated to my app)?

Thanks

**Comment by hobojoe** [comment]
I managed to get around it, not sure if it is the right way to do it or not.

I created a CubeJsService, which holds the reference to the CubejsClient, and I inject the service into the components I need.

On the constructor I can wait for the authentication to complete before instantiating the CubejsClient:

```
@Injectable({ providedIn: 'root' })
export class CubeJsService {

    private _cubejsSubject = new BehaviorSubject<CubejsClient>(null);
    public cubeJs$ = this._cubejsSubject
        .asObservable()
        .pipe(shareReplay(1));

    constructor(
        private http: HttpClient,
        private authService: AuthService
    ) {

        this.authService.isAuthenticated
            .pipe(
                switchMap(a => {
                    if (a === true) {
                        return this.http.get<string>(API_URL + '/dashboard-token', { responseType: 'text' as 'json'})
                    } else {
                        return of('');
                    }
                })
            )
            .subscribe(token => {
                let client: CubejsClient = null;
                if (token.length > 0) {
                    client = new CubejsClient({
                        token: token,
                        options: {
                            apiUrl: "https://CUBEJSAPIURL.amazonaws.com/dev/cubejs-api/v1"
                        }
                    });
                }

                this._cubejsSubject.next(client);
            });
    }

}
```

**Comment by vasilev-alex** [comment]
@hobojoe thanks for the snippet! I think we can make use of https://angular.io/api/core/APP_INITIALIZER to make it easier for end-users
