### ISSUE TITLE
ReferenceError: SECURITY_CONTEXT is not defined

### ISSUE THREAD

**Issue by hobojoe** [cube-js/cube.js#1995]
**Problem**

I am trying to use the SECURITY_CONTEXT to enforce multi tenancy on my queries.

I created a token with the following payload:
```
{
  "userid": "95",
  "companyid": "12"
  "nbf": 1612463352,
  "exp": 1612549752,
  "iat": 1612463352,
  "iss": "issuer",
  "aud": "audience"
}
```

My schema has this query:

```
cube(`Ticket`, {
  sql: `SELECT * FROM \`MyDB\`.\`Ticket\` WHERE ${SECURITY_CONTEXT.companyid.filter(
    'CompanyId'
  )}`,
```

While trying to execute a query I get an error:
`{"error":"ReferenceError: SECURITY_CONTEXT is not defined"}`

Do I need to do any other config to enable security context?

Couldn't find anything on the docs.

Thanks

**Comment by keydunov** [comment]
Hi @hobojoe ,

Do you mind sharing the version of Cube.js you are running?

**Comment by hobojoe** [comment]
> Hi @hobojoe ,
> 
> Do you mind sharing the version of Cube.js you are running?

I'm on the latest:
"@cubejs-backend/server": "^0.25.30"

**Comment by keydunov** [comment]
@hobojoe Could you please update to `0.26.4`?

**Comment by hobojoe** [comment]
> @hobojoe Could you please update to `0.26.4`?

It worked! Thanks!
