### ISSUE TITLE
Speed up postgres pre aggregations

### ISSUE THREAD

**Issue by landyrev** [cube-js/cube.js#200]
I’m trying to use Postgres as external db for rollup pre aggregations in serverless mode, but facing following issue: creating of new pre-aggregations takes a lot of time — about one second per every 4-5 rows of pre aggregated data.

As I can see — it happens because cube uploads data to Postgres row-by-row, and it takes a lot of time. Is there any ways to speed up uploading?

**Comment by paveltiunov** [comment]
@landyrev Thanks for posting this! Yep. It's because default driver implementation doesn't have any  DB specific optimizations. Thanks for providing this implementation!
