### ISSUE TITLE
Dashboard App - Tailwind?

### ISSUE THREAD

**Issue by srhise** [cube-js/cube.js#2013]
I was reading on the docs here: https://cube.dev/docs/dashboard-app

It said to mention in an issue if someone wanted a different UI framework. Would tailwind be a valid option? I'm not too familiar with ANT. Maybe too low level for something like this. I would love to help if there is interest in bringing in something like TailwindCSS.

**Comment by vasilev-alex** [comment]
Hi @srhise! We're definitely open to new contributions. If you'd like to work on it just let us know
