### ISSUE TITLE
runningTotal on a count

### ISSUE THREAD

**Issue by gane5h** [cube-js/cube.js#202]
**Describe the bug**
Trying to create a `runningTotal` measure on a `count` measure leads to an error.

**To Reproduce**
Say I have a schema with the following measures:

```
  measures: {
    count_col: {
      type: `count`,
      drillMembers: [Created, walletAddress]
    },
    cumulative_count: {
      type: `runningTotal`,
      sql: `${count_col} `      
    }
  }
```

I'm getting a `Error: aggregate function calls cannot be nested` error on Postgres when I try to use `cumulative_count`. It works fine for the `count_col` measure.

**Expected behavior**
A running total on the `count_col` measure.

**Comment by paveltiunov** [comment]
@gane5h Hey Ganesh! Yep. It's correct behavior. What you want is
```
  cumulativeCount: {
      type: `count`,
      rollingWindow: {
        trailing: `unbounded`
      }
    }
```
It makes sense to add this example here: https://cube.dev/docs/measures#parameters-rolling-window. Would love to see PR for that.

**Comment by paveltiunov** [comment]
@gane5h Did you have a chance to check it?

**Comment by gane5h** [comment]
I'm not able to get this to work. Let me do some more debugging. 

Is there a dependency with `timeDimension`. I'm only using `dimension` and I can see that the join condition isn't quite right (for the `unbounded` case.)

**Comment by gane5h** [comment]
@paveltiunov My dimensions actually DO have the type `time` – it's just that I'm using `dimension` instead of `timeDimension` in order to make the query. This is when I'm not able to get `rollingWindow` working. 

In the context of this issue, I think it's helped resolve my issue (as in NOTABUG). Thanks

**Comment by paveltiunov** [comment]
@gane5h Ah. I see. Makes sense. Yeah. When you use `time` dimension as generic dimension without granularity `rollingWindow` won't be triggered.
