### ISSUE TITLE
Document outdated

### ISSUE THREAD

**Issue by wadeyw** [cube-js/cube.js#2028]
Hi Team, since you already migrated to 0.23.* you need to update the document
like for this page: https://cube.dev/docs/@cubejs-backend-server , how to expose a healthChecks endpoint using new cubejs docker image

**Comment by hassankhan** [comment]
Hi @wadeyw :wave:

We have two[1][2] health-check API endpoints built into Cube.js itself now, they should also work through the Docker image with no extra configuration required. Does that help?

[1]: https://cube.dev/docs/rest-api#api-reference-readyz
[2]: https://cube.dev/docs/rest-api#api-reference-livez

**Comment by wadeyw** [comment]
Thanks, it works well in new version, but think you still need to update existing doc since it misleading
