### ISSUE TITLE
QueryBuilderRenderProps documentation is missing some props or bug?

### ISSUE THREAD

**Issue by mbiczysko** [cube-js/cube.js#2043]
**Missing a documentation on QueryBuilderRenderProps**
When looking at QueryBuilder,jsx in `cubejs-client-react` we have exposed number of renderProps that are not documentation.

from code:

```
QueryBuilder.jsx
line: 210 (a shorter version below)
return {
    meta,
    query,
    validatedQuery,
    isQueryPresent,
    chartType,
    measures,
    dimensions,
    timeDimensions,
    segments,
    filters,
    orderMembers,
    availableMeasures,
    availableDimensions,
    availableTimeDimensions,
    availableSegments,
    updateQuery,
    updateMeasures,
    updateDimensions,
    updateSegments,
    updateTimeDimensions,
    updateFilters,
    updateChartType,
    updateOrder,
    pivotConfig,
    updatePivotConfig,
    ...queryRendererProps
  };
```
We are missing in docs for ex.

```
filters
updateFilters
orderMembers,
updateOrder,
pivotConfig,
updatePivotConfig,
validatedQuery,
chartType,
updateChartType
```

**Additional context**

Funny enough VSCODE complains there not being part of renderOptions so maybe it's a bug

[
<img width="942" alt="Screenshot 2021-02-10 at 12 38 06" src="https://user-images.githubusercontent.com/28129/107511217-1c135a80-6b9d-11eb-8d5e-737c8aceb38a.png">
](url)

**Comment by florian-fischer-swarm** [comment]
I get the same errors in Webstorm, but only when using QueryBuilder in a typescript context.
