### ISSUE TITLE
CubeCli : generate token with user payload

### ISSUE THREAD

**Issue by zegravity** [cube-js/cube.js#206]
**Describe the bug**
Hi,
When generating token with payload with cubejs cli like : 
`cubejs token -s XXXXXX -p USERID=510`
Then the payload in JWT Token is `{"SITEID":"510"}` instead of `"u": {"SITEID": 510}` in order to use SITEID as USER_CONTEXT in a Cube.

Is it a bug or normal behavior ?

Best regards

**Comment by paveltiunov** [comment]
Hey @zegravity ! This behavior is right but I agree there's no way to create token with set `u` property. It makes sense to add something like `-u` for user payload or `-j` just for json payload.
