### ISSUE TITLE
Dashboard App generation is broken

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#2074]
**Describe the bug**
When I try to create a new dashboard app in Developer Playground, it's not being generated, and an error message is shown.

**To Reproduce**
* Run Developer Playground
* Navigate to the "Dashboard App" tab
* Try to generate, for instance, "Dynamic Dashboard with React, AntD, and Recharts"

**Expected behavior**
The generation ends without errors, the new `dashboard-app` folder appears in Cube.js project folder.

**Screenshots**
<img width="1072" alt="Screenshot 2021-02-11 at 23 39 32" src="https://user-images.githubusercontent.com/3852894/107741638-68a48600-6cc2-11eb-9062-fef46445f0cc.png">

```
❯ npm run dev

> clickhouse-dashboard@0.0.1 dev
> ./node_modules/.bin/cubejs-server

🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000
🚀 Cube.js server (0.26.12) is listening on 4000
(node:22364) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22364) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

up to date, audited 213 packages in 759ms

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

You are running `create-react-app` 4.0.1, which is behind the latest release (4.0.2).

We no longer support global installation of Create React App.

Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app

The latest instructions for creating a new app can be found here:
https://create-react-app.dev/docs/getting-started/

npm ERR! code 1
npm ERR! path /Users/igorlukanin/Documents/cube.js/examples/clickhouse-dashboard
npm ERR! command failed
npm ERR! command sh -c create-react-app "dashboard-app" "--use-npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/igorlukanin/.npm/_logs/2021-02-12T07_41_14_118Z-debug.log
err Error: npx create-react-app dashboard-app --use-npm failed with exit code 1. Please check your console.
    at ChildProcess.<anonymous> (/Users/igorlukanin/Documents/cube.js/examples/clickhouse-dashboard/node_modules/@cubejs-backend/server-core/src/dev/utils.js:53:16)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error: npx create-react-app dashboard-app --use-npm failed with exit code 1. Please check your console.
    at ChildProcess.<anonymous> (/Users/igorlukanin/Documents/cube.js/examples/clickhouse-dashboard/node_modules/@cubejs-backend/server-core/src/dev/utils.js:53:16)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Version:**
```
❯ cat package.json
{
  "name": "clickhouse-dashboard",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "./node_modules/.bin/cubejs-server"
  },
  "template": "docker",
  "templateVersion": "0.25.2",
  "devDependencies": {
    "@cubejs-backend/clickhouse-driver": "^0.26.12",
    "@cubejs-backend/server": "^0.26.12"
  }
}
```

**Comment by vasilev-alex** [comment]
@igorlukanin thanks for the details!

Looks like it's a problem with `create-react-app` installed globally

What I can see from your logs it suggests that you uninstall the global package.

```
We no longer support global installation of Create React App.

Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app
```
 
Related discussion https://github.com/facebook/create-react-app/issues/10132

As some users have already faced similar issue I'll think about what we can do to display a proper warning in advance.

**Comment by CataMates** [comment]
Hi,
I'm having the same issue when trying to generate the Dynamic Angular Material UI Dashboard template.
`Error: Can't parse /src/app/explore/add-to-dashboard-dialog/add-to-dashboard-dialog.component.ts: Decorators cannot be used to decorate parameters (17:4)
    at new TargetSource (/Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/src/TargetSource.js:34:15)
    at NgMaterialDynamicTemplate.createTargetSource (/Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/src/TemplatePackage.js:123:14)
    at /Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/src/TemplatePackage.js:89:35
    at Array.forEach (<anonymous>)
    at /Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/src/TemplatePackage.js:78:71
    at Array.forEach (<anonymous>)
    at NgMaterialDynamicTemplate.mergeSources (/Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/src/TemplatePackage.js:64:8)
    at NgMaterialDynamicTemplate.applyPackage (/Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/node_modules/@cubejs-templates/core/src/TemplatePackage.js:151:12)
    at CreateNgAppTemplate.applyChildren (/Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/packages/templates-core/src/TemplatePackage.js:167:9)
    at CreateNgAppTemplate.applyPackage (/Users/catalinmates/Documents/angular-workspace/2cubejs/node_modules/.tmp/cubejs-playground-templates-master/packages/templates-core/src/TemplatePackage.js:161:5)`

**Comment by m987987** [comment]
I just had this problem as well and I saw this flashing by in the console:

```
 Need to install the following packages:
   create-react-app
 Ok to proceed? (y) 
```

The app continued to spit out lines in the console so I didn't bother, but when I failed to start the dashboard-app, I tried being quick and pressing enter in the console and everything got installed properly..

**Comment by vasilev-alex** [comment]
@CataMates could you please check again? It should be fixed now.

**Comment by CataMates** [comment]
@vasilev-alex It works like a charm now.
Thanks for the quick fix!

**Comment by vasilev-alex** [comment]
@igorlukanin I've made some changes and from now on we'll try using global `create-react-app` on fail

**Comment by cadrogui** [comment]
HI, i've issues on create dashboards from docker image, here is some info about my problems.

![image](https://user-images.githubusercontent.com/5303414/109674630-d6233400-7b55-11eb-8dcf-01380b9040b0.png)

`cube_1  | Error: Cannot find module '/root/.npm/_npx/171/lib/node_modules/@angular/cli/bin/postinstall/script.js'
cube_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
cube_1  |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
cube_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
cube_1  |     at internal/main/run_main_module.js:17:47 {
cube_1  |   code: 'MODULE_NOT_FOUND',
cube_1  |   requireStack: []
cube_1  | }
cube_1  | npm ERR! code ELIFECYCLE
cube_1  | npm ERR! errno 1
cube_1  | npm ERR! @angular/cli@11.2.2 postinstall: `node ./bin/postinstall/script.js`
cube_1  | npm ERR! Exit status 1
cube_1  | npm ERR!
cube_1  | npm ERR! Failed at the @angular/cli@11.2.2 postinstall script.
cube_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
cube_1  |
cube_1  | npm ERR! A complete log of this run can be found in:
cube_1  | npm ERR!     /root/.npm/_logs/2021-03-02T15_39_59_281Z-debug.log
cube_1  | Install for [ '@angular/cli@latest' ] failed with code 1
cube_1  | err Error: npx @angular/cli new dashboard-app --routing=false --style=css --minimal=true --packageManager=npm --strict=false failed with exit code 1. Please check your console.
cube_1  |     at ChildProcess.<anonymous> (/cube/node_modules/@cubejs-backend/server-core/src/dev/utils.js:53:16)
cube_1  |     at ChildProcess.emit (events.js:314:20)
cube_1  |     at maybeClose (internal/child_process.js:1022:16)
cube_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
cube_1  | Error: npx @angular/cli new dashboard-app --routing=false --style=css --minimal=true --packageManager=npm --strict=false failed with exit code 1. Please check your console.
cube_1  |     at ChildProcess.<anonymous> (/cube/node_modules/@cubejs-backend/server-core/src/dev/utils.js:53:16)
cube_1  |     at ChildProcess.emit (events.js:314:20)
cube_1  |     at maybeClose (internal/child_process.js:1022:16)
cube_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)`

thaks for your work 
regards.

**Comment by vasilev-alex** [comment]
@cadrogui thanks for the report! We'll check it

**Comment by vasilev-alex** [comment]
@cadrogui will be fixed in the next release

**Comment by atakangameguru** [comment]
Hi I have encountering same issue that @cadrogui has. I am using latest docker image of cubejs
![image](https://user-images.githubusercontent.com/110380663/189088438-a3d6e33a-4299-45d8-8f9f-29cd769dcb3c.png)
![image](https://user-images.githubusercontent.com/110380663/189088591-e4b5126c-df6c-4d0c-8972-1994cdd374ea.png)

**Comment by enstit** [comment]
Same problem here, using the latest docker image of CubeJS on Debian GNU/LINUX 11 (bullseye).

The error:
![Capture2](https://user-images.githubusercontent.com/67797287/211833596-9893316b-6f9c-44ea-a7c3-1cc7f5a3f7a2.JPG)

The logs:
![Capture](https://user-images.githubusercontent.com/67797287/211833015-127ff744-c558-4a21-8eb3-c94c83df2f86.JPG)
