### ISSUE TITLE
How to Generate the token for Cube.js authentication using spring boot

### ISSUE THREAD

**Issue by ImalshaRathnaweera** [cube-js/cube.js#2098]
I used the below code to generate the Jwt token in spring boot.

```
String token = Jwts.builder().signWith(SignatureAlgorithm.HS256, Constants.API_SECRET_KEY)
                .setIssuedAt(new Date(timestamp))
                .setExpiration(new Date(timestamp + Constants.TOKEN_VALIDITY))
                .claim("user_id", user.getUserId())
                .compact();
```
A token was created, but not retrieve the correct data related to the cubejs scheme. how to make a Jwt token using spring boot for the cubejs authentication.

I generate a Jwt token using node backend.. then, it works for cubejs.
```
app.get('/auth/cubejs-token', (req, res) => {
    const CUBEJS_API_SECRET = "secret";
    const cubejsToken = jwt.sign({ user_id: 20 }, CUBEJS_API_SECRET, {
        expiresIn: '30d',
    });
    res.json({
        // Take note: cubejs expects the JWT payload to contain an object!
        token: cubejsToken
    });
});
```

I check node token and spring boot token using jwt.io. both results are equal. when applying the node token retrieve the correct data. but when applying spring boot token not retrieve the correct data.

**Comment by vasilev-alex** [comment]
Hello @ImalshaRathnaweera! I can see that the payload you pass in is different.

Java version
```
userId
```

Node.js version
```
{ u: { user_id: 20 } }
```

May it be the issue?

**Comment by ImalshaRathnaweera** [comment]
@vasilev-alex I have fixed this issue

**Comment by vasilev-alex** [comment]
So, just to confirm, you don't receive the `unauthenticated` or any other error from the server? 

If so, could you please share the related data schemas?

**Comment by ImalshaRathnaweera** [comment]
```
cube(`Accounts`, {
  sql: `SELECT * FROM bank_schema.accounts WHERE ${SECURITY_CONTEXT.user_id.filter('user_id')}`,
  
  joins: {
    Branch: {
      sql: `${CUBE}.branch_id = ${Branch}.branch_id`,
      relationship: `belongsTo`
    },
    
    Customers: {
      sql: `${CUBE}.customer_id = ${Customers}.customer_id`,
      relationship: `belongsTo`
    },
    
    Sectors: {
      sql: `${CUBE}.sector_id = ${Sectors}.sector_id`,
      relationship: `belongsTo`
    }
  },
  
  measures: {
    count: {
      type: `count`,
      drillMembers: []
    },
  },
  
  dimensions: {
    accountBalance: {
      sql: `account_balance`,
      type: `string`
    },
    
    accountType: {
      sql: `account_type`,
      type: `string`
    },
    
    accountNumber:{
      sql: `account_no`,
      type: `number`,
      primaryKey: true
    }
    
  
  }
});
```

**Comment by ImalshaRathnaweera** [comment]
I integrated the spring boot backend with nuxt js front end. then, become ``` isAuthenticate: false```. but login becomes successful and token stored in the localstorage.

**Comment by vasilev-alex** [comment]
@ImalshaRathnaweera how do you query the Cube.js API?

**Comment by ImalshaRathnaweera** [comment]
const cubejsApi = cubejs(token, {
  apiUrl: `http://localhost:4000/cubejs-api/v1`,
})

**Comment by vasilev-alex** [comment]
@ImalshaRathnaweera Could you please generate 2 fresh tokens and share them here? One using Java and another using Node.js

**Comment by ImalshaRathnaweera** [comment]
Node token
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozMSwiaWF0IjoxNjEzNDcwOTE2LCJleHAiOjE2MTYwNjI5MTZ9.nYF6QOfjTfb07tav1wQdwbPJvujW88TkxkK9Tmnxj2k

Spring boot token
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTM0NzEwMjksImV4cCI6MTYxMzQ3ODIyOSwidXNlcl9pZCI6MzF9.dWHHe22mjSKxB4mH7mh84RQSnrb9cSEsEXCRkvNt0d4
