### ISSUE TITLE
feat: Support external rollups from readonly source for MySQL

### ISSUE THREAD

**Issue by shahrin014** [cube-js/cube.js#2105]
Similar to 
https://github.com/cube-js/cube.js/pull/395

Support read only for MySQL external rollups.

Somehow it still seems to trigger CREATE TABLE dev_pre_aggregations in the readonly database

**Comment by shahrin014** [comment]
I can work on this but I need guidance.

**Suspected problem:**
at https://github.com/cube-js/cube.js/blob/master/packages/cubejs-mysql-driver/driver/MySqlDriver.js#L164
`
      // I suspect the issue is here. If I access the database with a read only user, this query will always fail.
      await db.execute(`CREATE TEMPORARY TABLE \`${this.config.database}\`.t_${tableName} AS ${query} LIMIT 0`, values);
      const result = await db.execute(`DESCRIBE \`${this.config.database}\`.t_${tableName}`);
      await db.execute(`DROP TEMPORARY TABLE \`${this.config.database}\`.t_${tableName}`);
`
**Proposed approach:**
Extract data types from table information_schema.columns. 

However, to do this I will need to get the tables and the columns. Apart from extracting it from the query string itself, do you have a better solution?

**Comment by jcw-** [comment]
Hi @shahrin014, I encountered something similar with the postgres driver and worked with Cube.js to add this support: https://github.com/cube-js/cube.js/pull/395

It's an older PR, so check the current codebase for the latest version of it, but I believe you could follow the same strategy with the mysql driver - let me know what you think!

**Comment by JoshMentzer** [comment]
@shahrin014 - another PR doing the same is https://github.com/cube-js/cube.js/pull/920

**Comment by paveltiunov** [comment]
Implemented in #2960
