### ISSUE TITLE
 need to integrate export to excel utility in the rendered table

### ISSUE THREAD

**Issue by I-akshay** [cube-js/cube.js#2107]
Hi Team ,

I need to integrate export to excel utility in the rendered table, is there any way to achieve this. My data source is click house
Thanks

**Comment by vasilev-alex** [comment]
hi @I-akshay! Cube.js doesn't provide special helpers for that but it neither limits you in choosing the appropriate tools. 

This package may be helpful for you https://github.com/rdcalle/react-export-excel#readme

**Comment by I-akshay** [comment]
> hi @I-akshay! Cube.js doesn't provide special helpers for that but it neither limits you in choosing the appropriate tools.
> 
> This package may be helpful for you https://github.com/rdcalle/react-export-excel#readme



> hi @I-akshay! Cube.js doesn't provide special helpers for that but it neither limits you in choosing the appropriate tools.
> 
> This package may be helpful for you https://github.com/rdcalle/react-export-excel#readme

Thanks @vasilev-alex for your response , Just one help can we integrate this in cube.js , if yes can you please let me know how to do the same

**Comment by vasilev-alex** [comment]
@I-akshay unfortunately, we don't have a guide on that. I can suggest creating a dashboard app (you can do that in the Playground) and check out the `react-export-excel` docs to see how you can achieve that.
