### ISSUE TITLE
Cube organization with joins

### ISSUE THREAD

**Issue by gane5h** [cube-js/cube.js#212]
I have `measures` that come from a bunch of joins, eg:

```
select dim1, dim2,
measure2,
measure 3
from ...

left join
( complex sql statement ) as measure2
on join condition

left join
( complex sql statement ) as measure3
on join condition
```

But the cube is executed regardless of whether I'm using `measure2` and `measure3` which are quiet expensive.

Is there an organization scheme I can use with `joins` so that I don't always have to join the tables?

**Comment by paveltiunov** [comment]
@gane5h Hey Ganesh! It's a great question! Yep. It's as simple as defining separate cubes for `measure2` and `measure3` and joining them to the`Cube1`. You can query then across joins like:
```
{
  "measures": ["Cube2.measure2", "Cube3.measure3"],
  "dimensions": ["Cube1.dim1"]
}
```
This way you don't need to define joins in `sql` of a `Cube1`. They'll be generated automatically when `Cube2.measure2` and `Cube3.measure3` are requested.

**Comment by gane5h** [comment]
@paveltiunov Awesome! 

Follow up question. I need this to be a `LEFT JOIN` because there might not always be a row match the join clause, and I need to return a `NULL` value (that I'll then `COALESCE` to a zero.) 

How can I achieve this?

**Comment by paveltiunov** [comment]
@gane5h All joins generated as `LEFT JOIN` actually: https://cube.dev/docs/joins

**Comment by gane5h** [comment]
Amazing. Thank you!
