### ISSUE TITLE
Pre-aggregation not selected for field of joined cube added in dimensionReferences.

### ISSUE THREAD

**Issue by NalinSajwan** [cube-js/cube.js#2131]
**Describe the bug**
Cube.js is not picking desired `pre-aggregation` for field of joined table even when aggregation table got created successfully on `Athena`.

**To Reproduce**

Cubes zip - [cubes.zip](https://github.com/cube-js/cube.js/files/5998374/cubes.zip)

1. Create 2 cubes `Orders` and `OrderPayments` (both files added in zip file above).
2. Join them both by relation `hasMany` and `belongsTo`in `Order` and `OrderPayments` respectively (already coded in sample cube) - 
   ```
   joins: {
      OrderPayments: {
         relationship: 'hasMany',
         sql: `${Orders}.payments = ${OrderPayments}.id`,
      },
   }
   ```
3. Apply following `preAggregations` -
   ```
   totalPriceByPaymentTypeName: {
      type: 'rollup',
      measureReferences: [ totalPrice ],
      dimensionReferences: [ OrderPayments.paymentTypeName ],
      timeDimensionReference: createdAt,
      granularity: 'day',
      refreshKey: {
         every: '1 hour',
      },
      scheduledRefresh: true
   }
   ```
4. Hit this query on postman or cube.js front end -
   ```
   {"measures":["Orders.totalPrice"],"timeDimensions":[{"dimension":"Orders.createdAt","dateRange":"today"}],"dimensions":["OrderPayments.paymentTypeName"]}
   ```
5. Error -
Desired pre-aggregation not selected (see image below)
![image](https://user-images.githubusercontent.com/10107926/108261789-17950600-718a-11eb-9525-ea470345bf41.png)

**Expected behavior**
Cube.js should have used the pre-aggregated table on hitting query, but it created entirely new query.

**Screenshots**
Query being called - 
![image](https://user-images.githubusercontent.com/10107926/108262120-81adab00-718a-11eb-9e34-52e0fe3ad7c9.png)
Pre-aggregation not selected -
![image](https://user-images.githubusercontent.com/10107926/108262181-968a3e80-718a-11eb-9b03-87122389d2d6.png)

**Version:**
```
"@cubejs-backend/athena-driver": "0.26.12",
"@cubejs-backend/server": "0.26.4"
```

**Additional context**
Table for `pre-aggregation` is getting generated with correct data but cube.js while running query is not selecting the table for field of joined table.

Cube.js is picking rollups correctly if I use field which was part of original cube (not a field from joined table)

**Comment by paveltiunov** [comment]
Hey @NalinSajwan ! This is tricky but correct. Rule 2 of https://cube.dev/docs/pre-aggregations#rollup-rollup-selection-rules says measures shouldn't be multiplied but those are multiplied by `OrderPayments` has many relation.

**Comment by paveltiunov** [comment]
@NalinSajwan Was it helpful? Please feel free to reopen if it's still an issue.
