### ISSUE TITLE
Incorrect date ranges when using text date strings

### ISSUE THREAD

**Issue by JoshMentzer** [cube-js/cube.js#2141]
https://github.com/cube-js/cube.js/blob/e7349f7bd71800e51a9c1d7cefecc8783bd886d6/packages/cubejs-api-gateway/src/dateParser.js#L39

If you were to submit a query with 'last 6 months' as the date search value, you get 8/1/2020 -> 1/28/2021; cutting off the last few days of January.
Should the above line swap the endOf and add functions?  I believe what is happening is it's doing 'endOf' Feb, so setting to 2/28 - then doing 1 minus month; so 1/28.  Essentially if the current month has less days than the prior, it will always cut off the difference.

**Comment by ovr** [comment]
Hello @JoshMentzer ,

Thank you for submitting an issue. So, on first look it looks like a bug, I will do a small research and talk with our team to understand how it should work.

Thanks
