### ISSUE TITLE
CubeJS Dashboard does not generate schema definitions properly for tables names contain special characters or starting with non-letter characters

### ISSUE THREAD

**Issue by s4ke** [cube-js/cube.js#215]
**Describe the bug**
The cubejs dashboard at localhost:4000 does not generate the proper schema definitions for tables that start with "_<number>", e.g. "_3_table".

also see: https://cube-js.slack.com/archives/CC0403RRR/p1569251834086700

Possible workaround:

Run the following in bash:
```
rename  's/3(.*)/$1/' *
sed -i 's/3//' *
sed -i 's/public.__/public._3_/' *
```

**Comment by s4ke** [comment]
I dont know if this should be a separate issue, but the generator also does not support column names with special characters in it. In our use case these are a result of uuids being used in pivot tables. It would be nice if cubejs would support this. However, it seems to be a bigger issue as quoting them in the generated js file does not solve the issue.

**Comment by paveltiunov** [comment]
@s4ke Hey Martin! Thanks for posting this! Yeah. Let's track all of this stuff in same issue.

**Comment by paveltiunov** [comment]
Should be already fixed.
