### ISSUE TITLE
node_redis: Using .end() without the flush parameter is deprecated and throws from v.3.0.0 on

### ISSUE THREAD

**Issue by wadeyw** [cube-js/cube.js#2187]
**Describe the bug**
As indicate below, after migrate to 0.23, when docker-compose up, it throw below info
cube_1  | node_redis: Using .end() without the flush parameter is deprecated and throws from v.3.0.0 on.
cube_1  | Please check the doku (https://github.com/NodeRedis/node_redis) and explictly use flush.

**To Reproduce**
docker-compose.yml
`version: "3"

services:
  cube:
    image: cubejs/cube:latest
    # env_file: ./.cubejs.env
    ports:
      # 4000 is a port for Cube.js API
      - 4000:4000
`

DockerFile
`FROM cubejs/cube:latest

COPY . .
RUN npm install`

package.json
`{
  "name": "cubejs-app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "./node_modules/.bin/cubejs-server server"
  },
  "dependencies": {
    "@cubejs-backend/postgres-driver": "^0.23.6",
    "@cubejs-backend/server": "^0.23.7"
  }
}
`

**Screenshots**
![image](https://user-images.githubusercontent.com/20250120/108653957-b3b06b80-7502-11eb-8155-753009d285fa.png)

**Version:**
[0.23]

**Comment by paveltiunov** [comment]
Hey @wadeyw ! Could you please try to upgrade to the latest version? Should be fixed.

**Comment by wadeyw** [comment]
Which version do you mean?

Package.json
`{
  "name": "cubejs-app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "./node_modules/.bin/cubejs-server server"
  },
  "dependencies": {
    "jwk-to-pem": "^2.0.4"
  },
  "devDependencies": {
    "@cubejs-backend/postgres-driver": "^0.26.25",
    "@cubejs-backend/server": "^0.26.25"
  }
}
`

**Comment by ovr** [comment]
> Which version do you mean?

Cube.js.

> Also seems the dependency also have some issues during npm install

It's just warnings, not errors.

**Comment by rpaik** [comment]
@wadeyw, not sure if you were able to upgrade to the latest version. Are you still having issues?
