### ISSUE TITLE
Hide measures/dimensions

### ISSUE THREAD

**Issue by richipargo** [cube-js/cube.js#219]
**Is your feature request related to a problem?**
When using meta endpoint from API, fields with `shown: false` are not included in request since they're intended for internal use on `@cubejs-server/core` but if you want to calculate paths for joins on `@cubejs-client/core` they're required to manage queries.

**Describe the solution you'd like**
A possible new property to the schema so that when the `@cubejs-client/core` parses the result from meta it can calculate the paths but hide from the available measures/dimensions

**Additional context**
It's a enhancement which might not be used in some cases but if you want to build UI using API mode this gives a bit more flexibility and control with paths

**Comment by paveltiunov** [comment]
@richipargo Hey Ricardo! Thanks for posting this! I believe this issue is much more deep: there's no way to control how cubes would be joined in terms of order as of right now. As we see from our experience in 95% of cases this can be solved with adjusting schema and queries and 5% of cases really require such control. 

Could you please elaborate on your use case a little bit more? Queries and Cube join structure would help a lot.

**Comment by richipargo** [comment]
Hey @paveltiunov, since this is not so much a query issue as it is a UI issue. Let me explain with a full example.

So i have a dynamically generated dashboard in which users are able to build their own charts and views using the `QueryBuilder` and `QueryRenderer` components I built for Vue.js. It is very  similar to the playground but customized. So in order to create the controls to manage the queries and joins i use the `/cubejs-api/v1/meta` which fed directly to `QueryBuilder` which works very well, but when there are some fields that I don't want to show in `Measures/Dimensions` because they're only used for joins internally `id`s and such; When using `shown: false` property the joins on `@cubejs-server` work perfect.

Now the issue is that some fields might be used on the background of the UI as context or other in which these queries have a preset filter fed by the UI, but when i load back the query from the saved query the paths of some filters are not loaded since they're hidden from meta request

**Comment by paveltiunov** [comment]
@richipargo I see. Could you please provide some example queries: what queried at first time, what's saved and what's restored and doesn't work?
