### ISSUE TITLE
Setup Cubejs in ECS

### ISSUE THREAD

**Issue by wadeyw** [cube-js/cube.js#2193]
**Problem**
I'm running an issue while passing environment variables when trying to deploy cubejs container to ECS

Three things I need to setup below without using .env file, since I'm running in ECS Fargate. 
1.How to setup postgresql database connection(How to read environment DB variables)
2.How to read environment variable CUBEJS_API_SECRET
3.How to read environment variable REDIS_URL

This is my version
`{
  "name": "cubejs-app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "./node_modules/.bin/cubejs-server server"
  },
  "dependencies": {
    "jwk-to-pem": "^2.0.4"
  },
  "devDependencies": {
    "@cubejs-backend/postgres-driver": "^0.26.25",
    "@cubejs-backend/server": "^0.26.25"
  }
}
`

Dockerfile
`FROM cubejs/cube:latest

COPY . .
RUN npm install`

docker-compose file
`version: "3"

services:
  cubejs:
    build: .
    ports:
      - 4000:4000
`

**Comment by paveltiunov** [comment]
Hey @wadeyw ! This question seems to be ECS specific rather than Cube.js related. I believe there's a great starting point for it: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html.
