### ISSUE TITLE
Granularity = week in timeDimension consider week as Monday to Sunday, how to change it?

### ISSUE THREAD

**Issue by PriyaGrover** [cube-js/cube.js#2195]
**Problem**

After adding granularity, I am getting weekly data. However, cube/postgres consider week as Monday to Sunday. If user queries on any other day of week, for example on Wednesday 17th Feb then I want to calculate week as (11th Feb - 17th Feb). At present, I am getting data for 8th to 14th Feb and 15th to 21st Feb. How can we achieve that in cube query?

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `` //, ...
})
```

**Related Cube.js generated SQL**

{

"measures": [
"TotalCaseValueVolume.totalCaseValue",
"TotalCaseValueVolume.totalCaseVolume"
],
"timeDimensions": [
{
"dimension": "TotalCaseValueVolume.createdAt",
"granularity": “week”,
"dateRange":  "from 29 days ago to now"
}
],
"order": {}
}

**Comment by paveltiunov** [comment]
Hey @PriyaGrover ! There's already an issue for it #177.
