### ISSUE TITLE
Feature request: A way to set CUBEJS_CACHE_AND_QUEUE_DRIVER parameter from the cube.js file / config

### ISSUE THREAD

**Issue by zameschua** [cube-js/cube.js#2204]
As per the title

I wanted to use cubejs backend-server with an existing expressjs deployment, so I'm trying to avoid adding too many environment variables because they can be hard to keep track of (there are already many environment variables in the existing project) and I just thought it'd be a natural progression since most of the env configs can already be set from code :)

**Comment by paveltiunov** [comment]
Hey @zameschua ! Thanks for posting it! Definitely makes sense to have it.

**Comment by acham1** [comment]
I am interested in working on this issue, thanks!

**Comment by rpaik** [comment]
Thanks @acham1 🚀  You don't have a PR associated with this yet correct? 

Let me go ahead and assign the issue to you.

**Comment by rpaik** [comment]
@acham1, just following up. Are you still interested in working on this?

**Comment by acham1** [comment]
Yes, so sorry! I'll pick it up during the coming long weekend.

**Comment by hassankhan** [comment]
Resolved by https://github.com/cube-js/cube.js/pull/2859
