### ISSUE TITLE
Prefer extended join path over transitive join when both exist to cube

### ISSUE THREAD

**Issue by SteffeyDev** [cube-js/cube.js#2241]
**Is your feature request related to a problem? Please describe.**

Let's say I have cubes A, B, C, E, X and have set up my joins so that A `belongsTo` B and B `belongsTo` C. A extends E. Both E and C `belongsTo` X.  When I want to filter on a property on X, the query orchestration ends up using the relations between C and X, instead of between E and X.  So in the generated SQL, A joins B, B joins C, and C joins X.  Because A extends E, I would expect the orchestration to use the simpler path, of joining A directly to X.  As you can probably see, in my setup X is a very generic object that can contain objects of many different types, including types that are in a hierarchy with one another.

**Describe the solution you'd like**

I would either like it to prefer extended joins over transitive joins in path resolution, or to give the option which join to use.  For example, if B also `belongsTo` X, it would be nice to have the option to pick between A's X, B's X, and C's X, as all three produce different results.

**Describe alternatives you've considered**

Right now, I can simply add the A -> X join in A directly, instead of having it in E, but this becomes redundant because I have many other cubes that extend E, and so the join to X has to exist in each where this situation exists (which is almost all of them).  Obviously, this defeats the purpose of extending a cube in the first place.

**Comment by paveltiunov** [comment]
Hey @SteffeyDev ! Could you please post it to #438 to have this discussion in a single place? Thanks!

**Comment by SteffeyDev** [comment]
Sorry, didn't see that one
