### ISSUE TITLE
continueWaitTimeout is ignored (redis)

### ISSUE THREAD

**Issue by vieira** [cube-js/cube.js#225]
**Describe the bug**
Even though I defined `continueWaitTimeout` to be `120` the "Continue wait" response is sent after ~5s (the default).

**To Reproduce**
1. Initialize CubejsServerCore defining the `continueWaitTimeout` to some value different than the default (5).
```js
CubejsServerCore.create({
  ...
  orchestratorOptions: {
    queryCacheOptions: {
      queueOptions: {
        continueWaitTimeout: 120,
      },
    },
    preAggregationsOptions: {
      queueOptions: {
        continueWaitTimeout: 120,
      },
  },
});
```
2. Make a REST API call resulting in a query that takes more than `5s` to run.
3. Notice a `Continue wait` response after `5s`. (Also visible in the logs, screenshot below).

**Expected behavior**
I expected to receive a `Continue Wait` response only after the configured `continueWaitTimeout`.

**Screenshots**
<img width="475" alt="Screen Shot 2019-10-04 at 00 47 20" src="https://user-images.githubusercontent.com/207460/66171876-a6f75300-e641-11e9-81af-23b45a025ec2.png">

**Version:**
@cubejs-backend/server-core: 0.10.46

**Notes:**
This might be related to #224 but is also happening in production where redis is being used, so I am not sure.

**Comment by paveltiunov** [comment]
@vieira I see. Seems like you expect to override api-gateway continue wait timeout which is not overridable right now:
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-server-core/core/OrchestratorApi.js#L24
