### ISSUE TITLE
Fatal Crash Caused by Incorrect `antlr4ts` Dependency Resolution 

### ISSUE THREAD

**Issue by joealden** [cube-js/cube.js#2264]
**Describe the bug**
Since [`@cubejs-backend/server@0.26.13`](https://github.com/cube-js/cube.js/releases/tag/v0.26.13), the cube server fatally crashes when installed via yarn 2 with the following error:

```
/node_modules/antlr4ts/dist/tree/xpath/XPathLexer.js:9
class XPathLexer extends __2.Lexer {
                             ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/app/node_modules/antlr4ts/dist/tree/xpath/XPathLexer.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/node_modules/antlr4ts/dist/tree/xpath/XPath.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

As shown in the stack trace, the error is coming from `antlr4ts`, which from some investigation, is a dependency recently introduced into `@cubejs-backend/schema-compiler` via #1817. As shown in [`cubejs-schema-compiler/package.json`](https://github.com/cube-js/cube.js/blob/c741d946973f85aeccef44adcc888564ad14b3ac/packages/cubejs-schema-compiler/package.json#L46), this dependency is currently listed in as being required as `^0.5.0-alpha.4`.

From looking at my local lock file (`yarn.lock`), I can see that the actual resolution of this package isn't to `0.5.0-alpha.4`, but instead `0.5.0-dev`:

```
"antlr4ts@npm:^0.5.0-alpha.4":
  version: 0.5.0-dev
  resolution: "antlr4ts@npm:0.5.0-dev"
  dependencies:
    source-map-support: ^0.5.16
  checksum: 0f206ef5ef5793456de66545a1bf6d8d52343bc6c6689d941cc16ea3f0b6b18a7710b4cc3946a61d021fda51f93b89adcd7c5d7fe249ea1739b0459e7a85b42c
  languageName: node
  linkType: hard
```

From looking at https://www.npmjs.com/package/antlr4ts/v/0.5.0-dev, this version was published on 2020-04-15, and from looking at https://www.npmjs.com/package/antlr4ts/v/0.5.0-alpha.4, this version was published on 2021-01-01. From this info, this shows that the `0.5.0-dev` version yarn is resolving to is actually older than `0.5.0-alpha.4`. By entering parts of the error shown above into the Github issue search for `antlr4ts`, I found https://github.com/tunnelvisionlabs/antlr4ts/issues/461, which was created and closed (so was presumably resolved) after `0.5.0-dev` was published.

To verify that `0.5.0-alpha.4` does indeed not result in the same error message shown above, I ran the following command and the cube server booted up successfully (see https://yarnpkg.com/cli/set/resolution):

```
yarn set resolution --save antlr4ts@npm:^0.5.0-alpha.4 0.5.0-alpha.4
```

After reading through the semver spec (https://semver.org/#spec-item-11), it looks like the resolution behaviour yarn 2 is doing is correct, so the problem is actually with the versioning of the `antlr4ts` package. To resolve this, I propose removing the `^` range specifier from the relevant `package.json` to ensure that everyone fetches `antlr4ts@0.5.0-alpha.4` correctly (which would probably be wise anyway as `0.5.0-alpha.5` may not be compatible with `0.5.0-alpha.4`).

So in summary, this means that anyone using yarn 2 to install their dependencies will experience a fatal crash if they depend on `@cubejs-backend/schema-compiler@0.26.13` or later until this problem is resolved.

Note that I haven't tested installation via yarn 1/npm/pnpm, so this could also be a problem for other package managers (and it should be if they are following the semver spec strictly).

**To Reproduce**
1. Setup a basic cube backend server using yarn 2 to install dependencies.
2. Try running the cube server.
4. See the fatal startup error mentioned above.

**Expected behavior**
Yarn resolves the internal `antlr4ts` dependency to a version that doesn't suffer from the mentioned problem.

**Version:**
- [`@cubejs-backend/server@0.26.44`](https://github.com/cube-js/cube.js/releases/tag/v0.26.44)
- `yarn@2.4.0`

**Comment by ovr** [comment]
Hello @joealden,

Thank you for submitting an issue with a detailed explanation, great work 👍 

I've prepared a PR with locking the version for `antlr4ts`.
