### ISSUE TITLE
Add Query parameters to HTTP requests in @cubejs-client/core

### ISSUE THREAD

**Issue by Lozzi** [cube-js/cube.js#2286]
We're trying to pass additional information to cube and we were wondering if it'd be possible to do that through query params.

A solution to it would be to add `queryParams` as a property to LoadOptions.

```ts
export type LoadMethodOptions = {
    /**
     * Key to store the current request's MUTEX inside the `mutexObj`. MUTEX object is used to reject orphaned queries results when new queries are sent. For example: if two queries are sent with the same `mutexKey` only the last one will return results.
     */
    mutexKey?: string;
    /**
     * Object to store MUTEX
     */
    mutexObj?: Object;
    /**
     * Pass `true` to use continuous fetch behavior.
     */
    subscribe?: boolean;
    /**
     * Function that receives `ProgressResult` on each `Continue wait` message.
     */
    progressCallback?(result: ProgressResult): void;
    /**
    * A queryParam object where the key is a string and the value is a string, which will be passed as queryParams to the 
    *  `loadMethod` a long with `query` and `queryType` params.
    */
    queryParams: {[key: string]: string};
  };
```

Then in the load function these queryParams could be added to when calling the loadMethod.

```ts
load(query, options, callback) {
    return this.loadMethod(
      () => this.request('load', {
        ...options.queryParams,
        query,
        queryType: 'multi'
      }),
      (response) => new ResultSet(response, { parseDateMeasures: this.parseDateMeasures }),
      options,
      callback
    );
  }
```

**Comment by vasilev-alex** [comment]
hey @Lozzi! Could you please tell us more about your use case? What kind of params are you planning to send and how're you going to use them later on?

**Comment by Lozzi** [comment]
@vasilev-alex sure thing! I was thinking about sending params that could be used within a cube schema.


We have to do a few joins and it would really help out to be able to push the filters further down into the nested query.
If we do it by using the filter array in the query with [filterParmas](https://cube.dev/docs/cube#context-variables-filter-params) then they're also applied in the outer final `select` statement which doesn't work since that field is not apart of the final schema.

We wanted to push those filters further down so that we could avoid a full table scan since we know beforehand what keys we want to get data from.

We then wanted to parse the query params in the HTTP request and add them to the context so we could use them in the nested query.

**Comment by thorey-as** [comment]
To elaborate further, the use case itself is about filtering customers who haven't bought some products but have bought other products. A fairly simple way to do this when there is a table containing records of customer transactions would be:

`SELECT DISTINCT customer
FROM transactions
WHERE
   purchased_product in ('A', 'B')
AND
   customer NOT IN (
      SELECT DISTINCT customer
      FROM transactions
      WHERE
         purchased_product in ('C')
   )
`

We have been looking at various different ways to accomplish this (subQuery, join and unions, etc.) and anything that could technically work is some kind of crazy hack which doesn't perform well because it involves considerably more data than we would ever have to work with if we would just be using a simple SQL query.

**Comment by vasilev-alex** [comment]
@Lozzi did you try to use the JWT payload? https://cube.dev/docs/security/context#top

**Comment by vasilev-alex** [comment]
@thorey-as This should work for you https://cube.dev/docs/dimensions#parameters-propagate-filters-to-sub-query

**Comment by Lozzi** [comment]
@vasilev-alex the token is from auth0 and the data I'm trying to send over to our cube is user defined and will vary between requests from the same user within the same session. The only way I see it being possible for me to achieve this today would be to create a new cube instance for each request so that I can set the headers each request.

It'd be best for our use case to be able to just supply more query parameters than `query` and `queryType`.

**Comment by vasilev-alex** [comment]
@Lozzi I see. But still, it looks like you're trying to work around some modeling challenges. Passing query params bypassing the recommended approach (filters, context) may cause difficulties using other Cube.js features (such as pre-aggregations) to work effectively down the road.

We'd be happy to help you with your particular case if you share related schemas/queries/code snippets.

**Comment by Lozzi** [comment]
@vasilev-alex will do and that'd be great!

Besides the use case that we've mentioned there is another one that fits into this category.

Previously we used to make our own analytics API where we generated the SQL using regex etc. We solved one feature request there which had to do with geolocation, so a User could pick a point on a map and the distance in either miles/kms to determine the radius from the point. This was then used to find all customer within the radius using haversine distance from the point and the customers address location.

Do you have any suggestions on how we'd solve this in cube?

**Comment by Lozzi** [comment]
@vasilev-alex here is a minified version of one of our attempts to solve this.


 The problem: We're trying to gather customers that have bought X products but have not bought Y products.
 
 
We haven't found a way to use filterParams to achieve this since the second `notIn` filter will be applied to the out most selection and which results in an empty data set. Below is a minimal version of a cube based on one of the iterations we've tried to solve this. 

```js
cube(`Example`, {
    sql: `
    SELECT * FROM example
        WHERE 
            product_ref IN (includePorduct1, ..., includePorductN)
            AND customer_ref NOT IN (
                SELECT customer_ref FROM example
                    WHERE product_ref IN (excludeProduct1, ..., excludeProductN)
            )`,
    dimensions: {
        ...dimension
    },
    measures: {
        ...measures
    }
});
```

**Comment by rpaik** [comment]
Closing this issue so that the conversation can continue in the Cube.js forum at https://forum.cube.dev/t/data-modeling-to-filter-customers-who-bought-a-group-of-products-but-not-some-other-products/93.
