### ISSUE TITLE
[CubeJS React API][TypeScript] QueryRenderer query props does not accept type Query[]

### ISSUE THREAD

**Issue by GuillaumeDesforges** [cube-js/cube.js#2290]
**Describe the bug**
QueryRenderer does not accept a `query` prop of type `Query[]` even though it should be used for data blending: https://cube.dev/blog/introducing-data-blending-api/

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**

**Additional context**

See https://github.com/cube-js/cube.js/blob/1465ad1f7b4c1d4370a1f64b66de06029115ad51/packages/cubejs-client-react/index.d.ts#L117

**Comment by vasilev-alex** [comment]
Fixed by 7c002c920732b7aca6a3e3f7f346447e6f5d1b4d

**Comment by GuillaumeDesforges** [comment]
Awesome, thanks!
