### ISSUE TITLE
Query with custom dateRange including time does not hit pre-aggregation

### ISSUE THREAD

**Issue by florian-fischer-swarm** [cube-js/cube.js#2299]
**Describe the bug**
Using a data range of format YYYY-MM-DD in a query is correctly served from pre-aggregations. Using YYYY-MM-DDTHH:mm:ss.SSS is never served from pre-aggregated results.

The query itself works fine using the format listed in https://cube.dev/docs/query-format#time-dimensions-format

But I am not sure if pre-aggregation is supposed to work for the second case based on the rules in https://cube.dev/docs/pre-aggregations#rollup-rollup-selection-rules (especially 7 / time granularity).
Intuitively, I think it should.

**To Reproduce**

Given a pre-aggregation like:

```
{
  "dimensions": [
    "Someevent.somedimension",
  ],
  "measures": [
    "Someevent.count"
  ],
  "timeDimensions": [
    {
      "dimension": "Someevent.timestamp",
      "granularity": "minute"
    }
  ],
  "rollups": []
}
```

I am seeing the following cases:

1.) Pre-aggregation hit:
```
{
  "measures": [
    "Someevent.count"
  ],
  "timeDimensions": [
    {
      "dimension": "Someevent.timestamp",
      "dateRange": [
        "2021-03-02",
        "2021-03-03"
      ]
    }
  ],
  "order": {}
}
```

2.) No pre-aggregation hit:
```
{
  "measures": [
    "Someevent.count"
  ],
  "timeDimensions": [
    {
      "dimension": "Someevent.timestamp",
      "dateRange": [
        "2021-03-02T00:27:00.000",
        "2021-03-03T23:27:00.000"
      ]
    }
  ],
  "order": {}
}
```

**Expected behavior**
Have case 2 hit pre-aggregation. 

**Version:**
* 0.26.45 but same behaviour in older versions.
* Using MSSQL as backend, but I am pretty sure this is not relevant because there is no query generated to check the pre-aggregation for case 2 at all.

**Comment by Mozzarella123** [comment]
Time range with granularity in preAggregation have strange behaivour. As i realize [this](https://github.com/cube-js/cube.js/blob/2059e57a2aa7caf81691c083949395e9697d2bcb/packages/cubejs-schema-compiler/src/adapter/BaseQuery.js#L1922) defines minimal granularity for time range. 
For example:
Granularity **week**
Daterange:   "2021-01-01","2021-11-28"
Preaggregation with week granularity doesnt hit 
![image](https://user-images.githubusercontent.com/22841455/111179544-3b970c00-85bd-11eb-8dce-c332c49acbbc.png)
with dateRange "2021-03-08","2021-03-28" hit,
because first date isn't start of month and second date is end of week

**Comment by florian-fischer-swarm** [comment]
@Mozzarella123 Ah thanks, that somehow clears  up where things might go wrong.
Then, there is also the issue, on how granulartyFor is used.

https://github.com/cube-js/cube.js/blob/2059e57a2aa7caf81691c083949395e9697d2bcb/packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.js#L149

To my understanding
`
    const msTo = moment.tz(this.dateToFormatted(), this.query.timezone).add(1, 'ms');`
means that for msTo most of the   obj.milliseconds === 0 checks can never work?

**Comment by Mozzarella123** [comment]
Perhaps, i didnt check for ms

**Comment by paveltiunov** [comment]
@florian-fischer-swarm Yep. Correct. Your end time should be `"2021-03-03T23:26:59.999"` in order to be matched.

**Comment by florian-fischer-swarm** [comment]
Ah, I guess this is intended behavour to get clean / non-overlapping intervalls?

**Comment by paveltiunov** [comment]
@florian-fischer-swarm Right. Otherwise, we'd need to use half-closed intervals. I can envision we add support for this in the future.
