### ISSUE TITLE
In Developer Playground, dashboard app creation requires interactive confirmation

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#2310]
**Describe the bug**
When a user creates a dashboard app via the "Dashboard App" tab in Developer Playground, an interactive confirmation in the console is required by `npx`. See this on the screenshot:

```
Need to install the following packages:
  create-react-app
Ok to proceed? (y) y
```

If the user doesn't switch and check the console, they're never getting a dashboard app.

**Expected behavior**
No interactive confirmation is required.

**Screenshots**

<img width="829" alt="Screenshot 2021-03-05 at 11 35 33" src="https://user-images.githubusercontent.com/3852894/110165385-b4b98680-7da7-11eb-963d-848a0d433e2c.png">

**Comment by vasilev-alex** [comment]
Fixed
