### ISSUE TITLE
Bug fail sustitution of alias in the on statement

### ISSUE THREAD

**Issue by lianabeatriz93** [cube-js/cube.js#2317]
**Describe the bug**
When we use queries thats need to join more than 2 cubes, queries fails with the error that say not exist path to join some measurments. 

**To Reproduce**
We debug the code and find the problem, in the line 638 of the file BaseQuery you use
```
on: `${this.evaluateSql(j.originalFrom, j.join.sql )}${conditions ? ` AND (${conditions})` : ''}`
```
The problen is, that in ```j.join.sql``` you do not habe the alias of the expresion generated to makes the joins, and for that reazon, queries for this type always fails

**Our Solution**
We replace the function joinQuery in file BaseQuery.js, for this

```
joinQuery(join, subQueryDimensions) {
        const _this = this;
        const joins = join.joins.map(j => {
            const [cubeSql, cubeAlias, conditions] = this.rewriteInlineCubeSql(j.originalTo, true);
            return {
                sql: cubeSql,
                alias: cubeAlias,
                on: `${this.evaluateSql(j.originalFrom,

                    //before
                    //j.join.sql

                    //now
                    () => {
                        let temp = j.join.sql();
                        temp = temp.replace(j.originalTo, _this.cubeAlias(j.originalTo));
                        temp = temp.replace(j.originalFrom, _this.cubeAlias(j.originalFrom));
                        return temp;
                        }
                    //now
                    )}${conditions ? ` AND (${conditions})` : ''}`
            };
        }).concat(subQueryDimensions.map(d => this.subQueryJoin(d)));
        const [cubeSql, cubeAlias] = this.rewriteInlineCubeSql(join.root);
        return this.joinSql([{ sql: cubeSql, alias: cubeAlias }, ...joins]);
    }
```

Maybe you can solution that problem with other way, but, we also know that this solution works becouse we used it for one year until now, at begining with verson 0.10.x, and now with the latest version

**Version**
0.26.52

**Additional context**
We are very happy with your work, we hope for all the things that you can continue to develop in the future. Kind regards

**Comment by paveltiunov** [comment]
Hey @lianabeatriz93! Could you please share the schema? Most likely it's https://cube.dev/docs/direction-of-joins#transitive-join-pitfall.

**Comment by lianabeatriz93** [comment]
Hello. This is our schema. When we try to join resumen_de_casos_603075 with eventos_activos_covid19_523324 with provincia_625138 it gives the error
[higiene.zip](https://github.com/cube-js/cube.js/files/6182840/higiene.zip)

thanks for your attention

**Comment by paveltiunov** [comment]
@lianabeatriz93 Could you please share also query which doesn't work?

**Comment by paveltiunov** [comment]
@lianabeatriz93 I do think it's https://cube.dev/docs/direction-of-joins#transitive-join-pitfall so I'll close it for now. Please feel free to reopen if you think it isn't your case.
