### ISSUE TITLE
Potential security context memory leak

### ISSUE THREAD

**Issue by MattGson** [cube-js/cube.js#2333]
**Describe the bug**
I believe there may be a memory leak with setting a security context on the request as shown in https://cube.dev/docs/security

Our cube server memory increase steadily over time. After profiling with chrome dev tools, I notice that the CompilerCache and LRUCache seem to grow incrementally with every request regardless of whether I am using redis or not. 

The memory growth seems to directly correlate to the size of the securityContext object. In our case, we were trying to attach a fairly large custom context object to the req and the cube server would crash with heap failures within a few dozen requests. The total heap size goes from around 50 MB on startup to 2GB during this time. 

Since reducing our context object, the growth is much more gradual (50 MB to 100 MB under the same test) but will still eventually cause the server to fail in production conditions.

I believe some of [these](https://cube.dev/docs/config#options-reference-compiler-cache-size) configuration options may help here but still not sure how?

**To Reproduce**
1. Create a cube server.
2. Attach a custom security context in the checkAuth config
3. Make a bunch of queries
4. Notice that the heap memory increases
5. Force the GC
6. Notice that most of the memory is not cleaned up.

**Expected behavior**
The request object should only live as long as the HTTP request lifecycle as expected in a stateless service.
Cube server memory should be GC'd and return to the baseline after each request.

**Screenshots**

![Screen Shot 2021-03-11 at 9 38 38 AM](https://user-images.githubusercontent.com/20088009/110705574-79adcc00-825b-11eb-8628-793946e529ca.png)

![Screen Shot 2021-03-11 at 8 52 30 AM](https://user-images.githubusercontent.com/20088009/110706029-1b351d80-825c-11eb-87b0-b2827ff493b1.png)

**Version:**
[0.26.52]

**Comment by paveltiunov** [comment]
Hey @MattGson ! Could you please share your `cube.js` config file and some parts of the schema that have multi-tenancy dependencies?

**Comment by paveltiunov** [comment]
@MattGson Please feel free to reopen if still persists.
