### ISSUE TITLE
[Feature request] Fetch distinct values of a dimension of a cube

### ISSUE THREAD

**Issue by GuillaumeDesforges** [cube-js/cube.js#2338]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/cube-js/cube.js/issues/1016 or any kind of interactive UI building.

**Describe the solution you'd like**
An API endpoint in CubeJS backend to fetch all distinct values of a dimension

Best would be to also have an expressive way to do it in the frontend API (not to implement a React hook myself).

**Describe alternatives you've considered**
I'm going to write a small API just for that, that's a lot of work when CubeJS could handle that well.

**Comment by igorlukanin** [comment]
Hi @GuillaumeDesforges 👋 Let me ask for details so I can fully understand this request.

So, if you have a cube `Cube` with a dimension `dim`, all you need to get the distinct values of a dimension is to send a query like this to Cube.js: 

```js
{
  dimensions: [ 'Cube.dim' ],
}
```

In the result set, you should get the distinct values. Here's a real-world example of doing so: https://github.com/cube-js/cube.js/blob/master/examples/bigquery-public-datasets/dashboard-app/src/api.js#L10

Does this solution work for your use case? Could you please elaborate?

**Comment by GuillaumeDesforges** [comment]
Well, seems like exactly what I need! Thanks a lot.
