### ISSUE TITLE
ResourceTimeOut error when creating schema with remote database 

### ISSUE THREAD

**Issue by MuhammadMattiullah** [cube-js/cube.js#234]
I am connecting a remote db with mongosqld for connection with my mongodb collections. After the successful connection with database when i create a schema using the command (cubejs generate -t Event)  then after sometime it produces an error (TimeoutError: ResourceRequest timed out). 
This is the case with the remote db but when i execute all the above steps with local db then it successfully create a schema.
I connect with the db with the following command (
./bin/mongosqld --mongo-uri mongodb://IPAddress : PortNumber
)
Kindly guide me why cube js is not  creating schema with remote db and also not handling queries on remote db and how can i increase the execution timeout in cube js ?
Thanks in Advance

**Comment by paveltiunov** [comment]
@MuhammadMattiullah It usually means there're some connection problems. Could you please share your cube.js server and mongosqld logs?

**Comment by MuhammadMattiullah** [comment]
Hey Pavel!
I have tried it many times but the result is same. Its working fine while connecting with local db and schema's are being created using the command but when i connect it with my remote db then this problem arises.
These are the logs that are coming during connection with remote db. But its connecting and archieving all the hosted db's and corresponding tables as well but when i create schema of remote db collections then the below logs are:

mongosqld Logs:

2019-10-22T21:42:47.976+0500 I NETWORK    [conn1] end connection 127.0.0.1:34542 (0 connections now open)
2019-10-22T21:42:47.978+0500 I NETWORK    [conn2] connection accepted from 127.0.0.1:34550 #2 (1 connection now open)
2019-10-22T21:43:24.010+0500 E NETWORK    [conn2] client read error: EOF
2019-10-22T21:43:24.010+0500 I NETWORK    [conn2] end connection 127.0.0.1:34550 (0 connections now open)
2019-10-22T21:45:08.394+0500 I NETWORK    [conn3] connection accepted from 127.0.0.1:34556 #3 (1 connection now open)

**Comment by paveltiunov** [comment]
@MuhammadMattiullah Are you using tunnel? Logs doesn't seem to have remote addresses. Could you please also try to start dev server using `npm run dev` open http://localhost:4000 and share all the logs dev server will generate?

**Comment by paveltiunov** [comment]
@MuhammadMattiullah Did you have a chance to solve this one?

**Comment by MuhammadMattiullah** [comment]
@paveltiunov yes it was resolved. 
When i created a fresh project of cube js and then connected the mongosqld with remote db it successfully fetched all the tables of corresponding db and created schema's of all the tables. Now its working fine with remote db's.
