### ISSUE TITLE
Client core crashes trying to resolve moment-range

### ISSUE THREAD

**Issue by tonylopez91** [cube-js/cube.js#2358]
Trying to import cubejs-client/core crashes, it tries to import moment range but it seems that momet-range has not a default export

Using:
Quasar 2.0.6
Vue: 2.6.12
Webpack: 4.44.2
cubejs-client-core: 0.26.54

![Screenshot_20210312_130443](https://user-images.githubusercontent.com/57803273/110980301-b4833300-8333-11eb-8ca7-5543a14b6017.png)

**Comment by youaresofunny** [comment]
Got same issue with fresh `cubejs-docker-demo`

**Comment by paveltiunov** [comment]
@tonylopez91 @youaresofunny It should be fixed right now. Could you please check?

**Comment by youaresofunny** [comment]
@paveltiunov same result after `docker pull cubejs/cube:latest`

**Comment by paveltiunov** [comment]
@youaresofunny Yep. Sorry. The fix is shipped as part of 0.26.56.
