### ISSUE TITLE
Data Blending across multiple databases (eg: postgress + mysql) for the same query

### ISSUE THREAD

**Issue by fabiosenracorrea** [cube-js/cube.js#2361]
**Problem**

So as i read though the documentation, i understand cube provides a really easy was of blending data from different tables (eg offline and online sales). It's also clear to me that i can set up an application that reacts to my user context and access the correct database/data based on that request. That's awesome! But what i've seem to be stuck is something thats related to both of these things, but not quite any.

Here's the thing: We are building for our private company an analytics dashboard, in which any user that has his credentials to access it will see the whole data available. No security issues to setup other than JWT auth.

Our data is split in different ways, and the relevant information about it is that any data related to any date other than the current day is stored and queried by Athena. On the other hand, the data for today would be in a Mysql hosted with amazon RDS.

Is it at all possible to configure a cube to do like:

```javascript
cube(`Cube`, {
  sql: `
SELECT * FROM athena.db_name.table_name
UNION ALL
SELECT * FROM mysql.db_name.tablem_name
`
})
```
Or by creating one Cube for each and then a Blending cube to query from!

Is that (or something similar) is currently available?

Thanks in advance!!

**Comment by rpaik** [comment]
This discussion has also been moved to the Cube.js forum at https://forum.cube.dev/t/data-modeling-to-filter-customers-who-bought-a-group-of-products-but-not-some-other-products/93
