### ISSUE TITLE
No "load" request on first measure/dimension selection in a template app

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#2365]
**Describe the bug**
It looks like the template app doesn't send the "load" request after the first measure or dimension is selected.

**To Reproduce**
- Generate a template app with default settings in Developer Playground and connect it to Cube.js
- Select a measure or a dimension — no data will be fetched: in developer tools, only the "dry run" request is sent but the "load" request is NOT sent
- Select the second measure or dimension — the data will be fetched, both "dry run" and "load" requests are sent

**Expected behavior**
The data is fetched after the first request is sent to Cube.js.

**Screenshots**
After a dimension is selected: 
<img width="1072" alt="Screenshot 2021-03-12 at 16 15 44" src="https://user-images.githubusercontent.com/3852894/111011432-3b450980-834e-11eb-9d11-7b1b8f3c0c16.png">

After a measure is selected:
<img width="1072" alt="Screenshot 2021-03-12 at 16 15 50" src="https://user-images.githubusercontent.com/3852894/111011436-40a25400-834e-11eb-9de0-5f2fbf0b8a7c.png">

**Version:**
`"@cubejs-backend/server": "^0.26.49"`

**Additional context**
You can see this bug reproducing in this app: https://multi-tenant-analytics-demo.cube.dev/#/

**Comment by vasilev-alex** [comment]
I believe we've fixed this. Could you try the latest version?

**Comment by igorlukanin** [comment]
@vasilev-alex I've tried and now it works as expected. Thank you! Closing this issue...
