### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by faizanaziz** [cube-js/cube.js#2404]
**Describe the bug**
Unable to run cube.js on an arm64 based computer (M1 apple mac)

**To Reproduce**
1. Launch terminal
2. Run command "npx cubejs-cli create hello-world -d postgres"
3. This is the error - npm ERR! Error: You are using arm64 architecture which is not supported by Cube Store

**Expected behavior**
Should install

**Version:**
0.26.62

**Comment by ovr** [comment]
Hello @faizanaziz,

Did you disable rosetta 2?

Thanks

**Comment by ovr** [comment]
I understand the problem: You are using native node.js for m1, which returns arm64 for `proccess.arch`. I will prepare a fix for that.

**Comment by ovr** [comment]
@faizanaziz Can you try with (https://github.com/cube-js/cube.js/releases/tag/v0.26.64)[]? Thanks

**Comment by faizanaziz** [comment]
Thank you @ovr

Just tested, it works
