### ISSUE TITLE
Conditional select in cube query

### ISSUE THREAD

**Issue by PriyaGrover** [cube-js/cube.js#2409]
**Problem**

I have below sql which calculates time on a particular condition, where startDate and endDate are input parameters :

select  case
		when (c.created_at >= $startDate) then
		AGE ($endDate, c.created_at) 
		else
		AGE (c.created_at , $startDate)
		end as timeSpent
        from 
          case c  
          where c.created_at between $startDate and $endDate

Is there any way of writing a cube schema for above sql?

**Comment by rongfengliang** [comment]
@PriyaGrover  this maybe helpful https://cube.dev/docs/dimensions#parameters-case &&   https://cube.dev/docs/cube#context-variables-filter-params but current  not support filter with  refs

**Comment by PriyaGrover** [comment]
Can I use filter parameters "${FILTER_PARAMS}" in the "SELECT" clause of the query, if not then what is the other option for passing the filter parameters dynamically in the SELECT clause?

**Comment by rongfengliang** [comment]
@PriyaGrover  as i know current can't

**Comment by paveltiunov** [comment]
I believe it's the same use case as in #481.
