### ISSUE TITLE
Error handling when using restify

### ISSUE THREAD

**Issue by RaGuL929** [cube-js/cube.js#2412]
**Description**
Error message is not sent when an query has failed when using restify with cubejs back-end.

**To Reproduce**
1. Connect cubejs backend with restify 
2. Send an incorrect query as request to `${this.basePath}/v1/load'
Service will not send any response and Warning in promise handling will occur

**Expected behaviour**
A Error response with error status code should be sent.

**Snap of error**
```
 UnhandledPromiseRejectionWarning: TypeError: res.status(...).json is not a function
    at /node_modules/@cubejs-backend/api-gateway/dist/src/gateway.js:485:75
    at ApiGateway.handleError (/node_modules/@cubejs-backend/api-gateway/dist/src/gateway.js:524:13)
    at ApiGateway.load (/node_modules/@cubejs-backend/api-gateway/dist/src/gateway.js:436:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /node_modules/@cubejs-backend/api-gateway/dist/src/gateway.js:225:13
(node:16726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Additional context**
this issue is because restify has a different way of sending response
I fixed this issue in node_modules/@cubejs-backend/api-gateway/dist/src/gateway.js 

Actual code used for express
` resToResultFn(res) {
        // @ts-ignore
        return (message, { status } = {}) => (status ? res.status(status).json(message) : res.json(message));
    }`

Fix for restify
`resToResultFn(res) {
        // @ts-ignore
        return (message, { status } = {}) => {if(status){res.status(status);res.json(message)}else{res.json(message)}};
    }`

**Comment by ovr** [comment]
> Embedding Cube.js into Express applications is deprecated due to performance and reliability considerations. 

https://cube.dev/blog/cubejs-loves-docker/
https://github.com/cube-js/cube.js/blob/master/DEPRECATION.md#embedding-cubejs-within-express

There are no plans to support it.
