### ISSUE TITLE
vue query builder demo is broken

### ISSUE THREAD

**Issue by johanjvrens** [cube-js/cube.js#2434]
**Describe the bug**
The vue query builder demo is broken. 

**To Reproduce**
1. Go to 'https://vue-query-builder-demo.cube.dev/'
2. See errors in console

**Expected behavior**
Expect to load query builder

**Screenshots**
![Screenshot 2021-03-24 at 14 13 49](https://user-images.githubusercontent.com/8234230/112308779-3287f800-8cab-11eb-8b06-a241dd5c6d27.png)

**Comment by vasilev-alex** [comment]
Fixed by 301d8881b819c802605b38a18894074923b50d0e
