### ISSUE TITLE
Support the oss version of ElasticSearch

### ISSUE THREAD

**Issue by Anonymity94** [cube-js/cube.js#2453]
Need to support the oss version of ElasticSearch, if necessary, I can submit pr.

**Comment by paveltiunov** [comment]
Hey @Anonymity94! Do you mean open distro support?

**Comment by Anonymity94** [comment]
@paveltiunov emmmmm,I'm not sure if this question is certain.

---

[Elasticsearch OSS](https://www.elastic.co/cn/downloads/past-releases#elasticsearch-oss) does not include the x-pack plugin(**x-pack is charged** T^T), and the username and password are not required.

After this [PR](https://github.com/cube-js/cube.js/pull/2354), Elasticsearch users must use the basic version.

**Comment by paveltiunov** [comment]
@Anonymity94 I guess this one was fixed. Feel free to reopen if it isn't the case.

**Comment by Anonymity94** [comment]
@paveltiunov OK. Thanks
