### ISSUE TITLE
Pass customized parameters in the request

### ISSUE THREAD

**Issue by gusthavosantana** [cube-js/cube.js#2457]
**The `cubejs` function (@cubejs-client/core) does not allow you to pass customized parameters in a request.**

I am using the `cubejs` function that receives a token as the first parameter and an object of type `CubeJSApiOptions` that allows only the following parameters:

- apiUrl: string;
- transport ?: ITransport;
- headers ?: Record <string, string>;
- pollInterval ?: number;
- credentials ?: 'omit' | 'same-origin' | 'include';
- parseDateMeasures ?: boolean.

However, I need to pass a custom parameter to the request, so that in `checkAuth` I can access the value of the parameter, is it possible?

It would look something like the code below:

```javascript
cubejs(TOKEN, {
    apiUrl: `${process.env.REACT_APP_API_CUBE_BASE_URL}/cubejs-api/v1`,
    customParam: 'custom value'
  })
```

**Comment by vasilev-alex** [comment]
Hi @gusthavosantana! Passing custom params is not supported. We had a similar discussion here https://github.com/cube-js/cube.js/issues/2286

You should use JWT payload for this purpose https://cube.dev/docs/security/context#top

**Comment by hassankhan** [comment]
Closing as answered by @vasilev-alex
