### ISSUE TITLE
Support time dimension hieararchies

### ISSUE THREAD

**Issue by Justin-ZS** [cube-js/cube.js#246]
Currently, a pre-aggregation only works for the query that has the same granularity.
e.g. A query on `month` can be matched to the preAgg on `month` only, not on `day`.

Expect:
The pre-aggregation table on 'day' can be used to handle queries on `week`/`month`/`year` too.

**Comment by paveltiunov** [comment]
@Justin-ZS Hey Jin! Thanks for posting this! This one is really important! So there're several places that should be adjusted:
Replace with time dimension hierarchy inheritance check:
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/PreAggregations.js#L224
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/PreAggregations.js#L237
Here we should use `this.query.timeGroupedColumn()` over `super.dimensionSql()`:
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/BaseTimeDimension.js#L68

This one is tricky to implement so there's can be something I'm missing. @Justin-ZS it would be really great if you can take over it! Thanks!

**Comment by Justin-ZS** [comment]
@paveltiunov  OK, I will try to take over it.

**Comment by Justin-ZS** [comment]
@paveltiunov 
Hi, I get stuck in creating dimension SQL.
After loosening pre-aggregation match function, `this.query.timeGroupedColumn()` returns wrong SQL.

Expect: 
```sql
date_trunc('year', ("orders__created_at_month"::timestamptz AT TIME ZONE 'UTC'))
```
Actual:
```sql
date_trunc('year', ("orders__created_at_year"::timestamptz AT TIME ZONE 'UTC'))
```
`orders__created_at_year`  doesn't exist in pre-aggregation table.

I have some rough thoughts about it:
1. Rewrite SQL generate function.
In the `rollupQuery` branch, measures and dimensions would pull the corresponding SQL from matched preaggregation.
1. Keep most code unchanged.
Add more columns that include all higher time hierarchies when creating a pre-aggregation table.

 Maybe there exists a better solution. Could you share some ideas for it?

**Comment by paveltiunov** [comment]
@Justin-ZS Hey Jin! This one is pretty tricky. Second approach is viable. It backward incompatible in terms of pre-aggregation structure though. It means that this version upgrade will trigger all rollup rebuild process. Given we have deployments with rollups of trillions data points worth of hundreds of aggregation hours we do not want to trigger it unless absolutely necessary. 

I'd suggest to introduce something like `rollupGranularity` context variable and put it together with `rollupQuery: true` context:
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/PreAggregations.js#L452

So if we see that there's `rollupGranularity` defined and it differs from own time dimension granularity we can change alias granularity suffix and also do this `this.query.timeGroupedColumn()` thing. What do you think?

**Comment by Justin-ZS** [comment]
@paveltiunov 
Adding a `rollupGranularity` variable looks like a simple approach and wouldn't bring too many changes.
I will try this way accordingly.
