### ISSUE TITLE
How to disable Schema option  

### ISSUE THREAD

**Issue by I-akshay** [cube-js/cube.js#2489]
Hi Team ,
How to disable Schema option  , soo that i can prevent other users from creating any other cubes . I need to put restriction that other that me , no one (extrenal users ) should be allowed to create cube

**Comment by vasilev-alex** [comment]
Hi @I-akshay! It is not possible as of now.

I'm assuming you're using the Playground which is not supposed to be used on production. So, you can try to fork the `@cubejs-client/playground` package and implement the required authorization/authentication stuff.
