### ISSUE TITLE
Generating Schema (Measures and Dimensions) dynamically ?

### ISSUE THREAD

**Issue by MuhammadMattiullah** [cube-js/cube.js#249]
Is there any way to create measures and dimensions dynamically in cube js schema ?
For example if i want to request data as the dataset is dynamic so all the measures and dimensions cant be defined in the schema.  
For example if i have a measure of Power in my dataset and i want to get the sum, avg , max and min  etc of Power than i have to manually add all the measures corresponding to the single state and lets suppose if i have many others measures like Energy, Voltage and Current and other 100's of states then adding manually measures and dimensions for all the operations will be very hectic depending on the dataset.
So is there anyway to implement the above mentioned scenario in cube js ?

**Comment by MuhammadMattiullah** [comment]
@paveltiunov Kindly guide me about this scenario.

**Comment by paveltiunov** [comment]
@MuhammadMattiullah Hey Muhammad! Yep. It's possible. Here're some docs on it:
https://cube.dev/docs/schema-generation
https://cube.dev/docs/schema-execution-environment

**Comment by MuhammadMattiullah** [comment]
@paveltiunov Thankyou very much for your response. 
Looking into the above provided solution.

**Comment by MuhammadMattiullah** [comment]
Successfully implemented the dynamic schema using the reference of above link. Thankyou @paveltiunov for the support.
I am closing the issue

**Comment by paveltiunov** [comment]
Great to hear that!
