### ISSUE TITLE
Snowflake - heap size increase with external pre-aggregations: support direct CSV Cube Store S3 ingestion

### ISSUE THREAD

**Issue by tomsej** [cube-js/cube.js#2502]
**Describe the bug**
Ok, I am having a hard time with pre-aggregations. I have a table in :snowflake: Snowflake with 86.357.223 records (~5GB of data). In dev-mode I am trying to test external pre-aggregation:

```
    preAggregations: {
        companyNameAgg: {
          type: `rollup`,
          external: true,
          measureReferences: [applicationCntInternetTotal, applicationCntTotal, detailCntInternetTotal],
          dimensionReferences: [companyName],
          timeDimensionReference: dateValid,
          granularity: `day`,
          refreshKey: {
            every: `1 day`,
          },    
        },
      },
```

The resulting aggregation table has around 130MB with ~12 mils of records. I am using last version of `cubejs = 0.26.76` . Whenever pre-aggregation counting starts, CPU and memory rapidly increase, and after few seconds cubejs shuts down with low Node heap size (think the default is around 1GB). So I tried to increase it up to 6GB with `NODE_OPTIONS=--max_old_space_size=6096` and I increased the memory of my Docker Engine. After a while I got the message:
```
[cubestore::metastore] Persisting meta store snapshot is shown and I am still getting heap size error:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[1:0x3f62e50]   315770 ms: Mark-sweep 5882.2 (6137.8) -> 5879.7 (6135.3) MB, 4429.5 / 0.5 ms  (average mu = 0.107, current mu = 0.005) allocation failure GC in old space requested
[1:0x3f62e50]   320119 ms: Mark-sweep 5879.7 (6135.3) -> 5879.2 (6135.5) MB, 4347.9 / 0.0 ms  (average mu = 0.060, current mu = 0.000) allocation failure GC in old space requested
```

I am using the default docker image with the following .env file:
```
CUBEJS_DB_NAME=xxx
CUBEJS_DB_TYPE=snowflake
CUBEJS_DB_SNOWFLAKE_ACCOUNT=xxx
CUBEJS_DB_SNOWFLAKE_REGION='xxxx'
CUBEJS_DB_SNOWFLAKE_WAREHOUSE=xxx
CUBEJS_DB_SNOWFLAKE_ROLE=xxxx
CUBEJS_DB_SNOWFLAKE_CLIENT_SESSION_KEEP_ALIVE=2000
CUBEJS_DB_USER=xxx
CUBEJS_DB_PASS='xxxx'
CUBEJS_DEV_MODE=true
CUBEJS_API_SECRET=SECRET
CUBEJS_SCHEDULED_REFRESH_TIMER=true
```

I also tried to run cubejs in production mode with Redis and with separated cubestore instance but result is the same -> cubejs container is failing with low heap size.

**Expected behavior**
It is possible to store bigger tables into `cubestore` from Snowflake without increasing heap size of Node.js.

**Version:**
0.26.76

**Additional context**
- link to Slack discussion - https://cube-js.slack.com/archives/CC0403RRR/p1617481690412600

**Comment by tomsej** [comment]
**Answer from @paveltiunov:**

For such big tables cube store supports direct CSV download avoiding pushing data through Node.js. It’s just not implemented for Snowflake yet however it is on our roadmap.

**Comment by paveltiunov** [comment]
@tomsej Thanks for posting this!
