### ISSUE TITLE
Is there any way to control a dryRun call?

### ISSUE THREAD

**Issue by mahesh-kedari** [cube-js/cube.js#2509]
**Problem**

In one of my scenario when I’m trying to edit the query, QueryBuilder is initially getting query as empty it is triggering dryRun with that. This is responsible for producing error

`Unhandled Rejection (Error): Query should contain either measures, dimensions or timeDimensions with granularities in order to be valid`

**Comment by vasilev-alex** [comment]
hi @mahesh-kedari! Thanks for posting it here. Which Cube.js version are you using?

**Comment by vasilev-alex** [comment]
Closing the issue as in the latest versions we do validate queries before sending a `dryRun` request. @mahesh-kedari feel free to reopen the issue if it still doesn't work for you.
