### ISSUE TITLE
SECURITY_CONTEXT is not set even with valid tokens

### ISSUE THREAD

**Issue by wynandjordaan** [cube-js/cube.js#2511]
Hi there

It looks to me like the SECURITY_CONTEXT is never set and only contains undefined values.

I have tried to set it in the dev playground and with a actual JWT token that has been validated, but I only get undefined values in the where clause (WHERE 1=1)

I have even tried to upgrade to the latest release 0.26.83, same story.

```js
cube(`Orders`, {
  sql: `SELECT * FROM public.orders WHERE ${SECURITY_CONTEXT.tenantid.filter(
    'tenantid'
  )}`,
```

Thanks in advance

**Comment by rongfengliang** [comment]
@wynandjordaan  this  maybe a broken relase you can use like  this

cube.js
```code
// Cube.js configuration options: https://cube.dev/docs/config
const jwt = require('jsonwebtoken');
module.exports = {
    checkAuth: async (req, auth) => {
        const decoded = jwt.decode(auth, { complete: true });
        req.securityContext = decoded.payload;
    }
};
```

**Comment by paveltiunov** [comment]
@wynandjordaan Could you please share your `cube.js` config file, request you're trying to execute and jwt token you use?

@rongfengliang code you shared is probably incorrect due to jwt doesn't have `decode` method and it just silently fails. Errors from `checkAuth` aren't propagated.

**Comment by rongfengliang** [comment]
@paveltiunov jsonwebtoken has  `decode` method    https://www.npmjs.com/package/jsonwebtoken#jwtdecodetoken--options

**Comment by paveltiunov** [comment]
@rongfengliang You're right. It's indeed in JWT as well. I was under the impression it's only defined in JWS. Just tested your code. It works for me. What JWT token do you use?

**Comment by rongfengliang** [comment]
@paveltiunov   this code not use jwt secret for better security must use jwt secret , jwt secret was generate by cli 
code acccess it with `process.env.CUBEJS_API_SECRET`,i think maybe better decode jwt  if we also config  `checkAuth`,as i known old version decode it with  `securityContext `

**Comment by paveltiunov** [comment]
@rongfengliang Yep. This is how default implementation works. Are you using docker or npx generated project?

**Comment by rongfengliang** [comment]
@paveltiunov  yes, i  use  npx generated  project

**Comment by wynandjordaan** [comment]
Hi @paveltiunov,

I am using a clean npx created project.

On further investigation it looks to me like the cli generated tokens are working as expected, however when I use the token below it looks like the the SECURITY_CONTEXT is not properly set.

My cube.js
```js
module.exports = {
    checkAuth: async (req, auth) => {
        const decoded = jwt.decode(auth, { complete: true });
        req.securityContext = decoded.payload;

        console.log("securityContext", req.securityContext);
    },
};
```

The output from the above from the token I use:
```js
securityContext {
  nbf: 1617869505,
  exp: 1617955905,
  iss: 'https://******',
  aud: '****.api',
  client_id: 'test-client',
  tenantdb: 'master',
  scope: [ '***.command' ]
}
```

/schema/Activities.js
```js
cube(`Activities`, {
  sql: `
  SELECT * FROM ${SECURITY_CONTEXT.tenantdb.unsafeValue()}."Activities" 
  `,
   measures: {
    count: {
      type: `count`
        }
  },
  
  dataSource: `default`
});
```


When I execute this query I get the following:

```
http://localhost:4000/cubejs-api/v1/sql?query={"measures":["Activities.count"]}
```

As you can see in the result the 
Result:
```sql
SELECT TOP 10000
                 count("activities"."Id") "activities__count"
                FROM
               undefined."Activities" AS "activities" ",

```

Expected Result:
```sql
SELECT TOP 10000
                 count("activities"."Id") "activities__count"
                FROM
               master."Activities" AS "activities" ",

```

**Comment by wynandjordaan** [comment]
I think I have found the issue:


The CUBEJS_JWT_CLAIMS_NAMESPACE was set to the wrong value.
