### ISSUE TITLE
Error: Installing serverless npx template for CubeJS results in an error

### ISSUE THREAD

**Issue by gottijspy** [cube-js/cube.js#2520]
Update: Looks like this happens only on Windows OS.

`npm install --save @cubejs-backend/cubestore-driver`

> @cubejs-backend/cubestore@0.26.81 postinstall '\node_modules\@cubejs-backend\cubestore'
> ./bin/post-install

'.' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @cubejs-backend/cubestore@0.26.81 postinstall: `./bin/post-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @cubejs-backend/cubestore@0.26.81 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ovr** [comment]
I reopened it, my solution doesn't fix the problem. Working on it.

**Comment by schoolytics-cto** [comment]
Running tutorial on a Macbook

npx cubejs-cli create hello-world 

fails with:
```
- Writing files from template
- Installing Cube Store driver
npm ERR! code 1
npm ERR! path /Users/philips/Developer/cubejs/hello-world/node_modules/@cubejs-backend/cubestore
npm ERR! command failed
npm ERR! command sh -c cubestore-installer
npm ERR! Cube.js Cube Store Installer ---------------------------------------
npm ERR! 
npm ERR! Error: Cube Store v0.26.92 Artifact for darwin is not found. Most probably it is still building. Please try again later.
npm ERR!     at Object.downloadBinaryFromRelease (/Users/philips/Developer/cubejs/hello-world/node_modules/@cubejs-backend/cubestore/js-wrapper/download.ts:83:11)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR!     at /Users/philips/Developer/cubejs/hello-world/node_modules/@cubejs-backend/cubestore/js-wrapper/post-install.ts:12:7
npm ERR! 
npm ERR! Need some help? -------------------------------------
npm ERR! 
npm ERR!   Ask this question in Cube.js Slack: https://slack.cube.dev
npm ERR!   Post an issue: https://github.com/cube-js/cube.js/issues

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philips/.npm/_logs/2021-04-12T20_22_44_966Z-debug.log

Cube.js Error ---------------------------------------

Error: npm install --save-dev @cubejs-backend/cubestore-driver failed with exit code 1
    at ChildProcess.<anonymous> (/Users/philips/.npm/_npx/b15e41626979eec6/node_modules/cubejs-cli/src/utils.ts:14:16)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

npm ERR! code 1
npm ERR! path /Users/philips/Developer/cubejs
npm ERR! command failed
npm ERR! command sh -c cubejs "create" "hello-world"
```

**Comment by ovr** [comment]
@gottijspy Can you try with latest release on Windows? Thanks

**Comment by ovr** [comment]
> npm ERR! Error: Cube Store v0.26.92 Artifact for darwin is not found. Most probably it is still building. Please try again later.

@schoolytics-cto Please use `v0.26.93`.

 v0.26.92 was broken for Darwin because brew failed to download upx from BinTray. BinTray had a maintenance today.

https://github.com/cube-js/cube.js/runs/2324882006?check_suite_focus=true
Fixed in https://github.com/cube-js/cube.js/commit/88a94464251cfa48a05447780c7157639a5df1eb

Update: Anyway I've updated assets manually for v0.26.92. It should work now.

**Comment by ovr** [comment]
Fixed & tested.

![image](https://user-images.githubusercontent.com/572096/114539921-a3dd1a00-9c5d-11eb-9ee3-e7903a7b3ef7.png)

**Comment by gottijspy** [comment]
> @gottijspy Can you try with latest release on Windows? Thanks

Thank you! Able to install 0.26.95 successfully on Windows OS.

```
> @cubejs-backend/cubestore@0.26.95 postinstall sls-cubejs\node_modules\@cubejs-backend\cubestore
> node bin/post-install

```
Downloading [========================================] 100% | Speed: 3.42MB/s
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @cubejs-backend/cubestore-driver@0.26.95
added 886 packages from 516 contributors and audited 887 packages in 292.53s

found 0 vulnerabilities
