### ISSUE TITLE
Does cube js security context support multiple value in single field?

### ISSUE THREAD

**Issue by LeeJiaLe** [cube-js/cube.js#2530]
Does cube js security context support multiple value in single field?

What I want to achieve is something like this
For example manager can view multiple user data

```javascript
jwt.sign( { user_id: [1, 2, 3], }, CUBEJS_API_SECRET, { expiresIn: '1d', }, ),
```

due to application design, my database didn't have manager id, but I can get the users id under the manager

**Comment by rongfengliang** [comment]
@LeeJiaLe current can't . if needed you can use querytransform func

**Comment by LeeJiaLe** [comment]
> @LeeJiaLe current can't . if needed you can use querytransform func

Any detail on how it possible done?

**Comment by rongfengliang** [comment]
> > @LeeJiaLe current can't . if needed you can use querytransform func
> 
> Any detail on how it possible done?

some links 
https://cube.dev/docs/config#options-reference-query-transformer 
https://cube.dev/docs/multitenancy-setup#security-context-vs-query-transformer

**Comment by LeeJiaLe** [comment]
> > > @LeeJiaLe current can't . if needed you can use querytransform func
> > 
> > 
> > Any detail on how it possible done?
> 
> some links
> https://cube.dev/docs/config#options-reference-query-transformer
> https://cube.dev/docs/multitenancy-setup#security-context-vs-query-transformer

Oh yes, this is exactly what I want, thank you very much for fast replying!
