### ISSUE TITLE
Error: on backend application using Cube.js CLI

### ISSUE THREAD

**Issue by rahulbabu25041998** [cube-js/cube.js#2535]
I was trying to create a backend application using Cube.js CLI. The process continued for some time, then it suddenly stopped and throw's me an error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @cubejs-backend/cubestore@0.26.90 postinstall: `bin/post-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @cubejs-backend/cubestore@0.26.90 postinstal script.
npm ERR! This is probably not a problem with npm. There is additional logging output above.

**Comment by ovr** [comment]
Hello @rahulbabu25041998 ,

What OS do you use?

**Comment by rahulbabu25041998** [comment]
> Hello @rahulbabu25041998 ,
> 
> What OS do you use?

Obviously Windows 10

**Comment by rahulbabu25041998** [comment]
Hello @ovr 

Windows 10.

**Comment by ovr** [comment]
Duplicates of https://github.com/cube-js/cube.js/issues/2520
I am working on this issue now.
