### ISSUE TITLE
External Refresh should not require all queries to be preaggregatable

### ISSUE THREAD

**Issue by yatesdev** [cube-js/cube.js#2550]
We have a background instance that is populating our preaggregations. However, if generation is failing or we create a
new query that does not have a relevant preaggregation defined yet, we receive the `One or more pre-aggregation tables could not be found to satisfy that query` error returned by our "non-background" instance that takes requests.
Essentially, enabling externalRefresh is also enabling rollupOnlyMode.

**Describe the solution you'd like**
Ideally, this should not be an all or nothing scenario. The background job should update the preaggregations it has available to it as normal, but if a request is made that isn't captured by a preagg, the Cubejs instance should make the query against the cube as if no preaggregations are defined, not error out entirely.
Current functionality could be maintained if both `externalRefresh` and `rollupOnlyMode` are set to true.

**Describe alternatives you've considered**
Unfortunately having the "non-background" instance of cube building preaggs slows everything to a crawl, so removing the background job is not an option.

**Additional context**
Relevant code where error is thrown:
https://github.com/cube-js/cube.js/blob/adf059ec52e31e3ebc055b60a1ac6236c57251f8/packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts#L362-L371

**Comment by paveltiunov** [comment]
@yatesdev Hey Mike! Thanks for posting this one! I guess the original reasoning for this feature that was introduced by @jcw- is to avoid hitting raw data at all costs. It means all pre-aggregations should be defined and warmed up before schema goes to production otherwise it's just a development or deployment mistake.

Could you please elaborate a little bit on why the new query which arrived isn't covered by pre-aggregation? Is it still need to be built or pre-aggregation even not defined yet?

**Comment by yatesdev** [comment]
Correct we have about 50 preaggregation tables that are defined by our schema, so they take a while to build.
We are currently trying to improve our Redshift database performance to help, but there is still going to be a >20 minute timeframe where we cannot even validate the deployment against our UI, due to the errors.
Once the set of preaggregations is built, the situation does improve though, so this is more to help handle initial bootstrap/startup.

**Comment by paveltiunov** [comment]
@yatesdev You should use the blue-green deployment concept for that. Before you deploy the actual UI you should deploy the pre-aggregation warmup process which makes sure all pre-aggregations are up to date with the new version of the schema. When it's ready new Cube.js API server version gradually substitutes older one with zero downtime and no build time for pre-aggregations. This is something we built in Cube Cloud and it works well for production environments.
