### ISSUE TITLE
How do I see the drillMember records?

### ISSUE THREAD

**Issue by sebinbabu** [cube-js/cube.js#256]
I've created some schema files and established joins between them.
I've added drillMembers to a count measure.
How do I query the drillMembers from the client (a table to display the drillMember rows perhaps)?
There is no example in the docs for this.

**Comment by paveltiunov** [comment]
@sebinbabu Hey Sebin! Thanks for posting this! There's already an issue for that: #190 . Could you please upvote it? This way we can know demand for it.
