### ISSUE TITLE
How to format time-type data with mongodb and cubejs?

### ISSUE THREAD

**Issue by radiorz** [cube-js/cube.js#2567]
I found this url about this topic:

https://cube.dev/docs/types-and-formats#dimensions-formats
https://cube.dev/docs/working-with-string-time-dimensions
I didnt found the format for time-type. So I try to use sql: PARSE_TIMESTAMP('%Y-%m-%d', date)
```
    createdat: {
      sql: `PARSE_TIMESTAMP('%Y-%m-%d',${CUBE}.\`createdAt\`)`,
      type: `time`
    },
```
it will return a error:
```
Error: Error: scalar function 'parse_timestamp' is not supported
```

**Comment by ovr** [comment]
Hello @radiorz ,

```
SELECT DATE(CURRENT_TIMESTAMP(), '%Y-%m-%d');
```

**Comment by radiorz** [comment]
Thank you @ovr ,But when i use  "the  time by day/week" it will format my data once again so i cannot get the right formated data.
![image](https://user-images.githubusercontent.com/24271959/115169093-b3da7b00-a0ef-11eb-92ed-64f50468a16a.png)
What should i do to change it?

**Comment by paveltiunov** [comment]
Please consider using client-side date formatting instead.
