### ISSUE TITLE
Dashboard App - Angular

### ISSUE THREAD

**Issue by bilelsgh** [cube-js/cube.js#2577]
Hello,

How can i find a Dashboard App based on Angular. I would like to do the exact same thing as [this ](https://real-time-dashboard-demo.cube.dev/#/).

Thank you :)

**Comment by vasilev-alex** [comment]
Hi @bilelsgh! I don't believe we have the same dashboard in Angular but you can find all the examples here https://github.com/cube-js/cube.js/tree/master/examples
