### ISSUE TITLE
Support for complex boolean logic in filters

### ISSUE THREAD

**Issue by ferrants** [cube-js/cube.js#259]
**Is your feature request related to a problem? Please describe.**
I want to handle use cases like:
- “Give me records where measures impressions are above 5 or clicks are above 1”
- "Give me records where (impressions are above 5 or clicks are above 1) AND sales are above 0"

**Describe the solution you'd like**
Boolean description of filters to apply, with ability to combine with ANDs or ORs. Top-level filters can still automatically be combined with an AND to maintain existing behavior. Instead of the existing `filter` object, allow an object with a single `or` or `and` key with nested filter objects that determine the boolean logic.

Queries could look like:
```
{
    ...
    filters: [
        {
            or: [
                {
                    member: "Results.impressions",
                    operator: "gte",
                    values: ["5"]
                },
                {
                    member: "Results.clicks",
                    operator: "gte",
                    values: ["1"]
                },
            ]
        }
    ]
}
```
with an and:
```
{
    ...
    filters: [
        {
            and: [
                {
                    or: [
                        {
                            member: "Results.impressions",
                            operator: "gte",
                            values: ["5"]
                        },
                        {
                            member: "Results.clicks",
                            operator: "gte",
                            values: ["1"]
                        },
                    ]
                },
                {
                    member: "Results.sales",
                    operator: "gte",
                    values: ["1"]
                },
            ]
        }
    ]
}
```

**Describe alternatives you've considered**
`filters` could be a dict at the top-level, but that would break existing uses

**Comment by paveltiunov** [comment]
@ferrants Hey Matt! Thanks for posting this one! Just to double check on use case: are these `5` and `1` filter values are variable in your case? I mean those are can be changed by users separately from each other?

**Comment by ferrants** [comment]
Yes @paveltiunov , these are just placeholders / example values. We could filter in the cube's sql definition for these statically, but we are trying to support specifying these dynamically and independently of each other when running a query against Cube.js. We have other fields we want to support this on as well, I just included sales, clicks and impressions as an example.

Seems like the logic would be in this file:
https://github.com/cube-js/cube.js/blob/e423d82f2045f43420488b08d34f954e308f5714/packages/cubejs-schema-compiler/adapter/BaseFilter.js#L29
This is something I'm trying to get working this sprint. I'm hoping to do this for both dimensions and measures. Does the format I suggested make sense or are you thinking a different format would be better?

**Comment by paveltiunov** [comment]
@ferrants Yeah. Overall this query structure seems right to me. This one will involve a lot of changes though. Two main points for implementation:
1. We'd need separate class for these logic filters. I believe it should extend `BaseFilter`.
2. All current filters usage should be checked for dimensions field and adjusted accordingly. Especially in pre-aggregations.
Need to think a little bit on this one. Will try to post some more thoughts on it tomorrow.

**Comment by kartblanch** [comment]
Hello! Did this feature appear in the current version Cube.js?

**Comment by paveltiunov** [comment]
@kartblanch Hey Anton! It isn't implemented yet. I believe @ferrants working on it.

**Comment by ferrants** [comment]
hey @kartblanch , @paveltiunov , I'm not working on this.

**Comment by olafkrawczyk** [comment]
Hey @paveltiunov any updates on this one? It would be great to have this feature. I can help if needed

**Comment by paveltiunov** [comment]
On our roadmap. For those who's looking for possible workarounds: https://stackoverflow.com/questions/58557803/how-to-add-or-condition-in-cube-js-filter-query.

**Comment by Manny91** [comment]
Hello all!

I was wondering if this is been released already? if it isn't, is it going to happen at any time soon?

Thanks

**Comment by niravjprabtani** [comment]
Is this feature already released ?
