### ISSUE TITLE
Number of redis connections exceeds 900 in multitenancy setup of Cube.js

### ISSUE THREAD

**Issue by aishwaryapanchal** [cube-js/cube.js#2609]
I have configured Redis cache with CUBEJS_REDIS_POOL_MAX=50 in a multitenancy setup of Cube.js.
Despite adding the above configuration, the number of Redis connections exceeds 900.

**Comment by ovr** [comment]
Hello @aishwaryapanchal ,

Yes, It's an issue. Thank you for submitting it.

Context:

Internally Cube.js instances `RedisPool` per `OrchestratorApi` instance, which causes a problem with multi-tenancy setup.

**Comment by paveltiunov** [comment]
@aishwaryapanchal Cube.js indeed reserves a pool per tenant and we're most likely keep it this way. We'd need to properly document it though.
