### ISSUE TITLE
cubejs-postgres-driver@0.11.6 timestamps returned as string instead of javascript object

### ISSUE THREAD

**Issue by berndartmueller** [cube-js/cube.js#265]
**Describe the bug**
Since adding custom pg type parsers for pg timestamp and timestampz in version 0.11.6 (https://github.com/cube-js/cube.js/commit/f1346daa0cb3ff47a6d226e7b8406c7b4874070a#diff-2fe83f1002ed7f79fe3eac6030f08254R11), when using e.g. Sequelize, all timestamp columns are returned as strings. This breaks current behaviour of our application because Sequelize says it returns Date, but in fact, it's a string.

**To Reproduce**
1. Checkout version 0.11.6 of cubejs-postgres-driver
2. Use any sequelize version and fetch a row from db which has a timestamp column
3. You will notice, the returned property is a string instead of javascript date object.

**Expected behavior**
Timestamp columns should return javascript date as usual, not string. Maybe it's intended for cubejs and it's very own frontend. But this commit affects the whole nodejs application, because the "pg" npm package is shared across other npm packages.

**Screenshots**

**Version:**
cubejs-postgres-driver@0.11.6

**Comment by paveltiunov** [comment]
@berndartmueller Hey Bernd! Yeah. This static solution sucks. I see node-postgres recently introduced custom types support on per-query basis: https://node-postgres.com/features/queries#Types. We'd need to upgrade version and use it instead of static one.

**Comment by paveltiunov** [comment]
@berndartmueller Would love if you can help here.

**Comment by berndartmueller** [comment]
@paveltiunov Those custom types on per-query basis look promising! Will have a look at it tomorrow
