### ISSUE TITLE
JWK_URL in dev mode

### ISSUE THREAD

**Issue by willhausman** [cube-js/cube.js#2651]
**Describe the bug**
When starting a cubejs server in dev mode, specifying `CUBEJS_JWK_URL` throws a prefetch error because the cert is self-signed.

Also, if I've specified a `CUBEJS_JWK_URL`, should `Warning. Option apiSecret is required in dev mode. Cube.js has generated it` really happen? I'm clearly not using an api secret.

**Expected behavior**
In dev mode, I should be able to use self-signed certs.

**Version:**
0.27.4

**Additional context**
I run a custom OIDC authentication microservice in docker when running my application that uses cubejs.

**Comment by ovr** [comment]
Hello @willhausman ,

> Also, if I've specified a CUBEJS_JWK_URL, should Warning. Option apiSecret is required in dev mode. Cube.js has generated it really happen? I'm clearly not using an api secret.

It's just a warning, `apiSecret` is used inside the playground, which is available in dev mode.

**Comment by willhausman** [comment]
> It's just a warning, `apiSecret` is used inside the playground, which is available in dev mode.

Thanks @ovr . That makes sense.

Further information for this issue.  I started to code a simple `rejectUnauthorized` resolution PR using `getEnv('devMode')`, but then realized I can directly set `NODE_TLS_REJECT_UNAUTHORIZED=0` in my development environment to bypass making code changes to cube.js.  This workaround allows me to move forward, although I believe a support option directly in cube.js which does not produce node warnings about insecure HTTPS requests would be great.

**Comment by paveltiunov** [comment]
@willhausman Hey Will! Is it just for dev purposes or do you plan to use a self-signed certificate in production?

**Comment by willhausman** [comment]
Hey @paveltiunov, been a while. I hope you are well.  This is just for development and cicd pipeline automated tests.  Once in actual production, a "real" cert is used.
