### ISSUE TITLE
"Cannot read property 'readOnly' of undefined" when creating mssql pre-agg

### ISSUE THREAD

**Issue by ack210** [cube-js/cube.js#2659]
When creating a rollup pre-aggregate from a mssql source, and a custom driver factory has not been defined (i.e., the SQL connection is configured via environment variables only), I receive the following error when attempting to define a rollup pre-aggregate:

> **TypeError: Cannot read property 'readOnly' of undefined**
    at MSSqlDriver.readOnly ([...]/@cubejs-backend/mssql-driver/driver/MSSqlDriver.js:103:26)
    at [...]/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:589:95
    at queue.<computed>.QueryCache_1.QueryCache.createQueue.concurrency ([...]/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:942:65)
    at Object.query ([...]/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:261:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at QueryQueue.processQuery ([...]/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:259:21)

It appears [this line](https://github.com/cube-js/cube.js/blob/c1e25d7184c5ed63ba083da1cd9cf0f2111b8011/packages/cubejs-mssql-driver/driver/MSSqlDriver.js#L33) is responsible for causing the error, as it is re-assigning the `config` parameter to the `config` property, regardless of whether `config` is `null` or not.  Further, since the `config` property is already defined immediately before this, and the `config` parameter is spread in that definition, I believe this line is superfluous and can be removed.

Until fixed, a workaround is to define a custom driver factory in `cube.js`:
```
module.exports = {
  driverFactory: () =>
    new MsSqlDriver({
      host: process.env.CUBEJS_DB_HOST,
      database: process.env.CUBEJS_DB_NAME,
      user: process.env.CUBEJS_DB_USER,
      password: process.env.CUBEJS_DB_PASS,
      options: {
        encrypt: process.env.CUBEJS_DB_SSL === "true",
      },
      readOnly: true,
    }),
};
```

Happy to submit a PR for this myself over the next day or so!

**Comment by ovr** [comment]
Hello @ack210 ,

> It appears this line is responsible for causing the error, as it is re-assigning the config parameter to the config property,

Yes, you are right!

Thank you for submitting an issue 👍
