### ISSUE TITLE
External Preaggregations in RDS for Cubes querying Redshift should pass through S3 using UNLOAD and COPY command 

### ISSUE THREAD

**Issue by ferrants** [cube-js/cube.js#266]
**Is your feature request related to a problem? Please describe.**
I am trying to persist sizable preaggregate tables in an RDS Database, sourced from a Redshift Database while using Cube.js Serverless. Loading the external table through the running cube.js instance is inefficient for Redshift -> RDS data transfers.

**Describe the solution you'd like**
For persisting preaggregates in RDS from Redshift, instead of passing trough Cube.js, allow the Redshift Driver / RDS Driver (currently just Postgres driver, consider sub-classing) to run an [UNLOAD](https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html) command on Redshift to land the results in S3, then run the COPY command from RDS to ingest to the database (https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-rds-postgresql-supports-data-import-from-amazon-s3/). This will greatly speed up external preaggregations.

Logic seems to be in here:
https://github.com/cube-js/cube.js/blob/6c81a02776a092f8468332d979c6ac273eeca211/packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js#L357
https://github.com/cube-js/cube.js/blob/feccdb5c40b1dec2b6ef9d39e6947e1c0c90c7db/packages/cubejs-query-orchestrator/driver/BaseDriver.js#L102-L104

**Describe alternatives you've considered**
Just using the slower cube.js method, but it's been slower than I'd like and with the Serverless approach, I feat we'll run into time and memory constraints.

**Additional context**
I could probably add support for this.

**Comment by paveltiunov** [comment]
@ferrants Yeah. Right. Every driver should implement it's own download tailored for performance capabilities. It would be great if you can contribute it! We can consider option of subclassing as well as providing some options for Postgres driver.

**Comment by narisso** [comment]
Hi, I recently had this issue and ended up using the dblink extension from postgres to redshift, it works like a charm with minor modifications to the drivers with a subclass.

**Comment by paveltiunov** [comment]
@narisso Hey Nicolas! Interesting. Are you using dblink to download results from redshift to postgres? And what modifications did you make to driver?

**Comment by ferrants** [comment]
@narisso , I'm glad that worked for you. I was using dblink to generate materialized views of  preaggregates (not for cube.js), but it was taking too long to generate the views for the large tables I was materializing. This method should definitely work for smaller data though.

**Comment by narisso** [comment]
Yes @paveltiunov I'm using dblink for the table download, the general changes for a driver are:
```
async downloadTable(table) {
    return null;
}

async uploadTable(table, columns, tableData) {
    try {
      let queryStr = `CREATE TABLE ${table} AS SELECT *
      FROM dblink('foreign_server',$REDSHIFT$
          SELECT ${columns.map(c => this.quoteIdentifier(c.name)).join(', ')}
          FROM ${table}
      $REDSHIFT$) AS t1(${columns.map(c => `${this.quoteIdentifier(c.name)} ${c.type}`).join(', ')})`;
      await this.query(queryStr);
    } catch (e) {
      throw e;
    }
}
```
