### ISSUE TITLE
Getting the count/list of users who have not purchased a item

### ISSUE THREAD

**Issue by sridhard** [cube-js/cube.js#2666]
Hi,

We have a use case where we want to show the count and the list of users who have signedup but not purchased any item.
Below is the sample SQL query for doing this:

`SELECT customers_id, customers_firstname, customers_lastname, customers_email_address
FROM customers
WHERE customers_id 
NOT IN (
SELECT customers_id
FROM orders
)`

Can we support this kind of requirement using cubejs? if possible can you pls give an idea about how to do it

**Comment by hassankhan** [comment]
Hi @sridhard :wave:

Just to expand on what @rongfengliang said, Cube.js can absolutely fulfil those requirements as well as do much more. Please check the Getting Started section of the documentation and try starting a new project; you can also join our [Discourse forum](https://forum.cube.dev/) or our [Slack community](https://slack.cube.dev/) where you'll find be able to get support 😀

**Comment by rchkv** [comment]
Hi @sridhard 🙂

I hope you solved this issue. I close it, but if you need any further assistance, please reopen the issue and follow up. We'll be happy to help you!
