### ISSUE TITLE
Support of dynamic filters

### ISSUE THREAD

**Issue by sridhard** [cube-js/cube.js#2667]
Hi,

Ours is a edtech company. In our DB we have Courses, Categories etc. We want to apply filters for course or categories dimension.

course/categories values are not fix and we need to find the values from the DB itself with an sql query.
Also we want to use the cubeJS query builder.

1. Is there any way to query the values from DB and give as values to the filter? Can filter values can be taken from another SQL query? How can we achieve this requirement
2. We want to use query builder. Can we implement dynamic filter values using query builder?

One way can be we can pre-query the values using our api and then we can show a drop-down to user. After the user select the value we can send query to cubejs. But this approach does-not use query builder and we want to use many features of query builder

**Comment by hassankhan** [comment]
Hi @sridhard :wave:

This is definitely possible by using drilldowns, please [consult the docs](https://cube.dev/docs/drill-downs#top) for more information. I recommend joining our Discourse forum or our Slack community where you'll find be able to get support 😀
