### ISSUE TITLE
Improve request error contents

### ISSUE THREAD

**Issue by sveisvei** [cube-js/cube.js#2672]
**Is your feature request related to a problem? Please describe.**
Query errors from backend is missing from the error thrown via frontend code.

**Describe the solution you'd like**
Have added more context, e.g. add response from a `400` `Bad Request` to the error object ```{"error":"Data blending query granularities must match"}``` here https://github.com/cube-js/cube.js/blob/c21b5f7690d5de7570034449d24a7842dfd097c6/packages/cubejs-client-core/src/index.js#L112

`VError` or `Boom.boomify` has patterns around decorating errors.

**Describe alternatives you've considered**
I have not found any way of accessing the response from the backend

**Comment by vasilev-alex** [comment]
Closed by #2703
