### ISSUE TITLE
Support a `maximum` time granularity option

### ISSUE THREAD

**Issue by g-berthiaume** [cube-js/cube.js#271]
**Is your feature request related to a problem? Please describe.**
My data is sampled every second. I would like to create a dashboard with that time granularity.

**Describe the solution you'd like**
From the doc:
> Supported granularities: hour, day, week, month.

I suggest adding a `max` option so the time granularity adapts to the data sampling rate. 
I understand a big data set could cause stress on the system. You could maybe limit the `timeDimensions.dateRange` if the user select a `timeDimensions.granularity` smaller than an hour.

**Describe alternatives you've considered**
You could also add a `minute`, `second` and `milisecond` options.

**Comment by paveltiunov** [comment]
Hey @g-berthiaume ! Thanks for posting this one! For additional granularities support there's already an issue #177. 

Regarding max granularity: you can just use your time column as a generic dimension instead of time dimension. This way granularity will always match the one is in database.

**Comment by paveltiunov** [comment]
Hey @g-berthiaume ! Was this issue resolved for you?
