### ISSUE TITLE
Update configuration documentation to make it clear that queries are tracked

### ISSUE THREAD

**Issue by jasongi** [cube-js/cube.js#2713]
**Describe the bug**
[The documentation here](https://github.com/cube-js/cube.js/blob/master/docs/content/Configuration/Config.md#telemetry) says:

> Cube.js collects high-level anonymous usage statistics for servers started in development mode. It doesn't track any credentials, schema contents or queries issued.

However it is clear by inspecting the https://track.cube.dev/track calls that query information is sent under the page tracking call under the search property e.g

```
search: "?query={%22dimensions%22:[%22Orders.status%22],%22timeDimensions%22:[],%22order%22:{%22Orders.status%22:%22asc%22}}"
```

Either the documentation or tracking should be updated so they reflect each other. I think the ethical thing to do would be to not track query data.

**To Reproduce**
1. Make a query in the development playground
2. Watch the tracking call to see the query being sent to the tracking server.

**Expected behavior**
Documentation and behaviour should match

**Screenshots**

**Version:**
Latest

**Additional context**

**Comment by jasongi** [comment]
Also, perhaps more importantly, the telemetry variable doesn't seem to stop tracking (at least for me).

**Comment by paveltiunov** [comment]
@jasongi Hey Jason! Thanks for pointing this out! Those two actually bugs. We'll fix them ASAP.
