### ISSUE TITLE
Dremio pre-aggregation download streaming support 

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube.js#2725]
**Describe the bug**

i have one table has more than 500000 datas . config with preAggregations is too slow 
and  always has `Error: Error: read ECONNRESET` and query db error

**Comment by paveltiunov** [comment]
@rongfengliang Could you please prove a little bit more info? What DB do you use as a source? Do you pre-aggregate using cube store?

**Comment by rongfengliang** [comment]
@paveltiunov  i have try  pre-aggregate with cubestore && sql database . my db is dremio . pre-aggregate config  as below
data is not too big (i try add some limit . with 100000 still has Error: read ECONNRESET)
```code
  preAggregations: {
    main: {
      type: `originalSql`,
      external: true
    },
  },
```

**Comment by rongfengliang** [comment]
cube.js version 0.27.11

**Comment by paveltiunov** [comment]
@rongfengliang Currently not all database drivers support streaming and / or direct Cube Store ingestion. By default, driver will try to fetch the whole data set which can cause out of memory in case of data set is large. I believe there's paging support for dremio queries so streaming can be implemented. Here's a good starting point if you want to implement it for dremio: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-mysql-driver/driver/MySqlDriver.js#L177.

**Comment by rongfengliang** [comment]
@paveltiunov  ok,thanks !!!
