### ISSUE TITLE
Strict validatation for configuration add dialectFactory && externalDialectFactory

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube.js#2726]
**Is your feature request related to a problem? Please describe.**
sometimes is some driver has bug or we need add  myself driver allow add   dialectFactory && externalDialectFactory maybe 
more flexibility
 
**Describe the solution you'd like**
 
 https://github.com/cube-js/cube.js/blob/master/packages/cubejs-server-core/src/core/optionsValidate.ts

add:
```code
    dialectFactory: Joi.func(),
    externalDialectFactory: Joi.func(),
```

if  possible i will make pr

**Comment by ovr** [comment]
Hello @rongfengliang ,

Thank you for submitting the issue 🍰 

Fixed & released in `v0.27.14`

Thanks
