### ISSUE TITLE
Date casting in MSSQL leads to data being returned for wider time range than requested

### ISSUE THREAD

**Issue by bgiles28** [cube-js/cube.js#2729]
**Describe the bug**
When a query with a date range (e.g. `"dateRange": ["2021-01-01",  "2021-03-31"]`) in the time dimension gets made to MSSQL, the end date gets updated to be `2021-03-31T23:59:59.999` and the generated SQL query casts that value as `DATETIME`. The problem with this casting is that it actually results in the date being updated to `2021-04-01T00:00:00.000` which leads to an additional unexpected data point being returned for `2021-04-01`.

**To Reproduce**
1. In MSSQL server, run `SELECT CAST('2021-03-31T23:59:59.999' AS DATETIME)` and it will return `2021-04-01 00:00:00.000`.
2. In CubeJS, a query with time dimensions like below produces the SQL WHERE clause as follows:
Query: 
```
 "timeDimensions": [
    {
      "dimension": "Date",
      "granularity": "month",
      "dateRange": [
        "2021-01-01",
        "2021-03-31"
      ]
    }
  ],
```

SQL: 
```
WHERE
  (
    "Date" >= CAST(@ _1 AS DATETIME)
    AND "Date" <= CAST(@ _2 AS DATETIME)
  )
```

**Expected behavior**
Queries with a date range such as `["2021-01-01",  "2021-03-31"]` would only return data within that date range. 

**Version:**
```
  "@cubejs-backend/cubestore-driver": "0.27.10",
  "@cubejs-backend/mssql-driver": "0.27.10",
  "@cubejs-backend/server": "0.27.10"
```

**Additional context**
I believe the issue could be fixed by changing the `CAST(${value} AS DATETIME)` (https://github.com/cube-js/cube.js/blob/c21b5f7690d5de7570034449d24a7842dfd097c6/packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js#L64)to `CAST(${value} AS DATETIME2)` which correctly preserves the precision and doesn't round up the date.

**Comment by hassankhan** [comment]
Fixed in https://github.com/cube-js/cube.js/pull/2988
