### ISSUE TITLE
CUBEJS_REDIS_URL Environment Variable is Not Applying

### ISSUE THREAD

**Issue by Spittal** [cube-js/cube.js#2737]
**Describe the bug**
Hello, I've noticed that running CubeJS in docker with the docker image `cubejs/cube:v0.27.13-alpine` has a strange issue where the environment variable `CUBEJS_REDIS_URL` will not apply. 

I can confirm by connecting into the docker container while it's running that the environment variable is set, and that the container itself is able to connect to the redis instance. As you can see in the code sample and screenshot below.

![image](https://user-images.githubusercontent.com/1229177/118187844-63a3bf80-b3f4-11eb-8ff7-a07f488e57bf.png)

```
# echo $CUBEJS_REDIS_URL
10.43.195.148
# telnet $CUBEJS_REDIS_URL 6379
Trying 10.43.195.148...
Connected to 10.43.195.148.
PING
+PONG
```

Then when I attempt to make any query with this service there is this log:

```
🚀 Cube.js server (0.27.13) is listening on 4000
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

I can confirm that the environment variable is set before the server booted and the error persists through reboots of the server. Why is it attempting to connect to a local redis instance when I have set the environment variable correctly? 

**To Reproduce**
1. Boot up a CubeJS environment in production mode in Docker with the image `cubejs/cube:v0.27.13-alpine`
2. Attempt to make any query to CubeJS

**Expected behavior**
I expect the Redis connection to attempt a connection to the set CUBEJS_REDIS_URL environment variable, not 127.0.0.1

**Version:**
v0.26.102
v0.27.0
v0.27.13-alpine

(I have tried all)

**Comment by rongfengliang** [comment]
@Spittal use .env file

**Comment by Spittal** [comment]
Hey @rongfengliang thanks for the quick reply. We can certainly switch to move over to a `.env`. However, I wonder if it's possible to either fix this issue or document that in the Docker context shell environment variables don't work?

**Comment by manishgadhock-monotype** [comment]
+1, Got this same issue

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379. I have set the value of the CUBEJS_REDIS_URL different IP.

CubeJs Server version : 0.26.102

**Comment by ovr** [comment]
```
# echo $CUBEJS_REDIS_URL
10.43.195.148
```

It's not a correct value for CUBEJS_REDIS_URL, you should follow specification https://www.iana.org/assignments/uri-schemes/prov/redis

@Spittal

Can you try with `CUBEJS_REDIS_URL=redis://10.43.195.148:6379`?

Thanks

**Comment by manishgadhock-monotype** [comment]
@ovr Tried `CUBEJS_REDIS_URL=redis://<redis_ip>:6379`. Not working still have that same message.

`Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379.`

**Comment by ovr** [comment]
Attention: `CUBEJS_REDIS_URL` > `0.27`, `REDIS_URL` < `0.27`.

https://github.com/cube-js/cube.js/commit/b5e7099da90d0f8c6def0af648b45b18c1e56569

> I am passing my redis password in this CUBEJS_REDIS_PASSWORD or Do I need to pass it in URL ?

It's ok to pass the password in `CUBEJS_REDIS_PASSWORD`.

I tried it locally in docker-compose & local setup and It works. I don't have any ideas, why it's not working for you.

**Comment by manishgadhock-monotype** [comment]
@ovr Thanks, I think REDIS_URL < 0.27 worked for me. Although getting this error right now :

`ReplyError: Ready check failed: NOAUTH Authentication required.`

**Comment by manishgadhock-monotype** [comment]
My Bad. Was using CUBEJS_REDIS_PASSWORD instead of REDIS_PASSWORD. Thanks @ovr . All sorted for me.

**Comment by Spittal** [comment]
> ```
> # echo $CUBEJS_REDIS_URL
> 10.43.195.148
> ```
> 
> It's not a correct value for CUBEJS_REDIS_URL, you should follow specification https://www.iana.org/assignments/uri-schemes/prov/redis
> 
> @Spittal
> 
> Can you try with `CUBEJS_REDIS_URL=redis://10.43.195.148:6379`?
> 
> Thanks

Hey I should've mentioned in the original ticket, but I did try this as well. 

As for > 27 using the env name `CUBEJS_REDIS_HOST` I can confirm the issue still exists. I've created a simple reproduction for this.

https://github.com/Spittal/cubejs-reproduciton-env

Just clone that repo, run `docker-compose up` then wait a few moments after the server boots up (about 15-30 seconds) and you should get this: 

![image](https://user-images.githubusercontent.com/1229177/119031142-99e6bf00-b95f-11eb-8a05-c349b5eddbaa.png)

**Comment by Spittal** [comment]
Thanks for the help @ovr using `redis://` and upgrading to > 27 seems to have fixed the issue. Thanks. Might be worth documenting more clearly the need for `redis://` in the URL?
