### ISSUE TITLE
Example links - HTTP 404

### ISSUE THREAD

**Issue by QAInsights** [cube-js/cube.js#274]
**Describe the bug**
Examples link mentioned in [here](https://cube.dev/docs/examples) are throwing `HTTP 404` error.

**To Reproduce**
1. Go to [https://cube.dev/docs/examples](https://cube.dev/docs/examples)
2. Click on `examples-gallery` and `aws-web-analytics` link
3. See HTTP error

**Expected behavior**
It should display right page to the user.

**Screenshots**
NA

**Version:**
NA

**Additional context**
NA

**Comment by paveltiunov** [comment]
@QAInsights Hey Naveen! Thanks for posting this! Yep. Broken links. Would love if you can provide PR for that! Thanks!
