### ISSUE TITLE
Continue wait when using three filters with 10 values each

### ISSUE THREAD

**Issue by angelo-cavallo** [cube-js/cube.js#2748]
If I add 3 or more filters to a query, each one with 10 values, It seems that cube can't return a result set (it keeps returning a "Continue wait" error). If I add only 2 filters, it works correctly no matter how many values I specify. 
I'm using version 0.27.14 and I already built my pre-aggregations in Cube Store. 

I've verified that all the query members are in the pre-aggregation, and that the granularities match on both the query and schema.

Source database: BigQuery
External database: Cube Store

**Comment by ovr** [comment]
Hello @angelo-cavallo ,

Can you provide logs from Cube.js?

Thanks

**Comment by ovr** [comment]
There is an error in Cube Store inside `PartionFilter`, assigned to @ilya-biryukov 

![image](https://user-images.githubusercontent.com/572096/118676368-05b41500-b804-11eb-8573-697fbb9fae9a.png)

**Comment by ilya-biryukov** [comment]
Thanks for reporting this. Should be fixed when https://github.com/cube-js/cube.js/commit/f6f09923c065ac6d2b97c5cbbe42958e51dab251 lands into the docker hub.
