### ISSUE TITLE
Npm run dev - Project doesn't start (DB credentials)

### ISSUE THREAD

**Issue by danielldante** [cube-js/cube.js#275]
When trying to run the project using the npm run dev command, the following message is displayed:

"Your .env file contains placeholders in DB credentials. Please replace them with your DB credentials."

Can anybody help me?

**Screenshots**
![Captura de Tela 2019-11-25 às 16 21 23](https://user-images.githubusercontent.com/12860259/69570994-ca82ae00-0f9f-11ea-9507-8496401238fe.png)

**Comment by paveltiunov** [comment]
@danielldante Hey Danielle! Could you please try to edit your .env file and set your DB credentials there?

**Comment by danielldante** [comment]
@paveltiunov 
My .env file was successfully edited and the project started. Thanks Bro!
