### ISSUE TITLE
Support for a timeDimension dateRange preaggregation

### ISSUE THREAD

**Issue by ferrants** [cube-js/cube.js#276]
**Is your feature request related to a problem? Please describe.**
The front-end can include `dateRange` like `last week` or `['2019-10-01', '2019-10-14']`. If I'm just looking for resources and don't care about any granularity, it would be nice to use preaggregations to have this data ready, especially because my requests date ranges are very predictable.

**Describe the solution you'd like**
be able to specify a `dateRange` for a preaggregation
```
preAggregations: {
  relativeDateRollup: {
    type: 'rollup',
    measureReferences: [count],
    dimensionReferences: [source],
    timeDimensionReference: createdAt,
    dateRange: 'last week',
  },
  staticDateRollup: {
    type: 'rollup',
    measureReferences: [count],
    dimensionReferences: [source],
    timeDimensionReference: createdAt,
    dateRange: ['2017-01-05', '2017-01-06'],
  },
}
```

How does the `timezone` play into this? Should a `timezone` be specified on the preAggregation as well?

**Describe alternatives you've considered**
Using segments to achieve this. But the parsing for `last week` is really nice and it would be nice to allow this to match with the front-end and have moment.js back it instead of needing to manipulate sql `CURRENT_TIMESTAMP` to get the right values.

**Additional context**
I should be able to handle implementing this if this is the right direction.

**Comment by paveltiunov** [comment]
@ferrants Hey Matt! Thanks for posting this! Is this for performance reasons mostly? If so there's https://cube.dev/docs/pre-aggregations#rollup-time-partitioning

**Comment by ferrants** [comment]
Yes, it would be for performance reasons. The `partitionGranularity` option comes close - but it would still need to traverse multiple partitions for many queries that we run. For example:
```
relativeDateRollup: {
    type: 'rollup',
    measureReferences: [count],
    dimensionReferences: [source],
    timeDimensionReference: createdAt,
    granularity: 'month',
    partitionGranularity: 'month'
  }
```
would result in a single record for each dimension row for each month, which is great. If I query for data for the last 180 days, that will need to union 5 or 6 of those together, along with joining to ones with day granularity, which would slow things down. We know the date ranges that our customers request and we can preaggregate to that entire dateRange and only hit that date range when the query's date range matches perfectly, we should be able to have lightning-fast responses. 

I tried this with segments, but it felt kinda hacky. `segmentReferences` appears to be supported on `preAggregations`, although it doesn't seem to be documented.

**Comment by paveltiunov** [comment]
Is there a chance you can test partitioned rollups on your data set against external rollups? It's heavily tested on queries that span over 100 of partitions and it still works with subsecond responses. As soon as rollup tables can fit in memory and filter push down optimizations work it shouldn't be a problem.

**Comment by ferrants** [comment]
I haven't been able to use the external rollups effectively yet because of https://github.com/cube-js/cube.js/issues/266. I was hoping I could do the "Period Deltas" (referenced in https://github.com/cube-js/cube.js/issues/262) in a table with preaggregates like this, so I could calculate these for a period and just reference that preAggregate

**Comment by paveltiunov** [comment]
@ferrants Gotcha. So I believe for `FILTER_PARAMS` support we should either go #273 way or you can do workaround using `originalSql` https://cube.dev/docs/pre-aggregations#original-sql. You'd need just to `group by` inside cube sql. Should work well.

**Comment by paveltiunov** [comment]
Cube Store should be used for this and similar cases.
