### ISSUE TITLE
Setting from CUBEJS_JWK_KEY and CUBEJS_JWT_KEY fails

### ISSUE THREAD

**Issue by TomFreudenberg** [cube-js/cube.js#2763]
Hi,

I checked this with latest release tag and from my point of view - still wrong.

The check of ENV type is not correct.

Check at:

https://github.com/cube-js/cube.js/blob/v0.27.14/packages/cubejs-backend-shared/src/env.ts#L220-L225

```js
  jwkKey: () => get('CUBEJS_JWK_KEY')
    .asUrlString(),
  jwkUrl: () => get('CUBEJS_JWK_URL')
    .asString(),
  jwtKey: () => get('CUBEJS_JWT_KEY')
    .asUrlString(),
```

should be changed for `.asUrlString` and `.asString` as followed:

```js
  jwkKey: () => get('CUBEJS_JWK_KEY')
    .asString(),
  jwkUrl: () => get('CUBEJS_JWK_URL')
    .asUrlString(),
  jwtKey: () => get('CUBEJS_JWT_KEY')
    .asString(),
```

Currently you can't set a general KEY for microservice site to validate any JWT

always: 

<pre>
EnvVarError: env-var: "CUBEJS_JWT_KEY" should be a valid URL
</pre>

Hope that fits

Cheers,
Tom

**Comment by ovr** [comment]
Hello @@TomFreudenberg

Yes, it's a bug. We created this variable but We didn't ship it in any documentation. Probably, in the feature, we will replace `API_SECRET` with `CUBEJS_JWT_KEY `
