### ISSUE TITLE
Compression of response payloads

### ISSUE THREAD

**Issue by dylanfprice** [cube-js/cube.js#2767]
I am currently driving a menu off the meta endpoint and the payload is ~1 MB and I expect it to grow quite a bit more. Compressing the response payload from the Cube API server would help my website load a lot faster.

**Describe the solution you'd like**
I can think of a couple ideas that would both be ideal for my use case:

- Add compression to the Cube API server such that a client sending `Accept-Encoding: gzip` gets a compressed response. (`gzip` is just for example, any well-supported compression algorithm is great)
- Create a way to add Express middleware to the Cube API server. Then I could easily configure something like https://github.com/expressjs/compression myself.

**Describe alternatives you've considered**

- Putting the Cube API behind a reverse proxy which can add compression
- Storing the meta response as a static file to be served by my webserver and periodically regenerating it.

**Additional context**
https://cube-js.slack.com/archives/CC0403RRR/p1621018392463500

**Comment by rongfengliang** [comment]
@dylanfprice  one way is use nginx. another way is add express compress middware  （shrink-ray-current npm package）
demo code (use initApp for add middware)
index.js
```code
const shrinkRay = require('shrink-ray-current');
module.exports = function (app) {
    }));
    app.use(shrinkRay());
}
```

cube.js 
```code
const index = require("./index")
module.exports = {
    initApp:index,
};

```
with shrink-ray-current  i have do some test is works well . you can have a try

**Comment by vasilev-alex** [comment]
@dylanfprice thanks for posting it here! However, as it can be easily done on the Nginx side (where you can use faster algorithms, such as Brotli) it doesn't make much sense to compress it on our side using middleware.

**Comment by ovr** [comment]
@dylanfprice

Another moment: That Cube.js doesn't support HTTP 2 + TLS was removed (https://github.com/cube-js/cube.js/blob/master/DEPRECATION.md#cubejs_enable_tls), anyway you need to use a reverse proxy.

**Comment by dylanfprice** [comment]
Thank you that makes sense. I am running the Cube server inside of a Kubernetes cluster and we have a service mesh which takes care of TLS and HTTP/2. It looks like it does have the capability to compress payloads so I am talking to our DevOps engineer about whether it makes sense to enable at the cluster level.

In the meantime, @rongfengliang's approach works (thanks!!). It appears the `initApp` configuration setting in `cube.js` is undocumented, is it safe to rely on?

**Comment by rongfengliang** [comment]
> Thank you that makes sense. I am running the Cube server inside of a Kubernetes cluster and we have a service mesh which takes care of TLS and HTTP/2. It looks like it does have the capability to compress payloads so I am talking to our DevOps engineer about whether it makes sense to enable at the cluster level.
> 
> In the meantime, @rongfengliang's approach works (thanks!!). It appears the `initApp` configuration setting in `cube.js` is undocumented, is it safe to rely on?

i think current is safe . it's one server-core option
