### ISSUE TITLE
Dependency issue with dynamic react demo

### ISSUE THREAD

**Issue by gah112** [cube-js/cube.js#2769]
Running the dashboard front-end demo via the playground throws the following error:

`Module not found: Can't resolve 'graphql' in '/cube/conf/dashboard-app/node_modules/@apollo/client/core'`

I am using the following:

- Docker image: `cubejs/cube:latest`
- React dynamic dashboard
- Rechart

**Comment by vasilev-alex** [comment]
@gah112 should be fixed now. Could you please check it one more time?

**Comment by chandlj** [comment]
@vasilev-alex I have the same issue when trying to run any of the demos. Many of the dependencies are missing and even after spending several hours trying to install them all it doesn't work.
