### ISSUE TITLE
CubeJS produces invalid SQL when using filters

### ISSUE THREAD

**Issue by lihan** [cube-js/cube.js#2778]
**Describe the bug**

IF `filters` in metrics are configured, then this error could trigger in BigQuery

`SELECT list expression references column <my_column> which is neither grouped nor aggregated `

Eg..
```
filters: [
  { sql: `type = 'my_type'` }
]
```
it will produce query like
```
SELECT
  col1,
  CASE
    WHEN (type = '2') THEN expr 
  END ` myvar `
FROM table
GROUP BY 1
```
which the field `type` is not grouped

## Updates

measurement definition

```
measures: {
  conversion: {
    sql: `COUNTIF(bookings) / COUNTIF(views > 0)`,
    title: `Conversion`,
    type: `number`,
    filters: [
       { sql: `${CUBE}.subject_type = 'device` }
    ]
  }
}
```

### Walkaround

* Develop the filter as segments

**Version:**
[e.g. 0.27.13]

**Comment by igorlukanin** [comment]
It makes no sense to filter a measure with the `number` type. The filter was moved to a segment.
