### ISSUE TITLE
Error while loading DB schema

### ISSUE THREAD

**Issue by jeremysugnaux** [cube-js/cube.js#278]
Hi,

I am trying to install Cube.js, and averything works well until I access to "localhost:4000", I can access to the page but I get this error:

`Error while loading DB schema
Error: getaddrinfo ENOTFOUND <localhost> at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)`

When I add the line "CUBEJS_DB_PORT=<5432> in the .env file, I get another error:

`Error while loading DB schema
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN. at lookupAndConnect (net.js:994:13) at Socket.connect (net.js:969:5) at Connection.connect (/root/test/node_modules/pg/lib/connection.js:54:17) at Client._connect (/root/test/node_modules/pg/lib/client.js:99:9) at Client.connect (/root/test/node_modules/pg/lib/client.js:284:10) at Pool.newClient (/root/test/node_modules/pg-pool/index.js:212:12) at Pool.connect (/root/test/node_modules/pg-pool/index.js:187:10) at Pool.query (/root/test/node_modules/pg-pool/index.js:323:10) at PostgresDriver.testConnection (/root/test/node_modules/@cubejs-backend/postgres-driver/driver/PostgresDriver.js:38:30) at CubejsServerCore.getDriver (/root/test/node_modules/@cubejs-backend/server-core/core/index.js:344:20)`

I can connect to my PostgreSQL database from a client.

I tried to reinstall on another server but I get the same result.

Can anyone help me please?

Thank you

**Comment by paveltiunov** [comment]
Hey @jeremysugnaux! Could you please rid off `<` and `>` in your .env file? It's just to mark placeholders.

**Comment by jeremysugnaux** [comment]
I feel stupid, it was so simple, thank you very much!

**Comment by paveltiunov** [comment]
No probs! 🙌

**Comment by sonu16455** [comment]
Error while loading DB schema
Error: connect ETIMEDOUT at Connection._handleTimeoutError (D:\Cube.js\nodejsapi\node_modules\mysql2\lib\connection.js:169:17) at ontimeout (timers.js:436:11) at tryOnTimeout (timers.js:300:5) at listOnTimeout (timers.js:263:5) at Timer.processTimers (timers.js:223:10)

**Comment by sonu16455** [comment]
Can some help me with this error ?

**Comment by paveltiunov** [comment]
@sonu16455 Hey Ravindra! Could you please check your connection credentials in .env?

**Comment by rahulbabu25041998** [comment]
hai @paveltiunov 

can u please tell me how to connect my data in mongodb-compass with cube.js CLI.
if there is any other way to go by can you mention that too......

**Comment by vineetjio3** [comment]
I am getting an error when I install cubjs on an ECS cluster with awsvpc network mode.
Error: getaddrinfo ENOTFOUND cubestore_router
