### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by mycahp** [cube-js/cube.js#2780]
**Is your feature request related to a problem? Please describe.**
On the install of CubeJS's ng package (@cubejs-client/ngx), Cube is requiring a dependency for Angular 10.0.5:

```
npm WARN Found: @angular/core@11.2.14
npm WARN node_modules/@angular/core
npm WARN   @angular/core@"^11.2.13" from the root project
npm WARN   13 more (@ag-grid-community/angular, @angular/animations, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @angular/core@"^10.0.5" from @cubejs-client/ngx@0.27.0
npm WARN node_modules/@cubejs-client/ngx
npm WARN   @cubejs-client/ngx@"^0.27.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @cubejs-client/core@0.27.15
npm WARN node_modules/@cubejs-client/core
npm WARN   @cubejs-client/core@"^0.27.6" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @cubejs-client/core@"^0.26.60" from @cubejs-client/ngx@0.27.0
npm WARN node_modules/@cubejs-client/ngx
npm WARN   @cubejs-client/ngx@"^0.27.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: rxjs@6.5.5
npm WARN node_modules/rxjs
npm WARN   rxjs@"~6.5.3" from the root project
npm WARN   5 more (@angular/common, @angular/core, @angular/forms, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rxjs@"^6.6.0" from @cubejs-client/ngx@0.27.0
npm WARN node_modules/@cubejs-client/ngx
npm WARN   @cubejs-client/ngx@"^0.27.0" from the root project

```

A `npm install --force` allows the package to be installed and everything appears to be working correctly.

Can the dependencies be changed to at least allow Angular 11 without requiring the use of `--force`? The current version of Angular is now 12.0.0.

**Describe the solution you'd like**
Update dependencies for Cube to allow newer versions than Angular 10.

**Describe alternatives you've considered**
Using --force in the npm install, which could create issues with other dependencies. 

**Additional context**

**Comment by vasilev-alex** [comment]
hi @mycahp! Thanks for posting it here. 

We're going to support the latest Angular version in the next minor release, as Angular 10, 11, and 12 are not backward compatible.

**Comment by mycahp** [comment]
@vasilev-alex Wonderful news! Any idea on the release timeline for the next minor version?

**Comment by vasilev-alex** [comment]
@hassankhan ^^ do we have a planned date?
