### ISSUE TITLE
Security context with cubeJs.load

### ISSUE THREAD

**Issue by bilelsgh** [cube-js/cube.js#2786]
**Security context with cubeJs.load**

I would like to add a security context based on "user_id" to my cube, so for that :
   - in a web server I create a token using the "user_id" 
   - in the client I fetch it and store it in the localStorage
   - in my cube schema I add ```WHERE ${SECURITY_CONTEXT.user_id.filter(
    'user_id'
  )```

Now I have to pass the token to the http header when I make a request to the CubeJS backend, but to make my request I use the method ```CubeJsClient.load(query)```, how can I modify the header ?

Thank you

**Comment by keydunov** [comment]
Hi @bilelsgh,

It would be great to use [StackOverflow](https://stackoverflow.com/questions/tagged/cube.js) with `cube.js` for questions in the future. 

Re: your question --

When you initiate a Cube.js client instance you pass a token to the `cubejs()` function. You don't need to directly modify the header. It will use this token to sign all future requests.

```
const cubejsApi = cubejs(
  'CUBEJS-API-TOKEN',
  { apiUrl: 'http://localhost:4000/cubejs-api/v1' }
);

cubejsApi.load(query) // will be signed with the above token
````

**Comment by bilelsgh** [comment]
Hi @keydunov ,

Thanks for your answer, next time I will ask it on Stackoverflow ;)

Have a nice day.
