### ISSUE TITLE
Error: Cannot find module '@cubejs-backend/shared'

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube.js#2788]
**Describe the bug**

 @cubejs-backend/schema-compiler missing @cubejs-backend/shared in package.json

 ear and concise description of what you expected to happen.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/2312287/118961972-7a6b8880-b997-11eb-9613-f2aedb0233a9.png)

**Version:**
[e.g. 0.27.15]

**Comment by ovr** [comment]
Hello @rongfengliang ,

Good catch 👍  Fixed in https://github.com/cube-js/cube.js/commit/3467b4472e800d8345260a5765542486ed93647b#diff-f6e4a5552327e130224cbe8560aba23f947533db54134e6d3d3c3a9d0ff15448R45

Thanks
