### ISSUE TITLE
Hide measures or dimensions per user goups

### ISSUE THREAD

**Issue by mhd-adam** [cube-js/cube.js#2797]
**Problem**
Hi guys, it has been a really great journey with CubeJS so far. I am wondering if there is a way to restrict access to measures based on user groups or any other criteria? For example, we have a cube with 5 measures, only 2 of them should be available for all users whereas the other 3 should be available to admin users only! My concern is that the `/meta` endpoint exposes all measures clearly to anyone and this way anyone can get access to any measure.

**Comment by rongfengliang** [comment]
@mhd-adam  i think you maybe need  multi-tenant setup

**Comment by mhd-adam** [comment]
Thanks @rongfengliang , would it help in **hiding** the measures from `/meta` endpoint for a group of users?

**Comment by rongfengliang** [comment]
yes.

**Comment by paveltiunov** [comment]
Hey @mhd-adam ! This would be possible with #2145.
