### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by dtslvr** [cube-js/cube.js#28]
Hi all,

As quickly discussed with @paveltiunov in Slack, it would be awesome to support _TypeScript_ for _Cube.js_. This can be achieved by adding a declaration file and bundling it with the npm package. Here you can find more [information](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

Thanks a lot and keep up the great work!

**Comment by paveltiunov** [comment]
Thanks for posting this!

@dtslvr What classes do think should be declared there?

**Comment by dtslvr** [comment]
Most important are the public APIs:
* `@cubejs-client/core` (class `CubejsApi`)
* `@cubejs-backend/server-core` (class `CubejsServerCore`)

**Comment by dtslvr** [comment]
I have created a pull request https://github.com/statsbotco/cube.js/pull/111 with typings for `@cubejs-backend/server-core`. It's a starting point, please check if it's also working with your _Cube.js_ integration. Thanks!
