### ISSUE TITLE
Snowflake driver error: cannot find module './dist/src'

### ISSUE THREAD

**Issue by RobWilliamBellamy** [cube-js/cube.js#2809]
**Describe the bug**
Creating a project with the snowflake driver displays the error: 

> Error: Cannot find module './dist/src'
> Require stack:
> - /Users/robert.bellamy/Code/test/node_modules/@cubejs-backend/snowflake-driver/index.js

**To Reproduce**
1) Run: npx cubejs-cli create cube-snowflake -d snowflake

**Expected behavior**
Cube.js project with snowflake driver to be createfd

**Version:**
Latest

**Comment by ovr** [comment]
Hello!

Thank you for submitting an issue. Yeah, it's a bug. 

Should be fixed in latest release `v0.27.19` https://github.com/cube-js/cube.js/commit/cd2c90f51bd02cd9b918c64e116207b75af95d3d

Thanks
