### ISSUE TITLE
No way to order without selecting

### ISSUE THREAD

**Issue by ifokeev** [cube-js/cube.js#282]
**Describe the bug**
There is no way to send `order` without selecting the measure/dimension. Looks strange

this function is about the order
https://github.com/cube-js/cube.js/blob/1a8260522a234ebaabb9360f58e9b62095fd87f7/packages/cubejs-schema-compiler/adapter/BaseQuery.js#L771

**Expected behavior**
expected to see order if it's not added in select

**Version:**
0.11.18

**Comment by paveltiunov** [comment]
@ifokeev Hey Ivan! Thanks for posting this! Do you expect to see dimension added to group by if it's missing in dimension list as well?

**Comment by ifokeev** [comment]
@paveltiunov No. I'm expecting to see the order only.

**Comment by paveltiunov** [comment]
@ifokeev Makes sense. What SQL do you expect it to generate?

**Comment by ifokeev** [comment]
@paveltiunov 
if query is:
```
measures: [],
dimensions: ['TestCube.dimension1', 'TestCube.dimension2'],
timeDimensions: [],
filters: [],
segments: [],
order: {"TestCube.index":"asc"}
```

then sql should be:

```
SELECT dimension1, dimension2 FROM table GROUP BY 1, 2 ORDER BY index
``` 

Now we have that case: select some dimensions and order the result by id

**Comment by paveltiunov** [comment]
@ifokeev The thing is most of SQL backends will respond with an error to such SQL:
```
column "table.index" must appear in the GROUP BY clause or be used in an aggregate function
```
There're some exceptions to this but in general you can't order `GROUP BY` clause without selecting grouped column. We can order before group by but most of databases wouldn't save this order either due to implementation specifics of `GROUP BY`.

**Comment by ifokeev** [comment]
@paveltiunov yeah, my fault with the query. I see.

I'm understanding your first question now.
So is it the right case to use `GROUP BY` if there is no aggregation function?

**Comment by paveltiunov** [comment]
@ifokeev Yep. For most analytics use cases it is correct approach. You can check if `ungrouped` fits your needs here: https://cube.dev/docs/query-format#query-properties.

**Comment by ifokeev** [comment]
@paveltiunov ok then I'll try. Thanks!
