### ISSUE TITLE
BigQuery driver error: cannot find module './dist/src' 

### ISSUE THREAD

**Issue by beefs** [cube-js/cube.js#2843]
**Describe the bug**
Creating a project with the BigQuery driver displays the error:

> Error: Cannot find module './dist/src'
> Require stack:
> - /Users/s/cube-bigquery/node_modules/@cubejs-backend/bigquery-driver/index.js
> - /Users/s/.npm/_npx/55017/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/shared/dist/src/package.js
> - /Users/s/.npm/_npx/55017/lib/node_modules/cubejs-cli/node_modules/@cubejs-backend/shared/dist/src/index.js
> - /Users/s/.npm/_npx/55017/lib/node_modules/cubejs-cli/dist/src/command/proxy-command.js
> - /Users/s/.npm/_npx/55017/lib/node_modules/cubejs-cli/dist/src/command/server.js
> - /Users/s/.npm/_npx/55017/lib/node_modules/cubejs-cli/dist/src/cli.js
> - /Users/s/.npm/_npx/55017/lib/node_modules/cubejs-cli/dist/src/index.js

**To Reproduce**
1. exec: npx cubejs-cli create cube-bigquery -d bigquery

**Expected behavior**
Cube.js project with bigquery driver to be created.

**Screenshots**
N/A

**Version:**
0.27.22

**Additional context**
No

**Comment by ovr** [comment]
Hello @beefs ,

Thank you for submitting an issue. Yes, it's a bug, fixed in `v0.27.23` via https://github.com/cube-js/cube.js/commit/8b8c10b94a99aca4ce26aab231d0379d434f88f6
