### ISSUE TITLE
dateRange 'Next 7 days'

### ISSUE THREAD

**Issue by chamabreu** [cube-js/cube.js#2866]
**Describe the bug**
If I pass 'Next 7 days' into the dateRange in query, the response is not a range over the next 7 days but only the day IN 7 days.

**To Reproduce**
1. Build a query like this:
```
const query: Query = {
    measures: [
      measure
    ],
    timeDimensions: [
      {
        dimension: 'Your.Dimension,
        dateRange: 'Next 7 days'
      }
    ]
  }
```
2. Send the request to CubeJS Api and watch the resultset timeDimension array. It returns not a dateRange over 7 days but only the one day in 7 days:
```
["2021-06-08T00:00:00.000", "2021-06-08T23:59:59.999"]
```

**Expected behavior**
Like the option to get the 'Last 7 days' like [here](https://cube.dev/docs/query-format#time-dimensions-format).
This gives me an timeDimension Array of
```
["2021-05-25T00:00:00.000", "2021-05-31T23:59:59.999"]
```
The actual "last 7 days", and not the "one day 7 days ago".

**Version:**
0.27.14

Maybe there is not such an option 'Next 7 days'. I tried also '7 days from now' and other stuff.
Am I missing something?

**Comment by chamabreu** [comment]
Just found a solution that works:
`'from now to 7 days from now'`
gives me the expected result of 
`["2021-06-01T00:00:00.000", "2021-06-08T23:59:59.999"]`.

It's a solution, but I think 'Next 7 days' should work if 'Last 7 days' work, too.

**Comment by imrishabh18** [comment]
@vasilev-alex Can I take up this issue?

**Comment by JoshMentzer** [comment]
@imrishabh18 Hey, I apologize - I worked this locally to fix an issue internally at my company and then came to do a PR up and noticed you had requested to work this issue; sorry for not checking ahead of time!
