### ISSUE TITLE
Can't cleanup async effects using useCubeQuery hook 

### ISSUE THREAD

**Issue by SergiuszMinsk** [cube-js/cube.js#2869]
**Describe the bug**
I'm using the useCubeQuery hook with React to make 4 requests on each of my pages. When I change the page from current to another one immediately, React tries to update the state of an already unmounted component in case of an incomplete request, it leads to a React warning:  ``` Warning: Can't perform a React state update on an unmounted component.```

**To Reproduce**
1. Go to Page1 with some useCubeQuery requests
2. Change the page to Page2 immediately
3. See the console error

**Expected behavior**
It's possible to clean up async effects in case of an unmounted component

**Screenshots**
![screen](https://user-images.githubusercontent.com/18442677/120296253-3a29d580-c2c8-11eb-91d6-9b20bb57e303.png)

**Version:**
[0.26.73]

**Comment by vasilev-alex** [comment]
@SergiuszMinsk actually, we do have this check in place https://github.com/cube-js/cube.js/blob/d72baf4ef39d89be986f51941629def0975c989f/packages/cubejs-client-react/src/hooks/cube-query.js#L62

As I can see from the error message you've provided this warning comes from the `ResizeableChartContainer` component.

**Comment by SergiuszMinsk** [comment]
@vasilev-alex, looks like this warning caused by another ```useEffect``` in the domain component (in my case inside of critical tickets where all async operation happens). Actually, I followed this pattern - https://github.com/cube-js/cube.js/blob/master/examples/highcharts/dashboard-app/src/components/Dashboard.js#L140

**Comment by vasilev-alex** [comment]
@SeekingMeaning so, do you confirm that the warning comes from some other component and not from the `useCubeQuery` hook?

**Comment by SergiuszMinsk** [comment]
@vasilev-alex , yes, I confirm it as we have ```isMounted``` ref inside the ```useCubeQuery``` hook to prevent the state from the update in case of an unmounted component.

**Comment by SergiuszMinsk** [comment]
@vasilev-alex , I confirm it.
