### ISSUE TITLE
Unable to create a cube project using npx in cli

### ISSUE THREAD

**Issue by surajlifeean** [cube-js/cube.js#2874]
While I am trying to get a cube project created using npx and running the command 
npx cubejs-cli create spark-cubejs -d mssql
in the terminal I am getting the issues specified below.

`- Installing server dependencies
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> @cubejs-backend/cubestore@0.27.25 postinstall C:\test\spark-cubejs\node_modules\@cubejs-backend\cubestore
> node bin/post-install

Cube.js Cube Store Installer ---------------------------------------

RequestError [HttpError]: request to https://api.github.com/repos/cube-js/cube.js/releases/tags/v0.27.25 failed, reason: read ECONNRESET
    at C:\test\spark-cubejs\node_modules\@octokit\request\dist-src\fetch-wrapper.js:91:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at fetchRelease (C:\test\spark-cubejs\node_modules\@cubejs-backend\cubestore\js-wrapper\download.ts:22:20)
    at Object.downloadBinaryFromRelease (C:\test\spark-cubejs\node_modules\@cubejs-backend\cubestore\js-wrapper\download.ts:59:19)
    at C:\test\spark-cubejs\node_modules\@cubejs-backend\cubestore\js-wrapper\post-install.ts:12:7 {
  status: 500,
  headers: {},
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/cube-js/cube.js/releases/tags/v0.27.25',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.4.0 Node.js/14.17.0 (win32; x64)'
    },
    request: { hook: [Function: bound bound register] }
  }
}

Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @cubejs-backend/cubestore@0.27.25 postinstall: `node bin/post-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @cubejs-backend/cubestore@0.27.25 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ukrcsjeswara\AppData\Roaming\npm-cache\_logs\2021-06-01T11_52_23_868Z-debug.log

Cube.js Error ---------------------------------------

Error: npm install --save-dev @cubejs-backend/server failed with exit code 1
    at ChildProcess.<anonymous> (C:\Users\ukrcsjeswara\AppData\Roaming\npm-cache\_npx\1960\node_modules\cubejs-cli\src\utils.ts:14:16)
    at ChildProcess.emit (events.js:376:20)
    at ChildProcess.cp.emit (C:\Users\ukrcsjeswara\AppData\Roaming\npm-cache\_npx\1960\node_modules\cubejs-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)`

**Screenshots**
![image](https://user-images.githubusercontent.com/23061145/120321895-bd085b80-c2db-11eb-868a-dc49a35ab099.png)

**Comment by ovr** [comment]
Hello @surajlifeean,

> `reason: read ECONNRESET`
> `status: 500,`

"ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. I think there was a problem with GitHub. Can you try again? Thanks

I tried, works as expected.

![image](https://user-images.githubusercontent.com/572096/120354442-189e0d80-c30b-11eb-9a13-8dd2a7149ad7.png)

**Comment by surajlifeean** [comment]
Tried several times.. Issue persist. 😞

**Comment by surajlifeean** [comment]
> Hello @surajlifeean,
> 
> > `reason: read ECONNRESET`
> > `status: 500,`
> 
> "ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. I think there was a problem with GitHub. Can you try again? Thanks
> 
> I tried, works as expected.
> 
> ![image](https://user-images.githubusercontent.com/572096/120354442-189e0d80-c30b-11eb-9a13-8dd2a7149ad7.png)

This doesn't work. Can you suggest me something to troubleshoot better.

**Comment by rongfengliang** [comment]
@surajlifeean  try disable install cubestore with `CUBESTORE_SKIP_POST_INSTALL=true  npx cubejs-cli create spark-cubejs -d mssql `

**Comment by surajlifeean** [comment]
Is guess there is something wrong. I am getting this issue:
![image](https://user-images.githubusercontent.com/23061145/120509383-5c9f1a00-c3c0-11eb-999f-a228b7d85227.png)

**Comment by ovr** [comment]
@surajlifeean you can use `set CUBESTORE_SKIP_POST_INSTALL=true` before `npx cubejs-cli create spark-cubejs -d mssql`

**Comment by surajlifeean** [comment]
> @surajlifeean
> 
> you can use `set CUBESTORE_SKIP_POST_INSTALL=true` before `npx cubejs-cli create spark-cubejs -d mssql`
> 
> Are you able to open `https://api.github.com/repos/cube-js/cube.js/releases/tags/v0.27.25` in your browser? Do you proxy on your computer?

This worked for me. Thanks a lot :) . I was able to access the link from the browser and there is a proxy I am trying to use it in my office laptop for a project.  Can you please explain me the reason and how the solution you gave worked. I am new to this and would love to learn more and contribute to the cuje js community :)
