### ISSUE TITLE
Catch responses being sent to the client

### ISSUE THREAD

**Issue by mhd-adam** [cube-js/cube.js#2885]
**Problem**

I want to be able to hide CubeJs error messages and replace them with my custom messages. I am trying to hook up middleware to catch any errors before being sent to the client, but it does not seem to be the right way as it does not catch the error.

When I try to query a measure that is not listed in the data model
```query={"measures":["random_measure"]}```
it returns this response

``{
    "error": "Invalid query format: child \"measures\" fails because [\"measures\" at position 0 fails because [\"0\" with value \"random_measure\" fails to match the required pattern: /^[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+$/]]"
}``

I would like to replace this message with another one

**Comment by vasilev-alex** [comment]
Hi @mhd-adam! What about customizing error messages on the client?

```js
const { resultSet, error } = useCubeQuery({ measures: ['Wrong.measure' ]});

// or

try {
  const res = await cubejsApi.load({ measures: ['Wrong.measure' ]});
} catch (error) {
  console.log('Custom error', error);
}
```
