### ISSUE TITLE
Cross-partition Cubestore preAggregate queries are failing during planning.

### ISSUE THREAD

**Issue by zpencerq** [cube-js/cube.js#2900]
**Describe the bug**
I have a rollup preAggregation of `{granularity: day, partitionGranularity: month, external: true}` with CubeStore configured with S3 storage (the upstream datasource is Snowflake). When querying with a filter on a particular day, everything works as expected.

However, if my query crosses a month boundary (for example, `timeDimension: dateRange: ["2021-03-20","2021-04-02"]`), I reliably get `Internal: Error during planning: UNION ALL schemas are expected to be the same`. The separate queries of dateRanges within each month work just fine; it's just the partial cross-month queries are getting this error.

**To Reproduce**
1. Create external preAggregation with granularity `day` and partitionGranularity `month`.
2. Query a `dateRange` that includes the start of a month. (ie. `dateRange: ["2021-03-20", "2021-04-02"]`)

**Expected behavior**
The query completes successfully and returns the appropriate results.

**Version:**
v0.27.29

**Additional context**
* Using Snowflake as default datasource
* `CUBEJS_EXTERNAL_DEFAULT=true`
* `CUBEJS_EXT_DB_TYPE=cubestore`
* `CUBESTORE_S3_*` values are set.

From: https://cube-js.slack.com/archives/C0206EXEVAS/p1622751401071900

**Comment by ovr** [comment]
Hello @zpencerq ,

Could you try with `v0.27.30`? Should be fixed via https://github.com/cube-js/cube.js/commit/a99977a11a2ae3029d3c2436b7d1500f7186a687

Thanks

**Comment by zpencerq** [comment]
Works for me 👍
