### ISSUE TITLE
Generating schema files using Azure SQL Database, primary keys are not generated

### ISSUE THREAD

**Issue by ecolara3** [cube-js/cube.js#2919]
**Describe the bug**
When I generate Schemas against an Azure SQL Database, primary keys are not generated for any of the cubes

**To Reproduce**
1. Create Sample Azure SQL Database using Free Tier with Azure (simple instructions to create [here](https://www.sqlshack.com/create-an-azure-sql-database-with-built-in-sample-data/))
2. Create a local cube project (followed these instructions [link](https://cube.dev/docs/getting-started/nodejs))
3. Run cubejs and go to schemas in playground
4. Select all tables and generate schemas

**Expected behavior**
Primary keys are generated in schemas

**Screenshots**
![image](https://user-images.githubusercontent.com/3268879/121135612-4e0a9580-c7fa-11eb-9db1-45efafa943b3.png)

**Version:**
0.27.30

**Additional context**
I have used CubeJS with an AWS RDS instance and it worked fine minus a few schemas not generating correctly, but CubeJS was able to create the primary keys. So I am not sure why when using CubeJS with an Azure SQL Database instance would be any different.

I tried looking at the CubeJS repo to see if there was something I could do to debug this for you guys. But I don't understand the code base and where the logic is to generate schemas.

Here is a pdf of the Database Diagram, the PKs are for sure there: 
[DBDiagramofAzureSQLDatabase.pdf](https://github.com/cube-js/cube.js/files/6614153/DBDiagramofAzureSQLDatabase.pdf)

**Comment by MarkGStacey** [comment]
I'll note that this behaviour is also present in MS SQL server

**Comment by ecolara3** [comment]
I pulled down the code and ran it locally to debug the situation and it seems to be working fine now. I am not sure what the issue was over the last few weeks, but this issue is resolved with the latest release 0.27.42
