### ISSUE TITLE
schemaVersion called with the wrong authInfo

### ISSUE THREAD

**Issue by willhausman** [cube-js/cube.js#294]
If I have an existing schema and pass a value in my request which should be used to trigger a schema recompile, the new value is not present.

Server:
```javascript
const server = new CubejsServer({
  contextToAppId: ({ authInfo }) => `${authInfo.tenantId}`,
  schemaVersion: ({ authInfo }) => {
    console.log(`id: ${authInfo.tenantId}, schemaVersion: ${authInfo.schemaVersion}`);
    return `${authInfo.schemaVersion}`;
  }
});
```
Two users from different tenants request data.  After the first request, an environmental event causes the schemaVersion to change.
```javascript
const values1 = { tenantId: 123, schemaVersion: 1 };
const values2 = { tenantId: 456, schemaVersion: 2 };
const values3 = { tenantId: 123, schemaVersion: 2 };
```

Output from schemaVersion's console.log():
```
id: 123, schemaVersion: 1
id: 456, schemaVersion: 2
id: 123, schemaVersion: 1
```

Expected output:
```
id: 123, schemaVersion: 1
id: 456, schemaVersion: 2
id: 123, schemaVersion: 2
```

**Analysis of the problem**

cubejs-server-core index.js:
```javascript
  getCompilerApi(context) {
    const appId = this.contextToAppId(context);
    let compilerApi = this.compilerCache.get(appId);
    if (!compilerApi) {
      compilerApi = this.createCompilerApi(
        this.repositoryFactory(context), {
          dbType: (dataSourceContext) => this.contextToDbType({ ...context, ...dataSourceContext }),
          externalDbType: this.contextToExternalDbType(context),
          schemaVersion: this.options.schemaVersion && (() => this.options.schemaVersion(context)),
          preAggregationsSchema: this.preAggregationsSchema(context)
        }
      );
      this.compilerCache.set(appId, compilerApi);
    }
    return compilerApi;
  }
```
`(() => this.options.schemaVersion(context))` is a cached closure.

cubejs-server-core CompilerApi.js:
```javascript
  async getCompilers() {
    let compilerVersion = (
      this.options.schemaVersion && this.options.schemaVersion() ||
      'default_schema_version'
    ).toString();
```
`getCompilers()` is called per-request to load data.  The same cached closure is used for `this.options.schemaVersion()`.

**This is a problem because...**
1. Documentation for cubejs suggests `schemaVersion` will cause recompiles if it changes.  `schemaVersion` can't change if it is based on the request itself.
2. I want to dynamically generate schemas per user to add custom logic like column-level security before the schema is compiled by cubejs.

**My current workaround**
```javascript
const server = new CubejsServer({
  contextToAppId: ({ authInfo }) => `${authInfo.tenantId}-${authInfo.schemaVersion}`,
  contextToDataSourceId: ({ authInfo }) => `${authInfo.tenantId}`
});
```
Abusing the server-core's LRU cache works nicely for forcing recompiles, but it means I need to also override `contextToDataSourceId`.  I would not have known this if it was not pointed out to me.

**Desired usage**
```javascript
const server = new CubejsServer({
  contextToAppId: ({ authInfo }) => `${authInfo.tenantId}`,
  schemaVersion: ({ authInfo }) => `${authInfo.schemaVersion}`
});
```

**Comment by paveltiunov** [comment]
@willhausman Thanks for posting this! I believe main misconception is `schemaVersion` can use `context` to retrieve version. Actually it wasn't designed to do so. Original idea was that `schemaVersion` should make additional requests in order to retrieve version using context information. We can make it either `async` or update schemaVersion for `CompilerApi` on each request so `CompilerApi` can always have recent version.

**Comment by willhausman** [comment]
Semantics, but the end result is the same. If `schemaVersion` is called with `context`, I expect the `context` to be the current `context`, not an old one.  Changing to `async` does not resolve this because it is a hook for customization. It is ultimately my responsibility as a developer to deliver a usable string, based on a `context` which came from my request. I might make an external request, or I might not.

With regards to PR #293, I think moving the call into the cache key for all `CompilerApi`s solves two birds with one stone.  The `context` called is now correct, and developer usage is simplified. Personally, I would completely remove recompiling from `CompilerApi`'s functionality and just manage the cache-key for recompiling and `devServer`.

I think this because my first PR had exactly what you describe.  `schemaVersion` on `CompilerApi` was kept up to date per request.  But, I needed a *lot* of `schemaVersions`, so the LRU cache was needed.  Putting my `schemaVersion` into the cache key for `CompilerApi` meant I now had to manage the cache key for `OrchestratorApi`.  It's all one big circle.

My hope is that other developers who wish to dynamically generate schemas with cubejs can do so with greater clarity.

**Comment by paveltiunov** [comment]
@willhausman I believe we should separate these two scenarios:
1. Multiple schemas should exists simultaneously.
2. Keep one schema up-to-date over time.

For the first case there's `contextToAppId`. For the second one there's `schemaVersion`. 

Some of our high throughput environments depend on `schemaVersion` behavior a lot: it's inevitable optimization where you should support a lot of frequently changing schemas without evicting others. Moreover you actually propose approach which can be done using `contextToAppId` API only as you mentioned in workaround solution. I believe we can just put additional info and examples in docs to clarify it and difference between `contextToAppId` and `schemaVersion`. We can also always pass most recent `context` to `schemaVersion` but we need to save existing memory management behavior.

**Comment by willhausman** [comment]
@paveltiunov Good clarification.  I'll adjust that PR to pass current `context` to `schemaVersion`.  That's not hard to do, fortunately.
