### ISSUE TITLE
Mistake in the documentation : CUBEJS_DB_PULL_TIMEOUT

### ISSUE THREAD

**Issue by nmathon** [cube-js/cube.js#2942]
**Describe the bug**

According to the code, the environment variable to set the DB timeout should be CUBEJS_DB_POLL_TIMEOUT but in the documentation CUBEJS_DB_PULL_TIMEOUT is written (POLL/PULL)
https://github.com/cube-js/cube.js/blob/6a7923de967abca3523887544f6a3c86d22647db/docs/content/Configuration/Environment-Variables-

**Version:**
0.27.30

**Comment by hassankhan** [comment]
Thanks for reporting the issue @nmathon 🙌
