### ISSUE TITLE
QueryBuilder makes filters unique by member rather than unique by a combination of member and operator

### ISSUE THREAD

**Issue by rdwoodring** [cube-js/cube.js#2948]
**Describe the bug**
When using the QueryBuilder component the filters parameter passed to the render prop function makes filters unique by member, even though the backend querying supports multiple filters on the same member. The use case here would be filtering on something like "users company contains 'limited'" and "users company notContains 'cubilia'". 

**To Reproduce**
1. Stand up a Cube.js backend
2. Create a React front-end. 
3. Using the QueryBuilder component, try to add a filter on a member that already has a filter applied (see [this Gist for an example](https://gist.github.com/rdwoodring/57118f14f48b41a1bc6dfe9a759875e1))

**Expected behavior**
Multiple filters on the same member should be allowed. Filters should be unique based on member and operator, i.e. if I try to add two filters for "Users.company contains", they should be de-duped. Adding a new filter for "Users.company notContains" when there is already a filter for "Users.company contains" is a valid use-case. In fact, hard-coding such a query works perfectly fine and the Cube.js backend happily returns a result set.

**Version:**
0.27.31

**Additional context**
- Sample repo can be pulled at [https://github.com/rdwoodring/cubejs-postgres-querybuilder-defect](https://github.com/rdwoodring/cubejs-postgres-querybuilder-defect)
- This behavior can also be reproduced right in the Cube.js playground if you try to add a new filter for the same member on which you are already filtered
- Relevant lines seem to be [here, in QueryBuilder](https://github.com/cube-js/cube.js/blob/f87b5ea8cbd7c144d9cf152eced8b43c8154bb72/packages/cubejs-client-react/src/QueryBuilder.jsx) where the filters are de-duped using ramda `uniqBy`

**Comment by PieterVanZyl-Dev** [comment]
Caught this issue as well while trying to do the same with angular, works manually though.

**Comment by rdwoodring** [comment]
@vasilev-alex is this something that needs some discussion and planning, or is this something you'd be looking for a PR on?

**Comment by vasilev-alex** [comment]
@rdwoodring it's in the backlog, but we're open to accepting a PR, of course.
