### ISSUE TITLE
RefreshWorker does not work for Cube query with FILTER_PARAMS

### ISSUE THREAD

**Issue by jmadan** [cube-js/cube.js#2955]
**Describe the bug**
ScheduledRefreshWorker fails to pass FILTER_PARAMS value to Cube Query. It is undefined and is replaced by 1=1 in query.

To Reproduce

Create a cube that uses FILTER_PARAMS and preaggregations with scheduled refresh, e.g.:

```
cube(``MyCube``, {
    sql: ``SELECT * from orders where '${FILTER_PARAMS.MyCube.date.filter("date")}' as orders``,
    measures:{
        one:{
            sql: '1',
            type: 'number'
        }
    },
    dimensions:{
        orderid:{
            sql: 'orderId',
            type: 'string'
        },
       orderDate:{
            sql: 'orderDate',
            type: 'time'
       },
    },
    preAggregations:{
        dummy: {
            type: 'rollup',
            external: true,
            measureReferences: [
              impressions,
              measuredImpressions,
              sumOfAttentionTimeInSeconds,
            ],
      dimensionReferences: [orderId],
      timeDimensionReference: orderDate,
      granularity: ``day``,
      partitionGranularity: ``week``,
      scheduledRefresh: true,
      refreshKey: {
        every: "1 day",
        incremental: true,
        updateWindow: `7 day`,
      },
        }
    }
})
```
In CubeJS set the 
```
scheduledRefreshContexts: async () => [
   {
      orderDate: "Select CURRENT_DATE()",
   }
  ],
```

**To Reproduce**
1. Start the CubeJs Server
2. Let the pre-aggregation worker kick in
3. In Logs you can see that query generated would be 'Select * from (Select [column_names...] from orders where 1=1)'

This fails on partitioned table in BigQuery as filter on partitioned column is required in all queries for partition elimination

**Expected behavior**
orderDate from scheduledRefreshWorkerContext should be passed in for the FILTER_PARAMS value or it should execute custom sql defined in refreshKey block of pre-aggregations

**NOTE**
I tried with having following as refreshKey block
```
refreshKey: {
        sql: `Select MAX(orderDate) from orders where orderDate = CURRENT_DATE()`
      },
```
Refresh Worker does not change the query it executes. It still tries to execute the same query which is 
`Select max(orderDate, 'UTC') from (SELECT * from orders where 1=1 as orders) and Select min(orderDate, 'UTC')` from `(SELECT * from orders where 1=1 as orders)`

**Version:**
@cubejs-backend/api-gateway 0.27.32
@cubejs-backend/bigquery-driver 0.27.32
@cubejs-backend/postgres-driver 0.27.32
@cubejs-backend/server 0.27.32

This impacts CubeStore as well.

**Comment by HJ29** [comment]
not sure if this is just a typo when u are writing this issue.
you don't have "date" dimension, your time dimension is "orderDate"
change `FILTER_PARAMS.MyCube.date.filter("date")` to `FILTER_PARAMS.MyCube.orderDate.filter("orderDate")`

**Comment by hassankhan** [comment]
@jmadan Can you confirm if @HJ29's suggestion worked for you?

**Comment by cassie-ying** [comment]
Hi @hassankhan,  I'm experiencing the same issue here. When I have FILTER_PARAM  in cube sql definition, preaggregation sql generated by cubejs Refresher Worker doesnt pick up values from FILTER_PARAM, instead it always return 1=1 for some reason. 

A minimum version to repoduce (took directly from the documentation)
```
cube(`Orders`, {
  sql: `select * from visitors WHERE ${FILTER_PARAMS.visitors.created_at.filter(
    'created_at'
  )}`,

  preAggregations: {
    main: {
      type: `originalSql`,
      timeDimensionReference: created_at,
      partitionGranularity: `month`,
      refreshKey: {
        every: `1 day`,
        incremental: true,
        updateWindow: `7 day`,
      },
    },
  },
});
```
Refresh Worker outputs:
```
Executing Load Pre Aggregation SQL: scheduler-44317b8a-790c-48cf-8eb3-243e483425f1 
--
  CREATE TABLE dev_pre_aggregations.orders_main20210729_dhoxmhkl_5llnspur_1gg4t9n AS SELECT * FROM visitor where 1 = 1
--
```

It seems like that cubejs loves to just capture a lot of "unexpected/unwanted cases" and return "1 = 1" without warning users,  cube.js/packages/cubejs-schema-compiler/src/adapter/BaseQuery.js

@cubejs-backend/server 0.28.8

**Comment by jkvgo** [comment]
@cassie-ying I got this to work. Same as the solution mentioned above your FILTER_PARAMS should use the Cube name and then should use the dimension name. That worked for me. So what you can do is something like
`FILTER_PARAMS.Orders.createdAt.filter('created_at')` assuming your dimension for column/field created_at is `createdAt`

**Comment by jkvgo** [comment]
That being said, the refresh worker does not seem to be updating my partitioned pre-aggregations though. I'm using the normal `refreshKey` and not the incremental refresh. Strangely in my local it seemed to work fine and immediately generated the partitioned but when deployed in other environments. It doesn't seem to work.

**Comment by cassie-ying** [comment]
@jkvgo, my FILTER_PARAMS works fine outside of preaggregation. It is only when it's inside preaggregation, it was interpreting as "1 = 1".

**Comment by igorlukanin** [comment]
@jmadan IDK if this question was resolved or answered anywhere else but let me answer it anyway.

In the example that you're showing in the original post, it would help to remove `FILTER_PARAMS` from your cube's `sql` definition while still having an `inDateRange` filter specified in your queries. This will allow the pre-aggregations to build.

The issue is that a refresh worker is run asynchronously and without any query context. It means that no `FILTER_PARAMS` are present for a refresh worker, so it cannot use them while evaluating the data schema.

Using `scheduledRefreshContexts` solves a similar but not the same problem. Again, a refresh worker is run asynchronously and without any query context. It also means that the security context passed with JWTs is not present for a refresh worker. So, `scheduledRefreshContexts` is a way to provide a security context (or contexts). However, security contexts and `FILTER_PARAMS` are, indeed, different features in Cube.

**Comment by igorlukanin** [comment]
@cassie-ying The approach with removing `FILTER_PARAMS` from your cube's `sql` definition should work for you as well. Please feel free to reopen this issue if you need any further assistance.

**Comment by cassie-ying** [comment]
> @cassie-ying The approach with removing `FILTER_PARAMS` from your cube's `sql` definition should work for you as well. Please feel free to reopen this issue if you need any further assistance.

Many thanks for the detailed explanation, that is very helpful.
