### ISSUE TITLE
How can I pass request information to server when using external auth token?

### ISSUE THREAD

**Issue by willhausman** [cube-js/cube.js#296]
I have an auth token for communicating with my microservices. When a user requests data, the request goes to cubejs with my auth token. I override `checkAuth` to verify my custom token.  In `repositoryFactory`, I can use my auth token again to communicate with a microservice.  Since I can't change this token, how can I pass additional parameters to the server from `cubejs-client-core` and have them show up in `repositoryFactory`?

I currently call the API directly without `cubejs-client-core` and pass extra query parameters.  The only place I found to grab those parameters was in the `authInfo` returned by `checkAuth`.  But, my parameters are not based on auth, they are based on page navigation. It feels like a hack, not an extension.

**Comment by paveltiunov** [comment]
@willhausman You can use custom headers for that: 
```javascript
import cubejs, { HttpTransport } from '@cubejs-client/core';

const cubejsApi = cubejs({
  transport: new HttpTransport({ authorization: CUBEJS_TOKEN, apiUrl: 'http://localhost:4000/', headers: { 'custom-header': 'value' } })
});
```

**Comment by krystian50** [comment]
@paveltiunov is it possible to completely remove CUBEJS_TOKEN and use custom authorization? I'm using auth0 for auth. It doesn't make a lot of sense to keep CUBEJS_TOKEN in that case.
