### ISSUE TITLE
deprecated and missing variable - serverless template

### ISSUE THREAD

**Issue by lucasortigoso** [cube-js/cube.js#2970]
Hi there,

First, congratulations! Cube.js is a really amazing platform! 

I found two issues on serverless.yml template:
- Missing variable CUBEJS_AWS_S3_OUTPUT_LOCATION
- Deprecated variable on line 107: REDIS_URL -> CUBEJS_REDIS_URL

https://github.com/cube-js/cube.js/blob/2c1e150ce70787381a34b22da32bf5b1e9e26bc6/packages/cubejs-cli/src/templates.ts#L107

I hope that helps the community!
Thanks!

**Comment by igorlukanin** [comment]
@lucasortigoso Thanks for reporting this!
