### ISSUE TITLE
Localizing and Internalization of Labels for ng charts 

### ISSUE THREAD

**Issue by PieterVanZyl-Dev** [cube-js/cube.js#2971]
Problem: I cannot localize chart labels in cube js (titles can be localized)
How might I handle this for labels that need to be localized.
@paveltiunov 

I'm wondering how to localize the labels (translate them)

and I'm unsure how to approach this

I have a solution for handling localization for the titles but not for the labels

I'm doing this in Angular with i18n which compiles everything at compile time (not run time translations)

_Originally posted by @PieterVanZyl-Dev in https://github.com/cube-js/cube.js/issues/1360#issuecomment-859463683_

**Comment by vasilev-alex** [comment]
Hi @PieterVanZyl-Dev! Are you talking about the Playground? Could you maybe share a screenshot/code snippet?

**Comment by PieterVanZyl-Dev** [comment]
I just realized the labels are coming from the data.

So to localize, I'd need to provide two queries, an english query (for example TitleEN) and an seperate query (with a column TitleAR) and then selectively decide which query to send depending on the user that is connected.
