### ISSUE TITLE
Support for Cloud Object Storage?

### ISSUE THREAD

**Issue by flop1971** [cube-js/cube.js#2972]
Hi,

How can I do connect to an Object Storage (i.e. https://www.ibm.com/cloud/object-storage) Repository with Cube.js?

Would it be possible to write a connector to pull the data from Object Storage or are connects available for SQL / NoSQL repos only?

Thanks
Jonathan

**Comment by rongfengliang** [comment]
@flop1971  for object storage use presto、trino、 dremio maybe easy . then we can use cube.js query data directly

**Comment by rchkv** [comment]
@rongfengliang, thanks for your answer! 

@flop1971  Is this issue still actually? Do you need any further assistance? Feel free to follow up :slightly_smiling_face:
If the issue doesn't actually, could you please close it? 
Thanks!
