### ISSUE TITLE
Build a measure with complex SQL that references the start and end dates a user selects?

### ISSUE THREAD

**Issue by milo157** [cube-js/cube.js#2980]
**Problem**

Hi! Is there a way to build a measure with complex SQL that references the start and end dates a user selects?

I attached an image of my schema which is a DBT snapshot and I'm trying to reproduce the query of:

```
SELECT SUM(cost*inventory_quantity)
FROM inventory_snapshot
WHERE 
(DATE(dbt_valid_from) <= '2021-06-01' AND DATE(dbt_valid_to) IS NULL) 
OR (DATE(dbt_valid_from) >= '2021-06-01' AND DATE(dbt_valid_to) <= '2021-06-01'))
```

As you can see I am checking the conditions on two seperate time columns. It doesn't seem like this is possible in Cube but I could write the SQL as a measure, I'm just not sure its possible to refer to dates in the SQL. 

![Screenshot 2021-06-19 at 13 09 25 (2)](https://user-images.githubusercontent.com/43028253/122663392-62f00d00-d19a-11eb-9c78-cb22136be7d0.png)

**Comment by rchkv** [comment]
@milo157 thanks for asking!

This question was answered in [Slack](https://cube-js.slack.com/archives/CC0403RRR/p1624101153446500), so I close the issue.
