### ISSUE TITLE
Require currency format

### ISSUE THREAD

**Issue by binodsarkar** [cube-js/cube.js#301]
**Currency need to be support.**
Most of the cases we need to display currency with currency symbol or code. So, to use in production currency format need to be supported?
Is there any simple way to do that?

**Comment by paveltiunov** [comment]
@binodsarkar Hey Binod! Thanks for posting this! We believe currency rendering is frontend responsibility. Cube.js supports meta format for currency: https://cube.dev/docs/types-and-formats#measures-formats-currency. You can use it to detect which columns should be rendered as a currency and handle it on your frontend.

**Comment by paveltiunov** [comment]
@binodsarkar Hey Binod! Do you think this is resolved for you?
