### ISSUE TITLE
Dremio reserved keyword is not handled properly

### ISSUE THREAD

**Issue by enathaniel-ib** [cube-js/cube.js#3022]
**Describe the bug**
We observed that if our cube contains Dremio reserved keyword, it is not being handled properly 

**To Reproduce**
1. Create a cube:
```
cube (`DNSActivity`, {
  sql: `select * from "dremio"."mytable"`,
  sqlAlias: `my_alias`,
  measures: ...,
  dimensions: {
    user: {
      sql: `"user"`, // reserve keyword in Dremio, must be double quoted, if not, exception will be thrown
      type: `string`
    }, 
  }
       
```
2. Observed the eval'ed SQL sent by Cube.js to Dremio
```
SELECT
      "user" "mytable__user"
```
3. Result: we get the user we use to connect to DREMIO!

**Expected behavior**
```
SELECT
      "mytable"."user" "mytable__user"
```

**Screenshots**

**Version:**
"@cubejs-backend/dremio-driver": "^0.26.56"

**Additional context**
The problem here is that the reserve keyword must prefixed by sqlAlias or else it won't work.

This issue is a showstopper (data invalid)

**Comment by paveltiunov** [comment]
@enathaniel-ib Hey Edwin! It should be referenced using `CUBE` https://cube.dev/docs/cube#members-and-referencing:
```javascript
cube (`DNSActivity`, {
  sql: `select * from "dremio"."mytable"`,
  sqlAlias: `my_alias`,
  measures: ...,
  dimensions: {
    user: {
      sql: `${CUBE}."user"`, // reserve keyword in Dremio, must be double quoted, if not, exception will be thrown
      type: `string`
    }, 
  }
  //...
  ```

**Comment by enathaniel-ib** [comment]
Verified using ${CUBE} works :).
