### ISSUE TITLE
ResultSet.chartPivot() doesn't return any counts when query granularity is set to "week"

### ISSUE THREAD

**Issue by econtentmaps** [cube-js/cube.js#3026]
**Describe the bug**
The chartPivot method doesn't return counts when the query's timeDimension granularity is set to week, even though counts are included in the API response. 

**To Reproduce**
1. Create a query (e.g.

```js
"query": {
  "measures": ["Transactions.totalSales"],
  "timeDimensions": [{
    "dimension": "Transactions.fullDate",
    "granularity": "week",
    "dateRange": ["2020-01-01T00:00:00.000", "2020-06-30T23:59:59.999"]
  }],
  "order": [{
    "id": "Transactions.fullDate",
    "desc": false
  }],
  "filters": [{
    "member": "Transactions.supplierId",
    "operator": "equals",
    "values": ["9140652-08"]
  }],
  "timezone": "UTC",
  "dimensions": [],
  "queryType": "regularQuery"
},
```

2. Use chartPivot method on resultsSet and see the array items don't contain the count:

```
{
	"category": "2020-06-24T00:00:00.000",
	"x": "2020-06-24T00:00:00.000",
	"xValues": ["2020-06-24T00:00:00.000"]
}
```

**Expected behavior**
I expect to see Transactions.fullDate counts in the object returned by the method.

**Version:**
0.27.41

**Comment by vkruoso** [comment]
I think this is exactly the issue I've opened yesterday. #3023 Will close that one in favor to this.
