### ISSUE TITLE
Weekly and Monthly aggregations are calculating wrong for last 90 days or last 30 days granularity

### ISSUE THREAD

**Issue by RajendraMallarapu** [cube-js/cube.js#303]
Weekly and Monthly aggregations are calculating wrong for last 90 days or last 30 days granularity.

calculating last 31 days instead of 30 and 91 days instead of 90 days.

Request 

timeDimensions":[  
      {  
         "dimension":"<proj>.date",
         "granularity":"month",
         "dateRange":"last 90 days"
      }
   ]
   }

Response: 
"timeDimensions": [
            {
                "dimension": "<Proj>.date",
                "granularity": "month",
                "dateRange": [
                    "2019-09-18",
                    "2019-12-17"
                ]
            }
        ],

**Comment by paveltiunov** [comment]
@RajendraMallarapu Hey Rajendra! Nice catch! Thanks for posting this one! Just fixed it.
