### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by flutterWang** [cube-js/cube.js#304]
**Describe the bug**
Documentation error 

**Screenshots**
![WeChat5f6675fe3810fff3623d8e45f9a0be89](https://user-images.githubusercontent.com/54163491/71083671-85ccea00-21ce-11ea-8a8b-113881bde559.png)

**Comment by paveltiunov** [comment]
@flutterWang Hey Wbofeng! Thanks for posting this! Nice catch! Fixed.
