### ISSUE TITLE
Typescript compilation error (cron-parser version mismatch)

### ISSUE THREAD

**Issue by mfulop** [cube-js/cube.js#3060]
Since 0.27.4x, compilation of Typescript project including cubejs-backend fails with error:

```
node_modules/@cubejs-backend/schema-compiler/dist/src/adapter/BaseQuery.d.ts:232:27 - error TS2694: Namespace 'CronParser' has no exported member 'CronDate'.

232         start: cronParser.CronDate;
                              ~~~~~~~~

node_modules/@cubejs-backend/schema-compiler/dist/src/adapter/BaseQuery.d.ts:233:25 - error TS2694: Namespace 'CronParser' has no exported member 'CronDate'.

233         end: cronParser.CronDate;
```

The reason is that `@cubejs-backend/api-gateway@^0.27.46` depends on `cron-parser "^2.16.3"` while `@cubejs-backend/schema-compiler@^0.27.46` depends on `cron-parser "^3.5.0"`. 

This can be worked around by forcing resolution of cron-parser v3.5.0 in package.json:
```
  "resolutions": {
    "cron-parser": "3.5.0"
  },
```

**Version:**
    "@cubejs-backend/server": "0.27.46"

**Comment by ovr** [comment]
Hello @mfulop,

Thank you for submitting an issue! Fixed, will be released in the next version.

Thanks
