### ISSUE TITLE
Dashboard app on docker dev deployment is not working

### ISSUE THREAD

**Issue by Arunkumar2609** [cube-js/cube.js#3078]
Creating your own dashboard app on docker dev deployment is not working. Resulting module not found errors.

1. Get started with docker dev deployment
2. Create dashboard app from cube js playground

Error1:
Failed to compile.

./node_modules/react-chartjs-2/dist/index.modern.js
Module not found: Can't resolve 'chart.js' in '/cube/conf/dashboard-app/node_modules/react-chartjs-2/dist'

After getting the error, I have installed the chart js manually using 
npm install chart.js

Error2:
Failed to compile.

./node_modules/@apollo/client/core/LocalState.js
Module not found: Can't resolve 'graphql' in '/cube/conf/dashboard-app/node_modules/@apollo/client/core'

**Version:**
0.27.47

**Comment by Arunkumar2609** [comment]
Any updates? @vasilev-alex

**Comment by vasilev-alex** [comment]
@Arunkumar2609 which dashboard is that?

**Comment by vasilev-alex** [comment]
@Arunkumar2609 should be fixed now. Could you test it again, please?

**Comment by Arunkumar2609** [comment]
Still, having the same issue. Please find the screen captures.
```
root@localhost:~# uname -a
Linux localhost 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@localhost:~# docker images | grep cube
cubejs/cube                         latest              8499354b47ca        21 hours ago        1.64GB
root@localhost:~# docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
1f93ffa19e6e        cubejs/cube                         "docker-entrypoint.sâ€¦"   8 minutes ago       Up 8 minutes        0.0.0.0:3000-3001->3000-3001/tcp, 0.0.0.0:4000->4000/tcp   cubetest
```
![image](https://user-images.githubusercontent.com/44184569/125106893-cb793c80-e0fd-11eb-8a90-d5ac83e64c50.png)

![image](https://user-images.githubusercontent.com/44184569/125106783-adabd780-e0fd-11eb-8541-90e492fd6e64.png)

![image](https://user-images.githubusercontent.com/44184569/125106749-a1277f00-e0fd-11eb-9197-1655ee18121d.png)

**Comment by wdifruscio** [comment]
Same issue for me (:

**Comment by Arunkumar2609** [comment]
Any updates? @vasilev-alex

**Comment by vasilev-alex** [comment]
@Arunkumar2609 fixed. Tested it with the same set and it works for me. Could you please also confirm that?
