### ISSUE TITLE
TypeScript type for filters in Query are incorrect

### ISSUE THREAD

**Issue by rdwoodring** [cube-js/cube.js#3083]
**Describe the bug**
The [Filter](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-client-core/index.d.ts#L711) type used in the [Query](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-client-core/index.d.ts#L768) type is a union of UnaryFilter and BinaryFilter, both of which support optional `and` and `or` keys; however, they also have other keys that are required, so writing a query with `and` or `or` is flagged by the TypeScript compiler.

**To Reproduce**
1. Create a Typescript project and install `@cubejs-client/core`
2. Import `Query` from `@cubejs-client/core` and write a manual query:
```
// flagged by TypeScript since BinaryFilter requires operator and values
const query: Query = {
  dimensions: ['Products.name'],
  filters: [
    {
      or: [
        {
          member: 'Products.name',
          operator: 'contains',
          values: [
            'train',
            'plane',
            'automobile'
          ]
        },
        {
          member: 'Products.price',
          operator: 'lte',
          values: [
            '1000'
          ]
        }
      ]
    }
    
  ]
};
```
3. Run the Typescript compiler (or see the error in your editor)

**Expected behavior**
As indicated in the [documentation](https://cube.dev/docs/query-format#boolean-logical-operators), I should be able to add logical operators to my query (and I can, actually, despite TypeScript's insistence, logical operators work properly when a query like the above is sent to the Cube.js server)

**Screenshots**
![Screenshot 2021-07-09 081810](https://user-images.githubusercontent.com/2885351/125076801-5a4e7080-e08e-11eb-8222-a08156cc6202.png)

**Version:**
[e.g. 0.27.48]

**Additional context**
The following updates in cubejs-client-core's index.d.ts seem to fix the issue:

```
interface OrFilter {
    or: Array<UnaryFilter | BinaryFilter | AndFilter>
  }
  
  interface AndFilter {
    and: Array<UnaryFilter | BinaryFilter | OrFilter>
  }
  
  type Filter = OrFilter | AndFilter | UnaryFilter | BinaryFilter
```

**Comment by vasilev-alex** [comment]
@rdwoodring thanks for posting it here. Would you mind creating a PR for that?

**Comment by rdwoodring** [comment]
I should have some time to try and work on it this evening.
