### ISSUE TITLE
Druid driver not mapping "ILIKE" to "LIKE"

### ISSUE THREAD

**Issue by vominhtritiki** [cube-js/cube.js#3109]
**Describe the bug**
Druid driver on version 0.27.49 throws an error ("Error: Encountered "ILIKE" at line 4, column 315...") when I execute a query with a string dimension in the filter.

**To Reproduce**
1. Create a project with the Druid database.
2.  Create a cube with a string dimension (X).
3. Execute query with X dimension in the filter.
4. See an error.

**Expected behavior**
Return results match with the filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/84368074/125555110-9828a60a-6c1a-4900-82ce-f4b808532612.png)

**Version:**
0.27.49

**Comment by paveltiunov** [comment]
Hey @vominhtritiki ! I can confirm Druid driver lacks like implementation. Looking forward to community contribution here!
