### ISSUE TITLE
docs(schema): Markdown not rendered

### ISSUE THREAD

**Issue by adnanrahic** [cube-js/cube.js#3141]
**Describe the bug**
Seems like parts of the Markdown was rendered inside of the code block element.

**To Reproduce**
1. Go to [Pre-Aggregations in the docs](https://cube.dev/docs/schema/reference/pre-aggregations#incremental-refresh)
2. Click on [Incremental Refresh](https://cube.dev/docs/schema/reference/pre-aggregations#incremental-refresh)
3. Scroll down to the code block element
4. See how the code block has Markdown code that was not rendered

**Expected behavior**
Expected to see rendered Markdown

**Screenshots**
![cube dev_docs_schema_reference_pre-aggregations](https://user-images.githubusercontent.com/15029531/126481461-390eb1ed-c79b-4dc9-afc2-1f7483d3967e.png)

**Comment by hassankhan** [comment]
Closed in 7bc3c53b08c94de22a6b4ab3bd49fc61b36fd80c
