### ISSUE TITLE
Provide How to Write cube.js driver test  or cube.js driver framework

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube.js#3168]
**Is your feature request related to a problem? Please describe.**

I need to do some tests for cube.js driver but current I  can't found any docs about how to write a better tests for cube.js driver 

**Describe the solution you'd like**

maybe provide some docs or  cube.js  driver test framework

**Comment by paveltiunov** [comment]
https://github.com/cube-js/cube.js/blob/master/packages/cubejs-testing/test/smoke-tests.ts great starting point for writing a basic integration test.
