### ISSUE TITLE
How to use logical operators in timeDimension filter

### ISSUE THREAD

**Issue by sourav-jha** [cube-js/cube.js#3196]
**Problem**

We have two date fields start and end date, we want to use the time dimension for filtering the date which matches the condition on the start date or end date.

We have tried this:

` "timeDimensions": [{
				"dimension": "Test.startDate",
				"dateRange": [
					"2020-08-02",
					"2021-08-02"
				]
			},
			{
				"dimension": "Test.endDate",
				"dateRange": [
					"2022-08-04",
					"2022-08-04"
				]
			}
		]`
 but this is generating AND query not or.

**Comment by rchkv** [comment]
Hi @sourav-jha 👋 

You can use `or` logical operator in your query: https://cube.dev/docs/query-format#boolean-logical-operators
