### ISSUE TITLE
Bug where week scope does't show any data

### ISSUE THREAD

**Issue by thellimist** [cube-js/cube.js#3198]
**Describe the bug**
When selecting "week" frequency, the data shows nothing if the start and end dates are not Monday and Sunday respectively. 

**To Reproduce**
Steps to reproduce the behavior fail:
1. Go to CubeCloud Playground
2. Select any Measure and Time. Select for `Last Quarter` and `Week` 
3. Run
4. See no data is shown

--

Steps to reproduce the behavior succeed:
1. Go to CubeCloud Playground
2. Select any Measure and Time. Select for `Custom` with Monday, Sunday as start and end of week and `Week` as frequency
3. Run
4. Data is shown

**Expected behavior**
Data should show regardless of Custom date selection

**Screenshots**
![](https://cdn.zappy.app/abfd2922f2af4963d19a7fdc69ba9edc.png)
![](https://cdn.zappy.app/38949276c2a5ccb03b761ca1dcfdf362.png)
![](https://cdn.zappy.app/8deafea4ab4068a81d2f1e85bace7fdb.png)
![](https://cdn.zappy.app/f4aa44a43b27ea785b739c90e1c235cb.png)

**Version:**
Cube server 0.28.11

**Comment by vasilev-alex** [comment]
hi @thellimist! Are you running this query on Cube Cloud or your local machine?

**Comment by thellimist** [comment]
We are using `import { QueryBuilder } from '@cubejs-client/playground';` for the page using Cube Cloud.

**Comment by vasilev-alex** [comment]
Ok, got it. You should update the Playground to the latest version, and also, update the chart renderers as shown here https://www.npmjs.com/package/@cubejs-client/playground

P.S. please keep in mind the `QueryBuilder` API is not guaranteed to be stable. In the future, parts of the API may be deprecated.

**Comment by thellimist** [comment]
Hi @vasilev-alex , I've updated the dependencies to 

```
    "@cubejs-client/core": "0.28.10",
    "@cubejs-client/playground": "0.28.14",
    "@cubejs-client/react": "0.28.10",
```

the weekly scope still fails to work.

**Comment by vasilev-alex** [comment]
@thellimist did you also run the command to update chart renderers?

**Comment by thellimist** [comment]
> @thellimist did you also run the command to update chart renderers?

I don't know what that command is. I just ran `npm install`

**Comment by vasilev-alex** [comment]
you can find it in the Readme file at https://www.npmjs.com/package/@cubejs-client/playground

```bash
#!/bin/bash

rm -rf ./public/chart-renderers 2> /dev/null
cp -R ./node_modules/@cubejs-client/playground/public/chart-renderers ./public
```
