### ISSUE TITLE
Sqlite driver error - no such function: FLOOR

### ISSUE THREAD

**Issue by rsxdalv** [cube-js/cube.js#3209]
**Describe the bug**
Internal Cube.js queries fail due to SQLite not supporting FLOOR function:  
```SQL
SELECT FLOOR((strftime('%s','now')) / 10)
```

Console output:
```json
{
  "processingId": 88,
  "queueSize": 1,
  "queryKey": [
    "SELECT FLOOR((strftime('%s','now')) / 10)",
    []
  ],
  "queuePrefix": "SQL_QUERY_STANDALONE_default",
  "timeInQueue": 0
}
```
```
Error: SQLITE_ERROR: no such function: FLOOR
```

**To Reproduce**
1. Clone this repo & locate https://github.com/cube-js/cube.js/tree/master/examples/slack-vibe
2. Run locally https://github.com/cube-js/cube.js/tree/master/examples/slack-vibe#running-locally
3. Import Slack Data.zip
4. Error will be visible in the Cube.js dev server

**Comment by ovr** [comment]
Hello @rsxdalv,

This issue was already fixed https://github.com/cube-js/cube.js/commit/fe64febd1b970c4b8396d05a859f16b3d9e5a8a8 in Cube.js >= `v0.26.6`.
 
Thanks
