### ISSUE TITLE
Use Yarn Workspaces

### ISSUE THREAD

**Issue by hassankhan** [cube-js/cube.js#321]
**Is your feature request related to a problem? Please describe.**

Currently each package in the monorepo has its own `yarn.lock` and `yarn install` must be run in each package independently.

**Describe the solution you'd like**

Since Yarn is already being used, it would make sense to enable workspaces.

Another cool feature of Workspaces is automatic symlinking of local packages. For example, where `@cubejs-client/react` depends on `@cubejs-client/core`, Yarn would automatically symlink the package folder when running `yarn install`.

Workspaces work alongside Lerna, although there is some overlap.

Also, upon checking the CircleCI configuration, we would need to update the caching strategy since most dependencies in a workspace are hoisted to the root of the project.

**Describe alternatives you've considered**

Could potentially use `lerna bootstrap` too, although at @EndemolShineGroup we've had more success with workspaces.

**Additional context**
[Yarn Workspaces documentation](https://yarnpkg.com/lang/en/docs/workspaces/)
[Yarn Workspaces caching on CircleCI](https://www.benpickles.com/articles/77-caching-yarn-workspaces-on-circleci)

**Comment by paveltiunov** [comment]
@hassankhan Yep. Agree. We even tried to do so but reverted as far as I remember it requires some root restructuring.
