### ISSUE TITLE
Node client hangs when loading big responses

### ISSUE THREAD

**Issue by tomasrb** [cube-js/cube.js#3235]
**Describe the bug**
Similar to: https://github.com/cube-js/cube.js/pull/3216.  When a payload size is large enough in our case 78KB, the node cube client hangs (promise remains idle indefinitely without resolving/rejecting/throwing errors).

**To Reproduce**
Use the Node cube client to load a payload that is 78KB in size.  In debug level trace the cube server logs will look like the request was successful "Query Completed" and "Load Request Successful" but the node client will hang.

Bypassing the node client with a curl /load request for the same query successfully returns the results.

**Expected behavior**
The node cube client doesn't hang and resolves it's promise successfully.

**Screenshots**
Cube server logs from hanging client are equivalent to same query with smaller payload that doesn't cause the client to hang.

![Screen Shot 2021-08-11 at 1 43 41 PM](https://user-images.githubusercontent.com/5140912/129101257-d73292ad-7b23-4258-ad44-0d5c3fbd51de.png)

**Version:**
Node version: 15.14.0
Cube version: 0.28.17

**Additional context**
Pre-aggregations are disabled and database is bigquery.

**Comment by vieira** [comment]
@tomasrb this seems exactly the same problem we were having but in our case #3216 fixed it.

Just to be sure, did you redeploy the nodejs application that is calling the cubejs server after updating? The fix was in the client library, not in the cube server.

**Comment by tomasrb** [comment]
@vieira ah must have been an issue on our side, to be sure i re-deployed/restarted our cluster and everything works well, closing this issue, thanks again!
