### ISSUE TITLE
Create Serverless template projects for easier setup

### ISSUE THREAD

**Issue by hassankhan** [cube-js/cube.js#325]
**Is your feature request related to a problem? Please describe.**
While it is awesome that Cube.js can scaffold a Serverless project for me, I'd prefer to use Serverless' own scaffolding tool.

**Describe the solution you'd like**
The Serverless CLI tool supports scaffolding projects from a URL:

```bash
serverless create --template-url https://github.com/cube-js/cube-js/tree/master/lib/packages/cubejs-serverless-aws-project --path myService
```

**Describe alternatives you've considered**
We could potentially change the current `cubejs create` command to instead run `npx serverless create <URL>`, or do something more extravagant with Yeoman templates 🙂

**Additional context**
[Serverless Create Command Reference](https://serverless.com/framework/docs/providers/aws/cli-reference/create/)

**Comment by paveltiunov** [comment]
@hassankhan Great idea! I think we can do this if they support execution of arbitrary JavaScript/binary during template creation.

**Comment by hassankhan** [comment]
>  if they support execution of arbitrary JavaScript/binary during template creation.

Unfortunately there is not, all it does is grab the files from the URL and recreate them on your local filesystem.

Given the requirements, I would suggest using [Yeoman](https://yeoman.io/) instead then. It's been around for ages, works extremely well and is easily integrated into the existing CLI package.
