### ISSUE TITLE
Use a `.cubejsrc` file for server configuration options

### ISSUE THREAD

**Issue by hassankhan** [cube-js/cube.js#326]
**Is your feature request related to a problem? Please describe.**
Currently Cube.js server options must be set inside Javascript source.

**Describe the solution you'd like**
This would improve ergonomics for Serverless projects as well as provide a single place for all configuration options to live in Cube.js projects.

I would suggest using something like [Cosmiconfig](https://github.com/davidtheclark/cosmiconfig), which makes reading `.*rc` (and similar filename variations) a doddle.

**Comment by paveltiunov** [comment]
@hassankhan Currently Cube.js has two configuration options:
1. Environment variables and .env.
2. JavaScript configs.
Second option used mostly to pass various custom implementations. 

Do you expect `.cubejsrc` to be alternative to the first option or to the second? If it's second do you want it to be JSON or JavaScript file?

**Comment by hassankhan** [comment]
Hi @paveltiunov, thanks for the reply :smile:

Currently, only _some_ of the available Cube.js options can be set via environment variables.

> Do you expect .cubejsrc to be alternative to the first option or to the second? If it's second do you want it to be JSON or JavaScript file?

I would almost expect it to be an option for both. Cosmiconfig supports loading JSON and JS files (as well as allowing you to add support for custom file types such as Typescript). In a perfect world, we would import values from both the environment and the config file and merge them, with values from the config file taking precedence.

We would also need a default configuration that reads environment variables from `process.env`, but allow users to override them in their own `.cubejsrc`.

I noticed that the idea was also floated in [#129](https://github.com/cube-js/cube.js/issues/129#issuecomment-504787841), so hopefully a resolution for this issue might help there, too.

**Comment by hassankhan** [comment]
Closed since Cube.js now has support for a configuration file.
