### ISSUE TITLE
Contains operator becomes case sensitive after query acceleration with pre-aggregations

### ISSUE THREAD

**Issue by lokeshwer** [cube-js/cube.js#3260]
**Describe the bug**
I connected to Postgres Db and I see ILIKE (in generated SQL query) for contains operator, which works as expected (case insensitive) until query is accelerated with pre-aggregations. After pre-aggregation, the query turns case sensitive. Please find attached the two queries and let me know if there's something that I can do to make the query case insensitive across the schemas.

**To Reproduce**
1. Create a simple schema (event_fact)
2. Apply filter on text dimension (EventName contains Fail) and observe the measure
3. Accelerate the query 
4. Apply the same filter as in Step 2. The measure differs

**Expected behavior**
The measure should remain same whether the query is accelerated or not.

**Screenshots**
```
SELECT
  "event_fact".event_name "event_fact__event_name",
  sum("event_fact".count_value) "event_fact__count_value"
FROM
  event_fact AS "event_fact"
  LEFT JOIN db.diag_fact AS "diag_fact" ON "event_fact".file_id = "diag_fact".file_id
WHERE
  ("diag_fact".event_name **ILIKE** '%' | | $ 1 | | '%')
  AND (
    "event_fact".event_name **ILIKE** '%' | | $ 2 | | '%'
  )
GROUP BY
  1
ORDER BY
  2 DESC
LIMIT
  10
```
```
SELECT
  ` event_fact__event_name ` ` event_fact__event_name `,
  sum(` event_fact__count_value `) ` event_fact__count_value `
FROM
  dev_pre_aggregations.event_fact_main AS ` event_fact__main `
WHERE
  (` diag_fact__event_name ` **LIKE** CONCAT('%', ?, '%'))
  AND (
    ` event_fact__event_name ` **LIKE** CONCAT('%', ?, '%')
  )
GROUP BY
  1
ORDER BY
  2 DESC
LIMIT
  10
```

**Version:**
[0.27.53]

**Additional context**

**Comment by paveltiunov** [comment]
Hey @lokeshwer ! Thanks for posting it! I can confirm that it wasn't implemented yet.

**Comment by paveltiunov** [comment]
Fixed in latest version.
