### ISSUE TITLE
Separate Express server from endpoint logic

### ISSUE THREAD

**Issue by hassankhan** [cube-js/cube.js#328]
**Is your feature request related to a problem? Please describe.**
Currently Cube.js Server comes bundled with an Express server.

**Describe the solution you'd like**
I would like for the logic in each endpoint to be located separately such that I can use my own HTTP server. In my case specifically, I would like to use [`lambda-api`](https://github.com/jeremydaly/lambda-api#readme), which functions similarly to Express but with a much smaller footprint.

**Comment by paveltiunov** [comment]
@hassankhan https://cube.dev/docs/@cubejs-backend-server-core is web framework agnostic. If lambda-api is connect compatible it should work out of the box. You can pass lambda-api instead of express to `serverCore.initApp()`.

**Comment by paveltiunov** [comment]
@hassankhan Hey Hassan! Would love to hear some feedback on it.
