### ISSUE TITLE
Skip preaggregation option in query options

### ISSUE THREAD

**Issue by starsuit** [cube-js/cube.js#3286]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be an easy way to skip a query that has a pre-aggregation if there's an issue with that pre-aggregation. E.g. sometimes a pre-aggregation will be extremely slow to build, or an issue with cubestore, and I'd rather query my source database directly as this can be faster. If there's a bug or issue with the pre-aggregations, I'd rather bypass and return some slow data rather than error.

**Describe the solution you'd like**
I'd like to be able to toggle a `skipPreAggregation` option on a query sent from the frontend.
e.g.
```
{
    measures: [...],
    timeDimensions: [...],
    filters: [...],
    skipPreAggregation: true
}
```
This would allow me to skip pre-aggregations if they're running slow, or if there's an issue.

**Describe alternatives you've considered**
A hacky way is to add an extra dimension to the query to make sure the query doesn't qualify for a pre-aggregation, but this is extremely messy. I can also comment out the pre-aggregation section of the schema, but this is also a bit messy.

**Additional context**

**Comment by rpaik** [comment]
@ovr @ilya-biryukov could you take a look at this?

**Comment by paveltiunov** [comment]
@starsuit Hey Sam! Thanks for posting this one! I believe the way to go here is using multiple environments with different configurations. Either with different env or even different sources. In Cube Cloud we're going to support multiple environments per deployment soon. You would be able to swap between them transparently in production. You can also create multiple deployments for the same app with different configurations.
