### ISSUE TITLE
Security context based schema access

### ISSUE THREAD

**Issue by ianschmitz** [cube-js/cube.js#3290]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to selectively show or hide certain aspects of the schema such as measures and dimensions based on the `SECURITY_CONTEXT`.

**Describe the solution you'd like**
Both [measures](https://cube.dev/docs/schema/reference/measures#parameters-shown) and [dimensions](https://cube.dev/docs/schema/reference/dimensions#parameters-shown) support a `shown` property which accepts a boolean. If we were able to provide a dynamic value such as via a function we could selectively show or hide these based on the security context. A contrived example:

```ts
cube(`Users`, {
	  dimensions: {
	    isAdmin: {
			sql: `is_admin`,
			type: `boolean`,
			// Only let users with the `admin` role see which users are admins
			shown: (securityContext) => !!securityContext.role === "admin"
		}
	  }
}

```

**Describe alternatives you've considered**
Multiple schemas based on the role? But that is a major maintenance burden.

**Comment by paveltiunov** [comment]
@ianschmitz Hey Ian! Thanks for posting this! Most likely it should be handled by #2145. Please let me know if you think this can solve your problem.

**Comment by ianschmitz** [comment]
I think so? Assuming in the OP by `context` this would mean the security context? (sorry i'm new to cube.js). Basically being able to inspect the claims from the JWT to make schema decisions.

**Comment by paveltiunov** [comment]
@ianschmitz Yep. Correct. I'd suggest continuing the discussion in #2145 then.
