### ISSUE TITLE
Support variable partition granularity for pre-aggregations

### ISSUE THREAD

**Issue by CNimmo16** [cube-js/cube.js#3294]
EDIT: issue initially raised as a bug, however the problem was actually misuse of the buildRange feature, as a workaround to the lack of support for variable partition granularity. See details in thread.

**Describe the bug**
After issuing a query with a timeDimension, Cube does not seem to check the buildRangeStart and buildRangeEnd when choosing a pre-aggregation: if an available pre-aggregation is otherwise matching, but has a buildRange which does not span the full dateRange in the query, the pre-aggregation is used anyway. This leads to a "successful" response, with the pre-aggregation used, but in fact the response is missing dates which were requested in the query, but not covered by the pre-aggregation.

**To Reproduce**
1. Create a rollup pre-aggregation with a buildRangeStart and buildRangeEnd, such as:
```
{
  type: `rollup`,
  external: true,
  granularity: 'day',
  buildRangeStart: {
    sql: () => `SELECT DATE_SUB(NOW(), INTERVAL 1 MONTH)`,
  },
  buildRangeEnd: {
    sql: () => `SELECT NOW()`,
  },
  ... other rollup props ...
}
```
2. Send a query matching the pre-aggregation, but with a dateRange outside the buildRange of the pre-aggregation, for example:
```
{
  "timeDimensions": [
    {
      "dimension": "ActiveUserEvents.eventAt",
      "granularity": "day",
      "dateRange": [
        "2020-08-01T00:00:00.000",
        "2021-08-31T23:59:59.999"
      ]
    }
  ],
  ... other query props ...
}
```

Cube responds with a dataset including only records from the last month (the buildRange of the pre-aggregation).

**Expected behavior**
I would expect that the pre-aggregation is simply ignored and the query is run against the source db, as with any other case where the query does not match the pre-aggregation. 

**Version:**
v0.28.13

**Comment by paveltiunov** [comment]
@CNimmo16 Hey Cameron! Thanks for posting this! It's actually intended behavior. So `buildRange` should span all the data you have. 

Could you please elaborate a little bit on your use case? Do you have data in the future such as predictions?

**Comment by CNimmo16** [comment]
Hi @paveltiunov, thanks for the reply. No, we don't have predictions - the use case is that I want to have multiple pre-aggregations for the same source data, as follows:

a) A pre-aggregation containing historic data (and "month" granularity). This should be fully refreshed once per week.
b) Another pre-aggregation **containing only data from the last 30 days with a "day" granularity - because we only display the last month of data broken down by day**. Data from the current day should be incrementally refreshed every 30 minutes.

I have bolded the part which is relevant here. From what I understand then, there is no recommended way of doing this?

**Comment by CNimmo16** [comment]
@paveltiunov sorry to follow up, but could I please get some advice on this? I have currently implemented the pre-aggregations as discussed above, and they are performing well, but I am quite concerned about the potential for datasets to be returned with missing values - with no way of capturing these query "errors", they could go unnoticed for months. If there is a better approach I would like to know as soon as possible, as we are hoping to release our cube.js backed dashboard imminently.

**Comment by paveltiunov** [comment]
@CNimmo16 It's a little bit more complicated than that. In fact, allowing two pre-aggregations with different build ranges to be selected at query time based on build range may seem to solve the problem but it introduces consistency issues with a refresh. Also, cases where data range span a border of a build range aren't covered. 

We're considering having variable partition granularity for pre-aggregations. Let's use this issue to track the status of this feature.

**Comment by paveltiunov** [comment]
It can be solved in the latest version using https://cube.dev/docs/caching/pre-aggregations/lambda-pre-aggregations#lambda-pre-aggregations by defining multiple rollups with variable granularity.
