### ISSUE TITLE
Week granularity has issues with `WHERE` statements

### ISSUE THREAD

**Issue by thellimist** [cube-js/cube.js#3317]
**Describe the bug**
When I have a WHERE filter on month granularity it works as expected. When I change only the granularity to week it shows incorrect results.

**To Reproduce**
Screenshots has the queries

**Expected behavior**
We expect the week granularity to show similar to month granularity

**Screenshots**
[Month: Works](https://cdn.zappy.app/266ded3f8de31b785ae644f36873297f.png)
[Week: Does not work](https://cdn.zappy.app/4a749cf158e02424814fb5c1548cecf8.png)

**Version:**
CubeCloud: 0.28.20
"@cubejs-client/core": "0.28.17",
"@cubejs-client/playground": "0.28.18",
"@cubejs-client/react": "0.28.17",

**Comment by vasilev-alex** [comment]
Hi @thellimist! I remember we had this discussion in the issue #3198. I'm not sure if you were able to update the chart renderers?

Also, does the same query work if you run it in the Playground on Cube Cloud?
