### ISSUE TITLE
Error: column "typcategory" does not exist in pg_type

### ISSUE THREAD

**Issue by root-io** [cube-js/cube.js#3330]
Introduced in 0.28.18: https://github.com/cube-js/cube.js/commit/b88d30cfceb66682fbd0508352d441ba930f9e7c#diff-d86515a2ea3cfc2cecae8482ac95e84bc7e94f87ba28cac62d2ff66163da26b3

**Comment by root-io** [comment]
PostgreSQL 13.2

**Comment by paveltiunov** [comment]
Should be fixed in latest version.
