### ISSUE TITLE
cubestored : Core dumped

### ISSUE THREAD

**Issue by egorovd** [cube-js/cube.js#3336]
**Describe the bug**

Core dumped in kubernetes (v1.18.8) 

**To Reproduce**
I can prepare helm-chart for reproduce. (If necessary, let me know.)

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/6965699/131130156-55a60810-6d8e-4e3e-99de-65492cb185f3.png)

**Version:**
[v0.28.28]

**Additional context**
What other information can help?

**Comment by paveltiunov** [comment]
@egorovd Please use non-avx docker image: https://hub.docker.com/r/cubejs/cubestore/tags?page=1&name=non-avx
