### ISSUE TITLE
Undeclared dependencies used in @cubejs-backend

### ISSUE THREAD

**Issue by vieira** [cube-js/cube.js#336]
**Describe the bug**
Two packages are used in `@cubejs-backend` without being declared as dependencies in its `package.json`:

- `@cubejs-client/ws-transport` in `cubejs-backend/server-core/dev/templates/packages/web-socket-transport/scaffolding/src/App.js`
- `apollo-link-schema` in `cubejs-backend/server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/graphql/client.js`

**Expected behavior**
No extraneous dependencies used: all packages used in `cubejs-backend` are declared as dependencies in `package.json`.

**Version:**
`@cubejs-backend/server-core`: 0.13.1

**Comment by paveltiunov** [comment]
@vieira Hey João! Where do you see problem with that? Is it some inspection tool? Those files are template files for dashboard applications and not part of backend code so there's no actual dependency frontend libraries.

**Comment by vieira** [comment]
@paveltiunov Hi! Thanks for taking the time to look into this.

We use a monorepo (one of the services in that monorepo uses `CubejsServerCore` via '@cubejs-backend/server-core'.

We then use webpack to build each service and all of its dependencies in a single bundle that is copied to a container (otherwise we would have to either copy the entire monorepo or resolve the dependencies from yarn workspaces ourselves).

This used to work fine with 0.11.3 but since upgrading to 0.13.1 the following errors are produced during build:

```
ERROR in /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/web-socket-transport/scaffolding/src/App.js
Module not found: Error: Can't resolve '@cubejs-client/ws-transport' in '/Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/web-socket-transport/scaffolding/src'
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/web-socket-transport/scaffolding/src/App.js 1:0-61 4:17-35
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages sync ^\.\/.*$
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/AppContainer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/DevServer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/index.js
 @ ./index.js

ERROR in /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/graphql/client.js
Module not found: Error: Can't resolve 'apollo-link-schema' in '/Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/graphql'
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/graphql/client.js 4:0-48 99:12-22
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages sync ^\.\/.*$
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/AppContainer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/DevServer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/index.js
 @ ./index.js
```

**Comment by vieira** [comment]
It seems that version 0.11.21 introduced the issue (0.11.20 is the latest version without this issue).

**Comment by paveltiunov** [comment]
@vieira Gotcha. Could you please try add ignore for these files in your webpack config?

**Comment by vieira** [comment]
Hello @paveltiunov, sorry for the delay, got the flu. 🤧 

I tried the following:

- `new webpack.IgnorePlugin(/dev\/templates/),`: builds, but then fails to start with `const AppContainer = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module '../dev/templates/AppContainer'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));`
- `new webpack.IgnorePlugin(/dev\/templates\/packages/),`: does not build, produces the same error,
- declaring these two dependencies as `externals`: builds, but then fails to start with `module.exports = @cubejs-client/ws-transport;
SyntaxError: Invalid or unexpected token`

Any other thing I should try?

Thanks for your help!

**Comment by paveltiunov** [comment]
@vieira Get well! Could you please try to ignore `/dev/templates/packages`?

**Comment by vieira** [comment]
@paveltiunov thanks! That was attempt number two in my previous comment, it fails to build with the same error.

**Comment by paveltiunov** [comment]
@vieira Could you please share this exact error?

**Comment by vieira** [comment]
@paveltiunov Hello, sorry for the delay.

With `new webpack.IgnorePlugin(/dev\/templates\/packages/),` the error during build is:

```
ERROR in /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/web-socket-transport/scaffolding/src/App.js
Module not found: Error: Can't resolve '@cubejs-client/ws-transport' in '/Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/web-socket-transport/scaffolding/src'
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/web-socket-transport/scaffolding/src/App.js 1:0-61 4:17-35
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages sync ^\.\/.*$
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/AppContainer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/DevServer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/index.js
 @ ./index.js

ERROR in /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/graphql/client.js
Module not found: Error: Can't resolve 'apollo-link-schema' in '/Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/graphql'
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/graphql/client.js 4:0-48 99:12-22
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/packages sync ^\.\/.*$
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/dev/templates/AppContainer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/DevServer.js
 @ /Users/vieira/Code/platform/node_modules/@cubejs-backend/server-core/core/index.js
 @ ./index.js
```

**Comment by paveltiunov** [comment]
@vieira Obviously it just not getting activated. You should ensure that your web pack config respects this `IgnorePlugin` declaration.

**Comment by vieira** [comment]
It think it does because when using `new webpack.IgnorePlugin(/dev\/templates/)`, it builds, but then fails to start with `const AppContainer = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module '../dev/templates/AppContainer'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));`, so IgnorePlugin is getting used.

I just created a reproduction repo for this issue: [vieira/cube-issue-336](https://github.com/vieira/cube-issue-336).

**Comment by paveltiunov** [comment]
@vieira I see. You should check this case: https://webpack.js.org/plugins/ignore-plugin/#example-of-ignoring-moment-locales. `IgnorePlugin` checks what passed to `require` instead of final resolved paths.

**Comment by vieira** [comment]
@paveltiunov thanks for the pointer. For reference, this one is working:
```
new webpack.IgnorePlugin(/^\.\/packages/, /dev\/templates$/),
```

Thanks again for your help.

**Comment by paveltiunov** [comment]
@vieira Great to hear that!
