### ISSUE TITLE
How to query postgresql json fields

### ISSUE THREAD

**Issue by devopsprosiva** [cube-js/cube.js#338]
Hi @paveltiunov ,

I have a requirement to map a query in postgresql with json fields similar to the screenshot below. Is there a way to do this directly in cube-js? Right now the only work around that worked for me was to create a view for each query with json filter in postgresql and then map that view in cube-js schema.

![image](https://user-images.githubusercontent.com/6834501/71786217-dbbad380-2fbd-11ea-8cc6-dff65ba9f8af.png)

**Comment by paveltiunov** [comment]
@devopsprosiva Yep. Please refer to https://stackoverflow.com/questions/59327256/how-to-deal-with-jsonb-objects-in-postgres-databases-in-cube-js
