### ISSUE TITLE
The time zone passed in was not used when converting the time

### ISSUE THREAD

**Issue by MuBeiSAMA** [cube-js/cube.js#3396]
**Describe the bug**

The time zone of the data in my database is Asia/Shanghai.

![image](https://user-images.githubusercontent.com/30261823/132486896-e18db0b1-a22a-43de-9b2b-c53f5e0443cb.png)

My query also specified the time zone as Asia/Shanghai.
```javascript
{
    "measures": [],
    "dimensions": [
        "AppsPlzEnvironment.humidity",
        "AppsPlzEnvironment.createTime",
        "AppsPlzEnvironment.id"
    ],
    "timeDimensions": [
        {
            "dimension": "AppsPlzEnvironment.createTime",
            "dateRange": "from 1 days ago to now"
        }
    ],
    "filters": [
        {
            "member": "AppsPlzEnvironment.farm",
            "values": [
                "14"
            ],
            "operator": "equals"
        }
    ],
    "limit": 500,
    "timezone": "Asia/Shanghai"
}
```

But the time conversion in the query result does not use the passed time zone.

![image](https://user-images.githubusercontent.com/30261823/132486956-cde0ce76-281e-4754-8c57-ce39ecca6e2d.png)

**To Reproduce**

As mentioned above

**Expected behavior**

Use the passed time zone

**Version:**

"@cubejs-backend/postgres-driver": "^0.27.30"
"@cubejs-backend/server": "^0.27.30"

**SQL**

PostgreSQL

**Comment by paveltiunov** [comment]
Hey @MuBeiSAMA ! This is not obvious but correct behavior. Let's move this conversation to #2965.
