### ISSUE TITLE
How to get minute granularity in charts

### ISSUE THREAD

**Issue by devopsprosiva** [cube-js/cube.js#340]
Hi,

I've a timestamp field in buckets on 1 minute. However, lowest granularity in cubejs is 1 hour. How can I get a granularity of 1 minute in my charts?

**Comment by paveltiunov** [comment]
@devopsprosiva `minute` is supported but not documented yet.

**Comment by devopsprosiva** [comment]
So I could use minute in the query code?

**Comment by paveltiunov** [comment]
@devopsprosiva Yes. That’s correct.
