### ISSUE TITLE
Multiple queries in a single request

### ISSUE THREAD

**Issue by smshuja** [cube-js/cube.js#3405]
**Is your feature request related to a problem? Please describe.**
We are evaluating cube.js to offload all our reporting queries. Each report can contain more than 100 queries. Ability to make a post request with multiple queries would help us optimise the data fetching.

**Describe the solution you'd like**
Would be great if query could be an array.
```javascript
[
  {
    measures: ['Stories.count'],
    dimensions: ['Stories.category'],
    filters: []
  },
  {
    measures: ['Orders.count'],
    dimensions: ['Orders.status'],
    filters: []
  }
]
```

Similarly response can be returned as an array, with object at each index corresponding to the respective query index in the request.
```javascript
[
  {
    query:{
      measures:[
        "Users.count"
      ],
      ...
    },
    data:[
      {
        "Users.count":"700"
      }
    ],
    ...
  },
  {
    query:{
      measures:[
        "Orders.count"
      ],
      ...
    },
    data:[
      {
        "Orders.count":"700"
      }
    ],
    ...
  }
]
```

**Describe alternatives you've considered**
Alternative seems to be making multiple queries.

**Additional context**
I tried searching the issues and docs, this doesn't seem to exist.

**Comment by paveltiunov** [comment]
@smshuja Hey Shuja! How do you think it can optimize the data fetch process? Do you think it can help by minimizing the count of HTTP round trips?

**Comment by smshuja** [comment]
@paveltiunov Yes. Exactly. Also, I think this would help with fetching some related data. Like if I fetch some measures grouped by a `related_id`, but also want the `Related` record to display some details about each `Related` record. So, instead of showing the IDs on the graph, `Related.name` can be shown. One would be a normal grouped query and another ungrouped query without any aggregations.

**Comment by paveltiunov** [comment]
@smshuja If your goal is to reduce roundtrip time then using a web socket would be the way to go here. It does packet batching transparently for users.

**Comment by smshuja** [comment]
@paveltiunov web socket approach looks great. Thank you. 👍
