### ISSUE TITLE
How to use Cube.js without dependenies of AWS services?

### ISSUE THREAD

**Issue by cadfurt** [cube-js/cube.js#341]
I am using Cube.js to make graphics with mongodb. For default, the graphs are saved in localStorage of the browser, but to put in a real world, the documentation says that we have to use the aws services to persist the dashboards. Has some manner of make this without this dependency?

**Solution that I'd like:**
Instead of using local storage, the application should be able to create a database on the server to be accessible to other users without the need to use AWS services.

**Comment by paveltiunov** [comment]
Hey @cadfurt ! Thanks for posting this! Answered here: https://stackoverflow.com/questions/59636431/how-to-use-cube-js-without-dependenies-of-aws-services/59670510#59670510

**Comment by paveltiunov** [comment]
@cadfurt Does it answer your question?
