### ISSUE TITLE
Cubejs CONTAINS operator incompatible with Dremio ILIKE syntax

### ISSUE THREAD

**Issue by zzhang-infoblox** [cube-js/cube.js#3413]
**Describe the bug**
Dremio doesn’t support the Cubejs generated query using the [CONTAINS](https://cube.dev/docs/query-format#filters-operators-contains) operator. The CONTAINS operator in Cubejs uses ILIKE operator on the backend, but this conflicts with the Dremio [ILIKE ](https://docs.dremio.com/sql-reference/sql-functions/functions/ILIKE/?parent=binary)operator, which causes the Cubejs query can’t not be parsed in Dremio.

**To Reproduce**
Cubejs filter:
```
  "filters": [
    {
      "member": "VDS.query",
      "operator": "contains",
      "values": [
        "csp"
      ]
    }
  ]
```

Cubejs query sent to Dremio: 
```
WHERE (qname ILIKE CONCAT('%', 'csp', '%'))
```
This will raise “Failure parsing the query.” in Dremio. 

**Expected behavior**
I expect the `ILIKE` operator looks like this such that it works in Dremio:
```
WHERE (ILIKE (qname, CONCAT('%', 'csp', '%'))
```

**Screenshots**

**Version:**
cubejs: v0.26.57

**Additional context**

**Comment by vignesh-123** [comment]
There is a file called cube.js\packages\cubejs-dremio-driver\driver\DremioQuery.js
You will find likeIgnoreCase function within this file
You can change that function to suit the needs of the specific database

**Comment by rongfengliang** [comment]
@zzhang-infoblox i think you use one old dremio driver . it has fixed for a long time 
please upgrade to latest version

**Comment by zzhang-infoblox** [comment]
Tested with the latest version 0.26.63 and worked as expected now. 

Thanks for the help. Closing this issue now.
