### ISSUE TITLE
Better change-log for removal of deprecated features

### ISSUE THREAD

**Issue by inventionlabsSydney** [cube-js/cube.js#3434]
G'day team,

I am concerned with the lack of "breaking change" notices in the change log.

when client-core PR's #3118 and #3135 removed the "category" from pivot this caused a breaking change that was undocumented in the change log and also wouldn't comply with the new version tag.
When upgrading from 0.28.0 to 0.28.1, we reviewed the change-log and deemed nothing of importance to worry about, net result is this caused breaking production issues for our platform, a patch version should never result in this.

After careful review we have identified that there's a lack of standards in regards to the deprecation and removal of features and also the use of semver for the project as a whole.

Some examples of this would be adding or removing features which are then released as a patch instead of a minor version.
Breaking production changes released without a major number change. 

Anyways, I think it's important to standardise this and stop the community being bitten by such actions.

Thanks,
Karl.

**Comment by paveltiunov** [comment]
Please see https://github.com/cube-js/cube.js/blob/master/DEPRECATION.md for deprecation notices.
