### ISSUE TITLE
Cube.js container stopped as connection to Redis got interrupted

### ISSUE THREAD

**Issue by sravikiran** [cube-js/cube.js#3437]
**Problem**

The cube.js server in one of our environments got crashed and from the log we found that it happened because of the connection to Redis. I saw the following error in the log:

_Error: Redis connection to path-to-redis failed - getaddrinfo ENOTFOUND path-to-redis_

We restarted the server and it is working fine now. But this issue can happen again and will cause an outage of our product. Is there a way to handle these errors globally and not let the server stop abruptly?

**Comment by sravikiran** [comment]
@paveltiunov Can you please respond me on this? Let me know if there is a way to handle such errors and point me to the documentation as I couldn't find it.

**Comment by paveltiunov** [comment]
Hey @sravikiran ! Thanks for pointing this out! While it's beneficial to have Redis network failover in Cube.js itself it isn't always possible to recover from these errors while Cube.js process is running. The best practice would be to check live probes https://cube.dev/docs/rest-api#livez and restart Cube.js whenever an instance is dead. Also do auto restarts on these crashes. For example, Kubernetes does this by default.
