### ISSUE TITLE
Unable to create PrestoDB project

### ISSUE THREAD

**Issue by SriSivaC** [cube-js/cube.js#344]
**Describe the bug**
Unable to create a cubejs project using the cubejs-cli for PrestoDB

**To Reproduce**
on the Command line , type this and press enter...
_

> cubejs create <projectName> -d presto

_
**Expected behavior**
A directory should be created where you can work on your project. This directory should contain all required dependencies related to prestodb

**Issue**
`Creating project structure
- Installing server dependencies
npm WARN deprecated @hapi/joi@14.5.0: This version is no longer maintained
npm WARN deprecated @hapi/hoek@6.2.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @hapi/marker@1.0.0: This module is no longer maintained
npm notice created a lockfile as package-lock.json. You should commit this file.
+ @cubejs-backend/server@0.13.11
added 286 packages from 214 contributors and audited 3305 packages in 36.762s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

- Installing DB driver dependencies

Cube.js Error ---------------------------------------

Error: Unsupported db type: presto
    at Function.driverDependencies (/home/d3v310p3r/Documents/cube/mongoPreAggTest/node_modules/@cubejs-backend/server-core/core/index.js:385:13)
    at Function.driverDependencies (/home/d3v310p3r/Documents/cube/mongoPreAggTest/node_modules/@cubejs-backend/server/index.js:120:29)
    at createApp (/usr/local/lib/node_modules/cubejs-cli/cubejsCli.js:94:41`

**Version:**
0.13.7

**Comment by paveltiunov** [comment]
@SriSivaC It should be `prestodb` instead: https://cube.dev/docs/connecting-to-the-database
