### ISSUE TITLE
How to connect to specific redis

### ISSUE THREAD

**Issue by EzraTsai** [cube-js/cube.js#3442]
If i want to connect cube.js to my own built redis, what should I do.
I use `CUBEJS_REDIS_URL` which is claimed by [official  document](https://cube.dev/docs/deployment/overview#redis). So, for example, if my own redis port is 31.71.195.218.
Should I use write `CUBEJS_REDIS_URL=redis://31.71.195.218:6379/0` in my backend .env file? I use many combination like, `redis://31.71.195.218:6379`, `redis://31.71.195.218`, ect. However, they all shows
```
process in uncaughtException:  { Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }
```
in my terminal. It seems that this environment variable  `CUBEJS_REDIS_URL` doesn't useful.

Any help/clarifications would be helpful; thanks.

**Comment by eawooten** [comment]
Hi @EzraTsai. Were you ever able to get this issue resolved? I have had a similar issue recently.

**Comment by brhelwig** [comment]
I didn't dig into the issue enough to confirm this is the cause, but it seemed like when you're running in dev mode you can _only_ use the in-process memory store so configuring redis causes things to break.

**Comment by eawooten** [comment]
I was able to resolve my particular issue with process described in this other issue.
https://github.com/cube-js/cube.js/issues/2737
