### ISSUE TITLE
React dashboard cannot get error

### ISSUE THREAD

**Issue by ZheweiZhong** [cube-js/cube.js#3443]
When I create a dashboard-app, and try to start it in localhost:3000, it shows "Cannot GET /" error.
Last time I did the same thing it works, but now it doesn't work.
Very appreciative if someone can fix it.

**Comment by rchkv** [comment]
Hi @ZheweiZhong 👋 

What dashboard type do you create? What OS and Cube version are you using?
Thanks in advance :)

**Comment by ZheweiZhong** [comment]
Well, I've solved it by switching from windows to ubuntu OS, many thanks.
