### ISSUE TITLE
MySQL to Postgres PreAggregations

### ISSUE THREAD

**Issue by SriSivaC** [cube-js/cube.js#345]
**Is your feature request related to a problem? Please describe.**
Unable to create pre-aggregations in postgres while using mysql as primary db

**Describe the solution you'd like**
External pre-aggregations are to be supported 

**Additional context**
date_trunc and timestamp are few functions that are creating issues while using this.

**Comment by paveltiunov** [comment]
@SriSivaC Thanks for posting this! To add more context: there's `error: function date_trunc(unknown, text) does not exist` error when Postgres tries to select from downloaded pre-aggregations because date type downloaded as text from MySQL.

**Comment by paveltiunov** [comment]
@SriSivaC Supported in Cube Store right now.
