### ISSUE TITLE
Vue `query-builder` removes any granularity when adding dimensions

### ISSUE THREAD

**Issue by ntma** [cube-js/cube.js#3458]
**Describe the bug**
Starting a query config without dimensions and then adding a dimension will cause the `granularity` of the time dimensions to vanish.

**To Reproduce**
1. Create an app with a query-builder component; 
2. Feed the query-builder with a query configuration without dimensions;
3. Change the query configuration to add a new dimension;
4. See the `granularity` of the time dimension disappear.

**Example**
In the following CodeSandbox we can find an example to reproduce this bug.

https://codesandbox.io/s/nuxtjs-cube-granularity-bug-1888s?file=/components/CubeChart.vue

The example contains two query configs to swap:
* `querySwap1`: config without dimensions. (initial query);
* `querySwap2`: same config as `querySwap1` but with a dimension added.

and two query-builder/graphs:
* Graph1: shows the bugged result when swapping to the second config;
* Graph2: shows the expected result. (Will only show when swapping to the second config);

At the bottom of the html page there is a print of the input and output `timeDimensions` , where the output is given by the `query-builder`.

**Expected behavior**
Adding/removing dimensions should not affect the `timeDimensions` granularity.

**Version:**
* NuxtJs: 2.15.8;
* @cubejs-client/core: 0.28.38;
* @cubejs-client/vue: 0.28.38;

**Comment by ntma** [comment]
After some digging, it seems that the culprit is [this](https://github.com/cube-js/cube.js/blob/2be8636260c06bc353aa41327b095ae612d6196a/packages/cubejs-client-vue/src/QueryBuilder.js#L353) heuristics function.

Looking deeper into the definition of `defaultHeuristics` ([this section of code](https://github.com/cube-js/cube.js/blob/2be8636260c06bc353aa41327b095ae612d6196a/packages/cubejs-client-core/src/utils.js#L109)), it seems that if `oldQuery.dimensions.length === []` and `newQuery.dimension.length > 0` is true, then the granularity is forced to `undefined`. 

Is this intentional?

**Comment by vasilev-alex** [comment]
@ntma yes, it's intentional. However, you can disable the default heuristics, or even pass your own if you need so using the `stateChangeHeuristics` prop.
