### ISSUE TITLE
Error: unexpected response Forbidden Issue with "cubejs create d3-dashboard -d postgres"

### ISSUE THREAD

**Issue by ramuece09** [cube-js/cube.js#3464]
I am running the above command to create the service, but its giving below error. Please guide me

npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
npm ERR! code 1
npm ERR! path C:\Upwork\d3-dashboard\node_modules\@cubejs-backend\cubestore
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node bin/post-install
npm ERR! Cube.js Cube Store Installer ---------------------------------------
npm ERR!
npm ERR! Error: unexpected response Forbidden
npm ERR!     at Object.downloadAndExtractFile (C:\Upwork\d3-dashboard\node_modules\@cubejs-backend\shared\src\http-utils.ts:80:11)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR!     at C:\Upwork\d3-dashboard\node_modules\@cubejs-backend\cubestore\js-wrapper\src\post-install.ts:12:7
npm ERR!
npm ERR! Need some help? -------------------------------------
npm ERR!
npm ERR!   Ask this question in Cube.js Slack: https://slack.cube.dev
npm ERR!   Post an issue: https://github.com/cube-js/cube.js/issues

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ramec\AppData\Local\npm-cache\_logs\2021-09-21T06_01_08_513Z-debug.log

Cube.js Error ---------------------------------------

Error: npm install --save-dev @cubejs-backend/server failed with exit code 1
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\cubejs-cli\src\utils.ts:14:16)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.cp.emit (C:\Program Files\nodejs\node_modules\cubejs-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

**Comment by rchkv** [comment]
Hi @ramuece09 👋 


The recommended way is to use [Docker-based setup](https://cube.dev/docs/getting-started/docker/). Your issue may be related to GitHub limits. We use releases to store binaries for Cube Store, when npm/yarn runs post-install script we send a request to Github's API to fetch the release’s assets. It works now.
