### ISSUE TITLE
Clarify pre-aggregation build error messages

### ISSUE THREAD

**Issue by joshhubers** [cube-js/cube.js#3469]
**Describe the bug**
I've started testing out `ROLLUP_ONLY` mode for a staging environment and a handful of my queries get a `Error: No pre-aggregation exists for that query`. And some get `"Error: Your configuration restricts query requests to only be served from pre-aggregations, and no pre-aggregation was found matching this query. Either update your pre-aggregations or disable rollup only mode in your Cube.js configuration."`.

@igorlukanin replied to me in this slack thread: https://cube-js.slack.com/archives/CC0403RRR/p1632169055242600

Stating that the difference between the two is:
- `No pre-aggregation exists for that query` should mean "No pre-aggregation table has been built for this query yet"
- `No pre-aggregation was found matching that query...` means your query does not match an existing pre-aggregate.

I see that the second message is relatively new, and isn't a terrible output, but when combined with the vagueness of the first it gets confusing.

@igorlukanin's recommendation for the first message would be something like: `No pre-aggregation table has been built for this query yet.`

I tend to agree with this suggestion, but maybe would also offer an action item to tell the developer this is expected and no action is required such as:

`No pre-aggregation table has been built for this query yet. Please wait while the worker populates your aggregate`

**Version:**
0.28.38

**Additional context**
Probably a good first issue. If you give me the thumbs up on the message I would be happy to fork and open an MR.

**Comment by paveltiunov** [comment]
@joshhubers Hey Josh! Thanks for the feedback! It's helpful. cc @keydunov
