### ISSUE TITLE
Docs : menu is truncated on mobile

### ISSUE THREAD

**Issue by ThomasKientz** [cube-js/cube.js#3479]
The bottom of the menu is hidden and some links are not reachable :

<img width="318" alt="Capture d’écran 2021-09-23 à 09 22 03" src="https://user-images.githubusercontent.com/10157845/134468856-f2645594-a51b-40bd-827c-2be5f8173374.png">

**Comment by hassankhan** [comment]
Hi @ThomasKientz :wave:

Thanks for reporting this issue, investigating now

**Comment by hassankhan** [comment]
Should be fixed now, thanks again for reporting @ThomasKientz 👍
