### ISSUE TITLE
Your dashboard app does not support adding of static charts

### ISSUE THREAD

**Issue by HardRock4Life** [cube-js/cube.js#3492]
![image](https://user-images.githubusercontent.com/21273349/134874279-3e7a9a6e-2383-4800-bfb7-12206d70d350.png)

Hello! What could be the reason for this error to appear?

I use Clickhouse and trying to create a dashboard app using Angular template.

**Comment by HardRock4Life** [comment]
Alright, we've got the `Build` tab where I tried to build the chart using Angular->ng2 configuration and it caused the error.
On the other hand, when I tried to create the same chart in the `Dashboard App` app, then it added all fine.

![image](https://user-images.githubusercontent.com/21273349/134878166-e3339603-ed51-49b5-831e-4fd2b52afe32.png)

But why is it so?

**Comment by vasilev-alex** [comment]
Hi @HardRock4Life! Adding charts from the Playground is supported only for `static` dashboards. The only Angular dashboard we have is dynamic (it has a query builder, so you can add charts directly from there), thus you don't need the Playground to add charts.
