### ISSUE TITLE
Empty DB Schema Please check connection settings

### ISSUE THREAD

**Issue by sys-auditing** [cube-js/cube.js#3496]
**Problem**

I got this message error when using  http://localhost:4000/#/schema url:
`Empty DB Schema
Please check connection settings
`

I have mariadb version *10.3.22-MariaDB-1ubuntu1* installed in my system .

**Related .env parameters**
```json
# Cube.js environment variables: https://cube.dev/docs/reference/environment-variables
CUBEJS_DEV_MODE=true
CUBEJS_DB_TYPE=mysql
CUBEJS_DB_SOCKET_PATH=/var/run/mysqld/mysqld.sock
CUBEJS_DB_NAME=test
CUBEJS_DB_USER=admin
CUBEJS_DB_PASS=yyyyy
CUBEJS_DB_PORT=3306
CUBEJS_API_SECRET=secret
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_WEB_SOCKETS=true
```

Thank you

**Comment by sys-auditing** [comment]
The issue is due to my database name `sys`, so when using another name works perfectly.
Is it a bug?

**Comment by paveltiunov** [comment]
@sys-auditing Are you using `test` or `sys` as a `CUBEJS_DB_NAME`?

**Comment by sys-auditing** [comment]
@paveltiunov i'm using ```sys``` .

Thanks

**Comment by paveltiunov** [comment]
@sys-auditing `sys` schema is indeed hidden during schema loading as its system. Could you please elaborate on your use case using it?

**Comment by asiri123** [comment]
@paveltiunov could you please suggest a working solution for this issue.

**Comment by AxiomaAbsurdo** [comment]
Same issue with a MySQL database on AWS RDS instances.
