### ISSUE TITLE
Create an issue and pull request templates

### ISSUE THREAD

**Issue by brenopolanski** [cube-js/cube.js#35]
GitHub now supports **issue templates** via a markdown file called `issue_template.md` in the root or `.github/` folder of your repo!

There is also added support for **pull request** templates via a markdown file called `pull_request_template.md` in the root or `.github/` folder of your repo!

- Example: https://github.com/OSBI/saiku/blob/development/.github/ISSUE_TEMPLATE.md
- About: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by paveltiunov** [comment]
Hi @brenopolanski ! Thanks for posting this and for the info! Yeah. Github open source checklist is on our TODO list. We'll use this issue to track the status of this task.
