### ISSUE TITLE
Cubestore: Error during create table: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by vincent-benbria** [cube-js/cube.js#3510]
**Describe the bug**
When a new pre-aggregation is added, but before the refresh worker has time to fully finish creating it, all queries that trigger this preaggregation will return this error. This is also seen when querying on a timezone that is not in the preaggregation list (requerying on that timezone does seem to work). I have also seen that on normal, fully precalculated pre-aggregation when they have not been queried for a day or two.

```
Error during create table: CREATE TABLE a_4f0f298c1808714405000002_preagg.name_of_preagg20210801_0h3gtjx3_bkqab5mm_1glc3cv (`columnA` varchar(255), `columnB` varchar(255), `columnC` timestamp, `columnD` bigint, `columnE` bigint) LOCATION ?: User: Create table failed: Internal: Error during downloading of temp-uploads/a_4f0f298c1808714405000002_preagg.name_of_preagg20210801_0h3gtjx3_bkqab5mm_1glc3cv.csv.gz: No such file or directory (os error 2)
```

**To Reproduce**
1. Create a massive dataset (to give a time windows where all pre-aggregation are not built yet)
2. Setup cube with multi-tenancy (not sure if relevant)
3. Setup multiple pre-aggregations (to give more of a window as well)
4. Query some measure/dimension that would hit a pre-aggregation (querying the past makes it event more a problem)

**Expected behavior**
Either the error does not happen (in cubestore) or at least cube captures it and re-runs the query without the benefit of the pre-aggregation, turning a failure into a slow query instead.

**Version:**
v0.28.40

**Additional context**
Pre-aggregation in question:
```
SurveyCategory: {
            measures: [
                CubeA.measureA,
                CubeA.measureB
            ],
            dimensions: [
                CubeA.dimensionA,
                CubeA.id
            ],
            timeDimension: CubeA.date,
            granularity: `day`,
            partitionGranularity: `month`,
            refreshKey: {
                every: `1 hour`,
                incremental: true,
                updateWindow: `7 day`
            }
        },
```

**Comment by ilya-biryukov** [comment]
@paveltiunov I agree with the suggestion to use `S3` and avoid the use `REMOTE_DIR` in production.
However, there is a real bug in our code. It can sometimes affect testing instances too, even when running multiple instances on the local filesystem. It's a race condition and it does not happen very often.

**Comment by PieterVanZyl-Dev** [comment]
We can reproduce this error on our kuberenetes cluster and we have a similar setup

    Create a massive dataset (to give a time windows where all pre-aggregation are not built yet)  ✔️
    Setup cube with multi-tenancy (not sure if relevant) ❌
    Setup multiple pre-aggregations (to give more of a window as well)  :white_check_mark: ✔️
    Query some measure/dimension that would hit a pre-aggregation (querying the past makes it event more a problem)   ✔️

**Comment by paveltiunov** [comment]
@PieterVanZyl-Dev Do you have S3 or GCS set up?

**Comment by PieterVanZyl-Dev** [comment]
We were using remote dir

This is no longer reproducible after we reduced the size of our database from 4 million records to less than half a million.

This also resolves #3448

Our client doesn't have S3 nor GCP in their kubernetes cluster, so we need remote dir to work. 
 

I suspect this and #3448 is directly related to database/table size

**Comment by paveltiunov** [comment]
Minio support was contributed by @PieterVanZyl-Dev and should be used instead of `CUBESTORE_REMOTE_DIR` for production purposes when S3 and GCS are not an option.

**Comment by vincent-benbria** [comment]
This PR should close https://github.com/cube-js/cube.js/issues/2642 and not this one.

**Comment by pandamien** [comment]
Hi guys, @paveltiunov 
i'm still facing this issue so would like to know what would be the solution in this case, if you are self hosting cubejs and doesn't S3, GCS or MInio ? does it mean you cannot build pre-aggregations using cubestore(local dir)? any thought would be really helpful, thanks.

**Comment by magno32** [comment]
Mentioning this because this is the top hit on Google for this error.

This was happening to us in dev mode, on Windows.

Problem seems to go away by disabling wsl in docker desktop. In our tests, the problem did not exist on our Linux or Mac hosts.
