### ISSUE TITLE
ecom-dump-d3-example.sql does not exist. 

### ISSUE THREAD

**Issue by erikjenks** [cube-js/cube.js#353]
**Describe the bug**
While following the guide to set up a [database/d3 dashboard tutorial](https://d3-dashboard.cube.dev/setting-up-a-database-and-cube-js), the `ecom-dump-d3-example.sql` file does not exist.

**To Reproduce**
1. Go to [](https://d3-dashboard.cube.dev/setting-up-a-database-and-cube-js)
2. Try the first command `curl http://cube.dev/downloads/ecom-dump-d3-example.sql > ecom-dump.sql`
3. running `cat ecom-dump.sql` returns:
```
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: downloads/ecom-dump-d3-example.sql</li>
<li>RequestId: 320CBB889D0E1EB2</li>
<li>HostId: c4FeKSYQ9SOl2YGiJnoBZ3UJqLqVf9k87PpRRX+KvXoqE9mo60WPuyWN7stpuYn+q1s1D2HDlgE=</li>
</ul>
<hr/>
</body>
</html>
```

**Expected behavior**
I would expect to see a valid sql file.

**Screenshots**
![image](https://user-images.githubusercontent.com/7226787/72552681-696fac00-3865-11ea-93df-4f483d5338e4.png)

**Comment by keydunov** [comment]
Hey @erikjenks,

The file was missing, thank you for bringing this up! I've just reuploaded the SQL example dump and it should work fine now.

**Comment by katherynhrabik** [comment]
hi @keydunov - just wanted to add onto this by saying that using the same steps to reproduce, I'm getting the following sql error: 

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>

**Comment by jromest** [comment]
Hey @keydunov, I'm also following the guide to set up a [database for react-dashboard tutorial](https://react-dashboard.cube.dev/overview-and-analytics-api#setting-up-a-database-and-cubejs), the ecom-dump.sql file does not exist.

**Comment by zzehli** [comment]
> **Edit:** running the cURL command with an extra -L flag works!
> 
> ```
> curl -L http://cube.dev/downloads/ecom-dump.sql > ecom-dump.sql
> ```
> 
> Hey @keydunov, I'm also following the guide to set up a [database for react-dashboard tutorial](https://react-dashboard.cube.dev/overview-and-analytics-api#setting-up-a-database-and-cubejs), the ecom-dump.sql file does not exist.
> 
> ecom-dump.sql
> 
> ```
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body bgcolor="white">
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>CloudFront</center>
> </body>
> </html>
> ```

this file seems to be the same sql: `https://cube.dev/downloads/ecom-dump-d3-example.sql`
