### ISSUE TITLE
Update docs to say single-element boolean arrays are allowed as query filters

### ISSUE THREAD

**Issue by zda** [cube-js/cube.js#3577]
**Is your feature request related to a problem? Please describe.**
The docs say boolean filters should have at least two children, but this is an awkward requirement, and not currently true in the backend implementation.

**Describe the solution you'd like**
Endorsing the point of view that boolean filters should be able to take less than two children, and updating the docs to reflect this.

**Describe alternatives you've considered**
The alternative is disallowing single-element arrays, but this creates more work at the point of query building.

**Comment by hassankhan** [comment]
Thanks for reporting this, @zda! 💯
