### ISSUE TITLE
Funnel step names cannot contain spaces

### ISSUE THREAD

**Issue by hassankhan** [cube-js/cube.js#359]
**Describe the bug**
When defining steps for a funnel [as described in the docs](https://cube.dev/docs/funnels#funnel-parameters-steps), a step name with spaces in it cannot be used. For example, given a step name 'Awaiting Approval', the generated SQL for the step is as follows:

```sql
LEFT JOIN (
  select
    user_id user_id,
    created_at t
  from
     <STEP_QUERY>
) awaiting _approval_events ON negotiation_events.user_id = awaiting _approval_events.user_id
AND awaiting _approval_events.t >= negotiation_events.t
```

**To Reproduce**
1. Create a new funnel
2. Add a new step to the funnel with a name that has a space character
3. Attempt to run any query against the funnel cube
4. Get error `Error: syntax error at or near "."`

**Expected behavior**
I expected it to generate the SQL correctly i.e. `awaiting _approval_events` should be `awaiting_approval_events`

**Version:**
v0.15.0

**Comment by paveltiunov** [comment]
@hassankhan Hey Hassan! Thanks for posting this! Yep. It's known issue we need to fix.
