### ISSUE TITLE
Multi tenancy best practices

### ISSUE THREAD

**Issue by pranav-loops** [cube-js/cube.js#3595]
Here are the following 2 approaches for multi tenancy I have in mind.

**Approach 1: Multi tenancy via the Cube SQL**
```javascript
// cube definition
const {
  securityContext: { tenantId },
} = COMPILE_CONTEXT;

cube(`MyCube`, {
  sql: `SELECT * FROM ${tenantId}.mytable`,
})
```
**Approach 2: Multi tenancy via the Cube config**

```javascript
// cube.js config file
module.exports = {
    driverFactory: ({ securityContext }) => new MySQLDriver({
      database: `${securityContext.tenantId}`,
    })
};

// cube definition
cube(`MyCube`, {
  sql: `SELECT * FROM mytable` 
})
```

**Questions**

1. Which are the pros/cons of defining the config + schema in the above approaches. Is one approach always better than the other?
2. How does the environment variable CUBEJS_DB_MAX_POOL behave in each of these cases. For instance if it's set to 10, are there max 10 connections per **database** driverFactory instance (per tenantId in above case) or are the max number of **datasource** TCP connections (irrespective of the individual database) is 10?
3. Is there a corresponding minimum no. of connections created per tenant in either case, or is it always on demand?
4. How does this impact caching? Does the cache key generated in both the cases consider the dynamic nature of the tenantId to invalidate the cache (ex. every 10 seconds - which is the default)

**Comment by igorlukanin** [comment]
I think your config would work for MySQL. Thanks for your note about pre-aggregations. I hope your database will be able to handle all connections. I guess the default value is ~100 for MySQL.

(Closing this issue now, but feel free to follow up if you have any questions.)

**Comment by tannirusrinivas** [comment]
Hi,

Can anyone post oracle driver code in cube.js file
