### ISSUE TITLE
Bug in chartPivot() / tablePivot() when using timeDimension "last 24 hours"

### ISSUE THREAD

**Issue by 0is1** [cube-js/cube.js#361]
**Describe the bug**
With query something like this:
```
{
"limit":10000,
"measures":["XXX.count"],
"timeDimensions":[{
  "dimension":"XXX.createdat",
  "granularity":"hour",
  "dateRange":"last 24 hours"}
]}
```

It seems that `resultSet.loadResponse.data` includes correct data (only "hourly" hits that have count > 0) but `resultSet.chartPivot()` returns data based on dateRange and granularity?

So in this case because granularity is hour and and dateRange is "between two days" => there will be 48 items in chartPivot / tablePivot data.

**To Reproduce**
1. Use query that is something like described above
2. Compare `resultSet.loadResponse.data` to `resultSet.chartPivot()` / `resultSet.tablePivot()`
3. `resultSet.loadResponse.data` should include only data that is created within 24 hours and count > 0
4. `resultSet.chartPivot()` / `resultSet.tablePivot()` return data that seems to follow the pattern `HOURS_PER_DAY * DAYS_IN_DATE_RANGE` => in this case 24 * 2 = 48

**Expected behavior**
`resultSet.chartPivot()` / `resultSet.tablePivot()`  should return only data from within the date range (in this case there should be 24 items in the result)

**Screenshots**
![resultSets](https://user-images.githubusercontent.com/852249/73518821-fd19ae80-4407-11ea-9a31-0168622071f6.png)

**Version:**
```
"@cubejs-client/core": "^0.15.2",
"@cubejs-client/react": "^0.15.0",
```

**Additional context**
Slack conversation https://cube-js.slack.com/archives/CC0403RRR/p1580200363166700

**Comment by paveltiunov** [comment]
@0is1 Hey Janne! Thanks for posting this! I believe it can be single line fix here: https://github.com/cube-js/cube.js/blob/2783446dbd7739412377309a34d68da02739a25b/packages/cubejs-client-core/src/ResultSet.js#L174
