### ISSUE TITLE
v0.28.42 release is incomplete

### ISSUE THREAD

**Issue by rksh1997** [cube-js/cube.js#3618]
**Describe the bug**

Regarding this release https://github.com/cube-js/cube.js/releases/tag/v0.28.42
It's incomplete. The reason is https://github.com/cube-js/cubejs-playground-templates were not rebuilt for `cubejs-playground` package.
the `public` folder of `cubejs-playground`  package is 2 months old.
the scripts inside `charts-gen`  folder in `cubejs-playground` package must be ran to update the charts.
Otherwise the feature is not present. This cannot be inside a pull request since it's uglified and anyone can put malware in it. Thus an internal developer must do it.

**Version:**
0.28.42

**Comment by rksh1997** [comment]
Hey, @vasilev-alex 
I was told by Igor to assign you for this, but I don't have permission to do so.

Could you please handle it ?

**Comment by vasilev-alex** [comment]
@rksh1997 good catch! we'll fix that

**Comment by vasilev-alex** [comment]
@rksh1997 I rebuilt it, will be available in the next release
