### ISSUE TITLE
Playground: Cannot read property 'dataSource' of undefined

### ISSUE THREAD

**Issue by vincentwinkel** [cube-js/cube.js#3637]
**Describe the bug**
```
TypeError: Cannot read property 'dataSource' of undefined
    at node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:109:30
    at node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:78:15
```

After investigation, I see the playground sends the request `http://localhost:4000/playground/db-schema` without any payload. If I change in the source:
```js
dataSource: req.body.dataSource || 'default',
```
by
```js
dataSource: (req.body || {}).dataSource || 'default',
```
Then it works. But I guess it's not a correct fix.

**To Reproduce**
1. Go to http://localhost:4000/#/schema
2. See error on the sidebar

**Expected behavior**
The schemas appearing

**Version:**
0.28.49

**Comment by paveltiunov** [comment]
Hey @vincentwinkel ! Could you please share how do you launch your cube.js server? Is it docker or npx?

**Comment by vincentwinkel** [comment]
Sorry, here is my init:
```js
      const core = CubejsServerCore.create({
        logger: (msg, params) => console.log(`${msg}: ${JSON.stringify(params)}`),
        basePath: this.getPath(),
        schemaPath: join(process.env.PATH_INTERNAL_ASSETS.replace(process.env.PATH_ROOT, '.'), '/schema'),
        // driverFactory: () => new PostgresDriver({ ssl: { rejectUnauthorized: false } })
      });
      core.initApp(app); // app is an Express app
```
No docker for now, just as an Express middleware.

**Comment by paveltiunov** [comment]
This way of embedding Cube inside of the express app isn't supported anymore by the core team. Please consider providing PR if it's still an issue.
