### ISSUE TITLE
Allow both `sql` and `every` in `refreshKey`

### ISSUE THREAD

**Issue by phitranphitranphitran** [cube-js/cube.js#365]
**Is your feature request related to a problem? Please describe.**
I would like to specify a custom SQL select statement for a `refreshKey` but also specify how often it can be executed. Currently this is not possible.
For example:
```
refreshKey: {
  sql: `select max(updated_at) from ...`,
  every: `30 seconds`
}
```
If that was my `refreshKey`, I would expect the behaviour to be "to check the cache, execute `select max(updated_at) from ...`, but no more than once every 30 seconds".

**Describe the solution you'd like**
Allow specifying both `sql` and `every` in the options of `refreshKey`.

**Describe alternatives you've considered**
N/A

**Additional context**
Me and @paveltiunov talked about this [in this thread](https://cube-js.slack.com/archives/CC0403RRR/p1580933237347300?thread_ts=1580923334.337600&cid=CC0403RRR) of the slack channel.

**Comment by dvins** [comment]
This would be a welcome feature. We use Athena and build a half dozen cubes several of which rely on very complex, costly views that only need to be up to date within about an hours timeframe. This wold significantly reduce the operational cost as right now some of these views are being updated every few minutes based on how fast new events come in.

**Comment by hassankhan** [comment]
Added in https://github.com/cube-js/cube.js/pull/3054
