### ISSUE TITLE
continueWaitTimeout flag not working

### ISSUE THREAD

**Issue by sourav-jha** [cube-js/cube.js#3653]
We have updated the values of "continueWaitTimeout" option to 120,  still we are getting following error after 5 sec.
`{"error":"Continue wait","stage":{"stage":"Executing query","timeElapsed":5002}}`

1. Update the "continueWaitTimeout" config options of queryCacheOptions to 120.
2. execute the cubejs query.
**Expected behavior**
The expected behavior was this will block until we get the result.

**Version:**

 "@cubejs-backend/postgres-driver": "^0.28.53",
 "@cubejs-backend/server": "^0.28.54"
**Additional context**

**Comment by paveltiunov** [comment]
Hey @sourav-jha ! There's also global `continueWaitTimeout` in orchestratorOptions. You can define it like
```
module.exports = {
  orchestratorOptions: {
    continueWaitTimeout: 120
  }
};
```
It seems to be missing in the doc @hassankhan.

**Comment by sourav-jha** [comment]
thanks @paveltiunov
