### ISSUE TITLE
Unable to unsubscribe a query from realtime data fetch

### ISSUE THREAD

**Issue by deekshith-elear** [cube-js/cube.js#3671]
Hi,
I was using cubejs to get the realtime data of a measure using example provided in https://cube.dev/docs/real-time-data-fetch#vanilla-java-script I'm getting continuous updates for the query. How can I stop the updates?

**Comment by paveltiunov** [comment]
@deekshith-elear There's an unsubscribe method returned in the result object of `load()` method. We need to document it. cc @hassankhan .
