### ISSUE TITLE
More details about measures in the meta

### ISSUE THREAD

**Issue by pyrooka** [cube-js/cube.js#368]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently, we get this response for the measures from the API when calling the meta endpoint:
```
measures:[
        {
          name:"Users.count",
          title:"Users Count",
          shortTitle:"Count",
          aliasName:"users.count",
          type:"number",
          drillMembers:[
            "Users.id",
            "Users.city",
            "Users.createdAt"
          ]
        }
```
It would be great if the type could contain the "real" type of the measures. E.g.: `count`, `sum`, `avg`, etc.. And the `sql` part from the cube would be also useful sometimes in my opinion. An example response:
```
measures:[
        {
          name:"Users.count",
          title:"Users Count",
          shortTitle:"Count",
          aliasName:"users.count",
          type:"sum",     // <-- THIS
          sql:"amount",   // <-- THIS
          drillMembers:[
            "Users.id",
            "Users.city",
            "Users.createdAt"
          ]
        }
```

As I see there is a `TODO` in the affected line already: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/compiler/CubeToMetaTransformer.js#L105

What do you think? 

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by norbertbede** [comment]
Hi, @paveltiunov  thanks to @pyrooka the issue was created we are chatted about last days. Hope this enhancement makes cubejs better and helps us to continue with Metabase integration.

**Comment by paveltiunov** [comment]
Hey @pyrooka ! Thanks for posting this! I believe we should add separate field for it. Something like `aggType` as `type` is used for formatting purpose. Also could you please elaborate on how do you want to use `sql` field? Adding it to this open API can be a security flaw.

**Comment by pyrooka** [comment]
Hi @paveltiunov! Yup, you are right.
1. The `aggType` would be great
2. The `sql` field was just an idea. To be honest, I didn't really think about it.

**Comment by paveltiunov** [comment]
@pyrooka Sounds good! Let's add only `aggType` then.

**Comment by paveltiunov** [comment]
@pyrooka Would love a PR here!

**Comment by Neko1313** [comment]
Hi guys, I think it is still worth adding a `sql` field as in some bi systems it would be nice to give transparency to the user how the metric is collected, I don't think it would be insecure as it is nothing more than a summary.
