### ISSUE TITLE
Typescript TCubeMember missing meta

### ISSUE THREAD

**Issue by System-Glitch** [cube-js/cube.js#3682]
**Is your feature request related to a problem? Please describe.**
The type `TCubeMember` is missing a field for the meta:
```ts
  export type TCubeMember = {
    type: TCubeMemberType;
    name: string;
    title: string;
    shortTitle: string;
  }
```

**Describe the solution you'd like**
Add `meta: any` to this type.

```ts
  export type TCubeMember = {
    type: TCubeMemberType;
    name: string;
    title: string;
    shortTitle: string;
    meta: any;
  }
```

**Comment by System-Glitch** [comment]
I will open a PR soon.

**Comment by hassankhan** [comment]
Hi @System-Glitch :wave: 

Thanks for reporting this - the issue seems to now have been resolved 👍
