### ISSUE TITLE
What is the best approach for handling two (or more) dimension cubes and two (or more) separate fact cubes for the reporting?

### ISSUE THREAD

**Issue by Pavel-Deryagin** [cube-js/cube.js#3690]
**Problem**

Hi! In terms of cube joins what would be the best approach for handling two dimension cubes and two separate fact cubes  ?
For example we have:
- cube named Campaigns that has information on all of the campaigns. this cube is a dimension cube, because it has mostly descriptive fields.
- cube named Games that has information on all of the games. this cube is a dimension cube, because it has mostly descriptive fields
- cube named DailyEvents that has information on ad requests (like how many ad requests there are in a day etc.). this cube is a fact cube, because it has mostly measure fields and fk to Campaigns and Games cubes
- cube named SSPEvents that has information on sessions (like how many sessions there are in a day etc...). this cube is a fact cube, because it has mostly measure fields and fk to Campaigns and Games cubes

In the end we would like to build a report that would show how many sessions and how many ad requests split by Campaigns and Games. There is no way to connect Campaigns and Games, because they are two separate entities.
Current approach where we defined 'belongsTo' relationship in DailyEvents and in SSPEvents to both dimensions - does not work and it throws an error:
```
Error: Can't find join path to join 'SSPEvents', 'DailyEvents', 'Campaigns', 'Games', 'Dates'
```
NB: 'Dates' is another cube that has descriptive information on dates and has the same 'belongsTo' relationship from DailyEvents and SSPEvents

**Related Cube.js schema**
```javascript
cube(`SSPEvents`, {
  sql: `SELECT * FROM sspevents`,
  title: ` `,

  joins: {
    Campaigns: {
      relationship: `belongsTo`,
      sql: `${SSPEvents}.creative_id = ${Campaigns}.creative_id`
    },
    Games: {
      relationship: `belongsTo`,
      sql: `${SSPEvents}.game_id = ${Games}.game_id and ${SSPEvents}.platform_id = ${Games}.platform_id`
    },
	Dates: {
      relationship: `belongsTo`,
      sql: `${SSPEvents}.date = ${Dates.time}`
    }
	
}
	
	....
	
measures: {

    bidRequests: {
      title: `Bid requests NEW`,
      sql: `case
               when total_count
              else null
            end`,
      type: `sum`,
      shown: true
    }
  }

}
	
....
	
	
cube(`DailyEvents`, {
  sql: `
 SELECT * FROM dailyevents`,
  title: ` `,

  joins: {
    Campaigns: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.creative_d = ${Campaigns}.creative_id`
    },
    Games: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.game_id = ${Games}.game_id and ${DailyEvents}.platform_id = ${Games}.platform_id`
    },
	Dates: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.date = ${Dates.time}`
    }
	
}
	
	....

  measures: {

    rowCount: {
      type: `count`,
      title: `Dummy (count)`,
      shown: true
    }
  }
}
	
....


cube(`Campaigns`, {
  sql: `SELECT * FROM campaigns`

  joins: {

  },

  measures: {

  },

  dimensions: {

    creativeId: {
      sql: `creative_id`,
      type: `number`,
      primaryKey: true,
      shown: false,

    }
   }
}
	
....
	
cube(`Games`, {
  sql: `SELECT * FROM games`,
  title: ` `,

  joins: {

  },

  dimensions: {
    gameId: {
      sql: `game_id`,
      type: `number`

    },

    platformId: {
      sql: `platform_id`,
      type: `number`,
      shown:false
    },
    
    gameName: {
      title: `Name`,
      sql: `game_name`,
      type: `string`,
      shown: true
    }
    
  }	
}
....

cube(`Dates`, {
  sql: `SELECT * FROM dates`
  ,
  title: ` `,

  joins: {

  },

  dimensions: {
    time: {
      title: `Date`,
      sql: `generated_dt`,
      type: `time`,
      primaryKey: true,
      shown: true
    }
  }
}
```

**Comment by Pavel-Deryagin** [comment]
@igorlukanin can you please help ?

**Comment by ivan-vdovin** [comment]
Moved to #3903
