### ISSUE TITLE
Error: npm install @cubejs-backend/oracle-driver

### ISSUE THREAD

**Issue by boPMjuan** [cube-js/cube.js#370]
**Describe the bug**
I have a problem when I want install @cubejs-backend/oracle-driver. The dependency oracledb@3.1.2 is deprecated. I use node v12.13.1

**To Reproduce**
1. npm i @cubejs-backend/oracle-driver

**Expected behavior**
I expected to install @cubejs-backend/oracle-driver. 

**Screenshots**
![issue](https://user-images.githubusercontent.com/41596953/74170691-54373480-4bfb-11ea-9556-48d4d7662ff6.PNG)

**Additional context**
I have a windows

**Comment by paveltiunov** [comment]
Hey @boPMjuan ! You may want to checkout this one: http://oracle.github.io/node-oracledb/INSTALL.html#-36-node-oracledb-installation-on-windows-with-instant-client-zip-files

**Comment by boPMjuan** [comment]
Thanks. I have the Oracle Instant Client, but it did not allow me to install @cubejs-backend/oracle-driver. The solution was to install node v10.16.0. The library only works with this version.

**Comment by paveltiunov** [comment]
Here's PR for this issue: #375
