### ISSUE TITLE
BigQuery pre-aggregation refreshkey updateWindow parameter generate an SQL error

### ISSUE THREAD

**Issue by ThibaultFoureur** [cube-js/cube.js#371]
**Describe the bug**
Cubejs is generating a refresh query using datetime and timestamp at the same time when using the refreshkey updateWindow parameter. This query result into a type error coming from BigQuery.

https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/BigqueryQuery.js#L94

**To Reproduce**
Use BigQuery as the main database and create a cube with a preAggregation schema with a refreshkey that uses an updateWindow such as this : 
`
refreshKey: {
        every: '1 day',
        incremental: true,
        updateWindow: '7 day'
      }
` 

**Result**
Generated the SQL code : 
`SELECT CASE  WHEN CURRENT_TIMESTAMP() < DATETIME_ADD(TIMESTAMP(‘2020-02-04T23:59:59Z’), INTERVAL 7 day) THEN FLOOR(UNIX_SECONDS(CURRENT_TIMESTAMP()) / 86400) END`

Which generate the following error : 
`No matching signature for function DATETIME_ADD for argument types: TIMESTAMP, INTERVAL INT64 DATE_TIME_PART. Supported signature: DATETIME_ADD(DATETIME, INTERVAL INT64 DATE_TIME_PART) at [1:30]`

(Comparing a Timestamp with a datetime wouldn't work anyway in the WHEN clause.)

**Manual correction**
Changed `DATETIME_ADD` and `DATETIME_SUB` into `TIMESTAMP_ADD` and `TIMESTAMP_SUB` in cube.js/blob/master/packages/cubejs-schema-compiler/adapter/BigqueryQuery.js

**Comment by paveltiunov** [comment]
Hey @ThibaultFoureur ! Thanks for posting this! There's already PR proposed in #367. I'll follow up with possible solution there.

**Comment by paveltiunov** [comment]
Fixed in #367
