### ISSUE TITLE
docker build remove yarn cache

### ISSUE THREAD

**Issue by wenerme** [cube-js/cube.js#3715]
**Describe the bug**

yarn cache waste 300MB

**To Reproduce**

https://diving.npmtrend.com/?image=cubejs%2Fcube%3Av0.28.59-alpine

![image](https://user-images.githubusercontent.com/1777211/142825735-36ee9a23-5003-4cf6-bcdc-0a436cadf8b1.png)

**Expected behavior**

**Screenshots**

**Version:**

v0.28.59-alpine

**Additional context**

**Comment by ovr** [comment]
Hello @wenerme ,

Good catch 👍 

I've created a PR with a fix for that!

Thanks

**Comment by ovr** [comment]
https://diving.npmtrend.com/?image=cubejs%2Fcube%3Av0.28.60-alpine

Fixed in `v0.28.60`

876.83MB -> 509.62MB

🚀
