### ISSUE TITLE
Dashboard app generation is broken

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#3727]
**Describe the bug**
The dashboard app fails when navigating to the "Build" tab.

**To Reproduce**
1. Create a new Cube app
2. Create a new dashboard app by selecting "Dynamic Dashboard with React, AntD, and Recharts"
3. Run it and navigate to the "Build" tab
4. See the error in the browser and in the console

**Expected behavior**
The "Build" tab works.

**Screenshots**
<img width="965" alt="Screenshot 2021-11-24 at 20 42 02" src="https://user-images.githubusercontent.com/3852894/143279522-2a1cc5a0-899c-4e58-986a-87c48f4bb418.png">

**Version:**
0.28.59

**Comment by vasilev-alex** [comment]
Should be fixed now
