### ISSUE TITLE
Different SQL Clients not working

### ISSUE THREAD

**Issue by vk99** [cube-js/cube.js#3741]
When connecting with Excel and KNIME with MySQL driver to Cube.js SQL API not able to get the data with various errors. Successfully connected with Dbeaver.

Excel error:
Details: "MySQL: Internal("Initial planning error: Error during planning: Invalid function 'timediff'")
disabled backtrace"

KNIME error:
Unsupported("table factor: Derived { lateral: false, subquery: Query { with: None, body: Select(Select { distinct: false, top: None, projection: [Wildcard], from: [TableWithJoins { relation: Table { name: ObjectName([Ident { value: \"Payment\", quote_style: None }]), alias: None, args: [], with_hints: [] }, joins: [] }], lateral_views: [], selection: None, group_by: [], cluster_by: [], distribute_by: [], sort_by: [], having: None }), order_by: [], limit: Some(Value(Number(\"5\", false))), offset: None, fetch: None }, alias: Some(TableAlias { name: Ident { value: \"tempTable_980843615313704399\", quote_style: Some('`') }, columns: [] }) }")
disabled backtrace

**Comment by ovr** [comment]
Hello @vk99 ,

Right now, We don't support it. There is an issue/epic https://github.com/cube-js/cube.js/issues/3528 where you can write down a comment which will be helpful for us to make the decision to support/prioritize it.

Thanks
