### ISSUE TITLE
Support underscore escaping in cube store

### ISSUE THREAD

**Issue by JaySunSyn** [cube-js/cube.js#3742]
**Describe the bug**
Filtering a value that contains an underscore gives unexpected results.

Cube Store doesn't support underscore escaping yet.

**To Reproduce**
1. Go to the playground
2 A. Filter by "contains" "abc_11" => no results
2 B. Filter by "equals" "abc_11" => results

**Expected behavior**
Underscore values should be supported.

**Screenshots**

**Version:**
v0.28.60

**Comment by nilansht** [comment]
How exactly is it working ? What do we need to send to allow "_" to be searched in "contains" ? @JaySunSyn @paveltiunov
