### ISSUE TITLE
SQL API connection to Excel

### ISSUE THREAD

**Issue by carla-fera** [cube-js/cube.js#3752]
Our team is trying to connect Cube.js to Excel, given a project that’s going on currently in our company. I know that the SQL API does not have the ability as of now, of connecting to Excel. But, by any chance, is anyone developing a solution for that or has encountered the same use case and was able to solve it? Additionally, I am including a link to a video from a platform called “AtScale” which has the functionality we are looking for.

https://www.youtube.com/watch?v=yuvKPblR0d8&t=1458s

**Comment by paveltiunov** [comment]
Hey @carla-fera ! Excel is in our BI support pipeline. Please stay tuned.

**Comment by MarkGStacey** [comment]
This would be fantastic. Implementing an ODBO connector that allows Excel to connect as if to a traditional OLAP or SSAS source would be wonderful. 
I had on my radar possibly re-implementing an open source Mondrian ODBO connector to connect to cube, but hasn't made it to the top of my list yet

https://github.com/zhifac/xmlaconnect

**Comment by paveltiunov** [comment]
Please see #3906 for progress.
