### ISSUE TITLE
How to add a run button similar to the playground with Vue ?

### ISSUE THREAD

**Issue by ThomasKientz** [cube-js/cube.js#3757]
Hi !

I am building a query builder (with Vue) and I am trying to add a "run query" button similar to the one on the playground. What's the trick to update measures, dimensions without actually running the query ? I have used https://github.com/cube-js/cube.js/tree/master/examples/vue-query-builder as a starting point. I have taken a look at [the actual source code of the playground](https://github.com/cube-js/cube.js/tree/master/packages/cubejs-playground) but I don't understand how this button works... 

Any hints would be much appreciated :) 

@vasilev-alex maybe ?

**Comment by igorlukanin** [comment]
@ThomasKientz Thanks for the question. Let's continue our conversation in Slack (https://cube-js.slack.com/archives/CC0403RRR/p1638364226415300). We'll post the solution here when it's resolved.

**Comment by vasilev-alex** [comment]
@ThomasKientz looks like it's not possible to achieve this in Vue as `QueryBuilder` always uses `QueryRenderer` behind the scenes which loads the query on every change.

https://github.com/cube-js/cube.js/blob/1bafff4f79a37acd67460afe78df4305c43a9638/packages/cubejs-client-vue/src/QueryBuilder.js#L237

We may need to refactor the client-vue a bit, to allow use QueryBuilder on it's own. 

Please, let me know if you're interested to submit a PR.

**Comment by ThomasKientz** [comment]
@vasilev-alex I will submit a PR
