### ISSUE TITLE
Sandbox in frontend documentation page not working as expected

### ISSUE THREAD

**Issue by anandbhaskaran** [cube-js/cube.js#3792]
**Describe the bug**
The sandbox code on the frontend documentation page results in an error instead of visualizing the data

**To Reproduce**
1. Go to [Frontend Documentation](https://cube.dev/docs/frontend-introduction/vue)
2. Scroll down to any of the examples built with Sandbox
4. See error -> `Could not find/install babel preset '@vue/app': Cannot find plugin '@vue/app' or '@vue/babel-preset-app'`

**Expected behavior**
The data visualization is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/6847984/145404846-fcae3b15-d0fa-43f9-9d58-caa7dc1bbc81.png)

**Version:**
Current live documentation

**Comment by ivan-vdovin** [comment]
Hey @anandbhaskaran ! Thanks for posting this one! We know that some of them are not working. Will fix this soon.

**Comment by ivan-vdovin** [comment]
Fixed with [PR #3847](https://github.com/cube-js/cube.js/pull/3847)
