### ISSUE TITLE
Issues with countDistinct measures & segments in rollup pre-aggregations

### ISSUE THREAD

**Issue by kaja78** [cube-js/cube.js#3795]
**Describe the bug**
External rollup pre-aggregations in CubeStore are used for count distinct measures & segments only when:
1) there is no dimension in rollup
2) there is only one segment in rollup

It fails in following cases:
1) Multiple segments are defined in rollup => rollup is not used for CubeJS query
2) One segment and one dimension is defined  in rollup => CubeJS query fails with "Error during planning: Table or CTE with name '[original table]' not found"

**To Reproduce**
1. Configure CubeJS to use Postgres as source database and CubeStore as storage for external pre-aggregations
2. Define testing cube:
```
cube(`Columns`, {
    sql: `select table_schema::varchar,table_name::varchar,column_name::varchar from information_schema.columns`,
    measures: {
        columnCount: {
            type: `count`
        },
        distinctColumnNames: {
            type: `countDistinct`,
            sql: `column_name`
        }
    },
    dimensions: {
        schema: {
            sql: `table_schema`,
            type: `string`
        },
        table: {
            sql: `table_name`,
            type: `string`
        },
        column: {
            sql: `column_name`,
            type: `string`
        }
    },
    segments: {
        information_schema: {
            sql: `${CUBE}.table_schema  = 'information_schema'`
        },
        pg_catalog: {
            sql: `${CUBE}.table_schema  = 'pg_catalog'`
        },
    },
    preAggregations: {
        mainRollup: {
            external: true,
            measures: [Columns.columnCount,Columns.distinctColumnNames],
            segments: [Columns.information_schema/*,Columns.pg_catalog*/]
        },
        schemaRollup: {
            external: true,
            measures: [Columns.columnCount,Columns.distinctColumnNames],
            dimensions: [Columns.schema],
            segments: [Columns.information_schema/*,Columns.pg_catalog*/]
        }
    }
});

```
3. Run bellow query:
```
{
  "measures": [
    "Columns.distinctColumnNames"
  ],
  "timeDimensions": [],
  "segments": [
    "Columns.information_schema"
  ],
  "filters": [],
  "order": {
    "Columns.distinctColumnNames": "desc"
  },
  "dimensions": [
    "Columns.schema"
  ]
}
```
This fails with `Internal: Error during planning: Table or CTE with name 'information_schema.columns' not found`. It looks like that CubeJS tries to source DB SQL query on CubeStore.
4. Uncomment Columns.pg_catalog segments in both preAggregation definitions in Columns cube.
5. Re-run above query. The query is executed successfully, but schemaRollup is not used.
6. Run bellow query:
```
{
  "measures": [
    "Columns.distinctColumnNames"
  ],
  "timeDimensions": [],
  "segments": [
    "Columns.information_schema"
  ],
  "filters": [],
  "order": {},
  "dimensions": []
}
```
The query is executed successfully in source database, but schemaRollup is not used.

I can see that pre-aggregation tables are created and loaded correctly in CubeStore. It seems that the pre-aggreation tables in CubeStore are just not used by above queries under given conditions. For additive metric (columnCount), the preaggregations are always used as expected.

**Expected behavior**
The preaggregations should be used and correct results should be returned.

**Version:**
0.28.61

**Additional context**
The cube and queries are just simplification for demonstration purposes. We are facing the issues in unique users analytics.

**Comment by igorlukanin** [comment]
@kaja78 Would you mind doing a small experiment? I suggest removing segments from your cube definition and removing them from rollup definitions as well. You can replace them with "filters with a dimension that equals some value". Does this allow you to use the rollup?

**Comment by kaja78** [comment]
With schema:
```
cube(`Columns`, {
    sql: `select table_schema::varchar,table_name::varchar,column_name::varchar from information_schema.columns`,
    measures: {
        columnCount: {
            type: `count`
        },
        distinctColumnNames: {
            type: `countDistinct`,
            sql: `column_name`
        }
    },
    dimensions: {
        schema: {
            sql: `table_schema`,
            type: `string`
        },
        table: {
            sql: `table_name`,
            type: `string`
        },
        column: {
            sql: `column_name`,
            type: `string`
        }
    },
    preAggregations: {
        mainRollup: {
            external: true,
            measures: [Columns.columnCount,Columns.distinctColumnNames],
        },
        schemaRollup: {
            external: true,
            measures: [Columns.columnCount,Columns.distinctColumnNames],
            dimensions: [Columns.schema],
        }
    }
});

This fails with :
```
{
  "measures": [
    "Columns.distinctColumnNames"
  ],
  "timeDimensions": [],
  "segments": [],
  "filters": [
    {
      "member": "Columns.schema",
      "operator": "equals",
      "values": [
        "information_schema"
      ]
    }
  ],
  "order": {},
  "dimensions": []
}
```

This works and uses CubeStore pre-aggregation:
```
{
  "measures": [
    "Columns.distinctColumnNames"
  ],
  "timeDimensions": [],
  "segments": [],
  "filters": [
    {
      "member": "Columns.schema",
      "operator": "equals",
      "values": [
        "information_schema"
      ]
    }
  ],
  "order": {
    "Columns.distinctColumnNames": "desc"
  },
  "dimensions": [
    "Columns.schema"
  ]
}
```

So the dimension used in filtering must be included in result set.

Anyway, in our real use case we use segments to define intervals on time dimension (last 7 days, previous 7 days, last 30 days, previous 30 days) in order to pre-aggregate countDistinct values for common queries. It is not possible to include time dimension in our queries...
However I can probably derive flags from time dimension and use them as dimension for filtering (like 7daysFlag=last/previous) to workaround this.

**Comment by ivan-vdovin** [comment]
@kaja78 

> However I can probably derive flags from time dimension and use them as dimension for filtering (like 7daysFlag=last/previous) to workaround this.
Yes, you definitely can do that.

As for the error, it looks weird. Could you, please, double-check and confirm that your schema is exactly the same as what you've posted here?

**Comment by kaja78** [comment]
Confirming. You can easily test with Postgres. I intentionally demonstrated the issue on data dictionary table, so no extra DDL is needed to execute on Postgres...

It seems, that if external pre-aggregation can be used and we are filtering on column which is not included in resultset, CubeJS decides correctly to issue query against cubestore, but the SQL is generated like for source DB (source table name is included in from clause, which does not exist in Cubestore). 
But if we just add the column being filtered to the query dimension element, the SQL is generated properly = proper pre-aggregation table name is used in from clause.

**Comment by paveltiunov** [comment]
@kaja78 Not reproduced on the latest version with schema and query you provided.
