### ISSUE TITLE
Missing Mapping of MSSQL for CubeStore 

### ISSUE THREAD

**Issue by niramsellem** [cube-js/cube.js#3827]
**Is your feature request related to a problem? Please describe.**
i am getting this error on CubeCloud when trying to create pre-aggregation:
```
Error: Error during create table: CREATE TABLE prod_pre_aggregations.appointment_appointment_map_rollup_tvuxzwq_vptm4bps_1grmkpj (`appointment__ansewrs_defect` int, `appointment__date` datetime2, `appointment__id` int, ...): User: Custom type 'datetime2' is not supported
    at WebSocket.<anonymous> (/cube/node_modules/@cubejs-backend/cubestore-driver/src/WebSocketConnection.ts:87:30)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/cube/node_modules/ws/lib/websocket.js:1008:20)
```
i am connected to mssql database and date columns are defined with datetime2.
after consulting on Slack it has been suggested that the mapping is missing on CubeStore

**Comment by ivan-vdovin** [comment]
Hi @niramsellem !
Thanks for posting this. Adding @ovr so he can take a look.

**Comment by paveltiunov** [comment]
Hey @niramsellem ! It's indeed missing mapping. Looking forward to contributions here. Here's an example for MySQL https://github.com/cube-js/cube.js/blob/2124c5fafceb6875ff94402d9560f93593a487dc/packages/cubejs-mysql-driver/src/MySqlDriver.ts#L42.
