### ISSUE TITLE
Compilation fails after adding CubejsClientModule to AppModule 

### ISSUE THREAD

**Issue by zaracooper** [cube-js/cube.js#3834]
**Describe the bug**
When I try to add `CubejsClientModule` to the `AppModule` of a newly created bare Angular 12 app, I get this error:
```
Error: node_modules/@cubejs-client/core/index.d.ts:789:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'order' must be of type 'IntrospectedTQueryOrderObject | IntrospectedTQueryOrderArray | undefined', but here has type 'TQueryOrderObject | TQueryOrderArray | undefined'.

789     order?: TQueryOrderObject | TQueryOrderArray;
        ~~~~~

  node_modules/@cubejs-client/dx/index.d.ts:20:5
    20     order?: IntrospectedTQueryOrderObject | IntrospectedTQueryOrderArray;
           ~~~~~
    'order' was also declared here.

✖ Failed to compile.
```

**To Reproduce**
I followed the instructions exactly on the [ `@cubejs-client/ngx` documentation page.](https://cube.dev/docs/@cubejs-client-ngx#api)

**Expected behavior**
I expected the app to compile successfully after adding the `CubejsClientModule` import to `AppModule`.

**Version:**
**@cubejs-client/ngx**: 0.29.0
**Angular**: 12.1.2

**Additional Context**
Here's the `app.module.ts`.
```typescript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { CubejsClientModule } from '@cubejs-client/ngx';
import { environment } from 'src/environments/environment';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

const cubejsOptions = {
  token: environment.CUBEJS_API_TOKEN,
  options: { apiUrl: environment.CUBEJS_API_URL }
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    CubejsClientModule.forRoot(cubejsOptions)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by ivan-vdovin** [comment]
Hi @zaracooper !
Thanks for posting this. Let me add @hassankhan to take a look there.

**Comment by hassankhan** [comment]
Hi @zaracooper :wave:

As a temporary workaround, could you set `skipLibCheck: true` in your `tsconfig.json`? I appreciate it's not ideal, but it should at least get you up and running for the meantime 👍

**Comment by zaracooper** [comment]
Thanks for the reply @hassankhan . I'll use the Cube REST API with a service instead. Thank you though.

**Comment by vasilev-alex** [comment]
Closing this as it has been fixed
