### ISSUE TITLE
Add option to set CUBEJS_ROLLUP_ONLY based on securityContext

### ISSUE THREAD

**Issue by wgalecki** [cube-js/cube.js#3839]
**Is your feature request related to a problem? Please describe.**
I have users with different permission levels accessing the cube.js API and would like to be able to let some of them query raw data while restricting others to only use preaggregated data.

**Describe the solution you'd like**
This would ideally happen in the `queryRewrite` method or some other hook that would have access to the `securityContext`. I would then be able to check the user role and set the option to only use preaggregated data for some users.

**Describe alternatives you've considered**
I'm considering validating the query and checking if the date range fits in the preaggregated data period but this would require manually updating it whenever the cube preaggregation configuration is changed. Another solution would be providing the cube metadata to the `queryRewrite` method so that validation can be implemented based on it.

**Comment by ivan-vdovin** [comment]
Hi @wgalecki !
Thanks for your feedback! 

Right now it's hard for me to understand the whole situation.
Could you tell me a little more about your use case, please? What permission levels do you have? Why it's important for you to ignore preaggs for some of the users?

**Comment by wgalecki** [comment]
Hi 👋 

The idea is not to skip preaggregations but to enable some users to query data whether it was preaggregated or not. While, at the same time prohibiting some users from querying data that has not been preaggregated. As an example, we have a database table that contains the last 12 months of data but querying it is expensive. We create a cube.js schema and use it to preaggregate the last 90 days of data. We want our **users** to only be able to query only data that has been preaggregated while giving **admins** access to the full 12 months of data.

**Comment by wgalecki** [comment]
I think the solution that would require least effort and still enable query validation based on cube definition would be passing the cube metadata to `queryRewrite`, like so:
```javascript
const metaConfig = await this.getCompilerApi(context).metaConfig({
  requestId: context.requestId,
});

const queries = Array.isArray(query) ? query : [query];
const normalizedQueries = await Promise.all(
  queries.map(async (currentQuery) => validatePostRewrite(await this.queryRewrite(normalizeQuery(currentQuery), context, metaConfig)))
);
```
I can submit a PR if you're interested in this.

**Comment by igorlukanin** [comment]
@wgalecki Could you please elaborate on this part?

> We want our users to only be able to query only data that has been pre-aggregated while giving admins access to the full 12 months of data.

What is the difference between user and admin permissions? Is it correct to assume that you'd like your users to have access to the last 90 days of data only?

**Comment by wgalecki** [comment]
@igorlukanin Exactly, I want users to be able to only query the last 90 days of data, which is preaggregated by cube.js. Admins should be able to query the full 12 months of data.

**Comment by paveltiunov** [comment]
@wgalecki You can add or remove the pre-aggregations definition from cube based on security context using dynamic schemas https://cube.dev/docs/schema/advanced/dynamic-schema-creation#dynamic-schema-creation
