### ISSUE TITLE
Fallback when PreAggregation cache is not available

### ISSUE THREAD

**Issue by yosi-codefresh** [cube-js/cube.js#3867]
**Problem**
My current architecture is BigQuery as a source database and postgres as pre aggregation database.
I'm trying to understand what happens when pre aggregations database is not available for any reason(e.g connection issues / database is down and so on).
will it give results from source database? will it return an error?
Currently i get an error when trying to run queries 
**The Error from cube.js which i get:**
in response payload: "Error: connect ECONNREFUSED 127.0.0.1:5432"

Is there any configuration which i can set to fallback to source data base in case database is not available?

can you please elaborate more about fallback mechanism for cubs js for all the cache layers(source database / pre aggregation / Redis)?

**Comment by paveltiunov** [comment]
Hey @yosi-codefresh ! Currently, if you have pre-aggregation in place your Cube Store should be 100% available. If it's unavailable it'll throw an error. Postgres usage as an external database is deprecated. Please consider using Cube Store.
