### ISSUE TITLE
Retrieve data from json document stored in mongoDB

### ISSUE THREAD

**Issue by Saul-rec** [cube-js/cube.js#3878]
Hello everyone. I am currently developing an API that connects to cube.js to retrieve data from a java entity stored in mongodb in json format. The structure with which it is stored in mongo is as follows.
![image](https://user-images.githubusercontent.com/28061008/148295597-475f4e49-c484-4a19-a302-92175eca061c.png)

The mongo json representation:
[mongodb data.txt](https://github.com/cube-js/cube.js/files/7818134/mongodb.data.txt)

I have been reading the documentation and following some examples but I have not found a way in which I can get all the data inside a json node, for example get the id, accountNumber and in a single call all the information inside the metadata array.
My cube.js schemas are compose in the following way.
![image](https://user-images.githubusercontent.com/28061008/148298366-7a7471de-ac7c-4557-97b3-eb1ccf3d2adb.png)
![image](https://user-images.githubusercontent.com/28061008/148298385-aaf6fcfd-7894-4d5c-b03b-4daf45e3579e.png)
![image](https://user-images.githubusercontent.com/28061008/148298419-dd2a3a88-04f0-46ad-8740-5824dd01a461.png)

Schemas was initially generated using the command: `cubejs generate -t data` and from cube.js playground
So, my problem right now is I am able to get some data from cube.js api but is not really usefull because I need map this info again to  a java class and right now I am only getting isolated data.
![image](https://user-images.githubusercontent.com/28061008/148297489-602b839f-92b6-44c9-8d16-efefc3ebe54d.png)

There is a possible way to get data from mongo in a more complete way? Like json format, or at least get the id, accountNumber and all metadata corresponding to one document.
Thanks in advance

**Comment by paveltiunov** [comment]
Hey @Saul-rec ! Do you mean you want dynamically define schema based on the contents of your table?

**Comment by Saul-rec** [comment]
Hello @paveltiunov ! 
Not really, I mean we have these three cubes: cube1 --> (`Data`, { ...}); // cube2 --> (`DataInvoicedocuments`, { ...}); and cube3 --> (`DataInvoicedocumentsMetadata`, { ...}); and we are able to get some data when we call a measure or dimension, but here is the thing. From cube2, cubejs can only access the id and accountNumber fields defined in invoicesDocuments node; from cube3 I can access the metadata node fields in mongo which are key, and value (see the first img I share in the first post). If I only call cube3 the response is not returned in a structured way so it is not known which key and value belongs to which document (bucket 2) so I have tried using joins or combining data between buckets but we could not find a way that when we call a dimension using the cube-js api we can get a combination of data from cube2 and cube3 (id, accountNumber, and the metadata array that belong to this specific document).
We have done it this way because I think cubejs is not able to return the complete json object from mongo, right?

**Comment by paveltiunov** [comment]
@Saul-rec I guess you're looking for https://stackoverflow.com/questions/59826986/cube-js-how-to-join-two-tables-created-from-mongodb-arrays
