### ISSUE TITLE
filter returns "Invalid query format" error 

### ISSUE THREAD

**Issue by Hindls** [cube-js/cube.js#3883]
**Problem**

Hello, 

Requesting the following filter throws this error : 
`{"error":"Invalid query format: child \"filters\" fails because [\"filters\" at position 0 does not match any of the allowed types]"}
`
**Related Cube.js schema**
```
{
  "dimensions": [
    "Bank.name"
  ],
  "timeDimensions": [],
  "order": {
    "BankRepos.count": "desc"
  },
  "measures": [
    "BankRepos.count"
  ],
  "filters": [
    {
      "member": "Bank.groupe",
      "operator": "equals",
      "values": "Somevalue"
    }
  ]
}
```
Please help 🙏

**Comment by Namec999** [comment]
hello Hind how you managed to solve this, got the same issue, when trying to use queryrewrite in cube.js

**Comment by leopepe** [comment]
> "values": "Somevalue"

values must be a list, not a string. I think this was the issue.
