### ISSUE TITLE
validatedQuery returns empty filters array

### ISSUE THREAD

**Issue by leymytel** [cube-js/cube.js#3901]
**Describe the bug**
Using the QueryBuilder in a React project, the `validatedQuery` returns an empty filters array, even when the filters are valid.

**Expected behavior**
`validatedQuery` should return the filters as well.
**Screenshots**
![Screenshot from 2022-01-10 11-21-28](https://user-images.githubusercontent.com/38193378/148758294-bbcf403f-df35-4ff2-89b5-4bd6813e45f3.png)

**Version:**
"@cubejs-client/core": "^0.29.8",
 "@cubejs-client/react": "^0.29.8",

**Comment by ivan-vdovin** [comment]
Hi @leymytel and thanks for the issue! 
How did you manage to find this? How do you use validatedQuery in your app?

As far as I know, validatedQuery is for internal use only.
That could be confusing so we're going to add more details about this one in docs.
