### ISSUE TITLE
What is the best approach for handling two (or more) dimension cubes and two (or more) separate fact cubes for the reporting?

### ISSUE THREAD

**Issue by Pavel-Deryagin** [cube-js/cube.js#3903]
Duplicate to https://github.com/cube-js/cube.js/issues/3690 because nobody answered/helped for almost 2 months.
**The problem**

Hi! In terms of cube joins what would be the best approach for handling two dimension cubes and two separate fact cubes ?
For example we have:

cube named Campaigns that has information on all of the campaigns. this cube is a dimension cube, because it has mostly descriptive fields.
cube named Games that has information on all of the games. this cube is a dimension cube, because it has mostly descriptive fields
cube named DailyEvents that has information on ad requests (like how many ad requests there are in a day etc.). this cube is a fact cube, because it has mostly measure fields and fk to Campaigns and Games cubes
cube named SSPEvents that has information on sessions (like how many sessions there are in a day etc...). this cube is a fact cube, because it has mostly measure fields and fk to Campaigns and Games cubes
In the end we would like to build a report that would show how many sessions and how many ad requests split by Campaigns and Games. There is no way to connect Campaigns and Games, because they are two separate entities.
Current approach where we defined 'belongsTo' relationship in DailyEvents and in SSPEvents to both dimensions - does not work and it throws an error:

`Error: Can't find join path to join 'SSPEvents', 'DailyEvents', 'Campaigns', 'Games', 'Dates'`
NB: 'Dates' is another cube that has descriptive information on dates and has the same 'belongsTo' relationship from DailyEvents and SSPEvents

**Related Cube.js schema**

```
cube(`SSPEvents`, {
  sql: `SELECT * FROM sspevents`,
  title: ` `,

  joins: {
    Campaigns: {
      relationship: `belongsTo`,
      sql: `${SSPEvents}.creative_id = ${Campaigns}.creative_id`
    },
    Games: {
      relationship: `belongsTo`,
      sql: `${SSPEvents}.game_id = ${Games}.game_id and ${SSPEvents}.platform_id = ${Games}.platform_id`
    },
	Dates: {
      relationship: `belongsTo`,
      sql: `${SSPEvents}.date = ${Dates.time}`
    }
	
}
	
	....
	
measures: {

    bidRequests: {
      title: `Bid requests NEW`,
      sql: `case
               when total_count
              else null
            end`,
      type: `sum`,
      shown: true
    }
  }

}
	
....
	
	
cube(`DailyEvents`, {
  sql: `
 SELECT * FROM dailyevents`,
  title: ` `,

  joins: {
    Campaigns: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.creative_d = ${Campaigns}.creative_id`
    },
    Games: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.game_id = ${Games}.game_id and ${DailyEvents}.platform_id = ${Games}.platform_id`
    },
	Dates: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.date = ${Dates.time}`
    }
	
}
	
	....

  measures: {

    rowCount: {
      type: `count`,
      title: `Dummy (count)`,
      shown: true
    }
  }
}
	
....


cube(`Campaigns`, {
  sql: `SELECT * FROM campaigns`

  joins: {

  },

  measures: {

  },

  dimensions: {

    creativeId: {
      sql: `creative_id`,
      type: `number`,
      primaryKey: true,
      shown: false,

    }
   }
}
	
....
	
cube(`Games`, {
  sql: `SELECT * FROM games`,
  title: ` `,

  joins: {

  },

  dimensions: {
    gameId: {
      sql: `game_id`,
      type: `number`

    },

    platformId: {
      sql: `platform_id`,
      type: `number`,
      shown:false
    },
    
    gameName: {
      title: `Name`,
      sql: `game_name`,
      type: `string`,
      shown: true
    }
    
  }	
}
....

cube(`Dates`, {
  sql: `SELECT * FROM dates`
  ,
  title: ` `,

  joins: {

  },

  dimensions: {
    time: {
      title: `Date`,
      sql: `generated_dt`,
      type: `time`,
      primaryKey: true,
      shown: true
    }
  }
}

```

**JSON query**

```
{
  "dimensions": [
    "Campaigns.creativeName",
    "Games.gameName"
  ],
  "timeDimensions": [],
  "order": [
    [
      "SSPEvents.bidRequests",
      "asc"
    ]
  ],
  "filters": [],
  "measures": [
    "SSPEvents.bidRequests",
    "DailyEvents.rowCount"
  ]
}
```

**Comment by ivan-vdovin** [comment]
Hi @Pavel-Deryagin !
I'm sorry for that. The dev team was too busy working on new features and Cube Cloud lately. Let me close #3690 and continue here.

I think that it's a configuration issue. Are you sure that game_id and creative_id exist for all joined cubes?
Could you add a minimum working example so we can find what exactly goes wrong? E.g. define join between Campaigns and DailyEvents only to begin with.

**Comment by Pavel-Deryagin** [comment]
Hi, @ivan-vdovin!
Thanks for reaching out. I am not sure that this is a configuration issue, because as I said we have a fact table (DailyEvents cube) with foreign keys to dimensions - in our case its campaigns and games. I want to analyze data from DailyEvents cube by Campaign and Game. I can't do it right now because there is no join between Campaigns and Games, which is logical because they are two separate dimensions which are not interconnected.

All of the definitions you are looking for are in the issue description, e.g:
```
cube(`DailyEvents`, {
  sql: `
 SELECT * FROM dailyevents`,
  title: ` `,

  joins: {
    Campaigns: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.creative_d = ${Campaigns}.creative_id`
    },
    Games: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.game_id = ${Games}.game_id and ${DailyEvents}.platform_id = ${Games}.platform_id`
    },
	Dates: {
      relationship: `belongsTo`,
      sql: `${DailyEvents}.date = ${Dates.time}`
    }
	
}
```
Pavel

**Comment by Pavel-Deryagin** [comment]
@ivan-vdovin:
"I think that it's a configuration issue. Are you sure that game_id and creative_id exist for all joined cubes?" - yes. we have two separate fact tables (two separate cubes with measures) that have different measures and different source tables. both of them have some of the same dimensions (e.g game and campaign).

**Comment by ivan-vdovin** [comment]
@Pavel-Deryagin 
There is typo in ${DailyEvents}.creative_d = ${Campaigns}.creative_id` 
creative_d --> creative_id
Could you confirm it's correct in your schema?

**Comment by Pavel-Deryagin** [comment]
The typo is because I wrote it by hand here (not copy paste).

Yes, it is correct in our schema.

**Comment by Pavel-Deryagin** [comment]
Hi.
This is turning into a joke, honestly :D I've waited for a month on a response which pointed to a typo that wouldn't generate the error I was talking about. Now it has been way over a month since the last comment and still no resolution.

Any comments on that?

**Comment by paveltiunov** [comment]
Hey @Pavel-Deryagin ! I'm sorry to hear you've waited for so long. Our team tries to answer every community question as much as possible however it isn't always feasible to do it on time given the growing number of questions.

As far as I understand `SSPEvents` can belong to either game or campaign. Not to two of them for the same row? If it's the case you'd need to use data blending to make one single cube out of those two and join it `SSPEvents` and `DailyEvents` instead of separate ones. Please see https://cube.dev/docs/schema/advanced/data-blending#top.

**Comment by Pavel-Deryagin** [comment]
Hi, @paveltiunov.
Thanks for the info, however:
"As far as I understand SSPEvents can belong to either game or campaign. Not to two of them for the same row?" - It **can** belong to both of them for the same row (as in dimensional models where one fact table may reference multiple dimension tables).

Provided example of data blending is not a good solution for us as we have a lot of rows in each table and that won't make sense to make it a union on them. Plus it would be hard to maintain preaggregations for that new data blended cube.

Is there another solution for this ?

**Comment by paveltiunov** [comment]
@Pavel-Deryagin Data blending through union is the best practice for such types of data modeling problems both in terms of performance for modern cloud data warehouses and data modeling outcomes.
