### ISSUE TITLE
UpdateSchema But Do not Compile All Files

### ISSUE THREAD

**Issue by peak-c** [cube-js/cube.js#3935]
**Problem**

Hello, my application needs to update the schema every query, but I find it very slow. 

I found that the reason is that compile schema takes a long time. I found the source code compilerapi js -> PrepareCompiler. ts -> 
DataSchemaCompiler. JS.
In the compile method, const toCompile is the entire schema.
 
From what angle should I solve this slow problem? How can I just compile the changed schema?

help!
thanks!
@paveltiunov

**Comment by ivan-vdovin** [comment]
@peak-c 

> I find it very slow.
What exactly do you mean by this? How much time does it take in your case?

**Comment by peak-c** [comment]
![image](https://user-images.githubusercontent.com/16895558/149741659-94cd312a-adf7-4d60-a995-70977c694481.png)

Compiling schema cost 10 seconds

> Hello, my application needs to update the schema every query, but I find it very slow.
> 
>  I found that the reason is that compile schema takes a long time. I found the source code compilerapi js ->  PrepareCompiler. ts ->
DataSchemaCompiler. JS.
> In the compile method, const toCompile is the entire schema.
> 
> From what angle should I solve this slow problem? How can I just compile the changed schema?

**Comment by peak-c** [comment]
@ivan-vdovin
Hello, I have bypassed this problem in other ways (for example, controlling the number of compile files). I will close the problem.

Thank you.
