### ISSUE TITLE
count/sum measures with numeric filters not working

### ISSUE THREAD

**Issue by klose4711** [cube-js/cube.js#3939]
**Describe the bug**
If filters are set with numerical values, then count and sum measures no longer return a value.
On the other hand, when filtering on string values, it works fine and the count and sum measures return the correct values.

**To Reproduce**
See example Cube schema: [cubeschema.json.txt](https://github.com/cube-js/cube.js/files/7870833/cubeschema.json.txt)

Running this query (e.g. via playground) with a filter on a string value:
```json
{
  "measures": [
    "FaBalanceOutput.countAssetNumber"
  ],
  "timeDimensions": [],
  "order": {
    "FaBalanceOutput.inServiceStartDateTime": "asc"
  },
  "segments": [
    "FaBalanceOutput.fixedAssetsIntangiblesFilter"
  ],
  "filters": [
    {
      "member": "FaBalanceOutput.assetCategory",
      "operator": "equals",
      "values": [
        "AIB"
      ]
    }
  ]
}
```
Is correctly returning the count value:
![image](https://user-images.githubusercontent.com/69890936/149527742-18cb45a1-6958-4aad-8e48-a0686db2e86e.png)

Running the same query, but with a filter on a numeric value:
```json
{
  "measures": [
    "FaBalanceOutput.countAssetNumber"
  ],
  "timeDimensions": [],
  "order": {
    "FaBalanceOutput.inServiceStartDateTime": "asc"
  },
  "segments": [
    "FaBalanceOutput.fixedAssetsIntangiblesFilter"
  ],
  "filters": [
    {
      "member": "FaBalanceOutput.sumOfTransferCostsBelowZero",
      "operator": "equals",
      "values": [
        "-608"
      ]
    }
  ]
}
```
Is just returning an empty response:
![image](https://user-images.githubusercontent.com/69890936/149528046-8a06621d-c313-45cd-a086-1f34af921f3a.png)

Not even an error is shown, just an empty response.

**Expected behavior**
We would expect the count and sum measures to return the correct values for both queries.
In the special case that no data is left by the filters, a 0 should be returned.

This actual works when filtering on string values and we would expect this to be the case for numeric values as well.

**Screenshots**
s.a.

**Version:**
v0.28.35

**Additional context**
Running cube via docker image `cubejs/cube:v0.28.35-alpine`

**Comment by ivan-vdovin** [comment]
Hi @klose4711 !
Actually what you see here is not a difference between num and string filtering but a diff between filters for measures and dimensions (sumOfTransferCostsBelowZero is a measure and assetCategory is a dimension):
https://cube.dev/docs/query-format#filtering-dimensions-vs-filtering-measures

it means that second example just showing that there is no data for your query:
<img width="1233" alt="Screenshot 2022-01-21 at 13 17 22" src="https://user-images.githubusercontent.com/26839230/150509859-1380b1e1-b8ae-4947-b4aa-e8bcdaf9c93c.png">
