### ISSUE TITLE
 comparedaterange is not working in cubejs SDK API

### ISSUE THREAD

**Issue by amiya-elear** [cube-js/cube.js#3954]
cubejs version: v0.29.20

 Comparedaterange is not working in cubejs SDK API

When I am using comparedaterange in cubejs query by doing postman call with  "queryType: multi" its working fine and able to get the appropriate data. 

Postman API :

```
curl --location --request POST 'http://localhost:4000/cubejs-api/v1/load' \
--header 'Content-Type: application/json' \
--data-raw '
{
  "query" : "{\"measures\":[\"test_energymeter_demand_watt.xxxxxx\"],\"timeDimensions\":[{\"dimension\":\"test_energymeter_demand_watt.xxxx\",\"compareDateRange\":[[\"2020-01-01\",\"2020-01-05\"],[\"2021-01-01\",\"2021-01-05\"]],\"granularity\":\"month\"},],\"order\":{},\"filters\":[{\"member\":\"test_energymeter_demand_watt.xxxxx\",\"operator\":\"equals\",\"values\":[\"xxxxxx\"]},{\"member\":\"test_energymeter_demand_watt.yyy\",\"operator\":\"equals\",\"values\":[\"xxxxxxxxxx\"]}],}",
  "queryType": "multi"

}
```

But when i am using qubejs SDK then I am not getting any option to pass "queryType: multi" can you guys help me how can I pass this option in cubejs SDK

while using SDK: 
```js
async function result(cubejsApi) {
  const resultSet = await cubejsApi.load([{
     "measures": [
      "xxxx"
    ],
    "timeDimensions": [
      {
        "dimension": "txxxx.update_time",
        "compareDateRange": [["2020-01-01", "2020-01-05"],["2021-01-01", "2021-01-05"]],
        "granularity": "day"
      },
    ],
    "order": {},
    "filters": [
      {
        "member": "xxxx.zzzz",
        "operator": "equals",
        "values": [
          "xxxxxx"
        ]
      },
      {
        "member": "xxxx.yyyy",
        "operator": "equals",
        "values": [
          "xxxxxx"
        ]
      }
    ],
  }]);
```

With this query I am getting all data point exist in my database. But I should  get only data for given date range. 
Can anyone help me on this ?

**Comment by amiya-elear** [comment]
Any update on this guys ?

**Comment by mhd-adam** [comment]
Hi @amiya-elear, I have just posted another question #4293. On my side, I see only the data of one date range, not both date ranges. I used exactly your query configuration but no luck. Am I missing something here? I expect to receive the data of the two date ranges in the `data` array

**Comment by edy-enumo** [comment]
I am getting the same problem. When I try multiple queries using compareDateRange I get all the data from my database instead of the selected date ranges.

**Comment by vasilev-alex** [comment]
@amiya-elear, you don't need to pass any additional params (`queryType=multi`) while using Cube SDK as it's done automatically for you.
