### ISSUE TITLE
Cube.js Joins across data sources aren't supported in community edition.

### ISSUE THREAD

**Issue by manikandanguruparan** [cube-js/cube.js#396]
In my cube.js server I have 2 tables from different data sources(both of them are postgres). I'm trying to create a join on these tables but get the following error

**Error: Joins across data sources aren't supported in community edition. Found data sources: dataSource_1, dataSource_2**

I have student_details cube and test_results cube (both cubes from different data source).

I'm trying to achieve a join on student id (test_results cube) and id (student_details cube ) but get the above error in bold.

Is there a way to achieve this kind of join. Any help would be appreciated.

Thanks in advance

**Comment by paveltiunov** [comment]
@manikandanguruparan Hey Mani! As error says this feature isn't part of open source Cube.js edition. As of now there's no way you can do it using open source Cube.js edition unless you implement it yourself.

**Comment by nimajalali** [comment]
@paveltiunov Is there a paid version of CubeJS that does support this?

**Comment by vkruoso** [comment]
That is a bummer. In the feature presentation at the Community Call, it is said that all those features are available on open-source. Not sure why show it in the community call tough.
https://www.youtube.com/watch?v=mu1_PdCpfCk

**Comment by keydunov** [comment]
Hi @vkruoso,

Sorry for the confusion. We need to fix the error message.

It is available in open-source. We're still working on the docs, but you should be able to join across multiple data sources via external pre-aggregations as shown in the community call.

**Comment by vkruoso** [comment]
Hi! Thanks for the fast response. Maybe I'm running an outdated version because I'm getting the same message. Will try to update the stack and give it another try!

**Comment by vkruoso** [comment]
Seems like it is still blocked in the latest version: 0.26.52.

**Comment by vkruoso** [comment]
It actually works, but in some cases where there is some error in the configuration (like missing columns in a rollup or fields on a join) that error pops up. I think there is just a need to update the error message. Thanks a lot!

**Comment by keydunov** [comment]
Yes, we need to update the error message. Other than that it should work fine.
