### ISSUE TITLE
No way to handle cubejs.watch() errors in Angular

### ISSUE THREAD

**Issue by springyboy** [cube-js/cube.js#3961]
**Describe the bug**
Errors are not propagated through the Observable returned via cubejs.watch()

**To Reproduce**
- Configure an Angular client that consumes the CubeJs client module
- Handle errors on the observable returned from watch() with an error handler (via pipe(catchError(...)) or subscribe({error:...}))
- Invoke a query on watch that causes an error in cubejs api (invalid join, etc)

**Expected behavior**
Any errors that occur in the underlying cubejs api should be raised on the observable returned from cubejs.watch() so that these can be reported to the client application.

**example**
```js
this.results$ = this.cubejs.watch(this._querySubject)
            .pipe(
                catchError(err => {
                    console.error(`*** this will never be reached ***`)
                    return throwError(err);
                }));
```

The reason this occurs is because the Angular wrapper around the native cubjs api does not propagate errors onto the observable return (usually contains the Results). 

**Version:**
@cubejs-client/ngx 0.29.0

**Additional context**
The following code in client.ts of cubejs-client-ngx needs updating to catch and propagate error on observable

```js
public watch(query, params = {}): Observable<ResultSet> {
    return new Observable((observer) =>
      query.subscribe({
        next: async (query) => {
          const resultSet = await this.apiInstace().load(query, params);
          observer.next(resultSet);
        },
      })
    );
  }
```

**Comment by PieterVanZyl-Dev** [comment]
Currently the cubejs.load() returns errors with a catchError/Subscribe
This is probably just a missing implementation on the cubejs.watch() function

I've created a fix, please have a look and see if it's appropriate.
