### ISSUE TITLE
Couldn't query data by Quarter

### ISSUE THREAD

**Issue by bong-sc** [cube-js/cube.js#3964]
**Describe the bug**

Whenever, I’m trying to query data by “Quarter” in a time dimension with CubeJS Playground and I receive this error:

> Internal: Execution error: Internal: Arrow error: External error: Execution error: Unsupported date_trunc granularity: quarter. 

And per @ivan-vdovin , it's supposed to work. Slack: https://cube-js.slack.com/archives/CK1K6LWTF/p1642651434007500

**To Reproduce**
1. Go to 'CubeJS Playground'
2. Select any measure, time dimension
3. Select by Quarter
4. Click on Chart
5. See error

**Expected behavior**

A chart should be presented instead of the error.

**Screenshots**
<img width="2041" alt="Screen Shot 2022-01-20 at 3 01 41 pm" src="https://user-images.githubusercontent.com/86209481/150427249-d786a593-dc6d-418a-a2b0-80d414a739f5.png">

**Version:**
[0.29.21]

**Additional context**

**Comment by paveltiunov** [comment]
Hey @bong-sc ! It's WIP #3285.

**Comment by paveltiunov** [comment]
Fixed in #4011
