### ISSUE TITLE
Pre-aggregations  throws error with api request using time granularity "quarter"

### ISSUE THREAD

**Issue by shaikwasef** [cube-js/cube.js#3970]
I'm currently getting the following error while using pre-aggregations for my schemas when I use the quarter granularity in my CUBE-JS query .

`Error: Error: Internal: Execution error: Internal: Arrow error: External error: Arrow error: External error: Execution error: Unsupported date_trunc granularity: quarter`

P.S As discussed with the dev team on slack , this feature is currently not a part of CUBE-JS and hence raising issue.

**Comment by ivan-vdovin** [comment]
Hey @shaikwasef ! 
We have open PR for this one #3415 .
