### ISSUE TITLE
Extending default checkAuth

### ISSUE THREAD

**Issue by mklishevych** [cube-js/cube.js#3976]
**Problem**

I'm looking for an easy way to extend the default implementation of `checkAuth`. The idea is that on frontend side I'm passing an additional header param and on the backend side I need to validate this param against the JWT payload but only if the JWT validation succeeds. I don't see a way to do so without duplicating all the code that is there for validating of the JWT. Am I missing it?

**Related Cube.js schema**
```javascript
cubejs('JWT-TOKEN', {
  apiUrl: `${API_URL}/cubejs-api/v1`,
  headers: {
    My-custom-header: `somevalue`
  },
 });
```

**Comment by paveltiunov** [comment]
@mklishevych Most likely you're looking for https://cube.dev/docs/config#options-reference-extend-context.
