### ISSUE TITLE
SQl generation regression

### ISSUE THREAD

**Issue by revuwem** [cube-js/cube.js#3981]
**Describe the bug**
`Error: column "orders__amount" does not exist` at [react-dashboard](https://examples.cubecloud.dev/deployments/107) running on Cube Cloud

**To Reproduce**
1. Go to [react-dashboard](https://examples.cubecloud.dev/deployments/107) playground
2. Select measures from Orders schema
3. Run query

**Expected behavior**
A chart should be presented

**Screenshots**
![image](https://user-images.githubusercontent.com/47831092/150969983-078e547b-ddcb-4552-ba92-0ddeca09d1fa.png)

**Version:**
0.29.21

**Additional context**
The Orders cube has the `amount` dimension defined via a subquery. There’s also the `amountTier` case dimension referencing amount ([source](https://github.com/cube-js/cube.js/blob/master/examples/react-dashboard/schema/Orders.js#L57,L78)).
Running a query with the `amountTier` dimension leads to some SQL being generated that doesn’t make much sense and throws an error like this:
`Error: column "orders__amount" does not exist`

Here the SQL being generated:
```
SELECT 
  CASE 
    WHEN "orders__amount" < 100 
    OR "orders__amount" is NULL THEN '$0 - $100' 
    WHEN "orders__amount" >= 100 
    AND "orders__amount" < 200 THEN '$100 - $200' 
    WHEN "orders__amount" >= 200 THEN '$200 +' 
    ELSE 'Unknown' 
  END "orders__amount_tier", 
  count("orders".id) "orders__count" 
FROM 
  public.orders AS "orders" 
  LEFT JOIN ( 
    [redacted] 
  ) AS "orders_amount_subquery" ON "orders_amount_subquery"."orders__id" = "orders".id 
WHERE 
  [redacted]
GROUP BY 
  1 
ORDER BY 
  2 DESC 
LIMIT 
  10000 
```
As you can see, the joined subquery table `orders_amount_subquery` is not used anywhere in the query. Also, the `orders__amount` column is not anywhere in the FROM clause.
Qualifying `${amount}` references in the `amountTier` definition as `${Orders.amount}` doesn’t change the SQL being generated. Also, this example was working for quite a while in Cube Cloud but somehow broke a few weeks ago.

**Comment by paveltiunov** [comment]
Fixed in 0.29.23.
