### ISSUE TITLE
`cubejs create` should generate a .gitignore file to avoid `.env` being version controlled

### ISSUE THREAD

**Issue by FanaHOVA** [cube-js/cube.js#402]
**Is your feature request related to a problem? Please describe.**
When you create a new Cube.js project, it asks to add your database credentials to the `.env`. The problem is that `.env` is version controlled by default, which can accidentally expose a lot of database credentials and Cube API secrets on GitHub/GitLab if developers don't remember to add a `.gitignore` to exclude it. 

**Describe the solution you'd like**
`cubejs create` should generate a `.gitignore` file with `.env` in it. 

**Describe alternatives you've considered**
I'm creating this manually at the moment. 

**Additional context**
Happy to open a PR for this, but wasn't sure if there was a reason why it didn't exist already. Thanks!

**Comment by paveltiunov** [comment]
@FanaHOVA Hey Alessio! Thanks for posting this one! Was just thinking about it. PR would be great!

**Comment by FanaHOVA** [comment]
@paveltiunov Great, see #403 👍
