### ISSUE TITLE
Preaggregation changes the result

### ISSUE THREAD

**Issue by JoeMoggridge** [cube-js/cube.js#4027]
**Describe the bug**
Without preaggreaggregation, the values match those from the database. With preaggregation, they are slightly off. 

**To reproduce**
Cube schema: 
```
cube("Freq", {
  sql: `
        with
            times AS (
                SELECT generate_series(
                   (date_trunc('minute', NOW()) - interval '60 minutes')::timestamp,
                   (date_trunc('minute', NOW()) + interval '5 minutes')::timestamp,
                   interval '15 seconds'
                ) AS time
            )

        SELECT
            times.time,
            frequency
        FROM
            times
            left join bmrs_freq as freq on times.time = freq.time
         WHERE
            times.time > NOW() - interval '60 minutes'
         `,
  refreshKey: {
    every: "1 minute",
  },
  measures: {
    frequency: {
      sql: "frequency",
      type: "sum",
    },
  },
  dimensions: {
    time: {
      sql: "time",
      type: "time",
    },
  },

 // preAggregations: {
   //Aggregation1: {
    //  external: true,
     // measures: [CUBE.frequency],
    //  timeDimension: CUBE.time,
   //   granularity: `second`,
//    },
 // },
});

```

In both cases, I make the following query: 
 ```
http://localhost:4000/cubejs-api/v1/load?query={"measures":["Freq.frequency"],"timeDimensions":[{"dimension":"Freq.time","granularity":"second"}],"order":{},"filters":[],"dimensions":[]}&queryType=multi
```

With the preaggregation commented out, this query works correctly, it returns numbers which match with those in the database.

With the preaggregation, the numbers returned tend to be slightly too large. 

In the attached file, I've included a column with each of the two sets of returned data. I find it pretty weird that the numbers can be _nearly_, but not quite correct. How could this happen?

[difference.ods](https://github.com/cube-js/cube.js/files/7996608/difference.ods)

**Comment by paveltiunov** [comment]
Hey @JoeMoggridge ! Could you please enable `CUBESTORE_LOG_LEVEL=trace` and share create table statement used to create a table in cube store?

**Comment by JoeMoggridge** [comment]
So I've captured some logging, but I'm not sure whether I've succeeded in capturing the line you want. 
Here's what I did:

1. Add the line `CUBESTORE_LOG_LEVEL=trace` to my docker-compose file. 
2. Navigate to my local .cubestore directory. Delete that directory. 
3. Start cube using `docker-compose up --build > MyFile.txt`
4. Go to the developer playground and make the same request as before.

[MyFile.txt](https://github.com/cube-js/cube.js/files/8016777/MyFile.txt)

**Comment by paveltiunov** [comment]
@JoeMoggridge log level wasn't applied. What database do you use as a source of data? Also data schema, cube query, imported csv files and actual example of a discrepancy would be helpful here.

**Comment by JoeMoggridge** [comment]
I use a postgres database. Here is the table structure:
```
CREATE TABLE public.bmrs_freq (
	"time" timestamptz NOT NULL,
	frequency numeric(5, 3) NULL,
	CONSTRAINT bmrs_freq_pkey PRIMARY KEY ("time")
);

```
The data in the table contains the most recent 2 hours. A cron job updates it with new data, and deletes the old data.
[bmrs_freq_202202091303.csv](https://github.com/cube-js/cube.js/files/8032925/bmrs_freq_202202091303.csv)


Here is my docker compose file: 
```
version: "2.2"

services:
  cube:
    image: cubejs/cube:latest
    environment:
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=<redacted>
      - CUBEJS_DB_USER=<redacted>
      - CUBEJS_DB_PASS=<redacted>
      - CUBEJS_DB_NAME=MarketDataRepo
      - CUBEJS_DB_PORT=5432

      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_DEV_MODE=true
      - CUBESTORE_LOG_LEVEL=trace
    volumes:
      - .:/cube/conf
    network_mode: "host"
```
I don't understand why the log level wasn't applied, as you can see, its right there in the docker compose file. 

The query I'm making is:
```
http://localhost:4000/cubejs-api/v1/load?query={"measures":["Freq.frequency"],"timeDimensions":[{"dimension":"Freq.time","granularity":"second"}],"order":{},"filters":[],"dimensions":[]}&queryType=multi
```

Here is an example of the discrepancy:
[difference.ods](https://github.com/cube-js/cube.js/files/8032811/difference.ods)
As you can see the discrepancy is only small, which is why I find it so odd.

**Comment by JoeMoggridge** [comment]
Ok, removed the `external: true` line from the cube, and hence I have been able to see the `create table` line in the log: 

```
Executing Load Pre Aggregation SQL: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 
cube_1  --
cube_1    CREATE TABLE dev_pre_aggregations.freq__aggregation1_ymb0wqoy_uc2nhvho_1h09o8p AS SELECT
cube_1        date_trunc('second', ("freq".time::timestamptz AT TIME ZONE 'UTC')) "freq__time_second", sum("freq".frequency) "freq__frequency"
cube_1     FROM
cube_1       (
cube_1        with
cube_1              times AS (
cube_1                   SELECT generate_series(
cube_1                   (date_trunc('minute', NOW()) - interval '60 minutes')::timestamp,
cube_1                   (date_trunc('minute', NOW()) + interval '5 minutes')::timestamp,
cube_1                   interval '15 seconds'
cube_1                ) AS time
cube_1             )
cube_1  
cube_1         SELECT
cube_1              times.time,
cube_1              frequency
cube_1          FROM
cube_1               times
cube_1               left join bmrs_freq as freq on times.time = freq.time
cube_1          WHERE
cube_1               times.time > NOW() - interval '60 minutes'
cube_1            ) AS "freq"  GROUP BY 1
cube_1   --
cube_1  Performing query completed: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 (24ms)
cube_1  Performing query completed: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 (62ms)
cube_1  Performing query: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 
cube_1  Performing query completed: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 (9ms)
cube_1  Performing query: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 
cube_1  Executing SQL: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 
cube_1   --
cube_1    SELECT date_trunc('minute', "freq__time_second") "freq__time_minute", sum("freq__frequency") "freq__frequency" FROM dev_pre_aggregations.freq__aggregation1_ymb0wqoy_uc2nhvho_1h09o8p AS "freq___aggregation1"  WHERE ("freq__time_second" >= '2021-11-15T00:00:00.000'::timestamp AND "freq__time_second" <= '2021-11-15T23:59:59.999'::timestamp) GROUP BY 1 ORDER BY 1 ASC LIMIT 10000
cube_1   --
cube_1  Performing query complete: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 (10ms)
cube_1  Load Request Success: c49853d8-f26d-45da-9c5a-a4310bffc509-span-1 (386ms)
cube_1   --
```

**Comment by JoeMoggridge** [comment]
Ok, I have another clue. 
Without external preaggregation, (so with the preaggregation being stored in the source db) it all works correctly. It is only once I set `external:true`, that I start to see the problem. 
That seems very wrong, surely where the preaggregation is stored should not affect its result?

**Comment by paveltiunov** [comment]
@JoeMoggridge Could you please try with latest version? Most likely it should be fixed. If not you can try to reproduce in Cube Cloud and share deployment with us so we can take a look at the data.
