### ISSUE TITLE
Athena pre-aggregation: "Error: Queries of this type are not supported" when refreshKey.incremental: true

### ISSUE THREAD

**Issue by shiriu** [cube-js/cube.js#404]
"Error: Queries of this type are not supported" message on incremental pre-aggregation. Otherwise, it works fine. 

The primary server is AWS Athena, and the pre-aggregation is an external MySQL. Get the same error even if the pre-aggregation is not external though.

In the logs, I see: 
```
Error while querying: 
SELECT CASE
    WHEN NOW() < CAST('2020-01-18T23:59:59Z' as TIMESTAMP) + interval '1' week THEN FLOOR(to_unixtime(NOW()) / 604800) END
{
  "queuePrefix": "SQL_QUERY_STANDALONE_athena"
} 
InvalidRequestException: Queries of this type are not supported

```

pre-aggregation is as follows:
```
preAggregations: {
        main: {
            type: `rollup`,
            measureReferences: [count],
            dimensionReferences: [category, id],
            granularity: `day`,
            timeDimensionReference: created_at,
            external: true,
            partitionGranularity: `week`,
            refreshKey: {
                every: `1 week`,
                incremental: true,
                updateWindow: `1 week`
            },
        }
    }
```

Similar error using different granularity and updateWindow values
```
Error while querying: 
SELECT CASE
    WHEN NOW() < CAST('2020-01-18T23:59:59Z' as TIMESTAMP) + interval '3' day THEN FLOOR(to_unixtime(NOW()) / 86400) END
{
  "queuePrefix": "SQL_QUERY_STANDALONE_athena"
} 
Error: GENERIC_USER_ERROR: Value cannot be cast to timestamp: 2020-01-18T23:59:59Z
    at AthenaDriver.query (/home/user/repos/cubejs/node_modules/@cubejs-backend/athena-driver/driver/AthenaDriver.js:57:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

with:
```
refreshKey: {
    every: `1 day`,
    incremental: true,
    updateWindow: `3 day`
}
```

using 
cubejs-backend/server-core 0.17.5

edit: used the same error message in both cases. now the error messages are correct

**Comment by paveltiunov** [comment]
@shiriu Hey Lucas! Thanks for posting this one! `week` interval isn't supported by presto so we should replace it by 7 day interval. Also `from_iso8601_timestamp()` should be used as a cast.

**Comment by shiriu** [comment]
I've fiddled with it, and it produced some errors like "timeDimension.dateFieldType() is not a function", which I couldn't reproduce. 

Tried tomake it work, at least to my case and now all I get is this:
```
Error while querying: 
SELECT CASE
    WHEN NOW() < from_iso8601_timestamp(?) + interval '7' day THEN FLOOR(to_unixtime(NOW()) / 604800) END
{
  "queuePrefix": "SQL_QUERY_STANDALONE_athena"
} 
Error: SYNTAX_ERROR: line 1:1: Incorrect number of parameters: expected 1 but found 0
```

what am I missing?

**Comment by paveltiunov** [comment]
@shiriu You can't pass parameters to query by simply inserting `?`. All params are allocated by cube.js to ensure there's no SQL injection. So the best way to fix it is to provide PR for this line. If you're looking for workarounds you may want to check this: https://cube.dev/docs/incremental-pre-aggregations#top

**Comment by tobilg** [comment]
@paveltiunov If I understand this correctly, this could be fixed in the [timeStampCast() method of the PrestoDB driver](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/adapter/PrestodbQuery.js#L39), correct?

Using `from_iso8601_timestamp()` function instead of the `CAST(dt as TIMESTAMP)` seems to work in my tests, but I'm unsure about the potential side effects tbh. What's your suggestion to tackle this?

**Comment by paveltiunov** [comment]
@tobilg Here's the description on how to fix it: https://github.com/cube-js/cube.js/issues/404#issuecomment-587149257

**Comment by tobilg** [comment]
Yeah, I saw that @paveltiunov, but I‘m unsure whether it’s correct to change this globally. I can’t test it for the other database types. As far as I understood this method could be overwritten by the Athena instance, correct?

Would you be willing to accept a PR?

**Comment by paveltiunov** [comment]
@tobilg Yep. It should be fixed in the base class. PR is very welcomed!

**Comment by tobilg** [comment]
@paveltiunov I deployed an instance with the fix you mentioned, but now I receive the save error message as @shiriu:

`Error: SYNTAX_ERROR: line 1:1: Incorrect number of parameters: expected 1 but found 0`

I have no clue how to fix this

**Comment by tobilg** [comment]
I investigated a bit, and it seems to fail from the `invalidateKeyQueries`:

```javascript
"invalidateKeyQueries": [
    [
        "SELECT CASE\n    WHEN NOW() < from_iso8601_timestamp(?) + interval '1' day THEN FLOOR(to_unixtime(NOW()) / 3600) END",
        []
    ]
],
```

There's no parameter which is passed to the query apparently...

**Comment by tobilg** [comment]
@paveltiunov any chance of an update? Thanks a lot!

**Comment by tobilg** [comment]
Thanks a million @paveltiunov! I locally applied you last commit, and this seems to fix the problem :-) Will this land in the next release?
