### ISSUE TITLE
Cube.js incremental pre-aggregation is selecting all data

### ISSUE THREAD

**Issue by josepereira93** [cube-js/cube.js#405]
**Describe the bug**
I'm running cube.js with incremental pre-aggregations and daily granularity. So, only the current day pre-aggregation are being rebuilt. 

The issue is that the queries runtime to create the pre-aggregations is worsen **a lot** as the data volume grows. Last week it took something like 8 seconds to build a pre-aggregation, yesterday it took 80s (and sometimes even 120s). The data volume clearly didn't grow 10 times.

It seems to me that the whole dataset is being selected, instead of the current day.

Example query:

```
CREATE TABLE cubejs_pre_aggregations.ufl_main20200218 AS SELECT
      "ufl".flow "ufl__flow", date_trunc('day', CAST(date_add('minute', timezone_minute("ufl".timestamp AT TIME ZONE 'UTC'), date_add('hour', timezone_hour("ufl".timestamp AT TIME ZONE 'UTC'), "ufl".timestamp AT TIME ZONE 'UTC')) AS TIMESTAMP)) "ufl__timestamp_day", count(*) "ufl__count"
    FROM
      (SELECT data.flow AS flow, timestamp FROM events WHERE type = 'ERROR') AS "ufl"
  WHERE ("ufl".timestamp >= from_iso8601_timestamp('2020-02-18T00:00:00Z') AND "ufl".timestamp <= from_iso8601_timestamp('2020-02-18T23:59:59Z')) GROUP BY 1, 2
```

To me it seems that the issue is this part:

```(SELECT data.flow AS flow, timestamp FROM events WHERE type = 'ERROR') AS "ufl"  WHERE ("ufl".timestamp >= from_iso8601_timestamp('2020-02-18T00:00:00Z') AND "ufl".timestamp <= from_iso8601_timestamp('2020-02-18T23:59:59Z'))```

Shouldn't it be?

```(SELECT data.flow AS flow, timestamp FROM events WHERE type = 'ERROR' WHERE (timestamp >= from_iso8601_timestamp('2020-02-18T00:00:00Z') AND timestamp <= from_iso8601_timestamp('2020-02-18T23:59:59Z')) AS "ufl" ```

**Expected behavior**
Incremental daily pre-aggregations should maintain its execution time as the data set grows. E.g. 8s to 10s seems acceptable. 8s to 80s isn't.

**Version:**
0.17.7

**Additional context**
I'm using MongoDB as main DB and MySQL as external pre-aggregations DB.

Keep up the good work, the project has a lot of potential.

**Comment by paveltiunov** [comment]
Hey @josepereira93 ! Great question! So in case database doesn't support filter pushdown optimization like MongoDB you can hint it with `FILTER_PARAMS`: https://cube.dev/docs/cube#context-variables-filter-params. 

Please note that amount of scanned data for Athena can be reduced only by means of partitioning which uses separate virtual column to represent partition values. For example:
```javascript
cube(`Ufl`, {
  sql: `
  SELECT data.flow, timestamp FROM events WHERE type = 'error'
  AND ${FILTER_PARAMS.Ufl.timestamp.filter((from, to) =>
    `from_iso8601_timestamp(date_partition) >= date_trunc('day', from_iso8601_timestamp(${from})) AND from_iso8601_timestamp(date_partition) <= date_trunc('day', from_iso8601_timestamp(${to}))`
  )}
  `,

  // ...

  dimensions: {
    timestamp: {
      sql: `timestamp`,
      type: `time`
    }
  }
});
```

**Comment by josepereira93** [comment]
Hey, I'm already familiar withe ```FILTER_PARAMS``` since I needed them in pre-aggregations RefreshKey. I didn't know that they can (and in MongoDB case, must) be used in the sql param. 

So, for what I understood, if a DB doesn't support pushdown optimization, the ```FILTER_PARAMS``` should always be used in sql param to improve performance.     

Thanks for the answer, I'll try it!

**Comment by paveltiunov** [comment]
@josepereira93 Yep. In case of MongoDB and MySQL these always should be hinted with filters on selected tables.
