### ISSUE TITLE
question: subquery aggregation

### ISSUE THREAD

**Issue by Eywek** [cube-js/cube.js#4051]
**Problem**

I'm currently trying to do an average of the number of times an event is done by a user, which could translate in the following SQL:

```sql
SELECT
	AVG(`conversion_events__count`)
FROM (
	  SELECT
	    `conversion_events`.user `conversion_events__user_id`,
	    count(`conversion_events`.eventId) `conversion_events__count`
	  FROM
		  `conversion_events`  
	  GROUP BY
	    1
)
```

And I have found a way (an easy one at least) to do this with CubeJS, I’m able to generate the subquery with CubeJS but I can’t figure how to do the AVG() on it. I’m using BigQuery if it matters.

Do you have any idea / lead on this?

Thank you

**Comment by Eywek** [comment]
Using the `avg` measure leads to the following query:
```sql
	  SELECT
	    `conversion_events`.user `conversion_events__user_id`,
	    avg(count(`conversion_events`.eventId)) `conversion_events__count`
	  FROM
		  `conversion_events`  
	  GROUP BY
	    1

```

Which isn't supported by bigquery (`aggregations of aggregations are not allowed`) and doesn't do what I expect (having an average of a count per user)

**Comment by shulmaneyal** [comment]
Maybe by skipping the sub query you can get it to work? Calculating the below directly

count(events)/count(distinct user)

**Comment by Eywek** [comment]
> Maybe by skipping the sub query you can get it to work? Calculating the below directly
> 
> > count(eventId)/count(distinct user)

Lgtm, thank you. 

But out of curiosity, is my original query doable with Cube?

**Comment by paveltiunov** [comment]
@Eywek Yep. It's average on subquery. Please see `averageDealsAmount` definition here https://cube.dev/docs/schema/fundamentals/additional-concepts#subquery.
