### ISSUE TITLE
Pre-aggregations do not support bulky SQL expressions [MongoDB]

### ISSUE THREAD

**Issue by shaikwasef** [cube-js/cube.js#4055]
I’m currently using CUBE-JS pre-aggregations for my data and I notice the following problem . When I do not use the filters in my CUBE-JS query , the pre aggregations work , however on using the filter with operator “set” on my two dimensions the pre aggregations are skipped .

The cited problem for this by @igorlukanin was this _"I think that Cube fails to recognize `AggregatedPenalties` as an additive measure because it has a quite complicated SQL expression in sql" . 

Here is the schema  and details of the ticker from the slack channel 

https://cube-js.slack.com/archives/CC0403RRR/p1642769348139600

 
Here are the screen shots of my results . 
![Screenshot 2022-01-21 at 6 18 38 PM](https://user-images.githubusercontent.com/12941030/152919576-301338c6-76ac-4be2-aa7f-63900183578d.png)
![Screenshot 2022-01-21 at 6 18 11 PM](https://user-images.githubusercontent.com/12941030/152919584-b4a146d6-aead-47c8-9d16-4886c92c246b.png)

**Comment by paveltiunov** [comment]
@shaikwasef This is not a bug but expected behavior. Pre-aggregation is not matched because there're multiplied measures. Please see https://cube.dev/docs/caching/pre-aggregations/getting-started#ensuring-pre-aggregations-are-targeted-by-queries-selecting-the-pre-aggregation.

**Comment by shaikwasef** [comment]
@paveltiunov As seen in the screenshot attached the pre-aggregations matching is not skipped in absence of the filters even though non-additive measures are being referenced. Kindly let me know if I should attach a new example.

**Comment by shaikwasef** [comment]
> @paveltiunov As seen in the screenshot attached the pre-aggregations matching is not skipped in absence of the filters even though non-additive measures are being referenced. Kindly let me know if I should attach a new example.

@paveltiunov Can you please reopen this ticket
