### ISSUE TITLE
Hook to manipulate the response before it gets sent

### ISSUE THREAD

**Issue by JaySunSyn** [cube-js/cube.js#4091]
As a developer, I want to be able to control the API response of Cube before it gets sent to the frontend.
Especially, when it comes down to error messages, I want to be able to sanitize them.

Given a `400` error response:

```
Column "user_id" does not exist.
```

leaks schema info from the DB to the frontend. 

I'd like to sanitize those response messages without running Cube as an express app.

**Describe the solution you'd like**
A hook `rewriteResponse: (req, res)` that can be used to manipulate the response object.

This hook can also be used to change the response status code.

```js
rewriteResponse: (req, res) {
   if (res.status_code === 500 && res.message === 'company validation failed') {
     res.status_code = 401
     res.status_message = 'Unvalidated company'
     res.body = null
     return
  }

  if (res.status_code > 299 && isProduction) {
    Sentry.logError(req, res)
    res.status_message = 'Something went wrong'
    res.body = null
  }
}
```
**Describe alternatives you've considered**
Running Cube as an express app in order to have control over the request and response objects.

**Comment by paveltiunov** [comment]
Hey @JaySunSyn ! Do you want to rewrite errors coming from the database?

**Comment by JaySunSyn** [comment]
@paveltiunov 

- I want to rewrite errors from coming from DB
- I want to rewrite response status codes coming from cube.js. E.g. What to do if a custom auth (via checkAuth()) failed. Right now, I can only throw an error which leads to a 500 instead of a 403/401 response.

**Comment by JaySunSyn** [comment]
Would maybe also solve this: https://github.com/cube-js/cube.js/issues/2368

**Comment by paveltiunov** [comment]
Let's merge it with #3799
