### ISSUE TITLE
tablePivot doesn't respect order

### ISSUE THREAD

**Issue by pierre-H** [cube-js/cube.js#4105]
I have a query with : 
- a measure (a sum)
- a time dimension with a granularity (month)

Setting the order in the measure have an impact in the `rawData()` function of `resultSet` but not in the `tablePivot` with or without a `pivotConfig`.

**Comment by vasilev-alex** [comment]
@pierre-H does it work with `pivotConfig.fillMissingDates = false`?

**Comment by Inoir** [comment]
this issue seems to happen on every resultSet.
i.E if you use QueryBuilder and just change the order, the incoming data from network is correct sorted, the filledDates  i.e:`resultSet.categories(pivotConfig)`  isnt.

**Comment by vasilev-alex** [comment]
This is expected behavior https://cube.dev/docs/@cubejs-client-core#types-pivot-config

`fillMissingDates` undoes any applied order, and it's `true` by default. If you want to preserve the order you may want to disable the `fillMissingDates` option
