### ISSUE TITLE
BUG: Funnel generates wrong SQL when filtered by Cube query filter

### ISSUE THREAD

**Issue by JaySunSyn** [cube-js/cube.js#4117]
**Describe the bug**
In a given Cube funnel, I get different results for Conversions and Percentage measures.

Measure: Conversions
Dimension: Step

| Funnel Step Clicked | Funnel Step Logged in |
|---------------------|-----------------------|
| Funnel Conversions  | Funnel Conversions    |
| 1                   | 3                     |

Measure: Percentage
Dimension: Step

| Funnel Step Clicked | Funnel Step Logged in |
|---------------------|-----------------------|
| Funnel Conversions Percent | Funnel Conversions  Percent  |
| 100%                  | 100%                   |

**To Reproduce**
1. Create a simple funnel (e.g. the purchase funnel)
2. Join it with `Users`
3. Query the funnel via the playground while adding a `Users` filter (e.g. Users.name = 'johnny'
4. See the `conversionsPercent` measure

**Expected behavior**
Correct percentage measures.

**Version:**
latest

**Additional context**
When I add a hard-coded filter in both of the `eventsView` properties (`WHERE user_name = 'johnny'`) it works. If I add the same filter via a Cube query, it does not work as described above.

**Comment by JaySunSyn** [comment]
Hey @paveltiunov, any update on this?

**Comment by paveltiunov** [comment]
@JaySunSyn Hey Jalal! Could you please share a minimally reproducible Cube.js schema? You can use selects without tables for that as follows
```
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status
  UNION ALL
  select 2 as id, 200 as amount, 'new' status
  UNION ALL
  select 3 as id, 300 as amount, 'processed' status
  UNION ALL
  select 4 as id, 500 as amount, 'processed' status
  UNION ALL
  select 5 as id, 600 as amount, 'shipped' status
  `,
  measures: {
    count: {
      type: `count`,
    },
    totalAmount: {
      sql: `amount`,
      type: `sum`,
    },
    toRemove: {
      type: `count`,
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },
  },
});
```

**Comment by JaySunSyn** [comment]
@paveltiunov 

I have trouble getting correct values even without the join.

Below query results in 1 conversion even with a different user_id (1 vs. 5). It should be 0 conversions. What am I doing wrong?

<img width="912" alt="image" src="https://user-images.githubusercontent.com/5872432/164014652-9923e1da-c66c-4e81-b976-a9562dc77285.png">


```js
const Funnels = require(`Funnels`);

cube(`Users`, {
  sql: `
  select 1 as id, 'Albert' as name
  UNION ALL
  select 2 as id, 'Blbert' as name
  UNION ALL
  select 3 as id, 'Clbert' as name
  UNION ALL
  select 4 as id, 'Dlbert' as name
  UNION ALL
  select 5 as id, 'Flbert' as name
  `,

  measures: {
    count: {
      type: `count`
    },
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `string`,
      primaryKey: true,
    },
    name: {
      sql: `name`,
      type: `string`
    }
  }
});


cube(`PurchaseFunnel`, {
  extends: Funnels.eventFunnel({
    userId: {
      sql: `user_id`,
    },
    time: {
      sql: `timestamp`,
    },
    // joins: {
    //   Users: {
    //     relationship: `belongsTo`,
    //     sql: `${CUBE}.first_step_user_id = ${Users}.id`,
    //   },
    // },
    steps: [
      {
        name: `view_product`,
        eventsView: {
          sql: `(select 1 as user_id, '2022-04-10'::TIMESTAMP as timestamp)`,
        },
      },
      {
        name: `purchase_product`,
        eventsView: {
          sql: `(select 5 as user_id, '2022-04-16'::TIMESTAMP as timestamp)`,
        },
      },
    ],
  }),
});
```

**Comment by JaySunSyn** [comment]
```js
const Funnels = require(`Funnels`);

cube(`Users`, {
  sql: `
  select 1 as id, 'Albert' as name
  UNION ALL
  select 2 as id, 'Blbert' as name
  UNION ALL
  select 3 as id, 'Clbert' as name
  UNION ALL
  select 4 as id, 'Dlbert' as name
  UNION ALL
  select 5 as id, 'Flbert' as name
  `,

  measures: {
    count: {
      type: `count`
    },
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `string`,
      primaryKey: true,
    },
    name: {
      sql: `name`,
      type: `string`
    }
  }
});


cube(`PurchaseFunnel`, {
  joins: {
    Users: {
      relationship: `belongsTo`,
      sql: `${CUBE}.first_step_user_id = ${Users}.id`,
    },
  },
  extends: Funnels.eventFunnel({
    userId: {
      sql: `user_id`,
    },
    time: {
      sql: `timestamp`,
    },
    steps: [
      {
        name: `view_product`,
        eventsView: {
          sql: `(select 1 as user_id, '2022-04-10'::DATE as timestamp UNION ALL select 1 as user_id, '2022-04-11'::DATE as timestamp UNION ALL select 3 as user_id, '2022-04-10'::DATE as timestamp)`,
        },
      },
      {
        name: `purchase_product`,
        eventsView: {
          sql: `(select 1 as user_id, '2022-04-16'::DATE as timestamp)`,
        },
      },
    ],
  }),
});
```

**Correct**
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/5872432/164017077-0399238c-f770-4691-9a8d-db5583451da1.png">

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/5872432/164017179-9c712efa-e4cf-4f23-bb72-17d4ba157651.png">


<img width="1129" alt="image" src="https://user-images.githubusercontent.com/5872432/164017850-9eba64f2-70cf-48e6-8522-fdd9a5387a61.png">
