### ISSUE TITLE
Query returning zero results returns one result when filter is added

### ISSUE THREAD

**Issue by reify-jeremy-fine** [cube-js/cube.js#4124]
Given the schema in the first [join example here](https://cube.dev/docs/schema/fundamentals/joins). i'm trying to find out the best way to deal with a query that would just list order ids for a given user. eg:
```
  {
    dimensions: ["Order.id"],
    measures: [],
    filters: [{member: "User.id", operator: "equals", values: ["test-user-id"]}]
  };
```
This works fine except for the case of a user with no orders. instead of getting an empty list of results, i get a result that contains one element like {"Oder.id": null}. Looking at the generated sql, it's understandable why this is happening. However, it's surprising at first glance because a query without the filter (and a database with no orders) returns an empty list as expected.

one way to deal with this is on the frontend is to to add this filter to the query:
```{member: "Order.id", operator: "set"}```
I'm wondering if there's a better way to do this since it seems i'll have to add this filter to many queries in my frontend code.

**Comment by ivan-vdovin** [comment]
Hi @reify-jeremy-fine ,
I can't reproduce that. Here is what I get:
`"data":[]`
Could you share the full response and your cube version, please?
