### ISSUE TITLE
Explicitly register Chart.js charts with react-chartjs-2 v4

### ISSUE THREAD

**Issue by jsbrain** [cube-js/cube.js#4137]
Generation of Chart.js dashboard from playground doesn't compile properly due to changes in `react-chartjs-2`.
As can be seen [here](https://github.com/reactchartjs/react-chartjs-2/releases/tag/v4.0.0), re-exports have been removed with v4 so moving forward charts must be registered explicitly.

**To Reproduce**
Start any example, create a dashboard with React and Chart.js from the playground and it will fail.

**Version:**
0.29.28

**Comment by igorlukanin** [comment]
@dangreen, could you please work with @vasilev-alex to fix this on Cube's side? I think we should update the code generation to Chart.js v3 and react-chartjs-2 v4. Possibly, fix the package versions, too.

**Comment by ivan-vdovin** [comment]
@jsbrain could you confirm it's still relevant, please?

**Comment by jsbrain** [comment]
@ivan-vdovin have there been changes to the code generation?
If not, this will still be an issue I guess.
