### ISSUE TITLE
Support for self-join

### ISSUE THREAD

**Issue by louis-vincent1** [cube-js/cube.js#4138]
**Describe the solution you'd like**

I would like to be able to self join over a my cube

**Describe alternatives you've considered**

Aggregate everything inside an array_agg and call a custom SQL function:

“SELECT my_logic(array_agg(fields i need ...)) from my_table"

**Comment by paveltiunov** [comment]
Hey @louis-vincent1 ! Self-joins are possible by introducing cubes with the same fact tables but different names. Could you please elaborate on your use case so we can guide you more precisely?

**Comment by louis-vincent1** [comment]
@paveltiunov 

Well the things is, I have to **filter** of a cubejs which is made of multiple joins.

Given the resulted **filtered** cube, I need to do further processing on it, for example do statistics over some column within the filtered cube columns.

What I need to is to do some sort of self-join over the cube with all its where clause in it.

Do you have any doc that shows an example of how to self joins over my own cube (including the same fitler conditions)?

**Comment by ivan-vdovin** [comment]
Hi @louis-vincent1 !
Looks like `extends` feature can be helpful here:
[](https://cube.dev/docs/schema/advanced/extending-cubes#top)
[](https://cube.dev/docs/schema/advanced/polymorphic-cubes)

**Comment by louis-vincent1** [comment]
@ivan-vdovin 
Well `extends` seems to copy the same exact same cube definition, but it does solve my problem where I need to do further processing over the ResultSet produce by the client's query.

Anyway I just gave up with this, Ill use my workaround...
