### ISSUE TITLE
Dremio driver does not accept CUBEJS_DB_NAME

### ISSUE THREAD

**Issue by mlilius** [cube-js/cube.js#4139]
**Describe the bug**
The value of CUBEJS_DB_NAME is ignored. It defaults to 'default'. This causes an error if you don't have a default space defined in Dremio.

**To Reproduce**
1. Setup dremio driver
2. Use a dremio server without a default space
3. Set the CUBEJS_DB_NAME environment variable to a space that does exist.
4. Error happens

**Expected behavior**
It is expected that the value of CUBEJS_DB_NAME should be used.

**Screenshots**
N/A

**Version:**
v0.29.28

**Comment by paveltiunov** [comment]
Hey @mlilius ! Could you please provide an example of what configuration is provided and what doesn't work as expected?
