### ISSUE TITLE
How to send multiple queries at once to Cube.Js Backend through Rest Api??

### ISSUE THREAD

**Issue by hawkEye-01** [cube-js/cube.js#4158]
Hi,
Question:
I  need 40 calculated values for a graph I am creating in my current react app. what is am doing is reading queries from a file then sending those queries to  Cube.Js through REST API one by one ,then merging those values together in order to use them. 
Is there any better way to achieve this in Cube.Js backend?

**Note**: kindly ignore the shortcomings since I am relatively new to JS and Cube

**Current Scenerio:**
Reading queries from a file

![image](https://user-images.githubusercontent.com/56556980/156346296-08079adc-e62c-4384-9c26-9ebaed015ea4.png)

Converting them to CubeJs query format:
```
{
        dimensions: ['One.measure_value'],
        filters:[
            {
                member: "One.time_period",
                operator: "equals",
                values: ["P1M"]
              }
		   {
                member: "One.prod_lvl_name",
                operator: "equals",
                values: ["Brand"]
              }
        ],
    
      }
```
**send these queries as **array of dictionaries** to CubeJs  one by one in loop**

**is there any better way to send all queries at once ????**

**Comment by shanewho** [comment]
If it is time based you can potentially use data blending and send the queries as an array:
https://cube.dev/docs/schema/advanced/data-blending

**Comment by hawkEye-01** [comment]
tried that! thanks! Although i am using dummy dates since i dont need to filter data on dates like so :
```
{
        dimensions: ['One.measureValue'],
        filters:[
            {
                member: "One.company",
                operator: "equals",
                values: ["IYSEST"]
              }
        ],
        timeDimensions: [
            {
              dimension: 'One.dataEnding',
              granularity: "month",
              dateRange: ['2020-10-01', '2022-10-01'],
            },
          ],
        timezone:'America/Los_Angeles'
      }
```
Any better way than this?

**Comment by ivan-vdovin** [comment]
Hi @hawkEye-01,
Does it work for you?
Sending separate queries one by one and combining them on the front is totally fine and should not take a lot of time if you use pre-aggregations. The approach from the first comment is also great if applicable for your use case. As for the time dimensions they are optional so you can skip them if you don't need that. Please, let me know if I didn't get your question right.

**Comment by hawkEye-01** [comment]
Hi @ivan-vdovin ,
data blending approach did work for me. and thankfully it s fast. I am able to get results for 60 queries or so in less than 5 seconds. 
as for the dimensions:  I can't get data blending to work without mentioning granularity and for that i need to use time dimensions
