### ISSUE TITLE
CubeJS timezone setting not working as expected

### ISSUE THREAD

**Issue by patelpriyankab** [cube-js/cube.js#4171]
Cube converts all time fields to UTC. How can we prevent this default setting or set timezone?
We are facing this issue when querying to snowflake and it works fine for redshift while using multitenancy.

Timezone conversion to UTC works fine with redshift. With snowflake it gives error.
So, when we try to use the generated query in snowflake, it shows synatx error as below:

```SQL compilation error: syntax error line 5 at position 39 unexpected 'AT'. syntax error line 5 at position 42 unexpected 'TIME'.```

So, then we followed the documentation here https://cube.dev/docs/query-format and added timezone which gives this error:
Error: Compile errors: AbandonedCarts cube: (timezone = Asia/Kolkata) is not allowed

Below is the cube schema we are using:

```javascript
cube(`AbandonedCarts`, {
  sql: `SELECT * FROM tbl_abandoned_carts WHERE ${FILTER_PARAMS.AbandonedCarts.updatedAt.filter('updated_at')} and is_active=true`,
  sqlAlias: `ac`,
  refreshKey: {
    sql: `SELECT max(updated_at) FROM tbl_abandoned_carts`
  },
  joins: {
    Customers: {
      relationship: `belongsTo`,
      sql: `${AbandonedCarts}.customer_id = ${Customers}.customer_id`
    },
    MgAbandonedCartItems: {
      relationship: `hasMany`,
      sql: `${AbandonedCarts}.cart_id = ${AbandonedCartItems}.cart_id`
    }
  },
  dimensions: {
    createdAt: {
      sql: `${CUBE}.created_at`,
      type: `time`
    },
    updatedAt: {
      sql: `${CUBE}.updated_at`,
      type: `time`
    },
    convertedAt: {
      sql: `${CUBE}.converted_at`,
      type: `time`
    },
  },
  timezone: `Asia/Kolkata`
});```

**Version:**
^0.29.27

**Comment by ack210** [comment]
We had a similar issue where date fields stored as UTC in the database were being converted to the local timezone, resulting in dates being off by 1 when running locally.  A workaround that helped us was setting the node environment variable `TZ` to UTC prior to server start, e.g.
```
process.env.TZ = 'Etc/UTC';
```

Even easier, you can include this in your `.env` file with the other cube.js server settings.

**Comment by ivan-vdovin** [comment]
Hi @patelpriyankab !
Timezone usage in your schema file is incorrect. Shared docs page describe how this can be used in the query not in the cube definition.
