### ISSUE TITLE
Throttle polling in cubejs - affecting the aws lambda costs due to limitation on athena concurrent query executions

### ISSUE THREAD

**Issue by pranay317** [cube-js/cube.js#4173]
I am facing an issue regarding continuous polling by the cubejs-client. The full description of the issue is as follows -

We are using serverless flavour of cubejs with athena driver. Athena has a concurrent query execution limit it seems. So, while the athena queue is being processed, all the subsequent requests by other users are getting queued and getting continue wait responses. So the cubejs client keeps polling the service. If the queue is quite large, then each user is making around 20 - 30 calls each time, which is affecting the lambda costs on the aws account!

The total daily invocations are going to a magnitude of 12 million with only 5000 users using the system

Any solution to this issue would be really helpful. Thanks

**Comment by paveltiunov** [comment]
@pranay317 I believe the only viable option is to use Cube Store pre-aggregations. You can indeed increase `continueWaitTimeout`, however, I wonder if it just worsens the situation.
