### ISSUE TITLE
Need to install core-js@2 for a sample

### ISSUE THREAD

**Issue by chengtie** [cube-js/cube.js#418]
I tried to follow [this blog](https://cube.dev/blog/building-mongodb-dashboard-using-node.js) to make a cubejs+react sample.

After installing the backend, we could successfully launch `http://localhost:4000` in a browser. Then,  I tried to add a React dashboard in the browser. After some installation, the folder `dashboard-app` was generated. However, after `npm run start`, launching `http://localhost:3000` returned an error:

```
./node_modules/@cubejs-client/core/dist/cubejs-client-core.js
Module not found: Can't resolve 'core-js/modules/es6.array.filter' in '/Users/chengtie/Startup/ReactProjects/mongo-tutorial/dashboard-app/node_modules/@cubejs-client/core/dist'
````

After chatting on Slack, Hassan Khan gave a solution: we need to install `core-js@2` under `dashboard-app` by `npm install core-js@2 --save`. Here is [the Slack link](https://cube-js.slack.com/archives/CC0403RRR/p1582122479171700).

I guess this report may help you improve the sample.

**Comment by paveltiunov** [comment]
Hey @chengtie ! Thanks for posting this one! Should be fixed in 0.17.10. Could you please try create new project from scratch again?

**Comment by hassankhan** [comment]
Hi @paveltiunov, I thought the fix would be to add `core-js` as a dependency when generating a new dashboard app?

**Comment by paveltiunov** [comment]
@hassankhan Yeah. This is fast fix to reanimate dashboards. We need to find a solution on how to make babel work with `core-js@3`. I wasn't able to find it yet. Do you have any ideas here?

**Comment by hassankhan** [comment]
Did some digging, [this link](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babel) seems to have some interesting information.

**Comment by paveltiunov** [comment]
@hassankhan Gotcha. Seems like babel is out of date on a build level rather than actually in created react app? Need to upgrade our babel for rollup build?
