### ISSUE TITLE
TypeScript type inference for query results

### ISSUE THREAD

**Issue by reify-thomas-smith** [cube-js/cube.js#4202]
**Is your feature request related to a problem? Please describe.**
Motivating example (which actually won't work due to #4160):

```ts
const results = await api.load({
  measures: ["Foo.count"],
  dimensions: ["Bar.id", "Bar.name"],
} as const);
```

We can infer that the type of `results` is:

```ts
ResultSet<{
  ["Foo.count"]: string | number | boolean,
  ["Bar.id"]: string | number | boolean,
  ["Bar.name"]: string | number | boolean,
}>
```

But `api.load()` is declared as returning `ResultSet<any>`.

**Describe the solution you'd like**

In the above example, `api.load` should return the more specific type. This would require some moderately clever type definitions. If there is interest in this, I can take a crack at it.

**Describe alternatives you've considered**
Not inferring the type, manually defining the correct return type, and casting the result.

**Comment by paveltiunov** [comment]
Hey @reify-thomas-smith ! Do you mean some type of code generation that can provide result set types based on Cube Data Schema?

**Comment by reify-thomas-smith** [comment]
I mean declaring a more complex type for e.g. `useCubeQuery` so that TypeScript does all the work. Here's a slightly stripped-down version of the wrapper I'm currently using:

```ts
// The cube.js functions won't accept readonly queries.
// See https://github.com/cube-js/cube.js/issues/4160
type DeeplyReadonly<T> = {
  readonly [K in keyof T]: DeeplyReadonly<T[K]>;
};

// As Query, but supporting type inference for dimension and measure names.
type TypedQuery<AttributeNames extends string> = DeeplyReadonly<
  Omit<Query, "measures" | "dimensions">
> & {
  readonly measures?: readonly AttributeNames[];
  readonly dimensions?: readonly AttributeNames[];
};

type CubeRecord<AttributeNames extends string> = {
  [k in AttributeNames]: string | number | boolean;
};

export function useTypedCubeQuery<AttributeNames extends string>(
  query: TypedQuery<AttributeNames>,
  options?: UseCubeQueryOptions
): UseCubeQueryResult<CubeRecord<AttributeNames>> {
  return useCubeQuery<CubeRecord<AttributeNames>>(query as Query, options);
}

export function loadTyped<AttributeNames extends string>(
  cubejsApi: CubejsApi,
  query: TypedQuery<AttributeNames>,
  options?: LoadMethodOptions
): Promise<ResultSet<CubeRecord<AttributeNames>>> {
  return cubejsApi.load(query as Query, options);
}
```

If you call one of these wrappers with a richly-typed query (e.g. defined using `as const`), then the `ResultSet` will have a type with a property for each dimension and measure in the query:

```ts
const results = await loadTyped(api, {
  measures: ["Foo.count"],
  dimensions: ["Bar.id", "Bar.name"],
} as const);

const record = results.rawData()[0];

record["Foo.count"]; // OK, suggested by autocomplete, etc
record["Foo.anotherField"]; // Compile-time type error, squiggly red line in editor, etc
```

This definitely works and I am using it in production code.

**Comment by paveltiunov** [comment]
@reify-thomas-smith I see. Yep. I think it'd be a great addition to the ResultSet types!

**Comment by reify-thomas-smith** [comment]
I am interested in working on this issue, and it can be assigned to me.
