### ISSUE TITLE
how to pass securityContext with SQL API

### ISSUE THREAD

**Issue by nightbear1009** [cube-js/cube.js#4204]
**Problem**

I am using mysql to connect to my cube, I am also using securityContext to manage multi-tenant, I would like to know is there anyway to pass securityConntext when using sql api?

**Related Cube.js schema**
```javascript
const Gift = cube(`Gift`, {
  sql: `
      SELECT 
        *
      FROM
        table
      WHERE 1=1
        AND ${SECURITY_CONTEXT.shop_id.requiredFilter("tenant_Id")}
```

**Comment by ivan-vdovin** [comment]
Hi @nightbear1009 !
You can use checkSqlAuth to do that:
https://cube.dev/docs/backend/sql#custom-authentication

**Comment by nightbear1009** [comment]
thanks,  but I have noticed that CUBEJS_SQL_USER can only allow one user, how can I config multiple user?

**Comment by nightbear1009** [comment]
hi, seems that checkSqlAuth can also solve this problem. I have no further question. thanks~
