### ISSUE TITLE
ResultSet.totalRow returns the first row instead of total

### ISSUE THREAD

**Issue by myself7890** [cube-js/cube.js#4214]
**Describe the bug**
When calling ResultSet.totalRow, I get the first data row instead of a row containing the totals. 

**To Reproduce**
Call ResultSet.totalRow().

**Expected behavior**
Considering the name of the method, I expect the result to be a row containing the totals of each measure.

**Screenshots**
![image](https://user-images.githubusercontent.com/16654482/158173357-aa8c576e-0f87-4dfa-8080-eb48bf32b9f5.png)

**Minimally reproducible Cube Schema**

```javascript
cube(`Sales`, {
    sql: `SELECT * FROM sales`,
    joins: {
        Stores: {
            relationship: `belongsTo`,
            sql: `${Stores}.id = ${CUBE}.store_id`,
        },
    },
    measures: {
        // Sales
        subtotal: {
            sql: `subtotal`,
            type: `sum`,
            filters: [{sql: `${CUBE}.is_refund = 0`}],
        },
        discount: {
            type: `sum`,
            sql: `discount`,
            filters: [{sql: `${CUBE}.is_refund = 0`}],
        },
        taxes: {
            sql: `taxes`,
            type: `sum`,
            filters: [{sql: `${CUBE}.is_refund = 0`}],
        },
        amount: {
            sql: `amount`,
            type: `sum`,
            filters: [{sql: `${CUBE}.is_refund = 0`}],
        },
        refundsAmount: {
            sql: `amount`,
            type: `sum`,
            filters: [{sql: `${CUBE}.is_refund = 1`}],
        },
        refundsSubtotal: {
            type: `sum`,
            sql: `subtotal`,
            filters: [{sql: `${CUBE}.is_refund = 1`}],
        },
        refundsGiftcard: {
            sql: `giftcard`,
            type: `sum`,
            filters: [{sql: `${CUBE}.is_refund = 1`}],
        },
        // Aggregations
        gross: {
            type: `number`,
            sql: `IFNULL(${subtotal},0) - IFNULL(${giftcard},0)`,
        },
        salesSubtotal: {
            type: `number`,
            sql: `IFNULL(${gross},0) - IFNULL(${discount},0)`
        },
        refundsGross: {
            type: `number`,
            sql: `IFNULL(${refundsSubtotal},0) - IFNULL(${refundsGiftcard},0)`,
        },
    },
    dimensions: {
        id: {
            sql: `id`,
            type: `number`,
            primaryKey: true
        },

        createdAt: {
            sql: `created_at`,
            type: `time`
        },
    },
});

```

**Version:**
0.28.52

**Comment by paveltiunov** [comment]
@myself7890 Yep. It's indeed not ideal naming. Originally it was designed to access rows of single-row queries like total queries. So is your issue more around bad naming or rather totals row evaluation?

**Comment by myself7890** [comment]
There is no explanation in the documentation about what that method is doing, so I thought it was doing what it seems to be saying: returning a row containing the totals of all the measures. 

Do you know another way to easily do that without having to resort to another query?

**Comment by paveltiunov** [comment]
@myself7890 The only reliable way to do it is to do a separate query. Do you have any issues with that?

**Comment by PieterVanZyl-Dev** [comment]
We have a few places in frontend applications where we need something similar to this 

We just take the cube resultSet data and use a util function that we create to do this for us.

We don't sum the totals of measures but it would be similar
