### ISSUE TITLE
Custom type `ltree` is not supported

### ISSUE THREAD

**Issue by manan-sc** [cube-js/cube.js#4243]
**Describe the bug**
The Postgress `ltree` type is not supported. I get the following error when trying to create pre-aggregations for a table that contains a column with the `ltree` type.

```
Error during create table: CREATE TABLE dev_pre_aggregations.site_rollup_site_syqyodvd_gqbpdzkl_1h3cprl (`site__folder_id` varchar(255), `site__l_tree_path` ltree, `site__org_id` varchar(64), `site__parent` varchar(255), `site__count` bigint) LOCATION ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?: User: Custom type 'ltree' is not supported
```

**To Reproduce**
1. Create a schema with a dimension that maps to a `ltree` column in a Postgres database.
2. Start cubejs server
4. See aforementioned `Custom type 'ltree' is not supported` error.

**Expected behavior**
In order to work with hierarchical data in Postgress, the `ltree` type should be supported.

**Screenshots**
<img width="1741" alt="Screen Shot 2022-03-20 at 10 58 04 am" src="https://user-images.githubusercontent.com/82794139/159142397-d2c541f0-63ca-477d-82dd-0cbfce5c2ddd.png">

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
const sitesFolderTable = "folder_hierarchies";

cube(`Site`, {
  sql: `SELECT * FROM ${sitesFolderTable}`,

  preAggregations: {
    rollupSite: {
      external: true,
      type: `rollup`,
      measures: [CUBE.count],
      dimensions: [CUBE.folderId, CUBE.parent, CUBE.orgId, CUBE.lTreePath],
    },
    drilldown: {
      external: true,
      type: `rollup`,
      measures: [CUBE.count],
      dimensions: [CUBE.folderId, CUBE.parent, CUBE.orgId, CUBE.lTreePath],
    },
  },

  joins: {
    
  },

  measures: {
    count: {
      type: `count`
    },
  },

  dimensions: {
    folderId: {
      sql: `CONCAT('location_', REPLACE(folder_id::varchar, '-', ''))`,
      type: `string`,
      primaryKey: true,
    },

    createdAt: {
      sql: `from_unixtime(created_at / 1000)`,
      type: `time`
    },

    parent: {
      sql: `CONCAT('location_', REPLACE(parent::varchar, '-', ''))`,
      type: `string`
    },

    orgId: {
      sql: `org_id`,
      type: `string`
    },

    lTreePath: {
      sql: `path`,
      type: `string`, // <-- error originating here
    }
  },

  dataSource: `sites`
});
```

**Version:**
```json
"devDependencies": {
    "@aws-sdk/client-sts": "^3.47.0",
    "@aws-sdk/credential-provider-node": "^3.47.0",
    "@cubejs-backend/athena-driver": "0.29.28",
    "@cubejs-backend/postgres-driver": "^0.29.31",
    "@cubejs-backend/query-orchestrator": "^v0.29.28",
    "@cubejs-backend/server": "^0.29.28",
    "cubejs-cli": "^0.29.28",
    "npm-check-updates": "^12.1.0"
  }
```

**Additional context**

**Comment by paveltiunov** [comment]
Hey @manan-sc ! `ltree` is indeed not supported by Cube Store. You can just cast `ltree` to `text`.

**Comment by abrostoff** [comment]
@paveltiunov Our team is also interested in support for ltree - is this support on the roadmap by chance?
