### ISSUE TITLE
Join operation delivers null values - MongoDB

### ISSUE THREAD

**Issue by shaikwasef** [cube-js/cube.js#4245]
I’m currently working on MongoDB and have the following issue w.r.t joins .
I have a collection ( say A) which has an array of grpIds , which can also be empty . On the other hand I have one more collection ( say B) which has documents containing grpId and grpName .
I created a join b/w these two schemas , Although , CUBE.Js does not throw any error , I receive null values  for the grpName and the grpId  , Attached are the schemas : 

Schema for  A : 

`cube(`RegAlertsGroupIds`, {
  sql: `SELECT * FROM \`RegHub\`.\`reg_alerts_grpIds\``,

  refreshKey: {
    every: `30 minute`,
  },

  joins: {
    AlertsMeta: {
      relationship: `hasOne`,
      sql: `${CUBE}.\`grpIds\` = ${AlertsMeta}.\`alertGrpId\``,
    },
  },

  measures: {
    count: {
      type: `count`,
      drillMembers: [grpIds],
    },
  },

  dimensions: {
    grpIds: {
      sql: `${CUBE}.\`grpIds\``,
      type: `string`,
      title: `grpIds`,
    },
    _id: {
      sql: `_id`,
      type: `string`,
      primaryKey: true,
    },
  },

  dataSource: `default`,
});`

Schema for B : 

`cube(`AlertsMeta`, {
  sql: `SELECT alertGrpId , alertGrpName , tenantId FROM \`RegHub\`.alerts_meta`,

  joins: {
    tenants: {
      relationship: `belongsTo`,
      sql: `TRIM(CONVERT(${AlertsMeta.tenantId}, CHAR)) = TRIM(CONVERT( ${tenants}.tenantId, CHAR))`,
    },
  },

  measures: {
    count: {
      type: `count`,
      drillMembers: [alertGrpId, alertgrpName, tenantId],
    },
  },

  dimensions: {
    alertGrpId: {
      sql: `${CUBE}.\`alertGrpId\``,
      type: `string`,
      primaryKey: true,
    },
    alertgrpName: {
      sql: `${CUBE}.\`alertGrpName\``,
      type: `string`,
    },
    tenantId: {
      sql: `TRIM(CONVERT(${CUBE}.\`tenantId\`,CHAR))`,
      type: `string`,
    },
  },

  dataSource: `default`,
});`

Query : 

`{
  "dimensions": [
    "RegAlertsGroupIds.grpIds",
    "AlertsMeta.alertgrpName"
  ],
  "timeDimensions": [],
  "order": {
    "AlertsMeta.alertgrpName": "asc"
  },
  "measures": [],
  "filters": []
}`

Result : 

![image](https://user-images.githubusercontent.com/12941030/159205235-751a189d-e348-41bb-be21-46124630aa01.png)

**Comment by ivan-vdovin** [comment]
Hi @shaikwasef !
Could you [sign up to Cube Cloud](https://cubecloud.dev/auth/signup) with a free plan and try to reproduce that, please? This can help us to look into it and get more details.
