### ISSUE TITLE
Cube result is different than the SQL's one

### ISSUE THREAD

**Issue by ShinyCoconut** [cube-js/cube.js#4254]
Hi, I have noticed a weird fact:
I have implemented a new Cube schema, according to the data below:

```
`import` { filterTickets } from './helpers';

cube(`Tickets`, {
  sql: `SELECT * FROM public.tickets`,

  joins: {
    Employees: {
      sql: `${CUBE}.requestor_id = ${Employees}.id`,
      relationship: `belongsTo`
    },

    Floors: {
      sql: `${CUBE}.floor_id = ${Floors}.id`,
      relationship: `belongsTo`
    }
  },

  measures: {
    count: {
      type: `count`,
      sql: `id`,
      description: `Count all tickets`
    },

    countOpenTickets: {
      type: `countDistinct`,
      sql: `id`,
      filters: [
        { sql: `${filterTickets(CUBE, 0)}` },
      ],
      description: `Count all open tickets `
    },

    countOngoingTickets: {
      type: `countDistinct`,
      sql: `id`,
      filters: [
        { sql: `${filterTickets(CUBE, 1)}` },
      ],
      description: `Count all ongoing tickets `
    },

    countClosedTickets: {
      type: `countDistinct`,
      sql: `id`,
      filters: [
        { sql: `${filterTickets(CUBE, 2)}` },
      ],
      description: `Count all closed tickets `
    },

    countTotalTickets: {
      type: `countDistinct`,
      sql: `id`,
      description: `Count all tickets `
    },
  },

  segments: {
    now: {
      sql: `
        date_trunc('day', now()) <= ${CUBE}.created_at
        AND ${CUBE}.finished_at >= timezone('utc', now())
      `
    }
  },

  dimensions: {    
    id: {
      sql: `id`,
      type: `string`,
      primaryKey: true,
      shown: true
    },
    
    requestorId: {
      sql: `requestor_id`,
      type: `string`
    },

    solverId: {
      sql: `solver_id`,
      type: `string`
    },

    floorId: {
      sql: `solver_id`,
      type: `string`
    },
    
    createdAt: {
      sql: `created_at`,
      type: `time`
    },
    
    updatedAt: {
      sql: `updated_at`,
      type: `time`
    },

    finishedAt: {
      sql: `finished_at`,
      type: `time`
    },

    title: {
      sql: `title`,
      type: `string`
    },

    description: {
      sql: `description`,
      type: `string`
    },

    location: {
      sql: `location`,
      type: `string`
    },

    status: {
      sql: `status`,
      type: `string`
    },
  },
  
  dataSource: `default`
});
`
```

```
`export` const filterTickets = (cubeRef, value) => `
    ${cubeRef}.status = \(SELECT unnest\(enum_range\(NULL::\"ETicketStatus\"\)\) limit 1 offset ${value}\)
`;`
```

The filter function is horrible but it was the only way I found to be able to reference my PostgreSQL enum type "ETicketStatus" and it works.

The point is: every measure I use, with every time dimension, always returns 0 (zero), however, the own SQL query generated by Cube (verified in Cube terminal logs and on Postgres terminal logs as well) provides the right results.

Examples:

Cube Query structure

`{
  "measures": [
    "Tickets.countOngoingTickets"
  ],
  "timeDimensions": [
    {
      "dimension": "Tickets.updatedAt",
      "dateRange": "this month"
    }
  ],
  "filters": [
    {
      "member": "Floors.isActive",
      "operator": "equals",
      "values": [
        "t"
      ]
    }
  ],
  "timezone": "America/Sao_Paulo",
  "segments": []
}`

SQL Query (in Cube)

`  SELECT
      count(distinct CASE WHEN (
    "tickets".status = (SELECT unnest(enum_range(NULL::"ETicketStatus")) limit 1 offset 1)
) THEN "tickets".id END) "tickets__count_ongoing_tickets"
    FROM
      public.tickets AS "tickets"
LEFT JOIN public.floors AS "floors" ON "tickets".floor_id = "floors".id  WHERE ("tickets".updated_at >= '2022-03-01T03:00:00.000Z'::timestamptz AND "tickets".updated_at <= '2022-04-01T02:59:59.999Z'::timestamptz) AND ("floors".is_active = 't') LIMIT 10000`

The result brought by Cube is always 0 (zero) ("wrong"), however, the SQL query result in a direct query is different ("right").
I know I am certainly wrong and this is not a Cube problem, but could you, at least, point me out to the right direction on solving this?
Thank you very much, in advance ♥

**Comment by paveltiunov** [comment]
@ShinyCoconut It'd be beneficial if you can share SQL that returns the correct result for you then it'd be much simpler advice on how to achieve the same result in Cube.

**Comment by ShinyCoconut** [comment]
> @ShinyCoconut It'd be beneficial if you can share SQL that returns the correct result for you then it'd be much simpler advice on how to achieve the same result in Cube.

The SQL generated by Cube itself and shown in its terminal achieves the right result. It is present in the first message here.
