### ISSUE TITLE
Is it possible to query the current year up until the current date

### ISSUE THREAD

**Issue by sambowenhughes** [cube-js/cube.js#4277]
**Problem**
We are trying to query using the Cube.js dateRange filter. We are able to use the following:

```
"timeDimensions": [
                      {
                            "dimension": "DIMDATE.date",
                            "granularity": "week",
                            "dateRange": "this year"
                        }
                    ]
```

This gives us the current year but we don't want any dates in the future. What we seem to be getting back is the complete year.

**Question**
Is there a date range option that lets us query this year up until the current date? 

e.g.

```
"timeDimensions": [
                      {
                            "dimension": "DIMDATE.date",
                            "granularity": "week",
                            "dateRange": "from this year to now"
                        }
                    ]
```

**Comment by ivan-vdovin** [comment]
Hi @sambowenhughes !
Have you tried something like `from 12 months ago to now`:
[https://cube.dev/docs/query-format#time-dimensions-format](https://cube.dev/docs/query-format#time-dimensions-format)

**Comment by sambowenhughes** [comment]
That would work but it wouldn't give us the right result.

What we want is the start of the current year, up until today. What we have is a set of charts that need to be filtered by year this year, last year etc. The problem with filtering this year we only want the dates from the 1st of January 2022 up until the current date.

**Comment by ivan-vdovin** [comment]
Got it, thanks! It makes sense but for now, an additional filter for your query (date < today's date) looks like the easiest workaround.

**Comment by paveltiunov** [comment]
@sambowenhughes Hey Sam! Have you tried `from jan 1 to now`?
