### ISSUE TITLE
question: join only first match

### ISSUE THREAD

**Issue by Eywek** [cube-js/cube.js#4300]
**Problem**

Hello, I'm trying to use Cube.js to join 2 table, my issue is that when I do the join, we can have duplicated row. I probably need to use `ROW_NUMBER()` to ensure I get only 1 row, but I don't found how I can use it with cube.

**Related Cube.js schema**
```javascript
const {
  securityContext: { companyId },
} = COMPILE_CONTEXT;

cube(`WorkflowEvents`, {
  dataSource: 'bigquery',
  sql: `
SELECT * EXCEPT (row_number)
FROM (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY run_id,mode ORDER BY timestamp DESC) AS row_number
  FROM \`workflow_events_production_eu.workflow_events_${companyId}\`
  WHERE ${FILTER_PARAMS.WorkflowEvents.timestamp.filter(
    (from, to) => `timestamp BETWEEN TIMESTAMP(${from}) AND TIMESTAMP(${to})`
  )}
)
WHERE row_number = 1`,

  joins: {
    Workflows: {
      relationship: `belongsTo`,
      sql: `${CUBE.workflowId} = ${Workflows.id}`,
    }
  },

  measures: {
    count: {
      type: `count`
    },
    openerCount: {
      sql: `user_identifier`,
      type: `countDistinct`,
      filters: [{ sql: `${CUBE.mode} = 'display'` }]
    },
  },

  dimensions: {
    id: {
      sql: `${CUBE}.run_id`,
      type: `string`,
      primaryKey: true,
      shown: false
    },
    workflowId: {
      sql: `workflow_id`,
      type: `string`
    },
    timestamp: {
      sql: `timestamp`,
      type: `time`
    }
  }
})

const {
  securityContext: { companyId },
} = COMPILE_CONTEXT;

cube(`PurchaseEvents`, {
  dataSource: 'bigquery',
  sql: `
SELECT
  * EXCEPT (row_number)
FROM (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY eventId ORDER BY timestamp DESC) AS row_number
  FROM \`tracking_events_production_eu.tracking_events_${companyId}\`
  WHERE name = 'purchase' AND ${FILTER_PARAMS.WorkflowEvents.timestamp.filter(
    (from, to) => `timestamp BETWEEN TIMESTAMP(${from}) AND TIMESTAMP(${to})`
  )}
)
WHERE row_number = 1`,

  joins: {
    WorkflowEvents: {
      relationship: `belongsTo`,
      sql: `${WorkflowEvents}.user_identifier = ${CUBE}.userId
        AND ${CUBE}.timestamp > ${WorkflowEvents}.timestamp
        AND ${CUBE}.timestamp < DATE_ADD(${WorkflowEvents}.timestamp, INTERVAL 1 HOUR)
        AND ${WorkflowEvents}.mode = 'click'`,
    }
  },

  measures: {
    count: {
      type: 'count',
      filters: [{ sql: `${WorkflowEvents.workflowId} IS NOT NULL` }],
    }
  },

  dimensions: {
    id: {
      sql: `${CUBE}.eventId`,
      type: `string`,
      primaryKey: true,
      shown: false
    }
  }
})
```

I want to keep the WorkflowEvents join to use some dimensions from `WorkflowEvents` to filter on (and some from `Workflows` which is joined via `WorkflowEvents`). 

**Related Cube.js query**

```json
{
  "measures": [
    "PurchaseEvents.count"
  ],
  "timeDimensions": [
    {
      "dimension": "WorkflowEvents.timestamp",
      "dateRange": [
        "2022-02-01",
        "2022-04-01"
      ]
    }
  ],
  "order": {},
  "filters": [
    {
      "member": "WorkflowEvents.workflowId",
      "operator": "equals",
      "values": [
        "621f9055c05ce50007ec3d32"
      ]
    }
  ]
}
```

**Related Cube.js generated SQL**

```sql
SELECT
  count(
    CASE
      WHEN (`workflow_events`.workflow_id IS NOT NULL) THEN `purchase_events`.eventId
    END
  ) `purchase_events__count`
FROM
  (
    SELECT
      *
    EXCEPT
      (row_number)
    FROM
      (
        SELECT
          *,
          ROW_NUMBER() OVER (
            PARTITION BY eventId
            ORDER BY
              timestamp DESC
          ) AS row_number
        FROM
          `tracking_events_production_eu.tracking_events_619e756f0a5c180012e4de73`
        WHERE
          name = 'purchase'
          AND timestamp BETWEEN TIMESTAMP(?)
          AND TIMESTAMP(?)
      )
    WHERE
      row_number = 1
  ) AS `purchase_events`
  LEFT JOIN (
    SELECT
      *
    EXCEPT
      (row_number)
    FROM
      (
        SELECT
          *,
          ROW_NUMBER() OVER (
            PARTITION BY run_id,
            mode
            ORDER BY
              timestamp DESC
          ) AS row_number
        FROM
          `workflow_events_production_eu.workflow_events_619e756f0a5c180012e4de73`
        WHERE
          timestamp BETWEEN TIMESTAMP(?)
          AND TIMESTAMP(?)
      )
    WHERE
      row_number = 1
  ) AS `workflow_events` ON `workflow_events`.user_identifier = `purchase_events`.userId
  AND `purchase_events`.timestamp > `workflow_events`.timestamp
  AND `purchase_events`.timestamp < DATE_ADD(`workflow_events`.timestamp, INTERVAL 1 HOUR)
  AND `workflow_events`.mode = 'click'
WHERE
  (
    `workflow_events`.timestamp >= TIMESTAMP(?)
    AND `workflow_events`.timestamp <= TIMESTAMP(?)
  )
  AND (`workflow_events`.workflow_id = ?)
LIMIT
  10000
```

Which returns `4` for following events:

`purchase_events.eventId` | `workflow_events.mode` | `workflow_events.run_id`
-- | -- | --
cl0xntjtd00013t7wa0908eej | click | 8dcf0006-b21f-4935-8f72-00d7a500ba37
cl0xntjtd00013t7wa0908eej | click | 53cfddd9-8ee0-43e1-ba3e-008e9ff56495
cl1bv6qhn00013t8f2ovvf0yi | click | 53ab8321-2810-4a52-ac37-392ca15db392
cl1bv6qhn00013t8f2ovvf0yi | click | 16628647-1524-4829-951f-4478262a4def

But the expected result is 2:

`purchase_events.eventId` | `workflow_events.mode` | `workflow_events.run_id`
-- | -- | --
cl0xntjtd00013t7wa0908eej | click | 8dcf0006-b21f-4935-8f72-00d7a500ba37
cl1bv6qhn00013t8f2ovvf0yi | click | 53ab8321-2810-4a52-ac37-392ca15db392

Thank you

**Comment by paveltiunov** [comment]
Hey @Eywek ! You get this duplication due to you actually have many-to-many relationship instead of belongs to from `PurchaseEvents` to `WorkflowEvents`. Please see https://cube.dev/docs/schema/fundamentals/joins#many-to-many-joins.

**Comment by Eywek** [comment]
> Hey @Eywek ! You get this duplication due to you actually have many-to-many relationship instead of belongs to from `PurchaseEvents` to `WorkflowEvents`. Please see [cube.dev/docs/schema/fundamentals/joins#many-to-many-joins](https://cube.dev/docs/schema/fundamentals/joins#many-to-many-joins).

I've tried to update `relationship` between `PurchaseEvents` and `PurchaseEvents` to `hasOne` and it didn't change anything. Did I miss something?

**Comment by Eywek** [comment]
So, I've updated to hasMany but I have the following dimension in my `PurchaseEvents` cube:

```js
  averageBasketValue: {
      type: `avg`,
      sql: `value`,
      format: `currency`,
      filters: [{ sql: `${WorkflowEvents.workflowId} IS NOT NULL` }],
    }
```

But I'm having the following error:

```
Error: 'PurchaseEvents.averageBasketValue' references cubes that lead to row multiplication. Please rewrite it using sub query.
```

But from what I've seen on the documentation I can't use subqueries here since I don't use a measure from another cube

**Comment by Eywek** [comment]
So, I'm not having duplicated rows anymore when using `count` or `avg` thank you.

But, I have the following dimension on `WorkflowEvents`:
```js
  isIndividualized: {
      type: `boolean`,
      sql: `(SELECT ${CUBE}.executed_branch IN UNNEST(${WorkflowVersions.individualizedBranches}))`
    },
```

and when I use the following query:

```json
{
  "measures": [
    "PurchaseEvents.count"
  ],
  "timeDimensions": [
    {
      "dimension": "WorkflowEvents.timestamp",
      "dateRange": [
        "2022-03-07",
        "2022-04-06"
      ]
    }
  ],
  "order": {
    "PurchaseEvents.count": "desc"
  },
  "filters": [],
  "dimensions": [
    "WorkflowEvents.isIndividualized"
  ]
}
```

I'm having events duplicated, because we have:

workflow_events__is_individualized | eventId
-- | --
true | cl1ep8frz00003k5mk41vexmz
true | cl1ep6y7k0000395mdmylvtmt
false | cl1ep3xju00003p645ks0ps74
true | cl1ep3xju00003p645ks0ps74
true | cl1dt6bq20000545xfjkf2gvs

We can see that the `cl1ep3xju00003p645ks0ps74` purchase event is in `workflow_events__is_individualized=true` and `workflow_events__is_individualized=false` where I only want it to be in `workflow_events__is_individualized=true`.

Can I do that with Cube.js?

Thank you!

**Comment by Eywek** [comment]
Any idea @paveltiunov?

Thank you

**Comment by paveltiunov** [comment]
@Eywek For many-to-many relationships, you need 3 cubes instead of 2. Please see example in https://cube.dev/docs/schema/fundamentals/joins#many-to-many-joins.
