### ISSUE TITLE
How can I monitor Cube.js with Datadog

### ISSUE THREAD

**Issue by MekLoops** [cube-js/cube.js#4317]
My company is looking to monitor Cube.js with Datadog. However, we can find documentation on how to configure it. Can you point me to the right direction?

**Comment by ivan-vdovin** [comment]
Hi @MekLoops !
We don't have such an example for now. Would you be so kind to share additional details on what you would like to monitor except Cube API state and logs?
Perhaps you'd be interested in Cube Cloud as it provides some additional features such as email alerts, query tracing, performance monitoring for API instances and source database.
