### ISSUE TITLE
Documentation on implementing support for a new backend?

### ISSUE THREAD

**Issue by fulmicoton** [cube-js/cube.js#4331]
Is there documentation somewhere on implementing a new backend?

I see SQL is used both for mongo, elastic and druid.
Is the use of SQL a necessity or would it have been possible to use a non-SQL API by implementing some kind of query builder?

If the latter is possible is there an example backend that does not rely on SQL?

**Comment by paveltiunov** [comment]
Hey @fulmicoton ! I guess https://github.com/cube-js/cube.js/blob/master/CONTRIBUTING.md#implementing-a-driver would be the right starting point.
