### ISSUE TITLE
Query result not cached.

### ISSUE THREAD

**Issue by gedaaaa** [cube-js/cube.js#4339]
**Problem**

I'm using cubejs with cube store, and I found that item count in Redis is not increasing.
If I change store to database internal, this count will increase very fast.
Is this intended or bug?

**Comment by ivan-vdovin** [comment]
Hi @gedaaaa !
Could you please share your setup and steps to reproduce that?

**Comment by paveltiunov** [comment]
Hey @gedaaaa ! This is correct behavior. Cube Store has its own query cache.
