### ISSUE TITLE
Join not working as expected in CubeStore

### ISSUE THREAD

**Issue by manan-sc** [cube-js/cube.js#4359]
**Describe the bug**
While joining across two different cubes and using filters, the CubeStore returns results that should not be part of the response. In essence, the JSON query and the SQL query that is seen in the playground are correct, but the results don't live up to that expectation.

FWIW, the `countryId` and `siteId` in `SiteMappings` cube follow a parent-child relationship.

**To Reproduce**

Consider - 
- Cube 1 - `Inspections` [has a dimension `site_id`]
- Cube 2 - `SiteMappings` [has a dimension (primary_key) `site_id`]
- A `combinedRollup` of type `rollupJoin` between the two cubes on `Inspections.siteId = SiteMappings.siteId`.
- Have a filter in the query.

To get a gist of the queries, please read below.
<details>
<summary>JSON Query</summary>
<pre>
<code>
{
  "measures": [
    "CubeInspection.count"
  ],
  "timeDimensions": [
    {
      "dimension": "CubeInspection.conductedAt",
      "dateRange": "Last 7 days"
    }
  ],
  "order": {
    "CubeInspection.count": "desc"
  },
  "dimensions": [
    "SiteAllMappings.countryId"
  ],
  "filters": [
    {
      "member": "SiteAllMappings.countryId",
      "operator": "set"
    },
    {
      "member": "SiteAllMappings.countryId",
      "operator": "equals",
      "values": [
        "aada4b91-0650-480c-8f41-78162c7df20b"
      ]
    }
  ]
}
</code>
</pre>
</details>

<details>
<summary>SQL Query</summary>
<pre>
<code>
SELECT
  `site_all_mappings__country_id` `site_all_mappings__country_id`,
  sum(`cube_inspection__count`) `cube_inspection__count`
FROM
  dev_pre_aggregations.cube_inspection_rollup_inspection AS `cube_inspection__rollup_inspection`
  LEFT JOIN dev_pre_aggregations.site_all_mappings_rollup_site_all_mappings AS `site_all_mappings__rollup_site_all_mappings` ON `cube_inspection__site_id` = `site_all_mappings__site_id`
WHERE
  (`site_all_mappings__country_id` IS NOT NULL)
  AND (`site_all_mappings__country_id` = ?)
  AND (
    `cube_inspection__conducted_at_day` >= to_timestamp(?)
    AND `cube_inspection__conducted_at_day` <= to_timestamp(?)
  )
GROUP BY
  1
ORDER BY
  2 DESC
LIMIT
  10000
</code>
</pre>
</details>

<details>
<summary>Output</summary>
<pre>
<code>
{
    "query": {
        "measures": [
            "CubeInspection.count"
        ],
        "timeDimensions": [
            {
                "dimension": "CubeInspection.conductedAt",
                "dateRange": [
                    "2022-04-04T00:00:00.000",
                    "2022-04-10T23:59:59.999"
                ]
            }
        ],
        "order": [
            {
                "id": "CubeInspection.count",
                "desc": true
            }
        ],
        "dimensions": [
            "SiteAllMappings.countryId"
        ],
        "filters": [
            {
                "operator": "set",
                "member": "SiteAllMappings.countryId"
            },
            {
                "operator": "equals",
                "values": [
                    "aada4b91-0650-480c-8f41-78162c7df20b"
                ],
                "member": "SiteAllMappings.countryId"
            }
        ],
        "timezone": "UTC"
    },
    "data": [
        {
            "SiteAllMappings.countryId": null,
            "CubeInspection.count": "1488"
        },
        {
            "SiteAllMappings.countryId": "aada4b91-0650-480c-8f41-78162c7df20b",
            "CubeInspection.count": "10"
        }
    ],
    "lastRefreshTime": "2022-04-11T05:31:01.000Z",
    "usedPreAggregations": {
        "dev_pre_aggregations.cube_inspection_rollup_inspection": {
            "targetTableName": "dev_pre_aggregations.cube_inspection_rollup_inspection20220401_faz2m0tv_ea2hhwl5_1h57t88",
            "refreshKeyValues": [
                []
            ],
            "lastUpdatedAt": 1649669384000,
            "type": "rollup"
        },
        "dev_pre_aggregations.site_all_mappings_rollup_site_all_mappings": {
            "targetTableName": "dev_pre_aggregations.site_all_mappings_rollup_site_all_mappings_35zgrlri_v5zspxcq_1h57f8l",
            "refreshKeyValues": [],
            "lastUpdatedAt": 1649655061000,
            "type": "rollup"
        }
    },
    "transformedQuery": {
        "sortedDimensions": [
            "SiteAllMappings.countryId"
        ],
        "sortedTimeDimensions": [
            [
                "CubeInspection.conductedAt",
                "week"
            ]
        ],
        "timeDimensions": [
            [
                "CubeInspection.conductedAt",
                null
            ]
        ],
        "measures": [
            "CubeInspection.count"
        ],
        "leafMeasureAdditive": true,
        "leafMeasures": [
            "CubeInspection.count"
        ],
        "measureToLeafMeasures": {
            "CubeInspection.count": [
                {
                    "measure": "CubeInspection.count",
                    "additive": true
                }
            ]
        },
        "hasNoTimeDimensionsWithoutGranularity": false,
        "allFiltersWithinSelectedDimensions": true,
        "isAdditive": true,
        "granularityHierarchies": {
            "year": [
                "year",
                "quarter",
                "month",
                "month",
                "day",
                "hour",
                "minute",
                "second"
            ],
            "quarter": [
                "quarter",
                "month",
                "day",
                "hour",
                "minute",
                "second"
            ],
            "month": [
                "month",
                "day",
                "hour",
                "minute",
                "second"
            ],
            "week": [
                "week",
                "day",
                "hour",
                "minute",
                "second"
            ],
            "day": [
                "day",
                "hour",
                "minute",
                "second"
            ],
            "hour": [
                "hour",
                "minute",
                "second"
            ],
            "minute": [
                "minute",
                "second"
            ],
            "second": [
                "second"
            ]
        },
        "hasMultipliedMeasures": false,
        "hasCumulativeMeasures": false,
        "windowGranularity": null,
        "filterDimensionsSingleValueEqual": {}
    },
    "requestId": "64242640-749e-4000-894e-7407a4c8f807-span-1",
    "annotation": {
        "measures": {
            "CubeInspection.count": {
                "title": "Cube Inspection Count",
                "shortTitle": "Count",
                "type": "number",
                "drillMembers": [],
                "drillMembersGrouped": {
                    "measures": [],
                    "dimensions": []
                }
            }
        },
        "dimensions": {
            "SiteAllMappings.countryId": {
                "title": "Site All Mappings Country Id",
                "shortTitle": "Country Id",
                "type": "string"
            }
        },
        "segments": {},
        "timeDimensions": {}
    },
    "dataSource": "inspections",
    "dbType": "athena",
    "extDbType": "cubestore",
    "external": true,
    "slowQuery": false
}
</code>
</pre>
</details>

**Expected behavior**
Filters across a rollupJoin should work as expected. When you look at the output above, or the screenshot below, there is a row with `null` countryId, in spite the filter specifying that it should not be `null`.

**Screenshots**
![Screen Shot 2022-04-12 at 8 43 00 am](https://user-images.githubusercontent.com/82794139/162845182-e8748a44-a9b6-4f38-852c-12e5f8acccf3.png)

**Minimally reproducible Cube Schema**
<details>
<summary><code>CubeInspection.js</code></summary>
<pre><code>
const inspectionRootTable = "public.table";
const partitionFilter = (from, to) => `date(from_iso8601_timestamp(${from})) <= conducted_date AND date(from_iso8601_timestamp(${to})) >= conducted_date`;

cube(`CubeInspection`, {
    sql: `SELECT *
          FROM ${inspectionRootTable}
          WHERE ${FILTER_PARAMS.CubeInspection.conductedAt.filter(partitionFilter)}`,

    preAggregations: {
        rollupInspection: {
            external: true,
            type: `rollup`,
            measures: [CUBE.count],
            dimensions: [CUBE.organisationId, CUBE.siteId],
            timeDimension: CUBE.conductedAt,
            granularity: `day`,
            partitionGranularity: `month`,
            scheduledRefresh: true,
            indexes: {
                categoryIndex: {
                    columns: [CUBE.siteId],
                }
            },
            refreshKey: {
                every: `15 minute`,
                sql: `SELECT MAX(_hoodie_commit_time)
                      FROM ${inspectionRootTable}
                      WHERE ${FILTER_PARAMS.CubeInspection.conductedAt.filter(partitionFilter)}`
            },
            buildRangeStart: {
                sql: `SELECT NOW() - interval '730' day`,
            },
            buildRangeEnd: {
                sql: `SELECT NOW()`,
            }
        },
        drilldown: {
            external: true,
            measures: [],
            dimensions: [CUBE.auditId, CUBE.organisationId, CUBE.siteId, CUBE.conductedAt],
            timeDimension: CUBE.conductedAt,
            granularity: `day`,
            partitionGranularity: `week`,
            scheduledRefresh: true,
            indexes: {
                categoryIndex: {
                    columns: [CUBE.siteId],
                }
            },
            refreshKey: {
                every: `15 minute`,
                sql: `SELECT MAX(_hoodie_commit_time)
                      FROM ${inspectionRootTable}
                      WHERE ${FILTER_PARAMS.CubeInspection.conductedAt.filter(partitionFilter)}`
            },
            buildRangeStart: {
                sql: `SELECT NOW() - interval '730' day`,
            },
            buildRangeEnd: {
                sql: `SELECT NOW()`,
            }
        },
        combinedRollup: {
            type: `rollupJoin`,
            measures: [CubeInspection.count],
            dimensions: [CUBE.siteId, CUBE.organisationId, SiteAllMappings.siteId, SiteAllMappings.areaId, SiteAllMappings.regionId, SiteAllMappings.countryId, SiteAllMappings.orgId],
            timeDimension: CubeInspection.conductedAt,
            granularity: `day`,
            rollups: [SiteAllMappings.rollupSiteAllMappings, CUBE.rollupInspection],
            external: true,
        },
    },

    joins: {
        SiteAllMappings: {
            relationship: `belongsTo`,
            sql: `${CubeInspection.siteId} = ${SiteAllMappings.siteId}`,
        }
    },

    measures: {
        count: {
            type: `count`
        }
    },

    dimensions: {
        auditId: {
            sql: `audit_id`,
            type: `string`,
            primaryKey: true,
            shown: true,
        },

        conductedAt: {
            sql: `from_unixtime(conducted_at / 1000)`,
            type: `time`
        },

        organisationId: {
            sql: `organisation_id`,
            type: `string`
        },

        siteId: {
            sql: `site_id`,
            type: `string`
        },
    },

    dataSource: `inspections`
});

</code></pre>
</details>
<details>
<summary><code>SiteAllMappings.js</code></summary>
<pre><code>
const sites = "public.sites_table";

cube(`SiteAllMappings`, {
    sql: `SELECT *
          FROM ${sites}
    `,

    preAggregations: {
        rollupSiteAllMappings: {
            external: true,
            type: `rollup`,
            measures: [CUBE.count],
            dimensions: [CUBE.siteId, CUBE.countryId, CUBE.orgId],
            indexes: {
                categoryIndex: {
                    columns: [CUBE.siteId],
                }
            },
        },
        drilldown: {
            external: true,
            type: `rollup`,
            measures: [CUBE.count],
            dimensions: [CUBE.siteId, CUBE.countryId, CUBE.orgId],
        },
    },

    measures: {
        count: {
            type: `count`
        },
    },

    dimensions: {
        siteId: {
            sql: `site_id`,
            type: `string`,
            primaryKey: true,
            shown: true,
        },

        countryId: {
            sql: `country_id`,
            type: `string`,
        },

        orgId: {
            sql: `org_id`,
            type: `string`,
        },
    },

    dataSource: `sites`
});
</code></pre>
</details>

**Version:**
```json
"devDependencies": {
    "@aws-sdk/client-sts": "^3.54.1",
    "@aws-sdk/credential-provider-node": "^3.54.1",
    "@cubejs-backend/athena-driver": "0.29.33",
    "@cubejs-backend/postgres-driver": "^0.29.33",
    "@cubejs-backend/query-orchestrator": "^v0.29.33",
    "@cubejs-backend/server": "^0.29.33",
    "cubejs-cli": "^0.29.33",
    "npm-check-updates": "^12.5.4"
  }
```

**Comment by bong-sc** [comment]
Related to this https://github.com/cube-js/cube.js/issues/3777?

**Comment by paveltiunov** [comment]
Moving conversation to #3777

**Comment by manan-sc** [comment]
Fixed in https://github.com/cube-js/cube.js/commit/c77586961078ec67395af39e3f233025833d4f6e.
