### ISSUE TITLE
Limits on the Number of Cached Queries

### ISSUE THREAD

**Issue by emir-jdv** [cube-js/cube.js#4397]
Is there any adverse impact on performance of scaling the number of cached queries? Assume that infrastructure scales accordingly.

I am trying to gauge a use case of serving potentially millions of cached queries. Cube seems to be ticking a lot of the boxes.

**Comment by paveltiunov** [comment]
@emir-jdv If you're looking to cache million of queries you most likely need to use pre-aggregations at that point.
