### ISSUE TITLE
graphQL schema does not let fields be nullable

### ISSUE THREAD

**Issue by MarkLyck** [cube-js/cube.js#4399]
**Describe the bug**
While trying to switch from cubejs react client to using the graphQL endpoint instead I'm running into some issues with nullable fields.

In our cubejs schema we are setting the fields as "string" like this:

```js
vlan_name: {
  type: 'string',
  sql: 'vlan_name',
  title: 'Vlan name'
},
```

In our data source this can either be a String or null (empty).

and that works fine in the Cubejs React client. It does not complain if the response ends up being null.

However when trying to query this in the graphQL schema I am running into errors like this:

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field CloudNacLatestStatusByInterfaceMembers.vlan_name.",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "cube",
        0,
        "cloudNacLatestStatusByInterface",
        "vlan_name"
      ]
    }
  ],
  "data": null
}
```

This error is completely blocking us from using the graphQL endpoint as we can't query some cubes at all for the data we need.

and looking at the graphQL schema, it is saved in there as `String!` (non-nullable field).

**To Reproduce**
1. Setup a datasource where some fields are null and others are strings on a column.
2. set the cubejs schema type to "string".
3. Attempt to query this using the graphQL endpoint

**Expected behavior**
I don't think graphQL here is the problem. The problem seems to me, that there are no "nullable" types in the cube schema so when cubejs generate the graphQL schema from the cubejs Scema, it can't possibly know if it should be `String!` or `String`.

The ideal solution is to add nullable types to cubejs.

Failing that, the graphQL schema should assume everything is nullable although this obviously isn't ideal as it doesn't represent the source of truth.

**Version:**
0.29.4

**Comment by MarkLyck** [comment]
@paveltiunov I would probably argue this a `bug` and not just an "enhancement" given it's completely blocking being able to use the graphQL endpoint and it's not "intended" to block people from using it?

The simple short term fix here, is just to change the default from `String!` to `String` in the graphQL schema generator. That should be backwards compatible too.

Then you can call it an enhancement to add a way to define types as nullable or whatever the longterm solution ends up being?

**Comment by paveltiunov** [comment]
@MarkLyck I agree it's a bug. Changed label.
