### ISSUE TITLE
Is there any development progress of add a connector for Metabase?

### ISSUE THREAD

**Issue by Lin-Aurora** [cube-js/cube.js#4404]
Hello,
I would like to know whether add a connector for metabase is in development progress?
Thanks!

**Comment by ovr** [comment]
Hello @Lin-Aurora ,

It worked with some limitations with [SQL API](https://cube.dev/docs/backend/sql) via MySQL protocol. Right now we are working on two big things for SQL API which should unblock it: A new query engine & PostgreSQL protocol support.

Thanks

**Comment by Lin-Aurora** [comment]
Thanks for your reply @ovr ,
Does this mean Metabase can only use REST API connections at present?
I refer to the [metabase-cubejs-driver](https://github.com/lili-data/metabase-cubejs-driver)

**Comment by abdel-87** [comment]
@ovr why did Cubejs chose to mimic some SQL protocol instead of building connectors that generate JSON queries instead of SQL? IMO it would be much cleaner, then trying to mimic a SQL protocol

**Comment by abdel-87** [comment]
By mimicing a SQL protocol, Cube JS would retrieve the SQL from the BI Tool, translate it to JSON and then translating it back to SQL? That naturally sounds as a big unnecessary workaround.

In the end Cube will anyway need to create and update all supported connectors, based on the updates of BI tools.

**Comment by paveltiunov** [comment]
@abdel-87 This is a great question! The reason for it is we're aiming for support of most downstream data tools out there. There're hundreds of those if not thousands. It'd be not feasible for us to implement integration with each of those however supporting a subset of Postgres Analytical SQL is doable and it can be done in a centralized manner for all tools altogether.

**Comment by paveltiunov** [comment]
Implementation progress is available here #3906
