### ISSUE TITLE
results not converted to timezone unless granularity is set: value fails to match the required pattern

### ISSUE THREAD

**Issue by jhofeditz** [cube-js/cube.js#443]
**Describe the bug**
When a dimension of type time is returned, it is in the server timezone (UST) regardless of the timezone setting. We do not need time filtering or grouping. But if I set a granularity, the result time is set according to the timezone.
As a workaround, I figured out that we can use second granularity:
`timeDimensions: [{dimension: 'issue.resolvedTime', granularity: 'second'}]`
Though, adding second to the Dimension itself fails with this exception:
`value "issue.resolvedTime.second" fails to match the required pattern: /^[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+(\.(hour|day|week|month|year))?$/]]`

This problem was mentioned in #196 but the other user actually wanted granularity so I'm not sure if the underlying issue was addressed.

**To Reproduce**
schema:
```
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    resolvedTime: {
      sql: `resolved_time`,
      type: `time`,
    },
}
```
query:
```
  dimensions: [
    'issue.resolvedTime',
  ],
  timezone: 'America/Chicago'
```
**Expected behavior**
All fields with type time should return in local timezone if timezone key is set.

**Version:**
0.17.10 with Postgres backend

**Additional context**

**Comment by paveltiunov** [comment]
@jhofeditz Hey Joe! Thanks for posting this one! Yep. It's right behavior: if you select dimension directly it's treated as a regular dimension without any transformations. However time dimensions are always go through time zone conversions to client tz. 

Missing granularity definition in API gateway is a bug. Let's use this issue to track it.

You can also checkout this one: https://cube.dev/docs/cube#context-variables-sql-utils

**Comment by jhofeditz** [comment]
Thanks Pavel! This is exactly what I needed. I thought I had read all of the documentation but I guess I never read to the bottom of the cube page. Nice to have more granularity options as well.
