### ISSUE TITLE
Typos in Dockerfile

### ISSUE THREAD

**Issue by jaehyeongchoe** [cube-js/cube.js#4538]
In dev.Dockerfile at line 12
```
RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends rxvt-unicode libssl1.1 curl cmake \
    && rm -rf /var/lib/apt/lists/* \

ENV RUSTUP_HOME=/usr/local/rustup
```
There is  "\" at the and of rm command
So Env RUSTUP_HOME is not applied.

Also, it is tiny, though

In latest.Dockerfile at line 21 and latest-alpine.Dockerfile at line 18
in comment
`buld -> build`

**Comment by paveltiunov** [comment]
@jaehyeongchoe Does it fail for you? If so could you please provide an error message?
