### ISSUE TITLE
devDependencies vs dependencies 

### ISSUE THREAD

**Issue by tsummerl** [cube-js/cube.js#4552]
Hi!

I have a question regarding why are cube.js packages installed under devDependencies instead of dependencies and why this is a requirement? What does this break if I install under dependencies?

Thanks in advance!

**Comment by ivan-vdovin** [comment]
Hi @tsummerl !
What do you mean by requirement here? You should be able to install cube as a dependency for your project.
Sharing an example for your project will let me be more specific.

**Comment by ivan-vdovin** [comment]
It allows using third-party dependencies and at the same time uses Cube dependencies from docker image. So it’s a way not to clash Cube dependencies in a docker image and in node_modules in production environments.
