### ISSUE TITLE
Can't import a variable from other file

### ISSUE THREAD

**Issue by MouadBH** [cube-js/cube.js#4562]
**Describe the bug**
I tried to import a variable from other javascript file to the file of my cube, but  I faced this problem while when I used `import`, photo of the error below.

**To Reproduce**
I followed the instructions in this link [https://cube.dev/docs/schema/reference/execution-environment#import-export](https://cube.dev/docs/schema/reference/execution-environment#import-export)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/28781942/169302429-b254c48f-e6d9-403a-b7fc-ed502c866472.png)
![image](https://user-images.githubusercontent.com/28781942/169302452-a7b8c340-1325-4fdf-9915-589209476b65.png)
![image](https://user-images.githubusercontent.com/28781942/169302485-6fc7561b-bea9-42eb-833c-f549800f5b50.png)

**Version:**
[0.29.23]

**Additional context**
MiskQ.js and schools.js are in the same folder.

**Comment by ivan-vdovin** [comment]
Hey @MouadBH ,
Have you tried to use exactly the same folder? I would like to know if it works at all for you
