### ISSUE TITLE
connect to MS SQL server using windows authentication and get an error (ConnectionError: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication))

### ISSUE THREAD

**Issue by nimblestart** [cube-js/cube.js#4585]
I'm trying to connect to MS SQL server using windows authentication and get an error, below is my setup, can I get help for this issue.

**.env file**
CUBEJS_DB_HOST=//removed for the post
CUBEJS_DB_NAME=<YOUR_DB_NAME>
CUBEJS_DB_PORT=<YOUR_DB_PORT>
CUBEJS_DB_USER=<YOUR_DB_USER>
CUBEJS_DB_PASS=<YOUR_DB_PASS>
CUBEJS_DB_DOMAIN=<YOUR_DB_DOMAIN>
CUBEJS_DEV_MODE=true
CUBEJS_DB_TYPE=mssql
CUBEJS_API_SECRET=//removed for the post
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true

**cube.js**
// Cube.js configuration options: https://cube.dev/docs/config
const MssqlDriver = require('@cubejs-backend/mssql-driver');
module.exports = {
  driverFactory: ({ dataSource }) =>
    new MssqlDriver({ database: dataSource, trustedConnection: true }),
};

**Error Message**
Error while loading DB schema
ConnectionError: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. at Connection.<anonymous> (C:\Code\cubejs\test2\node_modules\mssql\lib\tedious\connection-pool.js:68:17) at Object.onceWrapper (node:events:642:26) at Connection.emit (node:events:527:28) at Connection.message (C:\Code\cubejs\test2\node_modules\tedious\lib\connection.js:2201:18) at Connection.dispatchEvent (C:\Code\cubejs\test2\node_modules\tedious\lib\connection.js:1279:15) at MessageIO.<anonymous> (C:\Code\cubejs\test2\node_modules\tedious\lib\connection.js:1139:14) at MessageIO.emit (node:events:527:28) at Message.<anonymous> (C:\Code\cubejs\test2\node_modules\tedious\lib\message-io.js:46:14) at Message.emit (node:events:539:35) at endReadableNT

**Comment by paveltiunov** [comment]
@nimblestart MSSQL domain authentication isn't part of open source.
