### ISSUE TITLE
Compare to previous period

### ISSUE THREAD

**Issue by 0x62** [cube-js/cube.js#461]
I’ve got an events table, and I query count of events over a time range. Is it possible return the data for the previous range in the same request, so they can be charted together?

**Comment by paveltiunov** [comment]
@0x62 Hey Ben! Thanks for posting this one! 

As for now the simplest way to do this is to do 2 separate requests. If you want to achieve network request batching you can consider web socket transport: https://cube.dev/docs/real-time-data-fetch#web-sockets

Let's use this issue to track enhancement to support comparisons in API.

**Comment by magno32** [comment]
I'm looking to do this as well.

Essentially, my schema is like this (not actual though): 

```javascript

cube(`Sales`, {
    sql: `SELECT * FROM sales_db.\`sales\``,

    joins: {
        Seller: {
            sql: `${CUBE}.\`sellerId\` = ${Sellers}.id`,
            relationship: `belongsTo`
        }
    },

    measures: {
        unitsSold: {
            sql: `${CUBE}.units`,
            type: `sum`
        }
    },

    dimensions: {
        id: {
            sql: `id`,
            type: `number`,
            primaryKey: true
        },
        salesDate: {
            sql: `salesDate`,
            type: `time`
        },
        yoySalesDate: {
            sql: `DATE_SUB(${CUBE.salesDate}, INTERVAL 1 YEAR)`,
            type: `time`
        }
    }
});
```
I'm wanting to do this year-over-year.  In SQL I would simply join the table with itself on `yoySalesDate = other.salesDate AND sellerId = other.sellerId` and coalesce the `null` values to 0.

Is there a way join the cube to itself in this way?

**Comment by paveltiunov** [comment]
@magno32 The most optimal way of doing it in SQL is https://cube.dev/docs/data-blending#top. However two separate requests should work much better from scalability standpoint.

**Comment by magno32** [comment]
@paveltiunov 

Maybe I'm mis-reading, but would: https://cube.dev/docs/measures#parameters-rolling-window solve this as well?

I need to play around with it, but say I have a date range `2020-01-01 :: 2020-06-01`, would rolling-window of `1 year` not produce results from `2019-01-01 :: 2019-06-01`?

**Comment by vasilev-alex** [comment]
Please see the updated docs on the `compareDateRange` usage here https://cube.dev/docs/query-format#time-dimensions-format and let me know should you have any questions.

**Comment by magno32** [comment]
@vasilev-alex I updated the dependencies for the server, they are:

```json
  "dependencies": {
    "@cubejs-backend/postgres-driver": "^0.20.6",
    "@cubejs-backend/server": "^0.20.6",
    "@cubejs-backend/serverless": "^0.20.6",
    "@cubejs-backend/serverless-aws": "^0.20.6"
  }
```

I'm getting the following response when I try to run the example:

```json
{
    "error": "'compareDateRangeQuery' query type is not supported by the client. Please update the client."
}
```

**Comment by magno32** [comment]
Looks like I needed to add `"queryType": "multi"` as a parameter.  Is this correct (found it in the `client` source).  We aren't using the client, so this may need to be in the docs as well.

**Comment by ranjeetranjan** [comment]
Adding "queryType": "multi" in the JSON request will work. Here you go example. 

`{
    "queryType": "multi",
	"query": {
		"dimensions": [],
		"measures": [
			"student.totalStudent"
		],
		"timeDimensions": [{
			"dimension": "student.createdAt",
			"compareDateRange": [
				["2022-01-01", "2022-12-31"],
				["2021-01-01", "2021-12-31"]
			],
			"granularity": "month"
		}]
	}
    
}`
