### ISSUE TITLE
/cubejs-api/v1/sql : cast parameters are included in returned SQL which is not valid.

### ISSUE THREAD

**Issue by ThomasKientz** [cube-js/cube.js#4614]
With Clickhouse.

This http query to `/cubejs-api/v1/sql` for the query :

`{"dimensions":["ReseauFactureReseauCoverage.annee"],"filters":[{"member":"ReseauFactureReseauCoverage.annee","operator":"equals","values":["2019"]}],"limit":10000}`

returns the following SQL 

> "SELECT\n      `reseau_facture_reseau_coverage`.annee `reseau_facture_reseau_coverage__annee`\n    FROM\n      (SELECT ic.parent_id as ic_parent_ic, ic.child_id as ic_child_id, rfrc.* \n  FROM melolo_prod_ucanss.bi_reseau_facture_reseau_coverage rfrc\n  join melolo_prod_ucanss.implantation_closure ic \n  on rfrc.idimplantation_child = ic.child_id) AS `reseau_facture_reseau_coverage`  WHERE (`reseau_facture_reseau_coverage`.annee = toFloat64(?)) GROUP BY `reseau_facture_reseau_coverage__annee` ORDER BY `reseau_facture_reseau_coverage__annee` ASC LIMIT 10000"

This part is not valid SQL  :

> WHERE (`reseau_facture_reseau_coverage`.annee = toFloat64(?))

I guess it comes from :

https://github.com/cube-js/cube.js/blob/e8c72d630eecd930a8fd36fc52f9b594a45d59c0/packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.js#L25

Final SQL query sent to clickhouse is indeed correct. It is only the SQL returned from `/cubejs-api/v1/sql` which is wrong.

**Comment by paveltiunov** [comment]
Hey @ThomasKientz ! Its expected behavior as SQL returned by this endpoint is parameterized. Not all databases support parameterized/prepared statements so those `?` will be replaced by the driver before sending to the database in some cases.

**Comment by igorlukanin** [comment]
Hey @ThomasKientz 👋 Would it make sense, for data scientists, to use the [SQL API](https://cube.dev/blog/expanded-bi-support) and query Cube instead of raw data sources? Please feel free to tune in for the [workshop](https://cube.dev/events/sql-api/) I'm doing next week.

**Comment by paveltiunov** [comment]
@ThomasKientz You need to substitute `?` with params according to SQL rules of specific dialect.

**Comment by ThomasKientz** [comment]
@paveltiunov is there any way to get the final the SQL query via the api ? If not, why not provide such api (any technical reasons I am missing ? ), would you be open to a PR for this ? (should it fix the current one or add a new API ? )
