### ISSUE TITLE
breaking changes in antd 4.0.0

### ISSUE THREAD

**Issue by jhofeditz** [cube-js/cube.js#463]
running `npm start` or `yarn start` after installing dashboard app from cubejs playground fails with error:
```
Failed to compile.
./src/components/QueryBuilder/SelectChartType.js
Attempted import error: 'Icon' is not exported from 'antd'.
```
version: @cubejs-backend/server-core@0.18.2

It appears that in antd v4.0.0, the Icon component api has changed breaking the current dashboard app code:
https://ant.design/docs/react/migration-v4#Icon-upgrade

The playground and query builder are working fine (I think still using v3) but a newly created sample app does not start. Downgrading antd to a 3.x release fixed the problem for me.

**Comment by paveltiunov** [comment]
@jhofeditz Hey Joe! Thanks for heads up! Should be fixed right now.
