### ISSUE TITLE
continueWaitTimeout is ignored still not fixed ? 

### ISSUE THREAD

**Issue by dktjsp** [cube-js/cube.js#470]
**Describe the bug**

continueWaitTimeout on queueOptions is ignored ? (Always 5s)

**To Reproduce**
1. Set queueOptions continueWaitTimeout to 120
2. Check with a long rest request (5s timeout)

**Expected behavior**
Wait 120s max

**Version:**
0.18.3

**Comment by paveltiunov** [comment]
Yep. There's already open issue #225
