### ISSUE TITLE
Table name with aggregated creating an issues

### ISSUE THREAD

**Issue by ranjeetranjan** [cube-js/cube.js#4727]
**Describe the bug**
We use Postgress. When we have aggregated in the table its giving an error. 
**Error**

`You requested hidden member: 'aggregated_conversions_by_minute_aggregated_default_event_day__'. Please make it visible using `shown: true`. Please note primaryKey fields are `shown: false` by default: https://cube.dev/docs/schema/reference/joins#setting-a-primary-key.`

**To Reproduce**
1. Table Name  'aggregated_conversions_by_minut'
2. Schema
`ube(`AggregatedConversionsByMinute`, {
  sql: `SELECT * FROM public.aggregated_conversions_by_minute`,
  
  preAggregations: {
    // Pre-Aggregations definitions go here
    // Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started  
  },
  
  joins: {
    
  },
  
  measures: {
    count: {
      sql: `count`,
      type: `sum`
    }
  },
  
  dimensions: {
    eventType: {
      sql: `event_type`,
      type: `string`
    },
    
    timestamp: {
      sql: `timestamp`,
      // explicitly set this to be shown since it is a PK field
      shown: true,
      type: `time`
    }
  }
});`

5. See an error

`You requested hidden member: 'aggregated_conversions_by_minute_aggregated_default_event_day__'. Please make it visible using `shown: true`. Please note primaryKey fields are `shown: false` by default: https://cube.dev/docs/schema/reference/joins#setting-a-primary-key.`

**How problem solved?:**
When we change table name from aggregated_conversions_by_minute_aggregated_default_event_day to conversions_by_minute_default_event_day.

**Comment by paveltiunov** [comment]
Hey @ranjeetranjan ! You're hitting Postgres column name length limits. Please use https://cube.dev/docs/schema/reference/cube#sql-alias.
