### ISSUE TITLE
`shown: false` does not behave the same for `QueryBuilder` in `prod` and `dev` environment

### ISSUE THREAD

**Issue by b-jan** [cube-js/cube.js#4730]
**Describe the bug**
A measure with `shown: false` cannot be used in a `QueryBuilder` in `prod` environment

**To Reproduce**
1. Create a measure with `shown: false`
2. Use in frontend (I use vue.js) a `QueryBuilder` component and call the matching query dynamically
3. See the following error only using cube in `prod` mode

`TypeError: Cannot read properties of undefined (reading 'split')`

I debugged this error using Chrome debugger.
I found that in Meta.js file in core lib, the `this.meta` does not include the measures with `shown: false` only in cube.js `prod` mode. (I tried with many different measures)

**Expected behavior**
`shown: false` should act like in dev mode

```javascript
cube(`XXX`, {
  sql: `xxx`,
  measures: {
    timeStayAverage: {
      type: `avg`,
      sql: CUBE => `${CUBE.seniority}`,
      shown: false, // here
    },
  },
  dimensions: {
    seniority: {
      sql: `status`,
      type: `string`,
    },
  },
});
```

**Version:**
["@cubejs-backend/server": "^0.30.1"]

**Comment by b-jan** [comment]
I also found that `shown` and `visible` are similar. There is no mention about it in the documentation.

https://cube.dev/docs/schema/reference/measures#shown

**Comment by b-jan** [comment]
Using the same query elsewhere (not in query builder) is working.

**Comment by vasilev-alex** [comment]
@b-jan normally, invisible members are not supposed to be discovered at all. If you need similar behavior (e.g. you want to filter some members on the client) you can try to use the `meta` property
