### ISSUE TITLE
helm charts registry

### ISSUE THREAD

**Issue by kodeine** [cube-js/cube.js#4747]
Hello,

Is there a repository where helm charts are hosted and can be used?

**Comment by ivan-vdovin** [comment]
Hi @kodeine !
Are you looking for this example?
[https://github.com/cube-js/cube.js/tree/master/examples/helm-charts](https://github.com/cube-js/cube.js/tree/master/examples/helm-charts)

**Comment by booyaa** [comment]
I think what @kodeine meant was that there should be an index.yaml see ([docs](https://helm.sh/docs/topics/chart_repository/#create-a-chart-repository)). This could be generated using the [helm repo](https://v3-1-0.helm.sh/docs/helm/helm_repo_index/) command but would require integration into your pipeline.

**Comment by kodeine** [comment]
Thats correct @booyaa
