### ISSUE TITLE
Mongodb array handling in cube js

### ISSUE THREAD

**Issue by DhanushNehru** [cube-js/cube.js#4753]
Using mongosqld we used to generate the schema based on mongodb documents and query using cube js. Cube is able to handle and filter data over strings, numbers etc. But when it comes to handle arrays cube returns the data in form of separate documents

Eg) Consider the below document
 { _id: 1, name:"User1", subjects:["Physics","Maths","English"]

When i generate a schema using mongosqld and query the documents in cubejs I get the following as response

{
_id:1, name:"User1", subjects:"Physics",
_id:1, name:"User1", subjects:"Maths",
_id:1, name:"User1", subjects:"English",
}

It would be great if cube js supports arrays and the data can be filtered and queried based on the arrays. 

As a alternative I use the cube query all 3 documents, run a loop which on implementation of huge datasets creates a lot of issues.

Already aware of the schema type conflicts in mongodb 
https://www.mongodb.com/docs/bi-connector/master/schema/type-conflicts/
It would be great and really helpful if cube can provide an option to group things and return data as expected.

**Comment by ivan-vdovin** [comment]
Hi @DhanushNehru !
The solution here should be to unnest these fields. Have you tried that?

**Comment by DhanushNehru** [comment]
Hi @ivan-vdovin 
Even if we unnest fields, the output of the cube query seems to be a string & we get the similar output as shown above.

Especially when we do a pagination based on array field we don't get the output as expected.

**Comment by paveltiunov** [comment]
@DhanushNehru Please see https://stackoverflow.com/questions/59826986/cube-js-how-to-join-two-tables-created-from-mongodb-arrays on how to work with nested documents.
