### ISSUE TITLE
Docs, Minor: Curl command on the REST-API docs fails

### ISSUE THREAD

**Issue by maatumo** [cube-js/cube.js#4755]
## Docs URL
https://cube.dev/docs/rest-api#api-reference-v-1-load
<img width="590" alt="スクリーンショット 2022-06-13 22 37 18" src="https://user-images.githubusercontent.com/8266590/173366119-bafdb5b5-4f8f-4f36-b3b2-4ba7dd41c818.png">

## Issue description
The POST curl command fails 

```
$ curl \
 -X POST
 -H "Content-Type: application/json" \
 -H "Authorization: EXAMPLE-API-TOKEN" \
 -G \
 --data '{"query": {"measures":["Users.count"]}}' \
 http://localhost:4000/cubejs-api/v1/load

curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
zsh: command not found: -H
```

execution env:
-  macOs 12.3.1
-  curl 7.79.1

## For improvement
Perhaps the command supposed to be 
```
curl \
 -X POST  \
 -H "Content-Type: application/json" \
 -H "Authorization: EXAMPLE-API-TOKEN" \
 --data '{"query": {"measures":["Users.count"]}}' \
 http://localhost:4000/cubejs-api/v1/load
```

**Comment by hassankhan** [comment]
Thanks for reporting the issue @maatumo 👍
