### ISSUE TITLE
FILTER_PARAMS with expression issue

### ISSUE THREAD

**Issue by Koh-Meta** [cube-js/cube.js#4764]
**Describe the bug**
FILTER_PARAMS with expression not working with list of data

**To Reproduce**
1. I have added this into my Cube's sql generation
![image](https://user-images.githubusercontent.com/107404257/174054409-a9a18db3-ee0f-4e15-a6c9-6f4619c4d206.png)
2. In the Cube request payload, I have passed in two BranchId
![image](https://user-images.githubusercontent.com/107404257/174053885-0e77c159-7545-4c4f-a2e9-3f3fd8a26d82.png)
3. The resulted sql query only has one of the BranchId, the second BranchId is missing
![image](https://user-images.githubusercontent.com/107404257/174054494-e0df6ce1-289e-44c1-8773-8e3edae88ea7.png)

**Expected behavior**
To pass list into FILTER_PARAMS

**Version:**
2.2

**Additional context**
Unfortunately, I cannot CAST the field ssh.BranchId, as ssh itself contains millions of data.
Casting ssh.BranchId seems to pull out all the data before casting it, resulting in enormous loading time.

**Comment by ivan-vdovin** [comment]
Hi @Koh-Meta and thank you for a detailed report! 
When you specify several values in the filter it turns into IN operator in the final SQL and it isn’t supported for decimal. As a workaround, this dimension can be cast to string. Could you try that and let us know, please?

**Comment by paveltiunov** [comment]
@Koh-Meta Every filter value is passed to `filter` function as separate params. So you can do something like
```javascript
FILTER_PARAMS.store_profiling.BranchId.filter((...values) => values.map(value => `ssh.BranchId = CAST(${value} AS int)`).join(' AND '))
```
