### ISSUE TITLE
full cube store storage

### ISSUE THREAD

**Issue by aquiles419** [cube-js/cube.js#4794]
**Problem**

Over time, CubeJs takes up the storage space and doesn't clean up older information, so we don't have enough space for storage. Is there any setting for automatic cleaning of pre-aggregations?

used version 0.29

**Comment by ovr** [comment]
@aquiles419 Cube cleans orphaned/unused pre-aggregations at the end of doing pre-aggregations. Probably, somewhere there is an error that blocks the cleanup of it. Do you see any errors? What database do you use for pre-aggregations?

Thanks

**Comment by aquiles419** [comment]
the errors I have are query construction and timeout in the cubestore, I use postgres database and redis in the application!

erro:
{"message":"Error refreshing pre-aggregation","error":"Error:Error during create table ....

**Comment by paveltiunov** [comment]
@aquiles419 It means your deployment is unstable. You'd need to fix these errors first.
