### ISSUE TITLE
Dedicated Refresh Workers Don't Automatically Refresh Pre-Aggregations

### ISSUE THREAD

**Issue by tchell** [cube-js/cube.js#4797]
When setting up a dedicated refresh worker as defined in the documentation [1](https://cube.dev/docs/deployment/overview#refresh-worker), [2](https://cube.dev/docs/deployment/production-checklist#set-up-refresh-worker), [3](https://cube.dev/docs/deployment/platforms/docker#configuration) it seems like all that is needed for the refresh worker to refresh pre-aggregations is to define a cubejs server instance with `CUBEJS_REFRESH_WORKER=true`. However, when trying to set this up recently the refresh worker seemed to only be checking the redis cache and not doing anything about pre-aggregations. I was able to confirm this by:
1. setting the `preAggregationsOptions.externalRefresh = false` which would cause an error when querying saying that no pre-aggregations existed.
2. querying the pre-aggregations via the cube-api and seeing the pre-aggregations get built/refreshed by the regular cubejs server instead of the refresh worker.
3. viewing the cubestore logs to see when the pre-aggregations were built. They were never built or updated when they should have been. Only querying the data via the regular cubejs server would cause the pre-aggregations to build or refresh.

**To Reproduce**
1. Follow the documentation linked above for setting up a deployment with a refresh worker 
4. Define a pre-aggregation that should be refreshed automatically
5. Follow any of 1-3 above to determine if the pre-aggregations are being built by the refresh worker

**Version:**
0.29.50

**Additional context**
I was able to find a solution to get the refresh worker to build and refresh the pre-aggregations. After a lot of trial and error, reading documentation, and reading the source I came across [this slack thread](https://cube-js.slack.com/archives/CC0403RRR/p1639521207177600) describing a very similar problem I was having AND a [solution down below](https://cube-js.slack.com/archives/CC0403RRR/p1641220958003000?thread_ts=1639521207.177600&cid=CC0403RRR)!

Adding the `CUBEJS_SCHEDULED_REFRESH_DEFAULT=true` works to a refresh worker building pre-aggregations. It's not listed anywhere in the documentation but fortunately it still works. It seems like there was a previous bug that was supposed to be fixed that would eliminate the need for setting that flag but for some reason it doesn't seem to be working by default. So I guess my request is that this should either be added (back?) into the documentation OR this should be happening by default and the flag should be unnecessary to get things working.

**Comment by paveltiunov** [comment]
Hey @tchell ! This one has been fixed in the latest versions. `CUBEJS_SCHEDULED_REFRESH_DEFAULT` is always `true` by default.

**Comment by tchell** [comment]
Ahhh ok apologies. Guess I missed it in the changelog. Thanks for responding!
