### ISSUE TITLE
Is there a way to abort/cancel a query execution from client ?

### ISSUE THREAD

**Issue by barrazastark** [cube-js/cube.js#4806]
Is the a way to pass a unique identifier to my queries ?

Is there a way to cancel/abort a query execution ?

I would like to have something like

`cubeApi.load(query)...` and in some moment `cubeApi.cancelQuery(queryId)...`

**Comment by paveltiunov** [comment]
Hey @barrazastark ! There's no way to cancel the query from the client-side. Orphaned queries that aren't waited on by the client will be canceled automatically after `orphanedTimeout` https://cube.dev/docs/config#queue-options.
