### ISSUE TITLE
Support "minute" as a granularity option for pre-aggregations

### ISSUE THREAD

**Issue by tyronedougherty** [cube-js/cube.js#4809]
**Is your feature request related to a problem? Please describe.**
My application is highly real time. Users want to be able to verify that events are coming in very close to when they happen.

Currently, the smallest granularity for pre-aggregations is an `hour` (see docs [here](https://cube.dev/docs/schema/reference/pre-aggregations#parameters-granularity)). This means that users are not able to see these events for `60 minutes` or more, and when they can see them it doesn't do a great job at showing the precise time they happened because they are bucketed by the hour. I would love to use CubeJS, but this component does not seem to suit my use case very well.

**Describe the solution you'd like**
I would like to support a smaller `granularity` of pre-aggregations - somewhere between 1 to 5 minutes would be ideal. That way I can show events happening and communicate when they happened at a much finer granularity.

**Describe alternatives you've considered**
I could perhaps rely on caching mechanisms to help speed up transactions, but I'm not quite sure how or if this would work well for my use case.

**Additional context**
N/A.

Thank you! 😄

**Comment by paveltiunov** [comment]
@tyronedougherty Hey Tyrone! `minute` and seconds are actually supported. We need to fix the docs.

**Comment by tyronedougherty** [comment]
Thanks @paveltiunov that's awesome to hear!

**Comment by hassankhan** [comment]
Thanks for reporting the issue @tyronedougherty 👍
