### ISSUE TITLE
No data available before "buildRangeStart" date value

### ISSUE THREAD

**Issue by angelocavallo** [cube-js/cube.js#4813]
When I query data older than my "buildRangeStart" value, Cube always returns me 0 as a response.

I'm facing this problem in version 0.28+ since I was able to create on-demand pre-aggregations by simply querying older data in version 0.27.x.

My pre-aggregation configuration was the same for all my tests:

`{
			type: `rollup`,
			measureReferences: [...measures],
			dimensionReferences: [...dimensions],
			granularity: `day`,
			timeDimensionReference: date,
			external: true,
			partitionGranularity: `day`,
			refreshKey: {
				every: `1 hour`,
				incremental: true,
				updateWindow: `1 day`
			},
			buildRangeStart: {
				sql: `SELECT DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY)`,
			},
			scheduledRefresh: true
}`

I deploy Cube in a serverless environment (Google Cloud Run) and use the scheduled-refresh endpoint to refresh my pre-aggregations.

version [0.28.x] [0.29.x] [0.30.x]

**Comment by buntarb** [comment]
@paveltiunov, how do you think it is a regression or were there significant changes that could cause this issue?
