### ISSUE TITLE
How to specify conditions used to filter the table on the right side of join?

### ISSUE THREAD

**Issue by towerpark** [cube-js/cube.js#482]
Hi, I have a question about the join feature. For example, I have the following two tables:

customers:
```
 id | name
----+-------+
  1 | A
  2 | B
```
orders:
 ```
user | date
-----+------------+
    1 | 2020-03-05
```
I want to perform the following query on the tables:
```
SELECT name, COUNT(date)
FROM customers LEFT JOIN orders on id = user and date > X
GROUP BY name;
```
X is a parameter specified at run time by frontend.

I did some research but still cannot figure out how to implement it with schema and query of Cube.js.
I tried filters of Query but found out it was placed in WHERE clause, so for example, if X = '2020-03-01' I got
```
 name  | COUNT(date)
-------+------------
 A     | 1
```
, which is different from the result of the SQL above.

I also tried ``FILTER_PARAMS`` to filter ``orders`` in advance by ``sql`` of ``cube`` in schema:
```
cube(`Orders`, {
    sql: `SELECT * FROM orders WHERE ${FILTER_PARAMS.Orders.date.filter('date')}`,
    ...
    dimensions: {
        date: {
            sql: `date`,
            type: `time`,
        }
    }
});
```
, and then use query like (``joins`` is defined in schema of ``customers``):
```
      query: {
        measures: ["Orders.count"],
        dimensions: ["Customers.name"],
        filters: [
          {
            member: "Orders.date",
            operator: "afterDate",
            values: ['2020-03-01'],
          },
        ],
      },
```
But the log of backend showed it issued a SQL with the filter in both LEFT JOIN and WHERE clauses:
```
SELECT
  "customers".name "customers__name", count("orders".date) "orders__date__count"
FROM
  public.customers AS "customers"
LEFT JOIN (SELECT * FROM public.orders WHERE date > $1::timestamptz) AS "orders"
  ON "orders".user = "customers".id  WHERE ("orders".date > $2::timestamptz) GROUP BY 1 LIMIT 10000
```
I don't know if I used it wrong or it is by design.

Could you please give me some advice?
Thank you for the great job!

**Comment by paveltiunov** [comment]
@towerpark Great question! This case falls into `OR IS NULL` filter category which will be supported by this implementation: #259 .

**Comment by towerpark** [comment]
@paveltiunov Thank you for the quick response. You are right, ``OR`` with an ``IS NULL`` filter can solve my problem :+1:. I will try it out when the feature is done.

**Comment by apuntovanini** [comment]
@towerpark @paveltiunov can you share an example of this?
I cracked my head on documentation (https://cube.dev/docs/direction-of-joins) to have "Customers with no orders" working example but cannot find a way to do so
