### ISSUE TITLE
Is it possible to store pre-aggregations and remove the source data after some period of time?

### ISSUE THREAD

**Issue by tyronedougherty** [cube-js/cube.js#4825]
**Problem**

In my use case, I have billions of logs of event data. After some period of time, this raw data builds in costs and becomes less valuable to store indefinitely. Currently, we delete these logs after 12 months have passed.

I want to be able to aggregate this raw data into metrics and store these aggregated metrics indefinitely, even after the raw data has been deleted.

Is it possible to ensure that the aggregated metrics remain, even after the raw data has been deleted? If so, where is this data stored and how can I ensure it is backed up, etc?

Thanks so much!

**Comment by ivan-vdovin** [comment]
Hi @tyronedougherty !
I would like to know more about your tech stack and your current setup so I can be more specific.

**Comment by tyronedougherty** [comment]
Hi @ivan-vdovin!

At a high level our tech stack is:

* The raw event data exists in AWS S3
* We have both [transition actions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html) and [lifecycle actions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html) enabled on the S3 buckets to:
  * Make it cheaper to store data over time
  * Delete raw data that isn't used over time (older than 12 months)
* We were thinking of using AWS Athena to provide a querying interface for Cube

However we would be willing to spin up other technologies to support this use case. For example if this requires an SQL db to be created to store the aggregated metrics then that's not an issue 😄 

Hope that helps and keen to hear your thoughts on what is possible!

**Comment by paveltiunov** [comment]
Hey @tyronedougherty ! You can build such a system using incremental pre-aggregations https://cube.dev/docs/schema/reference/pre-aggregations#incremental. Data beyond `updateWindow` would never update and even if it's dropped from the data source it'll live within Cube Store. Please see https://cube.dev/docs/caching/running-in-production on how to set up its storage. However not having data for replay won't allow you to change cube schema so it isn't quite recommended to go this path.

**Comment by tyronedougherty** [comment]
Thanks for your response @paveltiunov 😄 

That makes sense. Do most Cube users keep their raw records forever? What is best practice?

**Comment by paveltiunov** [comment]
@tyronedougherty For event-based systems you'd usually end up with hot and cold storage. For cold S3 storage, you can use something like https://aws.amazon.com/s3/storage-classes/glacier/. You'll use it only in case of schema changes. Or you can just end up with a retention data policy so you never allow to query beyond your data retention period. It can be configured using https://cube.dev/docs/schema/reference/pre-aggregations#build-range-start-and-build-range-end.

**Comment by tyronedougherty** [comment]
Thanks @paveltiunov your insights are greatly appreciated 😄 

Have a great day!
