### ISSUE TITLE
How to forcefully refetch the data  without changing the query  in queryrenderer

### ISSUE THREAD

**Issue by rasheedk** [cube-js/cube.js#483]
Cube js` <QueryRenderer /> `component data not updated when component re renders even I have given  `renewQuery: true` in query. 

How can i refetch data again (Force refresh) from server without changing the query in Query renderer?

**Comment by paveltiunov** [comment]
@rasheedk Hey Rasheed! Could you please share schema of a cube you're trying to refresh? And what version of Cube.js do you use?

**Comment by rasheedk** [comment]
@paveltiunov 
I am using Cube version 0.17.0

`
cube(`OpportunityByCategory`, {
  sql: `SELECT * FROM pricing_opportunity_by_category`,
  title:` `,
  description: `This chart shows  test data`,
   refreshKey: {
    every: `10 second`
  },
  joins: {
    
  },
  
  measures: {
    measure1: {
      type: `max`,
      title:`Measure1`,
      sql:`repair`
    },
   measure2: {
      type: `max`,
      title:`measure2`,
      sql:`maintenance`
    }
  },
  
  dimensions: {
     date: {
      sql: `createdDate`,
      type: `time`
    }
  }
});

`

- I use a query in react component <QueryRenderer /> using setQuery and when i change query timeDimension in a button click , chart data is updated.
- I use this QueryRenderer inside a card component & is there any way to forceRefresh if i change data in database . 
- Data seems to be updated only if i change queryState.
I need to refresh the chart.

**Comment by paveltiunov** [comment]
@rasheedk Could you please update to the latest version and see if it changes something for you?

**Comment by ifokeev** [comment]
@paveltiunov having this issue too. Scheduled refresh doesn't work as expected. Getting Cache issues too often. `renewQuery` doesn't update the query in runtime.

**Comment by paveltiunov** [comment]
Should be fixed in the latest versions. Please feel free to open a new issue if it still persists.
