### ISSUE TITLE
Using where clause on a date field

### ISSUE THREAD

**Issue by ar-ms** [cube-js/cube.js#4853]
**Problem**

Hey folks 👋 ! Is there a way of querying a table using SQL with a where clause, date >= '2022-07-05' for example ?

I connected metabase to cube.js using the postgres connector, cube is plugged into BigQuery.

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `SELECT * FROM metrics.myTable`
    )}`,
  
  joins: {
    
  },
  
  measures: {

    count: {
      type: `count`,
      drillMembers: [uuid, date]
    },
    
    date: {
      sql: `date`,
      type: `time`
    },
  },

  dataSource: `default`
});

```

**Metabase query**

```sql
SELECT
    count
FROM
    Cube
where
    date > '2022-07-05'
```

And got the following error message:
```
Error during processing PostgreSQL message: Internal(None): Execution error: Internal(None): Error: No matching signature for operator > for argument types: DATE, TIMESTAMP. Supported signature: ANY > ANY at [4:112] None None
```

The [docs](https://cube.dev/docs/backend/sql#querying-fundamentals-filtering
) says the filtering works with >=, <=, > and <, seems like it does not work with dates.

Is there something similar to https://cube.dev/docs/query-format#filters-operators-in-date-range, in SQL query ?

Thanks ✌🏽 !

**Comment by paveltiunov** [comment]
@ar-ms We're working on Metabase support right now. More info here #3906 .

**Comment by paveltiunov** [comment]
@ar-ms Database support has been shipped.
