### ISSUE TITLE
Dashboard App iframe does not load when it is behind a load balancer

### ISSUE THREAD

**Issue by sergio-ferreira-jscrambler** [cube-js/cube.js#4869]
**Describe the bug**
We have a self-hosted cube.js playground deployed internally, in which we've created a Dashboard App. However, after starting the dashboard, a blank page appears.

![image](https://user-images.githubusercontent.com/97523204/177761178-64afa0bb-1b32-4673-a703-97f9d0770877.png)

When accessing the URL of the dashboard directly, it loads correctly.

After some digging, I've found out that the dashboard is trying to load an iframe inside the playground through HTTP, when the dashboard is currently served over HTTPS
![image](https://user-images.githubusercontent.com/97523204/177761411-8d5db708-4673-45b5-9ef3-0e990fb210c7.png)

This may be due to having a load balancer behind Cube.JS. In our infrastructure, which is described in the following image, we serve both the dashboard and playground through HTTPs through a load balancer which does the SSL offloading

![image](https://user-images.githubusercontent.com/97523204/177762851-3c89144b-fd65-4b52-ad32-77bdbf52805d.png)

**To Reproduce**
1. Serve playground over HTTPS through a load balancer with SSL offloading
2. Go to "Dashboard App" section
3. Create a dashboard
4. Start the dashboard
5. Check that the dashboard does not load

**Expected behavior**
The dashboard should load correctly

**Comment by paveltiunov** [comment]
@sergio-ferreira-jscrambler Cube playground isn't designed to be served in production behind the load balancer. The open-source playground is just for local development purposes. Please consider building a separate frontend app that embeds all of that features and is hosted separately. If you need this for developer collaboration please consider using Cube Cloud. For internal use you can also consider https://cube.dev/docs/backend/sql#sql-api with other BI tool that provides dashboarding features.
