### ISSUE TITLE
Typing errors in @cubejs-client/core: "^0.30.29"

### ISSUE THREAD

**Issue by tanvi-cota** [cube-js/cube.js#4892]
Upgraded to latest version of @cubejs-client/core": "^0.30.29"
On building it, it gives following typing error :

`node_modules/@cubejs-client/core/index.d.ts:838:21 - error TS1110: Type expected.

838       ? Dimension | `${Dimension & string}.${Granularity & string}`
                        ~~~

node_modules/@cubejs-client/core/index.d.ts:839:7 - error TS1128: Declaration or statement expected.

839       : never;`

**Comment by paveltiunov** [comment]
cc @reify-thomas-smith

**Comment by nymo** [comment]
Can confirm same error...breaks my production deployment.

**Comment by vasilev-alex** [comment]
Thanks @reify-thomas-smith 

@tanvi-cota I don't think we're going to support the older TypeScript versions, so the best option for you would be either to upgrade to a newer TS version or keep using the compatible `@cubejs-client/core` of **v0.29**
