### ISSUE TITLE
Can't connect to Dashboard App on localhost:3000 when using Docker image

### ISSUE THREAD

**Issue by alisymebv** [cube-js/cube.js#4895]
**Describe the bug**
Following the guide to get started with Docker, I'm getting as far as _starting_ the Dashboard App (I've tried a few from template gallery and the same problem) when I see that localhost:3000 isn't available and shows nothing, despite an app being created there.

Logs
```
Warning. There is no cube.js file. Continue with environment variables
🔥 Cube Store (0.30.33) is assigned to 3030 port.
🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000
🚀 Cube.js server (0.30.33) is listening on 4000
2022-07-12 07:39:26,701 INFO  [cubestored] <pid:18> Cube Store version 0.30.30
2022-07-12 07:39:26,706 INFO  [cubestore::http::status] <pid:18> Serving status probes at 0.0.0.0:3031
2022-07-12 07:39:26,709 INFO  [cubestore::metastore] <pid:18> Using existing metastore in /cube/conf/.cubestore/data/metastore
2022-07-12 07:39:26,805 INFO  [cubestore::http] <pid:18> Http Server is listening on 0.0.0.0:3030
2022-07-12 07:39:26,805 INFO  [cubestore::mysql] <pid:18> MySQL port open on 0.0.0.0:13306

> dashboard-app@0.1.0 start /cube/conf/dashboard-app
> react-scripts start "--port" "3000" "--host" "0.0.0.0"

Starting the development server...

Compiled successfully!

You can now view dashboard-app in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://172.17.0.2:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
```

**To Reproduce**
1. Follow the steps on Getting Started with Docker
2. Click to create any dashboard app from /template-gallery
3. Try to view the created app on /dashboard-app or localhost:3000

**Expected behavior**
That the created dashboard be available on localhost:3000

**Screenshots**
![image](https://user-images.githubusercontent.com/101576662/178421282-159fda2a-b464-47d5-a795-d5d5e478cb1a.png)

**Version:**
Docker Image Latest

**Comment by Martelloti** [comment]
Also worth noting that some previous versions such as v0.30.0 and v0.27.0 have the same error, while versions older than that return different errors before getting in to that page.

**Comment by buntarb** [comment]
@igorlukanin, could you please assist with this?

**Comment by paveltiunov** [comment]
@alisymebv Have you tried to expose 3000 port for your docker container?

**Comment by alisymebv** [comment]
My update is that I added -p 4000:4000 to the docker run command detailed here and it worked

https://cube.dev/docs/getting-started/docker 

(Note the documentation didn't initially include -p 4000:4000 so thanks for the update there)

**Comment by Martelloti** [comment]
In my case (using docker-compose), adding the 3000 now led me to another error type:

![image](https://user-images.githubusercontent.com/30840991/179819770-bd768b19-f15f-4f2a-bfe8-706bfbd3b8bd.png)

(almost all of the dashboard options lead to this)

**Comment by paveltiunov** [comment]
@Martelloti Please create another issue for that if you're still experiencing it.
