### ISSUE TITLE
Stop DB Query

### ISSUE THREAD

**Issue by zeokz** [cube-js/cube.js#4902]
As documented [here](https://cube.dev/docs/rest-api#prerequisites-continue-wait), when a CubeJS Query that takes a bit long for it to complete, the `CubeJS Client` & `CubeJS Server` make use the `ContinueWait` long polling mechanisms to keep the request alive. I would like to know whether there is some kind of a `timeout` configuration that makes it possible to configure the CubeJS server so that if `ContinueWait` polling request is not received after an `X` amount of seconds, the DB Query is terminated. Because based on my observations it looks like that even though the `CubeJS Client` stops polling for the results, the DB Query keeps on going in the background.

**Comment by ivan-vdovin** [comment]
Hi @zeokz !
Hace you tried to update CUBEJS_DB_QUERY_TIMEOUT to check if it helps here?
https://cube.dev/docs/reference/environment-variables#cube-store
