### ISSUE TITLE
Measure character(s) is being trimmed | measure name changes

### ISSUE THREAD

**Issue by PedramMarandi** [cube-js/cube.js#4931]
**Describe the bug**
I have a measure name called `job_order_free_form_total_sub_total` and my Cube name is `FreeFormItemSalesReport`.
When I query for `FreeFormItemSalesReport.job_order_free_form_total_sub_total` I receive the below error 

```json
{
    "error": "You requested hidden member: 'free_form_item_sales_report__job_order_free_form_total_sub_tota'. Please make it visible using `shown: true`. Please note primaryKey fields are `shown: false` by default: https://cube.dev/docs/schema/reference/joins#setting-a-primary-key."
}
```

However, if I change the measure name to `job_order_free_form_total_sub_tota` and query for `FreeFormItemSalesReport.job_order_free_form_total_sub_tota` I get the results with no error.

It seems like there is a length limit or something which is not mentioned in the documentation. 

**Expected behavior**
I expect the measure to have the exact same name, or even if any letters are being trimmed, I expect it to work with another measure that represents the modified measure name. in this case I expect the CubeJS to execute the code if I create another measure called `job_order_free_form_total_sub_tota`

**Minimally reproducible Cube Schema**
```javascript
cube(`FreeFormItemSalesReport`, {
   title: "Issued Free Form Item Report",
   description: "Sale Report Aggregate",
   sql: `
       select sale_store_id,
              job_order_free_form_sub_total as job_order_free_form_total_sub_total,
              'item_refund' AS row_type
     
       from ${InvoiceFreeFormItemRefund.sql()} as v
       where v.company_id = ${getCompanyId(securityContext)}
       UNION ALL
       select sale_store_id,

              job_order_free_form_sub_total as job_order_free_form_total_sub_total,
              'item_sale' AS row_type
       
       from ${IssuedInvoiceFreeFormItemSale.sql()} as s
       where s.company_id = ${getCompanyId(securityContext)}
   `,
   dimensions: {
      row_type: {
         sql: `row_type`,
         type: `string`,
      }
   },
   measures: {
      job_order_free_form_total_sub_total: {
         sql: 'job_order_free_form_total_sub_total',
         type: `sum`,
         format: 'currency'
      }
   }
})
```

**Version:**
[e.g. 0.30.35]

**Comment by ivan-vdovin** [comment]
Hi @PedramMarandi !
It can be source DB limitation. Could you share your DB type?

**Comment by PedramMarandi** [comment]
> Hi @PedramMarandi !
> 
> It can be source DB limitation. Could you share your DB type?

I'm using Postgres version 12

**Comment by ivan-vdovin** [comment]
It should be Postgres limitation. Could you try using shorter names?
`dentifier length	63 bytes	can be increased by recompiling PostgreSQL`
https://www.google.com/search?q=postgres+max+length+of+table+column&oq=postgres+max+[…]69i57j33i160l2j33i22i29i30.12089j0j7&sourceid=chrome&ie=UTF-8

**Comment by paveltiunov** [comment]
@PedramMarandi You can also use https://cube.dev/docs/schema/reference/cube#sql-alias
