### ISSUE TITLE
Does Cube have a way to test syntax for new schemas before deploying them? 

### ISSUE THREAD

**Issue by Martelloti** [cube-js/cube.js#4946]
**Problem**

I'd like to know if is there a possibility to use something related to Linter so that we can test a schema (alongside a sample payload) before deploying it. Our use case would be disposing our infrastructure to an outside client that would deploy its own schemas, but we wanted to make sure they would work before deploying them.
```

**Comment by ivan-vdovin** [comment]
Hi @Martelloti !
Schema validation won't let you adding nonexisting fields and will fail during parsing. I have to notice that using linter with dynamic schemas with async requests will be hard to implement. Could you add share more details on your expectations here?

**Comment by paveltiunov** [comment]
@Martelloti Simplest way to do it is to run schema compilation. Cube Cloud does it on every change you make during your development process to show you errors if there're any.
