### ISSUE TITLE
Can't connect to Superset using SQL API (docker)

### ISSUE THREAD

**Issue by seredayav** [cube-js/cube.js#4950]
Hi,
I'm trying to connect Superset to Cube js using new SQL API (Supetset and Cube js are in docker containers)

Cube js docker-compose:
```
version: '2.2'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 5432:5432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf
```

.env file:
```
CUBEJS_DB_HOST=(local ip)
CUBEJS_DB_PORT=3306
CUBEJS_DB_NAME=testbase
CUBEJS_DB_USER=dba
CUBEJS_DB_PASS=dbaPass
CUBEJS_DB_TYPE=mysql
CUBEJS_API_SECRET=.....
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_DEV_MODE=true
CUBEJS_PG_SQL_PORT=5432
CUBEJS_SQL_USER=myusername
CUBEJS_SQL_PASSWORD=password
CUBEJS_EXTERNAL_DEFAULT=true
```

and schema:
```
cube(`cubeName`, {
  sql: `SELECT * FROM testbase.cubeName`,
  .
  .
  .
```

and trying to connect to superset.
![image](https://user-images.githubusercontent.com/73606224/179977556-dd644a4b-94ec-464f-a565-436e94f84d1e.png)

Can't understand, what database name I need to paste. 

When I'm trying to connect it, Cube js docker logging:
```
Cube SQL Error: undefined 
{
   "appName": "NULL",
   "protocol": "postgres",
   "apiType": "sql"
}
Error during processing PostgreSQL connection: IO Error: unexpected end of file
```

trying to add dataset, Superset errors
![image](https://user-images.githubusercontent.com/73606224/179978748-5b18f1f3-24f9-4b0e-bf3e-14fd80f68ac1.png)

and Cube js logging
```
Cube SQL Error: undefined 
 --
"SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod), (SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid) FROM pg_catalog.pg_attrdef AS d WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef) AS DEFAULT, a.attnotnull, a.attrelid AS table_oid, pgd.description AS comment, a.attgenerated AS generated, (SELECT json_build_object('always', a.attidentity = 'a', 'start', s.seqstart, 'increment', s.seqincrement, 'minvalue', s.seqmin, 'maxvalue', s.seqmax, 'cache', s.seqcache, 'cycle', s.seqcycle) FROM pg_catalog.pg_sequence AS s JOIN pg_catalog.pg_class AS c ON s.seqrelid = c.\"oid\" WHERE c.relkind = 'S' AND a.attidentity <> '' AND s.seqrelid = CAST(pg_catalog.pg_get_serial_sequence(CAST(CAST(a.attrelid AS REGCLASS) AS TEXT), a.attname) AS REGCLASS)) AS identity_options FROM pg_catalog.pg_attribute AS a LEFT JOIN pg_catalog.pg_description AS pgd ON (pgd.objoid = a.attrelid AND pgd.objsubid = a.attnum) WHERE a.attrelid = 18000 AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum" 
```

Every manual I've found are for Cube Cloud BI tool and didn't help me

**Comment by ovr** [comment]
Hello @seredayav,

What Superset version do you use?

Most probably, this error was caused by the new Superset version (they started to use tables/functions that we still don't support). I recommend downgrading Superset's version before we will support unsupported features from this query.

Thanks

**Comment by seredayav** [comment]
Yes, I've used last version. Will try previous versions. Thank you for your answer!

**Comment by ovr** [comment]
@seredayav 

What version did you use? I tried Superset 2.0, but I could not find that query. Did you use the open source version or Preset.io?

Thanks
