### ISSUE TITLE
How to cancel / abort pending cubejs api request in react client ?

### ISSUE THREAD

**Issue by shubhamgoswamiofficial** [cube-js/cube.js#4993]
I am working with Cube.Js in react. When i am changing the the route (Navigating to another page), I need to cancel the running (Pending) request. How can we achieve this. Do Cube.js has any provision to cancel pending API requests?

Thanks in advance.

**Comment by ivan-vdovin** [comment]
Hi @shubhamgoswamiofficial 
There is no easy way to fo that right now. Could you elaborate on your use case here please?

**Comment by paveltiunov** [comment]
@shubhamgoswamiofficial Please see #4806
