### ISSUE TITLE
New Schema files not picked up by Cube

### ISSUE THREAD

**Issue by chargartenrga** [cube-js/cube.js#5003]
**Describe the bug**
We are currently deployed to cube in ECS, and, using EFS to mount cube schemas to our containers. At times, we have added cube schemas, and, not been able to retrieve them via the cubejs-api/v1/meta endpoint.

**To Reproduce**
1. Deploying to Docker, mount a volume at /cube/conf/schema.
2. Run the Docker stack.
3. Add a schema to the volume.
4. Query the cubejs-api/v1/meta endpoint, or, just try to write a query against new schema.

**Expected behavior**
We expected to see the cube schema added to /cube/conf/schema in the meta endpoint, and, to be able to query it with the load endpoint.

**Version:**
0.29.17

**Comment by ivan-vdovin** [comment]
Hey @chargartenrga 
Have you tried to rerun cube after that?

**Comment by paveltiunov** [comment]
@chargartenrga You need to define `schemaVersion`. Please see https://cube.dev/docs/schema/advanced/dynamic-schema-creation#usage-with-schema-version.

**Comment by chargartenrga** [comment]
Thanks for the response, @paveltiunov! I see those docs there, but, not understanding really what that `schemaVersion` function is doing.

**Comment by chargartenrga** [comment]
Nevermind, this has resolved our issue.
