### ISSUE TITLE
Typescript compile fails when importing @cubejs-client/core v0.29.54

### ISSUE THREAD

**Issue by juandiegocastrillon** [cube-js/cube.js#5065]
**Describe the bug**
I have a react typescript web application. I'm getting the following typescript compile tsc error when importing any version beyond v0.29.54 of @cubejs-client/core likely due to [this change](https://github.com/cube-js/cube.js/pull/4446). To fix, I had to downgrade to an earlier version. 
tsc version 4.6.2
```
node_modules/@cubejs-client/core/index.d.ts:818:61 - error TS2344: Type 'Rest' does not satisfy the constraint 'readonly DeeplyReadonly<Query>[]'.
  Type 'unknown[]' is not assignable to type 'readonly DeeplyReadonly<Query>[]'.
    Type 'unknown' is not assignable to type 'DeeplyReadonly<Query>'.

818       ? SingleQueryRecordType<First> | QueryArrayRecordType<Rest>
                                                                ~~~~


Found 1 error in node_modules/@cubejs-client/core/index.d.ts:818
```
**To Reproduce**
1. Import @cubejs-client/core v0.29.54 into a typescript project
2. Run `tsc` 

**Expected behavior**
- Typescript compile `tsc` should succeed

**Screenshots**

**Version:**
v0.29.54

**Additional context**

**Comment by reify-thomas-smith** [comment]
Looks like probably some versions of tsc are able to infer that the constraint is met but others aren't. PR #5067 should fix it. I'll check for any other similar constraints that might fail for similar reasons.

**Comment by reify-thomas-smith** [comment]
N.B. #4369 might help catch these sorts of bugs.

**Comment by paveltiunov** [comment]
@reify-thomas-smith Thanks for fixing that!
