### ISSUE TITLE
TypeError: Cannot read property 'testConnection' of undefined at CubejsServerCore.getDriver

### ISSUE THREAD

**Issue by trantuancnt** [cube-js/cube.js#5072]
**Describe the bug**

Error while loading DB schema
TypeError: Cannot read property 'testConnection' of undefined at CubejsServerCore.getDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:850:20) at processTicksAndRejections (internal/process/task_queues.js:95:5) at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:108:22 at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:78:9

**To Reproduce**
File Cube.js
```
const MongoBIDriver = require('@cubejs-backend/mongobi-driver');
const ClickHouseDriver = require('@cubejs-backend/clickhouse-driver');

module.exports = {
    driverFactory: ({ dataSource } = {}) => {
        if (dataSource === 'test_mg') {
          return new MongoBIDriver({
            database: 'test',
            host: '*.*.*.*',
            user: null,
            password: null,
            port: `3309`
          });
        }
       if (dataSource === 'test_ch') {
          return new ClickHouseDriver({
            database: 'test',
            host: '*.*.*.*',
            user: 'default',
            password: 'dC9dn8',
            port: '8123',
          });
        }
    },
  };
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43692764/183332991-f988912e-b880-4820-bf84-6808389c7f2c.png)

**Version:**
[e.g. 0.29.34]

**Comment by ivan-vdovin** [comment]
Hi @trantuancnt 
Could you upgrade Cube version to latest to check if it helps. Also I would like to check if it's not the case when dataSource = default. could you add else for the second condition to make sure?

**Comment by trantuancnt** [comment]
Thank @ivan-vdovin, After upgrade Cube version 0.30.44 and add config datasource = default to file config cube.js then Cube worked.
