### ISSUE TITLE
@cubejs-client/vue3: [Vue warn]: Property "setQuery" was accessed during render but is not defined on instance

### ISSUE THREAD

**Issue by josx** [cube-js/cube.js#5084]
**Describe the bug**
Every time you use query-builder you get a annoying warning in browser console.

**To Reproduce**
Using component <query-builder>

**Expected behavior**
Not show any warning on browser console

**Version:**
0.29.23

**Additional context**

Also is happening in Last version. 

There is not any documentation about **setQuery** on [builderSlot](https://cube.dev/docs/@cubejs-client-vue#builder-slot) so I think we need to remove it from source code. I can do a PR on this if you think it is right.

**Comment by ivan-vdovin** [comment]
@vasilev-alex WDYT of this one?
