### ISSUE TITLE
MergIng the critical and high vulnerability dependencies

### ISSUE THREAD

**Issue by ojhaujjwal** [cube-js/cube.js#5096]
Thank you for this awesome tool. 

**Problem**
Just doing a quick yarn audit in the repo, I got this:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/4995501/184285330-2e0fb1c9-3824-4db6-92d3-688edeaf3fbe.png">

I am slightly concerned by the number of high and critical issues. I am not complaining since this is an open source tool and this is freaking awesome. I am only opening the issue there because I am trying to use this and I have just been asked questions regarding the security aspect of the repo.

Is there something we can do about update security vulnerabilities or something where you guys need help to maintain?

**Comment by paveltiunov** [comment]
We’re periodically reviewing audit reviews for the open source images and merging the most critical fixes. For some of the dependencies where we consider risk low or surface of attack really small, we can decide not to merge those fixes. On the other hand, if you're looking to resolve these security issues from a compliance standpoint, please consider contacting our sales team https://cube.dev/contact. We have a slightly different policy for our enterprise images.

**Comment by ojhaujjwal** [comment]
Thanks for the reply @paveltiunov. Closing the issue for now.
