### ISSUE TITLE
How can I get all schema relationship with Cube.js ?

### ISSUE THREAD

**Issue by EzraTsai** [cube-js/cube.js#5102]
Do we have any method to get all defined schema relationship at front-end? For example, if I defined two schemas and added a joins for schema. Can I have an api or any way to show these two schema relationship at front-end?

```
cube(`Production`, {
  sql: `select * from production
  title: `Production`,
  joins: {
    DeviceInfo: {
      relationship: `belongsTo`,
      sql: `${Customer}.uuid = ${Production}.uuid`,
    },
  ...
  ...
  },

cube(`Customer`, {
  sql: `select * from customer
  title: `Customer`,
  ...
  ...
  },

```

My point is, if we have a lot of schemas, how can user know which two or three or more schema can be used in a query. I see it will show an error like, "Error: Can't find join path to join 'ExampleA', 'ExampleB'", after querying, but it will need user's try and error. So, is any way to inform front-end and user which schema can be queried together? My potential solution is to get all schema relationship with Cube.js firstly. However, I wondering if we have this feature.

**Comment by ivan-vdovin** [comment]
Hi @EzraTsai ,
You must be looking for meta endpoint:
https://cube.dev/docs/rest-api#v-1-meta

`connectedComponent` should help identify joined cubes as it has the same value for two cubes, then there is at least one join path between them.
