### ISSUE TITLE
Package cannot install on node > v14 with npm but works for yarn

### ISSUE THREAD

**Issue by josx** [cube-js/cube.js#5117]
**Describe the bug**
With node 16.x you get errors on install.

**To Reproduce**
1. `git clone repo`
2. `npm install`
3.

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @cubejs-client/core@0.30.46
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.21.0" from @cubejs-client/core@0.30.46
npm ERR!   packages/cubejs-client-core
npm ERR!     @cubejs-client/core@0.30.46
npm ERR!     node_modules/@cubejs-client/core
npm ERR!       workspace packages/cubejs-client-core from the root project
npm ERR!       7 more (@cubejs-backend/testing, @cubejs-client/ngx, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^4.19.1 || ^5.3.0" from eslint-config-airbnb-base@13.2.0
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^13.1.0" from @cubejs-client/core@0.30.46
npm ERR!   packages/cubejs-client-core
npm ERR!     @cubejs-client/core@0.30.46
npm ERR!     node_modules/@cubejs-client/core
npm ERR!       workspace packages/cubejs-client-core from the root project
npm ERR!       7 more (@cubejs-backend/testing, @cubejs-client/ngx, ...)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/josx/.npm/eresolve-report.txt for a full report.
```

**Expected behavior**
Clear installation without errors.

**Version:**
master branch

**Fix nvm use 14*

**Comment by ovr** [comment]
Hello!

Hmm, interesting to see that `yarn` allows to install it. I approve, that right now; it's not possible to use `npm`.

I recommend you use `yarn` for now before we will align our dependencies to the correct versions.

Thanks

**Comment by josx** [comment]
You can use `npm`  with `node 14.x` or  `pnpm`

**Comment by paveltiunov** [comment]
By default, `yarn` should be used to build Cube. Please feel free to provide PR with a fix if you find out how to fix it for `npm`.

**Comment by josx** [comment]
To avoid the errors using `npm` you can run `npm install --legacy-peer-deps` on `node > 14`

So Maybe it is usefull to add it in [CONTRBUTION](https://github.com/cube-js/cube.js/blob/master/CONTRIBUTING.md)

@paveltiunov If you agree i can do it.
