### ISSUE TITLE
Add support for filters to accept operator 'in'

### ISSUE THREAD

**Issue by igorshmukler** [cube-js/cube.js#5141]
**Is your feature request related to a problem? Please describe.**

Currently, Cube.JS supports several operators, starting with `equals`. It is possible to build `IN` using `OR` as:
```
{
  or: [
    {
      "member": "Events.event_id",
      "operator": "equals",
      "values": [
        "24"
      ]
    },
    {
      "member": "Events.event_id",
      "operator": "equals",
      "values": [
        "28"
      ]
    }]
}
```

**Describe the solution you'd like**
I would Cube.JS would also support:
```
    {
      "member": "Events.event_id",
      "operator": "in",
      "values": [
        "24", "28"
      ]
    }
```
It could/should be mapped to SQL `IN` and/or `ANY` as `column_name IN (ValA, ValB, ValC)`, in our case `"Events.event_id" IN ("24", "28")`

**Describe alternatives you've considered**
It is possible to use `or` and get away without `IN`. I understand this.

**Comment by paveltiunov** [comment]
@igorshmukler It's supported by `equals` operator. Please see https://cube.dev/docs/query-format#equals.
