### ISSUE TITLE
Time dimension, without timezone

### ISSUE THREAD

**Issue by mematthew** [cube-js/cube.js#5179]
**Problem**
I have a time dimension as per below and in the DB Postgres, the data type is a timestamp. Somehow the query sent from CubeJS is creating the query and appending ' timestamptz'. This is causing partitions and indexes to be ignored. Is there a way to stop CubeJS from appending ' datatype conversion' phrase ?

**Related Cube.js schema**
```javascript
 timeslot: {
      sql: `timeslot`,
      type: `time`
    }
})
```

**Related Cube.js generated SQL**

```sql
SELECT * FROM ...
 WHERE ("stats".timeslot >= '2022-08-15 00:00:00':: timestamptz
    AND "stats".timeslot <= '2022-08-15 23:59:59' :: timestamptz)
 
```

**Comment by paveltiunov** [comment]
@mematthew You can use https://cube.dev/docs/schema/reference/cube#filter-params to hint Postgres optimizer here.

**Comment by mematthew** [comment]
yes that did the trick
