### ISSUE TITLE
How to achieve Conditional formatting like in Power BI ?

### ISSUE THREAD

**Issue by rajeshkannandev** [cube-js/cube.js#520]
Conditional Formatting use case - 
if a student has first-year marks and second-year marks,

here I want to compare two-year marks and send the result in percentage with negative or positive marks

eg
 1) first-year mark 50 and a second-year mark is 100 here the average is 75% which is greater than first-year marks and so I want to highlight this as a positive one.

**Comment by paveltiunov** [comment]
Hey @rajeshkannandev! It can be done on client side. https://cube.dev/docs/@cubejs-client-core#result-set-table-pivot row values should be checked to decide if particular row should be colored.

**Comment by rajeshkannandev** [comment]
Again Thanks @paveltiunov your answers so helpful. 🙏
