### ISSUE TITLE
How to turn off cube schema caching ? 

### ISSUE THREAD

**Issue by rajeshkannandev** [cube-js/cube.js#523]
I've added an async module to each cube schema. It fetches new measures and dimensions from another API with on the fly.

however, it only shows the new measures and dimensions for the first time when the cube server gets restarted.

It's not reflecting new measures and dimensions or calling the third party API every time without restarting the server. 

do we have the option to it off ?

Thanks in advance 🙏.

**Comment by paveltiunov** [comment]
Hey @rajeshkannandev ! Please see note here: https://cube.dev/docs/schema-execution-environment#async-module

**Comment by rajeshkannandev** [comment]
Thanks @paveltiunov. async module i've already added. i forgot to update schema version. 
It's working super fine.
