### ISSUE TITLE
Allow user to provide list of columns for SELECT statement

### ISSUE THREAD

**Issue by lauraalkhoury-youitv** [cube-js/cube.js#524]
**Is your feature request related to a problem? Please describe.**
Yes, it would be more efficient (in terms of data scanned) to either:
a) allow the user to pass in a list of columns to be selected, OR
b) only select the dimensions and measures from the json query

This way, instead of doing an inner `SELECT *` in the `sql` field of the schema, then an outer `SELECT column_a, column_b, ...` from the measures/dimensions in the json query, we would simply have one `SELECT column_a, column_b, ...`.

**Describe the solution you'd like**
Ideally, at query rewrite time Cube.js would:
a) look at the columns field (new proposed field) of the query json, eg. `columns: [ 'column_a', 'column_b' ]` (this approach is a bit redundant because everything that should be included in the SELECT comes from `measures` and `dimensions` anyways)
b) simply look at the dimensions/measures field of the query json, eg.`dimensions: [ 'column_a', 'column_b' ]` and flatten the query to a single SELECT as described above.

**Describe alternatives you've considered**
I can create schemas where I avoid having SELECT * in the inner select, eg:
```
const columns = [
  'timestamp',
  'appname',
  'region',
  'stagename'
];

cube('Metrics', {
  sql: `
    SELECT
      ${columns.join(', ')}
    FROM metrics.metricsparquet
    WHERE (
      ${FILTER_PARAMS.Metrics.timestamp.filter('from_iso8601_timestamp(timestamp)')}
    )
  `,
  extends: BaseMetrics
});
```
But then this still creates duplication in the SQL as you end up with identical inner and outer SELECTs (assuming you have those same dimensions in your json query).

**Additional context**

**Comment by paveltiunov** [comment]
@lauraalkhoury-youitv Hey Laura! Thanks for posting this one! We expect it to be solved when simple query rewrites will be implemented: `WHERE` statements from cube sql will be merged to outer cube query so there will be no inner query at all.

Meanwhile as discussed pre-aggregations is the best solution to approach this stuff.

**Comment by paveltiunov** [comment]
@lauraalkhoury-youitv Hey Laura! This one should be working right now if you provide `rewriteQueries: true` flag:
```
cube('Metrics', {
  sql: `
    SELECT
      *
    FROM metrics.metricsparquet
    WHERE (
      ${FILTER_PARAMS.Metrics.timestamp.filter('from_iso8601_timestamp(timestamp)')}
    )
  `,
  rewriteQueries: true,
  extends: BaseMetrics
});
```
