### ISSUE TITLE
How to query ratio by a dimension in cube?

### ISSUE THREAD

**Issue by tonyabracadabra** [cube-js/cube.js#5242]
I have a column called `region` and I want to query the percentage for each region, the result would look like 

```
{'Texas': 50%, 'California': 30%, 'Penn': 20%}
```

I can definitely define a new cube just for getting the total amount of data, so the ratio = count(*) / the subquery for querying the total number of rows, but is there a better way for doing this without involving sub queries or new cube?

**Comment by dzvon** [comment]
@ivan-vdovin

**Comment by ivan-vdovin** [comment]
Hi @tonyabracadabra 
The approach you've mentioned should work. Another options is defining measures for all of the regions and adding separate measures to calculate percentage. Something like that:
  measures: {
    count: {
      type: `count`,
    },
    countTexas: {
      type: `count`,
      filters: [{ sql: `${CUBE}. region = 'Texas'` }],
    },
    percentageTexas: {
      type: `number`,
      sql: `100.0 * ${countTexas} / ${count}`,
    }
  },
