### ISSUE TITLE
SQL API Encryption

### ISSUE THREAD

**Issue by justusfowl** [cube-js/cube.js#5263]
Dear all, 

first of all let me thank you for providing such a great product, I really like cube-js. 

I have a question on the SQL API: 

I am currently trying to identify options how to encrypt the connection to the SQL API and wonder if people can share best practices on how to offer this API with TLS encryption. 

I am thinking to offload the TLS of the TCP connection at a proxy (nginx) and forward the connection in an unencrypted manner. 

Thanks a lot - grateful for any hints :) 

best

**Comment by paveltiunov** [comment]
@justusfowl Hey Justus! Connection encryption isn't part of an open source. If you're looking for encryption implementation for SQL API, you should consider using Cube Cloud.

**Comment by justusfowl** [comment]
Ok thanks - I really would, but due to data privacy constraints of clients this is not an option sadly. Do you plan to add this feature for the SQL API anytime in the future?

**Comment by NikKomarov** [comment]
@justusfowl you can take a look at pgbouncer.

**Comment by justusfowl** [comment]
Thanks @NikKomarov - I appreciate it!
