### ISSUE TITLE
connection pool size configuration with env variable for postges-driver

### ISSUE THREAD

**Issue by chaselmann** [cube-js/cube.js#527]
**Is your feature request related to a problem? Please describe.**
The default size of the connection pool for the postgres-driver is hard-coded to max. 8 connections at the moment. This number was higher than the available connections for cubejs, which lead to random slow query execution times.

**Describe the solution you'd like**
Provide an environment variable to make the pool size configurable.

**Comment by paveltiunov** [comment]
Fixed in #528
