### ISSUE TITLE
How can I dynamically generate schema that contains variables that refers to other measures / dimensions?

### ISSUE THREAD

**Issue by tonyabracadabra** [cube-js/cube.js#5303]
Hi team, how can I dynamically generate schema that contains variables that refers to other measures / dimensions? For example, I have a measure defined with `"sql": "${count} / ${total} * 100"`, which refers to `count` and `total` variables respectively, but obviously the variables (`${ ... }`) wrapped within `""` could not be further parsed into meaningful sql since they are dynamically generated and will be recognized as string later in the processing.

**Comment by paveltiunov** [comment]
@tonyabracadabra You can do that as follows:
```
// ...

const { aMember, bMember } = relation;
const member = {
  sql: (CUBE) => `${CUBE[aMember]} / ${CUBE[bMember]}`,
  type: `number`
};

cube('GeneratedCube', {
  // ...
  measures: {
    generatedMember: member
  }
})
```
