### ISSUE TITLE
Use assume role - AWS_ROLE_ARN - instead of access/secret key 

### ISSUE THREAD

**Issue by Hankier** [cube-js/cube.js#5330]
**Problem**

Is it possible to use s3 in cubestore on eks with assume role instead of access/secret?  
I see that implementation [of remoteS3](https://github.com/cube-js/cube.js/blob/master/rust/cubestore/cubestore/src/remotefs/s3.rs#L45) is checking for CUBESTORE_ prefixed values. There is nothing like CUBESTORE_AWS_ROLE_ARN or sth that would allow to use role instead of keys. 

Tried to run those helm-chart on EKS with [AWS_ROLE_ARN](https://github.com/durch/rust-s3/blob/44f21c4d589f88b9d65fe2796cf48caea978b9eb/aws-creds/src/credentials.rs#L191) from rust-s3 but it failed. 

Is this possible to use ARN and I did sth wrong. Or yet its not implemented in cubestore?

**Comment by paveltiunov** [comment]
There's PR for this already #4411 however, it's stale.
