### ISSUE TITLE
is it possible to use raw sql query in measures or dimensions  sql key ? like in the below image

### ISSUE THREAD

**Issue by rajeshkannandev** [cube-js/cube.js#542]
![image](https://user-images.githubusercontent.com/62346173/77723337-2fb1e300-7016-11ea-882a-381d4e4b741b.png)

**Comment by paveltiunov** [comment]
Hey @rajeshkannandev ! Custom SQL can either go in cube https://cube.dev/docs/cube#parameters-sql or in case of measure it should be aggregate expression https://cube.dev/docs/types-and-formats#measures-types-number

**Comment by rajeshkannandev** [comment]
yes i've learned and implemented in my project. 

Thanks. Cube JS is very much helpful in my project.
