### ISSUE TITLE
with snowflake: after 4 hours of inactivity, trying to perform any operation with snowflake, throws cannot use terminated connection error and nothing works

### ISSUE THREAD

**Issue by grinfeld** [cube-js/cube.js#543]
**Describe the bug**
Using snowflake as DB_TYPE, cubejs ver. 0.18.17, after 4 hours of inactivity, trying to perform any operation with snowflake, throws cannot use terminated connection error and nothing works.
 Error:
```
........
Error: Unable to perform operation using terminated connection.
Dropping Cache:
..................
```
seems, using most recent snowflake-nodejs will help to resolve the issue

**Comment by paveltiunov** [comment]
@grinfeld Hey Mikhail! Thanks for posting this one! Yep. I believe we need to use keep alive option.

**Comment by grinfeld** [comment]
getting error: "using fail-open to connect. Driver is connecting to an HTTPS endpoint without OCSP based Certificated Revocation checking as it could not obtain a valid OCSP Response to use from the CA OCSP responder."

https://www.snowflake.com/blog/latest-changes-to-how-snowflake-handles-ocsp/

**Comment by paveltiunov** [comment]
@grinfeld I believe we have version after May 10, 2019 but still makes sense to update.

**Comment by mdnelles** [comment]
I wrote a workaround that can be used as a cron job or a direct API link this has been working for us and is adequate until a solution is found.

http://locahost:3000/cube_reboot <swap localhost with anydomain>

`const kill = require("kill-port");
const { exec } = require("child_process");
const express = require("express");
const app = express();
const port = 3000;

const reboot = (res) => {
   (async () => {
      try {
         const { stdout } = await exec("npm run dev");
         console.log("Cube server rebooted successfully\n");
         res.send("Cube server rebooted successfully\n");
      } catch (err) {
         console.log(err);
         res.send("server rebooted failed\n");
      }
   })();
};
app.get("/cube_reboot", (req, res) => {
   kill(4000, "tcp").then(reboot(res)).catch(console.log);
});

app.listen(port, () => {
   console.log(`resetCubeServer.js http://localhost:${port}`);
   console.log("\n");
});
`
