### ISSUE TITLE
arabic table names don't work

### ISSUE THREAD

**Issue by yzn-h** [cube-js/cube.js#5440]
**Describe the bug**
I'm using supabas, I have tables with arabic names like "حصص الاتقان", When I try to build a build a query i get this error
![Screenshot from 2022-10-07 11-22-35](https://user-images.githubusercontent.com/63852512/194507702-93016d9e-a35f-4f50-ba1a-72366e3e9ebe.png)

**To Reproduce**
I don't know if it the problem with PostgreSQL alone
1. make PostgreSQL db
2. make a table with the name "اهلا كيف الحال"
3. try to query them

**Expected behavior**
to work like if there names were English 

**Screenshots**
![Screenshot from 2022-10-07 11-22-35](https://user-images.githubusercontent.com/63852512/194507702-93016d9e-a35f-4f50-ba1a-72366e3e9ebe.png)
![Screenshot from 2022-10-07 11-26-48](https://user-images.githubusercontent.com/63852512/194508652-504589e8-193e-41df-a211-ab09aae8b174.png)

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

**Version:**
[e.g. 0.4.5]

**Additional context**
I'm self hosting

**Comment by paveltiunov** [comment]
Let's discuss it here #5174
