### ISSUE TITLE
Inconsistent error formats returned from cube cloud

### ISSUE THREAD

**Issue by Josh-a-e** [cube-js/cube.js#5460]
**Describe the bug**
Sometimes errors have an "error" property, sometimes they have a "message" property.

**Expected behavior**

A consistent attribute to denote the details of an error.

**Screenshots**

<img width="394" alt="Screenshot 2022-10-12 at 21 46 40" src="https://user-images.githubusercontent.com/2893877/195446860-49ef18e9-19f0-4e04-8e93-b4bc99e37798.png">

<img width="465" alt="image" src="https://user-images.githubusercontent.com/2893877/195447025-0c6f459b-cf67-4dea-b7dd-1ef7bc5a47f8.png">

**Version:**
0.30.66

**Context**

I'm polling cube cloud to determine if my deployments have taken effect.

**Comment by paveltiunov** [comment]
@Josh-a-e Hey Joshua! Could you please share which API you're calling and with what parameters?

**Comment by Josh-a-e** [comment]
Hey - sure, I'm just hitting the regular query endpoint using `cubeClient.load({ ... })` to poll cube cloud to discover whether or not my deployment has been completed yet.

```ts
const token = jwt.sign({ STATUS_CHECK: 'OK' }, jwtSecretKey, {
  expiresIn: '2s',
});
const cubeClient = cubejs(token, {
  apiUrl: url,
});

// ...

const serviceQuery = await cubeClient.load({
  dimensions: ['Service.key', 'Service.value'],
  order: { 'Service.key': 'asc' },
});
```

I have this wrapped in a catch / retry loop, in which there is

```ts
const jwtTokenError =
  // If we update the JWT secret key the signed JWT will initially be invalid until it takes effect
  hasStatusAndResponse(error) &&
  error.status === 403 &&
  error.response?.error === 'Invalid token'; // <- "error" and not "message" like the other two below

const serviceTimeoutError =
  hasStatusAndResponse(error) &&
  error.status === 504 &&
  error.response?.message === 'Gateway Timeout';

const serviceUnavailableError =
  hasStatusAndResponse(error) &&
  error.status === 503 &&
  error.response?.message === 'Service Unavailable';
  ```

**Comment by paveltiunov** [comment]
@Josh-a-e Yep. This one was fixed.
