### ISSUE TITLE
The Security Token included in the Request is Invalid

### ISSUE THREAD

**Issue by dhavalaprashanth** [cube-js/cube.js#5462]
**Problem**

I am trying to connect athena with ```Assume Role``` credentials . Assume role credentials are generating well and good but the problem is when i pass the secret key , accesskey, sessiontoken  from assume role credentials to athena I am getting an error saying 
"The Security Token included in the Request is Invalid". I have the required permissions for assume role but i cant understand why i am getting this error :(

**Comment by paveltiunov** [comment]
@dhavalaprashanth Could you please reproduce this one in Cube Cloud so we can take a look?
