### ISSUE TITLE
Databricks connector issue

### ISSUE THREAD

**Issue by pm-hwks** [cube-js/cube.js#5470]
**Describe the bug**
Databricks connector is not showing up in the developer playground.

**Troubleshooting level 1 :** 
* provided the databricks connector configuration via environment variables in the docker run command. 
`docker run -p 4000:4000 -p 3000:3000 \
  -v ${PWD}:/cube/conf \
  -e CUBEJS_DEV_MODE=true \
  -e CUBEJS_DB_TYPE=databricks-jdbc \
  -e CUBEJS_DB_NAME=yyyyyy \
  -e CUBEJS_DB_DATABRICKS_URL="jdbc:spark://xxxxxxxxxx:443/default;transportMode=http;ssl=1;httpPath=sql/protocolv1/o/0/0120-214905-rehab0000234;AuthMech=3;UID=token" \
  -e CUBEJS_DB_DATABRICKS_TOKEN=xxxxxxxxxx \
  -e CUBEJS_DB_DATABRICKS_ACCEPT_POLICY=true \
  cubejs/cube:v0.31.3`

* ran into error java package missing
`Error while loading DB schema
Error: Cannot find module 'java' Require stack: - /cube/node_modules/jdbc/lib/jinst.js - /cube/node_modules/jdbc/lib/drivermanager.js`

**Troubleshooting level 2 :** 
* created another docker image extending cubejs docker image
* Installed jdk
* Installed java package from npm
`FROM cubejs/cube:v0.31.3
RUN apt-get update 
RUN apt-get install default-jdk
RUN npm install java
`
* built a new docker image and used the image in the docker run command
* Ran into a new error - no package.json
`Error while loading DB schema
Error: ENOENT: no such file or directory, open 'package.json' at DatabricksDriver.testConnection (/cube/node_modules/@cubejs-backend/jdbc-driver/src/JDBCDriver.ts:163:13)`

**Expected behavior**
Ability to connect to databricks via jdbc and ability to build cubes

**Screenshots**

**Version:**
0.31.3

**Additional context**
With some guidance, i can troubleshoot and fix the error. After that i can contribute back to the project

**Comment by paveltiunov** [comment]
@pm-hwks You should use jdk tag instead: https://hub.docker.com/r/cubejs/cube/tags.
