### ISSUE TITLE
Documentation of MongoDB is invalid

### ISSUE THREAD

**Issue by Inoir** [cube-js/cube.js#5515]
**Describe the bug**
Currently it doesnt mention SSL is required for MongoBI to run. Instead it says all SSL is optional.
As a lot people already mentioned in this post: https://github.com/cube-js/cube.js/issues/222 the only way to use MongoBI is with SSL enabled. Should be way more clear how you do this. i.E like this: https://stackoverflow.com/questions/58868085/cube-js-error-ssl-is-required-when-using-cleartext-authentication-using-mongod/58869914#58869914

**To Reproduce**
Just try use MongoBI without SSL with Cube. Doesnt work!

**Expected behavior**
Behaviour is fine, documentation is wrong

**Additional context**
https://cube.dev/docs/config/databases/mongodb

**Comment by hassankhan** [comment]
Thanks for reporting this @Inoir, the docs have now been updated 👍
