### ISSUE TITLE
Abort / cancel previous cubejs requests made

### ISSUE THREAD

**Issue by b-jan** [cube-js/cube.js#5524]
**THE PROBLEM**

On a page change, or a time filter change, we need to **abort / cancel previous cubejs requests made**.
Currently, there is no way to do it, and as a result you have to wait for every cubejs queries you made before resolving the new ones.

**THE SOLUTION**

As [you can do it with axios or fetch](https://stackoverflow.com/questions/50516438/cancel-previous-request-using-axios-with-vue-js), we can use an abort controller with a signal.

```
import cubejs from '@cubejs-client/core';

// declare the abort controller here
const controller = new AbortController();
const signal = controller.signal;

const cubejsApi = cubejs(
  'CUBEJS-API-TOKEN',
  { apiUrl: 'http://localhost:4000/cubejs-api/v1' }
);

// our classic request with a little improvement
const resultSet = await cubejsApi.load({
 measures: ['Stories.count'],
 timeDimensions: [{
   dimension: 'Stories.time',
   dateRange: ['2015-01-01', '2015-12-31'],
   granularity: 'month'
  }],
  signal // we add the abort signal here! ⚠️
});

// to cancel the request we just call:
controller.abort()
```

**MORE INFO**
MDN documentation is [here](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

**Comment by paveltiunov** [comment]
@b-jan You can use https://cube.dev/docs/@cubejs-client-core#unsubscribe-obj-unsubscribe to `unsubscribe()` from listening upcoming results and stop long polling loop. It doesn't cancel query in db though. Please see #4806.

**Comment by b-jan** [comment]
Thank you @paveltiunov 
But because it does not cancel query in db, and because the concurrency of queries is limited, Ii takes a lot of time to get the results...

**Comment by paveltiunov** [comment]
@b-jan In practice, query cancellation isn't that reliable as a mechanism for controlling your app query throughput. Please consider using pre-aggregations if you're looking for a reliable way of isolating pressure on your source database from your downstream users.
