### ISSUE TITLE
Serverless deployment on AWS

### ISSUE THREAD

**Issue by johhattingh** [cube-js/cube.js#5540]
Hi, 

From the documentation, https://cube.dev/docs/deployment/platforms/serverless/aws, it seems like the serverless deployment method is being deprecated. Is there any new plans for a deployment of Cube.js going forward?

Thanks in advance.
Johan

**Comment by paveltiunov** [comment]
@johhattingh If you're looking for a serverless hosting experience, you can try out https://cube.dev/cloud. This is the only fully supported serverless hosting option at the moment. There are no plans to support other serverless deployment options using the efforts of the Core team in the future.
