### ISSUE TITLE
Not Shown Fields are not accessable in Production Mode

### ISSUE THREAD

**Issue by bykof** [cube-js/cube.js#5542]
**Problem**

Hey Folks, 
if I have a cube like this:

```
cube(`Test`, {
  sql: `...`,
  dimensions: {
    id: {
      sql: `id`,
      type: `string`,
      primaryKey: true,
    },

    test: {
      sql: `test`,
      type: `string`,
      shown: false,
    },
  dataSource: `default`,
})
```

I can access the field `test` it in dev mode. 
But if I try to access this field in prod mode, I get the error: 

```
You requested hidden member: 'test__test'. Please make it visible using `shown: true`. Please note primaryKey fields are `shown: false` by default: https://cube.dev/docs/schema/reference/joins#setting-a-primary-key.
```

I thought `shown: true` exists to hide fields in the meta response, but still allow them to be queried.
There is also no hint on the page: https://cube.dev/docs/configuration/overview#development-mode

So my question is: Is the behaviour correct? I would expect, that I am still allowed to query this field, even if it's not "shown".

**Comment by paveltiunov** [comment]
@bykof This is correct behavior. Fields aren't allowed to be queried through API when hidden.

**Comment by bykof** [comment]
But this is somehow not consistent behaviour. If I test my code with env variable `CUBEJS_DEV_MODE=true` the fields are exposed and the code works, if I switch this env they are hidden.

I would suggest rather make all fields accessable but trigger hide/show in the /meta endpoint or make all fields not accessable which are hidden in DEV_MODE=true and false.

**Comment by paveltiunov** [comment]
@bykof Thanks for the feedback! We'll stick with the second option.

**Comment by bykof** [comment]
I hoped you would stick with the first option :D but anyway thank you for managing that! I appreciate your work!

**Comment by bykof** [comment]
@paveltiunov I would discuss this topic once more. 
So let's imagine if someone creates a dimension: 
```
 status: {
      sql: `status`,
      type: `string`,
    },
```

then the intention of the developer is that status is shown and accessable. 
If someone uses `shown: false`, then I would expect, that status is still accessable but not shown in the meta fields because it's "hidden".
What the current implementation does is rather a `accessable: false` behaviour.

Is it possible to change the current behaviour? I would implement it if it's necessary and you do not have the time to do it.

Best Regards

**Comment by igorlukanin** [comment]
Hey @bykof, thanks for elaborating. Could you please explain the use case?

> If someone uses shown: false, then I would expect, that status is still accessable but not shown in the meta fields because it's "hidden".

It sounds a bit like "security through obscurity". You know that there's such dimension but decide to not expose it through the `/meta` API call. Why?

**Comment by igorlukanin** [comment]
However, I agree that `shown` is poor naming, we could improve that.

**Comment by bykof** [comment]
> It sounds a bit like "security through obscurity". You know that there's such dimension but decide to not expose it through the /meta API call. Why?

The usecase would be to render a dropdown list of dimensions and measures (like you do in the cube developer dashboard). But still have the possibility to query a specific dimension by it's name, because it is just "hidden".

Imagine you have a customer, orders, order-items, categories and products. You let the user build the query by him/herself. For example you have order.status but you don't want to show the status field in the dimensions dropdown (doesn't matter if this example makes sense, I just trying to convert my specific case into an easy example). 
Then you let the frontend "hardcoded" query the orders.status field because your frontend always shows the current order status. 

So in the end you don't want to show the dimensions dropdown but still want to have it accessable.

I hope the example was good enough ^^

**Comment by igorlukanin** [comment]
@bykof It makes sense; thanks for explaining. There's a feature that is designed specifically for this use case: the [`meta` option](https://cube.dev/docs/schema/reference/dimensions#parameters-meta) in measures and dimensions. With that option, you're able to provide arbitrary information to the front-end side, e.g., rendering hints. What do you think?

**Comment by paveltiunov** [comment]
@bykof Do you want to be hidden in the playground or query builder? Are you embedding a playground somewhere in production?

**Comment by bykof** [comment]
@igorlukanin I think this would fix my problem for now. 
Nevertheless I think that the naming could be changed from "shown" to "private" or "accessable"

@paveltiunov no I don't embed playground into production. I built such a query builder by myself.

**Comment by chaos87** [comment]
I have the same problem as @bykof 

I am using `shown: false` to hide some dimensions from dropdowns on UI, and I use queryRewrite to parse the dimension + granularity chosen to then modify the dimensions array and possibly include the hidden dimensions

The code modification on v0.31.10 is breaking this behavior on my end

I would like the shown to behave like @bykof just said aka not in the response of `/v1/meta` but still valid for `/v1/load `

**Comment by Obi-Dann** [comment]
According to the docs the `shown` parameter controls the visibility of the property, not whether the property is accessible via the API. If the intention is to make the property inaccessible, a better more descriptive name for the parameter should be used, using `shown` for this is misleading.  
![image](https://user-images.githubusercontent.com/12251341/200211721-fe77d5d7-b291-45b5-bc65-ebba0f6f76cc.png)
