### ISSUE TITLE
can cube.js server be used with hapi or koa?

### ISSUE THREAD

**Issue by selbest** [cube-js/cube.js#555]
```
"Cube.js server is an Express application itself and it can be served as part of an existing Express application."
```

I saw this in document.

Can cube.js server be used with hapi or koa?  Do we have any plan to support koa or hapi

**Comment by paveltiunov** [comment]
Hey @selbest ! Great question. I think you can checkout this one https://github.com/vkurchatkin/koa-connect. Cube.js is connect middleware in fact.

**Comment by paveltiunov** [comment]
@selbest Was it helpful?
