### ISSUE TITLE
Exception from a finished function: AbortError: Ready check failed

### ISSUE THREAD

**Issue by shietpas** [cube-js/cube.js#556]
**Describe the bug**
I am using Google serverless implementation with utilizes the "api" and "process" functions with PubSub handoff between them and Redis Memorystore cache and Cloud SQL (postgres) backend.  The "api" function appears to complete successfully, then 4 minutes later an AbortError appears under the same execution id in the logs with:
> Exception from a finished function: AbortError: Ready check failed: Connection forcefully ended and command aborted. It might have been processed.
It appears as if a resource connection is being lost behind-the-scenes and resulting in an eventual error; possibly related to Redis cache pooling.

@paveltiunov noted that this may be related to the redis pool.  A possible workaround may be to set the environment variable CUBEJS_REDIS_POOL_MAX=0; although a complete resolution is still desired.

**To Reproduce**
1. Normal cube.js query execution in "production" mode using Redis Memorystore cache in GCP
2. Stackdriver logs capture AbortError events which occur 

**Expected behavior**
Exceptions should not be thrown if functions are completing successfully.

**Screenshots**
The screenshot below shows a single execution ID (call) with AbortError entries lagging the function execution end time by 1.5 minutes:
![image](https://user-images.githubusercontent.com/22350866/78037605-6434e000-7331-11ea-8141-ae4f95c9de34.png)

This screenshot shows frequency of error in a DEV environment with relatively low traffic:
![image](https://user-images.githubusercontent.com/22350866/78037735-8af31680-7331-11ea-8868-9a4b9d0597d0.png)

**Version:**
    "@cubejs-backend/bigquery-driver": "^0.18.13",
    "@cubejs-backend/postgres-driver": "^0.18.14",
    "@cubejs-backend/server": "^0.18.14",
    "@cubejs-backend/serverless": "^0.18.14",
    "@cubejs-backend/serverless-google": "^0.18.14",
    "serverless-express": "^2.0.11",

**Additional context**
Platform: Google
Cloud Function runtime: nodejs10

**Comment by paveltiunov** [comment]
@shietpas Hey Scott! Could you please share your options passed to `Handlers` constructor?

**Comment by shietpas** [comment]
@paveltiunov is this sufficient:
const GoogleHandlers = require("@cubejs-backend/serverless-google");
// appId 1 = a (BigQuery)
// appId 2 = b (Cloud SQL Postgres)

//https://cube.dev/docs/@cubejs-backend-server-core#queue-options
const queueOptions = {
  //Timeout and Interval options are in seconds
  concurrency: 100, //default = 2
  continueWaitTimeout: 60, // long polling interval, default = 5s
  executionTimeout: 120, //default = 600s (10 minutes)
  orphanedTimeout: 120, //default = 120s
  heartBeatInterval: 30 //default=30s, Worker heartbeat interval. If 4*heartBeatInterval time passes without reporting, the query gets cancelled.
};

const orchestratorOptions = {
  queryCacheOptions: {
    refreshKeyRenewalThreshold: 3600, //Time in seconds to cache the result of refreshKey check; default = 120 (2 minutes)
    backgroundRenew: true, //immediately return values from cache if available without refreshKey check to renew in foreground. Default value before 0.15.0 was true
    queueOptions
  },
  preAggregationsOptions: { queueOptions }
};

const aRepo = new FileRepository(`schema/a`);
const bRepo = new FileRepository(`schema/b`);

const postgresDriver = new PostgresDriver({
  host: process.env.CUBEJS_A_HOST,
  database: process.env.CUBEJS_A_DB,
  port: process.env.CUBEJS_A_PORT,
  user: process.env.CUBEJS_A_USER,
  password: process.env.CUBEJS_A_PASS
});

const bigQueryDriver = new BigQueryDriver({
  projectId: process.env.CUBEJS_DB_BQ_PROJECT_ID,
  keyFilename: process.env.CUBEJS_DB_BQ_KEY_FILE
});

module.exports = new GoogleHandlers({

  contextToAppId: ({ authInfo: { appId } }) => `CUBEJS_APP_${appId}`,

  dbType: ({ authInfo: { appId } }) => {
    if (appId == 2) return "postgres";

    return "bigquery";
  },

  driverFactory: ({ authInfo: { appId } }) => {
    if (appId == 2) return postgresDriver;

    return bigQueryDriver;
  },

  repositoryFactory: ({ authInfo: { appId } }) => {
    if (appId == 2) return aRepo;

    return bRepo;
  },

  orchestratorOptions
});

**Comment by paveltiunov** [comment]
@shietpas Gotcha. It's due to `continueWaitTimeout: 60`. I believe it exceed default timeout for GCP.

**Comment by shietpas** [comment]
I did extend the cloud function timeout to Max of 540 (9 minutes) to accommodate, so the function should not timeout. Prior to changing I did notice errors for long running operations such as building pre-agg table. I also do background refresh to avoid that particular delay.

Sent from my Verizon, Samsung Galaxy smartphone
________________________________

**Comment by paveltiunov** [comment]
@shietpas I believe function timeout and time allowed to wrap up all background jobs are different parameters. Not sure if GCP has an option for later.
