### ISSUE TITLE
Queries are getting timing out when high load.

### ISSUE THREAD

**Issue by rickyDeveloper** [cube-js/cube.js#5564]
Hi,

We are currently using open source version of cube to serve data for our dashboards.
We have started 6 instances of cube and deployed it in-house on our GCP VMs.  These VMs are fronted by a Load Balancer which has a 30 seconds query execution time out. 

Cube server connects to Snowflake data warehouse to extract data. 
The query execution time on Snowflake is max 1-3 seconds.

When a lot of concurrent users (~2000 users) access our dashboards than we see queries time out.  

Documentation of cube suggests that max 2 queries can be executed concurrently by a single instance. 

Hence, I want to know whether timing out the queries is because requests are getting queued on cube server and eventually timed out. 

If the above is true then what are options to build a scalable solution.  Moving to cube cloud?  Kubernetes based deployment?

Rgds,
-Vikas

**Comment by paveltiunov** [comment]
@rickyDeveloper What are your concurrency settings? What Cube queue size do you see in logs? Could you please also share Cube API instance CPU usage?

**Comment by shlok97** [comment]
Hi @paveltiunov, 
Replying on the behalf of Vikas. 
We are currently using the default concurrency settings and we have not changed them from our end. Hence it's 2 currently by default. 
We have a set of 12 cube containers running in parallel which have load balanced amongst them. The Cube API's cpu usage reached around 180% max on the docker containers. 
Also, I would need your help in finding the queue length, we're currently not tracking that at our end.

**Comment by shlok97** [comment]
Also, the number of queries we were receiving was around 200 per minute - or 6-7 QPS.

**Comment by shlok97** [comment]
Thanks @paveltiunov for the quick response, what's the maximum value of CUBEJS_CONCURRENCY that you would recommend for us to set? Is there any side effects of setting a high number  (let's say 10) for that? We have queuing and horizontal scaling on snowflake so we can handle a higher load there.

**Comment by rickyDeveloper** [comment]
Thnx @paveltiunov for the details it helps. 

One question -- what is the default `queue size` ?  We are not able to find it in docs.  

Given that we don't see any logs for cube server, it would be helpful if you can share how to enable logging on cube server that we deployed on our VMs.

**Comment by paveltiunov** [comment]
@shlok97 @rickyDeveloper Upper limit for `CUBEJS_CONCURRENCY` is basically what your data warehouse can handle. Query queue size is limited by your Redis throughput and instances memory. There's no setting for it, but I won't recommend going over 100 queued queries at any time to avoid degraded performance. Please see https://cube.dev/docs/reference/environment-variables#general for logging levels.

**Comment by paveltiunov** [comment]
@shlok97 Nope. It'll be just 8 if all of those are within the same cluster.

**Comment by paveltiunov** [comment]
@shlok97 Are they using the same Redis, or you're benchmarking containers in dev mode?
