### ISSUE TITLE
Joins in SQL query FROM clause are out of order and produce DB level error

### ISSUE THREAD

**Issue by HrisIord** [cube-js/cube.js#5580]
**Describe the bug**
After updating CubeJS to version 0.31.12 from version 0.30.4 running a query produces an SQL error. When examining the SQL produced, the `from` clause joins are being emitted in the wrong order and one of the joins is referencing a table that doesn't exist in the join path yet.

**To Reproduce**
The query:

```json
{
  "dimensions": [
    "Task.itemId",
    "Task.verificationStatus",
    "Project.name"
  ],
}
```

Produces the following SQL:

```sql
SELECT
  "library_task".item_id "task__item_id",
  "task_verification_status".label "task__verification_status",
  "project".name "project__name"
FROM
  table1 AS "project"
  LEFT JOIN (query for table2) AS "task" ON "project".id = "task".project_id
  LEFT JOIN dev_pre_aggregations.library_task_main AS "library_task" ON "task".standard_id = "library_task".id 
  LEFT JOIN table3 AS "task_verification_status" ON "latest_task_verification".verification_status_id = "task_verification_status".id
  LEFT JOIN (query for table3) AS "latest_task_verification" ON "task".id = "latest_task_verification".task_id
GROUP BY 1, 2, 3
ORDER BY 1 ASC
LIMIT 10000
```

This produces the following error on the server: `missing FROM-clause entry for table "latest_task_verification"`.

**Expected behavior**
I would expect the two joins to the two different verification cubes to be reversed as follows:

```sql
SELECT
  "library_task".item_id "task__item_id",
  "task_verification_status".label "task__verification_status",
  "project".name "project__name"
FROM
  table1 AS "project"
  LEFT JOIN (query for table2) AS "task" ON "project".id = "task".project_id
  LEFT JOIN dev_pre_aggregations.library_task_main AS "library_task" ON "task".standard_id = "library_task".id 
  LEFT JOIN (query for table3) AS "latest_task_verification" ON "task".id = "latest_task_verification".task_id
  LEFT JOIN table3 AS "task_verification_status" ON "latest_task_verification".verification_status_id = "task_verification_status".id
GROUP BY 1, 2, 3
ORDER BY 1 ASC
LIMIT 10000
```

**Screenshots**
No screenshots applicable.

**Minimally reproducible Cube Schema**

```javascript
cube(`Project`, {
  sql: `SELECT * FROM table1`,

  joins: {
    Task: {
      relationship: `hasMany`,
      sql: `${CUBE}.id = ${Task.projectId}`,
    },
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    name: {
      sql: `name`,
      type: `string`,
    },
  },
});


cube(`Task`, {
  sql: `query for table2`,

  joins: {
    LibraryTask: {
      relationship: `belongsTo`,
      sql: `${CUBE}.standard_id = ${LibraryTask.id}`,
    },
    LatestTaskVerification: {
      relationship: `hasOne`,
      sql: `${CUBE}.id = ${LatestTaskVerification.taskId}`,
    },
  },

  dimensions: {
    primaryKeyId: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    itemId: {
      sql: `${CUBE.LibraryTask.itemID}`,
      type: `string`,
    },
    verificationStatus: {
      sql: `${CUBE.LatestTaskVerification.label}`,
      type: `string`,
    },
  },
});

cube(`LibraryTask`, {
  sql: `select * from table3`, // pre-agged

  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    itemID: {
      sql: `item_id`,
      type: `string`,
    },
  }
});

cube("LatestTaskVerification", {
  sql: `query selecting from table4`,
  
  joins: {
    TaskVerificationStatus: {
      relationship: `belongsTo`,
      sql: `${CUBE}.verification_status_id = ${TaskVerificationStatus.id}`,
    },
  },
  
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    label: {
      sql: `${CUBE.TaskVerificationStatus.label}`,
      type: `string`,
      shown: false,
    },
    taskId: {
      sql: `task_id`,
      type: `number`,
      shown: false,
    },
  },
});

cube("TaskVerificationStatus", {
  sql: `SELECT * FROM table4`,
  
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    label: {
      sql: `label`,
      type: `number`,
      shown: false,
    },
  },
});
```

**Version:**
[0.31.12]

**Additional context**
Interestingly enough the `Project.name` dimension is nessecary to reproduce the bug, if I remove it from the query the SQL straightens itself out. I'm also somewhat unsure of how to use some of the new syntax. It's changed the semantics of implicit references. For example if I remove `CUBE` from the `sql` of `Task.itemID` and query for just that dimension I get the full list of library task item ids instead of the subset of task item ids I'm expecting. Lastly, the underlying DB is Postgres in case that's important.

**Comment by paveltiunov** [comment]
Hey @HrisIord ! Order can play a role when you're including third-party cubes in the join condition, but I don't see this in your example. Is it simplified?

**Comment by HrisIord** [comment]
Hi @paveltiunov, thank you for the quick reply. I'm not entirely sure what you mean by "third-party cubes", could you maybe give an example? The example I provided is simplified, we have a fairly large schema. Also in case this is relevant, we don't have any cubes coming from sources outside out schema files.

**Comment by paveltiunov** [comment]
@HrisIord By third-party, I mean cubes that will be referenced in join condition however will be neither of two joined cubes. For example:

```js
cube(`A`, {
  // ...
  joins: {
    B: {
      sql: `${A}.id = ${B}.a_id AND ${C}.id = 15`,
      // ...
    }
  }
})
```

**Comment by HrisIord** [comment]
The `LibraryTask` join in the `Task` cube has a filter on the security context but none of the other joins have any third-party cubes in their definitions. The full version of the mentioned join looks as follows:

```javascript
LibraryTask: {
  relationship: `belongsTo`,
  sql: `${CUBE}.standard_id = ${LibraryTask.id} 
    and ${SECURITY_CONTEXT.property.filter(`${LibraryTask.property}`)}`,
}
```

**Comment by paveltiunov** [comment]
@HrisIord Could you please elaborate about `latest_task_verification` and `task_verification_status` dependencies? Why those should go exactly in this order? Providing full failing SQL would be helpful here.

**Comment by paveltiunov** [comment]
Please feel free to reopen if issue is still there.
