### ISSUE TITLE
Design a counting measure of the element length in a MongoDB array property

### ISSUE THREAD

**Issue by lanceschi** [cube-js/cube.js#559]
**Describe the bug**
I'm using cube.js with MongoDB through [MongoDB Connector for BI][1] and [MongoBI Driver][1] and so far so good. I'd like to have a cube.js numerical **measure** that counts the element length from a MongoDB array of object nested property. Something like:

```json
{
  "nested": {
    "arrayPropertyName": [
      {
        "name": "Leatha Bauch",
        "email": "Leatha.Bauch76@hotmail.com"
      },
      {
        "name": "Pedro Hermiston",
        "email": "Pedro76@hotmail.com"
      }
    ]
  }
}

```

I wasn't able to figure that out looking at the docs and I was wondering if that is even possible.

I tried with `type: count`:
```javascript
    MyNestedArrayPropertyCounter: {
      sql: `${CUBE}.\`nested.arrayPropertyName\``,
      type: `count`,
      format: `number`,
    },
```
but I'm getting
```javascript
Error: Error: Unknown column 'nested.arrayPropertyName' in 'field list'
```

Any help/advice is really appreciated

Thanks for the awesome library!

**Expected behavior**
I'd like to have a cube.js numerical **measure** that counts the element number from a MongoDB array property.

**Version:**
0.18.23

[1]: http://docs.mongodb.com/bi-connector/master/
[2]: https://www.npmjs.com/package/@cubejs-backend/mongobi-driver

**Comment by paveltiunov** [comment]
@lanceschi Hey Luca! I think you can check this one and see if it's helpful: https://stackoverflow.com/questions/59826986/cube-js-how-to-join-two-tables-created-from-mongodb-arrays

**Comment by lanceschi** [comment]
Hi @paveltiunov,

first of all thanks for reaching out, for the advices and for the awesome lib. Here's briefly my outcomes: 

1. `LEFT JOIN` approach. I found it painfully slow and most of the time it endend out in a timeout even when querying was performed by command line sql client.

2. Launch [mongosqld][2] with [--prejoin][1] flag. That was a better option since `mongosqld` automatically adds master table columns/properties to the secondary tables thus enabling you to conveniently query without joins.

3. Wrote a mongo script that fetch/iterate/precalc and persist `nested.arrayPropertyName` count in a separate property of the collection documents.

Leaving out option 1, option 3 significantly outperforms option 2. Typically less than a seconds against more than 20''.

Most probably I'll incorporate array count precalc logic into mongo document persisting logic.


[1]: https://docs.mongodb.com/bi-connector/master/reference/mongosqld/#cmdoption-mongosqld-prejoin

[2]: https://docs.mongodb.com/bi-connector/current/
