### ISSUE TITLE
is it possible to send dynamic values into each cube schema file based on the request from users

### ISSUE THREAD

**Issue by rajeshkannandev** [cube-js/cube.js#560]
i'm using async module in every cube schema file. 

within the async module i'm making api calls to get custom measures and dimension. 

sample api call url
http://0.0.0.0:7777/api/mea-group?value=**xyz**

whenever i'm getting request from user, i want to replace the value **xyz** as per user request.

kindly provide a suggestion to achieve this. 

Thanks in advance 🙏

**Comment by paveltiunov** [comment]
@rajeshkannandev Hey Rajesh! Great question! You can use https://cube.dev/docs/cube#context-variables-compile-context for that.

**Comment by rajeshkannandev** [comment]
wow super 🎉 🎉. Thank you very much  and #stayhomestaysafe @paveltiunov
