### ISSUE TITLE
DisctinctCountApprox Postgres HLL support 

### ISSUE THREAD

**Issue by norbertbede** [cube-js/cube.js#563]
**Is your feature request related to a problem? Please describe.**
We can't make effective Count Distinct over joined tables order/orderline eg. Count Of Order
When CountDistinct used aggregations are not used because not Addictive  measure type.
https://cube.dev/docs/types-and-formats#measures-types-count-distinct-approx

**Describe the solution you'd like**
add support for DisctinctCountApprox (HLL) in Postgres

**Context**
Postgres 11 backend

**Comment by paveltiunov** [comment]
@norbertbede Hey Norbert! Thanks for posting this one! Yeah. It would be great to have one! However there's no HLL in Postgres. We'd need to support some plugin. Which one do you think the best and can solve your problem?

**Comment by norbertbede** [comment]
**Hi @paveltiunov**   We are running on AWS/RDS.  Amazon supporting plugin for awesome CitusData. The benefit would be this HLL extension is supported by AWS and also available for free for non AWS companies. 

**xref**
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html

**Comment by paveltiunov** [comment]
Yeah. I think we can stick with this one then: https://github.com/citusdata/postgresql-hll.

**Comment by norbertbede** [comment]
Interesting reading, related to this topic. 
https://www.citusdata.com/blog/2017/06/30/efficient-rollup-with-hyperloglog-on-postgres/

**Comment by norbertbede** [comment]
additional reading to implement hll
https://dzone.com/articles/faster-postgresql-counting

**Comment by norbertbede** [comment]
For better understanding how we can implement hll extension based countDistinctApprox, I write down logical flow, and pseudo sql. Cubejs engineers can use it to make exact change request.

Prerequisites
1. If cubejs using postgres then HLL extension must be installed. (if not then query reject query - like now but error message)
2. Configure schema including pre-aggregation schema include measure with orderDistinctApprox type.

Flow
1. start the cube-js server 
2. run rest query include pre-aggregation measure
3. cube-js server engine will:
    - create new pre-aggregation table A. if extension installed, then continue B. if extension can't be used returns  "Measure: xx has defined orderDistinctApprox which requre HLL extension installed DB (more info here...)
  - cube-js server will add to  all measures and dimension found in schema then =>
  - cube-js server add HLL column to newly created pre-aggregation table
  - cube-js server identify preaggregation exists - build SQL query using HLL syntax
  - cube-js server return data - counted by HLL/CountDistinctApprox extension


Example pseudo example in regular sql syntax - inherited from extension wiki:

`--Make pre-aggregation table
CREATE TABLE pre_aggreg_distinct_approx.. (
        id              integer,
        c_order_hll_id     hll  -- THIS column is place where we count id c_order_id
);

--- Insert an empty HLL - IMHO this can be optional
INSERT INTO pre_aggreg_distinct_approx(c_order_id, set) VALUES (1202001, hll_empty());

--- Add a hashed integer to the HLL
UPDATE pre_aggreg_distinct_approx SET set = hll_add(c_order_hll_id, hll_hash_integer(1202001)) WHERE c_order_id = 1;

--- Get the cardinality of the HLL
SELECT hll_cardinality(c_order_hll_id) FROM pre_aggreg_distinct_approx WHERE c_order_id = 1;`
