### ISSUE TITLE
413 error from API load endpoint

### ISSUE THREAD

**Issue by ddanf** [cube-js/cube.js#5637]
**Describe the bug**
when calling the load endpoint with a query > ~1700 bytes, we are receiving a 413 (request entity too large) error.  We have narrowed it down to between 1706 and 1758.

**To Reproduce**
1. post large query to `<host>:<port>/cubejs-api/v1/load`
2. Receive 413
3. removing one or two entries from Dimensions will cause the query to work as expected

**Expected behavior**
standard response json and 200 status

**Screenshots**
none available

**Minimally reproducible Cube Schema**

**Version:**
[e.g. 0.31.14]

**Additional context**
query:
```json
{
  "query": {
    "measures": [
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.count",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalDiscAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalCopayAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalDedctAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalRejAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalExGrtaAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsGrsAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsStlAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsRbnsAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsIbnrAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsIncrAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsRskStlAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsRskRbnsAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsRskIbnrAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsRskIncrAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsReinsAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsReinsRbnsAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsReinsIbnrAmt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.totalClmsReinsIncrAmt"
    ],
    "dimensions": [
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.clntCoCd",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.trtyClntGrpNm",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.grpNbr",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.primLfNbr",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.insLfNbr",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.rskIncptnDt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.rskRnwlDt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.trtmtStrtDt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.trtmtEndDt",
      "rpt_clm_clm_990_clab9f47d0000356e2szw7p19.admsnDt"
    ]
  },
  "queryType": "multi"
}
```

**Comment by ddanf** [comment]
Any thoughts on this?  I also posted to StackOverflow, but it seems like this was the correct place for it...

https://stackoverflow.com/questions/74491918/cube-js-api-load-endpoint-responds-with-413

**Comment by paveltiunov** [comment]
@ddanf Could you please share the curl request and response? The limit for POST load requests in Cube is 1MB. It might be you're hitting your reverse proxy limit somewhere.

**Comment by ddanf** [comment]
Hi @paveltiunov , sorry for my delay in responding - we were having trouble repeating it for a while, but now (we think) we have figured out that it is due to the response being larger than the 1MB.  The largest response that we have gotten back is just under the 1MB and when we are adding more to it, then we get the 413.

We are currently trying to refactor our app to include limit and do offset queries for additional data, but we're wondering if you have any thoughts on a better approach?

**Comment by paveltiunov** [comment]
@ddanf Do you have any reverse proxies in between?
