### ISSUE TITLE
rollupLambda aggregation add 1 =1 when FILTER_PARAMS used breaking query

### ISSUE THREAD

**Issue by kirill-morozov-bidstack** [cube-js/cube.js#5650]
**Describe the bug**

Here is example of cube schema that is used as a timeDimension (but this bug happens to any dimension/measure with FILTER_PARAMS):

```javascript
cube(`Dates`, {
  sql: `
    SELECT generated_dt
    FROM UNNEST(GENERATE_TIMESTAMP_ARRAY(
        ${FILTER_PARAMS.Dates.time.filter((from, to) =>
          `TIMESTAMP_TRUNC(timestamp(${from}), HOUR, 'Etc/UTC'), TIMESTAMP_TRUNC(timestamp(${to}), HOUR, 'Etc/UTC')`
        )},
    INTERVAL 1 HOUR)) AS generated_dt`,

  dimensions: {
    time: {
      title: `Date`,
      sql: `generated_dt`,
      type: `time`,
      primaryKey: true,
      shown: true,
    },
  },

  dataSource: `default`
});
```

Everything works fine with normal pre-aggregation, but as soon as rollupLambda is added query that being generated will look like:

```sql
SELECT generated_dt
FROM UNNEST(GENERATE_TIMESTAMP_ARRAY(
    1 = 1 AND TIMESTAMP_TRUNC(timestamp(?), HOUR, 'Etc/UTC'), TIMESTAMP_TRUNC(timestamp(?), HOUR, 'Etc/UTC'),
INTERVAL 1 HOUR)) AS generated_dt 
```

Which adds invalid 1 = 1 AND

**Version:**
v0.31.14

**Comment by paveltiunov** [comment]
@kirill-morozov-bidstack `FILTER_PARAMS` is designed to be used only in filters. Moreover, as Cube is based on multi-dimensional analysis principles it's really tough to work with calendar tables that way. Usually, most calculations based on calendar tables can be done in Cube in a much simpler way. Could you please elaborate on the final goal of this calculation?

**Comment by paveltiunov** [comment]
@kirill-morozov-bidstack What you're actually looking for is https://cube.dev/docs/schema/advanced/data-blending#data-blending. If you still want to go with joins for data blending, you can use `UNION ALL` of all distinct dates from all cubes to build a time-invariant cube for the calendar table.

**Comment by KristapsGarkevics** [comment]
@paveltiunov I think you did not understand the problem completely. The problem in this case is not about date/calendar cube, and how to change it in a working condition.
The root problem is, when any of the cube is used with FILTER_PARAMS on top of rollupLambda pre-aggregation, underneath it generates a query with extra 1:1 for a standard/regular cube join, which works with regular preaggregation. This could be easily be fixed if on cube.js generated query 1:1 generation in the query would be taken off. 
Hope this clears a bit the context of the problem for you.

**Comment by kirill-morozov-bidstack** [comment]
@paveltiunov yes, the problem here will be that it can't be predicted what combination of cubes will be requested through API, and we need this "middle" table that generates dates, which are passed in timeDimensions filter.

Based on this doc https://cube.dev/docs/schema/advanced/extending-cubes#usage-with-filter-params I do understand where "1 = 1" comes from, but query being built works perfectly with non-pre-aggregation queries, while this bug only appears with pre-aggregation. 

As an alternative maybe you know the way how to avoid "The unused filters will be rendered to 1 = 1 in the SQL query."

**Comment by paveltiunov** [comment]
@kirill-morozov-bidstack @KristapsGarkevics Yep. I see. It's intentional behavior. As of now, you can't use `FILTER_PARAMS` outside of `WHERE` statement. There's currently no straightforward workaround to that other than building time-invariant and parameter-invariant fact tables. What you're asking for is most probably this one #481.
