### ISSUE TITLE
 Restarting cube server in single instance multi tenant application

### ISSUE THREAD

**Issue by praseetha-nair** [cube-js/cube.js#5659]
We are using Cube Js - Single instance with multiple databases for multitenancy. We have a scenario where the data gets updated from the frontend on any one of the databases and we want to refresh the data for that database alone without having to restart Cube Server. Please let us know if there is any option to do this other than using the refresh key in every schema.

**Comment by paveltiunov** [comment]
@praseetha-nair Yep. You can use https://cube.dev/docs/config#schema-version for that.
