### ISSUE TITLE
Passing date range as dynamic parameter

### ISSUE THREAD

**Issue by prochj51** [cube-js/cube.js#5660]
In my model I need to calculate the total time of the dateRange which I am passing in query.

`[{"dimension":"StateDataSimple.from","granularity":"hour",**"dateRange":["2021-10-21","2021-10-22"**]}]`

Is it passible to use it in measure or in javascript code?

**Comment by paveltiunov** [comment]
@prochj51 I guess you're looking for https://cube.dev/docs/schema/reference/cube#filter-params.
