### ISSUE TITLE
Athena driver: Possibility to switch data source within Athena

### ISSUE THREAD

**Issue by remcotm** [cube-js/cube.js#5665]
**Is your feature request related to a problem? Please describe.**
Within Athena you can have multiple data sources. Currently there is no way to use a data source which is not the default one. This should be possible.

**Describe the solution you'd like**
A parameter which sets the context in which the athena queries are performed. Or just a specific env variable in which it is possible to set de athena datasource.

**Additional context**
[aws docs about the data sources within athena](https://docs.aws.amazon.com/athena/latest/ug/work-with-data-stores.html)

**Comment by paveltiunov** [comment]
@remcotm You can use fully qualified table names with catalog to switch between those like:
```
SELECT * FROM hms-catalog-1.CustomerData.customers 
```
