### ISSUE TITLE
Rename Open Distro ElasticSearch to AWS ElasticSearch

### ISSUE THREAD

**Issue by chad-codeworkshop** [cube-js/cube.js#567]
**Is your feature request related to a problem? Please describe.**
The currently implementation of OpenDistroElasticSearchQuery relates to the AWS dialect and not Open Distro

**Describe the solution you'd like**
Rename OpenDistro to AWS ElasticSearch and create a new implementation for the OpenDistro Driver

**Describe alternatives you've considered**
None

**Additional context**
ElasticSearch currently has 3 SQL dialects: X-Pack, AWS ES and OpenDistro
- [X-Pack](https://www.elastic.co/what-is/elasticsearch-sql)
- [Open Distro](https://opendistro.github.io/for-elasticsearch-docs/docs/sql/)
- [AWS ES](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/sql-support.html)

https://github.com/cube-js/cube.js/pull/551#issuecomment-608966028

**Comment by paveltiunov** [comment]
@chad-codeworkshop Hey Chad! Thanks for posting this one!
