### ISSUE TITLE
@cubejs-client/core - Error: Cannot find module '@babel/runtime/helpers/defineProperty'

### ISSUE THREAD

**Issue by MaxOrelus** [cube-js/cube.js#5670]
**Describe the bug**

@cubejs-client/core build seems to be broken on `0.30.60` and after. The following error shows up when I run a simple `cubejs.meta()`. Moving my version down to `0.30.46` resolves the issue for the time being, but all future releases error out the same way as above.

**To Reproduce**
1. Install version `0.30.60` and up
2. Run a simple `cubejs.meta()`

**Expected behavior**
`Error: Cannot find module '@babel/runtime/helpers/defineProperty'`

**Version:**
^0.30.60

**Comment by paveltiunov** [comment]
@MaxOrelus Are you building `@cubejs-client/core` from a source or using some specific build?

**Comment by ruiskeeled** [comment]
I'm facing the same problem using `"@cubejs-client/core": "0.31.15"`

I think the underline problem is related with this commit: https://github.com/cube-js/cube.js/commit/e2c9b20d0420049b9b96608716a7f10212db2c36

By moving the `@babel/runtime` to 'devDependencies' while the output build still tries to use it:
![image](https://user-images.githubusercontent.com/26111051/208637206-a7b1ade8-f3b1-4861-944a-fb0feea35bab.png)

As a temporary workaround added `"@babel/runtime": "^7.1.2"` manually and all works.
