### ISSUE TITLE
SumDistinct on cubejs

### ISSUE THREAD

**Issue by KristapsGarkevics** [cube-js/cube.js#5671]
In the company I work, there is a certain development needed for one measure, and cube.js have technical limitation, which does not allow the development to happen. 
The problem would be solved, if there would be a function sumDistinct available. 
Currently on cube.js function countDistinct(https://cube.dev/docs/schema/reference/types-and-formats#measures-types-count-distinct cube) is available for usage, but in our case, to create a measure, we need following functionality. 
Here is an sample data. 
```
with temp_data as 
(select 20 as id1,1 as id2, 100 as val union all
select 20 as id1,1, 100 union all
select 20 as id1,1, 100 union all
select 30 as id2,2, 200 union all
select 30 as id2,2, 200 union all
select 30 as id2,3, 300 union all
select 30 as id2,3, 300
)
select * from temp_data
```
The expected result form the function would be
```
row, id1, total_value
1 | 20 | 100 |  
2 | 30 | 500
```
The result is all distinct **val** values from **id2** within **id1** groups.
Here is a full example from BigQuery of the data operations, with the temporary function:
```
CREATE TEMP FUNCTION SumDistinct(arr ANY TYPE) AS ((
  SELECT AS STRUCT 
    SUM(val) total_value
  FROM (
    SELECT ANY_VALUE(t).*
    FROM UNNEST(arr) t
    GROUP BY FORMAT('%t', t)
  )
));
with temp_data as 
(select 20 as id1,1 as id, 100 as val union all
select 20 as id1,1, 100 union all
select 20 as id1,1, 100 union all
select 30 as id2,2, 200 union all
select 30 as id2,2, 200 union all
select 30 as id2,3, 300 union all
select 30 as id2,3, 300
)
SELECT id1,SumDistinct(ARRAY_AGG(STRUCT(id, val))).*
FROM temp_data
group by id1
```
The same idea should be reflected on cube.js as sumDistinct function, where for the first variable in the function, the unique key is identified, and for the second variable in the function, the appropriate value for the unique key is taken, and in general values summed all within a specific group, if data grouped.

**Comment by paveltiunov** [comment]
@KristapsGarkevics You should remodel your data in a way where you have a unique id for each sum and introduce a separate cube for it. Then you can use joins to join this cube back to the original data set. In this case, Cube will automatically take care of row deduplication.

**Comment by KristapsGarkevics** [comment]
Hello dear @paveltiunov.

Thank you very much for your suggestion. 
In our case, it is too difficult the change the data structure, ad everything else would be needed to restructure. We created a workaround regards this, so, case it closed. 
In case someone is in the same situation, or any other. If there are some operation with data, which needs to be done on cube.js, but not available on the platform. Feature can be created on BigQuery as UDF. If UDF is created, then functionality can be referenced from cube.js to BigQuery, and used on cubel.js. Simple as that. 
Again, Thank you very much for your suggestion, dear @paveltiunov .

@KristapsGarkevics
