### ISSUE TITLE
how to use calculated measure expression from async module response (Question)

### ISSUE THREAD

**Issue by rajeshkannandev** [cube-js/cube.js#568]
i'm using async module to retrieve calculated measures from api. 

when i setting the calculated measure from response its compiling only as string not as a template string. Because of that cube js schema compiler throwing an error.

when i'm trying to use cube schema name without template string(backtick) it's not making joins.  

here I want to replicate following image expression from json response and following is the syntax that cube js expects and it works fine. 

![image](https://user-images.githubusercontent.com/62346173/78469651-e6157680-7740-11ea-93a2-7687a6d7fae9.png)

and this happens when i retrieving calculated measure from response 

![image](https://user-images.githubusercontent.com/62346173/78469643-d0a04c80-7740-11ea-9803-977c2d72a322.png)

**Comment by paveltiunov** [comment]
@rajeshkannandev Hey Rajesh! Please see https://cube.dev/docs/schema-execution-environment#context-symbols-transpile
