### ISSUE TITLE
What is the effective maximum for multitenancy?

### ISSUE THREAD

**Issue by derekperkins** [cube-js/cube.js#5684]
I know Cube is designed with [multi-tenancy](https://cube.dev/docs/config/multitenancy) in mind, but how that scales isn't discussed. When does Cube performance start to degrade? If each tenant has 100 tables, can Cube support millions of tenants?

**Comment by paveltiunov** [comment]
@derekperkins Please see https://cube.dev/docs/config/multitenancy#multitenancy-running-in-production.

**Comment by derekperkins** [comment]
> Each unique id generated by contextToAppId or contextToOrchestratorId will generate a dedicated set of resources, including schema compile cache, SQL compile cache, query queues, in-memory result caching, etc. Depending on your data model complexity and usage patterns, those resources can have a pretty sizable memory footprint ranging from single-digit MBs on the lower end and dozens of MBs on the higher end

Thanks for responding - I did read that, but wasn't sure how to interpret it. For the scenario I described: 1M tenants with 100 tables each, that would be 100M unique ids, which translates into 100 TB - 1 PB of RAM required. Does that sound correct? I appreciate that you can shard those to hit different servers, which provides a way to horizontally scale, but would also be massively expensive.

**Comment by paveltiunov** [comment]
@derekperkins Yep. That's correct. The question is, do you need to allocate a unique `contextToAppId` per each tenant, or can you bucket, for example, 1000 tenants per each `contextToAppId` because they share the schema, tables, underlying databases and differ only with row-level security filters. I hope it makes sense. If you can provide more specific details on the business use case, I can probably provide you with more specific advice on how to do it.

**Comment by derekperkins** [comment]
We are multi-tenant inside of BigQuery, and every customer gets their own BQ dataset / tables. The schema structure for all the tables is the same, but none of them are shared with row level security filters

**Comment by paveltiunov** [comment]
@derekperkins Then it boils down to how many active or concurrent tenants you have. You need to reserve memory and resources for active tenants only, not for the total number. Regarding usage footprint per tenant would be more like ~10-20MB per unique `contextToAppId`, not per table.

**Comment by derekperkins** [comment]
I appreciate your help. What qualifies as "active"? We have daily data flowing into most of our accounts, but many tenants don't login more than weekly. Does Cube automatically spin down inactive connections?

**Comment by paveltiunov** [comment]
@derekperkins Some of the Cube in memory structures are LRU based, and some, like connection pools, aren't, so you'd need to take care of it yourself. You can employ garbage collection tactics similar to those found in young-old-generation algorithms. For example, rotate instances within a bucket, so only active tenants survive. We have more multi-tenancy auto-scaling controls in Cube Cloud to handle such use cases.
