### ISSUE TITLE
Charting data with a range

### ISSUE THREAD

**Issue by 0x62** [cube-js/cube.js#569]
I have a table containing subscriptions, with a start and end date (usually 1 month). At the end of each period a new row is inserted when it renews.

I'd like to be able to chart the number of active subscriptions over time, by day. For each day, it should be the total count of subscriptions where `date > row.start AND date < row.end`.

How can I do this in cubejs?

**Comment by paveltiunov** [comment]
@0x62 Hey Ben! Please see https://stackoverflow.com/questions/60644239/cube-js-time-range-best-practice

**Comment by 0x62** [comment]
Thanks, sorted
