### ISSUE TITLE
Items in resultSet.chartPivot() hold the wrong date in their x-property when comparing date ranges

### ISSUE THREAD

**Issue by code-shambles** [cube-js/cube.js#5691]
Under certain circumstances, the array items of `resultSet.chartPivot()` (and other functions that make use of it, like `resultSet.series()` hold the wrong date in their field `x`. The version in use is `"@cubejs-client/core": "^0.31.15"`.

Our setup is an analytics dashboard with a chart, a table, and some controls, most importantly a daterange selector and an option to compare with the previous period. When in compare mode, we use the time dimension type `TimeDimensionComparison` with the property `compareDateRange` to generate a `compareDateRangeQuery`.

So, when in compare mode, I noticed that the return of `resultSet.chartPivot()` (no arguments given) seems to be wrong. But only in one certain case that I came across so far; usually it works well 😱

## Negative case (positive below)

- comparing date ranges
- using `2022-10-01` to `2022-10-31` as current range
- comparing to "previous period", here `2022-09-01` to `2022-09-30` (the month before)

### The `query`

```json
{
    "measures": [
        "Count_clicks_positions.click_on_reco_slider"
    ],
    "timeDimensions": [
        {
            "dimension": "Count_clicks_positions.createdAt",
            "granularity": "day",
            "compareDateRange": [
                [
                    "2022-10-01",
                    "2022-10-31"
                ],
                [
                    "2022-09-01",
                    "2022-09-30"
                ]
            ]
        }
    ]
}
```

### The `resultSet`

✅ Looks normal to me.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/12255735/204769524-59edc45c-6565-4eff-91b6-5f995e2db442.png">

### The `resultSet.chartPivot()`

❗️ The items' `x` fields hold the dates of the date range we're _comparing with_, not the current date range

<img width="834" alt="image" src="https://user-images.githubusercontent.com/12255735/204605815-6003c808-4111-4567-a675-0d7a52f0414c.png">

## Positive case

<details>
<summary>
show/hide
</summary>

- also, comparing date ranges
- the only difference
  - above (bad case) date range was `2022-10-01` to `2022-10-31`
  - __now__ it's `2022-10-01` to only `2022-10-30`, compared to `2022-09-30` (the 30 days before)
- everything looks good

### The `query`

```json
{
    "measures": [
        "Count_clicks_positions.click_on_reco_slider"
    ],
    "timeDimensions": [
        {
            "dimension": "Count_clicks_positions.createdAt",
            "granularity": "day",
            "compareDateRange": [
                [
                    "2022-10-01",
                    "2022-10-30"
                ],
                [
                    "2022-09-01",
                    "2022-09-30"
                ]
            ]
        }
    ]
}
```

### The `resultSet`

<img width="834" alt="image" src="https://user-images.githubusercontent.com/12255735/204770071-cff8c6f8-fb60-4c38-b767-d6d23ff27b4a.png">

### The `resultSet.chartPivot()`

✅ The items' `x` properties hold the dates of the __current__ date range.
<img width="834" alt="image" src="https://user-images.githubusercontent.com/12255735/204601429-3f565875-46c7-47c8-ae74-fbd93c306567.png">

</details>

## Summary

Of course it's questionable if it does or does not make sense to compare a 31-days-month to a 30-days-month (and if it's related to the problem at all). Nevertheless, I think it's wrong that `resultSet.chartPivot()` return the wrong date for `x`. 

Some more notes I can share
- while `x` origins from the __wrong__ daterange, the actual `value`s of the items seem to come from the __correct__, current daterange
- it __never__ happened with a non-`compareDateRangeQuery`
- it __only__ happened with the example shown, so far
- I stripped the application as far as possible to make sure no other code acts on the console.logged objects any more

**Comment by vasilev-alex** [comment]
Hey @code-shambles!

It is not always obvious that the "current" date range is always the first. In your case, we take the longest period, as otherwise, what would be `x` for the last day of this range `"2022-09-01", "2022-09-30"` because the other range has 31 days.

Maybe you could elaborate on how you use the `x`'s value data?

Also, we have an undocumented flag `joinDateRange` which may be the thing you're looking for

```js
resultSet.chartPivot({
    x: ['Count_clicks_positions.createdAt'],
    y: ['measures'],
    joinDateRange: true
});
```

**Comment by SoozaV** [comment]
Hi @vasilev-alex I'm trying to rendering a compareDateRange chart, comparing a 30 days month with a 31 days month, but the chart always render 30 days (or the shortest period of the selected ranges, for example if I select 15 days range and a 10 days range, the chart display 10 days), I tried using `joinDateRange: true` but that's not working.

How could display the longest period in the chart.

**Comment by SoozaV** [comment]
Hi @code-shambles did you find a solution for this problem? Comparing 2 months with different number of days?

Regards.
