### ISSUE TITLE
Cubestore failed to start in macos 13 ventura

### ISSUE THREAD

**Issue by zhjuncai** [cube-js/cube.js#5712]
**Describe the bug**
Cubestore is not able to start on macos 13 ventura

**To Reproduce**
I downloaded the cubestore executable binary and just click on it.
```
> ./cubestored
[1]    41780 segmentation fault  ./cubestored
```

It works as exepcted on macos 12
![cubestore](https://user-images.githubusercontent.com/352408/205207105-39683b6f-4fd1-45ab-8ed8-f9c2ae0e6849.png)

**Expected behavior**
Not sure why it doesn't work on Macos 13, tested on other machines who had upgraded to macos 13, they had the same issue. But works great on 12

**Screenshots**
<img width="544" alt="Screenshot 2022-12-02 at 11 17 49" src="https://user-images.githubusercontent.com/352408/205207332-1a231107-7253-45c3-81b3-16e68a8c98f2.png">

**Version:**
cubestore latest version and older versions

**Additional context**
I don't know if this is Ventura macos system issue or cubestore doesn't support the latest macos ventura
**cubestore works great on M1 chip but not intel , mine is 2.3 GHz 8-Core Intel Core i9** MacOS: **Version 13.0.1 (22A400)**

**Comment by paveltiunov** [comment]
@zhjuncai Could you please try to run it within docker?

**Comment by zhjuncai** [comment]
> @zhjuncai Could you please try to run it within docker?

Hi @paveltiunov Docker works great on latest version

**Comment by phil-lange** [comment]
Same issue here - intel chip, newest macos version 13.0.1 (22A400). When I run cube.js in dev mode with npm, it automatically starts cubestore, but it doesn't work (exited with error null). If I run cubestore with docker and define the env vars, it works fine. Is there a plan to fix that @paveltiunov because it's indeed a bug?

**Comment by paveltiunov** [comment]
@zhjuncai @phil-lange Could you please try latest version?

**Comment by zhjuncai** [comment]
super!! works for me with **0.31.26**. Thanks very much @paveltiunov 

<img width="1039" alt="Screenshot 2022-12-14 at 12 39 37" src="https://user-images.githubusercontent.com/352408/207507418-c59dcf9c-45fc-4678-a034-f767dd6c4581.png">
