### ISSUE TITLE
ISNULL does not work in preaggergations

### ISSUE THREAD

**Issue by prochj51** [cube-js/cube.js#5714]
**Describe the bug**
I would like to check for null in my model, with function ISNULL() fro MSSQL.

When I do NOT use preaggregations, it gives me correct values. But when I do use it I get this error:

`Internal: Error during planning: Invalid function 'isnull'`

Would I have to use something else for preaggregations?

```javascript
cube(`CANData`, {
  sql: `SELECT  
  [AssetId]
  ,[Tag]
  ,[TypeCode]
  ,[From]
  ,[To]
  ,[StateValue]
  ,[ValueFrom]
  ,[ValueTo]

  FROM [Sidas3Uns].[dbo].[CANData]`,
  dataSource: `data`,
  preAggregations: {
    main: {
      measures: [CANData.productive, CANData.totalTime],
      timeDimension: CANData.from,
      granularity: `hour`
    }
  },
  measures: {
    //time partial models
    totalTime: {
      type: `sum`,
      sql: `${timeDifference}`
    },
    //RUN
    productive: {
      type: `sum`,
      sql: `${timeDifference}`,
    },
    //Models
    OAE: {
      sql: ` (ISNULL(${productive},0)) * 1.0 / ${totalTime}`,
      type: `number`
    },
  },
  dimensions: {
    timeDifference: {
      type: `number`,
      sql: `DATEDIFF(MINUTE, ${from} , ${to})`
    },
    from: {
      sql: `CAST(${CUBE}."From" as datetime)`,
      type: `time`
    },
    to: {
      sql: `CAST(${CUBE}."To" as datetime)`,
      type: `time`
    }
  }
});
```

**Version:**
0.31.5

**Comment by paveltiunov** [comment]
@prochj51 You should use `NULLIF()` instead.

**Comment by prochj51** [comment]
Does not `NULLIF()` do the opposite? I need the NULL value to be handled as zero ..

**Comment by prochj51** [comment]
@paveltiunov I think it will not help me. Because image when I do have some filter and it does not return me any value at all or there are no records, the `sql: `NULLIF(${timeDifference})`` is not executed at all and I get NULL anyway. I need also to check the null after the aggregation is done.

**Comment by paveltiunov** [comment]
@prochj51 Could you please try to reproduce it and provide the schema, data, and query you use?

**Comment by prochj51** [comment]
@paveltiunov Sorry, I was not around for a while..

This schema should make it more clear.
I have to models in there, Working and NotWorking, both models should return same data. 

filter TypeCode in nonSense measure is set to non existing value, so it returns NULL... the ISNULL() should be evaluated after aggregation

`cube(`CANDataBug`, {
  sql: `SELECT  
  [AssetId]
  ,[Tag]
  ,[TypeCode]
  ,[From]
  ,[To]
  ,[StateValue]
  ,[ValueFrom]
  ,[ValueTo]

  FROM [Sidas3Uns].[dbo].[CANData]`,
  dataSource: `data`,
  preAggregations: {
    main: {
      measures: [CANData.productive, CANData.totalTime],
      timeDimension: CANData.from,
      granularity: `hour`
    }
  },
  measures: {
    //time partial models
    totalTime: {
      type: `sum`,
      sql: `${timeDifference}`
    },
    //RUN
    productive: {
      type: `sum`,
      sql: `${timeDifference}`,
      filters: [{
        sql: `${CUBE}."TypeCode" = 4 and ${CUBE}."Tag" = 'CAN/Filler/State/Status'`
      }]
    },
    //filter TypeCode is set to non existing value, so it returns NULL... the ISNULL() should be evaluated after aggregation
    nonSense: {
      type: `sum`,
      sql: `ISNULL(${timeDifference},0)`,
      filters: [{
        sql: `${CUBE}."TypeCode" = 86 and ${CUBE}."Tag" = 'CAN/Filler/State/Status'`
      }]
    },
    //Two models, both should return same data
    Working: {
      sql: ` (${productive}) * 1.0 / ${totalTime}`,
      type: `number`
    },
    NotWorking: {
      sql: ` (${productive} + ${nonSense}) * 1.0 / ${totalTime}`,
      type: `number`
    },
  },
  dimensions: {
    timeDifference: {
      type: `number`,
      sql: `DATEDIFF(MINUTE, ${from} , ${to})`
    },
    from: {
      sql: `CAST(${CUBE}."From" as datetime)`,
      type: `time`
    },
    to: {
      sql: `CAST(${CUBE}."To" as datetime)`,
      type: `time`
    }
  }
});`


The return data for the models is not the same cause Cube handles it asi value + NULL = NULL which results in zero
![image](https://user-images.githubusercontent.com/40229516/207858181-26d98f6a-0e5e-4ba0-ba2f-0afbbae4f797.png)

My Query is
`http://localhost:4000/#/build?query={%22measures%22:[%22CANDataBug.Working%22,%22CANDataBug.NotWorking%22],%22timeDimensions%22:[{%22dimension%22:%22CANDataBug.from%22,%22granularity%22:%22hour%22,%22dateRange%22:[%222021-10-21%22,%222021-10-21%22]}]}`

Sample of working data:
[BugData.csv](https://github.com/cube-js/cube.js/files/10236897/BugData.csv)

**Comment by paveltiunov** [comment]
@prochj51 I see. You can use something like `CASE WHEN ${productive} IS NOT NULL THEN ${productive} ELSE 0 END` then.

**Comment by prochj51** [comment]
Yes, this works, thanks.
