### ISSUE TITLE
Invalid SQL generated by MSSQL driver

### ISSUE THREAD

**Issue by maxgrv** [cube-js/cube.js#573]
We run a very large cube.js model (1000s of cubes) and we are experiencing a SQL generation bug when we issue a query with two measures related to a second-level joined cube. Each measure works if queried separately. If requested in the same query, the generated SQL for SQL Server is invalid ("the multi-part identifier could not be bound"). I have formatted the large SQL query in the attached PDF and manually debugged it: basically, the group-by identifiers are not rewritten correctly to target the "keys" subquery. I have marked the invalid part in the PDF and the correct SQL identifiers 

[Formatted SQL Query](https://www.docdroid.net/sOxHsVZ/bug-pdf#page=2)

 I cannot post the cube.js model as it is unmanageably large.

**Version:**
latest (0.18)

**Comment by paveltiunov** [comment]
@maxgrv Hey Massimo! I can confirm this case seems unsupported by MS SQL.

**Comment by avin3sh** [comment]
I ran into exact same issue. Interestingly I observed that if I use drill-down instead of a "regular" measure, and modify CubeValidator and BaseQuery file to support the `type` (right now drill-down measure only supports `count`) - I am able to work around this issue. 

Would be great to see this fixed soon.

**Comment by davefrancis** [comment]
I am also running into this issue when making queries that require a join. It only seems to occur when the join requires a distinct set of primary keys to be selected. The GROUP BY clause that is generated uses aliases from the inner subquery (the one that selects the distinct keys) and not the alias defined in the grouped query. Like the query posted by @maxgrv, the GROUP BY clause should contain column names from the "keys" subquery.

`SELECT
  TOP 10000q_0."story_labels__label_name",
  q_0."story_labels__label_value",
  "pressboard_analytics__reads" "pressboard_analytics__reads",
  "instagram_post_insights__impressions" "instagram_post_insights__impressions"
FROM
  (
    SELECT
      "main___story_labels".LabelName "story_labels__label_name",
      "main___story_labels".LabelValue "story_labels__label_value",
      count(
        distinct "main___pressboard_analytics".VisitorId + '-' + "main___pressboard_analytics".SessionId + '-' + "main___pressboard_analytics".ViewId + '-' + CAST(
          "main___pressboard_analytics".StoryReportId AS nvarchar(100)
        )
      ) "pressboard_analytics__reads"
    FROM
      (
        SELECT
          *
        FROM
          StoryLabels
        WHERE
          OrganizationId = @ _1
      ) AS "main___story_labels"
      LEFT JOIN (
        SELECT
          *
        FROM
          PBAttentionMinutesV2
        WHERE
          OrganizationId = @ _2
      ) AS "main___pressboard_analytics" ON "main___story_labels".StoryId = "main___pressboard_analytics".StoryRequestId
      LEFT JOIN (
        SELECT
          *
        FROM
          InstagramPostInsights
        WHERE
          OrganizationId = @ _3
      ) AS "main___instagram_post_insights" ON "main___story_labels".StoryId = "main___instagram_post_insights".StoryRequestId
    GROUP BY
      "main___story_labels".LabelName,
      "main___story_labels".LabelValue
  ) as q_0
  INNER JOIN (
    SELECT
      "keys"."story_labels__label_name",
      "keys"."story_labels__label_value",
      sum(
        "instagram_post_insights_key___instagram_post_insights".Impressions
      ) "instagram_post_insights__impressions"
    FROM
      (
        SELECT
          DISTINCT "instagram_post_insights_key___story_labels".LabelName "story_labels__label_name",
          "instagram_post_insights_key___story_labels".LabelValue "story_labels__label_value",
          "instagram_post_insights_key___instagram_post_insights".StoryReportId "instagram_post_insights__story_report_id"
        FROM
          (
            SELECT
              *
            FROM
              StoryLabels
            WHERE
              OrganizationId = @ _4
          ) AS "instagram_post_insights_key___story_labels"
          LEFT JOIN (
            SELECT
              *
            FROM
              PBAttentionMinutesV2
            WHERE
              OrganizationId = @ _5
          ) AS "instagram_post_insights_key___pressboard_analytics" ON "instagram_post_insights_key___story_labels".StoryId = "instagram_post_insights_key___pressboard_analytics".StoryRequestId
          LEFT JOIN (
            SELECT
              *
            FROM
              InstagramPostInsights
            WHERE
              OrganizationId = @ _6
          ) AS "instagram_post_insights_key___instagram_post_insights" ON "instagram_post_insights_key___story_labels".StoryId = "instagram_post_insights_key___instagram_post_insights".StoryRequestId
      ) AS "keys"
      LEFT JOIN (
        SELECT
          *
        FROM
          InstagramPostInsights
        WHERE
          OrganizationId = @ _7
      ) AS "instagram_post_insights_key___instagram_post_insights" ON "keys"."instagram_post_insights__story_report_id" = "instagram_post_insights_key___instagram_post_insights".StoryReportId
    GROUP BY
      "instagram_post_insights_key___story_labels".LabelName,
      "instagram_post_insights_key___story_labels".LabelValue
  ) as q_1 ON (
    q_0."story_labels__label_name" = q_1."story_labels__label_name"
    OR (
      q_0."story_labels__label_name" IS NULL
      AND q_1."story_labels__label_name" IS NULL
    )
  )
  AND (
    q_0."story_labels__label_value" = q_1."story_labels__label_value"
    OR (
      q_0."story_labels__label_value" IS NULL
      AND q_1."story_labels__label_value" IS NULL
    )
  )
ORDER BY
  3 DESC`

**Comment by buntarb** [comment]
Hi, @maxgrv. I've merged https://github.com/cube-js/cube.js/pull/5078 and released 0.30.46 with these changes. This issue is fixed. Could you please check it?
