### ISSUE TITLE
Ability to provide order in the QueryBuilder (React) component.

### ISSUE THREAD

**Issue by gauravlanjekar** [cube-js/cube.js#578]
**Is your feature request related to a problem? Please describe.**
Currently, the QueryBuilder component in React only allows the user to set in measures, dimensions, time and filter. 
I would also like to provide order by clause to the query which is created. 

**Describe the solution you'd like**
In addition to measures I would like to pass in the order in which the query results are returned.

**Additional context**
Version:
"@cubejs-client/react": "0.18.18"

**Comment by paveltiunov** [comment]
@gauravlanjekar Would really appreciate if you can provide some description.

**Comment by gauravlanjekar** [comment]
@paveltiunov Updated the issue.

**Comment by paveltiunov** [comment]
@gauravlanjekar You can do so by providing `order` as part of `query` or `vizState` properties of `QueryBuilder`.

**Comment by gauravlanjekar** [comment]
@paveltiunov yes.. but its not dynamic. I mean if the user chooses say dimensionA and dimensionB and now I want to allow the user to sort either by A or by B. I want to provide the same flexibility as the query builder provides for dimensions and measures

**Comment by paveltiunov** [comment]
@gauravlanjekar Gotcha. Yeah. It's on-going work there to support ordering in `QueryBuilder` and playground. Let's use this issue to track status.

**Comment by vasilev-alex** [comment]
Closed by #685
