### ISSUE TITLE
databricks-driver: ENOENT: no such file or directory, open 'package.json'

### ISSUE THREAD

**Issue by zhjuncai** [cube-js/cube.js#5833]
**Describe the bug**
When use databricks driver in docker got error ENOENT: no such file or directory, open 'package.json'
Run the cube in local dev mode works well, but not in docker

**To Reproduce**
Deploy cube to k8s with production mode, and config the databricks env
- CUBEJS_DB_TYPE: databricks-jdbc
- CUBEJS_DB_NAME: demo
- CUBEJS_DB_EXPORT_BUCKET: bucket url
- CUBEJS_DB_EXPORT_BUCKET_AZURE_KEY: key
- CUBEJS_DB_DATABRICKS_URL: jdbc:databricks://adb-domain:443/demo;transportMode=http;ssl=1;httpPath=sql/protocolv1/o/7933175771707640/1120-155656-gwhb2j0i;AuthMech=3;UID=token;
- CUBEJS_DB_DATABRICKS_ACCEPT_POLICY: true
- CUBEJS_DB_DATABRICKS_TOKEN: databricks token

**Expected behavior**
Cube databricks driver can connect to datasource via databricks java driver

**Screenshots**
testConnection failed

```json
{
  "message": "Internal Server Error on readiness probe",
  "driverType": "internal",
  "error": "Error: ENOENT: no such file or directory, open 'package.json'\n    at DatabricksDriver.testConnection (/cube/node_modules/@cubejs-backend/jdbc-driver/src/JDBCDriver.ts:170:13)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at /cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:543:15\n    at OrchestratorApi.testDriverConnection (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:209:24)\n    at async Promise.all (index 0)\n    at ApiGateway.readiness (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1971:9)\n    at /cube/node_modules/@cubejs-backend/api-gateway/src/cached-handler.ts:58:9"
}
```

```
Error: ENOENT: no such file or directory, open 'package.json'
    at DatabricksDriver.testConnection (/cube/node_modules/@cubejs-backend/jdbc-driver/src/JDBCDriver.ts:170:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:543:15
    at OrchestratorApi.testDriverConnection (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:209:24)
    at async Promise.all (index 0)
    at ApiGateway.readiness (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1971:9)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/cached-handler.ts:58:9"
```

**Version:**
latest, cubejs/cube:v0.31.26-jdk

**Additional context**
It seems JDBCDriver.ts to `initMvn`which requires to read `package.json`, but I don't understand which package.json the `node-java-maven` tries to read.

```ts
const initMvn = (customClassPath: any) => {
  if (!mvnPromise) {
    mvnPromise = new Promise((resolve, reject) => {
      mvn((err: any, mvnResults: any) => {
        if (err && !err.message.includes('Could not find java property')) {
          reject(err); // the error seems thrown here
        } else {
          if (!jinst.isJvmCreated()) {
            jinst.addOption('-Xrs');
            const classPath = (mvnResults && mvnResults.classpath || []).concat(customClassPath || []);
            jinst.setupClasspath(classPath);
          }
          resolve();
        }
      });
    });
  }
  return mvnPromise;
};

```

**Comment by paveltiunov** [comment]
@zhjuncai You need to use `cubejs/cube:jdk` image in order to use data bricks. cc @hassankhan.

**Comment by hardiktalati** [comment]
still the error exist 

> You need to use `cubejs/cube:jdk` image in order to use data bricks. cc @hassankhan.
still facing the same error

**Comment by paveltiunov** [comment]
@zhjuncai @hardiktalati You need to build your custom image based on `cube:jdk` as Databricks driver is proprietary and we don't distribute it as part of our images. We need to update the docs here. @hassankhan

**Comment by zhjuncai** [comment]
I'm using cube jdk already and I saw the logs the driver itself downloaded the jar and put it in classpath.

**Comment by zhjuncai** [comment]
@paveltiunov from the `DatabricksDriver` implementation, the `DatabricksJDBC42.jar` will be downloaded as long as `CUBEJS_DB_DATABRICKS_ACCEPT_POLICY` set to true, and put in `/cube/node_modules/@cubejs-backend/databricks-jdbc-driver/dist/download`. However, when pre-aggregation refresher to run, got the above error message. So I think to build a custom image doesn't help here.
<img width="1125" alt="Screenshot 2022-12-22 at 13 07 45" src="https://user-images.githubusercontent.com/352408/209061475-bfd87810-8970-4cda-8e98-ffacb927668c.png">

**Comment by zhjuncai** [comment]
ok guys, I think I resolved the question by putting an empty `package.json` in `/cube/conf` folder.
It seems at the end of cube:jdk image, the WORKDIR was set to `WORKDIR /cube/conf`
I will continue test and will let you know if that's the final solution.

**Comment by laurentenhoor** [comment]
> 

It because of this mapping in docker-compose
```
    volumes:
      - .:/cube/conf
 ```
So you have to create an empty package.json in your project folder locally. Or remove this volume mapping.

**Comment by zhjuncai** [comment]
@laurentenhoor I'm using K8s configmap to mount the path. But you are right, put an empty package.json in /cube/conf should do the tricks.

**Comment by laurentenhoor** [comment]
@zhjuncai how do you prevent duplicate mounts in the k8s confgmap approach caused by the ..timestamp/ and ..data/ symlink folders?
