### ISSUE TITLE
Link broken or not working.

### ISSUE THREAD

**Issue by hasan-araav** [cube-js/cube.js#5847]
**Describe the bug**
I found a broken link while reading this page 👉 https://cube.dev/blog/building-open-source-google-analytics-from-scratch

This link 👉 [Here’s an analytics dashboard with an embedded tracking code](http://aws-web-analytics-dashboard.s3-website-us-east-1.amazonaws.com/) is broken.

**To Reproduce**
1. Go to 'https://cube.dev/blog/building-open-source-google-analytics-from-scratch'
2. Click on '[Here’s an analytics dashboard with an embedded tracking code](http://aws-web-analytics-dashboard.s3-website-us-east-1.amazonaws.com/) is broken.'
3. See error

**Expected behavior**
Expected to see a webpage

**Screenshots**
![image](https://user-images.githubusercontent.com/10432960/208346163-f551f004-9515-4b35-8421-53030bdafb78.png)

**Comment by igorlukanin** [comment]
Hey @hasan-araav 👋 Thanks for reporting this! Unfortunately, this example is quite outdated so I had to remove it. Please see this one as an alternative: https://web-analytics-demo.cube.dev
