### ISSUE TITLE
UnknownEndpoint: Inaccessible host: `athena.'

### ISSUE THREAD

**Issue by bfadnis** [cube-js/cube.js#588]
I am new to cube.js and trying to connect it to Athena from my local machine (using CLI). I updated .env file with athena credentials but still getting error as "Error while loading DB schema UnknownEndpoint: Inaccessible host: `athena.'. This service may not be available in the `<AWS REGION STRING, e.g. us-east-1>' region."  Is it incorrect format in .env file ? Please advise if you encounter similar error. We want to use us-west-2 region for athena but also tested with us-east-1 and it did not work.

**Comment by paveltiunov** [comment]
Hey @bfadnis ! Could you please share your .env file?

**Comment by bfadnis** [comment]
The .env file looks as below (credentials changed but format is same)
CUBEJS_AWS_KEY=ABCD
CUBEJS_AWS_SECRET=I1234
CUBEJS_AWS_REGION=us-west-2
# You can find the Athena S3 Output location here: https://docs.aws.amazon.com/athena/latest/ug/querying.html
CUBEJS_AWS_S3_OUTPUT_LOCATION=s3://my-bucket-dev/
CUBEJS_JDBC_DRIVER=athena
CUBEJS_DB_TYPE=athena
CUBEJS_API_SECRET=d1e**c

**Comment by paveltiunov** [comment]
@bfadnis And what's updated error message? Error you provided clearly says that region value is incorrect and it's a placeholder there.

**Comment by paveltiunov** [comment]
@bfadnis Was it helpful?
