### ISSUE TITLE
Update types in @cubejs-client/core

### ISSUE THREAD

**Issue by lenatech** [cube-js/cube.js#589]
**Describe the bug**
the types in `@cubejs-client/core` seems a little bit outdated

**To Reproduce**
For example, the function `totalRow` is defined in `ResultSet` class in the source code but it is not included in the ResultSet type. 

**Expected behavior**
`totalRow(pivotConfig?: PivotConfig): { [key: string]: number };`
should be added into ResultSet

**Screenshots**
![Screenshot from 2020-04-14 09-51-18](https://user-images.githubusercontent.com/5935679/79199640-91a38280-7e35-11ea-9742-9040c4caaec1.png)
![Screenshot from 2020-04-14 09-52-39](https://user-images.githubusercontent.com/5935679/79199757-ba2b7c80-7e35-11ea-8d98-7b8ce6cb461c.png)

**Version:**
[0.19.0]

**Additional context**
there are other types which might also need to be changed, such as `Column`, `Filter`.

**Comment by paveltiunov** [comment]
@lenatech Hey Aimee! Thanks for posting this! Yep. We need to update this.

**Comment by uncvrd** [comment]
Reporting in to note that `totalRow` still appears to be missing in documentation even though it is being used in cube playground! 

Here are the list of `ResultSet` options:

![image](https://user-images.githubusercontent.com/25097099/110426425-ee65e800-805a-11eb-936b-40bfd0757c73.png)

While here is `totalRow` being used in the playground:

![image](https://user-images.githubusercontent.com/25097099/110426463-00e02180-805b-11eb-9e71-302bdc31d09c.png)

**Comment by nuwe1** [comment]
@rpaik Could you please assign this to me?
