### ISSUE TITLE
Pluggable schema compiler adapter for new databases

### ISSUE THREAD

**Issue by klausb** [cube-js/cube.js#590]
**Is your feature request related to a problem? Please describe.**
 When a new DB needs to be supported I can provide the actual DB driver dynamically, but not the schema driver.

**Describe the solution you'd like**
I'd like add more schema drivers for new databases w/o waiting for a new build. E.g. dynamically adding a file to `packages/cubejs-schema-compiler/adapter`

**Describe alternatives you've considered**
Not available

**Additional context**
n/a

**Comment by paveltiunov** [comment]
Hey @klausb ! Thanks for posting this one! Yep. Agree. We need to load those dynamically as well and corresponding dialects should go to corresponding driver packages.

**Comment by klausb** [comment]
@paveltiunov, has this enhancement being added?

**Comment by paveltiunov** [comment]
@klausb Yep. It's shipped already. You can learn more here: https://github.com/cube-js/cube.js/blob/master/CONTRIBUTING.md#implementing-sql-dialect
