### ISSUE TITLE
ResultSet.totalRow is converting non-date fields to Dates since v0.19.9

### ISSUE THREAD

**Issue by JeffreyPalmer** [cube-js/cube.js#602]
**Describe the bug**
The client ResultSet.totalRow function is converting values that are not dates into dates.

For example, a result of "5138" used to be 5138, but it is now the date: "Date Fri Dec 31 5137 16:00:00 GMT-0800 (Pacific Standard Time)". I am guessing that [this commit](https://github.com/cube-js/cube.js/commit/11c1106) is the cause.

**To Reproduce**
1. Return a result that includes a number (in my case it was a "count" measure).
2. Access the result via the ResultSet.totalRow function
3. Your field has been erroneously converted into a Date.

**Expected behavior**
Non-dates should not become dates.

**Screenshots**

**Version:**
0.19.9

**Comment by paveltiunov** [comment]
@JeffreyPalmer Hey Jeffrey! Thanks for posting this! Seems like invalid regex. cc @richipargo

**Comment by paveltiunov** [comment]
@JeffreyPalmer Should be fixed in 0.19.11. Could you please update and check?

**Comment by richipargo** [comment]
Just saw this @paveltiunov thanks for the quick adjustement, probably will have to take a more in depth look

**Comment by JeffreyPalmer** [comment]
Yep, this is fixed. Thanks for the quick turnaround!
