### ISSUE TITLE
Support file-based certificate parameter for database connections

### ISSUE THREAD

**Issue by jcw-** [cube-js/cube.js#604]
**Is your feature request related to a problem? Please describe.**
Heroku has limitations on how much data you can put into environment variables, making the approach in #582 unusable as the .pem file for AWS exceeds this limit.

https://devcenter.heroku.com/articles/config-vars#config-var-policies
> Config var data (the combination of all keys and values) cannot exceed 32kb for each app

**Describe the solution you'd like**
Refer to discussion in #582:
> extract SSL code to BaseDriver and support file env variables as well in centralized manner

**Questions**

- Should it be the same environment variable (e.g. `CUBEJS_DB_SSL_CA`) but with detection if it is holding a file path or file contents?
- Should it be a new set of env vars?

**Comment by paveltiunov** [comment]
@jcw- Hey Jc! Thanks for posting this!

**Comment by hassankhan** [comment]
Closing as the `CUBEJS_SSL_*` environment variables now support raw input as well as a path to the Pemfile/CA bundle.
