### ISSUE TITLE
Feature/Support: Cube.js client REST call abstraction

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [cube-js/cube.js#607]
We have a complex REACT REDUX application, with a lot of data, we use Saga and custom REST APIs to pull and show the data. I am seeing Cube.js seems more simple and mature solution helps us not to write tons of custom APIs for every needs.

From the demo, I am seeing that Cube.js use REST API from browser to server, we want to know if any way to cancel the pending calls in SPA Applications.

For example, 

1. User visit page 1
2. Page 1 send few requests to get analytics data
3. Before the page 1 get data, user exit the page by visiting page 2
4. Page 1 data arrived but user no more in same page.
5. We need to cancel the pending calls if the user no more in the same page.

Do you have abstraction with cube.js, where we can plugin libraries like Axios, which support cancellation using tokens or RXJS with unsubscribe?

We use React and Redux with Saga, wondering how Cube.js would cancel pending calls.

Will you look for PR?

**Comment by paveltiunov** [comment]
@gopalakrishnan-subramani Heya! Thanks for posting this! So there're several reasons cancel can be helpful:
1. Ignore orphaned results so they can't affect the state of an app when it comes in.
2. Cancel queries in DB
3. Save traffic/parsing time by closing connections before results come in.

I'm curious which one is your goal?

**Comment by gopalakrishnan-subramani** [comment]
Right now, we are looking for point no. 1. Ignore orphaned results so they can't affect the state of an app and 3. Save Traffic/State issue,  when the data comes later in.

I am not sure whether cube.js backend automatically closes the db connection if requesting connection cancel the call.

Other curious question, do we need to use GraphQL, where GraphQL used? I see that calls to REST server is done via GET method with filters in query string, few proxies/intermitten gateways won't like too big query strings. Do you have consideration taking the queries in post method?

**Comment by paveltiunov** [comment]
@gopalakrishnan-subramani You can use `mutexObj` for that: https://cube.dev/docs/@cubejs-client-core#cubejs-api-load-method. `QueryRenderer` and `useCubeQuery` use it by default.
