### ISSUE TITLE
CubeJs within Express: Auth Handling

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [cube-js/cube.js#610]
We use Cube.js within express js, this application is tightly integrated with keycloak and other identity providers offered by customer customer.

We see that Cube.js needs Token to be passed, we have two questions here.

1. How to configure Cube.js core (within our express js), not to use cube.js token as mandatory one.
2. How to pass the user context for multi tenant nature when we don't use Cube.js tokens

We need User Context is sort of callback within Cube.js, from application side, we could give the callback function, then cube.js can call the function with express req object to get the user context. If none given, Cube.js may use its own way of extracting user context from its token.

**Comment by paveltiunov** [comment]
@gopalakrishnan-subramani You can override token check here: https://cube.dev/docs/@cubejs-backend-server-core#options-reference-check-auth.

**Comment by gopalakrishnan-subramani** [comment]
@paveltiunov Thank you, it did the job.
