### ISSUE TITLE
TypeError: CubejsServerCore.create is not a function

### ISSUE THREAD

**Issue by kAutoman** [cube-js/cube.js#6151]
After upgrading the "@cubejs-backend/server-core": "^0.31.59", 
I am facing some issues with cube js. 
Any idea what’s wrong?

```
CubejsServerCore.create(cubeOptions).initApp(app);
                 ^
TypeError: CubejsServerCore.create is not a function
```

**Comment by ovr** [comment]
Hello!

Embedding Cube.js within Express was deprecated.

https://github.com/cube-js/cube.js/blob/master/DEPRECATION.md#embedding-cubejs-within-express

This method was removed, but you can replace it with `new CubejsServerCore(cubeOptions).initApp(app);` but I highly recommend starting using docker.

Thanks

**Comment by kAutoman** [comment]
Thanks @ovr
