### ISSUE TITLE
timeDimension date filters with no granularity and timezone send utc time in sql where clause

### ISSUE THREAD

**Issue by jhofeditz** [cube-js/cube.js#616]
**Describe the bug**
For timeDimension "yesterday" with timezone "America/Denver", the start and end dateRange is off by 6hrs (the difference between local timezone and UTC). I only use Postgres so I don't know if this issue is specific to Postgres or not.

**To Reproduce**
```
{
  "dimensions": ["createTime"],
  "timeDimensions": [
    {
      "dimension": "createTime",
      // also occurs with relative dates like "yesterday" and "from 3 days ago to now"
      "dateRange": ["2020-04-20","2020-04-21"],
    }
  ],
  "timezone": "America/Denver"
}
```
**Possible solution**
It appears that the timezone is lost in the format here: https://github.com/cube-js/cube.js/blob/master/packages/cubejs-api-gateway/index.js#L231:L232
Adding a Z in the format strings appears to fix the issue for me:
```
              moment.utc(d).format(d.match(DateRegex) ? 'YYYY-MM-DDT00:00:00.000Z' : 'YYYY-MM-DDTHH:mm:ss.SSSZ') :
              moment.utc(d).format(d.match(DateRegex) ? 'YYYY-MM-DDT23:59:59.999Z' : 'YYYY-MM-DDTHH:mm:ss.SSSZ')
```

**Version:**
@cubejs-backend/postgres-driver@0.19.9
@cubejs-backend/query-orchestrator@0.19.9
@cubejs-backend/server@0.19.13
@cubejs-backend/server-core@0.19.13
@cubejs-backend/api-gateway@0.19.5
@cubejs-backend/schema-compiler@0.19.13

**Comment by paveltiunov** [comment]
@jhofeditz Hey Joe! Could you please share data schema, generated SQL and response from cube.js API?

**Comment by jhofeditz** [comment]
schema:
```
cube(`Messages`, {
  sql: `SELECT * FROM public.messages`,
  dimensions: {
    id: {
      sql: `${CUBE}.id`,
      type: `string`,
      primaryKey: true,
      shown: true,
    },
    createTime: {
      sql: SQL_UTILS.convertTz(`${CUBE}. create_time`),
      type: `time`,
    },
 },
});
```
response from /load API
```
{
query: {
dimensions: ["Messages.createTime"],
timeDimensions: [{
dimension: "Slack.tsTime",
dateRange: ["2020-04-20T00:00:00.000","2020-04-23T23:59:59.999"]
}],
timezone: "America/Denver",
},
data: [
{
Messages.createTime: "2020-04-20T16:56:02.000"
}
],
lastRefreshTime: "2020-04-24T23:13:17.991Z",
refreshKeyValues: [
[
{
max: "2020-04-23T01:14:26.645"
}
]
],
usedPreAggregations: { },
annotation: {
measures: { },
dimensions: {
Messages.createTime: {
title: "Messages.createTime",
shortTitle: "Create Time",
type: "time"
}
},
segments: { },
timeDimensions: { }
}
}
```
response from /sql API
```
["SELECT ("messages".create_time::timestamptz AT TIME ZONE 'America/Denver') "messages__create_time" FROM public.messages AS "messages" WHERE (("messages".create_time::timestamptz AT TIME ZONE 'America/Denver') >= $1::timestamptz AND ("messages".create_time::timestamptz AT TIME ZONE 'America/Denver') <= $2::timestamptz) GROUP BY 1 ORDER BY 1 ASC LIMIT 10000",
["2020-04-20T06:00:00Z","2020-04-24T05:59:59Z"]],
```
After my change, the sql values become ["2020-04-20T00:00:00Z","2020-04-23T23:59:59Z"] and the result includes a second row: {Messages.createTime: "2020-04-20T01:08:11.000"},

**Comment by paveltiunov** [comment]
@jhofeditz I believe this one should be fixed already. Feel free to create a new issue if it still persists.
