### ISSUE TITLE
Operator for FILTER_PARAMS Time type in postgres sql direct query does not work expected

### ISSUE THREAD

**Issue by gojumprope** [cube-js/cube.js#6162]
This is my Cube connecting Mysql driver
![image](https://user-images.githubusercontent.com/38604290/218912370-ca450625-9bbf-44b7-8175-0693cc6416ae.png)

My query in cube postgres db 
`select * from table_15_minute
where time >= '2022-01-01 00:00:00' and time < '2022-01-02 00:00:00'`

Auto generated query
`SELECT
    table_15_minute.__time table_15_minute___time,
    table_15_minute.genre table_15_minute___genre,
    count(1) table_15_minute___count
FROM
    (
        select
            t1.genre,
            t2.__time
        FROM
            (
                select
                    1 genre
            ) t1
            cross join (
                select
                    __time
                from
                    table_15_minute tm
                where
                    __time >= TIMESTAMP(
                        convert_tz(
                            '2022-01-01T00:00:00.000',
                            '+00:00',
                            @ @session.time_zone
                        )
                    )
                    AND __time <= TIMESTAMP(
                        convert_tz(
                            '2022-01-02T00:00:00.000',
                            '+00:00',
                            @ @session.time_zone
                        )
                    )
            ) t2
    ) AS table_15_minute
WHERE
    (
        table_15_minute.__time >= TIMESTAMP(
            convert_tz(
                '2022-01-01T00:00:00.000',
                '+00:00',
                @ @session.time_zone
            )
        )
        AND table_15_minute.__time <= TIMESTAMP(
            convert_tz(
                '2022-01-02T00:00:00.000',
                '+00:00',
                @ @session.time_zone
            )
        )
    )
GROUP BY
    1,
    2
ORDER BY
    3 DESC
LIMIT
    50000`

The where operator for time should be (`>=` and `<`) instead of (`>=` and `<=`)

Another Case:
If add one more condition (genre = 1/1 = 1) in the where condition, the operator in auto generated query for time changed to (`>` and `<`)
`select * from table_15_minute
where genre = 1 and time >= '2022-01-01 00:00:00' and time < '2022-01-02 00:00:00'`

Auto generated query:
`SELECT
    table_15_minute.__time table_15_minute___time,
    table_15_minute.genre table_15_minute___genre,
    count(1) table_15_minute___count
FROM
    (
        select
            t1.genre,
            t2.__time
        FROM
            (
                select
                    1 genre
            ) t1
            cross join (
                select
                    __time
                from
                    table_15_minute tm
                where
                    __time > TIMESTAMP(
                        convert_tz(
                            '2022-01-01T00:00:00.000',
                            '+00:00',
                            @ @session.time_zone
                        )
                    )
                    AND __time < TIMESTAMP(
                        convert_tz(
                            '2022-01-02T00:00:00.000',
                            '+00:00',
                            @ @session.time_zone
                        )
                    )
            ) t2
    ) AS table_15_minute
WHERE
    (table_15_minute.genre = '1')
    AND (
        table_15_minute.__time > TIMESTAMP(
            convert_tz(
                '2022-01-01T00:00:00.000',
                '+00:00',
                @ @session.time_zone
            )
        )
    )
    AND (
        table_15_minute.__time < TIMESTAMP(
            convert_tz(
                '2022-01-02T00:00:00.000',
                '+00:00',
                @ @session.time_zone
            )
        )
    )
GROUP BY
    1,
    2
ORDER BY
    3 DESC
LIMIT
    50000`

In this scenario, where operator for time should be (`>=` and `<`) instead of (`>` and `<`)

It is a weird behavior, how can I make the operator for time type to follow my query statement, any suggestion?

**Comment by gojumprope** [comment]
found a temporary solution to make sure data is correct, just cast time as timestamp type in the where condition then auto generated query will minus one milliseconds, and operator will always be `>=` and `<=`
revamped my query below:
`select * from table_15_minute
where  time >= cast('2022-01-01 00:00:00' as timestamp) and time < cast('2022-01-02 00:00:00' as timestamp) `

Auto generated query:
`SELECT
    table_15_minute.__time table_15_minute___time,
    table_15_minute.genre table_15_minute___genre,
    count(1) table_15_minute___count
FROM
    (
        select
            t1.genre,
            t2.__time
        FROM
            (
                select
                    1 genre
            ) t1
            cross join (
                select
                    __time
                from
                    table_15_minute tm
                where
                    __time >= TIMESTAMP(
                        convert_tz(
                            '2022-01-01T00:00:00.000',
                            '+00:00',
                            @ @session.time_zone
                        )
                    )
                    AND __time <= TIMESTAMP(
                        convert_tz(
                            '2022-01-01T23:59:59.999',
                            '+00:00',
                            @ @session.time_zone
                        )
                    )
            ) t2
    ) AS table_15_minute
WHERE
    (
        table_15_minute.__time >= TIMESTAMP(
            convert_tz(
                '2022-01-01T00:00:00.000',
                '+00:00',
                @ @session.time_zone
            )
        )
        AND table_15_minute.__time <= TIMESTAMP(
            convert_tz(
                '2022-01-01T23:59:59.999',
                '+00:00',
                @ @session.time_zone
            )
        )
    )
GROUP BY
    1,
    2
ORDER BY
    3 DESC
LIMIT
    50000`

**Comment by paveltiunov** [comment]
@gojumprope Cube always uses `>=` and `<=` for timestamp comparisons. Please see https://cube.dev/docs/query-format#time-dimensions-format
