### ISSUE TITLE
Pre-aggregation index definition doesn't inherit sqlAlias

### ISSUE THREAD

**Issue by norbertbede** [cube-js/cube.js#618]
**Describe the bug**
When i use sqlAlias to a cube, then columns are inherit prefix, however indexes defined in pre-aggregation not. When Rest request start building pre-aggregation table then create columns but index can't.

**To Reproduce**
1. Create cube (measures, dimensions), including sqlAlias
2. Define pre-aggregation and add index to a column - you will use internal dimension name
3. run request which hit preaggregation 
4. See error - response refer to a not existing column

**Expected behavior**
Consider sqlAlias when index created on column

**Version:**
[v0.19.14]

**Comment by norbertbede** [comment]
xref: https://cube.dev/docs/cube#parameters-sql-alias

**Comment by norbertbede** [comment]
**just catched this example** 

```
  preAggregations: {
    main: {
      type: `rollup`,
      measureReferences: [count],
      dimensionReferences: [Client.ad_client_id, ad_reference_id, ad_ref_list_id, ad_language, listname, refname],
      indexes: {
        ad_user_client_idx: {
          columns: [ad_client_id]
        },
        ad_user_idx: {
          columns: [ad_reference_id]
        },
        ad_user_idx: {
          columns: [ad_ref_list_id]
        }
      }
    }
  }

```

**Creates the next table**
```
CREATE TABLE "pre_aggreg_1000026"."ref_main_b20g3iwu_mpmaelf5_1587852102131" (
"cl__ad_client_id" numeric(10),
"ref__ad_language" varchar(6) COLLATE "default",
"ref__ad_ref_list_id" numeric(10),
"ref__ad_reference_id" numeric(10),
"ref__listname" varchar(60) COLLATE "default",
"ref__refname" varchar(60) COLLATE "default",
"ref__count" int8
)
WITHOUT OIDS;
ALTER TABLE "pre_aggreg_1000026"."ref_main_b20g3iwu_mpmaelf5_1587852102131" OWNER TO "cubejsrole";
```

**Try to generate the next Index**
_CREATE INDEX ref_main_ad_user_client_idx ON pre_aggreg_1000026.ref_main (\"ref__ad_client_id\_

**BUG** 
The table has column cl__ad_client_id however index try to create on column ref__ad_client_id <= ref__ad_client_id doesn't exists !!

**Comment by paveltiunov** [comment]
@norbertbede Hey Norbert! As far as I see you refer `Client.ad_client_id` in dimensions and `ad_client_id` in index which are different columns.
