### ISSUE TITLE
v0.31.63 release failure on x86_64-apple-darwin

### ISSUE THREAD

**Issue by p-linnane** [cube-js/cube.js#6180]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project.

While packaging cubejs-cli v0.31.63 we are encountering a test failure. Upon doing furthur researchs it looks like the release process encountered a failure on x86_64-apple-darwin: https://github.com/cube-js/cube.js/actions/runs/4224729670/jobs/7336065135

Related to https://github.com/Homebrew/homebrew-core/pull/123781

**Comment by ovr** [comment]
Hello @p-linnane ,

Thank you for submitting an issue. There was an issue with latest updates from GitHub.

Fixed and release.

Thanks
