### ISSUE TITLE
cube.js is returning null values as "null" strings at the response (firebolt driver)

### ISSUE THREAD

**Issue by euljr** [cube-js/cube.js#6226]
**Describe the bug**
 cube.js is returning `null` values as `"null"` strings at the response

Probably similar to https://github.com/cube-js/cube.js/issues/1741, but with firebolt.

**To Reproduce**
Not sure how to reproduce it as I only use the client and I don't have a local environment set up, please check screenshot below with an example response, the second expanded data item has a `"null"` in it.

**Expected behavior**
Return `null` instead of `'null'`

**Screenshots**
<img width="497" alt="image" src="https://user-images.githubusercontent.com/6294868/221898016-517f2f09-caa1-4f00-94fd-cc19f6d530b1.png">

**Version:**
[0.31.65]

**Additional context**

We're using firebolt. I believe the [isNumberType](https://github.com/firebolt-db/firebolt-node-sdk/blob/main/src/statement/dataTypes.ts#L99) helper returns `true` when it's nullable as well, so probably the problem is caused by the [getHydratedValue](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-firebolt-driver/src/FireboltDriver.ts#L164) of the FireboltDiver because when returning ``${null}``, it will output `"null"`, but I'm not sure if this is the right place to look.

**Comment by ovr** [comment]
Hello @euljr,

This issue was fixed in [v0.32.6](https://github.com/cube-js/cube.js/releases/tag/v0.32.6). Could you give it a try?

Thank you for submitting for bug reporting!

**Comment by euljr** [comment]
Hello @ovr,

We tested it yesterday, and it's all working fine 🙌 

Thank you so much for the fix!
