### ISSUE TITLE
Feature: metadata with the measure/dimension

### ISSUE THREAD

**Issue by ifokeev** [cube-js/cube.js#625]
**Is your feature request related to a problem? Please describe.**

I have some similar dimensions which want to group by the subsection and create the view for this in the UI.

**Describe the solution you'd like**

It's nice to have the feature when you able to pass some metadata with `cube` attributes in `measures` and `dimensions`. As I see it's not hard to implement, but have a great value.

**Comment by paveltiunov** [comment]
@ifokeev Hey Ivan! Thanks for posting this! I think it's good idea. Do you have any sense on how should it look like?

**Comment by ifokeev** [comment]
@paveltiunov Hey Pavel. It could be just a `metadata` property inside `measure` or `dimension` definition. Then it just raw passes to `/meta` api endpoint response.

**Comment by ifokeev** [comment]
@paveltiunov @vasilev-alex thank you, guys
