### ISSUE TITLE
Sqlite Driver cannot create schema

### ISSUE THREAD

**Issue by tonyd256** [cube-js/cube.js#626]
I'm trying to connect a sqlite3 database but the driver was returning an error:

```
TypeError: Cannot read property '2' of null
    at ./node_modules/@cubejs-backend/sqlite-driver/driver/SqliteDriver.js:63:33
```

1. Create a new project based on the sqlite driver.
2. Create new table in sqlite `CREATE TABLE test (id TEXT PRIMARY KEY, name TEXT NOT NULL);`
3. Launch Cube with `node index.js`.
4. Try to build a new schema for the test table.

I expect that it should be able to create the schema.

**Screenshots**

**Version:**
0.19.14

I was able to make it work by changing the regex matching in the sqlite driver to `      .match(/(\w+)\s(\w+)/);` but I know that's not going to work for every case.

**Comment by paveltiunov** [comment]
@tonyd256 Hey Tony! Thanks for posting this! Yep. I would really appreciate if you can provide PR for that.
