### ISSUE TITLE
Unable to setup snowflake database connection

### ISSUE THREAD

**Issue by vkonapalli** [cube-js/cube.js#6263]
**Describe the bug**

**To Reproduce**
1. Go to 'Cube Cloud'
2. Click on 'Set Up a Database Connection'
3. Click on Snowflake
4. Selct user/password auth
5. Configure credentails, click apply. It throws timeout error.

**Expected behavior**
It should have configured the db connection successfully, as the same credentails works fine for logging into snowflake cloud.

**Screenshots**
[
](![Screen Shot 2023-03-09 at 1 38 24 PM](https://user-images.githubusercontent.com/31501235/223885145-93ad0dcf-f84e-41b8-b097-046311a82241.png))**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

**Version:**
CubeCloud

**Additional context**

**Comment by danielbakas** [comment]
@vkonapalli how did you fix this?
