### ISSUE TITLE
No able to set cubestore as the queue driver

### ISSUE THREAD

**Issue by ifokeev** [cube-js/cube.js#6279]
**Describe the bug**

Joi is not allowing to set `cubestore` as queue driver here https://github.com/cube-js/cube.js/blob/0b72d58fe144d0508e75f826bc7fe0d68a62d2ed/packages/cubejs-server-core/src/core/optionsValidate.ts#L63, but in the Orchestrator types it's possible https://github.com/cube-js/cube.js/blob/master/packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts#L14

Now I'm receiving:
```
Error: Invalid cube-server-core options: "cacheAndQueueDriver" must be one of [redis, memory]
```

**Version:**
0.32.4

**Comment by ovr** [comment]
Hello!

Thank you for submitting an issue! Fixed, it will be released in the upcoming release.
