### ISSUE TITLE
Psql Function calling within cube sql

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [cube-js/cube.js#628]
Our customer projects have tons of psql functions which needs to be invoked with parameters and those functions returns a query which is basically a table structure.

In cube definition, we have sql, where we can plan sql statement, how do we define the dynamic parameters which the values might change time to time based on user selection..

```
cube(`DataReceived`, {
  sql: `SELECT * FROM  myschema.myfunction('city')`,
```

Where as city is dynamic, which can be NY, NJ, Denver etc, which use pick from User Interface. These are pre-existing functions, does complex sql stuffs internally, we just need to use them as is, while passing dynamic parameters. Any suggestion?  We are ok, if we can pass data through filter like approach or additional parameters that comes from request body.

**Comment by paveltiunov** [comment]
Hey @gopalakrishnan-subramani ! Did you have a chance to check https://cube.dev/docs/cube#context-variables-filter-params?
