### ISSUE TITLE
Hive Driver: Cannot read property 'execute' of undefined

### ISSUE THREAD

**Issue by parked-toes** [cube-js/cube.js#6281]
**Describe the bug**
I'm connecting Cube.js to Spark SQL (Thrift server) using Hive driver. The connection works OK. In the playground\schema\tables, I can list all tables.
Executing any query leads to the following error:

> Error: Cannot read properties of undefined (reading 'execute')
>     at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:434:13)
>     at QueryQueue.executeQueryInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:411:19)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at /cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:736:17
>     at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:292:20)
>     at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:98:20)
>     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1561:21
>     at async Promise.all (index 0)
>     at ApiGateway.getSqlResponseInternal (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1559:31)
>     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1735:28
>     at async Promise.all (index 0)
>     at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1726:23)
>     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:244:7

After a quick debugging I found a cause. The following `HiveDriver` method expects 3rd parameter to be a connection object:
```javascript
async query(query, values, conn) {
  values = values || [];
  const sql = SqlString.format(query, values);
  const connection = conn || await this.pool.acquire();
  ...
```

But It gets a request object when called from `QueryCache` :
```javascript
return client.query(req.query, req.values, req);
```

After removing `conn || ` part it works again.

**Version:**
[0.32.4]

**Comment by ovr** [comment]
Hello @parked-toes,

Thank you for submitting the issue!

> The following HiveDriver method expects 3rd parameter to be a connection object:

It's right, but the problem comes from what it receives. We declare in the `DriverInterface` (that the 3rd param is options),  but `hive-driver` uses `conn` as workaround for passing the connect without storing It in a pool from `testConnection` method.

Fix was merged and released in https://github.com/cube-js/cube.js/releases/tag/v0.32.5

Thanks
