### ISSUE TITLE
Error: Cannot find module './locale'

### ISSUE THREAD

**Issue by TariqAHassan** [cube-js/cube.js#629]
**Describe the bug**

A `Cannot find module './locale'` error appears when following [Cube.js, the Open Source Dashboard Framework: Ultimate Guide](https://cube.dev/blog/cubejs-open-source-dashboard-framework-ultimate-guide/)

**To Reproduce**

Follow all of the steps in [Cube.js, the Open Source Dashboard Framework: Ultimate Guide](https://cube.dev/blog/cubejs-open-source-dashboard-framework-ultimate-guide/) exactly.

**Expected behavior**

Simple dashboard to appear.

**Screenshots**
N/A

**Version:**

* Node: v12.16.3
* CubeJS: 0.19.0

**Additional context**
N/A

---

Edit:

May be related to https://github.com/moment/moment/issues/5484

**Comment by CKKnot** [comment]
1. cd into dashboard-app
2. npm install moment@2.24.0
3. npm uninstall moment
4. Done

Refer to https://stackoverflow.com/a/61556856

**Comment by NathanChannon** [comment]
I also have an open ticket for this. If you're able to use Yarn, then using package.json "resolutions" is your way out.

If you're using npm, then you can use this [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) to accomplish the same result, but beware you must reference momentjs in the dependencies if you weren't already.

**Comment by paveltiunov** [comment]
@TariqAHassan Hey Tariq! It seems new version of moment has been shipped. Could you please try it and let us know if it's fixed for you?

**Comment by TariqAHassan** [comment]
@paveltiunov 

Sorry for the delay. 
Yes, this appears to be resolved now.

Thanks!
