### ISSUE TITLE
Redis still listed as requirement for docker deployment

### ISSUE THREAD

**Issue by cndev123** [cube-js/cube.js#6302]
Redis still listed as a requirement for docker deployment on this page: https://cube.dev/docs/deployment/platforms/docker#configuration

Is this legacy info or is redis still required? If not how does a docker deployment without redis look like?

**Comment by ovr** [comment]
Hello @cndev123 ,

Oops! We need to remove it. Good catch! 

Thanks

cC @hassankhan @keydunov
