### ISSUE TITLE
useCubeQuery requires a dimension to work

### ISSUE THREAD

**Issue by MarkLyck** [cube-js/cube.js#634]
**Describe the bug**
useCubeQuery from @cubejs-client/react throws an error "cannot read property "split" of undefined" when you give it a query with either no dimensions or an empty array for dimensions.

**To Reproduce**
1. Make query with no dimension,
2. pass query to useCubeQuery like this:

`const renderProps = query ? useCubeQuery(query, { subscribe: true }) : {};`

observe error.

**Expected behavior**
Should query fine just like it does when you make a manual request.

**Version:**
"@cubejs-client/core": "^0.17.10",
"@cubejs-client/react": "^0.17.10",
"@cubejs-client/ws-transport": "^0.17.10",

**Additional context**
I was forced to add a meaningless dimension to my query that I don't need, to get it to work.
My measure gives me all the data I want.

**Comment by MarkLyck** [comment]
Also. happens on lates version 0.19.16

**Comment by paveltiunov** [comment]
Hey @MarkLyck ! Thanks for posting this! Interesting. Could you please check 0.19.15?

**Comment by paveltiunov** [comment]
@MarkLyck BTW hook can't be under conditional statement like ternary operator or `if`. You should see react warnings about that. Could you please also share full stack trace?

**Comment by MarkLyck** [comment]
Turns out it was a Presto error in our multitenacy code, and not from useCubeQuery.

My bad.
