### ISSUE TITLE
Querying empty Postgres table with 'time' dimension in a cube results in null value passed to moment.range() fn when the cube's preAggregation.partitionGranularity is enabled

### ISSUE THREAD

**Issue by SamShiSS** [cube-js/cube.js#639]
**Describe the bug**
See title.
The error originates from the `timeSeries` fn in BaseTimeDimension.ts, which is called by `refreshQueriesForPreAggregation` during scheduled refresh. The following error message can be found in the console:
`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.`

Note: if there is at least one row in the table, then the error disappears

**To Reproduce**
1. Set up a backend using cubejs server and Postgres
2. Create a cube with its sql pointing to an empty table in Postgres
3. Enable the preAggregation in the cube's options, and enable the partitionGranularity attribute in preAggregation's options
4. Set up cubeServer.runScheduledRefresh() to execute at any time interval (preferably shorter like 30 seconds so that you can see the error message sooner, but not too short)
5. Set up the cubeLogger option for the cubejs server to log cubejs's events in the console
6. Run the backend server with Postgres
7. See error message in the console during scheduled refresh

**Expected behavior**
No error in the logs even if there is no rows in the table

**Version:**
@cubejs-backend/server: 0.19.18
@cubejs-backend/postgres-driver: 0.19.17,
postgres: 12

**Comment by paveltiunov** [comment]
@SamShiSS Thanks for posting this! Yeah. Seems this case isn't handled properly.
