### ISSUE TITLE
Postgres Schema Generation - Spinning

### ISSUE THREAD

**Issue by swamichandra** [cube-js/cube.js#649]
I have Postgres running on my Mac locally (installed via Brew). Can connect to psql, create DB's, set use password etc. Here is my .env file and can launch a cube's project. But when I open the Cube --> Schema, I see the hourglass spinning continuously and no errors in the console/logs either. Also the '+' icon is grayed out for both Tables and Files. Pleas help.

```
CUBEJS_DB_HOST=localhost
CUBEJS_DB_NAME=cubejs
CUBEJS_DB_USER=xxx
CUBEJS_DB_PASS=xxx
CUBEJS_DB_PORT=5432
CUBEJS_WEB_SOCKETS=true
CUBEJS_DB_TYPE=postgres
CUBEJS_API_SECRET=DEFAULT GENERATED 128-char
```

**Comment by vasilev-alex** [comment]
Hi! Which `node` version are you using? There's a known issue that has been fixed https://github.com/brianc/node-postgres/issues/2180

**Comment by rpaik** [comment]
I'll go ahead and close this issue. @swamichandra if you have further questions, please let us know. 🙇
