### ISSUE TITLE
Dashboard app breaking with graphql-tools v6.0.0

### ISSUE THREAD

**Issue by nodeworks** [cube-js/cube.js#661]
**Describe the bug**
Following the guide here: https://react-dashboard.cube.dev/overview-and-analytics-backend

When I start the dashboard app, I get an error:
`TypeError: Cannot read property 'native' of undefined`

(screenshot below)

If I downgrade graphql-tools to ^5.0.0 it works fine. Seems to be an issue with the new 6.0.0 that was recently released.

**To Reproduce**
Follow this guide: https://react-dashboard.cube.dev/overview-and-analytics-backend

**Expected behavior**
Expected the app to compile properly.

**Screenshots**
![Screen Shot 2020-05-24 at 5 48 57 PM](https://user-images.githubusercontent.com/5272855/82780419-174b2280-9e25-11ea-882a-ebf4580b4d95.png)
**Version:**
dashboard-app: 0.1.0

**Additional context**
Node version 12.8.0, but also fails with any version

**Comment by vincebeck** [comment]
I'm experiencing the exact same bug with node v12.16.3. 
I couldn't make it work with graphql-tools v5.x.x either.

![image](https://user-images.githubusercontent.com/51480342/82809243-f36ef780-9e8b-11ea-8d39-05bcad192b6c.png)
