### ISSUE TITLE
Support time dimension without granularity

### ISSUE THREAD

**Issue by gauravlanjekar** [cube-js/cube.js#662]
**Is your feature request related to a problem? Please describe.**
Currently if you do not provide granularity to the time dimension it is not added on the query. 
This makes it impossible to render a line chart on raw data. This is really helpful in realtime scenarios. Wherein the data is not grouped at all and rawdata is rendered as charts. 

**Describe the solution you'd like**
Would like to have the possiblity to render charts on ungrouped time data. 

**Describe alternatives you've considered**
Tried using the time as an additional dimension but then the result pivot does not work as anticipated

**Comment by paveltiunov** [comment]
@gauravlanjekar Hey Gaurav! Thanks for posting this! Have you tried to use time dimension in `dimensions`?
Like:
```
{
  measures: ['Some.count'],
  dimensions: ['Some.time']
}
```

**Comment by gauravlanjekar** [comment]
@paveltiunov  ended up doing something like this 
```
{
             
              dimensions: ['Some.dim', 'Some.time'],
              order: {
                'Some.dim': 'desc',
              },
              limit: 500,
              ungrouped: true,
            }
```
With this i do get ungroupped results. This is what I would expect to get back when I have a time dimension without granularity and I can then also use the interval feature of the time dimension and so on.
