### ISSUE TITLE
No drillMembers docs

### ISSUE THREAD

**Issue by krystian50** [cube-js/cube.js#680]
**Is your feature request related to a problem? Please describe.**
Hi, I want to create drill-down table. Basically table like: 

![image](https://user-images.githubusercontent.com/19366440/83352586-dc794b00-a34c-11ea-852a-01a59621c49e.png)

**Describe the solution you'd like**
There is no proper documentation for that
**Describe alternatives you've considered**
Pls, add information what is actual result od drillMembers. Also pls let me know if it's useful in my case :).

**Comment by paveltiunov** [comment]
@krystian50 We're working on that in this issue: #190. cc @vasilev-alex

**Comment by vasilev-alex** [comment]
Hi, @krystian50! 

I've update the docs here https://cube.dev/docs/@cubejs-client-core#result-set-drill-down and created a simple example on codesandbox https://codesandbox.io/s/nostalgic-moore-wk3ev where you can get the idea on how to use the `drillDown` method.

Hope that helps.
