### ISSUE TITLE
MSSQL Joins involving sub-queries

### ISSUE THREAD

**Issue by JoshMentzer** [cube-js/cube.js#686]
**Describe the bug**
When a dimension uses another cube's field, and that dimension is used as part of a relationship to a 3rd cube, the order of the joins in the resulting SQL statement is important.  If the 3rd cube is joined first, multi-part identifier errors will occur as the alias does not yet exist according to the SQL interpreter.

**To Reproduce**
1. Create cube 'A' with a join to a 2nd cube 'B', 'belongsTo' relationship
2. Create a dimension in 'A' with a 'case' attribute which uses fields from 'B' cube in the sql of 'when' clauses 
3. Create cube 'C', in cube 'A' add a relationship to 'C' which uses the dimension from step 2
4. Resulting SQL query, is set up like so:

> `FROM cubeA as cubeAAlias

> LEFT JOIN cubeC as cubeCAlias on CASE when cubeBAlias.field = 'someValue' THEN 'CaseResult' END = cubeCalias.field

> LEFT JOIN cubeB as cubeBAlias ON cubeAAlias.id = cubeBAlias.fk_id`

Result is Error: The multi-part identifer "cubeBalias.field" could not be bound.

**Expected behavior**
The joins should be ordered such that aliases are defined before being used.  If a 'sub-query' in a dimension uses a future join alias definition, that join should come after the alias is defined.  The resulting query above will run without errors if the two joins are 'swapped' in order.

**Comment by paveltiunov** [comment]
@JoshMentzer Hey Joshua! Could you please share your data schema?

**Comment by JoshMentzer** [comment]
Was able to work around the issue by moving some of the 'case' dimensions between cubes.
