### ISSUE TITLE
Timezone conversion gets applied twice if SQL_UTILS.convertTz() is used on time dimensions

### ISSUE THREAD

**Issue by cd-romulus** [cube-js/cube.js#689]
**Describe the bug**
In queries with time zone the time zone gets applied twice, if a dimension of type 'time' that uses SQL_UTILS.convertTc() is used in the `timeDimensions` field of the query. (For postgres backends) this leads to an 'over compensation' of the time difference and yields wrong time values.

**To Reproduce**
1. Create a cube like this:

```js
cube(`MyCube`, {
    sql: `SELECT now() as ts`,
      measures:{
        one:{
            sql: '1',
            type: 'number'
        }
    },
    dimensions:{
        timestamp:{
            sql: SQL_UTILS.convertTz(`${CUBE}.ts`),
            type: 'time'
        }
    }
})
```

2. Load the following query

```json
{
  "measures":["MyCube.one"],
  "dimensions":["MyCube.timestamp"],
  "timeDimensions":[{
     "dimension":"MyCube.timestamp",
     "granularity":"hour"
  }],
  "timezone":"Europe/Berlin"
}
```

3. The data result of `MyCube.timestamp.hour` will be in the future

```json
"data": [
        {
            "MyCube.timestamp": "2020-06-04T13:45:42.322",
            "MyCube.timestamp.hour": "2020-06-04T15:00:00.000",
            "MyCube.one": 1
        }
    ]
```
The generated sql is

```sql
SELECT
      ("my_cube".ts::timestamptz AT TIME ZONE 'Europe/Berlin') "my_cube__timestamp",
       date_trunc('hour', (("my_cube".ts::timestamptz AT TIME ZONE 'Europe/Berlin')::timestamptz AT TIME ZONE 'Europe/Berlin')) "my_cube__timestamp_hour", 1 "my_cube__one"
    FROM
      (SELECT now() as ts) AS "my_cube"
  GROUP BY 1, 2 ORDER BY 1 ASC LIMIT 10000
```

The timestamp conversion is applied both before and after date_trunc.

**Expected behavior**
MyCube.timestamp and MyCube.timestamp.hour should have the same hour.

**Version:**
@cubejs-backend/postgres-driver: 0.19.20,
@cubejs-backend/server: 0.19.23,
Postgres: 11

**Workaround**
A workaround is to add an additional time dimension that does *not* use SQL_UTILS.convertTz(). Then use this for the timeDimensions field of the query. A hint in the docs might be helpful.

**Comment by paveltiunov** [comment]
Hey @cd-romulus ! It's a tricky one. I'd say `SQL_UTILS.convertTz()` wasn't intended to be used in time dimensions. Could you please elaborate on your use case: why do you need to select `hour` time dimensions and this exact dimension in same query? Would just `second` granularity work for you?

**Comment by JeffreyPalmer** [comment]
I was also confused by this behavior, and didn't realize that convertTz was not really intended for time dimensions. Perhaps a dedicated section in the documentation on how CubeJs handles timezones with respect to pre-aggregations, automated timezone conversion, etc. would be helpful.

**Comment by cd-romulus** [comment]
Thanks for getting back @paveltiunov! Selecting the same `time` dimension twice was just to illustrate the discrepancy more clearly. The issue is still present if we don't query `MyCube.timestamp` as a normal dimension. In particular, `second` granularity would not resolve it: the unintended time offset would still be generated. In my understanding using `SQL_UTILS.convertTz()` fields in `timeDimensions` introduces errors to the result set that are fairly hard to spot. 

Would it make sense to simply strip the `SQL_UTILS.convertTz()` whenever the respective field is used as a time dimension?

That said, I believe that the real bug is actually in the database backend (here postgres) because I would expect the timestamp to stay the same no matter how often I cast it to the same time zone.

I think the best cube.js could do quickly is to clearly point out this problem and the workaround in the docs.

**Comment by cd-romulus** [comment]
(on the use case and why we started using `SQL_UTILS.convertTz()` in the first place when obviously we don't need it for `timeDimensions`: we also query ungrouped data and want the timezone to be accurate in this case)

**Comment by paveltiunov** [comment]
@cd-romulus I see. Could you please share your ungrouped query?

**Comment by cd-romulus** [comment]
@paveltiunov honestly I don't quite remember our original query but I don't think it will be very helpful without the data. Instead I crafted an example that will hopefully be more illustrative.

Consider the following cube
```js
cube(`MyCube`, {
    sql: `SELECT * FROM (VALUES 
            ( 1, '2020-06-06 00:02:01'::timestamp, 0, 2),
            ( 2, '2020-06-06 00:02:02'::timestamp, 0, 2),
            ( 3, '2020-06-06 01:03:01'::timestamp, 1, 3),
            ( 4, '2020-06-06 01:03:02'::timestamp, 1, 3),
            ( 5, '2020-06-06 01:03:03'::timestamp, 1, 3),
            ( 6, '2020-06-06 02:04:01'::timestamp, 2, 4),
            ( 7,' 2020-06-06 02:04:02'::timestamp, 2, 4),
            ( 8, '2020-06-06 02:04:03'::timestamp, 2, 4),
            ( 9, '2020-06-06 02:04:04'::timestamp, 2, 4),
            (10, '2020-06-06 03:05:01'::timestamp, 3, 5),
            (11, '2020-06-06 03:05:02'::timestamp, 3, 5),
            (12, '2020-06-06 03:05:03'::timestamp, 3, 5),
            (13, '2020-06-06 03:05:04'::timestamp, 3, 5),
            (14, '2020-06-06 03:05:05'::timestamp, 3, 5),
            (15, '2020-06-06 04:06:01'::timestamp, 4, 6),
            (16, '2020-06-06 04:06:02'::timestamp, 4, 6),
            (17, '2020-06-06 04:06:03'::timestamp, 4, 6),
            (18, '2020-06-06 04:06:04'::timestamp, 4, 6),
            (19, '2020-06-06 04:06:05'::timestamp, 4, 6),
            (20, '2020-06-06 04:06:06'::timestamp, 4, 6)       
        ) as t(id,ts,utc_hour,cest_hour)`,

    measures:{
        count:{
            type: 'count'
        }
    },
    dimensions:{
        id:{
            sql:'id',
            type:'number',
            primaryKey: true,
            shown:true
        },
        timestamp:{
            sql: `${CUBE}.ts`,
            type: 'time'
        },
        timestampTz:{
            sql: SQL_UTILS.convertTz(`${CUBE}.ts`),
            type: 'time'
        },
        utc_hour:{
            sql: 'utc_hour',
            type: 'number'
        },
        cest_hour:{
            sql: 'cest_hour',
            type: 'number'
        }
    }
})
```
The hardcoded data contain an id as primary key, a timestamp (without time zone), the hour of the timestamp at UTC and the hour of the timestamp at CEST (i.e. at time zone 'Europe/Berlin'). Additionally, the minute of each timestamp is set to be identical to the CEST hour.
Notably, the number of rows that have a certain CEST hour is chosen to correspond to the CEST hour itself.

The cube implements two different time dimensions `timestamp`, which is unmodified, and `timestampTz`, which explicitly applies the time zone conversion.

Now, consider the following queries:

1. Ungrouped query of all *raw* data rows:

```json
{"dimensions":["MyCube.id","MyCube.timestampTz","MyCube.utc_hour","MyCube.cest_hour"],
"ungrouped":true,"timezone":"Europe/Berlin"}
```

The result is perfectly fine and exactly, what we expect:

```json
 "data": [
        {
            "MyCube.id": 1,
            "MyCube.timestampTz": "2020-06-06T02:02:01.000",
            "MyCube.utc_hour": 0,
            "MyCube.cest_hour": 2
        },
        {
            "MyCube.id": 2,
            "MyCube.timestampTz": "2020-06-06T02:02:02.000",
            "MyCube.utc_hour": 0,
            "MyCube.cest_hour": 2
        },
        {
            "MyCube.id": 3,
            "MyCube.timestampTz": "2020-06-06T03:03:01.000",
            "MyCube.utc_hour": 1,
            "MyCube.cest_hour": 3
        },
        ...
```

2. Ungrouped query of a subset of rows, where the timestamp at time zone 'Europe/Berlin' is *between 4 and 6 in the morning*

```json
{"dimensions":["MyCube.id","MyCube.timestampTz","MyCube.utc_hour","MyCube.cest_hour"],
"timeDimensions":[{
  "dimension":"MyCube.timestampTz",
  "granularity": null, 
  "dateRange": ["2020-06-06 04:00:00.000", "2020-06-06 06:00:00.000"]}],
"ungrouped":true,
"timezone":"Europe/Berlin"}
```

The result we get looks like this:

```json
    "data": [
        {
            "MyCube.id": 1,
            "MyCube.timestampTz": "2020-06-06T02:02:01.000",
            "MyCube.utc_hour": 0,
            "MyCube.cest_hour": 2
        },
        {
            "MyCube.id": 2,
            "MyCube.timestampTz": "2020-06-06T02:02:02.000",
            "MyCube.utc_hour": 0,
            "MyCube.cest_hour": 2
        },
        {
            "MyCube.id": 3,
            "MyCube.timestampTz": "2020-06-06T03:03:01.000",
            "MyCube.utc_hour": 1,
            "MyCube.cest_hour": 3
        },
        {
            "MyCube.id": 4,
            "MyCube.timestampTz": "2020-06-06T03:03:02.000",
            "MyCube.utc_hour": 1,
            "MyCube.cest_hour": 3
        },
        {
            "MyCube.id": 5,
            "MyCube.timestampTz": "2020-06-06T03:03:03.000",
            "MyCube.utc_hour": 1,
            "MyCube.cest_hour": 3
        }
    ],
```
While the data in itself is still consistent, we obviously got the wrong time range, i.e. between 2 and 4 in the morning. The reason becomes clear if we change the `granularity` from `null` to `hour`, which makes cubejs output the date_trunc result:

```json
      {
            "MyCube.id": 1,
            "MyCube.timestampTz": "2020-06-06T02:02:01.000",
            "MyCube.utc_hour": 0,
            "MyCube.cest_hour": 2,
            "MyCube.timestampTz.hour": "2020-06-06T04:00:00.000"
        },...
```
Since the time zone conversion was applied twice, our filter boundaries were compared to wrong time values.

Finally let's look at a grouped query:

3. Count the number of rows we have for each hour at time zone 'Europe/Berlin'

```json
query={"measures":["MyCube.count"],
"timeDimensions":[{"dimension":"MyCube.timestampTz","granularity":"hour"}],
"timezone":"Europe/Berlin"}
```
As a result we get:

```json
 "data": [
        {
            "MyCube.timestampTz.hour": "2020-06-06T04:00:00.000",
            "MyCube.timestampTz": "2020-06-06T04:00:00.000",
            "MyCube.count": "2"
        },
        {
            "MyCube.timestampTz.hour": "2020-06-06T05:00:00.000",
            "MyCube.timestampTz": "2020-06-06T05:00:00.000",
            "MyCube.count": "3"
        },
        {
            "MyCube.timestampTz.hour": "2020-06-06T06:00:00.000",
            "MyCube.timestampTz": "2020-06-06T06:00:00.000",
            "MyCube.count": "4"
        },
        {
            "MyCube.timestampTz.hour": "2020-06-06T07:00:00.000",
            "MyCube.timestampTz": "2020-06-06T07:00:00.000",
            "MyCube.count": "5"
        },
        {
            "MyCube.timestampTz.hour": "2020-06-06T08:00:00.000",
            "MyCube.timestampTz": "2020-06-06T08:00:00.000",
            "MyCube.count": "6"
        }
```
For our carefully crafted dataset, we know that `MyCube.count` should equal the hour at time zone 'Europe/Berlin'. Obviously, in the result set this is not the case and the count differs from the hour by 2, i.e. the time difference between the CEST and UTC. *We actually retrieved wrong results* and I think it would be hard to notice if this were a real dataset.

Of course, the mistake is not cube.js'. The mistake is that I have used the already converted timestamp in the `timeDimensions` field. 

Everything becomes fine, once we change the query to

```json
query={"measures":["MyCube.count"],
"timeDimensions":[{"dimension":"MyCube.timestamp","granularity":"hour"}],
"timezone":"Europe/Berlin"}
```
and we get

```json
"data": [
        {
            "MyCube.timestamp.hour": "2020-06-06T02:00:00.000",
            "MyCube.timestamp": "2020-06-06T02:00:00.000",
            "MyCube.count": "2"
        },
        {
            "MyCube.timestamp.hour": "2020-06-06T03:00:00.000",
            "MyCube.timestamp": "2020-06-06T03:00:00.000",
            "MyCube.count": "3"
        },
        {
            "MyCube.timestamp.hour": "2020-06-06T04:00:00.000",
            "MyCube.timestamp": "2020-06-06T04:00:00.000",
            "MyCube.count": "4"
        },
        {
            "MyCube.timestamp.hour": "2020-06-06T05:00:00.000",
            "MyCube.timestamp": "2020-06-06T05:00:00.000",
            "MyCube.count": "5"
        },
        {
            "MyCube.timestamp.hour": "2020-06-06T06:00:00.000",
            "MyCube.timestamp": "2020-06-06T06:00:00.000",
            "MyCube.count": "6"
        }
    ]
```

In the case of the query under 2. I find this a little less obvious, because here we have to actually use two different timestamp fields in a single query, that both refer to the same raw data:

```json
{"dimensions":["MyCube.id","MyCube.timestampTz","MyCube.utc_hour","MyCube.cest_hour"],
"timeDimensions":[{"dimension":"MyCube.timestamp","granularity":null, "dateRange": ["2020-06-06 04:00:00.000", "2020-06-06 06:00:00.000"]}],
"ungrouped":true,"timezone":"Europe/Berlin"}
```

(I realize that this is a veeery long response, so thanks to anyone who actually read it. May it be useful.)

**Comment by paveltiunov** [comment]
@cd-romulus Makes sense. To sum up what was your initial expectation here? Is it `timestamp` field selected as `timeDimension` with some granularity in `ungrouped` query should be returned in requested client time zone?

**Comment by cd-romulus** [comment]
@paveltiunov My initial expectation was that the `timestamp` field when requested as `dimension` would be returned in the requested time zone. Or that the un-truncated `timestamp` field selected as `timeDimension` is returned in `ungrouped` queries.

**Comment by paveltiunov** [comment]
@cd-romulus Makes sense. I'd suggest to return `timeDimensions` in requested timezone for `ungrouped` queries as a solution. Would it solve your issue?

**Comment by cd-romulus** [comment]
@paveltiunov Yes, i think that would be a good solution. Thank you!
