### ISSUE TITLE
Auth0 authorization

### ISSUE THREAD

**Issue by krystian50** [cube-js/cube.js#704]
Hi, I recently removed CUBEJS_TOKEN authorization and added custom auth0 security. I think it can be a good idea to provide docs about such feature. Many people is ussing auth0. It's easy to go and secure. My code below: (the solution is based on auth0 official docs)
```
require('dotenv').config();
const http = require('http');
const express = require('express');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const session = require('express-session');
const CubejsServerCore = require('@cubejs-backend/server-core');
const jwt = require('express-jwt');
const jwksRsa = require('jwks-rsa');

// Set up Auth0 configuration
const authConfig = {
  domain: '',
  audience: '',
};

const app = express();
app.use(require('cors')());
app.use(cookieParser());
app.use(bodyParser.json({ limit: '50mb' }));
app.use(session({ secret: process.env.CUBEJS_API_SECRET }));

const checkJwt = jwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: `https://${authConfig.domain}/.well-known/jwks.json`,
  }),

  audience: authConfig.audience,
  issuer: `https://${authConfig.domain}/`,
  algorithm: ['RS256'],
});

app.use(checkJwt);

const serverCore = CubejsServerCore.create({
  checkAuth: (req, auth) => {
    if (!req.user) {
      throw new Error(`Unauthorized`);
    }
    req.authInfo = { u: req.user };
  },
});

serverCore.initApp(app);

const port = process.env.PORT || 4000;
const server = http.createServer(app);

server.listen(port, (err) => {
  if (err) {
    console.error('Fatal error during server start: ');
    console.error(e.stack || e);
  }
  console.log(
    `🚀 Cube.js server (${CubejsServerCore.version()}) is listening on ${port}`,
  );
});

```

**Comment by paveltiunov** [comment]
Hey @krystian50! I think it's really great idea to add it to security doc. Also we'd love if you can write a small blog post about it where you describe how to setup it step by step.

**Comment by krystian50** [comment]
@paveltiunov, I can write a blog post. Where should I post it? I saw you have your own blog. Should I create a pull request with MD file? Like for eg. https://github.com/cube-js/cube.js/blob/62aaddefa58400b48cae35ebfbbfc92ccdb0a0c7/guides/react-dashboard/content/1_overview_and_analytics_backend.md

**Comment by paveltiunov** [comment]
@krystian50 Could you please contact me in https://slack.cube.dev/? I'll intro you to our dev rel team. Thanks!

**Comment by krystian50** [comment]
@paveltiunov I did. I'm waiting for response on priv msg.

**Comment by CMD-V** [comment]
Has this been posted anywhere yet? Having issues with my app.js set up for auth0.

**Comment by davemaier** [comment]
Hi, I've just implemented auth0 authorization for a project of mine. 
I wanted to mention that since `checkJwt` is an express middleware and `CubejsServerCore` options accept a `checkAuthMiddleware` property, it might be better to pass `checkJwt` to `CubejsServerCore` directly. This approach also works when using `CubejsServer` and requires no fiddling around with the express app. 

```const checkJwt = jwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: `https://${authConfig.domain}/.well-known/jwks.json`,
  }),
  audience: authConfig.audience,
  issuer: `https://${authConfig.domain}/`,
  algorithms: ['RS256'],
});

const server = new CubejsServer({checkAuthMiddleware: checkJwt});```

**Comment by hassankhan** [comment]
Closing this as we now have first-class support for Auth0: https://cube.dev/docs/security/jwt/auth0
