### ISSUE TITLE
Fix a typo in a code snippet in the "Ultimate Guide" blog post

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#721]
**Describe the bug**

See the "[Cube.js, the Open Source Dashboard Framework: Ultimate Guide](https://cube.dev/blog/cubejs-open-source-dashboard-framework-ultimate-guide/)" blog post. It has the following code snippet:

<img width="605" alt="Screenshot 2020-06-12 at 21 24 58" src="https://user-images.githubusercontent.com/3852894/84534753-2ff77b80-acf3-11ea-9bdf-c6883b5e12c1.png">

The React app is created in the `dashboard-frontend` folder but the snippet suggests that a user should navigate to the `cubejs-dashboard` folder.

**To Reproduce**

**Expected behavior**

The snippet should contain the following command:

`$ cd dashboard-frontend`

**Screenshots**

**Version:**

**Additional context**

**Comment by paveltiunov** [comment]
@igorlukanin Hey Igor! Thanks for posting this! Nice catch!

**Comment by igorlukanin** [comment]
Fixed. Kudos to @hassankhan for reminding about this!
