### ISSUE TITLE
Allow HTTP POST for query

### ISSUE THREAD

**Issue by magno32** [cube-js/cube.js#723]
**Is your feature request related to a problem? Please describe.**

Node limits (by default) max header size to 8k.  This also affects the size of the query string when using GET.  This can be alleviated by setting the `--max-http-header-size=<something larger>` flag
when running server, and is a decent work around for development.

However, API Gateway on AWS is not configurable like this.  So, if the query string is too long, the request will never even make it through the API Endpoint.  I suspect that anywhere a user wants to host CubeJS, this will be a problem.

**Describe the solution you'd like**

A supported API call to `POST` the query to the server.  This may violate the purpose of using `GET` from a REST perspective, but I don't know another way around it, since hosting provider configuration will often be outside of our control.

**Describe alternatives you've considered**

As a work-around, I have changed the Lambda deployment (serverless.yml) to use a custom mapping.  I `POST` the query to API Gateway as the body:

```json
{
    "query": "..."
}
```

I then map that query from the body to the expected `queryStringParameters` block expected from Lambda Passthrough:

#### proxy_request.vsl
```velocity
#set($allParams = $input.params())
{
    "http_method": "$context.httpMethod",
    "source_ip" : "$context.identity.sourceIp",
    "user-agent" : "$context.identity.userAgent",
    "stage" : "$context.stage",
    #set($req_body = $util.parseJson($input.body))
    #set($requestParams = $allParams.get('querystring'))
    "queryStringParameters":{
        ## Request body
        #foreach($q in $req_body.keySet())
        "$q":"$util.escapeJavaScript($req_body.get($q))"#if($foreach.hasNext),#end
        #end
        #foreach($q in $requestParams.keySet())
            "$q":"$util.escapeJavaScript($requestParams.get($q))"#if($foreach.hasNext),#end
        #end
    },
    "resource":"/{proxy+}",
    "path":"/$input.params('proxy')",
    "pathParameters": {
        "proxy": "$input.params('proxy')"
    },
"headers": {
#set($params = $allParams.get('header'))
#foreach($paramName in $params.keySet())
    "$paramName" : "$params.get($paramName)"#if($foreach.hasNext),#end
#end
}
}
```
You also need a response template, since the lambda was originally using passthrough:

#### proxy_response.vsl
```velocity
#set($inputRoot = $input.path('$'))
$input.path('$.body')
#set($context.responseOverride.status = $inputRoot.get('statusCode'))
#set($headers = $inputRoot.get('headers'))
#foreach($header in $headers.keySet())
    #set($context.responseOverride.header[$header] = $headers.get($header))
#end

```

**Additional context**

The workaround above has the benefit of allowing the context path to be different (i.e. when using custom domains from API Gateway).  This should probably be in the documentation somewhere, as it appears that Express is expecting all of the calls to be based off the root `/` context path.

#### See:
```velocity
    "resource":"/{proxy+}",
    "path":"/$input.params('proxy')",
    "pathParameters": {
        "proxy": "$input.params('proxy')"
    }
```

However,  when running the CubeJS dev server, I have to `GET` the request, and in production I have to `POST`.

**Comment by RusovDmitriy** [comment]
Hey everyone, catch PR))

Maybe don't need worry about canonicity REST API? Cube.JS is more of a service with use-cases, while REST spinning around resourses. It seems you can safely remove REST prefix)) 

I added:
 - POST handler for /load route
 - Example into docs REST-API.md
