### ISSUE TITLE
Error while loading DB schema - Invalid object name 'information_schema.columns'

### ISSUE THREAD

**Issue by sazarag** [cube-js/cube.js#728]
When trying to connect an MSSQL DB, an error has occurred like that.

used MSSQL driver version like that:
 
"dependencies": {
    "@cubejs-backend/mongobi-driver": "^0.19.17",
    "@cubejs-backend/mssql-driver": "^0.19.17",
    "@cubejs-backend/server": "^0.19.17"
  }
   
Bug Log:

Error while loading DB schema
RequestError: Invalid object name 'information_schema.columns'. at handleError (C:\XXX\node_modules\mssql\lib\tedious\request.js:366:15) at Connection.emit (events.js:182:13) at Parser.tokenStreamParser.on.token (C:\XXX\node_modules\tedious\lib\connection.js:832:12) at Parser.emit (events.js:182:13) at Parser.parser.on.token (C:\XXX\node_modules\tedious\lib\token\token-stream-parser.js:37:14) at Parser.emit (events.js:182:13) at addChunk (C:\XXX\node_modules\readable-stream\lib\_stream_readable.js:298:12) at readableAddChunk (C:\XXX\node_modules\readable-stream\lib\_stream_readable.js:280:11) at Parser.Readable.push (C:\XXX\node_modules\readable-stream\lib\_stream_readable.js:241:10) at Parser.Transform.push (C:\XXX\node_modules\readable-stream\lib\_stream_transform.js:139:32)

**Comment by paveltiunov** [comment]
Hey @sazarag ! We have a PR for this here #226 . Would love if you can pick it up.
