### ISSUE TITLE
Reverse Engineering Cubes from SQL queries

### ISSUE THREAD

**Issue by gokulanv** [cube-js/cube.js#731]
**Is your feature request related to a problem? Please describe.**
I want to migrate an application from a PHP server to Nodejs+Cube architecture. I have many SQL queries in the legacy app. Rewriting that as Cubes would take a lot of time. So just like you convert Cubes to SQL, would it be possible to convert SQL to Cubes?

**Describe the solution you'd like**
Given SQL queries, generate cubes automatically.

**Describe alternatives you've considered**

**Additional context**
This is mainly for migration purposes.

**Comment by paveltiunov** [comment]
@gokulanv Hey Gokulan! Thanks for posting this! We're working on this one. It'll be available as part of Cube Cloud https://cube.dev/#cube-cloud.
