### ISSUE TITLE
CubeJS result removes timezone

### ISSUE THREAD

**Issue by krystian50** [cube-js/cube.js#752]
**Describe the bug**
CubeJS removes information about timezone from result data

**To Reproduce**
1. Create CubeJS schema
2. Use postgressDB
3. Create CubeJS query with timeDimensions set to :
```
{
  measures: ['RefundLines.amount', 'RefundLines.amountPrice'],
  timeDimensions: [
    {
      dimension: 'Refunds.refundDate',
      granularity: 'hour',
      dateRange: ['2020-06-08T22:00:00.000Z', '2020-06-09T21:59:59.999Z'],
// or: dateRange: ['Tue Jun 23 2020 00:00:00 GMT+0200 (Central European Summer Time)', 'Tue Jun 23 2020 00:00:00 GMT+0200 (Central European Summer Time)'], 
    },
  ],
}
```

**Expected behavior**
CubeJS result will respect Zulu Timezone and return proper data set with time set to `${date}Z`

**Actual behavior**
The result is:
![image](https://user-images.githubusercontent.com/19366440/85607148-1b50a700-b654-11ea-82e6-bce31552273e.png)

The timeDimensions.dateRange is clearly without timezone. Browser recognize it as a local timezone date and format (in my case) with CEST timezone. 
The same goes for data objects.

What is more, I'm living in CEST timezone and by "2020-06-22T22:00:00.000" - "2020-06-23T21:59:59.999" I want to force cubeJS to show data for the whole day (start and end day). When timezone is not respected, it divides data on two days:
![image](https://user-images.githubusercontent.com/19366440/85608219-25bf7080-b655-11ea-91c5-840fb74aa8a5.png)

There's also walk around. You can simply set timezone property in the query (in my case "Europe/Warsaw").

**Version:**
   "@cubejs-client/core": "^0.19.23",
    "@cubejs-client/react": "^0.19.23",
    "@cubejs-backend/postgres-driver": "0.19.17",
    "@cubejs-backend/server": "0.19.21",

**Comment by krystian50** [comment]
Also, it looks like the actual data is wrong, because of timeshift.

**Comment by jhofeditz** [comment]
@krystian50 This sounds like the same problem that I identified in #616. I also noticed the filters returning incorrect results because of the timezone difference. I would be interested to know if the workaround I posted helps your issue as well.

**Comment by the5thbeatle** [comment]
@krystian50 I think I've run into the same problem. I've handled it by adding a query transformer that takes each date in the `timeDimensions` and replaces it with `moment.tz(date, query.timezone).format()`. In the response of the Cube server, the `query` `timeDimensions` are correct and still include the offset. The dates in the `data` objects don't include the offset, but they are the correct local times for the timezone I used. That just means I have to localize the times in `data` and I don't have a query for one day being split into two days. For example:

```
{
    "query": {
        ...,
        "timeDimensions": [{
            "granularity": "day",
            "dateRange": ["2020-06-01T00:00:00-0700", "2020-06-01T23:59:59-0700"],
            "dimension": "Cube.time"
        }]
    },
    "data": [{
        ...,
        "Cube.time": "2020-06-01T00:00:00"
    }]
}
```

**Comment by vasilev-alex** [comment]
I took a closer look at the problem and it does seem to behave properly. 

Cube.js always returns data in the timezone specified for the query (`UTC` by default) and doesn't really make sense to duplicate this information for each date in the data object.

But if you use the data to draw charts you should consider passing in your local timezone to avoid conversion (which you already do), and also in this case you're not gonna need to manually calculate the timeshift for date ranges.

As for dividing data into two dates, this should not happen and I'm not able to reproduce this behavior on the latest version. Is that possible that you try it again?

Сlosing the issue now, but if you have any concerns feel free to reopen it.
