### ISSUE TITLE
9999 data result limit

### ISSUE THREAD

**Issue by lanceschi** [cube-js/cube.js#762]
**Describe the bug**
If I query a long period of time with a lower granularity (minute), I'm hitting 9999 data result limit

**To Reproduce**
Query a big enough database by a long period of time with a lower granularity (minute or second)

**Expected behavior**
Possibility to set the result upper limit

**Version:**
@cubejs-backend/mongobi-driver: `^0.19.17`
@cubejs-backend/server-core: `^0.19.33`

**Additional context**
I'd developing a frequency distribution chart, hence the lower granularity. I'm creating data buckets programmatically after fetched data arrive in the front-end.

A better approach would have been to have the possibility to bucket query the DBase like in [MongoDB][1]

As a workaround I thought about devising separate pre-defined count bucket measures/series as described [here][2].

Any advice appreciated

Thanks in advance

[1]: https://docs.mongodb.com/manual/reference/operator/aggregation/bucket/
[2]: https://stackoverflow.com/questions/6669730/sql-query-that-groups-different-items-into-buckets#answer-6670110

**Comment by paveltiunov** [comment]
@lanceschi Hey Luca! Did you have a chance to check `limit` query param? https://cube.dev/docs/query-format#query-properties

**Comment by lanceschi** [comment]
Hi @paveltiunov , sorry, I totally missed that one. My bad.
