### ISSUE TITLE
Allow specifying Pre-Aggregation table name: support `sqlAlias` for pre-aggregations

### ISSUE THREAD

**Issue by magno32** [cube-js/cube.js#764]
**Is your feature request related to a problem? Please describe.**
Postgres likes to truncate descriptive table names.  I'm sure this is an issue in other database.

**Describe the solution you'd like**
It would be nice to be able specify Pre aggregation table names.  This could happen either in the pre-agg definition, or possibly
even a function passed on server creation.  We would obviously need reference to the context information, such as the partition, when doing this.

**Describe alternatives you've considered**
I am having to get inventive while naming pre-aggregations in the schema, even then it is difficult since all of the prefix information is put on the table name as well.

**Comment by paveltiunov** [comment]
@magno32 Hey Justin! Did you have a chance to check this option: https://cube.dev/docs/cube#parameters-sql-alias?

**Comment by magno32** [comment]
I had not used that yet, but is there a similar option for
pre_aggregations? If not, it would be equally helpful.

**Comment by paveltiunov** [comment]
@magno32 It actually affects pre-aggregation table names as well. However I believe it would be helpful to support the same property on pre-aggregation level. Let's use this issue to track it.

**Comment by hassankhan** [comment]
Closing as `sqlAlias` can now be specified on pre-aggregation definitions: https://cube.dev/docs/pre-aggregations#naming

**Comment by benswinburne** [comment]
> Closing as `sqlAlias` can now be specified on pre-aggregation definitions: [cube.dev/docs/pre-aggregations#naming](https://cube.dev/docs/pre-aggregations#naming)

@hassankhan this no longer appears to be described in the pre-aggregations docs

**Comment by benswinburne** [comment]
Having also just tried to actually use this I got the below using  `image: cubejs/cube:v0.29.5-alpine`

```
cube_1      | TypeError: Cannot create property 'type' on string 'myalias'
cube_1      |     at CubeSymbols.transformPreAggregations (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:124:28)
cube_1      |     at CubeSymbols.transform (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:107:12)
cube_1      |     at /cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:33:34
cube_1      |     at _map (/cube/node_modules/ramda/src/internal/_map.js:7:19)
cube_1      |     at map (/cube/node_modules/ramda/src/map.js:83:14)
cube_1      |     at /cube/node_modules/ramda/src/internal/_dispatchable.js:50:15
cube_1      |     at /cube/node_modules/ramda/src/internal/_curry2.js:26:18
cube_1      |     at f1 (/cube/node_modules/ramda/src/internal/_curry1.js:19:17)
cube_1      |     at /cube/node_modules/ramda/src/internal/_pipe.js:3:27
cube_1      |     at /cube/node_modules/ramda/src/internal/_arity.js:11:19
cube_1      |     at CubeSymbols.compile (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:35:6)
cube_1      |     at /cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:37:56
```
