### ISSUE TITLE
Return pre-agg status on repeated calls to `run-scheduled-refresh`

### ISSUE THREAD

**Issue by magno32** [cube-js/cube.js#765]
**Is your feature request related to a problem? Please describe.**
To get the status of a running operation, we can repeat the rest-api call.  Typically this returns `{'error':'continue-wait'}`

If we query the cube, and a required pre-agg is rendering, we get the pre-aggregation status, e.g. 
`response={error=Continue wait, stage={stage=Building pre-aggregation 1/12: #1 in queue}})`

However, if the call is to `run-scheduled-refresh` we don't get this status.  For dev-ops purposes, it would be nice to get the stage information as well.

**Describe the solution you'd like**
Return stage information in the `run-scheduled-refresh` api call.

**Comment by paveltiunov** [comment]
@magno32 Thanks for posting this one! Could you please elaborate a little bit on your use case? Do you want to get info about all the stages from all pre-aggregations at once? How do you want to use this info?

**Comment by magno32** [comment]
It seems that getting info on the execution status would be useful.

For instance, I'm tracking the duration of the pre-aggregation in splunk.
This happens by pinging the endpoint every 5 seconds while it is running.
I know when it starts, and how long it takes.

It would be helpful to get status information back as well, to see which
pre-aggregations take how long to run.

**Comment by paveltiunov** [comment]
@magno32 Gotcha. This info is available in logs already and it's a better way to get it for DevOps purpose. Refresh Scheduler can provide just partial info in this case unfortunately.
