### ISSUE TITLE
scheduledRefreshTimer.match is not a function

### ISSUE THREAD

**Issue by buffcode** [cube-js/cube.js#772]
**Describe the bug**
According to the [TS definition](https://github.com/cube-js/cube.js/blob/b396b05d6128a8864840d9225043053c68c64581/packages/cubejs-server-core/core/index.d.ts#L33) and [docs](https://github.com/cube-js/cube.js/blob/6d0096e945c7f9d3822a657c1e0920a46d37cdf5/docs/Cube.js-Backend/%40cubejs-backend-server-core.md#options-reference), `scheduledRefreshTimer` is of type `Boolean | number`.

With the latest version there is a new check to validate the string to contain only digits, while neither `Boolean` nor `number` implement `match`.

**To Reproduce**
```js
const CubejsServer = require('@cubejs-backend/server');
const server = new CubejsServer({
  scheduledRefreshTimer: true
});
```

```
TypeError: this.scheduledRefreshTimer.match is not a function
    at new CubejsServerCore (node_modules/@cubejs-backend/server-core/core/index.js:230:86)
    at Function.create (node_modules/@cubejs-backend/server-core/core/index.js:358:12)
    at new CubejsServer (node_modules/@cubejs-backend/server/index.js:11:34)
```

**Expected behavior**
No BC break when implementing new checks.

**Version:**
`@cubejs-backend/server-core@0.19.40`

**Additional context**
- Suspected commit: https://github.com/cube-js/cube.js/commit/6d0096e945c7f9d3822a657c1e0920a46d37cdf5#diff-49fd186d45485663b0e641a0214512e2R230
- [TS definition](https://github.com/cube-js/cube.js/blob/b396b05d6128a8864840d9225043053c68c64581/packages/cubejs-server-core/core/index.d.ts#L33)
- [Docs](https://github.com/cube-js/cube.js/blob/6d0096e945c7f9d3822a657c1e0920a46d37cdf5/docs/Cube.js-Backend/%40cubejs-backend-server-core.md#options-reference)

**Comment by paveltiunov** [comment]
@buffcode Thanks for heads up! Should be fixed right now. Could you please check!
