### ISSUE TITLE
Adjust Cube.js Client to support the Fetch API 'credentials' option

### ISSUE THREAD

**Issue by colefichter** [cube-js/cube.js#788]
**Is your feature request related to a problem? Please describe.**
The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) supports a `credentials` option to control the session cookies sent along with a request. By adjusting the Cube.js Client to support this option, we will be able to route our cube queries through a different sub-domain.

For example. If your site is running at `secure.mydomain.com` and your API calls need to go to `api.mydomain.com` it can be handy to pass the cookies over in the cross-domain API call. In order to support such a request pattern, the cube client must allow us to set `credentials: 'include'` when calling `fetch()`.

**Describe the solution you'd like**
Here is a patch that I think gets us the behaviour that we need, but I can't test it as the yarn build tools are not working for me yet and I don't have permission to push a branch anyhow:

[0001-Adjust-fetch-to-allow-users-to-pass-credentials-opti.patch.zip](https://github.com/cube-js/cube.js/files/4870606/0001-Adjust-fetch-to-allow-users-to-pass-credentials-opti.patch.zip)

**Describe alternatives you've considered**
Only writing our own client code, which is not ideal.

**Comment by colefichter** [comment]
Here is the patch that github won't let me attach:


From 63f65cc65a49d74c97399a8b71dedc3c0f73b6c6 Mon Sep 17 00:00:00 2001
From: Cole Fichter <REDACTED>
Date: Fri, 3 Jul 2020 09:53:25 -0600
Subject: [PATCH] Adjust fetch() to allow users to pass credentials option into
 browser API call.

---
 packages/cubejs-client-core/index.d.ts           |  4 +++-
 packages/cubejs-client-core/src/HttpTransport.js | 16 +++++++++-------
 packages/cubejs-client-core/src/index.js         |  4 +++-
 3 files changed, 15 insertions(+), 9 deletions(-)

diff --git a/packages/cubejs-client-core/index.d.ts b/packages/cubejs-client-core/index.d.ts
index b83ae50f..820ae623 100644
--- a/packages/cubejs-client-core/index.d.ts
+++ b/packages/cubejs-client-core/index.d.ts
@@ -21,6 +21,7 @@ declare module '@cubejs-client/core' {
      * custom headers
      */
     headers?: Record<string, string>;
+    credentials: 'omit' | 'same-origin' | 'include';
   };
 
   export interface ITransport {
@@ -47,6 +48,7 @@ declare module '@cubejs-client/core' {
     transport?: ITransport;
     headers?: Record<string, string>;
     pollInterval?: number;
+    credentials: 'omit' | 'same-origin' | 'include';
   };
 
   export type LoadMethodOptions = {
@@ -646,7 +648,7 @@ declare module '@cubejs-client/core' {
 
   /**
    * Main class for accessing Cube.js API
-   * 
+   *
    * @order 2
    */
   export class CubejsApi {
diff --git a/packages/cubejs-client-core/src/HttpTransport.js b/packages/cubejs-client-core/src/HttpTransport.js
index ec44191a..189829ac 100644
--- a/packages/cubejs-client-core/src/HttpTransport.js
+++ b/packages/cubejs-client-core/src/HttpTransport.js
@@ -2,10 +2,11 @@ import fetch from 'cross-fetch';
 import 'url-search-params-polyfill';
 
 class HttpTransport {
-  constructor({ authorization, apiUrl, headers = {} }) {
+  constructor({ authorization, apiUrl, headers = {}, credentials = 'same-origin' }) {
     this.authorization = authorization;
     this.apiUrl = apiUrl;
     this.headers = headers;
+    this.credentials = credentials;
   }
 
   request(method, { baseRequestId, ...params }) {
@@ -21,12 +22,13 @@ class HttpTransport {
     // remember to add a 'Content-Type' header.
     const runRequest = () => fetch(
       `${this.apiUrl}/${method}${searchParams.toString().length ? `?${searchParams}` : ''}`, {
-        headers: {
-          Authorization: this.authorization,
-          'x-request-id': baseRequestId && `${baseRequestId}-span-${spanCounter++}`,
-          ...this.headers
-        }
-      }
+      headers: {
+        Authorization: this.authorization,
+        'x-request-id': baseRequestId && `${baseRequestId}-span-${spanCounter++}`,
+        ...this.headers
+      },
+      credentials: this.credentials
+    }
     );
 
     return {
diff --git a/packages/cubejs-client-core/src/index.js b/packages/cubejs-client-core/src/index.js
index d3e39c6b..06f4476e 100644
--- a/packages/cubejs-client-core/src/index.js
+++ b/packages/cubejs-client-core/src/index.js
@@ -25,10 +25,12 @@ class CubejsApi {
     this.apiToken = apiToken;
     this.apiUrl = options.apiUrl || API_URL;
     this.headers = options.headers || {};
+    this.credentials = options.credentials || 'same-origin';
     this.transport = options.transport || new HttpTransport({
       authorization: typeof apiToken === 'function' ? undefined : apiToken,
       apiUrl: this.apiUrl,
-      headers: this.headers
+      headers: this.headers,
+      credentials: this.credentials
     });
     this.pollInterval = options.pollInterval || 5;
     this.parseDateMeasures = options.parseDateMeasures;
-- 
2.25.0

**Comment by paveltiunov** [comment]
@colefichter Hey Cole! Thanks for posting this! Could you please try to fork our repository and push to your own branch? Then you can create a PR in main cube.js repo.

**Comment by colefichter** [comment]
@paveltiunov Ok, hopefully this works correctly: https://github.com/cube-js/cube.js/pull/790
