### ISSUE TITLE
Typescript: Cannot import TimeDimensionGranularities enum from @cubejs-client/core/index.d.ts

### ISSUE THREAD

**Issue by sigtot** [cube-js/cube.js#807]
**Describe the bug**
Trying to import and use the `TimeDimensionGranularities` enum (e.g. using `.DAY`) defined in `/packages/cubejs-client-core/index.d.ts` in a node application yields the following runtime error:
```
TypeError: Cannot read property 'DAY' of undefined
    at myFunc (...)
    at Object.lambdaHandler (...)
    at [eval]:1:27
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_string.js:23:3 undefined undefined
```
Apparently, it happens because declaration files like `index.d.ts` are not compiled to js, causing a runtime error if e.g. enums defined there are used. No errors appear during compile time. 

**To Reproduce**
1. Create a simple node application
2. Import `TimeDimensionGranularities` from `@cubejs-client/core`
3. Do something with it, e.g. `console.log(TimeDimenstionGranularities.DAY)`
4. See runtime error

**Expected behavior**
No runtime error appears.

**Version:**
[0.19.47]

**Comment by vasilev-alex** [comment]
Hi @sigtot! Thanks for posting this one

We need to replace it with a string-literal union type.

**Comment by sigtot** [comment]
Wow that was fast. Thanks!
