### ISSUE TITLE
Property 'loadResponse' does not exist on type 'ResultSet<any>'

### ISSUE THREAD

**Issue by yossi-dy** [cube-js/cube.js#828]
**Describe the bug**
When trying to compile any code that attempts to read this property.

**To Reproduce**
Try this (code taken from docs):
```
import cubejs, { ResultSet } from '@cubejs-client/core';

const cubejsApi = cubejs('CUBEJS_TOKEN');

const resultSet = await cubejsApi.load({
 measures: ['Stories.count'],
 timeDimensions: [{
   dimension: 'Stories.time',
   dateRange: ['2015-01-01', '2015-12-31'],
   granularity: 'month'
  }]
});

const copy = new ResultSet(resultSet.loadResponse);
```
https://cube.dev/docs/@cubejs-client-core#result-set

**Expected behavior**
'ResultSet' class to retain the 'loadResponse' property.

**Version:**
After 0.19.35

**Additional context**
Appears like it was removed in this commit:
https://github.com/cube-js/cube.js/commit/c5b26d062affd7740e713e80048e4dadbcc366fd?diff=unified#diff-3cc1dfd973da00761dd52753cadd56c4
(Line 171 in `packages/cubejs-client-core/index.d.ts`)

**Comment by vasilev-alex** [comment]
hey @yossi-dy! You should better use `serialize`/`deserialize`. More info here https://cube.dev/docs/@cubejs-client-core#result-set-deserialize

**Comment by jd2rogers2** [comment]
but what if we're not putting our data on a graph? i'm also having this issue and serialize doesn't apply to me.
@vasilev-alex what about `rawData()`? that with passing in the type to `useCubeQuery`, like below, seems to appease TS, do you think this is a good solution?
`  const { resultSet } = useCubeQuery<ResultType>({`

**Comment by yossi-dy** [comment]
I haven't had a chance review @vasilev-alex 's suggestion yet, but it does seem to require some changes in methodology from how we do it in our application.
In our setup, reading the data from the cube and passing data to the charting mechanism are completely decoupled, with quite a lot of transformations done in the middle, so I do appreciate the idea of having the ability to handle the data in its rawest form, as close to the source as possible.
`loadResponse` allows me to do that.
With this change in the type definitions - which until now I considered as a simple error in the definitions, and not as an intentional change - we might need to refactor our code  or `@ts-ignore` them temporary - which is never a good solution.

**Comment by paveltiunov** [comment]
@yossi-dy do you access `loadResponse` to extract data and metadata?

**Comment by yossi-dy** [comment]
@paveltiunov correct. I extract both.

**Comment by paveltiunov** [comment]
@yossi-dy Gotcha. We'll provide API for meta on `ResultSet`. `loadResponse` field however will remain internal to `ResultSet` implementation for now. cc @vasilev-alex
