### ISSUE TITLE
Query Builder and Query Renderer for Angular

### ISSUE THREAD

**Issue by Vbboi24** [cube-js/cube.js#832]
**Is your feature request related to a problem? Please describe.**
I have been trying to get hold of the cube js and one thing i realized was that i couldnt find Query Render

**Describe the solution you'd like**
Similar to @cubejs-client/vue and @cubejs-client/react, It would be great if @cubejs-client/ngx can also have cube native components for Query Builder and Query Renderer

**Describe alternatives you've considered**
I have planned to build my own custom query builder, ( eg. Angular Query Builder ). Then, Build the Cube Query to render the same

**Additional context**

**Comment by vasilev-alex** [comment]
hi @Vbboi24! Thanks for posting it here. It is actually on our roadmap.

**Comment by vasilev-alex** [comment]
Closed by #1073
