### ISSUE TITLE
ER_TOO_LONG_IDENT error when using pre-aggreations in MySQL

### ISSUE THREAD

**Issue by gizmodus** [cube-js/cube.js#86]
**Describe the bug**
As discussed with @paveltiunov: I get the following error when using pre-aggregations with MySQL:
ER_TOO_LONG_IDENT: Identifier name 'xxxxxxxx_xxxxxxxxxxxxxxxxx_category_and_date_grxbl5i2_qpwevmo0_1555596567123' is too long

**To Reproduce**
Define a pre-aggregation in the cube.js schema with a long name.

**Version:**
0.4.5

**Comment by paveltiunov** [comment]
Hey Reto! Thanks for posting this! MySQL is very restrictive in terms of table name length. First of all I think we can replace integer timestamp with string version.
Here's the place that parses timestamp:
https://github.com/statsbotco/cube.js/blob/50f1bbb7aac34ae7c4fd82a86ecee8506b17f4ea/packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js#L40
Here's the place that generates table names:
https://github.com/statsbotco/cube.js/blob/50f1bbb7aac34ae7c4fd82a86ecee8506b17f4ea/packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js#L255

**Comment by gizmodus** [comment]
@paveltiunov What do you mean with string version of the timestamp? Like date + time, e.g. "201904231718". This would save 2 characters 😃

**Comment by paveltiunov** [comment]
@gizmodus Hey Reto! I mean we can use for example the same base32 encoding we use for hash.

**Comment by beefs** [comment]
What about having a table to store the mapping of the tables?

**Comment by paveltiunov** [comment]
@beefs Hey Sunny! Great question! Cube.js was designed to minimize requirements for target DB in terms of pre-aggregations and one of design decision was not to store metadata in DB itself due to many big data backends doesn't support consistent transactional inserts/updates.

**Comment by lihan** [comment]
This issue happens on Postgres too, the table names are truncated and will not work.
