### ISSUE TITLE
cubejs-client/ngx to support Angular 9 and 10

### ISSUE THREAD

**Issue by tanvi-cota** [cube-js/cube.js#864]
I want to upgrade my angular app to Angular 10, but cubejs-client/ngx client does not let me. Gives the below error -
`
Package "@cubejs-client/ngx" has an incompatible peer dependency to "@angular/core" (requires "^6.1.0 || ^7.0.0 || ^8.0.0" (extended), would install "10.0.4").`

**Comment by vasilev-alex** [comment]
this should be closed by https://github.com/cube-js/cube.js/pull/887 

@tanvi-cota can you check out the latest version?
