### ISSUE TITLE
404: Files Not Found

### ISSUE THREAD

**Issue by sanjanathinks** [cube-js/cube.js#867]
While using Cube.js with an Angular front-end, I keep running into a 'Failed to load resource: the server responded with a status of 404 (Not Found)' with regards to the queries I have called.
<img width="966" alt="404" src="https://user-images.githubusercontent.com/43222065/87861647-2f678b80-c916-11ea-9727-0a7674674b29.png">

I'd like to know which files I'm missing, and how I can resolve this issue. How would I be able to connect to the Cube.js backend port?

**Comment by vasilev-alex** [comment]
Hi @sanjanathinks! Looks like you have a redundant slash in the `apiUrl` (`http://localhost:4200//cubejs-api/v1`). Could you please fix it and see if that helps?

**Comment by sanjanathinks** [comment]
Thank you for reaching out, Alex!
I tried fixing the url, but ended up with the same error again. Attached is the updated url.
<img width="967" alt="updated_url" src="https://user-images.githubusercontent.com/43222065/87951556-b7fd3d80-ca76-11ea-8ef0-bc7327b2f9d3.png">

**Comment by vasilev-alex** [comment]
By default the base path is `/cubejs-api`. I believe, in your case it should be reachable at `http://localhost:4200/cubejs-api/v1`

**Comment by sanjanathinks** [comment]
I changed the path to `http://localhost:4200/cubejs-api/v1`, but ended up getting the same error. Could you double check that I have the path named correctly?
<img width="964" alt="retry cubejs-api:v1" src="https://user-images.githubusercontent.com/43222065/87960543-72df0880-ca82-11ea-9c47-7c102a3473bb.png">

**Comment by vasilev-alex** [comment]
Looks fine now. Can you hit the `http://localhost:4200/cubejs-api/v1/meta` endpoint and see if that responds correctly? Otherwise there's something wrong with your server config. You can also post it here.

**Comment by sanjanathinks** [comment]
How would I be able to hit the endpoint? Do I have to change the path?

**Comment by sanjanathinks** [comment]
Could you please let me know how to find the endpoint as soon as possible?
Looking forward to using Cube.js in my project.

**Comment by vasilev-alex** [comment]
Did you manage to get the server up and running? If you configured everything correctly, you can try to open `http://localhost:4200/cubejs-api/v1/meta` in your browser and see if it gives you a valid response

**Comment by sanjanathinks** [comment]
How can I get the server to run? 
I did try opening up `http://localhost:4200/cubejs-api/v1/meta`in my browser, but still got loading circles, and not the data itself.

**Comment by sanjanathinks** [comment]
Hi, any updates regarding this issue? As I've said, I'd really like to use the Cube.js framework in my project and I'm working on a strict deadline. Please respond as soon as possible.
I appreciate all of your help!

**Comment by vasilev-alex** [comment]
@sanjanathinks this doesn't look like an Angular specific issue but it's rather a matter of configuring and running Cube.js server. I suggest that you check out our getting started page https://cube.dev/docs/getting-started

**Comment by sanjanathinks** [comment]
When I input `this.data` into Cube.js client, I keep getting the following error.
<img width="424" alt="data_error" src="https://user-images.githubusercontent.com/43222065/89053628-86f9f400-d325-11ea-8190-acb1a751da71.png">

Where should I declare the data from?
