### ISSUE TITLE
Error while loading DB schema Error: Server does not support secure connnection at ClientHandshake.handshakeInit

### ISSUE THREAD

**Issue by sazarag** [cube-js/cube.js#869]
SSL connection is disabled at the server which is ready to connect MongoDB. I try to connect at the client and get an error like image.

![image](https://user-images.githubusercontent.com/4058541/87926575-8f7f3e80-ca8a-11ea-98ee-84a7c7e0d5cb.png)

Config at yml file:
mongodb:
  net:
    uri: "mongodb://127.0.0.1:27017" # https://docs.mongodb.com/manual/reference/connection-string/#mongodb-uri
    ssl:
      enabled: false
security:
  enabled: true
net:
  bindIp: "127.0.0.1,10.**.**.99" # To bind to multiple IP addresses, enter a list of comma separated values.
  port: 3307
  ssl:
    mode: "disabled"

The pure connection has to be active without error message

v0.19.43

**Comment by vasilev-alex** [comment]
hi @sazarag! Could you please check out this guide https://cube.dev/docs/connecting-to-the-database#notes-mongo-db and see if that helps?

**Comment by vasilev-alex** [comment]
Looks like you're trying to connect to MongoDB directly. You should have the connector for BI in place https://docs.mongodb.com/bi-connector/master/. 

Please find more info here https://cube.dev/blog/building-mongodb-dashboard-using-node.js and let me know if that's what you need.
