### ISSUE TITLE
Pre-aggregation partitioning on daily level not working on Aurora

### ISSUE THREAD

**Issue by tobilg** [cube-js/cube.js#871]
**Describe the bug**

We see the following error when using Athena cubes with Aurora MySQL pre-aggregations:

```javascript
{
	"message": "Dropping Cache",
	"cacheKey": [
		"SELECT CASE\n    WHEN NOW() < CAST(? as TIMESTAMP) + interval '1' day THEN FLOOR(to_unixtime(NOW()) / 3600) END",
		[
			"2020-06-20T23:59:59Z"
		]
	],
	"error": "Error: GENERIC_USER_ERROR: Value cannot be cast to timestamp: 2020-06-20T23:59:59Z\n    at QueryQueue.parseResult (/var/task/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:99:13)\n    at QueryQueue.executeInQueue (/var/task/node_modules/@cubejs-backend/query-orchestrator/orchestrator/QueryQueue.js:88:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async PreAggregationLoadCache.keyQueryResult (/var/task/node_modules/@cubejs-backend/query-orchestrator/orchestrator/PreAggregations.js:118:68)\n    at async Promise.all (index 0)\n    at async PreAggregationLoader.loadPreAggregationWithKeys (/var/task/node_modules/@cubejs-backend/query-orchestrator/orchestrator/PreAggregations.js:225:30)\n    at async OrchestratorApi.executeQuery (/var/task/node_modules/@cubejs-backend/server-core/core/OrchestratorApi.js:32:20)\n    at async ApiGateway.load (/var/task/node_modules/@cubejs-backend/api-gateway/index.js:422:24)\n    at async /var/task/node_modules/@cubejs-backend/api-gateway/index.js:286:7",
	"requestId": "9ae61853-1e3e-40ba-a3ef-aef270ff9b9e"
}
```

This yields end user errors, and the queries are not successful. We suspect that the query generation return incorrect SQL for Aurora MySQL.

**To Reproduce**
Our pre-aggregation definition is the following:

```javascript
  preAggregations: {
    main: {
      type: `rollup`,
      measureReferences: [
         /* omitted */
      ],
      dimensionReferences: [
        /* omitted */
      ],
      timeDimensionReference: PageViewsNew.eventDate,
      granularity: `hour`,
      partitionGranularity: `day`,
      refreshKey: {
        every: `1 hour`,
        incremental: true,
        updateWindow: `1 day`
      },
      external: true,
      scheduledRefresh: true
    }
  }
```

**Expected behavior**
Pre-aggregations with partitioning should work.

**Version:**
latest

**Comment by paveltiunov** [comment]
@tobilg Hey Tobi! What version of MySQL do you use? I believe it runs in strict mode however I'm not sure if Aurora will allow you to override it. Strict mode MySQL isn't supported as a target for external rollups as of now.

**Comment by tobilg** [comment]
Currently we're using v5.6, but we could switch to v5.7 if necessary. 

Regarding limitations etc. please refer to https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations

**Comment by tobilg** [comment]
I also tested the generated SQL in a Docker container with v8.0, and it yielded the same error. IMO it could be the case that the SQL generation produces incorrect SQLs for the daily partitions.

**Comment by paveltiunov** [comment]
@tobilg Right now only MySQL 5.7 with `--sql-mode=ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION` option is throughly tested as MySQL external pre-aggregation db.

**Comment by tobilg** [comment]
@paveltiunov thanks for the fast feedback. I think the SQL generation could be changed to be working in broader settings TBH. From an operations perspective, we'd strongly prefer to have a fully managed db instead of running one ourselves with custom settings. 

Granularity daily with partitionGranularity monthly works with my current setup, only if I change it to hourly/daily I receive the above SQL error. As said, it doesn't seem to work as well with ootb MySQL v8.

**Comment by paveltiunov** [comment]
@tobilg Yep. Agree! We're open to this sort of contribution however it isn't on our road map as of right now. If you need managed Cube.js compatible external pre-aggregation databases as part of your Cube.js deployment you may want to try out https://cube.dev/#cube-cloud.

**Comment by tobilg** [comment]
@paveltiunov Could you eventually point me to the code location? I could imagine creating a PR on that... Thanks!

**Comment by tobilg** [comment]
Seems rather to be an Athena problem, and the same issue as https://github.com/cube-js/cube.js/issues/404

**Comment by paveltiunov** [comment]
@tobilg Ah. Yep. Right. This refresh key evaluated on Athena side rather than in MySQL.
