### ISSUE TITLE
Group by Custom field: string measure support

### ISSUE THREAD

**Issue by gokulanv** [cube-js/cube.js#874]
**Is your feature request related to a problem? Please describe.**
A simpler version of the query that I would like to write in Cube.Js is :
SELECT
	con.id,
	GROUP_CONCAT(t.title) FROM Contacts con LEFT JOIN Titles t on con.titleid = t.id;

Where I need to group only by con.id

**Describe the solution you'd like**
SELECT
	con.id,
	GROUP_CONCAT(t.title) FROM Contacts con LEFT JOIN Titles t on con.titleid = t.id **GROUP BY con.id**;

**Additional context**

The query generated by Cube Js is:
SELECT
	con.id,
	GROUP_CONCAT(t.title) FROM Contacts con LEFT JOIN Titles t on con.titleid = t.id **GROUP BY 1, 2**;
This gives an erroneous output

**Comment by paveltiunov** [comment]
@gokulanv Hey Gokulan! Right now it can be achieved by introducing string measure
```
cube(`Con`, {
  // ...,
  measures: {
    concat: {
      sql: `GROUP_CONCAT(${CUBE}.title)`,
      type: `number`
    }
  }
})
```

There's no dedicated string measure type as of right now. There's an issue for it: #260.
