### ISSUE TITLE
Question: Is it possible to exclude the userContext filters while building pre-aggregations?

### ISSUE THREAD

**Issue by tobilg** [cube-js/cube.js#882]
I have a cube which uses UserContext and a filter on the userId, and want to employ pre-aggregations to speed up pthe query results. I now saw in the SQL generated that the filter is applied on read of the base cube, meaning that it will generate the pre-aggregations on userId level, which is not what I want.

I saw https://cube.dev/docs/multitenancy-setup#user-context-vs-query-transformer and as far as I understand, the usage of `queryTransformer` (https://cube.dev/docs/multitenancy-setup#same-db-instance-with-per-tenant-row-level-security) instead of userContext filters can solve this?

**Comment by paveltiunov** [comment]
@tobilg Hey Tobi! That's correct!
