### ISSUE TITLE
Option to renew queries in caching layer every defined interval period

### ISSUE THREAD

**Issue by psharma0789** [cube-js/cube.js#884]
Hi,

Is there an option to for a query to renew in the caching layer in the background by a defined interval. For example: the system would look at all cached queries and automatically renew every hour, day, etc. This would keep data fresh in the cache.

**Comment by vasilev-alex** [comment]
hey @psharma0789! I believe you looking for https://cube.dev/docs/caching#keeping-cache-up-to-date

**Comment by psharma0789** [comment]
Hi @vasilev-alex ! This only seems to be for pre aggregations, correct?

**Comment by jcw-** [comment]
> This only seems to be for pre aggregations, correct?

Nope! The CRON job technique in the first paragraph would also keep the redis cache fresh as well.

**Comment by vijsai** [comment]
@jcw- I think that the CRON job needs to execute the queries as if the frontend calls them with "renewQuery: true" flag. Is there any example available? I searched enough and couldn't find a solution.

**Comment by jcw-** [comment]
That's right - you would mimic the same queries that your dashboard is making, and include `renewQuery:  true`, as documented here: https://cube.dev/docs/query-format#query-properties

An example of making a query is here: https://cube.dev/docs/@cubejs-client-core#cubejs-api-load

A more specific version of that would be something like this:
```
import cubejs from '@cubejs-client/core';

const cubejsApi = cubejs('CUBEJS_TOKEN');

const resultSet = await cubejsApi.load({
 measures: ['Stories.count'],
 timeDimensions: [{
   dimension: 'Stories.time',
   dateRange: ['2015-01-01', '2015-12-31'],
   granularity: 'month'
  }],
 renewQuery: true
});
```
