### ISSUE TITLE
MSSQL: limit and offset cannot be used together in a query

### ISSUE THREAD

**Issue by ykphuah** [cube-js/cube.js#891]
**Describe the bug**
When the limit and offset parameter is used together in a query, the SQL generated for MSSQL will be something like this:
SELECT TOP 20 ..... OFFSET 20 ROWS
which will return the error:  A TOP can not be used in the same query or sub-query as a OFFSET.

**To Reproduce**
1. Create a query that uses both "limit" and "offset" parameter on MSSQL

**Expected behavior**
It is able to return results!

**Version:**
0.19.47

**Additional context**
The issue can be resolved by a patch to the cubejs-schema-compiler/adapter/MssqlQuery.js file:

```
  groupByDimensionLimit() {
    if (this.rowLimit) {
      return this.offset ? ` OFFSET ${parseInt(this.offset, 10)} ROWS FETCH NEXT ${parseInt(this.rowLimit, 10)} ROWS ONLY` : '';
    } else {
      return this.offset ? ` OFFSET ${parseInt(this.offset, 10)} ROWS` : '';
    }
  }

  topLimit() {
    if (this.offset) {
      return '';
    }
    return this.rowLimit === null ? '' : ` TOP ${this.rowLimit && parseInt(this.rowLimit, 10) || 10000}`;
  }

```
When we need both rowLimit and also offset, we need to use the FETCH NEXT xx ROWS ONLY method.

**Comment by vasilev-alex** [comment]
hey @ykphuah, thanks for positing this! Would be nice if you could create a PR.

**Comment by ykphuah** [comment]
I have created a PR #908, I am new to cubejs dev, not sure how to go around adding Tests, I see MSSqlDbRunner.js but there seems like no tests for the two functions groupByDimensionLimit and topLimit?
