### ISSUE TITLE
Not able to install new version 0.19.54

### ISSUE THREAD

**Issue by Ananya-96** [cube-js/cube.js#892]
**Error during npm install**
Postinstall: ngcc error occurs while trying to install the new version. 0.19.53 works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/24409739/88270513-64e3ee80-ccf3-11ea-9feb-aadd3664d3e5.png)

**Version:**
0.19.54

**Comment by paveltiunov** [comment]
Hey @Ananya-96 ! This one should be fixed right now. Could you please check?

**Comment by Ananya-96** [comment]
It's working fine. Thanks for the update.
