### ISSUE TITLE
Querying against dynamic schemas

### ISSUE THREAD

**Issue by marcospassos** [cube-js/cube.js#904]
Hi everyone!

We're exploring analytics frameworks, and we stumbled upon Cube.js that seems very promising.

**Problem**

We allow our users to define their customers' custom attributes (domain-specific), such as `favorite_colors` or `preferred_songs`. Those attributes are stored in a JSON column using Postgres. As a multitenancy platform, we'd like to allow our users to create custom reports based on these custom attributes.

Does Cube.js support JSON-based dynamic columns? Is there any example on how to configure a cube for this purpose?

**Comment by paveltiunov** [comment]
Hey @marcospassos ! Here's resources which should help you with that: https://cube.dev/docs/schema-generation#top,  https://cube.dev/docs/schema-execution-environment#async-module and https://cube.dev/docs/multitenancy-setup#multiple-schema-and-drivers.
