### ISSUE TITLE
Query or User variable 

### ISSUE THREAD

**Issue by hanavarrete** [cube-js/cube.js#911]
**Problem**

Hi everyone! We're building an internal analytics tool, and we are very impressed with Cube.js.

Our situation is that we have the same schema on multiple tables, depending on the user (also, the name of each table has a prefix depending on the user so that way we can map where to query). For example,
```
cube(`Example`, {
  sql: `SELECT * FROM ${VARIABLE}_example`, ....
```

Does Cube.js supports user variables? Is there any example on how to configure backend and client for this?
I found https://cube.dev/docs/cube#context-variables-user-context but is not clear for me how to use it on the client side.

**Comment by vasilev-alex** [comment]
hey @hanavarrete! You may be looking for https://cube.dev/docs/multitenancy-setup#user-context-vs-multitenant-compile-context
