### ISSUE TITLE
Blank page while use Bizcharts visualizations

### ISSUE THREAD

**Issue by Kozhay** [cube-js/cube.js#918]
**Describe the bug**
Blank page while trying to use: Bar, Area or Pie from Bizchart. (Table, line, and number is OK)

**To Reproduce**
1. Go to Explore tab
2. Set any measure and dimension
3. Choose viz. type Bar, Area or Pie
4. Blank page
5. Reload page

**Expected behavior**
Page doesn't blank when I choose one of these visualizations. Charts have built.

**Screenshots**
Screencast: https://gyazo.com/2205d793ef12cdbc1e1fb31796c44b79

**Version:**
VM on Google Cloud, Debian 10, Cubejs v0.19.55, Node.js v10.21.0, React dynamic app, Bizcharts

**Comment by vasilev-alex** [comment]
hi @Kozhay! Yeah, looks like the `Geom` component was given wrong types.
