### ISSUE TITLE
Can't start dahsboard-app

### ISSUE THREAD

**Issue by cb1544** [cube-js/cube.js#919]
Hello,

I deployed cube js, I was able to add a schema. Then I added a dashboard using the example Dynamic Dashboard with React, AntD, and Recharts. Once I tried to run the dashboard app I'm getting this error :

** react-scripts start

Attempting to bind to HOST environment variable: x86_64-apple-darwin13.4.0
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://bit.ly/CRA-advanced-config

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND x86_64-apple-darwin13.4.0
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1485:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:17) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'x86_64-apple-darwin13.4.0'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dashboard-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dashboard-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
**

Any idea how to fix this please ?
Thank you !

**Comment by vasilev-alex** [comment]
Hey @cb1544!

Could you please check out the first answer here https://stackoverflow.com/questions/44826017/create-react-app-error. That might be your case.
