### ISSUE TITLE
Support for more Granularities (Quarter, decade, etc)

### ISSUE THREAD

**Issue by aslaksm** [cube-js/cube.js#930]
Currently supported granularities:
- Hour
- Day
- Week
- Month
- Year

Having a `Quarter` granularity would be very useful. Others might be useful as well(?).
A workaround now is to `date_trunc` the relevant timestamped fields with the desired granularity, but it's not ideal.

**Comment by paveltiunov** [comment]
Hey @aslaksm ! Thanks for posting this! We already have it here: #177
