### ISSUE TITLE
how to determine backlog/remaining/outstanding at a point in time

### ISSUE THREAD

**Issue by JoshMentzer** [cube-js/cube.js#932]
**Is it possible to ...**

We use cube.js for service performance dashboards, among other things.  One thing we would like to be able to report on is at any particular point in time, how many issues were open.  Using various combinations of rollingWindow trailing unbounded and FILTER_PARAMS I've managed to get a specific date range answered (e.g. if I say only 'last month' I can get an answer to how many were outstanding at the end of the month), but looks like with any granularity set it isn't accurate or it errors.
Outcome looking for would be something like a month granularity query resulting as such

|Date   |Issues Opened  | Issues Closed  | Backlog  |
|---|---|---|---|
|  6/1 | 10  | 10  | 30  |  
|  7/1 | 15 | 20  | 25  |  
|  8/1 | 20  | 30  | 15  |  

Use case is it provides a singular value that you can see the delta on, sort of answering the question of whether a group is falling behind, burning down, or staying flat.  Can be a leading indicator to service performance issues, etc.
Anyone else done anything similar; should I be able to accomplish this and is user error? ;)

**Comment by dvins** [comment]
I think you want to construct a window clause with an aggregate where the range is unbounded preceding?

**Comment by JoshMentzer** [comment]
> I think you want to construct a window clause with an aggregate where the range is unbounded preceding?

I think so?  The challenge seems to be whenever you do a query like this is creates a date_from and date_to; however it doesn't appear that those date_from's and to's are available to utilize other than against the original filtered date.
For example; if I do a 'last 3 months' by openedDate - it'll form the date_from and date_to data set as a table; join that to the 'task' table where opened at within those date_from and to groupings.  However, if I have a measure that needs to look back filtered on 'closedDate' - i.e. an item as or is open in the date_from/to range and within that range it was still not closed.. that is what I don't appear to be able to figure out a way to answer.

**Comment by rpaik** [comment]
Moving this discussion to the Discourse forum at https://forum.cube.dev/t/determining-backlog-remaining-outstanding-at-a-point-in-time/81.

Closing this issue here.
