### ISSUE TITLE
Add SSL and unix socket support for MySQL driver

### ISSUE THREAD

**Issue by davemaier** [cube-js/cube.js#939]
**Is your feature request related to a problem? Please describe.**
To connect do a hosted mysql db I need ssl support, for testing I need unix socket support. The current mysql-driver doesn't have ssl and unix socket support.

**Describe the solution you'd like**
Since the library used to connect to the mysql db supports both requirements, it should be easy to add them by just reading the required environment variables from dotenv. The process should be quite similar to how it is solved in the postgres driver. If a socket is provided in dotenv, the host and port related variables should be ignored (this is also the default behavior of the mysql npm package. 

**Describe alternatives you've considered**
It might be possible to use something like ProxySQL to connect to remote mysql server, but the proposed solution would be much easier.

**Additional context**
I think I'll have some spare time this week and I will integrate this and add a PR.

**Comment by davemaier** [comment]
How can I push code change proposals? Looks like I don't have permissions to push a new branch.

**Comment by vasilev-alex** [comment]
> How can I push code change proposals? Looks like I don't have permissions to push a new branch.

You can read about that here https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ovr** [comment]
Thank you for your contribution,

We merged the PR with the fix and released a new version. I am going close to the issue.
