### ISSUE TITLE
Pre-Aggregation table does not exist when use ${CUBE_NAME}.sql()

### ISSUE THREAD

**Issue by Nathlmt** [cube-js/cube.js#951]
**Describe the bug**
I have 2 schemas **Events** and **Funnels**. In Events I define originalSql preAggregations 
```
main: {
        type: `originalSql`,
        indexes: {
          main: {
            columns: ['anonymous_id']
          }
        }
      },
```
and in Funnels schema I query 
```select anonymous_id, timestamp from ${Events.sql()} AS e where e.event = '${event}' ORDER BY anonymous_id LIMIT 1000```
but I received an error 

> Error: relation "stb_pre_aggregations.events_main" does not exist

**Version:**
    "@cubejs-backend/postgres-driver": "^0.19.54",
    "@cubejs-backend/server": "^0.19.55"
     "postgresql": "10"

**Comment by paveltiunov** [comment]
@Nathlmt Hey Nath! Thanks for posting this! Could you please provide your schema in full?

**Comment by Nathlmt** [comment]
**Events**
`
cube(`Events`, {
    sql:
        `
       SELECT
        t.id || '-e' as event_id
        , t.anonymous_id as anonymous_id
        , t.timestamp
        , t.event
        , NULL as page_path
      from glot_mobile_tracks as t
  
      UNION ALL
  
      SELECT
        p.id as event_id
        , p.anonymous_id
        , p.timestamp
        , 'screen' as event
        , p.name as page_path
      FROM glot_mobile_screens as p
      `,
    joins: {
        Sessions: {
          relationship: `belongsTo`,
          sql: `
            ${Events}.anonymous_id = ${Sessions}.anonymous_id
            AND ${Events}.timestamp >= ${Sessions}.session_start_at
            AND (${Events}.timestamp < ${Sessions}.next_session_start_at or ${Sessions}.next_session_start_at is null)
          `
        },
        Users: {
          relationship: `belongsTo`,
          sql: `
            ${Events}.anonymous_id = ${Users}.anonymous_id
          `
        }
      },
    measures: {
        count: {
            sql: `event_id`,
            type: `count`
        },
        activeUser: {
          sql: `anonymous_id`,
          type: `countDistinct`
        },
        pageViewsCount: {
            sql: `event_id`,
            type: `count`,
            filters: [
                { sql: `${CUBE}.event = 'screen'` }
            ]
        },
        lastEventTimestamp: {
            sql: `timestamp`,
            type: `max`,
            shown: true
          }
    },
    dimensions: {
        timestamp: {
            sql: `timestamp`,
            type: `time`
        },
        anonymous_id: {
            sql: `anonymous_id`,
            type: `string`
        },

        eventId: {
            sql: `event_id`,
            type: `number`,
            primaryKey: true
        },

        event: {
            sql: `event`,
            type: `string`
        }
    },
    preAggregations: {
      main: {
        type: `originalSql`,
        indexes: {
          main: {
            columns: ['anonymous_id']
          }
        }
      },
      eventByDay: {
        type: `rollup`,
        measureReferences: [count, pageViewsCount, lastEventTimestamp, activeUser],
        timeDimensionReference: timestamp,
        granularity: `day`,
        useOriginalSqlPreAggregations: true
      }
    }
});
`
**Funnels**
const Funnels = require(`Funnels`);
const { steps }  = COMPILE_CONTEXT;
const jsonSteps = JSON.parse(steps);
const character = ['a','b','c','d','e','f','g']
asyncModule(async () => {
  console.log();
cube(`WatchVideo`, {
  extends: Funnels.eventFunnel({
    userId: {
      sql: `anonymous_id`
    },
    time: {
      sql: `timestamp`
    },     
    steps: jsonSteps.map((event, index) => ({
      name: `${character[index]}-${event}`,
      eventsView: {
        sql: `select anonymous_id, timestamp from ${Events.sql()} AS e where e.event = '${event}' ORDER BY anonymous_id LIMIT 1000`
      }
    })
    )
  }),
  preAggregations: {
    main: {
      type: `originalSql`
    }
  }
}); 
})

**Comment by Nathlmt** [comment]
> @Nathlmt Hey Nath! Thanks for posting this! Could you please provide your schema in full?

Here my schema

**Comment by paveltiunov** [comment]
@Nathlmt Did you have a chance to resolve this one?
