### ISSUE TITLE
Specifying `dateRange` in time dimension should produce same result as `inDateRange` in filter

### ISSUE THREAD

**Issue by emmanuel** [cube-js/cube.js#962]
## Describe the bug

When querying a cube with a time dimension, the behavior is different when specifying a filter on the time dimension via the `dateRange` option of the time dimension, vs specifying the same constraint as a `filter` with an `inDateRange` operator.

In the case of a `filter` with an `inDateRange` operator, the upper endpoint of the date range is directly cast to a `timestamptz` (with a PostgreSQL backend); e.g.,

```
{"query":{..., "filters":[{"dimension":"...","operator":"inDateRange","values":["2020-08-01","2020-08-10"]}], ...}
```

Results in:

```
{"query":"... WHERE (... >= $1::timestamptz AND ... <= $2::timestamptz)","params":["2020-08-01","2020-08-10"],...}
```

On the other hand, when using a time dimension with a `dateRange` specification, the date value provided in the API request is converted to the final second of the given day of the upper end of the date range; e.g.,

```
{"query":{"measures":["..."],"order":{},"dimensions":[],"filters":[],"timeDimensions":[{"dimension":"...","granularity":"day","dateRange":["2020-08-01","2020-08-10"]}]}
```

Results in:

```
{"query":"... WHERE (... >= $1::timestamptz AND ... <= $2::timestamptz)","params":["2020-08-01T00:00:00Z","2020-08-10T23:59:59Z"], ...}
```

## Expected behavior

Both `inDateRange` on `filter` and `dateRange` on `timeDimension` would behave the same for time dimensions.

## Version:

0.19.55

**Comment by vasilev-alex** [comment]
hey @emmanuel! Yep, we need to fix it. Thanks for posting this one!
