### ISSUE TITLE
Native elasticsearch driver traverseAggregations issue

### ISSUE THREAD

**Issue by vignesh-123** [cube-js/cube.js#986]
**Describe the bug**

**To Reproduce**
When we use the elastic driver in the below format
```
export const cubejs = CubeJsServerCore.create({
  devServer: true,
  telemetry: false,
  schemaPath: "./src/schema/",
  dbType: "elasticsearch",
  apiSecret: "RANDOM_CUBEJS_SECRET",
  driverFactory: () =>
    new ElasticDriver({
      url: "http://username:password@elasticIP:9200/",
      openDistro: false,
      dialect: "elasticsearch",
    })
});
```
The data returned from elastic will be in the format of rows and columns 
But the transformer for such data is set up only when the cloud key is present in the config. Which is not a necessary parameter 
```
      // TODO: Clean this up, will need a better identifier than the cloud setting
      if (this.config.cloud) {
        const compiled = result.rows.map(
          r => result.columns.reduce((prev, cur, idx) => ({ ...prev, [cur.name]: r[idx] }), {})
        );

        return compiled;
      }
```

The code fails because of this
I see there is a comment line on it saying 'needs be cleaned up'. I can help
If we can set up one more parameter in the driver for mentioning what type of elastic we are going to use, it will solve the problem

**Comment by vasilev-alex** [comment]
Hey @vignesh-123! Looks like `CUBEJS_DB_TYPE` is already used for that `packages/cubejs-server-core/core/index.js:33`

Would be nice if you could create a PR.

**Comment by vignesh-123** [comment]
Sure will do

**Comment by dylman79** [comment]
See comments on PR re: use of api and external setting - @vignesh-123 I am happy to close mine but suggest we use the api as intended and also allow for setting for external as well as config
