### ISSUE TITLE
"Request Timeout" when running Cube.js on AWS Lambda

### ISSUE THREAD

**Issue by cbroome** [cube-js/cube.js#987]
**Problem**

I'm setting up Cube.js for the first time in Lambda. I was able to get everything set up such that a request to `/meta` returns as expected. However when actually querying Athena all requests are timing out. 

Looking in the CloudWatch logs, the only error getting recorded is: 
```
/bin/sh: hostname: command not found
```
It seems this specific issue was addressed in v0.10.59. Locally I'm running v0.19.51. cubejs-backend/athena-driver, cubejs-backend/server, cubejs-backend/serverless, cubejs-backend/serverless-aws--are all at v0.19.61

Any idea what can be causing this, or if the hostname error is a red herring? 

Thanks.

**Comment by paveltiunov** [comment]
@cbroome Hey Chris! Please see https://stackoverflow.com/questions/60943814/error-continue-wait-issue-on-cube-js-backend.

**Comment by cbroome** [comment]
Thanks @paveltiunov it turned out to be an access issue with Redis. The hostname error was in fact a red herring.

**Comment by duncanmapes** [comment]
@paveltiunov any suggestions on how to solve when you've confirmed that the internet is reachable?
