### ISSUE TITLE
Presto offset with limit are in the wrong order 

### ISSUE THREAD

**Issue by Ulimo** [cube-js/cube.js#988]
**Describe the bug**
If you try to use offset with at least the presto connector you gain a user error from presto.

The SQL statement is: "select ... from ... limit ? offset ?" 

**To Reproduce**
Send in any query that uses the offset with the presto adapter.

**Expected behavior**
A sql statement should generate that looks like: "select ... from ... offset ? limit ?".

**Version:**
0.19.61

**Additional context**
I looked at the code and you should only need to change place of the offset and the limit. I had some troubles compiling locally so I cant send in a PR my self at the moment.

**Comment by paveltiunov** [comment]
Hey @Ulimo ! Thanks for posting this one!
