### ISSUE TITLE
Schema Generation & Dynamic Schema Generation

### ISSUE THREAD

**Issue by FinnONeill** [cube-js/cube.js#991]
Hi all,

**Background**
I have just created a new project and am using the mongodb setup. I have uploaded my data to the database and a single entry looks something like this:

```json
{
    "_id" : ObjectId("5f352ed7d94b216e79398d0d"),
    "Game" : "A01 Barndoorl",
    "Name" : "John Smith",
    "In_Possession_Gain_Line_Carry" : 3,
    "In_Possession_Non_Gain_Line_Carry" : 2,
    "In_Possession_Linebreak" : 0,
    "Ruck_BC_Double_Effort" : 4,
    "Ruck_BC_No_Effort" : 3,
    "Ruck_Effective_Bullet" : 4,
    "Ruck_Non_Effective_Bullet" : 2,
    "Ruck_Strong_Gun" : 7,
    "Ruck_Weak_Gun" : 0,
    "Tackling_Dominant_Tackle" : 1,
    "Tackling_Chop_Tackle" : 0,
    "Tackling_Soak_Tackle" : 1,
    "Tackling_Tackle_Assist" : 0,
    "Tackling_Missed_Tackle" : 1,
    "Tackling_Bounce_To_Feet" : 0,
    "Tackling_Logging" : 1,
    "In_Possession_Sucessful_Pass" : 2,
    "In_Possession_Unsucessful_Pass" : 0,
    "In_Possession_Sucessful_Offload" : 0,
    "In_Possession_Unsucessful_Offload" : 0,
    "Handling_Errors" : 0,
    "Total_Involvements" : 31,
    "Ineffective_Involvement" : 10,
    "Percentage_Effectiveness" : "68%"
}
```

**The Problem**
The problem I'm having is when I run the generate command to create the schema, I'm only getting the fields that are of type string being created and none of the number fields are created. I know I can manually create these but I plan to add the ability to let users upload data (similar to power bi or tablaeu) and I'd like to know if I can dynamically create schemas.

```jsx
cube(`PlayerPerformance`, {
  sql: `SELECT * FROM rugby.\`playerPerformance\``,
  
  joins: {
    
  },
  
  measures: {
    count: {
      type: `count`,
      drillMembers: [name]
    }
  },
  
  dimensions: {
    percentageEffectiveness: {
      sql: `${CUBE}.\`Percentage_Effectiveness\``,
      type: `string`
    },
    
    game: {
      sql: `${CUBE}.\`Game\``,
      type: `string`
    },
    
    name: {
      sql: `${CUBE}.\`Name\``,
      type: `string`
    }
  }
});

```

**Comment by Levhav** [comment]
Hi, @FinnONeill 
Could you please elaborate on your use case?

Possibly you should see docs about [execution environment](https://cube.dev/docs/schema-execution-environment), It looks like something similar for your task.

**Comment by Levhav** [comment]
Hi, @FinnONeill 
Did you solve your problem? If yes, could you please share your solution here?
Thanks.
