### ISSUE TITLE
count hierarchical(tree) data

### ISSUE THREAD

**Issue by DmytroShyshko** [cube-js/cube.js#994]
**Problem**

There are tables 'Users' and 'Departments'
'Users' has fields 'id', 'name', 'department_id'
'Departments' has fields 'id', 'name', 'parent_dep_id'
Suppose we have this structure in departments:
```
dep1
    sub_dep2
        sub_dep3
            sub_dep_4
        sub_dep_5
dep_6
    sub_dep_7
```
Each dep or sub_dep can have users
Question 1: How many departments has sub_dep2. Answer will be 3(sub_dep3 and sub_dep4 and sub_dep5)
Question 2: How many users has sub_dep2. Answer will be users from sub_dep2 + sub_dep3 + sub_dep4 + sub_dep5

**Comment by paveltiunov** [comment]
Hey @DmytroShyshko ! Great question! What database do you have?

**Comment by DmytroShyshko** [comment]
MySql

**Comment by JoshMentzer** [comment]
Interested in this as well; we have this same situation in MSSQL databases.  Some of the source systems, thankfully, had tables that were already setup and kept up to date with the full breadcrumb for each hierarchy; others do not though - in those cases we've end up creating a view with a recursive CTE that creates the hierarchy and using that view as a cube (performance isn't great though - only really a good user experience if the resulting dimensions are pre-aggregated with their measures).

**Comment by paveltiunov** [comment]
@DmytroShyshko @JoshMentzer Recursive CTE is indeed way to go in this case. You'd need to pre-calculate count of children and other properties for each node in tree and then pre-aggregate it using `originalSql` for example. Recursive CTE doc for reference in MySQL: https://dev.mysql.com/doc/refman/8.0/en/with.html#common-table-expressions-recursive-examples.

**Comment by DmytroShyshko** [comment]
i have this CTE: 
`with recursive subnodes as (
    select * from departments
    where id = 195
    union
    select child .*
    from departments as child, subnodes as parent
    where child.parent_id = parent.id
)
select * from  subnodes`
but how can i use it with `originalSql` if i pass id from client?
or for each node i need to create separate cube?
@paveltiunov can you share example of cube schema?

**Comment by paveltiunov** [comment]
@DmytroShyshko You need to calculate `originalSql` for every possible input node id. Basically, you'd need to materialize whole tree.
