### ISSUE TITLE
custom JWT support in the Playground

### ISSUE THREAD

**Issue by Ankcorn** [cube-js/cube.js#998]
**Is your feature request related to a problem? Please describe.**
When using the checkAuth method to verify it becomes more difficult to use the playground.

**Describe the solution you'd like**
Ability to easily add a JWT to the playground to build queries for our various users and test our multitenancy auth setup.

**Describe alternatives you've considered**

We currently work around this by using an environment variable in the checkAuth option to replace the JWT passed in via the auth argument. Modifying our authentication to enable development works well but it feels like it could be an area where we have introduced risk by adding extra code paths to something reasonably crucial to protecting our user's data.

**Additional context**
Our JWT expiry time is around 1 hour so we are fine with manually refreshing the jwt in the playground.

**Comment by jcw-** [comment]
FYI, we also work around this, but slightly differently - by using a `queryTransformer` on dev to set `context.authInfo.u` to something.

**Comment by Ankcorn** [comment]
Oh Nice! That actually makes a lot of sense.
